.gitignore
run.py
suites/ocs_basic_install.yml
templates/install-config.yaml.j2
tests/test_ocs_basic_install.py

Note that this includes some temporary changes to run.py to allow execution of the test case. Further changes to run.py will remove ceph specific functionality that is no longer needed.

Initial implementation of OCP install test

---

README.md

Add initial README and update as more work gets done.

---

oc/Exceptions.py
oc/pod.py
oc/pod_exec.py
tests/test_bench.py
tests/test_pod_exec.py
tests/test_radosbench.py

Also few command exec related changes.
Since exec rest api is not returning err code for
command execution, we have to rely on shell to get
err code.

[ocs-ci]:Add radosbench task

---

oc/Exceptions.py
oc/pod.py
oc/pod_exec.py
tests/test_bench.py
tests/test_pod_exec.py
tests/test_radosbench.py

Addressed flake8 failures, tox is passing

---

ocsci/enums.py
ocsci/framework.py
run.py
utility/utils.py

TestCase class for runner to utilize per test in suite

---

tests/test_ocs_basic_install.py

Cause they changed the path of installer, changed also here.

Fix new url for download installer

---

run.py
utility/utils.py

DEBUG level by default for file handler and INFO level for stream
console handler

Fixing logging in OCS-CI

---

run.py

Fixed:
- jenkins_rc value at the end of the run
- suite config value being passed to TestCases
- test abort_on_fail scenario condition

jenkins_rc value and other fixes

---

ocs/defaults.py
tests/test_ocs_basic_install.py

Added INSTALLER_VERSION
and few more code guidelines fixes

Add defaults.py file

---

oc/openshift_ops.py
ocs/defaults.py
ocs/pod.py
ocs/rook.py
tests/test_rook_cluster.py

Introducing 3 commits for Rook infrastructure class and related changes along with a simple test.

Wip rook infra changes

---

docs/getting_started.md

Update prerequisites section for additional requirement

---

ocs/defaults.py

Append username to default ocs installations

---

oc/openshift_ops.py
ocs/api_client.py
ocs/defaults.py
tests/test_api_client.py

This PR has 2 commits. 
1. Which handles the api-client configurations at run time
2. A simple test for api-client infrastructure

Configurable api client

---

ocs/defaults.py
ocs/exceptions.py
ocs/ocp.py
setup.py
suites/basic_testing.yml
templates/ocs-deployment/PersistentVolume.yaml
templates/ocs-deployment/cephfilesystem.yaml
tests/test_add_mds_to_cluster.py
tests/test_pv_creation.py
utility/templating.py
utility/utils.py

This is 2 new tests - please review

Implementing issue#48 and adding 2 new test cases

---

conf/ocs_basic_install.yml
docs/usage.md
ocs/defaults.py
ocs/utils.py
templates/ocs-deployment/common.yaml
tests/test_ocs_basic_install.py

This patch implements the easier way how to overwrite the variables for
rendering the templates.

Implement the easier way how overwrite vars

---

docs/getting_started.md

Fixing the command for create venv in doc

---

docs/README.md
docs/code_review.md

Improved docs about the application for WIP and the tox command.

Improve the documentation for contribution

---

templates/ocs-deployment/storage-manifest.yaml

Fixing https://github.com/red-hat-storage/ocs-ci/issues/78

fix of typo in storage-manifest.yaml

---

tests/test_ocs_basic_install.py

tests/test_ocs_basic_install.py -- Added func parallel() to create_ebs_volumes() to create and attach volumes to the worker node in parallel

parallel() func to do ops in parallel

---

templates/ocs-deployment/storage-manifest.yaml

Changed the failure domain from OSD to host and updated the replica_size to 3 in jinja template

Updating storage-manifest.yaml with failure domain and replica_size

---

ocs/ocp.py
suites/basic_testing.yml
tests/test_add_mds_to_cluster.py
tests/test_pv_creation.py
utility/utils.py

Something similar to:
https://github.com/openshift/openshift-restclient-python#watch

Add wait() method

---

pytest_customization/ocscilib.py

Fix issue with naming cluster

---

pytest.ini

fixing https://github.com/red-hat-storage/ocs-ci/issues/108

isolate unittests from ocs test runs

---

LICENSE
setup.py

Add License and update setup.py for license and author

---

conf/ocs_basic_install.yml

Fix for https://github.com/red-hat-storage/ocs-ci/issues/121.

changing the number of worker node count from 6 to 3

---

docs/getting_started.md

Mention clone of repository before run pip install cmd.

Fixing issue #66

---

conf/ocsci/default_config.yaml
ocs/defaults.py
ocs/exceptions.py
resources/base_resource.py
resources/ceph_file_system.py
resources/persistent_volume_claim.py
resources/secret.py
resources/storage_class.py
templates/ocs-deployment/PersistentVolumeClaim_new.yaml
templates/ocs-deployment/cephfilesystem_new.yaml
tests/test_add_mds_to_cluster.py
utility/templating.py

- Creating classes for few kinds
- Change direction and using yaml files directly (no jinja2)
- work with dict() directly from yaml

Design kind classes

---

unittests/README.md

fixing part. of https://github.com/red-hat-storage/ocs-ci/issues/114

add README file for unittests dir

---

ocsci/pytest_customization/README.md

part. fixing https://github.com/red-hat-storage/ocs-ci/issues/114

add a readme file for pytest_customization dir

---

docs/writing_tests.md
ocs/constants.py
ocs/defaults.py
ocs/kinds.py
ocs/rook.py
ocs/volumes.py
resources/pod.py
resources/pvc.py
resources/secret.py
resources/storage_class.py
tests/ecosystem/deployment/test_ocs_basic_install.py
tests/helpers.py
tests/test_add_mds_to_cluster.py
tests/test_pv_creation.py
utility/templating.py

Created constants module. Moved constant vars from defaults and kinds modules to new module. #161

Constants module

---

ocs/constants.py
ocs/defaults.py
ocs/ocp.py
resources/ocs.py
resources/pod.py
templates/CSI/rbd/pod.yaml
templates/CSI/rbd/storageclass.yaml
templates/ocs-deployment/cephblockpool.yaml
tests/fixtures.py
tests/helpers.py
tests/manage/test_pvc_deletion_during_io.py
unittests/test_defaults.py

Continuation of https://github.com/red-hat-storage/ocs-ci/pull/69

New test case - OCS371 - Delete PVC while I/O is in progress

---

ocs/defaults.py

See https://github.com/red-hat-storage/ocs-ci/pull/183

Fix mismatched default for OSP release

---

ocs/constants.py
ocs/defaults.py
resources/pod.py
resources/pvc.py
tests/helpers.py
tests/manage/ocs_288.py

1:- Fixed cephfs storageclass creation in tests.helpers
2:- Made changes to testscript to use latest changes made in ocs-ci
3:- Log http://pastebin.test.redhat.com/770626

TestCase OCS-288 creating pvc with random sc

---

ocs/defaults.py

See https://github.com/red-hat-storage/ocs-ci/pull/182

Fix mismatched ceph image defaults

---

utility/utils.py

Adding a method which can be used to run a command and check the status and result of the command at a later point of time.
Issue #225

Method to execute command in an asynchronous way

---

ocs/constants.py
ocs/exceptions.py
resources/pod.py
tests/manage/test_pvc_delete_verify_size_is_returned_to_backendpool.py

This PR introduces test case OCS-372 and template files.
Need to make changes on running IO's method function and checking the reclaimed space before and after creating pvc.

OCS-372:Verify size is returned to backend pool after pvc delete

---

resources/pvc.py

* Fixes #235
* Most useful in cases where more than one PVC has to be created

Method to create one or more PVC

---

tests/helpers.py

Fix storageclass creation for cephfs

---

ocsci/pytest_customization/marks.py
utility/environment_check.py

Ignore env checker for deployment and destroy.

---

ocs/ocp.py

*Switch to another project
*Switch to default project
Fixes #223

Methods to switch between projects

---

templates/CSI/rbd/storageclass.yaml
tests/helpers.py

- Updated create_storage_class() with storageclass template update of rbd csi
templates/CSI/rbd/storageclass.yaml
- Updated template storageclass.yaml as per issue #242 

Update helpers.py and storageclass.yaml of rbd csi

---

setup.py

- Updated kubernetes version to latest

Update kubernetes version to latest

---

ocsci/main.py
run_ocsci.py

* configure `PATH` based on configuration `RUN['bin_dir']`

Configure PATH from configuration

---

tests/manage/test_ocs_324.py

This PR addresses #262 and update the test tier.

Update: tests/manage/test_ocs_324.py

---

conf/README.md
conf/ocsci/default_config.yaml
ocsci/__init__.py
ocsci/main.py
ocsci/pytest_customization/tests/test_pytest.py
ocsci/tests/test_config.py
ocsci/tests/test_main.py

This is marked as a WIP because I still want to update docs.

Move config initialization to Config class

---

tests/test_cluster_utils.py

Fix issue with collection with wrong class member

---

tests/test_pvc_concurrent_deletion_creation.py

Test case to verify concurrent deletion and creation of multiple PVCs

---

docs/getting_started.md
docs/usage.md
ocs/ocp.py
ocsci/main.py
ocsci/pytest_customization/ocsci_logging.py
ocsci/pytest_customization/ocscilib.py
ocsci/pytest_customization/reports.py
setup.py
utility/utils.py

Email Reporting
This PR includes the following things:
* create html reports
* parse html reports 
* generate run_id for every test run
* sending emails about test run results

Email reports

---

tests/conftest.py

- Auto use fixture added
- Fixed project-id property name
- Added custom polarion property for description to add jenkins build URL

Add autouse fixture for polarion project ID

---

ocs_ci/ocs/ocp.py

Add option to return raw_output from oc run_cmd

---

ocs_ci/ocs/constants.py
ocs_ci/templates/CSI/cephfs/secret.yaml
ocs_ci/templates/CSI/cephfs/storageclass.yaml
ocs_ci/templates/CSI/rbd/secret.yaml
ocs_ci/templates/CSI/rbd/snapshotclass.yaml
ocs_ci/templates/CSI/rbd/storageclass.yaml
ocs_ci/templates/ocs-deployment/csi/cephfs/csi-provisioner-rbac_cephfs.yaml
ocs_ci/templates/ocs-deployment/csi/rbd/csi-nodeplugin-rbac_rbd.yaml
ocs_ci/templates/ocs-deployment/csi/rbd/csi-provisioner-rbac_rbd.yaml
ocs_ci/templates/ocs-deployment/operator-openshift-with-csi.yaml
tests/helpers.py

This PR addressed #317 
Corresponding changes doen in helpers.py as well.
Tested following:
1. Fresh deployment (due tochanges in rbac files and operator-openshift-with-csi.yaml)
2. Create sc, secret (admin user) , pvc and pod

Fix for Issue-317

---

tests/conftest.py

Don't leak the pull secret!

---

tests/manage/test_pvc_delete_verify_size_is_returned_to_backendpool.py

Commenting the validation pv exists in backend since it fails due to bug

---

ocs_ci/framework/conf/default_config.yaml
ocs_ci/framework/pytest_customization/ocscilib.py

Use first 8 chars of username for default cluster_name

---

tests/conftest.py

Add run_id to config

---

ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/ocs/defaults.py
ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/workload.py
ocs_ci/templates/workloads/fio/workload_io_rw.yaml
ocs_ci/utility/workloads/fio.py
tests/manage/test_pvc_deletion_during_io.py

- Added run_io() so it will be used as pod.obj.run_io()

Add FIO as a function to Pod object

---

tests/fixtures.py

Updating method create_cephfs_secret based on recent changes

---

tests/manage/test_remove_mon_from_cluster.py

Moving Testcase to manage directory

---

ocs_ci/ocs/resources/pvc.py
tests/manage/test_pvc_concurrent_deletion_creation.py

Enhancement: Using delete_all_pvcs for deleting PVCs
Also , Fixes #345 

Use delete_all_pvcs method to delete PVCs

---

tests/manage/test_remove_mon_from_cluster.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/360

fix cluster init

---

ocs_ci/templates/install-config.yaml.j2

Changing the API version from v1beta4 to v1.

update api version in the install config

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/ocp.py
ocs_ci/ocs/resources/pod.py
tests/manage/test_reclaim_policy.py

Adding the following tests
- OCP_Validate Reclamation policy 'Retain' policy is honored
- OCP_Validate Reclamation policy 'Delete' policy is honored

Adding tests OCS-383 & OCS-384

---

ocs_ci/ocs/ocp.py

This is to align with rook u/s testing

log yaml output to ocp.create() function

---

docs/usage.md
docs/writing_tests.md
ocs_ci/framework/pytest_customization/marks.py
setup.py

Add bugzilla integration

---

ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/utils.py
ocs_ci/utility/utils.py

This PR will enable us  to automatically collect OCS logs when a test case failed. It helps in filing bugs.

Collect OCS logs when a test case failed.

---

tests/fixtures.py

Ceph block pool may not exists, check before deleting

---

ocs_ci/utility/utils.py
tests/conftest.py
tests/ecosystem/destroy/test_destroy_cluster.py

Use pytest log_cli_level for openshift-installer log level

---

tests/manage/test_verify_rbd_based_rwo_pvc.py

Updating polarion id of test case test_rbd_based_rwo_pvc

---

ocs_ci/ocs/monitoring.py
ocs_ci/ocs/resources/pod.py
ocs_ci/utility/utils.py

Change yaml.load to yaml.safe_load

---

ocs_ci/utility/environment_check.py
setup.py

Fix environment checker print layout

---

tests/manage/test_run_io_multiple_pods.py

Add polarion IDs to run IO on multiple pods TCs

---

conf/ocs_basic_install.yml
ocs_ci/framework/conf/default_config.yaml
ocs_ci/framework/tests/test_config.py
ocs_ci/templates/CSI/rbd/storageclass.yaml
ocs_ci/templates/ocs-deployment/cluster.yaml
ocs_ci/templates/ocs-deployment/common.yaml
ocs_ci/templates/ocs-deployment/csi/cephfs/csi-node-plugin-psp_cephfs.yaml
ocs_ci/templates/ocs-deployment/csi/cephfs/csi-provisioner-psp_cephfs.yaml
ocs_ci/templates/ocs-deployment/csi/rbd/csi-node-plugin-psp_rbd.yaml
ocs_ci/templates/ocs-deployment/csi/rbd/csi-provisioner-psp_rbd.yaml
ocs_ci/templates/ocs-deployment/operator-openshift-with-csi.yaml
ocs_ci/templates/ocs-deployment/toolbox_pod.yaml
tests/conftest.py
tests/helpers.py

Synced yaml with upstream rook master

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/pvc.py
tests/helpers.py
tests/manage/test_create_pvc_random_storage_class.py
tests/manage/test_remove_mon_from_cluster.py

- Fixed depended script which were using function from helpers.py and pod.py

Fix for issue 384

---

tests/fixtures.py

We need to ensure to switch to the default project

Fixing new_project fixture

---

conf/ocsci/downstream_config.yaml
ocs_ci/templates/ocs-deployment/operator-openshift-with-csi.yaml

Ticket:
https://jira.coreos.com/browse/RHSTOR-150

Adding usage of CSI Ceph DS image

---

ocs_ci/framework/conf/default_config.yaml

Sync ceph image with upstream rook/master

---

tests/manage/pv_services/test_pvc_concurrent_deletion_creation.py

* Improved implementation using fixtures
* Improved teardown functionality
* Removed invalid validation of PV existance using ceph toolbox
* Added TODO for validating PV existence which is currently blocked by Bz 1723656
* Fixes #448
* Log improvement

 Test case enhancement and fix - test_multiple_pvc_concurrent_creation_deletion

---

ocs_ci/ocs/resources/pod.py
ocs_ci/utility/workloads/fio.py
ocs_ci/utility/workloads/helpers.py
ocs_ci/utility/workloads/jenkins.py
tests/e2e/test_jenkins_simulation.py

- Uses 'git clone' to simulate active user
- small fix to PVC object

Add "Jenkins" simulation workload

---

ocs_ci/ocs/constants.py
ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-csc.yaml
ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-namespace.yaml
ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-og.yaml
ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-sub.yaml
ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/instance.yaml
ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-csc.yaml
ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-og.yaml
ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-project.yaml
ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-rbac.yaml
ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-sub.yaml
ocs_ci/utility/deployment_openshift_logging.py

Deployment of openshift-logging

---

ocs_ci/utility/environment_check.py
setup.py

Fixing environment checker format and login

---

docs/code_review.md

update docs on how to address new review comments on old PR's

---

conf/ocsci/downstream_config.yaml
ocs_ci/framework/conf/default_config.yaml
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/utility/utils.py
tests/conftest.py

* add Test Run ID to html and email reports
(for example:  OCS_US_4-2_tier1)
* add folowing properties to xml jUnit report:
* polarion-testrun-id
* polarion-custom-plannedin
* polarion-testrun-status-id
fixes: https://github.com/red-hat-storage/ocs-ci/issues/409

update reporting (add Test Run ID to reports)

---

ocs_ci/deployment/deployment.py

and use cephfs/rbd as default storageclass.

patch gp2 ebs based storage class 

---

tests/manage/pv_services/test_verify_rbd_based_rwo_pvc.py

* Added wait time for verifying PV deletion
* Added sufficient timeout for second pod to be in Running state after deleting first pod

Adding wait time for PV and pod status check in test case

---

ocs_ci/deployment/aws.py
tests/conftest.py

Force download client and installer only when deploy

---

tests/manage/cluster/test_add_mds_to_cluster.py

Add bugzilla decorator to add_mds test case

---

tests/manage/noobaa/test_create_bucket.py

Skip NooBaa test

---

docs/fixture_usage.md

Correcting the link for test_fixtures in doc

---

tests/manage/pv_services/test_verify_rbd_based_rwo_pvc.py

Using create_project fixture in test_verify_rbd_based_rwo_pvc

---

tests/manage/storageclass/test_create_multiple_sc_with_same_pool_name.py

Adding  testcases OCS-622 and OCS-623 : Create multiple SC's with same pool name

Testcase: OCS-622 and OCS-623 Create multiple SC's with same pool name

---

tests/conftest.py

Add factory fixtures from https://github.com/red-hat-storage/ocs-ci/pull/418 so they can be used in new tests.

Add factory fixtures

---

ocs_ci/utility/environment_check.py

Remove secret from the environment checks

---

ocs_ci/deployment/aws.py
ocs_ci/ocs/node.py
ocs_ci/utility/aws.py
ocs_ci/utility/utils.py
tests/manage/cluster/nodes/base_node_ops.py
tests/manage/cluster/nodes/conftest.py
tests/manage/cluster/nodes/test_disk_failures.py
tests/manage/cluster/nodes/test_nodes_restart.py

- Test cases to detach and attach volume from worker node/s
- Modifications in aws.py: Separated create and attach volume and seperated detach and delete volume
- Modifications in tests/manage/cluster/nodes: moved the base class to a common file and the fixtures to conftest.py

Node disk failures

---

.editorconfig
.functional_ci_setup.py
Jenkinsfile

This is what we'll use to validate builds internally (it can also be used upstream).

Add a Jenkins pipeline definition

---

tests/conftest.py
tests/e2e/test_io_performance.py
tests/fixtures.py
tests/helpers.py

- Added a fixture to iterate over ceph interfaces
- Created generic fixtures to create resources based on interface

Generic fixtures for parametrize usage

---

ocs_ci/ocs/cluster.py
tests/manage/cluster/test_remove_mon_from_cluster.py

Signed-off-by: Shay Rozen <srozen@localhost.localdomain>

Fix test remove mon from cluster

---

ocs_ci/ocs/resources/pod.py
tests/e2e/test_pvc_creation_performance.py
tests/helpers.py

Time measurement for PVC creation

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/ripsaw.py
ocs_ci/templates/workloads/pgsql/server/ConfigMap.yaml
ocs_ci/templates/workloads/pgsql/server/Service.yaml
ocs_ci/templates/workloads/pgsql/server/StatefulSet.yaml

Ripsaw class to run various workloads and scale tests

---

ocs_ci/utility/utils.py

Parse pgsql benchmark data and return in readable format for scripts

---

tests/conftest.py
tests/e2e/test_pvc_creation_performance.py

- This will help tearing down resources that were created as part of the test

Add teardown factory

---

ocs_ci/ocs/defaults.py
ocs_ci/templates/CSI/cephfs/storageclass.yaml
ocs_ci/templates/CSI/rbd/snapshotclass.yaml
ocs_ci/templates/CSI/rbd/storageclass.yaml

Fix issue 562

---

ocs_ci/ocs/exceptions.py
ocs_ci/utility/utils.py

Wait for build extraction

---

ocs_ci/ocs/exceptions.py
tests/e2e/test_pvc_creation_performance.py
tests/helpers.py

https://jira.coreos.com/browse/KNIP-627 item #3

Performance testing: Creation of 120 PVCs in 60 seconds

---

ocs_ci/ocs/resources/ocs.py
tests/conftest.py
tests/manage/pv_services/test_delete_create_pvc_same_name.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/557

check is_deleted flag in the base OCS class and avoid repetitive checks

---

docs/code_review.md

Added guidelines to contribution doc around pairing PRs with Issues

---

tests/fixtures.py

Fix create_pods fixture

---

tests/conftest.py

Fix for Issue #592 : "InvalidValue: [Errno 22] error in setxattr" error while creating CephFS based PVC

---

tests/manage/pv_services/test_reclaim_policy.py

Fixing https://github.com/red-hat-storage/ocs-ci/issues/586

Fixing issue-586: broken test case - test_reclaim_policy

---

ocs_ci/ocs/ocp.py

Fix issue #591

---

tests/conftest.py

Fix Pod factory fixture

---

tests/conftest.py
tests/manage/pv_services/test_pvc_disruptive.py

Change PVC disruptive tests to factory

---

tests/conftest.py
tests/manage/storageclass/test_create_multiple_sc_with_different_pool_name.py

Testcase: OCS-624; Create multiple SC(different names) with different pool name

Testcase: OCS-624; Create multiple SC(different names) with different pool name

---

tests/e2e/test_jenkins_simulation.py

- Use factory fixture in test_jenkins_simulation.py
- Parametrize interfaces

Use factory fixture in test_jenkins_simulation.py

---

ocs_ci/ocs/resources/pvc.py
tests/conftest.py
tests/helpers.py
tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py

Test Case - Delete ceph pod while pvc/pod deletion is running

---

ocs_ci/ocs/constants.py
ocs_ci/templates/app-pods/fedora_dc.yaml
ocs_ci/templates/ocs-deployment/service_account.yaml
ocs_ci/utility/workloads/helpers.py
tests/fixtures.py
tests/helpers.py
tests/manage/pv_services/test_run_io_multiple_dc_pods.py

Run IO on multiple Deploymentconfig pod

---

.gitignore
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/utility/templating.py
ocs_ci/utility/utils.py
tests/conftest.py

Proposing method to clone rook repository for consuming yaml files directly. This will allow us keep with all changes quite easier if we will convert everything to this new approach.
I just updated for example usage of RBD and CEPHFS CSI storage classes as I found occurrences of them.
Fixes: #596

Rook repo download

---

tests/manage/pv_services/test_delete_create_pvc_same_name.py

Fixed teardown mechanism using teardown_factory

Fix test_delete_create_pvc_same_name

---

ocs_ci/ocs/resources/pvc.py
tests/e2e/test_pvc_creation_performance.py
tests/helpers.py

https://polarion.engineering.redhat.com/polarion/#/project/
OpenShiftContainerStorage/workitem?id=OCS-1270

Add test OCS-1270

---

tests/manage/storageclass/test_create_multiple_sc_with_different_pool_name.py

Fix helpers.create_pod function argument changes in OCS-624

---

tests/manage/pv_services/test_run_io_multiple_pods.py

Change test_run_io_multiple_pods to factory

---

tests/manage/noobaa/test_bucket_deletion.py
tests/manage/noobaa/test_create_bucket.py
tests/manage/noobaa/test_write_to_bucket.py

Addresses [issue 645](https://github.com/red-hat-storage/ocs-ci/issues/645)

Assign Polarion IDs to all existing NooBaa tests

---

ocs_ci/ocs/ocp.py

Fix docstring in OCP wait for delete

---

tests/conftest.py

Add isautomated to polarion

---

ocs_ci/framework/conf/default_config.yaml

Fixes https://github.com/red-hat-storage/ocs-ci/issues/651

enable OCP/OCS monitoring by default

---

ocs_ci/ocs/ocp.py

Fixing issue with deployment and check mons

---

ocs_ci/ocs/ceph.py
ocs_ci/ocs/clients.py
ocs_ci/ocs/exceptions.py
ocs_ci/ocs/utils.py

Fixes: #649
In this PR I am fixing the exception issue with CommandFailed.
Also adding timeout for must-gather execution for 600 seconds.

Fix must gather timeout

---

ocs_ci/ocs/resources/pod.py
ocs_ci/utility/uninstall_openshift_logging.py

Uninstall openshift-logging for ocp 4.2

---

ocs_ci/ocs/constants.py
ocs_ci/utility/prometheus.py
tests/manage/monitoring/conftest.py
tests/manage/monitoring/prometheus/test_deployment_status.py

- Add `check_alert_list` function.
- Add `check_alert_cleared` function.
- Add `workload_stop_ceph_mon` fixture.
- Add `test_ceph_monitor_stopped` test case.

Monitor quorum alert test case

---

tests/e2e/test_io_performance.py
tests/e2e/test_jenkins_simulation.py
tests/e2e/test_pgsql.py
tests/e2e/test_pvc_creation_performance.py
tests/e2e/test_small_file_workload.py
tests/manage/pv_services/test_pvc_concurrent_deletion_creation.py
tests/manage/storageclass/test_create_multiple_sc_with_different_pool_name.py
tests/manage/storageclass/test_create_multiple_sc_with_same_pool_name.py

- New tier levels now in use:
* performance
* workloads

Order tier levels

---

ocs_ci/framework/conf/default_config.yaml
ocs_ci/templates/ocs-deployment/cluster.yaml

Fixes: #653
You can see the changes also in the rook repo here:
https://github.com/rook/rook/commit/a42916eff098db63241cd4f56c7aca83196cb035

Move Ceph to the new version

---

ocs_ci/utility/aws.py

- added methods to class AWS
- create function block az, restore az
function added: (in progress):
get_vpc_by_name_pattern
create_security_group
file updated, in progress
in progress, made some fixes
reformat
method: test_block_availability_zone is now ready

Infrastructure for blocking AWS availability zones

---

ocs_ci/ocs/resources/noobaa.py

Add an option to create a bucket on a specific region. 
When running against S3, you can specify the specific region for the bucket.

Add option to create a bucket on a specific region

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/pod.py
tests/helpers.py
tests/manage/pv_services/test_no_space_left.py

Automating OCS-852 and OCS-853
OCS-853 is buggy - https://bugzilla.redhat.com/show_bug.cgi?id=1745344

No space left test case

---

tests/manage/pv_services/test_pvc_disruptive.py

* Both RWX and RWO PVC will be created
* Few other enhancements

Update test_pvc_disruptive to use RWX PVC

---

ocs_ci/ocs/resources/mcg.py
tests/helpers.py
tests/manage/mcg/conftest.py
tests/manage/mcg/test_bucket_creation.py
tests/manage/mcg/test_bucket_deletion.py
tests/manage/mcg/test_write_to_bucket.py

Verified locally since MCG isn't yet deployed 
========================== 3 passed in 239.16 seconds ==========================

Refactor 'NooBaa' to 'MCG'

---

conf/ocsci/deploy_with_operator.yaml
conf/ocsci/downstream_config.yaml
ocs_ci/deployment/aws.py
ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/ocs/defaults.py
ocs_ci/ocs/exceptions.py
ocs_ci/ocs/ocp.py
ocs_ci/ocs/resources/csv.py
ocs_ci/templates/ocs-deployment/deviceset.yaml
ocs_ci/utility/templating.py

Fixes: #641 
Use operator for the deployment:
https://github.com/openshift/ocs-operator

Deployment using ocs operator

---

conf/ocsci/deploy_with_operator.yaml
conf/ocsci/deploy_without_operator.yaml
ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml

Enable OCS deployment via operator by default

---

ocs_ci/ocs/resources/pvc.py
tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py

Fix for test_pvc_delete_verify_size_is_returned_to_backendpool

---

conf/ocsci/downstream_config.yaml

https://projects.engineering.redhat.com/browse/OCSQE-59

Added ocs_must_gather_image to downstream config

---

conf/ocsci/production-aws-ipi.yaml

Fixes: #696 
This config will be used for production runs

Add produciton config for AWS IPI with m5.4xlarge

---

ocs_ci/deployment/deployment.py

This reverts commit 250b6ec09be8dc62c6057e32d8b269ad23f27cf9.
Fixes issue: #687
The commit which is fixing it in the operator is this:
https://github.com/openshift/ocs-operator/commit/8c491c23972beab6088d7301397365ebb965887e

Revert "workaround for BZ 1747388 with WARN too few PGs"

---

ocs_ci/ocs/constants.py
ocs_ci/templates/app-pods/fedora_dc.yaml
tests/conftest.py
tests/fixtures.py
tests/helpers.py
tests/manage/pv_services/test_run_io_multiple_dc_pods.py

1- Add factory fixture for deployment config pod
2- Move script from fixture to factory fixture

Add factory fixture for deploymentconfig pod

---

tests/conftest.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/701

Add factory fixture at class scope

---

ocs_ci/ocs/resources/pvc.py

- Added @property backed_sc method

Fix for method backed_sc in ocs_ci/ocs/resources/pvc.py 

---

tests/manage/cluster/test_add_mds_to_cluster.py

Skip TestCephFilesystemCreation due to bz 1752286

---

conf/ocsci/downstream_config.yaml
ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/ocs/defaults.py
ocs_ci/ocs/exceptions.py
ocs_ci/ocs/ocp.py
ocs_ci/ocs/resources/csv.py
ocs_ci/ocs/resources/ocs.py
ocs_ci/ocs/resources/packagemanifest.py
ocs_ci/utility/templating.py
ocs_ci/utility/utils.py

Fixes: #712 
Implement missing functionality for DS OCS operator deployment.

Deploy via downstream ocs operator

---

ocs_ci/deployment/ocp.py
ocs_ci/framework/conf/default_config.yaml

Ticket:
https://projects.engineering.redhat.com/browse/OCSQE-68

Add ssh key for OCP deployment

---

tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py

Fixes https://github.com/red-hat-storage/ocs-ci/issues/767

Issue 767 test decorators

---

tests/manage/pv_services/test_create_pvc_random_storage_class.py

Fix tc failing in Jenkins
Fixes for issue #524 

Fix for issue 524

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/pod.py
tests/disruption_helpers.py
tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py

OCS-1009 - RBD: Delete csi-rbdplugin while deleting app pods along with their mount points
OCS-1018 - CEPHFS: Delete csi-cephfsplugin while deleting app pods along with their mount points

Adding test cases OCS-1009 and OCS-1018

---

ocs_ci/deployment/deployment.py
ocs_ci/deployment/factory.py
ocs_ci/deployment/vmware.py
ocs_ci/ocs/constants.py

patch sc as non-default based on platform

---

ocs_ci/framework/conf/default_config.yaml

Move Ceph to v14.2.3-20190904 in default config

---

ocs_ci/ocs/cluster.py
tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py

Fix for varying_ceph_size in backend_pool test

---

tests/manage/pv_services/test_pvc_disruptive.py

Test cases added:
OCS-1014
RBD: Delete csi-rbdplugin while running IO
OCS-1017
CEPHFS: Delete csi-cephfsplugin while running IO
Added ceph health check
Added verification of pods of type 'resource_to_delete'

test_pvc_disruptive new test cases and enhancement

---

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py

OCS-1010
RBD: Delete csi-rbdplugin while PVC creation, Pod creation and IO are progressing
OCS-1011
CEPHFS: Delete csi-cephfsplugin while PVC creation, Pod creation and IO are progressing

Tests OCS-1010 OCS-1011

---

ocs_ci/deployment/aws.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/platform_nodes.py
ocs_ci/ocs/resources/pvc.py
ocs_ci/utility/aws.py
tests/conftest.py
tests/helpers.py
tests/manage/cluster/nodes/test_disk_failures.py

This PR prepares the classes needed for the abstraction layer of nodes operations used in node related tests.
Adjusted disk failures related tests to this change. Will adjust other tests in following PRs

Allow running node related tests on any platform type

---

ocs_ci/deployment/aws.py

Improve skip cluster deployment logging

---

conf/ocsci/skip_ocp_deploy.yaml
conf/ocsci/skip_ocs_deploy.yaml
docs/usage.md
ocs_ci/framework/main.py
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/framework/tests/test_main.py

Initial step for this issue #700.

Allow ocsci-conf read multiple conf files

---

docs/getting_started.md

Update the path of default_config.yaml

---

docs/README.md
docs/debugging.md
docs/getting_started.md

Add documentation for SSH key deployment

---

ocs_ci/utility/utils.py

Include deployment platform and type in email subject for test results
Fixes: #799

Include deployment platform and type in email subject for

---

.gitignore
conf/ocsci/aws_upi.yaml
docs/getting_started.md
external/README.md
ocs_ci/deployment/aws.py
ocs_ci/deployment/factory.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
ocs_ci/utility/utils.py

AWS UPI Deployment

---

ocs_ci/ocs/constants.py
tests/manage/monitoring/conftest.py
tests/manage/monitoring/prometheus/test_deployment_status.py

Add test_ceph_osd_stopped test case.

Stop osd test case

---

ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/utility/utils.py

Fetch container name instead of parging image for getting name

Fix Reporting in email

---

ocs_ci/deployment/deployment.py
ocs_ci/ocs/resources/catalog_source.py

Fixes: #782 - increased timeout for 100 seconds for CSV
Fixes: #846 - separate subscriptin from deploy-with-olm.yaml
Recommended in bug: https://bugzilla.redhat.com/show_bug.cgi?id=1757013

Wait for catalog source before subscription

---

ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/constants.py
ocs_ci/utility/utils.py

Fixes: #848
Infra ticket:
https://projects.engineering.redhat.com/browse/OCSQE-84

Print consolidated config to the file

---

Jenkinsfile

Jenkins: pass --bugzilla when running tests

---

ocs_ci/utility/templating.py

Read file before passing to loader for local yaml files

---

conf/ocsci/upstream_config.yaml
ocs_ci/framework/conf/default_config.yaml
ocs_ci/framework/tests/test_config.py

Move to downstream

---

conf/ocsci/production-aws-ipi.yaml
ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml

Fixes: #861
All info described in the issue.

Allow lower requests/limits for worker instances

---

Jenkinsfile

downsteam-ci: use conf/ocsci/production-aws-ipi.yaml

---

conf/ocsci/aws_ipi_workload_3_nodes.yaml
ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml

Add workload config

---

ocs_ci/deployment/deployment.py

Fixing noobaa requirements

---

conf/ocsci/production-vsphere-upi.yaml
ocs_ci/deployment/vmware.py
ocs_ci/ocs/constants.py
ocs_ci/utility/templating.py
setup.py

providing option for users to configure vCPUs for nodes in cluster for vSphere platform
Issue: #875

Adding vCPU option for vSphere platform

---

ocs_ci/deployment/terraform.py
ocs_ci/deployment/vmware.py

Reinitializing the terraform for destroy functionality for vSphere platform
Issue: #886

Reinitializing the terraform for destroy functionality for vSphere platform

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/ocp.py
ocs_ci/templates/openshift-infra/rsync-pod.yaml

Add function for rsync

---

ocs_ci/ocs/ocp.py
ocs_ci/utility/utils.py

Added new function "exec_oc_debug_cmd" to run commands on OCP nodes.
Signed-off-by: ramkiperiy <rperiyas@redhat.com>

Function to execute cmd on master/worker nodes. 

---

ocs_ci/deployment/aws.py

Read clusterName from deployment metadata instead of from file

---

.functional_ci_setup.py
conf/ocsci/downstream_config.yaml
conf/ocsci/upstream_config.yaml
ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml

Rename ocs_operator_image to ocs_registry_image

---

ocs_ci/ocs/constants.py
ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-sub.yaml
ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-sub.yaml
tests/e2e/logging/test_openshift-logging.py

Deployment of openshift-logging for 4.2 with updated images

---

ocs_ci/ocs/node.py

Adding library for removing nodes

Adding library for removing nodes

---

ocs_ci/framework/main.py
ocs_ci/utility/utils.py

Fixing typos

---

conf/ocsci/host_network_enabled.yaml
ocs_ci/deployment/aws.py
ocs_ci/deployment/deployment.py
ocs_ci/utility/aws.py

Fixes: #909
All the description is in the issue mentioned above.

Add host network

---

ocs_ci/deployment/aws.py

https://github.com/red-hat-storage/ocs-ci/pull/910/ broke our CI builds.

aws: Safely check for host_network setting

---

ocs_ci/utility/aws.py

Fix issue with VpcId

---

ocs_ci/framework/pytest_customization/marks.py
tests/manage/cluster/nodes/test_nodes_maintenance.py
tests/manage/cluster/nodes/test_nodes_restart.py

Also replace old skipifs with the new marker.
Solves issue #926

Fix bug where a lower case platform name is not checked

---

ocs_ci/ocs/cluster.py

Safe load yaml to fix YAMLLoadWarning

---

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py

test_resource_deletion_during_pvc_pod_deletion_and_io.py
Updating test case to create rbd block type volume

Adding rbd block type volume creation in test case

---

tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py

Update test_disruptive_during_pod_pvc_deletion to use block type volume

---

setup.py

- resolve conflict with newer openshift package
- fixes https://github.com/red-hat-storage/ocs-ci/issues/935

setup.py: remove particular version for kubernetes

---

tests/ecosystem/deployment/test_deployment.py

Skip ocs install verification if we skip ocs deployment

---

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py

Test case update to create rdb block type volume

---

conf/ocsci/production_device_size.yaml

Adding device size for production environments

Adding device size for production environments

---

tests/manage/cluster/test_add_mds_to_cluster.py

Various fixes for MDS test which is consistently failing in tier1 

Various fixes for Add MDS test

---

tests/manage/mcg/test_object_integrity.py

Endpoint param mismatch due to changes done in #807

Minor fix in test_object_integrity

---

ocs_ci/utility/environment_check.py

Fix issue #802

---

ocs_ci/deployment/deployment.py
ocs_ci/ocs/constants.py

using default pools and storage class for monitoring

---

ocs_ci/ocs/ocp.py
ocs_ci/ocs/platform_nodes.py
tests/manage/cluster/nodes/test_nodes_maintenance.py
tests/manage/cluster/nodes/test_nodes_restart.py
tests/sanity_helpers.py

Adjust test_nodes_restart to address https://github.com/red-hat-storage/ocs-ci/issues/788

Adjust nodes restart tests to run on any type of platform

---

ocs_ci/deployment/vmware.py

Remove unused code for vsphere platform

Remove unused code for vsphere platform

---

ocs_ci/deployment/deployment.py

Distribute labels among different AZ

---

ocs_ci/ocs/platform_nodes.py
tests/manage/cluster/nodes/test_nodes_restart.py
tests/sanity_helpers.py

Remove BZ 1748001 W/A

---

conf/ocsci/production-aws-ipi.yaml
conf/ocsci/production-vsphere-upi.yaml

Fix allow_lower_instance_requirements in configs

---

tests/manage/mcg/test_bucket_creation.py

Update test function with extra parameter amount and interface.
Parametrize tests with current sets and three new sets.
Signed-off-by: Wayne Sun <gsun@redhat.com>

Parametrize bucket creation test cases

---

tests/ecosystem/deployment/test_deployment.py

check to verify OSD's are distributed among worker nodes
Fixes: #952

check to verify OSD's are distributed among worker nodes

---

conf/ocsci/ocp-4.3-config.yaml

Add OCP 4.3 config

---

conf/ocsci/aws_1az.yaml
conf/ocsci/aws_ipi_1az.yaml

Add 1az Config for default region

---

conf/ocsci/vsphere_upi.yaml

Changing worker nodes count to 3 in vSphere platform

---

ocs_ci/deployment/deployment.py

Fixes: #782
The BZ appeared again:
https://bugzilla.redhat.com/show_bug.cgi?id=1757013
So trying to increase timeouts to wait a bit more and maybe it will
stabilize the deployment.

Increase timeout for CSV and PackageManifest

---

conf/ocsci/production-aws-upi.yaml

Adding yaml for AWS UPI production environment

---

.functional_ci_setup.py

Jenkins: Drop OLM and cluster CR

---

ocs_ci/ocs/exceptions.py
ocs_ci/ocs/ocp.py
ocs_ci/ocs/resources/csv.py
ocs_ci/ocs/resources/ocs.py
ocs_ci/ocs/resources/storage_cluster.py

Fixes: #1003
Added default timeout to 600sec for OCS deployment verification.

Fix StorageCluster check

---

tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
tests/manage/pv_services/test_verify_rwo_using_multiple_pods.py

The expected error message is updated
Added bugzilla marker in tests

Add bugzilla marker in test cases

---

tests/e2e/test_pv_scale_and_respin_ceph_pods.py
tests/e2e/test_pv_scale_ocs_create_delete_pvcs.py
tests/helpers.py

Enhanced Threading mechanism of deleting objs and added Ignore_left_overs in PVC scale TC's

Fix for #1019, Enhance parallel obj delete

---

Jenkinsfile

Jenkins: Fix broken variable injection for UMB msg

---

ocs_ci/ocs/resources/catalog_source.py

Based on discuttion in https://bugzilla.redhat.com/show_bug.cgi?id=1770192

Increase catalog source wait timeout to 8 minutes

---

tests/manage/mcg/test_bucket_creation.py

Add negative test cases with create duplicate OBC.
Signed-off-by: Wayne Sun <gsun@redhat.com>

Add duplicate BOC creation cases

---

tests/e2e/test_pv_scale_and_respin_ceph_pods.py
tests/e2e/test_pv_scale_ocs_create_delete_pvcs.py

Modified Scale tests with bugzilla marker which are blocked due to bz 1768031
Signed-off-by: ramkiperiy <rperiyas@redhat.com>

Updated bugzilla marker in the blocked scale tests

---

ocs_ci/deployment/aws.py
ocs_ci/deployment/deployment.py
ocs_ci/ocs/ocp.py
ocs_ci/utility/utils.py

Avoids: https://github.com/red-hat-storage/ocs-ci/issues/830

Add default timeout(600 seconds) for run_cmd

---

ocs_ci/ocs/platform_nodes.py
tests/manage/cluster/nodes/test_nodes_maintenance.py

Fixes in nodes tests

---

ocs_ci/deployment/deployment.py

Extended waiting_time for alertmanager from 30 to 45 seconds

---

docs/code_review.md

Updated the code review document with explanation about DCO

---

tests/manage/cluster/test_must_gather.py

removed workaround for prepare-ocs-devicese pods

---

conf/deployment/aws/ipi_1az_coreos_3m_3w.yaml
conf/deployment/aws/ipi_3az_coreos_3m_3w.yaml

Added AWS IPI production deployment configurations

---

tests/manage/cluster/test_must_gather.py

added workaround for BZ BZ-1766646

---

ocs_ci/ocs/resources/ocs.py

Remove local storage operator from deployment check

---

tests/manage/cluster/nodes/test_nodes_maintenance.py

Addresses https://github.com/red-hat-storage/ocs-ci/issues/788 

Adjust node maintenance tests to abstract nodes platform class

---

ocs_ci/templates/workloads/smallfile/SmallFile.yaml
tests/e2e/test_small_file_workload.py

Adding parameters to the test of smallfiles, and updating the corresponding yaml file.

Adding parameters to smallfile test

---

conf/README.md

The code sample wasn't valid Python. Fix that.

conf/README.md: Fix broken docs build

---

conf/ocsci/aws_upi.yaml
ocs_ci/deployment/aws.py

Add support to pass availability zone count to aws upi script

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/exceptions.py
ocs_ci/ocs/ocp.py
ocs_ci/ocs/resources/ocs.py
ocs_ci/ocs/resources/pod.py
ocs_ci/utility/utils.py
tests/ecosystem/upgrade/test_upgrade.py

Verify upgrade of all images used by OCS components

---

conf.py

Sphinx: Ignore ./venv

---

ocs_ci/ocs/exceptions.py
ocs_ci/ocs/resources/objectconfigfile.py
tests/conftest.py
tests/manage/monitoring/conftest.py
tests/manage/monitoring/test_workload_fixture.py

Storage utilization workload fixtures, for metrics and alerting tests.

Workload storage utilization

---

ocs_ci/ocs/platform_nodes.py
ocs_ci/ocs/resources/pvc.py
tests/manage/cluster/nodes/test_disk_failures.py

Fix for failure of test_disk_failures.py

Fix getting deviceset name function

---

ocs_ci/framework/conf/default_config.yaml

Set RC build as the default

---

conf/deployment/aws/upi_1az_coreos_3m_3w.yaml
conf/deployment/aws/upi_3az_coreos_3m_3w.yaml

Jira: https://projects.engineering.redhat.com/browse/OCSQE-100

Added deployment configs for AWS UPI coreos scenarios

---

tests/manage/mcg/test_bucket_creation.py

Fixed call to *_get_all_bucket_names

---

conf/ocsci/vsphere_scale_cluster.yaml
conf/ocsci/vsphere_scale_cluster.yaml.example
ocs_ci/deployment/install_ocp_on_rhel.py
ocs_ci/deployment/terraform.py
ocs_ci/deployment/vmware.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/ocs/node.py
ocs_ci/templates/ocp-deployment/scale_up_terraform.tfvars.j2
ocs_ci/utility/utils.py
setup.py

This PR will allows user to perform below thing
1. To Install Mixed OCS Cluster ( RHCOS + RHEL compute nodes )
2. To intsall OCS with RHEL compute nodes
PR contains below commits
46ee67a8a3691b3a62a0355b57b65fdf9db1ff37 : Adding scale-up templates for vsphere and related constants
5a897be259474673d4e2a346af908009f936083f : Adding module for OCP installation on RHEL
and Also added methods for terraform and node modules
0c8510bf9e4ec47d8bba1a27be8d15bb57935142 : Install OCP on RHEL nodes which makes the mixed cluster
cc72b872ab037b970cf90e57b948c4b14b4b4871 : Removes RHCOS compute nodes from mixed cluster - OCS cluster  with RHEL nodes
6dbb62470093b9170afa99cba296b8bc0c08cfff : Delete scale-up nodes before deleting cluster
a74c346f3378fd0ca66c6664ba756ffc078825e9 : Include timeout for …

RHEL installation in vSphere platform

---

conf/deployment/vsphere/upi_1az_coreos_vmfs_3m_3w.yaml

Jira: https://projects.engineering.redhat.com/browse/OCSQE-100

Added deployment configuration for vsphere upi

---

ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/utility/utils.py

Use latest RC tag as default

---

conf/ocsci/manual_subscription_plan_approval.yaml
ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/ocs/exceptions.py
ocs_ci/ocs/ocp.py
ocs_ci/ocs/resources/install_plan.py
ocs_ci/templates/ocs-deployment/deploy-with-olm.yaml
ocs_ci/templates/ocs-deployment/subscription.yaml
tests/ecosystem/upgrade/test_upgrade.py

Change to manual subscription plan

---

tests/manage/cluster/nodes/test_nodes_maintenance.py

Skip leftovers in maintenance tests

---

ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/templates/ocs-deployment/catalog-source.yaml
ocs_ci/templates/ocs-deployment/deploy-with-olm.yaml

Prepare for UI deployment

---

ocs_ci/ocs/ocp.py

Added support for a custom column name in wait_for_resource()

---

conf/deployment/aws/upi_1az_rhel7_3m_3w.yaml
conf/deployment/aws/upi_3az_rhel7_3m_3w.yaml

Added deployment configs for AWS UPI with RHEL workers

---

ocs_ci/utility/utils.py

Increase timeout for get openshift mirror url

---

ocs_ci/deployment/aws.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/1117

aws-upi 3az: ocs_ci/deployment/aws.py

---

tests/e2e/monitoring/test_monitoring_after_reboot_master_node.py
tests/e2e/monitoring/test_reboot_node_where_mgr_running.py
tests/e2e/monitoring/test_when_one_of_the_prometheus_node_down.py
tests/e2e/monitoring/test_when_respin_ceph_pods_interaction_with_prometheus.py

Change e2e monitoring tests to run under workloads suite

---

tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py

OCS-1136	RBD: MGR daemon kill while PVC deletion, Pod deletion and IO are progressiing
OCS-1122	RBD: Mon daemon kill while PVC deletion, Pod deletion and IO are progressiing
OCS-1129	RBD: OSD daemon kill while PVC deletion, Pod deletion and IO are progressiing
OCS-1108	CEPHFS: MGR daemon kill while PVC deletion, Pod deletion and IO are progressing
OCS-1093	CEPHFS: Mon daemon kill while PVC deletion, Pod deletion and IO are progressing
OCS-1101	CEPHFS: OSD daemon kill while PVC deletion, Pod deletion and IO are progressing
OCS-1115	CEPHFS: MDS daemon kill while PVC deletion, Pod deletion and IO are progressing

Tests: Kill daemon while pvc, pods deletion and IO are progressing

---

ocs_ci/deployment/aws.py

Skip RHEL worker termination if worker list is empty

---

conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml

Added config for vsphere upi deployment with rhel workers

---

docs/usage.md
ocs_ci/cleanup/aws/cleanup.py
ocs_ci/ocs/constants.py
ocs_ci/templates/cleanup/cleanup.yaml.j2
setup.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/883

Add cleanup option that can be used to cleanup cluster setup by any user

---

ocs_ci/ocs/openshift_ops.py
tests/manage/z_cluster/test_must_gather.py

Fix tier1 must-gather test

---

ocs_ci/deployment/aws.py

Fix UPI AWS deployment with CoreOS

---

ocs_ci/ocs/resources/pod.py
tests/helpers.py
tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py
tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
tests/manage/pv_services/test_pvc_disruptive.py
tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py

Update tests to use latest available helper functions.

Methods consolidation pv services tests

---

ocs_ci/framework/exceptions.py

Changed min/max so it won't shadow builtin functions

---

tests/manage/z_cluster/nodes/test_nodes_maintenance.py

Adjustments in 2_nodes_maintenance_same_type + BZ 1780157 decorator

---

tests/ecosystem/upgrade/test_configuration.py

Test to check crush map before and after upgrade

---

ocs_ci/ocs/constants.py
ocs_ci/utility/prometheus.py
tests/manage/monitoring/conftest.py
tests/manage/monitoring/prometheus/test_capacity.py
tests/manage/monitoring/prometheus/test_deployment_status.py

- Add capacity test cases for alerts.
- Update target values for capacity workload fixtures.

Test alerts for capacity workload

---

ocs_ci/framework/pytest_customization/ocscilib.py

Only check for cluster name length on a deployment operation

---

ocs_ci/ocs/cluster.py
ocs_ci/ocs/ocp.py
ocs_ci/utility/utils.py
tests/ecosystem/upgrade/test_upgrade.py

Ticket:
https://projects.engineering.redhat.com/browse/OCSQE-145

Add health check to the upgrade test

---

ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/utility/utils.py

Ticket: https://projects.engineering.redhat.com/browse/OCSQE-96

UI deployment via OCS-CI

---

ocs_ci/utility/prometheus.py
tests/manage/monitoring/prometheus/test_ceph.py

add Ceph Cluster health Alerts test case

---

conf/examples/telemeter_stage.yaml
ocs_ci/deployment/deployment.py
ocs_ci/ocs/monitoring.py

This pull request contains 2 changes:
- log UUID of the cluster, so that one can query telemeter for the data of the cluster
- reconfiguration of telemeter-client to use send data to stage telemeter instead of production

Telemeter setup

---

tests/manage/z_cluster/test_add_mds_to_cluster.py

Removed the usage of ignore_leftovers as it cause following test to fail

Fix add MDS tier1 test case

---

ocs_ci/ocs/cluster.py

Fix for ceph_status function name

---

ocs_ci/utility/utils.py

Add timeout parameter for rhel_pod creation

---

ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/instance.yaml

Setting redundancy & curator values to default values for logging

---

tests/e2e/logging/test_openshift-logging.py

Change test_create_new_project_to_verify_logging to workloads

---

conf/deployment/vsphere/upi_1az_coreos_3m_3w.yaml
conf/deployment/vsphere/upi_1az_coreos_3m_3w_dc1_dc2.yaml
conf/deployment/vsphere/upi_1az_rhel_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhel_3m_3w_dc1_dc2.yaml

And create other config files for DC1 and DC2.

Change vmware config to production

---

ocs_ci/utility/utils.py

Need to take previous RC build for upgrade

---

tests/conftest.py

Quick fix for #1151 
Workarounds https://bugzilla.redhat.com/show_bug.cgi?id=1777384

Enable container_use_cephfs SELinux boolean on RHEL based workers

---

ocs_ci/ocs/resources/ocs.py
tests/ecosystem/upgrade/test_upgrade.py

Fix OSD count number verification

---

conf/ocsci/vsphere_scale_cluster.yaml
ocs_ci/templates/ocp-deployment/scale_up_terraform.tfvars.j2

Updating memory and CPU's for RHEL nodes

---

ocs_ci/ocs/resources/pod.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/1193

Add more info for debugging fio failure

---

ocs_ci/deployment/aws.py

Pass region to boto clients properly

---

ocs_ci/deployment/deployment.py

Increase timeout for UI deployment

---

ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/ocs.py
ocs_ci/ocs/resources/pod.py

 Get mcg core and operator version info

---

conf/deployment/vsphere/upi_1az_rhel_3m_3w.yaml

Adding Memory and CPU option for RHEL in vSphere platform

---

ocs_ci/deployment/deployment.py
ocs_ci/templates/ocs-deployment/subscription.yaml

Take the channel for ocs operator dynamically

---

ocs_ci/ocs/resources/ocs.py

Removed logging which was unnecessary and caused report generation failure

Remove unnecessary log

---

ocs_ci/utility/utils.py

Upgrade just between rc builds

---

conf/ocsci/stage.yaml.example
ocs_ci/deployment/deployment.py
ocs_ci/ocs/constants.py
ocs_ci/templates/ocs-deployment/stage-operator-source-secret.yaml
ocs_ci/templates/ocs-deployment/stage-operator-source.yaml
ocs_ci/utility/templating.py
ocs_ci/utility/utils.py

* Configure OperatorSource and related secret for deployment from stage.
* enhance `censor_values` function to process dictionaries recursively
* censor values in data printed to log in `dump_data_to_temp_yaml`
* Deployment now works only in VMWare environment.

Deployment from stage

---

ocs_ci/ocs/cluster.py
ocs_ci/ocs/exceptions.py
ocs_ci/ocs/resources/pod.py

Addresses https://github.com/red-hat-storage/ocs-ci/issues/1089

Added Noobaa pods to cluster_health_check

---

ocs_ci/ocs/ocp.py
tests/manage/monitoring/prometheus/test_alerting_works.py
tests/manage/monitoring/prometheus/test_capacity.py
tests/manage/monitoring/prometheus/test_ceph.py
tests/manage/monitoring/prometheus/test_deployment_status.py
tests/manage/monitoring/prometheus/test_noobaa.py

Added support for logging in as sa and using it in the end of relevant tests

---

ocs_ci/ocs/ripsaw.py
tests/e2e/test_pgsql_pod_respin.py

Fixes #1225 - resource leftover during ceph pod re-spin with pgsql workload

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/platform_nodes.py
ocs_ci/ocs/resources/pod.py
ocs_ci/utility/vsphere.py
tests/helpers.py
tests/manage/z_cluster/nodes/test_disk_failures.py
tests/manage/z_cluster/nodes/test_nodes_restart.py

Partial implementation for https://github.com/red-hat-storage/ocs-ci/issues/1080

Enable nodes restart tests over VMWare

---

ocs_ci/templates/workloads/smallfile/SmallFile.yaml

Updates smallfile workload CRD template.

Modify smallfile workload template

---

ocs_ci/ocs/resources/pod.py
tests/e2e/test_pvc_deletion_performance.py
tests/helpers.py

Tests to measure PVC deletion performance.

Tests to measure performance for PVC delete operation

---

ocs_ci/ocs/resources/pvc.py
tests/conftest.py

Fetch reclaim policy from PV instead of getting it from storage class

---

ocs_ci/ocs/resources/pod.py

Enhanced run_fio function with rate and rate_process param
modified:   ocs_ci/ocs/resources/pod.py
Signed-off: rperiyas <rperiyas@redhat.com>

Enhance run_fio function with rate and rate_process param

---

tests/helpers.py

Added new function in tests/helpers.py to add labels to worker node.

Added new function in tests/helpers.py to add labels to worker node.

---

ocs_ci/ocs/ocp.py

Fixes: #929
During attempts for waiting for resource, it can happen that the
resource is deleted beteween the quieries and then the get function fail.
This fix adding additional retry to get function which is used in
wait_for_resource function.
This makes function more robust and proof for such issues whene the
resource is deleted and recreated between the calls.
The origin behavior for get function remain the same with no extra
attempt/retry or wait.

Add retry in get function for wait for resource

---

ocs_ci/utility/workloads/fio.py

Fixes: #1200
This adds retry the setup function for fio.
Currently upgrade is failing on this issue and we need unblock upgrade
jobs ASAP hence adding retry as quick fix here.
For sure Vasus propsed PR to use preinstalled images is still valid but
this setup is executed all the time as well to make sure we have the
fio package.

Add retry to setup fio function

---

ocs_ci/deployment/deployment.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/ocs.py
tests/conftest.py
tests/helpers.py
tests/internal/test_create_pvc_random_storage_class.py
tests/internal/test_create_storage_class_pvc.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/954 

Use Default StorageClass for tests

---

ocs_ci/framework/pytest_customization/marks.py
pytest.ini
tests/manage/mcg/test_multi_region.py
tests/manage/monitoring/prometheus/test_ceph.py
tests/manage/monitoring/prometheus/test_deployment_status.py
tests/manage/monitoring/prometheus/test_noobaa.py
tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py
tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py
tests/manage/pv_services/test_pvc_disruptive.py
tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
tests/manage/z_cluster/nodes/test_az_failure.py
tests/manage/z_cluster/nodes/test_disk_failures.py
tests/manage/z_cluster/nodes/test_nodes_maintenance.py
tests/manage/z_cluster/nodes/test_nodes_restart.py
tests/manage/z_cluster/test_remove_mon_from_cluster.py

Addresses https://github.com/red-hat-storage/ocs-ci/issues/1239

separate tier4 into 2 more tiers

---

tests/conftest.py

Do not report version when teardown

---

ocs_ci/utility/utils.py

Increase timeout for OCP installer/client donwload

---

ocs_ci/templates/app-pods/nginx.yaml
tests/helpers.py

Update tests/helpers.py and nginx template for node selection constraints

---

tests/conftest.py

Fix positional param issue for pvc_factory for session fixture

---

tests/conftest.py
tests/e2e/logging/test_openshift-logging.py
tests/fixtures.py
tests/helpers.py

ocs-ci fails if called deletion of dc for singe dc twice

Improve Deletion of Deploymentconfig

---

ocs_ci/framework/pytest_customization/marks.py
ocs_ci/ocs/machine.py
ocs_ci/ocs/node.py
ocs_ci/ocs/resources/pod.py
tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py

This patch automates KNIP-678: Automated recovery from failed nodes. Proactive-AWS-IPI case

KNIP-678: Automated recovery from failed nodes - Proactive-IPI

---

tests/conftest.py

Update multi_pvc_factory_fixture to accept non- default sc

---

ocs_ci/framework/conf/default_config.yaml
ocs_ci/utility/utils.py

Changed how testrun name is constructed for email subject and polarion

---

ocs_ci/deployment/aws.py

Check whether RHEL nodes are accepting ssh connections

---

ocs_ci/utility/deployment_openshift_logging.py

Increase timeout for the logging pods

---

ocs_ci/ocs/resources/packagemanifest.py

Adding retry mechanism for get_default_channel

---

conf/README.md
conf/examples/monitoring.yaml
conf/examples/telemeter_stage.yaml
docs/usage.md
ocs_ci/framework/conf/default_config.yaml
ocs_ci/framework/main.py
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/framework/pytest_customization/tests/test_pytest.py
ocs_ci/framework/tests/test_main.py
tests/manage/monitoring/test_workload_fixture.py

Remove '--cluster-conf' cli option and its references

---

conf/ocsci/live_deployment.yaml
conf/ocsci/ocp_ga_version.yaml
docs/usage.md
ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/defaults.py

Live install

---

ocs_ci/deployment/vmware.py
ocs_ci/ocs/constants.py

Changing root disk dize in vSphere platform

---

ocs_ci/deployment/deployment.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/ocp.py
ocs_ci/ocs/resources/ocs.py
ocs_ci/ocs/resources/packagemanifest.py
ocs_ci/templates/ocs-deployment/catalog-source.yaml
tests/ecosystem/upgrade/test_upgrade.py

Fix deployment conflict with live content

---

ocs_ci/ocs/constants.py
ocs_ci/templates/app-pods/raw_block_pod.yaml
tests/helpers.py

Enhance create_pod_parallel function to create DC based app pods.
Enhance create_pod function to create Fedora Raw block PVC based app pod.
Signed-off-by: rperiyas <rperiyas@redhat.com>

Enhance create_pod_parallel function to create DC based app pods.

---

tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py

Should Fix: https://github.com/red-hat-storage/ocs-ci/issues/1299

Give extra time for pods to come up

---

conf/ocsci/ocp_ga_version.yaml

Bump OCP GA version

---

ocs_ci/ocs/resources/pod.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/1276

Fix FIO issues

---

ocs_ci/templates/workloads/pgsql/server/StatefulSet.yaml
tests/e2e/test_pgsql.py
tests/e2e/test_pgsql_pod_respin.py

Remove storage class factory and using default storage class for pgsql tests.

Fixed pgsql workload to use default storage class.

---

ocs_ci/deployment/deployment.py
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/defaults.py
ocs_ci/ocs/resources/packagemanifest.py
ocs_ci/templates/ocs-deployment/operator-source-secret.yaml
ocs_ci/templates/ocs-deployment/operator-source.yaml
ocs_ci/utility/environment_check.py
ocs_ci/utility/utils.py
tests/ecosystem/upgrade/test_upgrade.py

Fix conflict for stage testing and live content

---

ocs_ci/ocs/node.py
tests/manage/z_cluster/nodes/test_nodes_maintenance.py

Addresses https://github.com/red-hat-storage/ocs-ci/issues/1282

Assert in case node objects are not found and few fixes in drain tests

---

ocs_ci/deployment/deployment.py

Ticket: https://projects.engineering.redhat.com/browse/OCSQE-195

Pass env variable for live_deployment for UI console

---

ocs_ci/utility/utils.py
tests/manage/monitoring/conftest.py
tests/manage/monitoring/test_workload_fixture.py

Fixes https://github.com/red-hat-storage/ocs-ci/issues/1327

space reclaim check in workload_fio_storageutilization

---

ocs_ci/utility/utils.py
tests/conftest.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/1315

Add health check for tier4 tests before they are run

---

conf/ocsci/ocp_ga_version.yaml

Roll new OCP GA version 4.2.16

---

ocs_ci/ocs/node.py

Fix in get_typed_nodes()

---

tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
tests/helpers.py

Generic function for making osd pod down and up actions.

Function to modify osd replica count

---

Jenkinsfile

Jenkins: Remove ref to downstream_config.yaml

---

tests/e2e/test_vdbench_workload.py

This is to add another test with "@workloads" marker.
This additional test will run for only one hour.

Adding another test for the vdbench according to issue #1368

---

tests/e2e/logging/test_openshift-logging.py

OCS-650 Respin osd pod and verifies logs in EFK stack

---

tests/helpers.py

Added new function to get pvc creation & deletion time for pvc_list
#988
Signed-off-by: rperiyas <rperiyas@redhat.com>

Added new function to get pvc creation & deletion time for pvc_list

---

ocs_ci/deployment/vmware.py

Sync guest time with host in vSphere platform

---

ocs_ci/ocs/resources/pod.py

include timeout for checking pods in openshift-monitoring

---

ocs_ci/ocs/utils.py

Add tag to ocs must gather image

---

tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py

Added test_automated_recovery_from_failed_nodes_proactive_IPI.py to tier4b

---

tests/manage/z_cluster/cluster_expansion/test_node_expansion.py

- Fixed script issue for 1AZ aws ipi setup

Updated tests/manage/z_cluster/cluster_expansion/test_node_expansion.py

---

tests/e2e/test_amq_streamer_creation.py

Changed  the deualt sc to cephfs

added default sc to amq workload

---

ocs_ci/deployment/terraform.py

Fix for terraform apply stuck

---

conf/ocsci/ocs-4.3.yaml

Simple provide `conf/ocsci/ocs-4.3.yaml` as `CLUSTER_CONF` parameter.

add simple configuration for OCS 4.3 installation

---

conf/ocsci/ocs-4.3.yaml
ocs_ci/ocs/constants.py

Add 4.3 latest tags

---

conf/ocs_version/ocs-4.2.yaml
conf/ocs_version/ocs-4.3.yaml
ocs_ci/framework/main.py
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/constants.py

Added --ocs-version argument for specifying ocs version from CLI

---

ocs_ci/deployment/vmware.py

Include sync_guest_time for RHEL nodes in vSphere platform

---

conf/ocs_version/ocs-4.2.yaml
conf/ocs_version/ocs-4.3.yaml
docs/usage.md
ocs_ci/framework/main.py

Fix ocs-version parameter

---

conf/ocsci/ocp-4.2-config.yaml
conf/ocsci/ocp-4.3-config.yaml

Fixes: #1432
Also updating ocp 4.2 config with RHCOS image.

Add new 4.3 coreoes image for 4.3 ocp conf

---

ocs_ci/deployment/vmware.py
ocs_ci/templates/ocp-deployment/terraform.tfvars.j2

Include memory option for master and computer nodes individually

---

ocs_ci/ocs/resources/pod.py
tests/helpers.py
tests/manage/mcg/test_object_integrity.py
tests/manage/mcg/test_write_to_bucket.py
tests/manage/monitoring/conftest.py

Add new cases for write multiple large, small and empty files to bucket.

Add new bucket write io test cases

---

ocs_ci/ocs/resources/ocs.py

Verify that snapshotter sidecar container or image is not present
Verifies bug https://bugzilla.redhat.com/show_bug.cgi?id=1778805

Verify CSI snapshotter sidecar container is not present

---

tests/manage/monitoring/prometheus/test_capacity.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/1434

add capacity message for ocs 4.3

---

conf/ocs_version/ocs-4.2.yaml
ocs_ci/utility/utils.py

Update 4.2 config to use latest-4.2 tag

---

ocs_ci/ocs/utils.py

Deploy toolbox pod via ocs for 4.3

---

ocs_ci/deployment/aws.py
ocs_ci/deployment/vmware.py
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/exceptions.py
ocs_ci/ocs/resources/ocs.py
ocs_ci/ocs/utils.py
ocs_ci/utility/bootstrap.py
ocs_ci/utility/utils.py

Run gather bootstrap if recommended after OCP install fail

---

conf/deployment/vsphere/upi_1az_rhcos_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhcos_3m_3w_prod_memory.yaml
conf/deployment/vsphere/upi_1az_rhel_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhel_3m_3w_prod_memory.yaml

Update VmWare production config with memory

---

ocs_ci/deployment/vmware.py
ocs_ci/utility/vsphere.py

Adding post destroy checks for vSphere platform

---

ocs_ci/ocs/constants.py
tests/e2e/logging/test_openshift-logging.py

OCS-651, Respin the elasticsearch pod and check for logs in .operations index

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/ocs.py

Verify pool crush rule is with "type": "zone"
Verifies bug https://bugzilla.redhat.com/show_bug.cgi?id=1763070

Verify pool crush rule is with "type": "zone"

---

docs/getting_started.md
docs/usage.md
ocs_ci/deployment/deployment.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/exceptions.py
ocs_ci/utility/openshift_console.py
tests/ui/test_ui.py

Infra ticket:
https://projects.engineering.redhat.com/browse/OCSQE-172
Fixes: #1153

Enable UI testing

---

ocs_ci/cleanup/aws/cleanup.py

AWS cleanup: skip cloudformation VPCs

---

ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/utility/utils.py

Rely on CSV for fetching ocs version info

---

docs/writing_tests.md
ocs_ci/framework/testlib.py
tests/helpers.py

Decorator to skip tests based on ocs version

---

conf/ocsci/ocp-4.2-config.yaml

Infra ticket:
https://projects.engineering.redhat.com/browse/OCSQE-226

Change RHCOS 4.2 image to the new one

---

tests/helpers.py

pre-pull container images on all nodes during pod creation

---

tests/e2e/test_pvc_attachtime.py
tests/helpers.py

Adds a helper function to measure pod start time and a simple test case.

Test to measure pod start time

---

ocs_ci/ocs/defaults.py
tests/manage/mcg/test_verify_noobaa_status.py

OCS-2084 - Verify noobaa status
Verifies:
bug https://bugzilla.redhat.com/show_bug.cgi?id=1764195
bug https://bugzilla.redhat.com/show_bug.cgi?id=1764195

Testcase to verify noobaa status output

---

ocs_ci/ocs/cluster.py

This includes function:
- to get osd utilization 
- to validate the osd utilization matches with the given one

Function to get osd utilization and validate the osd utilization

---

ocs_ci/ocs/exceptions.py
ocs_ci/ocs/monitoring.py
tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
tests/sanity_helpers.py

Fixing the timeout and JSONDecoderError

Increasing timeout and fixing JSONDecoderError

---

ocs_ci/utility/bootstrap.py

Ensure Nonetype values are not added to the master_ips list for gathering bootstrap data

---

conf/examples/polarion_id.yaml
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/utility/reporting.py
tests/ecosystem/deployment/test_deployment.py

Jira: https://projects.engineering.redhat.com/browse/OCSQE-168

Add polarion ID from config to test_deployment

---

ocs_ci/framework/pytest_customization/marks.py
ocs_ci/ocs/resources/mcg.py
ocs_ci/ocs/resources/pod.py
tests/manage/mcg/conftest.py
tests/manage/mcg/helpers.py
tests/manage/mcg/test_bucket_creation.py
tests/manage/mcg/test_bucket_deletion.py
tests/manage/mcg/test_write_to_bucket.py

This test runs rbd/cephfs and s3 bucket IOs and checks for rgw restarts if any.

Adding test for rgw pod restart in mcg_write_to_bucket

---

conf/ocsci/maximum_production_device_size.yaml
conf/ocsci/minimum_production_device_size.yaml

This PR is created based on the KNIP https://issues.redhat.com/browse/KNIP-1232

Yaml files for minimum and maximum device size support

---

pytest.ini

Pin junit_family to 1.0 to keep a legacy compatibility

---

Jenkinsfile

If the failure happens before acceptance tests, send a brief message
noting the failure and basic metadata including the name of the failed
stage.

Jenkins: Send email on all failures

---

ocs_ci/ocs/resources/pod.py
tests/manage/pv_services/test_create_large_sized_pvc_while_io_in_progress.py

This patch automates BZ,
Bug 1748939 - App pod stuck at ContainerCreating status

Create a large sized PVC while IO in progress (Bug 1748939)

---

conf/ocs_version/ocs-4.2.yaml
conf/ocs_version/ocs-4.3.yaml
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/utils.py

Fix must gather image tag

---

conf/ocs_version/ocs-4.2.yaml
conf/ocsci/upgrade.yaml
conf/ocsci/upgrade_to_next_build.yaml
docs/upgrade.md
docs/usage.md
ocs_ci/deployment/deployment.py
ocs_ci/framework/__init__.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/utils.py
ocs_ci/utility/reporting.py
ocs_ci/utility/utils.py
tests/ecosystem/upgrade/test_upgrade.py

Infra ticket:
https://projects.engineering.redhat.com/browse/OCSQE-227

Allow upgrade between versions like 4.2 -> 4.3

---

ocs_ci/ocs/resources/mcg.py

Fix to verify rgw pod is not present on aws platform

---

tests/conftest.py
tests/libtest/test_requirements.py
tests/manage/monitoring/conftest.py

Add supported_configuration fixture and use it for capacity workloads

supported_configuration fixture

---

tests/conftest.py

fix condition in supported_configuration fixture

---

ocs_ci/ocs/cluster.py
ocs_ci/ocs/constants.py

The functionality to get total IOPS and Throughput of the cluster and calculate their percentage.
Note:
This functionality right now is applicable only for AWS

Functionality to get IOPS and Throughput of cluster for AWS

---

tests/manage/monitoring/prometheus/test_capacity.py

move capacity alerting tests into tier2

---

tests/manage/pv_services/test_pvc_disruptive.py

Issue 1519 test decorator

---

ocs_ci/ocs/resources/pod.py

Fix doc string Args: data type

---

ocs_ci/ocs/cluster.py
ocs_ci/ocs/node.py

Function to get resource utilization(CPU,memory) of a node

---

ocs_ci/ocs/exceptions.py
tests/e2e/workloads/test_pod_from_registry.py
tests/helpers.py

Function to create custom image locally and test to validate

---

ocs_ci/deployment/vmware.py
ocs_ci/utility/vsphere.py

Description: Currently when we teardown the cluster, it
leaves the disks in datastore. This fix will delete the
disk from datastore.

Removes the extra disks from vSphere environment

---

ocs_ci/cleanup/aws/cleanup.py

Added options to skip interactive prompts during AWS cleanup

---

conf/deployment/aws/ipi_1az_rhcos_3m_3w.yaml
conf/deployment/aws/ipi_3az_rhcos_3m_3w.yaml
conf/deployment/aws/upi_1az_rhcos_3m_3w.yaml
conf/deployment/aws/upi_1az_rhel7_3m_3w.yaml
conf/deployment/aws/upi_3az_rhcos_3m_3w.yaml
conf/deployment/aws/upi_3az_rhel7_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml

* Add polarion_ids for deployment job configurations. 
* Created separate config files for vmware vmfs and vsan
Jira: https://projects.engineering.redhat.com/browse/OCSQE-168

Deployment configuration polarion IDs

---

ocs_ci/ocs/constants.py
ocs_ci/utility/environment_check.py

Fix issue with leftover must-gather pod

---

ocs_ci/framework/pytest_customization/marks.py
tests/conftest.py
tests/ecosystem/deployment/test_deployment.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/735

remove @destroy marker from test_deployment test

---

tests/ecosystem/upgrade/test_upgrade.py

Fix upgrade tag for specific image

---

tests/conftest.py

improve log for supported configuration error

---

tests/manage/z_cluster/nodes/test_nodes_maintenance.py

Add ceph health check before doing node drain

---

ocs_ci/utility/vsphere.py

adding option for user to remove disk only from VM

---

ocs_ci/utility/deployment_openshift_logging.py

fixes: #1474

---

setup.py

Fix reportportal import issue

---

ocs_ci/cleanup/aws/cleanup.py

Download openshift installer before destroying clusters

---

ocs_ci/cleanup/aws/cleanup.py

fixes: https://github.com/red-hat-storage/ocs-ci/issues/1575

fix aws-cleanup TypeError

---

ocs_ci/ocs/cluster.py

Function to validate pg_balancer is enabled or not

Function to validate pg_balancer is enabled or not

---

tests/conftest.py

Modify dc_pod_factory fixture in tests/conftest.py

---

tests/helpers.py

This param will help pods to be started on particular labeled node.

Enhance create_pods_parallel function with node_selector param

---

tests/helpers.py

Updated create_pod function for nginx pod raw_block support

Updated create_pod function for nginx pod raw_block support

---

docs/getting_started.md
ocs_ci/utility/utils.py

Jira: [OCSQE-237](https://projects.engineering.redhat.com/browse/OCSQE-237)

Add ability to read in access token for quay private repo authentication

---

tests/e2e/test_pgsql_node_drain.py

Fixed PGSQL Master node drain

---

ocs_ci/deployment/install_ocp_on_rhel.py
ocs_ci/ocs/constants.py
ocs_ci/utility/utils.py

build ocp repo names dynamically

---

ocs_ci/ocs/cluster.py
tests/ecosystem/upgrade/test_upgrade.py

Fix monitor of Ceph health

---

ocs_ci/ocs/machine.py
ocs_ci/ocs/resources/storage_cluster.py
tests/manage/z_cluster/cluster_expansion/test_add_capacity.py

Signed-off-by: annagitel <asandler@redhat.com>

Add capacity final 

---

ocs_ci/ocs/constants.py
ocs_ci/utility/environment_check.py

Fix a leftover from openshift-monitoring namespace

---

tests/e2e/test_pvc_creation_deletion_scale.py
tests/e2e/test_pvc_creation_scale.py

Test case to create 1500 PVC and get PVC creation_time
Script covers 1500 PVC deletion_time too.

Scale Test case to create 1500 PVC and get PVC creation_time

---

conf/ocs_version/ocs-4.2.yaml
conf/ocs_version/ocs-4.3.yaml
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/resources/ocs.py
ocs_ci/ocs/resources/storage_cluster.py
tests/ecosystem/upgrade/test_upgrade.py

Fix for BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1811625
Workaround issue: #1615
After BZ is fixed we can remove channel from config files.

Propagate default channel for specific version

---

ocs_ci/framework/conf/default_config.yaml

Fix default latest tag for must gather default value

---

ocs_ci/ocs/platform_nodes.py
ocs_ci/utility/aws.py

Function to terminate an aws instance

---

ocs_ci/ocs/node.py

This function will help to bring the node network interface down, making the node unresponsive
Creating this separate PR from #1416 because it is needed by other node failure and node replacement tests

Function to make node network down

---

ocs_ci/cleanup/aws/cleanup.py
ocs_ci/cleanup/aws/defaults.py

Addressing enhancements brought up in #1490 as well as some other small fixes.

AWS cleanup enhancements

---

tests/manage/z_cluster/nodes/test_nodes_maintenance.py

Fix Issue #1599

---

ocs_ci/utility/tests/test_utils.py
ocs_ci/utility/utils.py

Fixes https://github.com/red-hat-storage/ocs-ci/issues/1623

don't include secrets from stdout into debug logs

---

tests/conftest.py

Enhance dc_pod_factory with node_selector param

---

ocs_ci/ocs/exceptions.py
ocs_ci/ocs/resources/packagemanifest.py

Report properly issue when channel is missing

---

tests/manage/z_cluster/nodes/test_az_failure.py

test_az_failure: added skip marker

---

ocs_ci/framework/pytest_customization/marks.py
ocs_ci/framework/testlib.py
ocs_ci/utility/utils.py
pytest.ini
tests/conftest.py

Filter tests from report if its skipped because of ocs version mismatch

---

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py

Fixes #1636: Add Capacity: Increase cluster health timeout

---

conf/ocsci/ocp-4.2-ga-config.yaml
conf/ocsci/ocp-4.3-ga-config.yaml

Fix OCP GA versions

---

ocs_ci/deployment/vmware.py
ocs_ci/utility/vsphere.py

Delete folder from templates as post-check

---

setup.py

Require kubernetes 10.0.1 to satisfy latest openshift package requirement

---

ocs_ci/utility/environment_check.py

Fix environment check to exclude specified namespaces and labels

---

docs/usage.md
ocs_ci/framework/main.py
ocs_ci/utility/utils.py

Take OCS version from registry image if passed

---

ocs_ci/ocs/node.py

Increase drain_nodes timeout to 1200 seconds

---

conf/ocsci/fips.yaml
ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2

Fixes: #1594 - Enable FIPS

---

ocs_ci/framework/pytest_customization/ocscilib.py

Ticket:
https://projects.engineering.redhat.com/browse/OCSQE-258

Add --osd-size parameter

---

ocs_ci/deployment/deployment.py
ocs_ci/framework/main.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/ocp.py
ocs_ci/utility/utils.py
tests/ecosystem/upgrade/test_upgrade.py

Allow upgrade to change channel

---

ocs_ci/utility/deployment_openshift_logging.py
tests/conftest.py
tests/e2e/logging/test_openshift-logging.py

Moving deployment of logging to conftest.py

---

conf/ocp_version/ocp-4.2-config.yaml
conf/ocp_version/ocp-4.2-ga-config.yaml
conf/ocp_version/ocp-4.2-ga-minus1-config.yaml
conf/ocp_version/ocp-4.3-config.yaml
conf/ocp_version/ocp-4.3-ga-config.yaml
conf/ocp_version/ocp-4.3-ga-minus1-config.yaml
conf/ocp_version/ocp-4.4-config.yaml
docs/usage.md
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/constants.py
ocs_ci/utility/utils.py
tests/ecosystem/upgrade/test_upgrade.py

Infra ticket:
https://projects.engineering.redhat.com/browse/OCSQE-260

Add --ocp-version CLI param

---

tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py

Test test_pvc_delete_and_verify_size_is_returned_to_backend_pool modified to address issue #1664 
Fixes #1664 

Update test test_pvc_delete_and_verify_size_is_returned_to_backend_pool

---

ocs_ci/ocs/resources/storage_cluster.py
tests/ecosystem/upgrade/test_upgrade.py

Add check of OCS version is correct in the CSV

---

ocs_ci/utility/utils.py

Extract proper OCP version from semantic_version

---

ocs_ci/ocs/monitoring.py
tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py

Adding retry and validating nodes is in ready state

---

ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
ocs_ci/templates/ocp-deployment/install-config-vsphere-upi.yaml.j2

Enable FIPS in vsphere

---

setup.py

Remove kubernetes package from requirements 

---

ocs_ci/framework/pytest_customization/marks.py
ocs_ci/ocs/constants.py
pytest.ini
tests/ecosystem/upgrade/test_upgrade.py
tests/ecosystem/upgrade/test_upgrade_ocp.py

Add OCP ugprade related markers

---

ocs_ci/ocs/node.py
ocs_ci/ocs/resources/pod.py

Log Ceph status in case drain command times out

---

conf/ocs_version/ocs-4.2.yaml
conf/ocs_version/ocs-4.3.yaml
ocs_ci/framework/conf/default_config.yaml
tests/conftest.py

Installs Logging according to OCP version on the cluster

---

conf/ocs_version/ocs-4.4.yaml

Add config for OCS 4.4

---

ocs_ci/deployment/aws.py

Use get_cluster_name instead of ocp_deployment object

---

ocs_ci/ocs/machine.py
ocs_ci/ocs/node.py
tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py

Node replacement - Reactive(IPI)

---

ocs_ci/ocs/machine.py
ocs_ci/ocs/node.py
tests/manage/z_cluster/nodes/test_node_replacement_proactive.py

KNIP-894: Replacement of nodes Proactive

---

ocs_ci/ocs/resources/pod.py

Fix get_all_pods function

---

tests/manage/pv_services/test_reclaim_policy.py

Update test_reclaim_policy to verify PV deletion

---

ocs_ci/ocs/resources/bucket_policy.py

Bucket policy - OBC initialization fix

---

ocs_ci/utility/environment_check.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/1684

environment_check ignores all OCP ns but OCS one

---

ocs_ci/ocs/resources/storage_cluster.py
ocs_ci/utility/utils.py
tests/ecosystem/upgrade/test_upgrade.py

Wait longer time in case of upgrade for HEALTH_OK

---

ocs_ci/ocs/machine.py
ocs_ci/ocs/node.py
tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py

Automatic recovery from failed nodes - Reactive(IPI)

---

tests/manage/mcg/test_bucket_policy.py

Bucket policy - Adding skip for if OCS <4.3

---

ocs_ci/ocs/cluster.py

This PR is to add function that retrieve the Storage capacity in GB to support Issue #1696

Adding get_ceph_capacity function

---

tests/manage/z_cluster/nodes/test_nodes_maintenance.py

BZ 1818613 decorator to TestNodesMaintenance

---

tests/ecosystem/upgrade/test_upgrade_ocp.py

Ignore leftovers post OCP upgrade

---

conf/ocsci/aws_i3_local_storage.yaml
ocs_ci/deployment/deployment.py
ocs_ci/ocs/cluster.py
ocs_ci/ocs/constants.py
ocs_ci/templates/ocs-deployment/local-storage-operator.yaml
ocs_ci/templates/ocs-deployment/local-volume.yaml
ocs_ci/utility/templating.py

Jira: https://projects.engineering.redhat.com/browse/OCSQE-190

Support deployments using LSO for AWS IPI on i3 instance types

---

tests/ecosystem/upgrade/test_upgrade.py

Fix upgrade in stage

---

ocs_ci/cleanup/aws/cleanup.py

Do not delete floating cloudformation stacks

---

tests/ecosystem/upgrade/test_upgrade.py

Fixes: fixes possibility of false return when CSV is not yet upgraded.

Fix max attempt check, range will return integers before final stop.

---

ocs_ci/deployment/vmware.py

Deleting extra disks for RHEL.

---

ocs_ci/ocs/platform_nodes.py

Fixes: #1743 -  Fix vSphere get_vms() method for RHEL workers

---

ocs_ci/ocs/resources/mcg.py
tests/manage/mcg/test_write_to_bucket.py

- Add a highly compressible text file that consistently compresses well
- Adjust the check threshold
- Improve log prints

Stabilize the MCG data reduction test

---

ocs_ci/deployment/aws.py
ocs_ci/utility/aws.py

Fixing teardown of cluster

---

ocs_ci/templates/app-pods/fedora_dc.yaml

Increase memory limit for dc pods

---

tests/manage/z_cluster/test_must_gather.py

added some debug logs on locate_pods_directory function
added exception on make_directory function - will check if path exist before proceed 

added some logs, add exception if logs directory dosent found

---

tests/conftest.py

Health check for all the tier tests

---

requirements-docs.txt

Pin Sphinx version to 2.4.4

---

conf/ocsci/preserve_bootstrap_node.yaml
ocs_ci/deployment/aws.py
ocs_ci/deployment/vmware.py
ocs_ci/framework/conf/default_config.yaml

Jira: [OCSQE-293](https://projects.engineering.redhat.com/browse/OCSQE-293)

Added configuration option to preserve the bootstrap node

---

conf/deployment/aws/upi_1az_rhcos_3m_3w.yaml
conf/deployment/aws/upi_3az_rhcos_3m_3w.yaml

Add missing worker instance type to production configs

---

ocs_ci/ocs/resources/storage_cluster.py

Fix Indentation in storage_cluster

---

ocs_ci/framework/main.py

Add OCS 4.4 to --ocs-version param

---

tests/ecosystem/upgrade/test_upgrade.py

Wait longer time for OSD upgrade

---

conf/deployment/aws/upi_1az_rhel7_3m_3w.yaml
conf/deployment/aws/upi_3az_rhel7_3m_3w.yaml
conf/ocp_version/ocp-4.2-config.yaml
conf/ocp_version/ocp-4.3-config.yaml
conf/ocp_version/ocp-4.4-config.yaml

Disable rhcos_ami

---

ocs_ci/repos/ocp_4_4.repo

Fix ansible repo for OCP 4.4

---

ocs_ci/cleanup/aws/cleanup.py
tests/conftest.py

Fixes: #1811: Fix for a few issues in aws-cleanup

---

tests/manage/pv_services/test_change_reclaim_policy_of_pv.py

This test is the most time consuming in tier1
Fixing some waiting calls

test_change_reclaim_policy_of_pv test optimization

---

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py

Add capacity test: Fix Ceph health check

---

ocs_ci/utility/environment_check.py
ocs_ci/utility/utils.py
tests/conftest.py

Add Ceph health check in environment_check as a finalizer for all test

---

ocs_ci/ocs/resources/storage_cluster.py

Fixes https://github.com/red-hat-storage/ocs-ci/issues/1819

Fix: #1819 - Fix OSD distribution validation to handle multiple OSDs per node

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/platform_nodes.py
ocs_ci/ocs/resources/ocs.py
ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/resources/pvc.py
ocs_ci/utility/vsphere.py
tests/manage/z_cluster/nodes/test_disk_failures.py
tests/sanity_helpers.py

- Automation for disk replacement procedure detailed in https://bugzilla.redhat.com/show_bug.cgi?id=1787236#c16
- Addresses issues:
- https://github.com/red-hat-storage/ocs-ci/issues/1080
- https://github.com/red-hat-storage/ocs-ci/issues/1814

Test case for recovery from disk deletion over vSphere

---

ocs_ci/utility/bootstrap.py

Jira: [OCSQE-254](https://projects.engineering.redhat.com/browse/OCSQE-254)

Still gather bootstrap if no master IPs are gathered

---

ocs_ci/deployment/terraform.py

Increase timeout for terraform commands

---

ocs_ci/deployment/vmware.py
ocs_ci/framework/conf/default_config.yaml

Persistent logs for terraform

---

ocs_ci/utility/prometheus.py
ocs_ci/utility/tests/test_prometheus.py
tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py

Tests for `check_query_range_result()`, necessary for upcoming fixes.

check_query_range_result is function, add tests

---

tests/e2e/logging/test_openshift-logging.py

Skipping logging deployment/tests on OCP 4.4

---

ocs_ci/cleanup/aws/cleanup.py
ocs_ci/ocs/exceptions.py

Jira: [OCSQE-314](https://projects.engineering.redhat.com/browse/OCSQE-314)

Check more than one instance if the cluster_io_tag isn't found on the first

---

tests/conftest.py

Removed logging of skip_condition during test collection

---

ocs_ci/deployment/deployment.py

Add retry for monitoring deployment check

---

ocs_ci/framework/main.py
ocs_ci/framework/pytest_customization/reports.py
pytest.ini
setup.py

Enable internal reportportal host

---

ocs_ci/cleanup/aws/cleanup.py
ocs_ci/ocs/exceptions.py

Log warning instead of raising Error if cluster isn't an OCS cluster

---

ocs_ci/utility/tests/test_utils.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/1648

less strict check of the stderr in unitttest

---

ocs_ci/deployment/deployment.py
ocs_ci/ocs/monitoring.py
ocs_ci/ocs/registry.py

Fix issue with mount command

---

conf/ocp_version/ocp-4.4-candidate-upgrade.yaml

Added config file for OCP upgrade into 4.4 latest rc build

added config file for ocp4.4 candidate channel

---

tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/1841

move assert statements to the end

---

tests/manage/monitoring/conftest.py

To handle use case of test_workload_rbd_cephfs_minimal which writes data to reach a small fraction of the total capacity only (eg. 5%), the test is going increase the target 2x and try again.
If this is still not enough, the test will be skipped, because the idea of tests reaching a small total utilization is to do just that. Moreover this will also skip this test case for any other utilization level, which is easier to read in the test report than the actual failure with negative pvc size.
fixes https://github.com/red-hat-storage/ocs-ci/issues/1731

try to double a small utilization target if met

---

ocs_ci/deployment/vmware.py

checkout version specific openshift installer branch

---

ocs_ci/ocs/fiojob.py
ocs_ci/ocs/ocp.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/1779

fetch logs of all job pods in case of a failure

---

ocs_ci/ocs/ocp.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/1473

run  `oc describe` when wait timeouts

---

conf/ocp_version/ocp-4.4-config.yaml
ocs_ci/framework/conf/default_config.yaml

Infra ticket:
https://projects.engineering.redhat.com/browse/OCSQE-320

Change to OCS 4.4 as default

---

ocs_ci/deployment/vmware.py
ocs_ci/ocs/exceptions.py
ocs_ci/utility/csr.py

Jira: [OCSQE-321](https://projects.engineering.redhat.com/browse/OCSQE-321)

Approve csrs

---

ocs_ci/framework/pytest_customization/marks.py
pytest.ini

Infra ticket:
https://projects.engineering.redhat.com/browse/OCSQE-322

Add tier_after_upgrade

---

ocs_ci/deployment/vmware.py
ocs_ci/utility/csr.py

Ticket:
https://projects.engineering.redhat.com/browse/OCSQE-321

Add one more approve of CSRs after deployment finish

---

ocs_ci/ocs/resources/pvc.py
ocs_ci/templates/CSI/cephfs/storageclass.yaml
ocs_ci/templates/CSI/rbd/storageclass.yaml
tests/helpers.py
tests/manage/pv_services/test_pvc_resize.py

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

Add test case for cephfs and rbd pv resize.

---

ocs_ci/cleanup/aws/defaults.py
ocs_ci/deployment/aws.py

Cluster prefix duplication fix

---

ocs_ci/ocs/fiojob.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/1892

code style fix in fiojob module

---

ocs_ci/cleanup/aws/cleanup.py

Handle case where vpc_obj tags returns a NoneType

---

ocs_ci/deployment/vmware.py

Improving teardown cluster in vSphere

---

ocs_ci/utility/csr.py

* Current CSR functionality approves the alreday
approved CSR.
Fixes: #1902

Fix in Approving CSRs

---

ocs_ci/repos/ocp_4_4.repo

Fix OCP 4.4 repos

---

ocs_ci/ocs/cluster.py
tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py

This PR checks for
* Storage utilization , if its less then runs IO to increase storage utilization,
* Scale OSDs from 3-6, 
* Check for rebalance status 
* Reboot workers

Function to check rebalance status and time taken

---

tests/manage/z_cluster/nodes/test_disk_failures.py

Test detach attach worker volume: Increase health check timeout

---

ocs_ci/cleanup/aws/cleanup.py

Fix: #1929 - Fix in AWS cleanup - replace() instead of strip()

---

tests/conftest.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/749

log events in test namespaces before teardown

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/resources/pvc.py
ocs_ci/ocs/resources/storage_cluster.py

Signed-off-by: annagitel <asandler@redhat.com>
-PVC
-constants
-storage cluster
-POD

helpers for uninstall OCS automation

---

ocs_ci/ocs/resources/storage_cluster.py

Move ceph health to the end of install verification

---

ocs_ci/deployment/vmware.py
ocs_ci/ocs/node.py
ocs_ci/utility/csr.py

* included expected CSRs as argument

Improvement in approve_csr functionality

---

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py

Test add capacity pre upgrade

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/defaults.py
ocs_ci/ocs/resources/bucket_policy.py
tests/manage/mcg/helpers.py
tests/manage/mcg/test_bucket_policy.py

Tier1 tests : bucketwebsite, bucket version, deny effect, multi statement
Tier3 tests: Malformed policies

Bucket policy - Adding additional tier1 and tier3 testcases

---

ocs_ci/ocs/resources/mcg.py

Fix - Add retry to get aws-cloudcred secret

---

tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py

Add tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py: TCs  for KNIP-677: OCS support for Automated fencing/unfencing RWO PV

Add tests for KNIP-677: OCS support for Automated fencing/unfencing RWO PV

---

conf/deployment/baremetal/upi_1az_rhcos_3m_3w.yaml
ocs_ci/deployment/baremetal.py
ocs_ci/deployment/factory.py
ocs_ci/ocs/platform_nodes.py
ocs_ci/utility/utils.py

Add Support to run test over BAREMETAL

---

ocs_ci/ocs/ocp.py

Follow up PR#1921, fixed 1 intenatation

OCP upgreade: fixed indentation

---

tests/e2e/performance/test_vdbench_workload.py

Signed-off-by: Avi liani <alayani@redhat.com>

vdbench | Adding teardown ceph_health_check to the test

---

ocs_ci/ocs/ocp.py
tests/conftest.py
tests/sanity_helpers.py

Fix: #1960 - Wait for cluster connectivity after disruptive node tests

---

ocs_ci/ocs/fiojob.py
tests/manage/monitoring/conftest.py
tests/manage/monitoring/test_workload_fixture.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/1891

constant target in fio storageutilization workload

---

tests/ecosystem/deployment/test_deployment.py

Add sanity test post deployment

---

tests/manage/z_cluster/nodes/test_disk_failures.py

BZ 1830702 decorator to test_recovery_from_volume_deletion

---

ocs_ci/ocs/machine.py
ocs_ci/ocs/resources/ocs.py
ocs_ci/ocs/resources/pod.py
tests/conftest.py
tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
tests/manage/z_cluster/nodes/test_nodes_maintenance.py

Implementing coverage for BZ 1830015

---

tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py

Fix issue:1987

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/storage_cluster.py

This PR is focused on supporting ```ocs_ci/ocs/resources/storage_cluster.py/add_capacity``` over baremetal cluster.
Work in Progress.
Need Suggestions!
Signed-off-by: Anubhav <adeep@redhat.com>

Support add_capacity() over Baremetal Cluster

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/fiojob.py
ocs_ci/ocs/ocp.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/1954

Add error_condition option for wait_for_resource()

---

ocs_ci/ocs/resources/storage_cluster.py

Fix test_add_capacity failure on AWS,vmware

---

conf/ocsci/aws_upi_rhcos_workers.yaml
ocs_ci/deployment/aws.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/exceptions.py
ocs_ci/ocs/platform_nodes.py
ocs_ci/utility/aws.py

This PR implements
1. Functions for adding RHCOS nodes to an existing OCS cluster
2. AWS cloudformation templates are used for adding RHCOS nodes
3. Few aws utility functions 

Add RHCOS node to an existing OCS cluster

---

conf/deployment/aws/ipi_1az_rhcos_lso_3m_3w.yaml
conf/deployment/aws/ipi_3az_rhcos_lso_3m_3w.yaml
conf/deployment/aws/upi_1az_rhcos_lso_3m_3w.yaml
conf/deployment/aws/upi_1az_rhel7_lso_3m_3w.yaml
conf/deployment/aws/upi_3az_rhcos_lso_3m_3w.yaml
conf/deployment/aws/upi_3az_rhel7_lso_3m_3w.yaml

Jira: [OCSQE-340](https://projects.engineering.redhat.com/browse/OCSQE-340)

Production AWS configs for LSO deployments

---

tests/e2e/logging/test_openshift-logging.py

Remove skip from logging testcase

---

ocs_ci/ocs/ocp.py

Minor update to  wait_for_cluster_connectivity

---

tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py

Fix for Issue 1777: Increase timeout to 60 seconds for pod deletion to start

---

conf/ocs_version/ocs-4.5.yaml
ocs_ci/framework/main.py

Infra ticket:
https://projects.engineering.redhat.com/browse/OCSQE-339

Add OCS 4.5 config

---

ocs_ci/ocs/resources/storage_cluster.py

Increase timeout for upgrade

---

tests/manage/monitoring/prometheus/test_capacity.py

add bugzilla marker for utilization tests

---

ocs_ci/ocs/ocp.py

removed duplicate imports from constatns.py

removed specific imports, changed to constants.X

---

ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/cluster.py
tests/helpers.py

Pass out_yaml_format=False in get_ceph_status

---

tests/disruption_helpers.py

Update daemon kill process to handle multiple osd per node

---

ocs_ci/utility/utils.py

Add LSO to generated testrun_name if we are configured for it

---

ocs_ci/ocs/resources/storage_cluster.py

Fixed function description with doc-string.
Signed-off-by: Anubhav Deep <adeep@redhat.com>

Follow up PR to #1825 Support add_capacity() over Baremetal Cluster

---

conf/deployment/aws/ipi_1az_rhcos_lso_3m_3w.yaml
conf/deployment/aws/ipi_3az_rhcos_lso_3m_3w.yaml
conf/deployment/aws/upi_1az_rhcos_lso_3m_3w.yaml
conf/deployment/aws/upi_1az_rhel7_lso_3m_3w.yaml
conf/deployment/aws/upi_3az_rhcos_lso_3m_3w.yaml
conf/deployment/aws/upi_3az_rhel7_lso_3m_3w.yaml

Jira: [OCSQE-340](https://projects.engineering.redhat.com/browse/OCSQE-340)

Added polarion IDs for AWS LSO production configs

---

ocs_ci/ocs/resources/storage_cluster.py

Fixes: #2064  
Fix incorrect localvolume name

Fix issue 2064: Correction in LocalVolume name

---

tests/manage/mcg/test_object_integrity.py
tests/manage/mcg/test_write_to_bucket.py

Fixes test failures caused by #2051

MCG-Test-Fix: Replace resources with clients

---

ocs_ci/deployment/vmware.py
ocs_ci/ocs/constants.py

Changing openshift installer to use release-4.3 branch

---

setup.py

Updated requests dependency version to 2.23.0

---

ocs_ci/cleanup/aws/cleanup.py

Jira: https://projects.engineering.redhat.com/browse/OCSQE-264

Keep a list of remaining clusters to log at the end of the execution

---

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py

Move add_capacity test as last one

---

ocs_ci/framework/conf/default_config.yaml

Move OCP 4.4 as default

---

ocs_ci/deployment/vmware.py

updating memory for nodes in vSphere platform

---

ocs_ci/deployment/deployment.py

Asserting on empty list for PVs creation

---

ocs_ci/framework/__init__.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/utility/aws.py

store our auth details in simple s3 bucket and read secrets from dict.

get secrets from auth file from s3

---

requirements.txt
setup.py

Move elasticsearch and numpy from requirements.txt to setup.py

---

tests/helpers.py
tests/manage/pv_services/test_change_reclaim_policy_of_pv.py

This will also fix issue 1993.
Fixes #1993 

Function to wait for image/sub-volume deletion in backend

---

ocs_ci/ocs/node.py
tests/manage/z_cluster/cluster_expansion/test_node_expansion.py

- Added add node code for AWS upi rhel and  AWS upi coreos

Cluster expansion : Add node AWS+UPI --> RHCOS+RHEL

---

ocs_ci/deployment/deployment.py

Fix in updating portable field in LSO deployment

---

ocs_ci/deployment/vmware.py

Wait for CSR to generate and approve after bootstrapping is completed

Wait for CSR to generate and approve after bootstrapping is completed

---

ocs_ci/deployment/vmware.py

separate function for updating machine configuration

---

docs/usage.md
ocs_ci/framework/main.py
ocs_ci/ocs/resources/storage_cluster.py
tests/ecosystem/deployment/test_deployment.py

Install previous version from the new build

---

conf/ocp_version/ocp-4.5-config.yaml

Ticket:
https://projects.engineering.redhat.com/browse/OCSQE-339

Add OCP 4.5 config file

---

ocs_ci/cleanup/aws/cleanup.py

Jira: [OCSQE-264](https://projects.engineering.redhat.com/browse/OCSQE-264)

Write failed cluster deletions to a file

---

tests/e2e/performance/test_pod_reattachtime.py

Sending new PR for https://github.com/red-hat-storage/ocs-ci/pull/1171. We almost lost this valuable effort from @fmarchioni

Adds test for pod reattach time

---

docs/README.md
docs/deployment_without_ocs.md
index.rst

fixes https://github.com/red-hat-storage/ocs-ci/issues/2065

docs: add deployment_without_ocs.md

---

ocs_ci/ocs/resources/pod.py

Fix labels in getting all pods

---

tests/disruption_helpers.py

Fix retry for selection daemon

---

tests/e2e/performance/test_small_file_workload.py

Changing the formula of deviation percentage calculation and adding calculation of the total data set.

Smallfiles | change the deviation calculation

---

ocs_ci/ocs/fiojob.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/2014

fiojob: fetch ceph full rations from osd map

---

ocs_ci/ocs/registry.py

Fix registry deployment

---

tests/manage/z_cluster/nodes/test_disk_failures.py

BZ 1825675 for test_detach_attach_worker_volume

---

ocs_ci/ocs/constants.py
ocs_ci/utility/performance_dashboard.py
tests/e2e/performance/test_io_performance.py

Add functionality to push data to perf dashboard

---

ocs_ci/ocs/cluster.py
ocs_ci/ocs/resources/storage_cluster.py

Fixes: #2169
Fixing verification as we see issue in this BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1840084

Fix verification of OSDs and MONs backed by PVC

---

conf/ocp_version/ocp-4.4-config.yaml
conf/ocp_version/ocp-4.4-ga-config.yaml

Updating templates for ocp 4.4 version

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/platform_nodes.py
ocs_ci/utility/csr.py
tests/manage/z_cluster/cluster_expansion/test_node_expansion.py

Adding libraries for adding RHCOS nodes - vSphere platform

---

tests/e2e/performance/test_small_file_workload.py

Fix #2137 - Smallfile getting user and email

---

ocs_ci/framework/pytest_customization/marks.py

Correcting the skip reasons

---

ocs_ci/cleanup/aws/cleanup.py
ocs_ci/cleanup/aws/defaults.py

Fix AWS cleanup and reduce time for 16 hours for PR validation

---

conf/deployment/vsphere/upi_1az_rhcos_vmfs_directpath_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhcos_vmfs_rdm_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhcos_vmfs_vmdk_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_directpath_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_rdm_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhel_vmfs_directpath_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhel_vmfs_rdm_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhel_vmfs_vmdk_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhel_vsan_directpath_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhel_vsan_rdm_3m_3w.yaml
conf/deployment/vsphere/upi_1az_rhel_vsan_vmdk_3m_3w.yaml

Production config files for LSO Deployment

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/node.py
ocs_ci/ocs/resources/storage_cluster.py

AWS LSO ceph osd tree verification

---

ocs_ci/framework/pytest_customization/marks.py
tests/e2e/performance/test_vdbench_workload.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/2049

Add mark to run tests only in red hat internal lab
