- tests/manage/z_cluster/nodes/helpers.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
- tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
- Fixes https://github.com/red-hat-storage/ocs-ci/issues/2165
- Also move the pods validation section from the different test files to a common helpers file
> Fix node replacement tests to validate also OSD prepare and DC pods

- ocs_ci/repos/ocp_4_3.repo
> Fix OCP 4.3 repo for RHEL

- ocs_ci/repos/ocp_4_2.repo
- ocs_ci/repos/ocp_4_4.repo
> Fix RHEL repos for ocp 4.4 and 4.2

- ocs_ci/repos/ocp_4_2.repo
- ocs_ci/repos/ocp_4_3.repo
> Fix RHEL repos for OCP 4.2 and 4.3

- Jenkinsfile
I'm still waiting to get this tested in the downstream CI.
> downstream ci: tag successful builds with latest-stable-X.Y

- conf/ocp_version/README.md
- conf/ocs_version/README.md
- conf/ocs_version/ocs-4.2.yaml
- conf/ocs_version/ocs-4.3.yaml
- conf/ocs_version/ocs-4.4.yaml
- conf/ocs_version/ocs-4.5.yaml
- index.rst
- ocs_ci/framework/main.py
Jira: [OCSQE-348](https://projects.engineering.redhat.com/browse/OCSQE-348)
> Load default ocp version conf if ocs version or registry image is provided

- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/localstorage.py
The idea is to segregate all the local-storage related functions in a proper module.
This PR aims to fix that.
Signed-off-by: Anubhav Deep <adeep@redhat.com>
> Added local-storage related functions in utility module properly

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/resources/pod.py
> Catching the exception in retry for checking pods in monitoring NS

- ocs_ci/framework/pytest_customization/marks.py
- tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
> Skip stop/shutdown test cases on lso based cluster

- tests/ecosystem/upgrade/test_upgrade.py
> Change order for upgrade mons and mgr

- tests/sanity_helpers.py
> provide interface while creating resources using sanity helpers

- ocs_ci/utility/vsphere.py
> Fixing doc string for get_lunids

- conf/ocs_version/ocs-4.2.yaml
- conf/ocs_version/ocs-4.3.yaml
- conf/ocs_version/ocs-4.4.yaml
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/constants.py
> Use latest-stable

- ocs_ci/deployment/deployment.py
> Assert when number of PVs created doesn't match with expected number

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/defaults.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/resources/mcg.py
- ocs_ci/ocs/resources/storage_cluster.py
- tests/manage/mcg/test_verify_noobaa_status.py
validate the the non optional components of noobaa. (issue #1871 )
> validate noobaa status

- ocs_ci/utility/csr.py
> Adding retry for approving CSRs

- tests/conftest.py
> Log thread name in ocs logger

- tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
> Adding wait time after the restart/stop nodes

- conf/ocsci/disconnected_cluster.yaml.example
- ocs_ci/ocs/utils.py
- ocs_ci/utility/utils.py
- tests/conftest.py
- tests/helpers.py
* mirror images required by various tests on demand
* configure http_proxy and https_proxy env variables in newly created pods, to redirect requests for example for package installation through proxy
> Changes for disconnected cluster

- ocs_ci/deployment/aws.py
> Changing the bucket names based on ocp versions

- ocs_ci/utility/performance_dashboard.py
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/2233
> Fix get version for ocs to push to dashboard

- ocs_ci/framework/conf/default_config.yaml
> Default OCP and OCS versions to 4.5

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/ocp.py
- ocs_ci/utility/utils.py
- tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
Updated test_node_expansion.py to apply ocp workaround on new RHEL nodes
Fixes https://github.com/red-hat-storage/ocs-ci/issues/2238
> Fix for issue #2238

- tests/e2e/logging/test_openshift-logging.py
W/A issue:
https://github.com/red-hat-storage/ocs-ci/issues/2278
> WA: Skip logging deployment for OCP 4.5

- tests/e2e/performance/test_fio_benchmark.py
Signed-off-by: Avi liani <alayani@redhat.com>
> FIO | Pushing results into codespeed

- tests/e2e/workloads/couchbase/test_couchbase.py
> Update: tests/e2e/workloads/couchbase/test_couchbase.py

- tests/manage/monitoring/prometheus/test_noobaa.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/2281
> add pending status to noobaa alerts

- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
- ocs_ci/utility/vsphere.py
> Supporting LSO deployment for VMFS datastore in vSphere platform

- ocs_ci/ocs/node.py
- ocs_ci/ocs/pgsql.py
- setup.py
- tests/e2e/workloads/pgsql/test_pgsql.py
- tests/e2e/workloads/pgsql/test_pgsql_node_drain.py
- tests/e2e/workloads/pgsql/test_pgsql_node_reboot.py
- tests/e2e/workloads/pgsql/test_pgsql_pod_respin.py
Signed-off-by: Oded Viner <odedviner@localhost.localdomain>
Add more data to analyze the CI results more effectively.
1.Measuring the time pgbench pods reach to "Completed" state
2.Get CPU usage and memory usage on relevant nodes (VM) and print to table
3.Get pgbech pod data and print to table
> pgsql_debug

- ocs_ci/ocs/amq.py
- tests/e2e/workloads/amq/test_amq_streamer_creation.py
> Fix issue-2299 and also updated new tc id

- tests/manage/monitoring/conftest.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/1992
> add ceph health check to alerts tests

- tests/helpers.py
> Fix for issue #2319: Modified helper functions used for verifying backend volume deletion

- ocs_ci/ocs/cluster.py
Enhanced function to get fetch output from dict than string
Updated function get_rebalance_status() similarly to get ceph status output in dict than string
Updated log.warning in validate_osd_utilization()
> Enhanced get_ceph_cluster_iops() function

- ocs_ci/ocs/node.py
Signed-off-by: Avi liani <alayani@redhat.com>
> Fix #2329 with get provider name

- ocs_ci/utility/utils.py
> Fix issue with missing imge_id for new DS builds

- tests/e2e/performance/test_fio_benchmark.py
Fixes the following two issues. 
a. it reports about sequential pattern, but it ran random read/write -> fixes with modifying the cr file. 
b. it report on deviation > 5% also when it was less than 5% -> For now, we simply log the variance.
> Fixes minor issues around FIO test

- tests/conftest.py
- tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
- Add node_name param to pod_factory_fixture in tests/conftest.py
- Improvements in tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
> Enhancements for pod_factory_fixture and test_dynamic_pvc_accessmodes_with_reclaim_policies.py

- tests/manage/z_cluster/nodes/test_disk_failures.py
Fixes : #2207 
Signed-off-by: rachael <rgeorge@redhat.com>
> Fix disk replacement procedure for VMWare clusters

- requirements-dev.txt
- requirements-docs.txt
- setup.py
> Freeze requirement versions

- pytest.ini
> Pin junit_family to xunit1

- ocs_ci/ocs/cluster_load.py
- tests/conftest.py
> Cluster load: Do not load during deployment

- ocs_ci/framework/conf/default_config.yaml
> Have 2 noobaa endpoints as default

- ocs_ci/ocs/pgsql.py
- ocs_ci/ocs/ripsaw.py
> Fix: Fails to get pgsql pods when namespace is switched.

- tests/ecosystem/upgrade/test_upgrade.py
> Fix order in upgrade for subscription

- setup.py
> changing gevent version to compatible with python3.8

- conf/deployment/aws/ipi_1az_rhcos_lso_3m_3w.yaml
- conf/deployment/aws/ipi_3az_rhcos_lso_3m_3w.yaml
- conf/deployment/aws/upi_1az_rhcos_lso_3m_3w.yaml
- conf/deployment/aws/upi_1az_rhel7_lso_3m_3w.yaml
- conf/deployment/aws/upi_3az_rhcos_lso_3m_3w.yaml
- conf/deployment/aws/upi_3az_rhel7_lso_3m_3w.yaml
- conf/ocsci/aws_i3_local_storage.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/templates/ocs-deployment/local-volume.yaml
- ocs_ci/utility/localstorage.py
- tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
> AWS LSO alignment with doc

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/pod.py
- tests/conftest.py
- tests/helpers.py
- tests/manage/mcg/helpers.py
- tests/manage/z_cluster/cluster_exp_helpers.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
- tests/manage/z_cluster/pvc_ops.py
addressing comments from old PR https://github.com/red-hat-storage/ocs-ci/pull/1751
> Add capacity with cluster filling, entry and exit criteria 

- conf/ocsci/ibm_cloud_upi.yaml
- conf/ocsci/live-must-gather.yaml
- ocs_ci/ocs/utils.py
- ocs_ci/ocs/version.py
- ocs_ci/utility/localstorage.py
- tests/conftest.py
> Fix few issues for IBM cloud execution

- ocs_ci/deployment/vmware.py
- ocs_ci/utility/csr.py
> Include retry mechanism for get_pending_csr

- ocs_ci/deployment/vmware.py
> Removing the bootstrap node since new vSphere provider plugin is released

- tests/conftest.py
> Fixing teardown for aborted cluster

- tests/conftest.py
> Multiarch container for fio

- tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
OCS-302 - FT-OCP-PVCExpand- Validate PVC expand of already expanded PVC
> Test to verifiy PVC can be expanded more than once

- ocs_ci/ocs/constants.py
- tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
fixes https://github.com/red-hat-storage/ocs-ci/issues/2348
> Don't check RGW metrics on any cloud platform

- tests/conftest.py
- Created fixture for running couchbase workload
> Fixture for running couchbase workload

- tests/e2e/workloads/amq/test_amq_streams.py
> Test case to create amq cluster and run open messages on it

- conf/ocp_version/ocp-4.2-config.yaml
- conf/ocp_version/ocp-4.2-ga-config.yaml
- conf/ocp_version/ocp-4.2-ga-minus1-config.yaml
- conf/ocp_version/ocp-4.3-config.yaml
- conf/ocp_version/ocp-4.3-ga-config.yaml
- conf/ocp_version/ocp-4.3-ga-minus1-config.yaml
- conf/ocp_version/ocp-4.4-config.yaml
- conf/ocp_version/ocp-4.4-ga-config.yaml
- conf/ocp_version/ocp-4.5-config.yaml
- ocs_ci/deployment/terraform.py
- ocs_ci/deployment/vmware.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/constants.py
- ocs_ci/utility/utils.py
Downloading appropriate terraform binary version in ocs-ci according to ocp release
> Downloading terraform binary version in ocs-ci

- tests/e2e/performance/test_fio_benchmark.py
Setting number of pods to not more then 50 (by changing the file size)
and the total data set to 40% of total capacity.
> FIO| Setting dataset to 40% of total capacity

- ocs_ci/framework/conf/default_config.yaml
- tests/ecosystem/upgrade/test_logging_upgrade.py
> Upgrade logging post OCP upgrade

- ocs_ci/utility/performance_dashboard.py
Adding some logging
Fix the version_get methodology
> performane_dashboard | Changing the platform to be more generic.

- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/localstorage.py
> Enhance add osd for LSO

- ocs_ci/ocs/ripsaw.py
> minor fix: postgress pods namespace

- ocs_ci/ocs/cluster.py
- tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
Fixing timeout issue: https://github.com/red-hat-storage/ocs-ci/issues/2246
Increase timeout and update ceph_health cluster query.
> Fixing timeout issue in scale test

- conf/ocp_version/ocp-4.5-config.yaml
- ocs_ci/framework/conf/default_config.yaml
> Updating RHCOS template

- ocs_ci/cleanup/aws/cleanup.py
- ocs_ci/deployment/aws.py
- ocs_ci/utility/aws.py
> Delete mcg target and image-registry buckets during cluster teardown and aws cleanup

- ocs_ci/ocs/node.py
Added new function : get_node_name
> added function: get_node_name

- ocs_ci/ocs/ocp.py
…es/2312)
Signed-off-by: Oded Viner <odedviner@localhost.localdomain>
fix work around:
https://github.com/red-hat-storage/ocs-ci/issues/2312
> fix work around 

- tests/conftest.py
> Skip deployment of tool box for OCP ONLY deployments

- ocs_ci/utility/performance_dashboard.py
> pushing the data to code speed

- docs/deployment_without_ocs.md
fixes https://github.com/red-hat-storage/ocs-ci/issues/2406
> docs: note about latest tags of ocs dev images

- tests/e2e/workloads/jenkins/test_jenkins_pod_respin.py
OCS-2205- Jenkins application: Restart MGR pod
OCS-2204- Jenkins application: Restart MON pod
OCS-2179- Jenkins application: Restart OSD pod
> add jenkins pod respin tests

- conf/ocsci/aws_i3_local_storage.yaml
- ocs_ci/deployment/deployment.py
> Enable limits for production AWS LSO deployments

- tests/helpers.py
> Enable Registry testcase to run on Proxy env

- tests/conftest.py
[jenkins fixture.txt](https://github.com/red-hat-storage/ocs-ci/files/4891054/jenkins.fixture.txt)
*attached test log
> add jenkins fixture

- ocs_ci/framework/pytest_customization/ocscilib.py
> Make collecting of the logs more error prone for internall error

- ocs_ci/utility/utils.py
> Fix in deprecated warning for oc exec command

- ocs_ci/deployment/deployment.py
> Fix for allow lower instances in ocs 4.5

- ocs_ci/templates/ocp-deployment/terraform_4_5.tfvars.j2
> Fixing variables in template

- ocs_ci/deployment/vmware.py
> Use terraform log to download terraform binary version

- ocs_ci/ocs/utils.py
Allow re-collecting of Noobaa DB dump with a limitation of 5 attempts
> Try again collecting DB dump

- conf/deployment/vsphere/upi_1az_rhcos_vmfs_lso_vmdk_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vmfs_lso_vmdk_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vsan_lso_vmdk_3m_3w.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/vmware.py
> LSO VMDK installation for vSphere platform

- tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
> Enable add node test over Azure

- ocs_ci/templates/workloads/jenkins/buildconfig.yaml
- tests/e2e/workloads/jenkins/test_jenkins.py
> change buildconfig.yaml (jenkins)

- ocs_ci/ocs/monitoring.py
> Check for pvc creation in monitoring NS

- ocs_ci/ocs/utils.py
> Fix never ending noobaa db dump

- ocs_ci/ocs/constants.py
- ocs_ci/utility/localstorage.py
Fixes #2324 
- Fix LSO operator channel
- Fix wrong sc name
> Fix lso operator channel

- conf/ocsci/noobaa_endpoints_2.yaml
- conf/ocsci/noobaa_endpoints_scale.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/utils.py
- tests/conftest.py
- tests/ecosystem/deployment/test_deployment.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/2376
> Move Noobaa max endpoint change to deploy_ocs() and change the minimum to be 2 as a default for clusters that meet the min requirements 

- conf/ocsci/flexy_baremetalpsi_upi.yaml
> Make default registry svc to 4.5

- ocs_ci/ocs/utils.py
> Fix db dump collection

- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/resources/ocs.py
- ocs_ci/ocs/resources/storage_cluster.py
Jira: [OCSQE-360](https://projects.engineering.redhat.com/browse/OCSQE-360)
> Improved report portal tagging

- ocs_ci/ocs/elasticsearch.py
Adding functions to open connection, getting list of all 'tables' in the ES and copy all data to different ES server
> Adding functionality to ElasticSearch module

- tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
> Update test test_pvc_expansion to check pod status before running IO

- ocs_ci/ocs/cluster.py
> Wait for Noobaa health instead of calling it once

- docs/results.md
> Added doc around report portal tags

- conf/ocp_version/ocp-4.4-ga-config.yaml
> Use OCP 4.4 stable channel for GA version

- ocs_ci/ocs/pillowfight.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/2536
> Added wait_for_delete() for namespace post deletion of namespace

- conf/ocp_version/ocp-4.5-config.yaml
- ocs_ci/framework/conf/default_config.yaml
> Updating RHCOS 4.5 template

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/storage_cluster.py
Workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1857802.
To be tracked with https://github.com/red-hat-storage/ocs-ci/issues/2532
> W/A for bug 1857802 - only 1 RGW pod post upgrade to 4.5

- ocs_ci/ocs/cluster_load.py
- ocs_ci/utility/prometheus.py
- tests/conftest.py
> Cluster load: Mute Prometheus query logs for logging cluster metrics in the test background + few minor fixes in ClusterLoad

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/vmware.py
- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/constants.py
- ocs_ci/utility/load_balancer.py
- ocs_ci/utility/utils.py
- ocs_ci/utility/vsphere_nodes.py
Updating clock.redhat.com to all compute nodes when clock
skew is detected on health check during deployment
> Fix for clock mon skew detected

- tests/manage/z_cluster/test_ceph_default_values_check.py
Fixes: #1861 
Corrective measure for BZ 1805674
> Test to check ceph values on the cluster with the default values

- ocs_ci/ocs/resources/mcg.py
- tests/conftest.py
- tests/manage/mcg/test_multi_region.py
> Improved AWS cred-req flow, create cred-reqs only for tests that require them

- ocs_ci/deployment/deployment.py
> Remove pg autoscale workaround

- ocs_ci/ocs/jenkins.py
- tests/e2e/workloads/jenkins/test_jenkins_node_drain.py
> Add Jenkins Drain node tests

- tests/ecosystem/upgrade/test_resources.py
> Disable tests that generate IOs during upgrade

- ocs_ci/ocs/amq.py
- tests/e2e/workloads/amq/test_amq_streamer_creation.py
> Export all amq workload run outputs to google spreadsheet

- ocs_ci/cleanup/aws/cleanup.py
- ocs_ci/deployment/aws.py
- ocs_ci/utility/aws.py
> Delete apps record set before destroying security group stack for AWS UPI teardown

- tests/ecosystem/upgrade/test_resources.py
> Add back post_uprade marker to test_storage_pods_running that was removed in PR 2518

- ocs_ci/framework/__init__.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/utils.py
- ocs_ci/templates/ocs-deployment/toolbox_pod.yaml
> setup ceph client when cluster is in independent mode

- tests/manage/pv_services/test_pvc_disruptive.py
- tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Add bugzilla marker in test cases - bug 1860891
> Add bugzilla marker in test cases - bug 1860891

- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/ocp.py
- ocs_ci/utility/utils.py
> Configure Chrony for vsphere platform

- ocs_ci/utility/utils.py
> Fix parsing version from stable tag

- ocs_ci/utility/aws.py
> Changed a few warning level log messages to info

- tests/helpers.py
> proxy config: configure also no_proxy env variable

- ocs_ci/ocs/amq.py
- tests/conftest.py
- tests/e2e/workloads/amq/test_amq_node_reboot_and_shutdown.py
- tests/e2e/workloads/amq/test_amq_pod_respin.py
- tests/e2e/workloads/amq/test_amq_streams.py
> Testcases to reboot/shutdown and recovery node when amq workload is running

- conf/ocp_version/ocp-4.5-ga-config.yaml
- conf/ocp_version/ocp-4.5-ga-upgrade.yaml
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/utility/localstorage.py
> 4.5 ga fixes

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/templates/ocp-deployment/install-config-vsphere-upi.yaml.j2
> Include hostprefix in vSphere

- ocs_ci/utility/aws.py
> Except boto errors when deleting cluster buckets

- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
> Skip add capacity testcase for BM

- docs/usage.md
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/cluster_load.py
- setup.py
> Fine tunings in ClusterLoad

- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/utility/environment_check.py
> Collect OCS must gather upon setup/teardown failures

- tests/conftest.py
> Fix arguments issue in bucket factory fixture

- ocs_ci/ocs/node.py
> Improve logging in node.wait_for_nodes_status

- tests/e2e/workloads/jenkins/test_jenkins_node_reboot.py
> Jenkins Node Reboot

- tests/helpers.py
> Fix storagecluster_independent_check

- ocs_ci/ocs/cluster.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
- tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
> Wait for rebalance post add capacity test

- conf/ocsci/io_in_bg.yaml
- docs/usage.md
- ocs_ci/deployment/deployment.py
- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/cluster_load.py
- ocs_ci/utility/utils.py
Allows usage of custom images for example, like MCG or RHCS
> Allow modifying OCS CSV pre OCS deployment

- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
> Skip add capacity for external mode RHCS

- ocs_ci/utility/performance_dashboard.py
- tests/e2e/performance/test_pvc_creation_performance.py
- tests/e2e/performance/test_pvc_deletion_performance.py
> fixed variable and flake errors

- ocs_ci/utility/aws.py
> Check for app record sets in AWS UPI

- tests/e2e/workloads/jenkins/test_jenkins_node_drain.py
> change polarion id (Worker node drain, Jenkins test)

- ocs_ci/ocs/scale_lib.py
- tests/e2e/scale/test_scale_pvc_expand.py
> Scale test cases for pvc expansion.

- tests/conftest.py
fixes https://github.com/red-hat-storage/ocs-ci/issues/2646
> fix links to mcg_obj

- ocs_ci/ocs/fio_artefacts.py
- tests/conftest.py
- tests/ecosystem/upgrade/conftest.py
> move fio definitions to fio_artefacts file

- ocs_ci/cleanup/aws/cleanup.py
- ocs_ci/cleanup/aws/defaults.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/aws.py
- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Add functionality for testing a node replacement proactive when running a cluster with AWS UPI.
> Node replacement proactive with AWS UPI

- ocs_ci/ocs/registry.py
- ocs_ci/utility/svt.py
- tests/e2e/registry/test_registry_pod_respin.py
> Testcase for registry workload when backed by OCS respin of ceph pods

- ocs_ci/ocs/cluster_load.py
Few minor changes in ClusterLoad, that are needed in order to adjust to the performance of the new OCS QE HW 
> Cluster load: Adjustments to the new OCS QE HW

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/storage_cluster.py
Fixes #2532
Reverts red-hat-storage/ocs-ci#2533
> Revert "W/A for bug 1857802 - only 1 RGW pod post upgrade to 4.5"

- ocs_ci/ocs/fio_artefacts.py
- tests/ecosystem/upgrade/test_noobaa.py
> fix mcg workload tests

- tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
> test_monitoring_delete_pvc (OCS-638)

- tests/e2e/registry/test_registry_pull_and_push_images_to_registry.py
> Tier1 testcase to pull and push images to registry backed by OCS

- ocs_ci/ocs/constants.py
- tests/e2e/performance/test_fio_benchmark.py
Since hit some problems with Port-FWD to ES server on BM cluster, and the Internal ES server is needed only in the cloud environment, it will be created only in the cloud.
> Create the ES only in the cloud

- ocs_ci/ocs/defaults.py
- ocs_ci/ocs/resources/storage_cluster.py
> CSI Driver verification in OCS 4.6

- conf/ocsci/README.md
- conf/ocsci/openshift-console/README.md
- conf/ocsci/openshift-console/openshift_console_no_failfast.yaml
- index.rst
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/utility/openshift_console.py
> Fix UI testing for new openshift-console

- ocs_ci/ocs/cluster_load.py
- tests/conftest.py
- tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
> Add functionality to pause the cluster load

- ocs_ci/framework/pytest_customization/marks.py
> Replace 'independent_mode' key with 'external_mode'

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/templates/app-pods/fedora_dc.yaml
- tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Fixes: #2205
Fixes: #1943  
Fixes: #2101 
Updated the following files:
- `ocs_ci/templates/app-pods/fedora_dc.yaml` 
- `ocs_ci/framework/pytest_customization/marks.py`
- `tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py`
> Fix fedora dc pod restarts and update tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py

- ocs_ci/utility/aws.py
> Add Permission exception for update_config_from_s3

- ocs_ci/ocs/ripsaw.py
- tests/e2e/performance/test_fio_benchmark.py
This is to fix the first issue in Jenkins build #10799
> Adding retries to the ripsaw.get_uuid function

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/cluster_load.py
- tests/conftest.py
> Cluster load fixture: use conf file instead of a text file

- tests/e2e/logging/test_openshift-logging.py
From OCP 4.5, The usage of elasticsearch5 is deprecated and elasticsearch6 is in use. Hence it needs some changes in the testcases to run on version on OCP 4.5 and lesser than that.
There are few changes in the way we fetch the logs of a project and few command changes.
> Enabling logging testcases to run on OCP 4.5 and lesser

- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Addresses the failure seen in run ID 1596649015
> Increase timeout in add capacity test waiting for rebalance to complete to 5400 seconds

- ocs_ci/deployment/deployment.py
- ocs_ci/templates/ocs-deployment/local-volume.yaml
> Update LSO limits

- tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
> skip test_ceph_rbd_metrics_available if ocs version < 4.6

- ocs_ci/ocs/resources/pvc.py
> Make PVC.size to be flexible for any deivce size unit

- ocs_ci/framework/pytest_customization/ocscilib.py
Jira: [OCSQE-368](https://projects.engineering.redhat.com/browse/OCSQE-368)
> Added --ocp-installer-version cli option for deploying OCP with a specific build

- ocs_ci/ocs/resources/objectbucket.py
- ocs_ci/ocs/resources/rgw.py
> Fix for RGW test failures 

- tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
> Skip restart nodes over BM

- ocs_ci/ocs/resources/pod.py
Closes #2742 
The leader pod can be obtained using these commands:
"oc get leases openshift-storage-rbd-csi-ceph-com"
"oc get leases openshift-storage-cephfs-csi-ceph-com"
> Fix plugin_provisioner_leader to find the leader pod using oc get leases command

- ocs_ci/deployment/vmware.py
- ocs_ci/utility/utils.py
> Increasing timeout for machines to comeup

- ocs_ci/ocs/scale_pgsql.py
- tests/e2e/scale/test_scale_pgsql.py
This is a pgsql scale test.  New worker nodes will be added to the cluster, and then pgsql pods will be created on the new created worker nodes using node_selector and scale label.
> Pgsql scale test

- ocs_ci/ocs/bucket_utils.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/mcg.py
- ocs_ci/ocs/resources/objectbucket.py
- tests/conftest.py
- tests/manage/mcg/test_namespace.py
Signed-off-by: romayalon romy2232@gmail.com
1. Added new test_namespace to handle the tier1 tests for namespace feature.
2. Added option to send signed requests to AWS. (was needed for uploading/downloading files directly to/from AWS - when the bucket isn't public)
3. changed the create_new_aws_connection function to be compatible for the new cloud manager changes.
> Tier1 tests - MCG - Namespace feature

- ocs_ci/deployment/aws.py
- ocs_ci/ocs/constants.py
1. Repo has been moved to flexy-templates location
2. Add IAAS_PLATFORM env variable
> openshift-misc related changes

- ocs_ci/utility/aws.py
> Ensure a hosted zone was returned before attempting to delete the apps record set

- tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
…sion
Add ceph health check in teardown part of test test test_resource_deletion_during_pvc_expansion
> Add health check in test

- ocs_ci/ocs/resources/storage_cluster.py
Snapshots are enabled in OCS 4.6 so ocs-ci should not panic after
seeing snapshot container inside the csi provisioners.
Also, CSI_ENABLE_SNAPSHOTTER will not be set to false because
snapshots would be enabled by default.
Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>
> ocs-ci should not hit the assert in 4.6 if snapshot container is present

- conf/ocp_version/ocp-4.6-config.yaml
- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
- ocs_ci/utility/utils.py
> Changes needed for OCP 4.6 on vSphere platform

- ocs_ci/deployment/deployment.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/resources/storage_cluster.py
> Validate Noobaa endpoints according to min of 1 if the cluster doesn't meet the min requirements

- tests/conftest.py
> Skip downloading mcg cli for OCP deployments

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/pvc.py
- ocs_ci/templates/CSI/cephfs/pvc-clone.yaml
- ocs_ci/templates/CSI/rbd/pvc-clone.yaml
- tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py
Verify pvc to pvc cloning by following steps:
1. Create a PVC
2. Bind it to an app
3. Create a test file to validate clone later.
4. Clone a pvc from existing one.
5. Bind the cloned pvc to an app.
6. Verify if the test file is present in the clone.
Signed-off-by: Yug <yuggupta27@gmail.com>
> Add test case for pvc to pvc cloning.

- ocs_ci/ocs/constants.py
- ocs_ci/templates/CSI/cephfs/pvc-restore.yaml
- ocs_ci/templates/CSI/cephfs/snapshot.yaml
- ocs_ci/templates/CSI/cephfs/snapshotclass.yaml
- tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py
Added another parameter to the snapshot test case so that it tests
CephFS snapshot also along with rbd snapshot.
Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>
> cephfs: enhanced snapshot test case to test CephFS snapshot feature

- tests/conftest.py
> Skip mcg operations when deleting the cluster

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/storage_cluster.py
> Validate 1 RGW pod post upgrade

- ocs_ci/deployment/vmware.py
> Skip installation of chrony for VMFS datastores

- conf/ocsci/flexy_baremetalpsi_upi.yaml
- ocs_ci/deployment/flexy.py
- ocs_ci/ocs/constants.py
> generate installer payload dynamically from ocp installer version

- ocs_ci/ocs/uninstall.py
Signed-off-by: annagitel <asandler@redhat.com>
> Uninstall changes + LSO 

- tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
- tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
- tests/manage/pv_services/test_pvc_assign_pod_node.py
- tests/manage/pv_services/test_raw_block_pv.py
- tests/manage/pv_services/test_verify_rwo_using_multiple_pods.py
Fixes: #2786 
Fixes: #2790 
Skip tests due to following bugs found during tier1 runs on IBM Cloud:
- https://bugzilla.redhat.com/show_bug.cgi?id=1871314 
- https://bugzilla.redhat.com/show_bug.cgi?id=1871315
> Skip relevant pv_services tier1 test cases on IBM cloud due to Bug 1871314 and 1871315

- conf/ocp_version/ocp-4.5-upgrade.yaml
> Adding OCP 4.5 upgrade yaml

- tests/ecosystem/upgrade/test_upgrade_ocp.py
> Fix for OCP upgrade

- tests/manage/mcg/test_namespace.py
> skip noobaa namespace tests for non-aws platforms

- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
> Increase clsuter health timeout in node drain tests

- ocs_ci/ocs/resources/backingstore.py
- ocs_ci/ocs/resources/cloud_uls.py
- tests/conftest.py
- tests/ecosystem/upgrade/test_noobaa.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/2822
I also moved factory fixture implementation to `resources` directory. `conftest.py` starts to get big due to implementation function for factories.
> Add backingstore_factory_session and cloud_uls_factory_session

- ocs_ci/deployment/vmware.py
> Fix for connection refused for OCP 4.5

- tests/e2e/flowtest/test_base_operation_node_drain.py
Tracked in bz: https://bugzilla.redhat.com/show_bug.cgi?id=1869303
> Skipping Flow testcase

- conf/ocp_version/ocp-4.5-ga-minus1-config.yaml
> add config file ocp4.5ga minus1

- conf/ocp_version/ocp-4.5-config.yaml
- conf/ocp_version/ocp-4.5-ga-config.yaml
- conf/ocp_version/ocp-4.5-ga-minus1-config.yaml
> Adding latest template for ocp45

- ocs_ci/ocs/resources/mcg.py
- ocs_ci/ocs/resources/ocs.py
> Check if cluster was upgraded for RGW count validation

- conf/ocsci/external_rhcs_cluster.yaml
WA for issue: https://github.com/red-hat-storage/ocs-ci/issues/2861
> Set noobaa endpoints to 1 for external mode

- conf/deployment/aws/ipi_1az_rhcos_3m_3w.yaml
- conf/deployment/aws/ipi_3az_rhcos_3m_3w.yaml
- conf/deployment/aws/upi_1az_rhcos_3m_3w.yaml
- conf/deployment/aws/upi_1az_rhel7_3m_3w.yaml
- conf/deployment/aws/upi_3az_rhcos_3m_3w.yaml
- conf/deployment/aws/upi_3az_rhel7_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml
- ocs_ci/utility/reporting.py
- tests/ecosystem/deployment/test_deployment.py
- tests/ecosystem/upgrade/test_upgrade.py
> Upgrade polarion ids

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/utils.py
- setup.py
- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
- Change URL of RHCOS template
- Add functionality to download a file from a git repository
> Fix get rhcos template

- conf/ocp_version/ocp-4.6-upgrade.yaml
> Add OCP 4.6 upgrade conf file

- ocs_ci/ocs/cluster.py
> Fix mcg-cli pod issue

- conf/ocsci/infra_worker_nodes.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/constants.py
> Add functionality to deploy with infra worker nodes

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/utility/utils.py
- pytest.ini
- tests/conftest.py
- tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
- tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
- tests/manage/pv_services/pvc_resize/test_pvc_expansion_when_full.py
- tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
> Skip PVC expansion tests if the cluster is upgraded from OCS4.4

- ocs_ci/ocs/cluster.py
> Fixing the issue for setting the property for mcg_obj

- tests/conftest.py
Currently, some failed test cases might leave a leftover service CA.
This led to many failures that shouldn't have happened.
Closes #2657
> Retry AWSCLI service CA creation if already exists

- ocs_ci/ocs/cluster_load.py
> Set a fixed PVC size for cluster load with external cluster

- ocs_ci/ocs/ocp.py
- mirror rsync image for disconnected cluster
> update ocp.rsync for disconnected cluster

- ocs_ci/ocs/monitoring.py
- tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
> monitoring_mgr_pod_OCS-1535

- tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
> Update test_pvc_delete_verify_size_is_returned_to_backendpool.py to support External mode cluster

- ocs_ci/deployment/baremetal.py
- ocs_ci/ocs/constants.py
This PR includes a check function to make sure only one BM is Created
>  Add a check condition before deploying BM cluster

- ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/instance.yaml
> Setting toleration for fluentd pods

- conf/ocsci/tainted_worker_nodes.yaml
> Add conf file to taint worker nodes

- ocs_ci/ocs/scale_pgsql.py
Added support for VMware, Baremetal and Independent mode.
> pgsql scale test: Added support for VMware, Baremetal and Independent mode.

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/mcg.py
- ocs_ci/ocs/resources/storage_cluster.py
> Adjustments for RGW as the default backingstore over 4.4 Azure

- ocs_ci/ocs/constants.py
- tests/helpers.py
- tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py
Update test case test_pvc_snapshot to use default volumesnapshotclass
> Update test_pvc_snapshot to use default volumesnapshotclass

- ocs_ci/ocs/couchbase.py
- ocs_ci/ocs/pillowfight.py
- tests/e2e/workloads/couchbase/test_couchbase_node_drain.py
- tests/e2e/workloads/couchbase/test_couchbase_node_reboot.py
- tests/e2e/workloads/couchbase/test_couchbase_pod_respin.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/2690
> Fixing Couchbase issues

- ocs_ci/ocs/fio_artefacts.py
- ocs_ci/ocs/mcg_workload.py
- tests/conftest.py
- tests/ecosystem/upgrade/conftest.py
- tests/ecosystem/upgrade/test_noobaa.py
- tests/libtest/test_mcg_workload.py
> create_workload_job function and workload job factory for mcg io

- conf/ocp_version/ocp-4.6-config.yaml
> Updating OCP4.6 vm template

- conf/ocs_version/ocs-4.5.yaml
- conf/ocs_version/ocs-4.6.yaml
- ocs_ci/ocs/constants.py
> Add latest tags for 4.6 and use stable builds

- ocs_ci/ocs/platform_nodes.py
- tests/manage/z_cluster/nodes/test_nodes_restart.py
> vSphere: Do cold power off in node restart scnenarios instead of graceful OS shutdown

- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Increase number of retries of this test
> increase timeout of santiy health check in test_node_maintenance

- tests/e2e/performance/test_pod_reattachtime.py
> test_pod_reattachtime_fix

- ocs_ci/deployment/vmware.py
- ocs_ci/utility/utils.py
> Increases timeout for configuring chrony on nodes

- ocs_ci/templates/ocp-deployment/rhcos_images.yaml
> Add OCP 4.6 images for BM

- ocs_ci/ocs/cluster_load.py
- tests/conftest.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
> Cluster load: Allow reduce load in addition to pause

- ocs_ci/ocs/constants.py
- ocs_ci/utility/utils.py
Enhancement for avoiding of latest tags without need to change it
for each new version.
Fixes: #2937
> Avoid using latest tags

- ocs_ci/framework/pytest_customization/ocscilib.py
> Fix typo for client_version

- ocs_ci/deployment/deployment.py
- ocs_ci/framework/pytest_customization/ocscilib.py
Skip ocs must gather for ocp deployment failures
Fixes: #2912 
Signed-off-by: vavuthu vavuthu@redhat.com
> Skip ocs must gather for ocp deployment failures

- ocs_ci/ocs/resources/objectbucket.py
> Extend OBC health verification timeout

- tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py
Updates:
* Run fio before creating the clone
* Add test case id.
* Split long lines
> Update test_pvc_to_pvc_clone to run IO before creating clone

- tests/e2e/performance/test_pvc_deletion_performance.py
> added mutiple pvc deletion case

- tests/helpers.py
> Change the PVC multiple creation to work as bulk

- tests/ecosystem/upgrade/test_upgrade_ocp.py
> Remove duplicate logging in test_upgrade_ocp

- tests/manage/z_cluster/test_add_mds_to_cluster.py
> Disable test case: add MDS to cluster

- tests/e2e/performance/test_pod_reattachtime.py
This is addressing Issue: #2962
> Changing the PVC type that create to be taken from variable

- tests/helpers.py
Updated code to skip collecting perf stats in external mode RHCS cluster
> Skip performance stats collection for external mode RHCS cluster

- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
- ocs_ci/utility/vsphere.py
> vSphere: Abort deployment if cluster with the same name prefix already exists

- ocs_ci/framework/pytest_customization/reports.py
- add tests failed in setup or teardown phase to report
- fixes: https://github.com/red-hat-storage/ocs-ci/issues/2977
> fix squad analysis report

- ocs_ci/ocs/node.py
- ocs_ci/ocs/resources/storage_cluster.py
> fix osd tree verification for baremetalpsi platform

- conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/gcp.py
- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/templates/ocp-deployment/install-config-gcp-ipi.yaml.j2
- ocs_ci/templates/ocs-deployment/storageclass.gcp.yaml
- ocs_ci/utility/gcp.py
- ocs_ci/utility/tests/test_gcp.py
- tests/libtest/test_gcp.py
This is a work in progress right now. Opening as WIP for a better visibility.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/2890
> GCP deployment

- tests/helpers.py
> Mirror images before using it

- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/registry.py
- ocs_ci/utility/utils.py
- tests/e2e/registry/test_registry_pod_respin.py
- tests/e2e/registry/test_registry_pull_and_push_images_to_registry.py
> Fix registry failures

- tests/e2e/test_simple_registry_workload.py
> checking the number of builds succeeded instead of failures

- ocs_ci/ocs/registry.py
- tests/e2e/registry/test_registry_by_increasing_num_of_image_registry_pods.py
> Test case to increase number of registry pods

- conf/ocsci/local_storage_namespace.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/ocs/uninstall.py
- ocs_ci/templates/ocs-deployment/local-storage-operator.yaml
- ocs_ci/templates/ocs-deployment/local-storage-optional-operators.yaml
- ocs_ci/templates/ocs-deployment/local-volume.yaml
- ocs_ci/utility/deployment.py
- ocs_ci/utility/localstorage.py
> Use optional-operators catalogsource for LSO on non-GA OCP versions

- ocs_ci/framework/pytest_customization/marks.py
- pytest.ini
- tests/e2e/flowtest/test_base_operation_node_drain.py
> Added new marker "flowtests" for running flowbased tests

- ocs_ci/deployment/vmware.py
> retry for patching imageregistry operator

- conf/deployment/aws/ipi_1az_rhcos_3m_3w.yaml
- conf/deployment/aws/ipi_3az_rhcos_3m_3w.yaml
- conf/deployment/aws/upi_1az_rhcos_3m_3w.yaml
- conf/deployment/aws/upi_1az_rhel7_3m_3w.yaml
- conf/deployment/aws/upi_3az_rhcos_3m_3w.yaml
- conf/deployment/aws/upi_3az_rhel7_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml
- conf/upgrade/upgrade_3m.yaml
- conf/upgrade/upgrade_3m_3w.yaml
- conf/upgrade/upgrade_greater_than_3w.yaml
> Polarion upgrade fix

- conf/ocsci/encryption_at_rest.yaml
- docs/usage.md
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/exceptions.py
> Enable encryption at rest

- ocs_ci/ocs/resources/cloud_manager.py
> Fix cred dict issue

- ocs_ci/deployment/deployment.py
> Add a wait after creating LSO yaml

- conf/deployment/rhv/ipi_1az_rhcos_3m_3w.yaml
> Add config file for rhv platform

- ocs_ci/framework/pytest_customization/marks.py
> Fix skipif_no_lso marker

- docs/conf.py
fixes https://github.com/red-hat-storage/ocs-ci/issues/3045
> doc fix: don't show readme in FAQ section

- tests/e2e/registry/test_pod_from_registry.py
- tests/helpers.py
> Update the source image to fedora

- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_6w.yaml
Create a new configuration file with vSphere, UPI, RHCOS, 6 worker nodes. We need to have 3 extra worker nodes to test node replacement with vSphere, as you can see in the file https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
> Create new conf file the configurations: vSphere, UPI, RHCOS, 6 worker nodes

- ocs_ci/ocs/jenkins.py
- ocs_ci/ocs/ocp.py
There is a difference between jenkins-persistent template on OCP 4.5 and OCP 4.6
This PR fix this issue.
https://github.com/red-hat-storage/ocs-ci/issues/2993
> fix jenkins issue on OCP4.6

- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/constants.py
> Set log level of ocscilib module based on pytest.ini log_cli_level

- ocs_ci/deployment/baremetal.py
> Avoid creating pxe file for all nodes

- ocs_ci/framework/pytest_customization/reports.py
> Fixing log handler issue

- conf/ocsci/stage-rh-osbs-4.5.yaml
- conf/ocsci/stage-rh-osbs-4.6.yaml
- conf/ocsci/stage-rh-osbs.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/ocs-deployment/stageImageContentSourcePolicy.yaml
> Stage bundle 4.6

- ocs_ci/deployment/helpers/prechecks.py
- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/utility/vsphere.py
> Environment pre-checks for on-prem platforms

- conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
- ocs_ci/deployment/cloud.py
- ocs_ci/framework/conf/default_config.yaml
fixes https://github.com/red-hat-storage/ocs-ci/issues/3071
> deployment: add 15 min to Azure ocp install timeout

- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/framework/pytest_customization/reports.py
> Explicitly add StreamHandler to ocscilib logger instead of using basicConfig

- ocs_ci/deployment/vmware.py
> skip environment prechecks for teardown

- conf/ocsci/noobaa_endpoints_scale.yaml
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/testlib.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/storage_cluster.py
> Look for 1 min and 1 max NB EPs with 4.5 and lower clusters

- conf/ocp_version/ocp-4.6-config.yaml
> Adding updated template for OCP 4.6

- tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py
Fixed fio_file_size bigger than PVC_size problem
Enhanced TC to support external mode cluster.
> Enhanced TC for External mode, fixed pvc capacity problem

- ocs_ci/ocs/ripsaw.py
to fix issue : #3110 
changing the timeout from 60 sec. to 180 sec.
> changing timeout for ripsaw cleanup

- conf/upgrade/upgrade_3m.yaml
- conf/upgrade/upgrade_3m_3w.yaml
- conf/upgrade/upgrade_greater_than_3w.yaml
> Remove replica counts from upgrade config files

- ocs_ci/utility/utils.py
> Fixing the skipif_ocp_version

- tests/manage/mcg/test_bucket_policy.py
> Fix for test_object_actions test case for OCS >=4.6

- ocs_ci/ocs/ocp.py
> added function: get_ocs_parsed_version

- conf/ocp_version/ocp-4.7-config.yaml
> Added config file for OCP 4.7

- conf/ocs_version/ocs-4.7.yaml
- ocs_ci/framework/main.py
> Added config file for OCS 4.7

- ocs_ci/deployment/deployment.py
> Use Rotational to detect HDD disk for LocalVolumeSet for Vmware LSO deployment

- ocs_ci/ocs/mcg_workload.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/3136
> Change log level for job pod logs

- ocs_ci/framework/pytest_customization/ocscilib.py
- tests/conftest.py
> Fix for test_uninstall_ocs verification

- tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Verify used percentage after attaching the restored PVC to pods in test test_snapshot_at_different_usage_level.
> Verify usage on new pods in snapshot test

- ocs_ci/ocs/resources/pod.py
- tests/conftest.py
- tests/manage/pv_services/conftest.py
- tests/manage/pv_services/pvc_clone/test_clone_with_different_access_mode.py
Test to verify PVC clone with access mode different than parent PVC. 
Polarion test case id OCS-2368
> Test to verify PVC clone with access mode different than parent PVC

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/node.py
> Fix getting Hostname for worker nodes

- conf/ocp_version/ocp-4.7-upgrade.yaml
> Add OCP 4.7 upgrade config

- docs/usecases/reporting_tests_results_from_cluster_not_deployed_by_ocsci.rst
fixes https://github.com/red-hat-storage/ocs-ci/issues/3041
> docs: how to report test results without jenkins

- ocs_ci/ocs/bucket_utils.py
- tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle.py
Tests MCG namespace resource/bucket lifecycle
1. Create namespace resources.
2. Create namespace bucket
3. Set bucket policy on namespace bucket with a S3 user principal
4. Verify bucket policy get/ delete
5. Read/write directly on namespace resource target.
6. Edit the namespace bucket
7. Verify data after edit
8. Delete namespace bucket
9. Delete namespace resource
> Mcg namespace lifecycle test

- tests/manage/pv_services/test_verify_rwo_using_dc_pod.py
tests/manage/pv_services/test_verify_rwo_using_dc_pod.py
1. Update to check whether running pods are on same node.
2. Increase replica count to verify  using more pods.
> Update to check running pods are on same node

- tests/conftest.py
> using logger instead of logging module

- ocs_ci/ocs/cluster_load.py
> retry Prometheus query in cluster load in case of IndexError

- tests/manage/storageclass/test_create_multiple_sc_with_different_pool_name.py
- tests/manage/storageclass/test_create_multiple_sc_with_same_pool_name.py
- tests/manage/storageclass/test_create_storageclass_with_wrong_provisioner.py
- tests/manage/storageclass/test_rbd_csi_default_sc.py
- tests/manage/storageclass/test_verify_all_fields_in_sc_yaml_with_oc_describe_sc.py
This PR closes #2854 , closes #2837 
> Skip irrelevant tests in tests/manage/storageclass/ on External mode

- ocs_ci/ocs/constants.py
- tests/conftest.py
- tests/manage/monitoring/conftest.py
- tests/manage/monitoring/prometheus/test_rgw.py
> RGW monitoring test

- ocs_ci/ocs/platform_nodes.py
> Update validation for node restart operations

- conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
- conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
Add test case IDs into Azure and GCP deployment config files.
> add polarion IDs for Azure and GCP deployment

- conf/ocsci/aws_upi_flexy_rhcos_3m_3w_proxy.yaml
- conf/ocsci/flexy_baremetalpsi_upi.yaml
- ocs_ci/deployment/aws.py
- ocs_ci/deployment/factory.py
- ocs_ci/deployment/flexy.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/conf/flexy_default_config.yaml
- ocs_ci/ocs/constants.py
- ocs_ci/utility/aws.py
This PR implements installation of AWS UPI Cluster behind Proxy.
> AWS UPI Cluster behind Proxy - using Flexy

- setup.py
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/3140
> bump gevent version to 20.9.0 for ABI changes

- tests/conftest.py
> Change function get_ocp_version to get_running_ocp_version

- ocs_ci/deployment/vmware.py
fixes: https://github.com/red-hat-storage/ocs-ci/issues/3180
> Fix usage of cluster existence check on VMware

- tests/e2e/scale/test_scale_amq.py
> added amq scale test

- ocs_ci/deployment/flexy.py
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/3182
> fix handling of error raised during flexy execution

- ocs_ci/deployment/deployment.py
> Set constant limits and requests for noobaa endpoints

- docs/usage.md
> Adding documentation for development mode

- ocs_ci/ocs/node.py
> Fix getting wrong value from get_compute_node_names

- ocs_ci/utility/prometheus.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/3189
> log details about prometheus query parsing error

- .gitignore
- docs/usecases/running_tests_on_cluster_not_deployed_by_ocsci.rst
fixes https://github.com/red-hat-storage/ocs-ci/issues/3040
> docs: running tests on non ocs-ci cluster

- tests/sanity_helpers.py
> Fix the NB sanity test to not run too many iterations

- tests/e2e/scale/test_cephfs_many_files.py
> Add initial version of scale test for one million cephfs files.

- ocs_ci/ocs/cluster_load.py
- tests/conftest.py
Make the autouse session scope fixture for cluster load more robust.
Fixes: #3145
> Fix cluster load fixture

- ocs_ci/deployment/vmware.py
Just few small cosmetic fixes in `vmware.py` file.
> fix indentation of if conditions blocks in vmware.py

- ocs_ci/framework/pytest_customization/ocscilib.py
Jira: [OCSQE-232](https://projects.engineering.redhat.com/browse/OCSQE-232)
> Add upgrade OCP version CLI options

- ocs_ci/cleanup/vsphere/cleanup.py
- ocs_ci/utility/aws.py
- setup.py
This PR contains below important commits
5b72c33cc3e73c56520cbb6b58b957b442759f41 : cleanup tool for vsphere ( reading config file and establishes connection to vcenter )
0102875ea51053f3210cf4fa57330d7470984227 : Delete the disks from VM and delete the cluster from datacenter
fd7bf909df69c2a063537b72b716765afeb06288 : Release IP's from IPAM server
71d36ed475713b87549558edbba1e5a4d1bea288 : Delete hosted zone and its records from AWS
e2f7b4509173d6420ad875ad3e40263d3c122125 : Delete records from base domain
> force cluster destroy -  vsphere platform

- conf/ocsci/scale.yaml
> Added generic file for scale tests to override must gather timeout

- ocs_ci/ocs/constants.py
- tests/manage/monitoring/prometheus/test_hpa.py
- tests/manage/monitoring/prometheusmetrics/test_mcg_hpa.py
Automates:  BZ #1836299 and #1873162
> Test cases for BZ #1836299 and #1873162

- ocs_ci/repos/ocp_4_6.repo
> Adding extra repos for RHEL installation for vsphere

- ocs_ci/ocs/resources/packagemanifest.py
Take CSV name is needed only when we have some install plan to approve.
If not, we need to continue to take CSV name from packageManifest.
Fixes: #3235
> Fix for get csv neme from install plan

- ocs_ci/ocs/bucket_utils.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/backingstore.py
- ocs_ci/ocs/resources/cloud_manager.py
- ocs_ci/ocs/resources/cloud_uls.py
- ocs_ci/templates/mcg/BackingStore.yaml
- ocs_ci/templates/mcg/BackingStoreSecret.yaml
- setup.py
- tests/conftest.py
- tests/manage/mcg/test_multi_region.py
Added the needed code for creating of Azure, GCP and IBMCOS ULSs and backingstores in our code
Closes #3123
> Implement Azure, GCP and IBM COS in CloudManager

- ocs_ci/deployment/deployment.py
Signed-off-by: annagitel <asandler@redhat.com>
> Add OCS uninstall to cluster teardown 

- tests/e2e/logging/test_openshift-logging.py
> Remove skipping logging TCs on OCP 4.6 & skip for next non-GAed version

- ocs_ci/framework/conf/default_config.yaml
> Update default template to latest

- tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py
Run IO after attachig the cloned PVC to a pod in test test_pvc_to_pvc_clone
> Run IO on cloned PVC pod

- ocs_ci/deployment/deployment.py
> Fix unistall issue with logger of Exception

- ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
- ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
- ocs_ci/templates/ocp-deployment/install-config-azure-ipi.yaml.j2
- ocs_ci/templates/ocp-deployment/install-config-gcp-ipi.yaml.j2
> Fix indention problem for OCP install config templates

- ocs_ci/deployment/deployment.py
> Add annotations to show ocs disk status on UI for LSO cluster

- ocs_ci/utility/lvm_utils.py
- tests/manage/mcg/test_object_integrity.py
- tests/manage/pv_services/test_pvc_rwx_writeable_after_pod_deletions.py
> Manually fix files that black could not automatically reformat

- tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py
Run IO on restored PVC pod in test test_pvc_snapshot
> Run IO after restoring the PVC

- ocs_ci/ocs/pgsql.py
- tests/conftest.py
- tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py
> Testcase: Multiple clones of PGSQL Workloads PVCs

- ocs_ci/helpers/helpers.py
- ocs_ci/templates/ocs-deployment/cephblockpool.yaml
- tests/conftest.py
- tests/manage/storageclass/test_new_sc_rbd_replica2_3.py
Issue KNIP-1462
Fix on https://github.com/red-hat-storage/ocs-ci/issues/3161
Todo: https://github.com/red-hat-storage/ocs-ci/issues/3162 , in follow up pr
> Create new rbd storage class on a new rbd pool  with replica and compression options

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/node.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/vsphere.py
- ocs_ci/utility/vsphere_nodes.py
This PR contains below important commits
c98b39665ce16e51cafe05b7bb591921a5f0fe64 : Adding libraries for add_node functionality which contains cloning VM from template, converting ignition to base64 and sets the host name
30df11f0e872623dd4776253932435586adab100 : providing option for users to change memory, CPUs, root disk size and network adapter for the VM while cloning
9098f7d2a6c92f213fbe29e4f8b596d86f330236 : Passing advanced configuration parameters to the VM while cloning from template
Signed-off-by: vavuthu vavuthu@redhat.com
> Add nodes manually for vSphere platform

- conf/ocp_version/ocp-4.6-ga-config.yaml
Adding RHCOS OCS 4.6 GAed template
> Adding RHCOS OCP 4.6 GAed template

- ocs_ci/ocs/external_ceph.py
- ocs_ci/ocs/utils.py
A reboot function for external rhcs nodes
> reboot external rhcs nodes

- ocs_ci/ocs/bucket_utils.py
- tests/e2e/flowtest/mcg/test_mcg_namespace_disruptions.py
> Flowtest - mcg namespace disprution flow

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/mcg.py
- tests/conftest.py
- tests/manage/mcg/test_namespace.py
> Add namespace bucket test for azure

- ocs_ci/deployment/deployment.py
Use LSO namespace defined in configuration when creating LSO and local volume
Fixes: #3307 
> Use namespace from config for LSO deployment

- ocs_ci/ocs/ocs_upgrade.py
W/A issue: https://github.com/red-hat-storage/ocs-ci/issues/3309
Because of BZ mentioned in $SUBJECT we need to increase the timeou.
This change should be reverted or fixed once we will have clarity in
the bug.
> Increase timeout for upgrade for BZ: 1895402

- ocs_ci/utility/utils.py
fixes: https://github.com/red-hat-storage/ocs-ci/issues/3292
> fix squad analysis skipped_message issue

- ocs_ci/ocs/node.py
> Increase node drain command timeout in TestNodesMaintenance

- tests/manage/pv_services/pvc_clone/test_node_restart_during_pvc_clone.py
Test case to verify PVC cloning will succeed if a worker node is restarted while cloning is in progress.
OCS-2373 - FT-Worker node restart during PVC clone
> Test worker node restart during PVC clone

- tests/e2e/performance/test_pvc_creation_performance.py
- tests/e2e/performance/test_pvc_deletion_performance.py
> updated codespeed

- tests/conftest.py
- tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
Verify PVC clone will succeeded if rook-ceph, csi pods are re-spun while creating the clone
OCS-2413 - FT-Resource deletion during PVC clone
> Test to verify PVC clone when rook-ceph, csi pods are deleted

- ocs_ci/ocs/constants.py
> Assign lifecycle and flowtest to Magenta squad

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/exceptions.py
- tests/manage/storageclass/test_new_sc_rbd_replica2_3.py
In order to test KNIP 1462 multiple storage class added function to validate compression and replication at pool level
> Function to check compression and replication

- tests/manage/pv_services/pvc_snapshot/test_snapshot_restore_with_different_access_mode.py
Test to verify PVC snapshot restore with access mode different than parent PVC
OCS-2410 - FT-Restore snapshot with access mode different than that of parent PVC
> Tests to verify PVC snapshot restore with access mode different than parent PVC

- ocs_ci/helpers/disruption_helpers.py
- ocs_ci/ocs/resources/pod.py
- tests/conftest.py
- tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
- tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Test to verify PVC snapshot and restore will succeeded if rook-ceph, csi pods are re-spun while creating snapshots and while restoring the snapshots.
OCS-2369 - FT-Resource deletion during snapshot and restore
Signed-off-by: Jilju Joy jijoy@redhat.com
> Test resource deletion during snapshot and restore

- ocs_ci/repos/ocp_4_6.repo
> Use Repo link from mirror.openshift.com instead of internal link

- conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml
- conf/deployment/baremetal/upi_1az_rhel7_nvme_intel_3m_3w.yaml
> Add Polarion Id for BM config file

- ocs_ci/framework/pytest_customization/ocscilib.py
- pytest.ini
- tests/conftest.py
> CI reportportal gaps

- ocs_ci/ocs/bucket_utils.py
- ocs_ci/ocs/resources/mcg.py
- tests/conftest.py
- tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops.py
> Test case for mcg namespace supported S3 operations

- tests/e2e/performance/test_pvc_snapshot_performance.py
This PR adding a test which take snapshot for PVC with huge number of file on it - 1M / 2M / 4M
an measure the time it tack.
the purpose of it, is to see if the number of file on the volume impact the time it take to create the snapshot.
> Add a test to a pvc image with a huge number of files

- ocs_ci/ocs/ocs_upgrade.py
> Changing the location of the ocs upgrade to the newer location

- ocs_ci/helpers/helpers.py
- tests/conftest.py
Wait for PV to delete in finalizer of snapshot_restore_factory and pvc_clone_factory
> Wait for PV to delete in finalizer of snapshot_restore_factory and pvc_clone_factory

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/cloud_manager.py
- ocs_ci/ocs/resources/cloud_uls.py
- ocs_ci/ocs/resources/mcg.py
- ocs_ci/ocs/resources/rgw.py
- tests/conftest.py
- tests/manage/mcg/test_namespace.py
> Namespace bucket tests that use RGW

- ocs_ci/ocs/ripsaw.py
since the repo. name was changed, this PR changing the use to the new repo name.
> Rename Ripsaw repo

- .github/workflows/pr_checks.yml
- tox.ini
> Introducing github actions to ocs-ci

- ocs_ci/deployment/deployment.py
> changing info to debug in deployment

- conf/deployment/aws/ipi_3az_rhcos_3m_3w_3i.yaml
- conf/ocsci/infra_nodes.yaml
- ocs_ci/deployment/aws.py
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/machine.py
- ocs_ci/ocs/scale_lib.py
- ocs_ci/ocs/scale_pgsql.py
> Add infra nodes to ocp cluster - AWSIPI

- ocs_ci/deployment/baremetal.py
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/disruptive_operations.py
- ocs_ci/ocs/flowtest.py
- ocs_ci/ocs/jenkins.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/ocs/scale_lib.py
- ocs_ci/ocs/version.py
- ocs_ci/utility/localstorage.py
- ocs_ci/utility/performance_dashboard.py
- ocs_ci/utility/utils.py
- tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
- tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
- tests/e2e/workloads/amq/test_amq_node_reboot_and_shutdown.py
- tests/e2e/workloads/couchbase/test_couchbase_node_drain.py
- tests/e2e/workloads/couchbase/test_couchbase_node_reboot.py
- tests/e2e/workloads/pgsql/test_pgsql_node_drain.py
- tests/manage/pv_services/pvc_clone/test_node_restart_during_pvc_clone.py
- tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
- tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Fix function name to use simple form as argument indicates the necessary modifiers
> Fix function name to use simple form 

- ocs_ci/ocs/resources/pod.py
> Fix TypeError when calling wait_for_storage_pods

- tests/conftest.py
* fix https://github.com/red-hat-storage/ocs-ci/issues/3393
* split ns_resource_factory to create mcg connection separately
> fix issue 3393 and split ns_resource_factory

- tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops.py
> ListObjectsv2 continuation token implementation

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/cloud_manager.py
- ocs_ci/ocs/resources/cloud_uls.py
- ocs_ci/utility/utils.py
> Instantiate default cloud clients as None when no auth.yaml is found

- ocs_ci/framework/conf/ocp_version/ocp-4.7-config.yaml
> updating RHCOS template for OCP4.7

- ocs_ci/ocs/constants.py
- tests/conftest.py
> Fix for rgw_service issue in external mode env

- tests/manage/z_cluster/test_must_gather.py
> Fix collection issue

- ocs_ci/ocs/ocs_upgrade.py
> Revert upgrade timeout increase for 4.6

- tests/conftest.py
> Do not fail execution when RP has issues

- docs/code_review.md
Let's make it clear that MCG test cases in particular should work on any cloud platform.
> docs: note about NooBaa test cases on cloud platforms

- ocs_ci/ocs/resources/rgw.py
> MCG: Fix for #3434

- .functional_ci_setup.py
- ocs_ci/framework/main.py
> Jenkins: Optionally set OCP version

- ocs_ci/utility/csr.py
- ocs_ci/utility/vsphere.py
Fixes: #3258
In some cases the vsphere VM doesn't get IP for first start and cannot
load the ignition config. In this fix we will try to find those VMs
without IP and reboot them.
> Improve in approving CSRs fro vSphere

- conf/deployment/aws/ipi_3az_rhcos_3m_3w_3i.yaml
> Enable infra_nodes flag in production yaml

- conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
- conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
> Fix GCP and Azure prod config files

- ocs_ci/deployment/flexy.py
- ocs_ci/ocs/constants.py
- as flexy working directory always use data/flexy-dir
- copy flexy working dir to the cluster path
- change flexy image version
> update integration with flexy

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/machine.py
> Remove 'app' label in case of infra nodes

- ocs_ci/utility/environment_check.py
> Ignore oc debug pods in leftover checks

- conf/README.md
> Document all known configuration settings

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/hsbench.py
- ocs_ci/templates/app-pods/golang.yaml
- ocs_ci/templates/workloads/hsbench/hsbench_obj.yaml
- tests/e2e/scale/noobaa/test_hsbench.py
Writing 1M objects to a single bucket using hsbench s3 benchmark.
HotSauce S3 benchmark: https://github.com/markhpc/hsbench
> Noobaa scale: Writing 1M objects to a single bucket

- ocs_ci/helpers/helpers.py
- ocs_ci/utility/uninstall_openshift_logging.py
- tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Simulating this BZ https://bugzilla.redhat.com/show_bug.cgi?id=1858185 with RBD PVC, adding the BZ validation in the uninstall_openshift_logging.py
> Checking space reclaimed post deletion of Elasticsearch PVC

- conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w_3i.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_3i.yaml
> Production yaml:Infra deployment on vsphere

- ocs_ci/templates/ocs-deployment/stageImageContentSourcePolicy.yaml
> Fix operator bundle image

- conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
- ocs_ci/templates/ocp-deployment/install-config-azure-ipi.yaml.j2
fixes https://github.com/red-hat-storage/ocs-ci/issues/3398
> move Azure baseDomainResourceGroupName to conf file

- tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops.py
Removing skip since Listobjects v1 and v2 on namespace buckets with azure resource is now [fixed](https://bugzilla.redhat.com/show_bug.cgi?id=1898830). Added a workaround for listobjectsv1 with markers on azure resource [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1901943).
> Unskipping 'list' ops & added a workaround for 'markers' for azure res.

- ocs_ci/ocs/resources/cloud_uls.py
Fixed wrong documentation link, and added further explanation.
> Improve CLDMGR docs

- tests/manage/z_cluster/nodes/test_nodes_restart.py
https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-2448
> add polarion id mark

- ocs_ci/ocs/metrics.py
- tests/manage/monitoring/prometheusmetrics/test_rgw.py
> Add RGW metrics test

- ocs_ci/framework/conf/default_config.yaml
> updating ocs-olm-operator to ocs-registry in default_config

- ocs_ci/cleanup/vsphere/cleanup.py
> generate node names in case of empty resource pool

- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
- tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
Test Procedure:
- Verify OSD encrypted on relevant nodes
- Deleting machine and waiting for new machine to come up
- Verify new OSD encrypted
> node replacement test, verify the new osd is encrypted 

- ocs_ci/framework/pytest_customization/ocscilib.py
> Don't collect noobaa DB dump if cluster version is 4.7

- ocs_ci/ocs/amq.py
- tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
> Adding retries to the function

- ocs_ci/ocs/elasticsearch.py
- ocs_ci/templates/app-pods/eck.1.3.1-all-in-one.yaml
This PR is to replace the downloaded CR file for ECK by local copy of the file,
to fix #3533 
> Replacing the ECK download file with local copy

- docs/index.rst
- docs/release_guidelines.md
- setup.py
Updates release note to match released version and also adds the initial docs for release note process.
> update setup.py to match released version

- tests/e2e/flowtest/pvc_snapshot_and_clone/test_pgsql_pvc_snapshot_and_clone.py
> Flow based test scenario for pgsql snapshot and clone

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/resources/backingstore.py
- ocs_ci/ocs/resources/cloud_manager.py
> Cldmgr unique secret names

- ocs_ci/ocs/amq.py
- ocs_ci/ocs/couchbase.py
- ocs_ci/ocs/jenkins.py
- ocs_ci/ocs/pgsql.py
> Use external mode sc in workloads if the deployment type is independent mode

- ocs_ci/ocs/must_gather/const_must_gather.py
- ocs_ci/ocs/must_gather/must_gather.py
- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
- tests/manage/z_cluster/test_ceph_default_values_check.py
- tests/manage/z_cluster/test_must_gather.py
~Fixes: #2882~
Fixes: #2885 
Fixes: #2838 
Fixes: #2923 
> Fix tier1 test failures in tests/manage/z_cluster/ on External mode

- tests/e2e/pvc_snapshot_and_clone/test_cloned_and_restored_pvc_resize.py
> Test PVC resize of cloned and restored PVC

- ocs_ci/ocs/must_gather/const_must_gather.py
> Add oc_output files to must gather test lists

- ocs_ci/ocs/resources/mcg.py
> Allow the MCG health check to fail

- ocs_ci/templates/app-pods/eck.1.3.1-all-in-one.yaml
> Fixing the API version in the ECK yaml file

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/vsphere.py
- tests/manage/z_cluster/nodes/test_disk_failures.py
1. Update the test 'test_recovery_from_volume_deletion' to be compatible with vSphere LSO
2. Add a new class in `platfrom_nodes` with the LSO functionality
> Update the test 'test_recovery_from_volume_deletion' to be compatible with vSphere LSO

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/azure_utils.py
> Add methods to start azure node

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/azure_utils.py
> Add methods to stop azure nodes

- ocs_ci/ocs/resources/cloud_manager.py
Run 1608808595 failed because of this exception, this PR is supposed to take care of future occasions.
> Handle EndpointConnectionError when trying to retrieve auth.yaml

- ocs_ci/ocs/exceptions.py
- tests/manage/storageclass/test_create_2sc_at_once_with_io.py
Test multiple sc with replica 2 and 3 with 10 pods
> Adding test multiple sc with replica 2 and 3 with IO

- ocs_ci/ocs/node.py
- tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
For running acceptance test for https://github.com/red-hat-storage/ocs-ci/pull/3586
> added acceptance related changes and verify

- conf/ocsci/openshift_dedicated.yaml
- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/mcg/test_bucket_creation.py
- tests/manage/mcg/test_bucket_deletion.py
- tests/manage/mcg/test_write_to_bucket.py
For running acceptance test for https://github.com/red-hat-storage/ocs-ci/pull/3543
> Skipping mcg related tests for openshift dedicated acceptance testing and verify

- ocs_ci/ocs/resources/cloud_uls.py
Up until now, we failed the tests.
Instead, this PR will skip them.
> Skip tests where cloud credentials are missing

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/defaults.py
- ocs_ci/ocs/exceptions.py
- tests/manage/storageclass/test_multiple_sc_comp_rep_data_delete.py
Add test to verify that data from pools that have replica 2,3 and compression is deleted after IO and pvc delete.
> Test multiple storageclasses data deletion with compression and replication

- ocs_ci/ocs/node.py
Fixes #https://github.com/red-hat-storage/ocs-ci/issues/3593
> Check if the new node with OCS storage label

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/defaults.py
- ocs_ci/templates/workloads/fio/benchmark_fio_cmp.yaml
- tests/e2e/performance/test_fio_benchmark.py
This PR is adding FIO test on compressed volume with different block size and IO pattern : sequential / random
it replace #3395
> Adding fio test on compressed volume

- tests/manage/storageclass/test_create_multiple_sc_with_same_pool_name.py
> Fix Issue #3604: Wait for PV to delete in test_create_multiple_sc_with_same_pool_name during teardown

- tests/conftest.py
- tests/manage/storageclass/test_create_2_sc_with_1_pool_comp_rep2.py
Test 2 storage class using same pool with replica 2 and compression
> Test 2 storage class using same pool with replica 2 and compression

- ocs_ci/framework/conf/default_config.yaml
> Update OCS 4.7 as default version

- tests/manage/mcg/test_namespace.py
- tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py
- tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py
- tests/manage/pv_services/test_raw_block_pv.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Acceptance tier lacks some of the new features of 4.5 and 4.6
> Enhance acceptance tier with new features

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/helpers/lso_helpers.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/resources/storage_cluster.py
Label the nodes based on config value
Fixes: #3297 
> Label the nodes based on config value

- ocs_ci/ocs/registry.py
- tests/e2e/registry/test_registry_shutdown_and_recovery_node.py
> Shutdown and recovery node and its impact on registry

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/mcg.py
- tests/manage/mcg/test_verify_noobaa_status.py
manually verify that the state of the NooBaa CR, default backingstore and default bucketclass is `READY`.
Closes #3570
> Fix NooBaa health verification

- ocs_ci/ocs/platform_nodes.py
> Add Azure restart node method by stopping and starting node

- tests/manage/mcg/test_bucket_policy.py
customer issue: https://bugzilla.redhat.com/show_bug.cgi?id=1889683
> Adding test for public access website

- ocs_ci/deployment/deployment.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/3629
> Reduce the timeout of storagecluster creation from 40 to 20 minutes

- tests/ecosystem/upgrade/test_noobaa.py
* fixes https://github.com/red-hat-storage/ocs-ci/issues/3172
> Fix backingstore object usage

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/ocp.py
- tests/manage/storageclass/test_create_sc_reclaim_policy_rep2_comp.py
Add test storageclass with reclaim policy retain and pool with replica 2 and compression
> Add test storageclass with reclaim policy retain and pool with replica 2 and compression

- ocs_ci/templates/ocs-deployment/local-storage-optional-operators.yaml
> Update ImageContentSourcePolicy yaml for non-GA LSO installs

- docs/getting_started.md
> Added doc around retrieving brew registry access for non-GA LSO testing

- ocs_ci/helpers/sanity_helpers.py
- ocs_ci/ocs/resources/objectbucket.py
- tests/conftest.py
- tests/ecosystem/deployment/test_deployment.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
- tests/manage/z_cluster/nodes/test_az_failure.py
- tests/manage/z_cluster/nodes/test_disk_failures.py
- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
- tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
- tests/manage/z_cluster/nodes/test_nodes_restart.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/3621
> Replace OBC operations with factory fixtures in sanity_helpers

- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/utils.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/3525
> Enable DB dump collection with OCS 4.7 and above

- tests/conftest.py
- fixes https://github.com/red-hat-storage/ocs-ci/issues/3668
> add logs_url as property to junit xml file

- tests/manage/pv_services/test_raw_block_pv.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Added changes related to openshift dedicated after the new additions of tests to acceptance tier https://github.com/red-hat-storage/ocs-ci/pull/3341
> [Openshift-Dedicated] Added acceptance related changes for openshift dedicated platform

- tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Test case -  test_resource_deletion_during_pvc_expansion
Add verification of expanded size on pods before running IO.
Fixes #3658 
> Check new size on pods in test

- ocs_ci/framework/conf/ocp_version/ocp-4.8-config.yaml
> Adding OCP 4.8 config file

- tests/ecosystem/deployment/test_deployment.py
> Remove usage of new fixtures in test_deployment

- setup.py
> Updating paramiko version to 2.7.2

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/mcg.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/rgwutils.py
- ocs_ci/utility/tests/test_rgwutils.py
> Update rules on how rgw_count is determined based on OCS version

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/resources/pod.py
- tests/manage/z_cluster/nodes/test_toleration.py
Automated GSS BZs
https://bugzilla.redhat.com/show_bug.cgi?id=1883828
> Testcase to check taint and tolerations

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/utility/rgwutils.py
> Fix issue when casting to float in upgrade

- ocs_ci/utility/workloadfixture.py
- tests/manage/monitoring/conftest.py
fixes https://github.com/red-hat-storage/ocs-ci/issues/3400
> pause workload_idle when background io is used

- tests/e2e/registry/test_registry_reboot_node.py
> Node reboot and its impact on registry pods

- ocs_ci/deployment/vmware.py
> enable chrony for vsphere

- tests/conftest.py
> skip collection OCS versions for OCP deployments

- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/resources/storage_cluster.py
> Fix in getting worker node based on label in AWS

- docs/usage.md
> Documentation for vSphere cleanup

- tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
- tests/e2e/registry/test_registry_pod_respin.py
- tests/e2e/workloads/amq/test_amq_node_reboot_and_shutdown.py
- tests/e2e/workloads/amq/test_amq_pod_respin.py
- tests/e2e/workloads/couchbase/test_couchbase_node_drain.py
- tests/e2e/workloads/couchbase/test_couchbase_node_reboot.py
- tests/e2e/workloads/couchbase/test_couchbase_pod_respin.py
- tests/e2e/workloads/jenkins/test_jenkins_node_drain.py
- tests/e2e/workloads/jenkins/test_jenkins_node_reboot.py
- tests/e2e/workloads/jenkins/test_jenkins_pod_respin.py
- tests/e2e/workloads/pgsql/test_pgsql_node_drain.py
- tests/e2e/workloads/pgsql/test_pgsql_node_reboot.py
- tests/e2e/workloads/pgsql/test_pgsql_pod_respin.py
> Increase tries on sanity_health check function

- ocs_ci/ocs/monitoring.py
> logging pvc names instead of dictionary

- ocs_ci/deployment/baremetal.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/ocp-deployment/rhcos_images.yaml
> Add OCP 4.7 config file for BM

- ocs_ci/ocs/resources/mcg.py
Reverts red-hat-storage/ocs-ci#3671
Closes #3673
> Revert "Log MCG RPC token retrieval calls"

- tests/conftest.py
> Donot check alerts for teardown

- conf/README.md
- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
- docs/supported_platforms.md
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/ocs-deployment/ibm-cloud-secret.yaml
Fixes: #3728
* Adding config map to change defautl kubelet path
* Add secret for IBM Cloud COS
> Fix IBM Cloud deployment

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/scale_lib.py
- tests/e2e/scale/test_pvc_creation_deletion_scale.py
> Scale pvcs to number of pods * 500

- tests/conftest.py
> Load auth.yaml file to AUTH framework config

- ocs_ci/deployment/baremetal.py
> Increase timeout for BM

- tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops.py
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1917677#c3
Fixes #3726 
Skipping listobjectsv1 on azure resource
> Fix for getobjectacl and listobjectv1 S3 ops

- ocs_ci/utility/tests/test_utils_timeout_sampler.py
- ocs_ci/utility/utils.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/3564
> Fix and improve TimeoutSampler, add tests

- ocs_ci/helpers/sanity_helpers.py
> Added obc_objs attribute to SanityExternalCluster init

- conf/deployment/azure/ipi_3az_rhcos_3m_3w.yaml
Modified 1 AZ config `conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml`
Added 3 AZ config `conf/deployment/azure/ipi_3az_rhcos_3m_3w.yaml`
> Update Azure IPI production configs to support 1 & 3 AZ deployment

- ocs_ci/ocs/cluster.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
Fixes: #3742 
Few changes related to validation of ceph osd tree to work on any cloud platform.
> Support ceph osd tree validation to work on any cloud platform

- ocs_ci/utility/azure_utils.py
> Add base method to get power status of Azure VM

- ocs_ci/utility/azure_utils.py
> Add Azure base method to get VM names in recent resource group

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/platform_nodes.py
> Add azure teardown method to ensure running status of all VM instances

- ocs_ci/ocs/platform_nodes.py
> Only append _lso for vsphere platform

- tests/libtest/test_azure.py
> Add libtest to test get_vm_names method

- tests/e2e/scale/test_pvc_creation_deletion_scale.py
> Add log.info for duration time of each run.

- ocs_ci/utility/tests/test_azure_utils.py
> Remove test_azureutil_init_invalidcredentials

- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
> Delete .terraform directory as part destroy cluster in vSphere

- ocs_ci/cleanup/vsphere/cleanup.py
> Destroy empty resource pool in vsphere-cleanup script

- ocs_ci/ocs/utils.py
> Adding ceph volumeMounts for creating toolbox in external cluster

- ocs_ci/templates/ocp-deployment/rhcos_images.yaml
> Use Latest RHCOS images

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/azure_utils.py
This PR includes: 
- Add support for force VM stop
- Handle the vms/nodes list in low-level modules similar to what we do for other platforms
Also, Fixes: #3736 
> Update azure node related methods in platform_nodes and azure_utils

- tests/libtest/test_azure.py
> Add libtest to test get_vm_power_status method

- ocs_ci/helpers/sanity_helpers.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/must_gather/const_must_gather.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/ocp.py
- tests/conftest.py
- tests/e2e/logging/test_openshift-logging.py
- tests/manage/mcg/test_bucket_policy.py
- tests/manage/mcg/test_endpoint_autoscale.py
- tests/manage/mcg/test_multi_region.py
- tests/manage/mcg/test_multicloud.py
- tests/manage/mcg/test_multipart_upload.py
- tests/manage/mcg/test_namespace.py
- tests/manage/mcg/test_object_integrity.py
- tests/manage/mcg/test_verify_noobaa_status.py
- tests/manage/monitoring/prometheus/test_hpa.py
- tests/manage/monitoring/prometheusmetrics/test_mcg_hpa.py
- tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
- tests/manage/monitoring/prometheusmetrics/test_ocs_utilization.py
- tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
- tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
**Description**
This consists of the changes related to Tier 1 tests for Openshift Dedicated
> [Openshift-Dedicated] Added changes related to tier 1 tests 

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/registry.py
> Configure monitoring and registry during OCS deployment in external mode

- ocs_ci/deployment/deployment.py
> Allow deploying OCS > 4.6 on Power

- ocs_ci/deployment/deployment.py
Fixes: #3813
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1920261
> Increase timeout for mon pods for IBM Cloud

- ocs_ci/ocs/bucket_utils.py
> Fix for s3 delete_object invalid/empty version string

- ocs_ci/ocs/elasticsearch.py
This PR change the way all data that retrieve from the deployed elastic-search (which used the benchmark-operator)
to the main elastic-search server.
Before this PR all records was loaded sequentially (one by one) which may take several hours (182K records took ~11 Hours),
While this PR change it to be done as a bulk (Same 182K records took ~ 12 Min.)
> Loading elasticsearch data as bulk and not one by one

- tests/manage/mcg/test_namespace.py
> Remove acceptance marker from namespace bucket test cases

- ocs_ci/deployment/deployment.py
- ocs_ci/utility/utils.py
Closes: #3764 
This PR removes the workaround added in #3767 and #3782 
> Remove workaround: [AZURE] Apply SSD tuning as a workaround for bug 1909793

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
> Install OCS operator via ui 

- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/utility/utils.py
Signed-off-by: Aaruni Aggarwal <aaruniagg@gmail.com>
> modifying new timeout values for power architecture

- ocs_ci/ocs/small_file_workload.py
- tests/conftest.py
- tests/e2e/scale/test_scale_small_file_workload.py
Look for storage space leaks in Ceph Filesystems.
> Add small file workload test for scale

- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
> skip test_rwo_pvc_fencing_unfencing test case for IBM since PlatformNodesFactory is not implemented for IBM

- ocs_ci/deployment/vmware.py
> generating manifests and removing Machines and MachineSets

- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
2. apply skipif_bmpsi marker for few acceptance tests
> 1. Add a new marker skipif_bmpsi for skipping tests on baremetal psi

- tests/e2e/scale/test_cephfs_many_files.py
Avoids AlreadyExists exceptions.
> Make sure pvc and pod names are unique.

- ocs_ci/ocs/resources/storage_cluster.py
> Fixing osd tree verification on BM platform

- docs/usecases/deployment_without_ocs.md
Documentation update fixing https://github.com/red-hat-storage/ocs-ci/issues/3828
> docs: LSO CI note in FAQ entry for manual OCS setup

- tests/conftest.py
- tests/e2e/performance/test_fio_benchmark.py
with this PR i am implementing code reused of Performance test withing the FIO benchmark test.
> FIO | clean code duplication

- ocs_ci/ocs/bucket_utils.py
- tests/manage/rgw/test_object_bucket_size.py
Covers bz: 1880747 and 1880748
> Test to validate available size in object bucket. CustoBZ(1880747 and 1880748)

- ocs_ci/deployment/terraform.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/load_balancer.py
> Add nodes using terraform in vSphere

- docs/usage.md
- docs/usecases/using_alternative_ocp_mirrors.md
> Doc installer client cli args

- tests/e2e/logging/test_openshift-logging.py
> Fixes:3862

- ocs_ci/deployment/deployment.py
> Fix kubelet path for IBM Cloud OCP 4.6

- Jenkinsfile
Apparently we need to compile netifaces now.
> Jenkins: Install gcc

- tests/manage/mcg/test_namespace.py
> Fix flake8 issue with skipif_ocs_version

- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
> Remove node replacement test from acceptance suite

- conf/ocsci/early_testing_rhcos.yaml
- ocs_ci/deployment/vmware.py
- tests/conftest.py
> Config file which contains necessary values for early testing of RHCOS

- ocs_ci/framework/conf/ocs_version/ocs-4.8.yaml
- ocs_ci/framework/main.py
> Adding OCS 4.8 config file

- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
fix
(cherry picked from commit ea17c9bd826c846a7af66221e54df2e38d10ce3a)
> Remove node replacement test from acceptance suite (#3904)

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/disconnected.py
- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/catalog_source.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/utils.py
* implementing changes required for upgrade of disconnected OCS Cluster (from internal builds)
* fix issue with images on mirror registry with non-standard port (e.g. mirrored images for disconnected cluster)
> Upgrade of Disconnected OCS cluster from internal builds

- tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
The BZ https://bugzilla.redhat.com/show_bug.cgi?id=1844521 is closed, and Vijay fixed the functionality of adding a new worker node in VMWare, so we can remove the skip line and add the test of adding new worker nodes on VMWare.
> Add the test of adding node in VMWare since it's now fixed

- ocs_ci/ocs/hsbench.py
- tests/e2e/scale/noobaa/test_hsbench.py
Fixing https://github.com/red-hat-storage/ocs-ci/issues/3917
> Fixed issue with Azure test failing.

- ocs_ci/deployment/vmware.py
> Fix for ocp 4.8 installation issue

- tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle.py
> Fix for bucket policy issue in NS life cycle test

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/utils.py
> Fix terraform issue when add node

- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
> Verification that the already existing OSDs are not restarted post add capacity (bug 1931601)

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/resources/pod.py
> Change pod.get_memory() to return memory value for a specific container name

- docs/index.rst
- docs/stable_branch.md
> Added documentation around stable branch

- ocs_ci/deployment/terraform.py
- ocs_ci/ocs/platform_nodes.py
Adding refresh param to terraform apply and use refresh false when adding node
> Adding refresh param to terraform apply

- ocs_ci/framework/conf/ocp_version/ocp-4.7-ga-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.7-ga-minus1-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.7-ga-upgrade.yaml
> Configs for OCP 4.7 GA

- ocs_ci/ocs/resources/pod.py
- tests/e2e/workloads/test_jenkins_simulation.py
Fixes: #3895 
Signed-off-by: Prasad Desala tdesala@redhat.com
> Use pre-installed git package image in test_git_clone

- tests/conftest.py
> Fix login issue for IBM Cloud

- ocs_ci/ocs/constants.py
- ocs_ci/utility/utils.py
> Iterate over each page when retrieving OCS OLM Operator tags

- conf/ocsci/production_powervs_upi.yaml
- ocs_ci/deployment/helpers/lso_helpers.py
Signed-off-by: Aaruni Aggarwal <aaruniagg@gmail.com>
Fixes: OCS deployment on powerVS having more than 1 disk.
> modifying lso_helpers.py for power

- conf/README.md
- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
- docs/supported_platforms.md
- ocs_ci/deployment/deployment.py
> Update kubelet path for IBM Cloud

- conf/deployment/aws/ipi_3az_rhcos_3m_4w_arbiter.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/constants.py
With this PR we will be able to deploy an arbiter/stretch cluster.
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>
cc @raghavendra-talur
> deploy: Add a way to deploy arbiter/stretch cluster

- docs/usage.md
- ocs_ci/cleanup/vsphere/cleanup.py
Changing parameter names for vsphere cleanup to align with the name convention of ocs-ci
> Changing parameter names for vsphere cleanup

- ocs_ci/ocs/amq.py
> Replace apply with create

- ocs_ci/helpers/helpers.py
when tests run on midnight.
Fixes #3844 on github
> Fix time measurement error where negative time durations occur

- ocs_ci/deployment/vmware.py
> Fix for thick_sc key error

- ocs_ci/ocs/resources/storage_cluster.py
> Fix UI deployment over 3 AZs

- docs/getting_started.md
> Add empty line before new section

- tests/e2e/scale/test_scale_pgsql.py
Skip pgsql test case due to https://github.com/red-hat-storage/ocs-ci/issues/3983
> Skipping pgsql in scale test

- ocs_ci/ocs/resources/pod.py
> Fix in getting node name for aws

- ocs_ci/ocs/amq.py
- ocs_ci/templates/workloads/amq/rbac.yaml
- tests/e2e/workloads/amq/test_amq_streamer_creation.py
- tests/e2e/workloads/amq/test_amq_streams.py
> Fix amq failures

- tests/conftest.py
- tests/e2e/logging/test_openshift-logging.py
> Set logging channel as stable for version >= OCP 4.7

- ocs_ci/ocs/bucket_utils.py
- tests/e2e/flowtest/mcg/test_mcg_namespace_disruptions_crd.py
- tests/e2e/flowtest/mcg/test_mcg_namespace_disruptions_rpc.py
- tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
- tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_rpc.py
- tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops_crd.py
- tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops_rpc.py
Split namespace e2e tests to CRD and RPC
> Split and update E2E mcg namespace tests to cover CRDs

- conf/ocsci/early_testing_rhcos.yaml
> Updating new release image for early testing  of RHCOS

- ocs_ci/ocs/ui/add_replace_device_ui.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/infra_ui.py
- ocs_ci/ocs/ui/views.py
- tests/ui/test_add_capacity_ui.py
> add capacity on internal cluster via ui (selenium)

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/utility/kms.py
- ocs_ci/utility/utils.py
- pytest.ini
- tests/conftest.py
- tests/manage/mcg/test_kms.py
> skipif_no_kms marker and NooBaa KMS test

- tests/manage/mcg/test_bucket_deletion.py
We've seen a failure of `test_bucket_delete_with_objects` in one of our recent runs.
Upon closer inspection, it was discovered that the test uses `BUCKET_MAP` to create buckets, and because of that, *does not wait for them to bind*.
This resulted in us trying to sync objects to buckets that were not yet ready, and running into a `NoSuchBucket` error.
I replaced the logic with a call to `bucket_factory()`, that by default waits for the buckets to become healthy.
> Replace BUCKET_MAP call with bucket_factory() in test_bucket_deletion

- ocs_ci/ocs/resources/mcg.py
- tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
- tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops_crd.py
> Adding rgw resource for e2e namespace tests

- ocs_ci/utility/workloads/helpers.py
- ocs_ci/utility/workloads/jenkins.py
- tests/e2e/workloads/test_jenkins_simulation.py
This fixes #4027. I just had tests on ppc64le pass.
> Make test_jenkins_simulation work on all architectures

- conf/deployment/aws/ipi_6az_rhcos_3m_6w.yaml
> Adding config file for 6 AZ's

- ocs_ci/ocs/perftests.py
This PR add more data which collected from the environment, to use in the performance report.
The data collection is done in the PASTest object at the setup of the test, so
each test that is based on this class, will have the data to in it's report.
> Collecting more environment data for performance test report

- ocs_ci/ocs/utils.py
> Fix for toolbox pod disappearance in external mode

- ocs_ci/framework/pytest_customization/marks.py
- tests/e2e/flowtest/test_base_operation_node_drain.py
- tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
- tests/e2e/workloads/amq/test_amq_node_reboot_and_shutdown.py
- tests/e2e/workloads/jenkins/test_jenkins_node_reboot.py
- tests/manage/pv_services/pvc_clone/test_node_restart_during_pvc_clone.py
- tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
- tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
- tests/manage/z_cluster/nodes/test_nodes_restart.py
- tests/manage/z_cluster/nodes/test_worker_nodes_network_failures.py
> Skipping test cases for vSphere IPI platform which involves getting VM from resource pool

- tests/manage/z_cluster/test_delete_rook_ceph_mon_pod.py
Delete rook-ceph-operator and delete the created rook-detect-version pod
when created
> Automating bz https://bugzilla.redhat.com/show_bug.cgi?id=1859033

- tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
> Skipping rgw client access on non supported platforms

- tests/conftest.py
> Skip alert check for development mode

- ocs_ci/utility/kms.py
> Add cluster-name to vault resources like path, policy and namespace

- tests/conftest.py
> Donot collect pytest_collection_modifyitems for OCP only deployments

- ocs_ci/ocs/amq.py
- ocs_ci/ocs/couchbase.py
- tests/conftest.py
- tests/e2e/workloads/test_new_sc_rbd_e2e_workloads.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/4040
> e2e workload fixes

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.7-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.8-config.yaml
> Updating templates

- ocs_ci/ocs/node.py
> Pick machine list based on machine type

- tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
> 1904917 bz fixed on OCS4.7

- ocs_ci/templates/ocs-deployment/stageImageContentSourcePolicy.yaml
> Fix for imageContentSourcePolicy for RHCS image

- ocs_ci/utility/utils.py
> Force client download if existing oc version does not match config

- ocs_ci/framework/main.py
> Add hyphen between testrun_name and username for RP launch name

- ocs_ci/ocs/exceptions.py
Fixes: #4080
Just fixing a bug I introduced, nothing to see here...
> ResourceWrongStatusException: Set all attributes

- ocs_ci/ocs/ocs_upgrade.py
> Fix noobaa label issue for upgrade to OCS 4.7

- ocs_ci/ocs/cluster.py
> Fix validate_cluster_on_pvc for OCS <= 4.5

- ocs_ci/templates/ocp-deployment/install-config-baremetal-upi.yaml.j2
> Update base install-config file for BM

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/exceptions.py
- ocs_ci/utility/utils.py
- tests/conftest.py
This PR will address a few of the issues raised in #4093
> OC download fixes

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/constants.py
- tests/conftest.py
- tests/manage/pv_services/test_rbd_thick_provisioning.py
Test case to verify PVC creation and consumption using RBD thick provisioning enabled storage class.
OCS-2500 - FT - PVC creation using RBD thick provisioning enabled storage class
> Test case - RBD thick provisioned PVC

- tests/manage/monitoring/prometheus/test_capacity.py
> Skip capacity tests due to bz 1943137

- conf/deployment/aws/ipi_6az_rhcos_3m_6w.yaml
Change Instance type to m4.4xlarge in conf/deployment/aws/ipi_6az_rhcos_3m_6w.yaml
> Change Instance type to m4.4xlarge in conf/deployment/aws/ipi_6az_rhcos_3m_6w.yaml

- ocs_ci/helpers/helpers.py
- tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
> Add support multiple daemons on one worker node [coredump test]

- ocs_ci/framework/conf/ocp_version/ocp-4.8-upgrade.yaml
> OCP 4.8 upgrade config file

- ocs_ci/ocs/scale_lib.py
Added Scale lib functions to create pods using kube_job
Added functionality to add mutliple PVCs to single POD
Added functionality to create DC pod
Added functionality to create pod with liveness probe and to start fio IO
> Function To scale pods using Kube_Job, DC and attach multiple PVCs

- ocs_ci/deployment/deployment.py
- ocs_ci/utility/utils.py
> Fix registry for non OCS-CI OCP deployed clusters

- ocs_ci/framework/pytest_customization/ocscilib.py
> Added --skip-download-client CLI option

- conf/README.md
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/pytest_customization/ocscilib.py
> Explicitly set log level for reportportal_client logger

- conf/README.md
> Added doc for skip_download_client config

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/constants.py
- tests/manage/mcg/test_mcg_resources_disruptions.py
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1903573
> Cust issue: Test for changing default scc on noobaa db

- conf/deployment/vsphere/ipi_1az_rhcos_vmfs_3m_3w.yaml
- conf/ocsci/vsphere_ipi.yaml
> Adding vSphere IPI config files

- ocs_ci/ocs/must_gather/const_must_gather.py
- ocs_ci/ocs/must_gather/must_gather.py
> Fix must gather tests

- ocs_ci/deployment/baremetal.py
- ocs_ci/utility/aws.py
> Recreate DNS record at the time of BM Install

- ocs_ci/ocs/bucket_utils.py
- tests/manage/mcg/test_namespace_crd.py
> Add timeout sampler to verify cached objects

- docs/usage.md
- ocs_ci/utility/ocs_build.py
- setup.py
Adding ocs-build entrypoint which is able to return latest internal build.
> Add ocs build utility

- tests/manage/z_cluster/cluster_expansion/conftest.py
The BZ https://bugzilla.redhat.com/show_bug.cgi?id=1844521 is closed, and Vijay fixed the functionality of adding a new worker node in VMWare, so we can remove the skip line and add the test of adding new worker nodes on VMWare.
> add the test of adding a new worker node on vSphere platform

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/utils.py
> Check whether all nodes are created after OCP deployment

- ocs_ci/ocs/scale_noobaa_lib.py
- tests/e2e/scale/noobaa/test_scale_obc_creation.py
Creation of OBCs in MCG and RGW.
> Noobaa scale obc creation

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.3-upgrade.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.4-upgrade.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.5-upgrade.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.6-upgrade.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.7-upgrade.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.8-upgrade.yaml
> Fix OCP upgrade

- ocs_ci/ocs/resources/storage_cluster.py
> Test "add capacity" via UI on tier1 suite

- ocs_ci/ocs/amq.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/workloads/amq/kafkadrop.yaml
- ocs_ci/utility/utils.py
- tests/e2e/workloads/amq/test_rgw_kafka_notifications.py
> Test to verify rgw kafka notifications

- ocs_ci/framework/pytest_customization/marks.py
> Enable health check for performance, scale and workload markers

- ocs_ci/templates/ocp-deployment/rhcos_images.yaml
> Add BM Config Files for OCP 4.8

- ocs_ci/ocs/node.py
> Adding infra nodes in verify_all_nodes_created function

- ocs_ci/deployment/helpers/prechecks.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/utility/vsphere.py
> Template check for vsphere

- ocs_ci/ocs/openshift_ops.py
> Download openshift client while setting kubeconfig if needed

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/machine.py
- ocs_ci/ocs/scale_lib.py
- ocs_ci/templates/openshift-infra/machineset-azure.yaml
This is enhancement for adding more worker nodes to azure cluster
for running app pods.
> Azure Scale: Enhancement to add custom_machineset/node which will be used to running app pods

- ocs_ci/ocs/resources/storage_cluster.py
> Skip on failure domain verification on upgraded lso cluster

- ocs_ci/ocs/scale_lib.py
Fix to remove custom machinesets created during tests in Azure cluster
> Fix to remove added machinesets and nodes in Azure

- conf/deployment/aws/upi_1az_rhcos_3m_3w_disconnected.yaml
- conf/deployment/aws/upi_1az_rhcos_3m_3w_proxy.yaml
- conf/deployment/aws/upi_3az_rhcos_3m_3w_disconnected.yaml
- conf/deployment/aws/upi_3az_rhcos_3m_3w_proxy.yaml
- upi_1az_rhcos_3m_3w_disconnected.yaml
- upi_3az_rhcos_3m_3w_disconnected.yaml
- upi_1az_rhcos_3m_3w_proxy.yaml
- upi_3az_rhcos_3m_3w_proxy.yaml
> add AWS disconnected and proxy deployment production configs

- ocs_ci/ocs/ui/base_ui.py
> Support multiple UI tests

- tests/manage/monitoring/prometheus/test_rgw.py
> Skip RGW alerting test due to bz 1953615

- conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_external_with_namespace.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_external_vault_with_namespace.yaml
> Add vsphere/aws ocs with vault production yamls

- ocs_ci/ocs/ripsaw.py
This PR adds a cache dropper pod the benchmark-operator base tests (FIO / Smallfiles)
this will enable the benchmarks to drop off the kernel cache between samples for consistent results.
this feature supported by the FIO and Smallfiles benchmark and will integrate into them (updating the CRD files) after this PR will be merged.
> Add cache-dropper pod to the benchmark-operator base tests

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/helpers/bdi_helpers.py
- ocs_ci/ocs/bdi/bdi_base_class.py
- ocs_ci/ocs/bdi/config.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/workloads/bdi/configure-workload.yaml
- ocs_ci/templates/workloads/bdi/data-load-job.yaml
- ocs_ci/templates/workloads/bdi/ibm_bdi_scc.yaml
- ocs_ci/templates/workloads/bdi/run-workload.yaml
- tests/e2e/workloads/bdi/conftest.py
- tests/e2e/workloads/bdi/test_bdi_workload.py
IBM defined workload that models a day in the life of a business intelligence
application.
The automation is currently uses the default configuration for 3 executions:
- warmup
- multiuser, 16 users, static values
- multiuser, 32 users, static values
> [BDI automation]

- tests/e2e/workloads/amq/test_rgw_kafka_notifications.py
> Skip test over external mode cluster
