red-hat-storage/ocs-ci

- tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
The test case tests/manage/pv_services/pvc_resize/test_pvc_expansion.py::TestPvcExpand::test_pvc_expand_expanded_pvc is failing with the below error.
```
for df_out in TimeoutSampler( 240, 3, pod_obj.exec_cmd_on_pod, command="df -kh" ):> df_out = df_out.split()E AttributeError: 'NoneType' object has no attribute 'split'tests/manage/pv_services/pvc_resize/test_pvc_expansion.py:110: AttributeError
```
The output of df command on the app pod did not return any value. As a solution, check whether the df output is empty before processing the value
Issue #3846 
> Check whether the df output is empty before processing the value in test test_pvc_expand_expanded_pvc

- ocs_ci/helpers/helpers.py
- tests/e2e/performance/test_pvc_snapshot_performance.py
On OCS 4.8 the way that the snapshot creation report to the log was changed, and all performance test of snapshot creation was failed.
This PR is fixing this problem and in case the creation time did not found in the log in the previous format, it try to find it in the new format (for backward compatibility)
> Updating Snapshot creation time log parsing

- ocs_ci/ocs/resources/storage_cluster.py
- tests/ui/test_pvc_ui.py
Thick provisioning is disabled in OCS4.8 but deployment
is still checking and failing because of the same.
Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>
> deployment: Don't check for rbd-thick sc in OCS4.8

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/rgw.py
- tests/conftest.py
Manual exposure of the service is no longer needed thanks to [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1915730)
> Remove manual exposure of RGW service on OCS 4.7+

- ocs_ci/ocs/resources/backingstore.py
Up until now, we tried to delete PVCs that weren't necessarily properly created before, leading to an exception when accessing the [0] index of the PVC list. This PR skips the deletion if no fitting backingstores are found.
> Skip deletion for PVC backingstores that couldn't be found

- setup.py
- tests/manage/mcg/test_bucket_deletion.py
- tests/manage/mcg/test_object_integrity.py
- tests/manage/mcg/test_write_to_bucket.py
- tests/manage/rgw/test_bucket_deletion.py
- tests/manage/rgw/test_object_integrity.py
Some of our tests rely on the retrieval of test objects from AWS. Because of transient connection errors, those tests sometimes fail.
These new markers should rerun each test in case it fails, which should hopefully reduce the number of failures overall.
> Add rerun markers for flaky tests

- ocs_ci/ocs/ui/mcg_ui.py
Since MCG is entirely dependent on OCS version, we should run the tests based on the OCS version in the cluster, and not the OCP one.
> Rely on OCS version rather than OCP for MCG UI tests

- ocs_ci/ocs/utils.py
- ocs_ci/templates/ocs-deployment/toolbox_pod.yaml
- Update the creds and image in toolbox_pod.yaml
- Update setup_ceph_toolbox() to use new cred format and by default use 
rook image present in rook-ceph-operator
Fixes: #4486 
> Update toolbox_pod.yaml and utils.py to use new creds format

- tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
- tests/manage/pv_services/test_delete_pvc_while_provisioning.py
- tests/manage/pv_services/test_expansion_snapshot_clone.py
- tests/manage/pv_services/test_rbd_thick_provisioning.py
- tests/manage/pv_services/test_verify_thick_pvc_utilization.py
Skip RBD thick test cases because the feature will not be fully supported in OCS4.8
> Skip RBD thick test cases in OCS4.8

- tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
Output:
```
sh-4.4# ceph health detail
HEALTH_WARN 3 daemons have recently crashed
RECENT_CRASH 3 daemons have recently crashed
mgr.a crashed on host rook-ceph-mgr-a-56fdcbb6-nv54h at 2021-07-06 12:08:04.659384Z
osd.2 crashed on host rook-ceph-osd-2-74cc6b5fd9-t5wr4 at 2021-07-06 12:08:10.811095Z
mon.g crashed on host rook-ceph-mon-g-649bd4589d-6tp7j at 2021-07-06 12:08:16.709094Z
```
> Verify ceph health is HEALTH_WARN after ceph daemon killing

- ocs_ci/ocs/ocp.py
By default, `get_ocs_version` checks for the version of the first CSV it can find.
However, the first CSV is now ElasticSearch operator, which means the function returns its version, instead of the OCS one.
> Fix `get_ocs_version()`

- ocs_ci/deployment/factory.py
bc81735 broke instances where ENV_DATA.platform is not all lower-case.
> Fix regression in DeploymentFactory

- ocs_ci/helpers/helpers.py
- tests/manage/z_cluster/test_drain_node_mon.py
- tests/manage/z_cluster/test_rook_operator_restart_during_mon_failover.py
https://bugzilla.redhat.com/show_bug.cgi?id=1959983
Test Process:
1.Get worker node name where monitoring pod run
2.Verify pdb status, disruptions_allowed=1, max_unavailable_mon=1
3.Drain node where monitoring pod run
4.Verify pdb status, disruptions_allowed=0, max_unavailable_mon=1
5.Verify the number of mon pods is 3 for (1400 seconds)
6.Change node to be scheduled
7.Wait for mon pods to be on running state
8.Verify pdb status, disruptions_allowed=1, max_unavailable_mon=1
9.Check ceph status
> GSS bug,Verify the num of mon pods is 3 when drain node

- tests/e2e/performance/test_pvc_snapshot_performance.py
since the smallfile benchmark is used in this test only to create files on the volume and we are not interesting with the small file results, the ES configuration disabled in this test.
> disable ES from smallfile used in snapshot test

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/rgw.py
- tests/conftest.py
Since the current implementation on external mode is problematic, it'd probably be best to return to the old flow for the time being.
> Revert #3928 and #4548

- ocs_ci/ocs/cluster.py
current time out cause "test add capacity" to fail, as timeout is too short
> increased waiting for rebalance timeout when io in background

- tests/e2e/performance/test_pvc_attachtime.py
This PR push the results of the pvc_attached time test to the ElasticSearch server so we can add them to the
Performance-Dashboard.
> Pushing attach_time results to ES for the performance-dashboard

- ocs_ci/framework/pytest_customization/marks.py
- pytest.ini
Added new tier scale_long_run and scale_changed_layout
scale_long_run: scale tests which has execution time in days
scale_changed_layout: scale capacity/node tests without teardown
> Introducing new tier scale_long_run and scale_changed_layout

- ocs_ci/ocs/scale_lib.py
- tests/e2e/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py
Commented pg_balancer validation in scale tests
Due to PG auto_scale enabled sometime PG's can't be equally distributed across OSDs
Added validation for FileNotFoundError
> Fix for Scale test failure during upgrade tests

- ocs_ci/helpers/helpers.py
- tests/manage/z_cluster/test_rook_ceph_operator_log_type.py
https://bugzilla.redhat.com/show_bug.cgi?id=19628
Test Process:
1.Set ROOK_LOG_LEVEL param to "DEBUG"
2.Respin OSD pod
3.Verify logs contain the expected strings
4.Verify logs do not contain the unexpected strings
5.Set ROOK_LOG_LEVEL param to "INFO"
6.Respin OSD pod
7.Verify logs contain the expected strings
8.Verify logs do not contain the unexpected strings
Comment:
On INFO mode,  expected log type [I],[E]
On DEBUG mode, expected log type [I],[D],[E]
> GSS, test the mechanism to enable and disable debug logs

- tests/e2e/scale/test_cephfs_many_files.py
tests/e2e/scale/test_cephfs_many_files.py
This fixes issue #4589
> Increase timeout for tar creation in

- tests/e2e/scale/test_ceph_pod_respin_in_scaled_cluster.py
- tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
- tests/e2e/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py
In scale tests like creation of 1000+ PVC's and PODs we need more worker nodes(other than OCS nodes)
for running app pods and all the relevant tests supports only IPI platform.
> Added ipi_deployment_required marker in scale tests where node scaling is done for app pods.

- ocs_ci/deployment/aws.py
- variable OCP_INSTALL_DIR is now required by `upi_on_aws-install.sh`(`bash.vars`)
fixes: https://github.com/red-hat-storage/ocs-ci/issues/4649
> fix AWS UPI RHEL installation: add required var

- ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-upgrade.yaml
Command:
```
curl -sH 'Accept:application/json' \
'https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.8' \
| jq -r '.nodes[] | .version' | sort -V | tail -1
```
Returns:
4.8.2
So we are ready to move to the stable channel.
> Change channel for OCP 4.8-GA config to stable

- tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
- tests/manage/pv_services/test_delete_pvc_while_provisioning.py
- tests/manage/pv_services/test_expansion_snapshot_clone.py
- tests/manage/pv_services/test_rbd_thick_provisioning.py
- tests/manage/pv_services/test_verify_thick_pvc_utilization.py
Skip RBD thick test cases because the feature will not be fully supported in OCS4.9
> Skip RBD thick test cases in OCS 4.9

- ocs_ci/helpers/helpers.py
- tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
- tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py
- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Update tests to run IO on pods attached with PVCs having unique access mode and volume mode combination. This is to ensure that the IO will consume PVCs with all supported combination of of access mode and volume mode. The will also reduce the number of pods running IO simultaneously.
Tests updated:
tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
> Update tests to run IO on pods attached with PVCs having unique access mode and volume mode combination

- ocs_ci/framework/conf/ocs_version/ocs-4.9.yaml
> Changing default_latest_tag to stable for OCS 4.9

- ocs_ci/ocs/ui/mcg_ui.py
The tests failed because, although the checkbox component could be found in time, it seems that the click on it would not register without a slight wait before and after the action.
> Fix bucketclass UI tests

- tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Closes: #3846 
This PR is for fixing the issue in test mentioned in [comment](https://github.com/red-hat-storage/ocs-ci/issues/3846#issuecomment-883906599)
> Check whether the df output is empty before processing the value in test_resource_deletion_during_pvc_expansion

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/scale_lib.py
- ocs_ci/templates/workloads/osd_scale/osd_scale_benchmark.yaml
- tests/e2e/scale/test_osd_node_balancing.py
This test checks osd distributions for 4.7 clusters where 3 nodes and 3 osds are added at a time.  This should work for
both flexible scaling and non-flexible situations.  This makes sure that one case of OCSQE-571 is tested, and also makes sure that comment #33 in bugzilla Bug 1817438 is checked.
> Add tests/e2e/scale/test_osd_node_balancing.py

- ocs_ci/ocs/ocp.py
This PR fixing issue with IBM Cloud (or any other platform) which the OCP channel is not configure.
in this case instead of the the test will failed because the we do not found the OCP channel in the output of the command `oc get clusterversion -o json` it will return "None" - this is the string None and not None value since elastic-search an not index the None value
> Fix issue with retrieving ocp channel

- ocs_ci/deployment/deployment.py
When deployment is done via UI, the NAD is referenced along with the namespace in which it is present.
The format is as follows:
```
public: <namespace>/<name of NAD>
```
Updating the code to follow the same format.
> [Multus] Add namespace reference along with NAD name in the StorageCluster network spec

- docs/getting_started.md
pull secret link was updated from cloud.openshift.com to https://console.redhat.com/openshift/install/pull-secret
> Update Pull-secret link

- tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
- tests/manage/z_cluster/nodes/test_worker_nodes_network_failures.py
Fixes:  Some of the failing tests in tier4 as these tests are shutting down the network interface which in turn causes the worker nodes to be in NotReady state as kubelet.service can't talk outside. Then our environment tries to restart the node by SSHing into the worker node which is also not possible as network interface is down. 
Signed-off-by: Aaruni Aggarwal <aaruniagg@gmail.com>
> Adding skip for some of tier4 tests for power

- ocs_ci/helpers/helpers.py
When using:
`pod_factory(pvc=pvc, raw_block_pv=True)`
I fails:
`>               pod_data["spec"]["containers"][0]["volumeDevices"][0][
"devicePath"
] = raw_block_device
E               KeyError: 'volumeDevices'
`
When no pod_dict_path is used the default is constants.CSI_RBD_POD_YAML with suitable for filesystem and the  conditions doesn't handle it and get to a part that only assign devicePath and it fails.
Before that part there is:
`        elif pod_dict_path == constants.NGINX_POD_YAML:
temp_dict = [
{
"devicePath": raw_block_device,
"name": pod_data.get("spec")
.get("containers")[0]
.get("volumeMounts")[0]
.get("name"),
}
]
del pod_data["spec"]["containers"][0]["volumeMounts"]
pod_data["spec"]["containers"][0]["volumeDevices"] = temp_dict`
Which is suitable also for …
> fix create_pod when raw block is used with no pod_dict_path

- ocs_ci/cleanup/aws/defaults.py
I think this MR:
https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/694/diffs
Changed the logic and cluster names is now like j-ddd .
So we would like to include both.
> Add new j-ddd prefix

- tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
Test case test_worker_node_restart_during_pvc_expansion enhancement.
1. Check new size on pod after volume expansion.
2. Add describe output of PVC and PV if expansion fails.
Closes #2750 
> Test case test_worker_node_restart_during_pvc_expansion enhancement

- ocs_ci/ocs/scale_lib.py
- tests/e2e/scale/test_scale_3_OCS_worker_nodes_and_1500_PVCs.py
renamed test_ceph_pod_respin_in_scaled_cluster.py to test_scale_3_OCS_worker_nodes_and_1500_PVCs.py
Added reboot test to tests/e2e/scale/test_scale_3_OCS_worker_nodes_and_1500_PVCs.py
> Adding reboot tests to scale script tests/e2e/scale/test_scale_3_OCS_worker_nodes_and_1500_PVCs.py

- tests/e2e/performance/test_pvc_attachtime.py
This PR implements the following: 
1) Instead of having one measurement for pod attach time we create number ( currently 5) of sampled PVCs, attach pod to each one of them, calculate attach time for each pod and after that the test calculates
- average pod attach time
- standard deviation
2) After having calculated the average pod attach time and STD - those results are uploaded to the ES server. 
3) In addition to RBD and CephFS , the RBD Thick interface was added to this test. 
> improvements to test_pvc_attachtime.py

- ocs_ci/ocs/defaults.py
- ocs_ci/templates/CSI/rbd/csi-kms-connection-details.yaml
- ocs_ci/utility/kms.py
- tests/manage/pv_services/test_rbd_pv_encryption.py
Adding VAULT_BACKEND parameter to the csi-kms-connection-details to allow creation of encrypted PVs with the vault namespace functionality
Eng. Bug: [1997624](https://bugzilla.redhat.com/show_bug.cgi?id=1997624)
> Add VAULT_BACKEND parameter as a work around for BZ 1997624

- ocs_ci/utility/ibmcloud.py
This commit should fix the issue of volume leftovers in
IBM Cloud.
> Force delete storage when destroy IBM Cloud cluster

- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
- tests/manage/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py
Tests `test_add_ocs_node` and `test_ceph_csidriver_runs_on_non_ocs_nodes` are not compatible with OCP cluster installed via flexy, because of the way how terraform is used in Flexy for the OCP installation.
Created issue https://github.com/red-hat-storage/ocs-ci/issues/4802 for that, but the fix is not easy, so I would propose to skip those two tests for now.
> Skip tests if flexy deployment

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/templates/ui/chrome-proxy-extension-background.js.j2
- ocs_ci/templates/ui/chrome-proxy-extension-manifest.json.j2
- ocs_ci/utility/flexy.py
If `ENV_DATA["client_http_proxy"]` parameter is defined, configure proxy server for the Chrome/Chromium browser.
There is a big difference between configuring **not authenticated** and **authenticated** proxy server for Chrome:
* **not authenticated** proxy can be configured via `--proxy-server` command line parameter
* there is no easy way, to configure **authenticated** proxy in Chrome browser via Selenium, the only found solution is creating custom Extension ([see also this page](https://botproxy.net/docs/how-to/setting-chromedriver-proxy-auth-with-selenium-using-python/)). This doesn't work in headless mode!
This PR depends on PR https://github.com/red-hat-storage/ocs-ci/pull/4747.
> Configure proxy server for Chrome browser if required

- ocs_ci/ocs/node.py
In the node replacement verification steps, we need to check that the osd node name exists because, in some cases, we don't need to pass the new osd node name to the function since it does not always exist. Here is an example of a test that failed because we didn't check the new osd node name: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/5779/testReport/tests.manage.z_cluster.nodes.test_node_replacement_proactive/TestNodeReplacement/test_nodereplacement_proactive/
> Check the osd node name exist in the node replacement verification steps

- ocs_ci/ocs/resources/objectconfigfile.py
- ocs_ci/ocs/scale_lib.py
- tests/e2e/scale/test_scale_pvc_expand.py
Existing Scale Pvc expand test is skipped due to changes in scale_lib function for memory issue.
with the changes/enhancements in this PR code will support pvc_expand tests and other tests
we should not observe any memory failures since code is using kube_job for creating PVCs and PODs
> PR to fix scale pvc expand test

- ocs_ci/ocs/resources/pod.py
*. Fixes #4800 
*. Remove WA for recovering rook-ceph-crashcollector in wait_for_storage_pods() - #1631
> Fix condition in wait_for_storage_pods() to ignore rook-ceph-detect-version pod

- tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Enhancement to "test_pv_scale_and_respin_ceph_pods". Apart from existing four resource type (mgr, mon, osd and mds) in ceph resource types, additional resource types are added (rbdplugin_provisioner, cephfsplugin_provisioner, cephfsplugin, rbdplugin and operator)
Enhancements are part of "Automate scale tests with CSI pod re-spin" test
> Enhancement to "test_pv_scale_and_respin_ceph_pods" test with additional resource types

- ocs_ci/ocs/resources/storage_cluster.py
Skip RBD thick storage class verification due to the bug https://bugzilla.redhat.com/show_bug.cgi?id=2000865
> Skip RBD thick SC verification in 4.9

- tests/manage/pv_services/pvc_snapshot/test_restore_snapshot_using_different_sc.py
Test case test_snapshot_restore_using_different_sc is updated to use a storage class using different pool. This will verify the bug 1901954.
> Restore snapshot to different pool

- ocs_ci/ocs/cluster.py
- tests/e2e/performance/test_pvc_snapshot_performance.py
In OCS4.9, 'ceph status' doesnot give replica count value. Hence 'ceph mgr dump' command is used.
> Fix for get_ceph_default_replica returning None value.

- tests/manage/pv_services/test_verify_rwo_using_dc_pod.py
The test case test_verify_rwo_using_replicated_pod cannot be continued if all the pods are created on the same node.
This will also fixes #4431
> Skip test_verify_rwo_using_replicated_pod if all pods are created on the same node

- tests/conftest.py
- tests/manage/pv_services/pvc_snapshot/test_verify_rbd_trash_purge.py
Test case to verify RBD trash purge command when the  RBD image in trash have snapshots. Verifies bug 1964373.
OCS-2595 - FT-Verify RBD trash purge command when the RBD image in trash have snapshots
Updated snapshot_factory to delete the snapshots in teardown session which fixes #4672 
> Test case - Verify RBD trash purge command if the RBD PVCs have snapshots

- ocs_ci/deployment/flexy.py
`terraform.tfstate` file is available only for installation on vSphere platform
fixes: https://github.com/red-hat-storage/ocs-ci/issues/4879
> fix flexy_post_processing: terraform part is applicable only for vSphere platform

- tests/manage/mcg/test_namespace_crd.py
This test was missed in the changes introduced in #3754, and doesn't adhere to the design changes that were introduced into `write_files_to_pod_and_upload()`. The added variables should fix the problem.
> Fix `test_block_read_resource_in_namespace_bucket_crd`

- ocs_ci/ocs/pgsql.py
Adding `benchmark-operator` namespace while collecting logs of pgbench-1-dbs-client-1-* pod.
Signed-off-by: root <aaruniagg@gmail.com>
> Adding namespace while collecting logs for pgbench

- tests/manage/pv_services/pvc_clone/test_encrypted_rbd_pvc_clone.py
Add test case for creating clone of encrypted RBD PVCs
Vault auth method: Token auth
Backend Paths : kv-v1 and kv-v2
Polarion test cases:
[Test PVC-PVC clone for encrypted RBD PVCs (vaulttoken kv-v2)](https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-2651)
[Test PVC-PVC clone for encrypted RBD PVCs (vaulttoken kv-v1)](https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-2650)
> Test case to verify creation of encrypted RBD PVC clone

- ocs_ci/helpers/helpers.py
- tests/e2e/performance/test_pvc_bulk_creation_deletion_performance.py
- tests/e2e/performance/test_pvc_creation_deletion_performance.py
- tests/e2e/performance/test_pvc_multiple_creation_deletion_performance.py
- tests/fixtures.py
The content of this PR: 
1) Adding Bulk Delete functionality 
2) Adding parametrization of bulk size 
Please note that It was decided to parametrize bulk size to 2 values: 120 and 720 . 
It is possible to add additional  bulk size test cases, but it will cause the test to run for additional hours. 
Since our goal is to have this test as rather short test ( in terms of run time) - it was chosen to have only 2 bulk sizes as a parameter. 
120 - for backward compatibility with Performance results in the previous versions ( for bulk creation) 
720 - since this is close to the maximal bulk size tested on 3 masters and 2 workers cluster and a multiplication of 120 ( 720 = 120*6). 
We would like to compare the 120 and 720 bulk size results and make …
> Adding bulk deletion functions and functionality, adding parametrization of bulk size 

- tests/manage/monitoring/prometheusmetrics/test_ocs_utilization.py
CPU usage metric has been modified due to change in the "rate" function to "irate"
References:
1. https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/619/commits/e996e00fa3a0c17a7a9f5d01f6c1a3544731bd33
2. https://monitoring.mixins.dev/kubernetes/
Signed-off-by: Sravika Balusu <sravika.balusu@ibm.com>
> Modify the cpu usage metric

- tests/e2e/performance/test_pvc_bulk_creation_deletion_performance.py
This PR contains one small but important change that by mistake was not included in the previous big PR that implemented bulk deletion. This is changing E2ETest to PASTest. 
> test_pvc_bulk_creation_deletion_performance.py - change of E2Etest to PASTest

- ocs_ci/ocs/elasticsearch.py
- ocs_ci/ocs/exceptions.py
- tests/libtest/test_elasticsearch.py
This PR improve the local elasticsearch module by preventing it to leave leftovers if deployment failed.
it also :
* setting the storageclass as optional parameter
* Delete the namespace if it is already exists, and try to continue deployment
* Delete the project if PVC did not create
> improve the elasticsearch module

- tests/e2e/scale/conftest.py
- tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
Skipped tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py TC due to hitting memory issue
Removed entries of 2 TC, which is enhanced to work on vmware
> Skip tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py due to memory issue

- tests/e2e/workloads/couchbase/test_couchbase.py
- tests/e2e/workloads/couchbase/test_couchbase_node_drain.py
- tests/e2e/workloads/couchbase/test_couchbase_node_reboot.py
- tests/e2e/workloads/couchbase/test_couchbase_pod_respin.py
- tests/e2e/workloads/test_new_sc_rbd_e2e_workloads.py
We are seeing couchbase workload failing to run from OCP 4.8 onward, i.e cb-example pod fails to come with Readiness probe failure, skipping those tests until we find the root cause and resolve it.
> Skip couchbase workload tests

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/catalog_source.py
Fixes: #4929
In the case of live deployment and then upgrade to internal build,
we have to disable default sources as we cannot change the image in
the default redhat-operators.
> Disable default sources when upgrading

- ocs_ci/framework/pytest_customization/ocscilib.py
- tests/conftest.py
With this fix, it should be possible to use squad marks for test execution like
`-m brown_squad`.
For example:
```
$ run-ci --collect-only -m purple_squad
...
collected 865 items / 769 deselected / 96 selected                             
<Module tests/e2e/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py>
<Function test_scale_pvcs_pods_pre_upgrade>
<Module tests/ecosystem/upgrade/test_configuration.py>
<Function test_load_crush_map>
<Module tests/ecosystem/upgrade/test_noobaa.py>
<Function test_fill_bucket>
<Function test_buckets_before_upgrade>
<Function test_start_upgrade_mcg_io>
<Module tests/ecosystem/upgrade/test_resources.py>
<Function test_start_pre_upgrade_pod_io>
<Module tests/ecosystem/upgrade/test_monitoring_after_ocp_upgrade.py>
<Function test_monitoring_before_ocp_upgrade> …
```
> Fix tests selection based on squad marks

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/perfresult.py
- ocs_ci/ocs/perftests.py
- ocs_ci/templates/workloads/smallfile/SmallFile.yaml
- tests/e2e/performance/test_small_file_workload.py
change the number of threads / clients (pods) /files per thread and increase the number of samples from 3 to 5
improve the read from elasticsearch function, to read more then 10000 records
Update the CRD file with response-times and disable cache dropping
> Updateing test parameters for Smallfiles performance test

- tests/e2e/performance/test_bulk_pod_attachtime_performance.py
The new test measures Bulk pod attachment time ( 100 /200 RBD/CephFS pods are attached each pod to one PVC , the attachment is done in a bulk). 
At the end the test results are uploaded to the ES server.
> Adding a new test_bulk_pod_attachtime_performance test

- ocs_ci/ocs/ui/deployment_ui.py
Storage Cluster tab return "404:Page not found" 
http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-098vuf1cs33-t1/j-098vuf1cs33-t1_20211016T172130/logs/screenshots_ui_1634405155/test_deployment/2021-10-16T17-54-42.429099.png
> Fix OCS deployment via UI

- tests/e2e/scale/conftest.py
- tests/e2e/scale/test_osd_node_balancing.py
Skipped TC tests/e2e/scale/test_osd_node_balancing.py due to bugzilla bz
> Skip test_osd_node_balacing due to bz

- tests/manage/mcg/test_host_node_failure.py
- tests/manage/mcg/test_mcg_resources_disruptions.py
- Add new tests in mcg/test_host_node_failure.py
- Reduce timeout from 300 seconds to 90 seconds in existing mcg/test_mcg_resources_disruptions.py
> Implement tests for NooBaa component rescheduling improvements

- tests/e2e/performance/test_bulk_pod_attachtime_performance.py
- tests/e2e/performance/test_pvc_attachtime.py
The current PR contains improvements to the following tests: 
1) test_pvc_attachtime.py
2) test_bulk_pod_attachtime_performance.py 
The improbvements are : adding additional keys and values to the data sent to the ES server, for further production of a comprehensive performance report. 
> adding additional keys to the ES reports

- ocs_ci/ocs/resources/storage_cluster.py
- tests/ui/test_pvc_ui.py
Thick provisioning is being deprecated, removing the storage class
check and tests. Complete code cleanup is still pending.
Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>
> deployment: remove checks for rbd-thick sc

- ocs_ci/ocs/jenkins.py
- ocs_ci/ocs/ocp.py
Added "Pipeline Utility Steps" plugin via Jenkins Template
OCP team changed the default plugin list on OCP4.9
https://github.com/openshift/jenkins/commit/44deeafca418dc5a786b1dcd705b4aaef0d2fe3c#diff-2a93d798ca112ffa17e2d1d713ef42d02dab81e4704b8a783d9b03635b6470b3
Fixes: #4911 
> Fix jenkins workload on OCP4.9

- ocs_ci/framework/pytest_customization/marks.py
- tests/conftest.py
Do not automatically add squad mark to tests, which already have squad mark manually assigned.
> allow override automatically added squad marks

- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
- tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
ROSA is Redhat openshift service on AWS. Hence the test
applicable on aws should be consider for ROSA platform as well
> Add marker for aws based platforms only test 

- tests/manage/storageclass/test_create_2_sc_with_1_pool_comp_rep2.py
- tests/manage/storageclass/test_create_2sc_at_once_with_io.py
- tests/manage/storageclass/test_create_sc_reclaim_policy_rep2_comp.py
- tests/manage/storageclass/test_multiple_sc_comp_rep_data_delete.py
- tests/manage/storageclass/test_new_sc_rbd_replica2_3.py
tests/manage/storageclass/test_create_2sc_at_once_with_io.py::TestCreate2ScAtOnceWithIo::test_new_sc_rep2_rep3_at_once is failing in [run](https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/2228/)
There is some timeout issue and it not related to compression as checking it manually through the test I see compression is there. Added runtime to fio and removed getting results for the fio as they are not used and they are the one causing the timeout.
> Fix failure in compression test

- tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
- tests/manage/pv_services/test_delete_pvc_while_provisioning.py
- tests/manage/pv_services/test_expansion_snapshot_clone.py
- tests/manage/pv_services/test_rbd_thick_provisioning.py
- tests/manage/pv_services/test_verify_thick_pvc_utilization.py
Skipping RBD thick tests because the feature will be deprecated.
Fixes #5059 
> Skip RBD thick test cases

- conf/ocsci/vault_external_standalone_ca_only_v1.yaml
- conf/ocsci/vault_external_standalone_ca_only_v2.yaml
- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/kms.py
Based on https://bugzilla.redhat.com/show_bug.cgi?id=1970641, we need to import only the CA Certificate file and not use Client Certificate and Client Private Key.[for deployment cluster with KMS] 
> Deploy KMS with CA Certificate[without Client Certificate and Client Private Key]

- conf/README.md
- ocs_ci/deployment/disconnected.py
This parameter is required for non x86_64 architectures.
> Possibility to add param --binary-image to opm index prune command

- ocs_ci/deployment/deployment.py
- create _custom_ `redhat-operators` catalog source before configuring LSO (otherwise there is no catalog source from which it can be installed (all default sources are disabled on disconnected deployment)
> Fix disconnected lso deployment

- conf/README.md
- docs/results.md
- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/templates/reporting/report_portal.cfg
- pytest.ini
- requirements.txt
- tests/conftest.py
Remove pytest-reportportal integration code now that we have moved to utilizing rp_preproc.
> Remove legacy reportportal

- ocs_ci/ocs/constants.py
`noobaa-operator` package was renamed to `mcg-operator` (we can keep there both names, as it skips those which are not available)
Related to https://github.com/red-hat-storage/ocs-ci/issues/5080.
> fix disconnected odf > 4.9.0-231 deployment

- tests/e2e/performance/csi_tests/test_pvc_attachtime.py
Adding marker to skip the test: test_pod_start_time while running with param: CEPHBLOCKPOOL_THICK
> Adding marker to skip the test: test_pod_start_time while running with param: CEPHBLOCKPOOL_THICK

- ocs_ci/ocs/version.py
In this PR i changed the OCS version reporting in the Performance test to include build number, as implemented on other tests, to be align with the 4.9 reporting. 
> changing the reporting of OCS version in performance tests

- tests/manage/pv_services/test_rbd_thick_provisioning.py
The test case is test_rbd_thick_provisioning deprecated and will be skipped. Remove the test from acceptance run.
> Remove acceptance marker from the test test_rbd_thick_provisioning

- ocs_ci/helpers/helpers.py
- tests/e2e/performance/csi_tests/test_pvc_attachtime.py
- tests/e2e/performance/csi_tests/test_pvc_bulk_creation_deletion_performance.py
This PR runs the "test_pvc_bulk_creation_deletion_performance" test in new namespace instead of existing namespace and deletes the namespace at the end of the test.
Also deleting pvc objects solves tear down issues in "tests.e2e.performance.test_pvc_bulk_creation_deletion_performance.TestPVCCreationPerformance.test_bulk_pvc_creation_after_deletion_performance[CephFS]"
> Teardown fixes in "test_pvc_bulk_creation_deletion_performance" test case

- ocs_ci/framework/__init__.py
> Import ABC from collections.abc for Python 3.10 compatibility.

- ocs_ci/ocs/resources/mcg.py
External mode deployment failed with the error :
```
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage get backingstore noobaa-default-backing-store -n openshift-storage -o yaml.
E           Error is Error from server (NotFound): backingstores.noobaa.io "noobaa-default-backing-store" not found
ocs_ci/utility/utils.py:511: CommandFailed
```
Add a retry to check the status of mcg. 
> Retry mcg status check

- tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
This PR addresses failure reported in "https://reportportal-ocs4.apps.ocp4.prod.psi.redhat.com/ui/#ocs/launches/-1/334/11820/11870/11871/log"
Post directory changes(PR5020), script was failing as main_script path had changed in "test_pvc_multi_snapshot_performance.py"
> PR to update new main_script path in pvc multi snapshot testcase

- conf/deployment/rhv/ipi_1az_rhcos_3m_3w.yaml
- conf/deployment/rhv/ipi_1az_rhcos_lso_3m_3w.yaml
In current RHV deployment we have we have maximum 191 GB of memory.
To accommodate it for all hosts we need to lower memory.
Based on documentation in total ODF requires 72 GB in total for all
nodes.
> Set lower memory for RHV prod configs

- ocs_ci/ocs/machine.py
- ocs_ci/ocs/scale_lib.py
Increased node to be up validation timeout for scale tests
Observed Issues in vmware IPI tests for new spun node due to timeout, due to this increased the timeout.
> Increase node_up validation timeout for scale vmware tests

- tests/manage/z_cluster/test_restart_mgr_while_two_mons_down.py
https://bugzilla.redhat.com/show_bug.cgi?id=1990031
Test Procedure:
1.Scaling down two mons:
oc scale --replicas=0 deploy/rook-ceph-mon-a
oc scale --replicas=0 deploy/rook-ceph-mon-b
2.Restarting mgr
oc delete pod -l app=rook-ceph-mgr
3.sleep 5 seconds
4.Scaling mons back up
oc scale --replicas=1 deploy/rook-ceph-mon-a
oc scale --replicas=1 deploy/rook-ceph-mon-b
5.sleep 10
6.Waiting for mgr pod move to running state:
oc get pod -l app=rook-ceph-mgr
> Close loop BZ:1990031, Restart mgr pod while two mon pods are down

- ocs_ci/ocs/resources/pod.py
- tests/manage/pv_services/pvc_clone/test_encrypted_rbd_pvc_clone.py
Add fio parameters --direct=1 and end_fsync=1 in the test case test_encrypted_rbd_pvc_clone. 
This is done based on the suggestions given in https://bugzilla.redhat.com/show_bug.cgi?id=2028757 and the discussions that followed.
> test_encrypted_rbd_pvc_clone I/O enhancement

- tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
- tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
- tests/e2e/performance/io_workload/test_fio_benchmark.py
At present "test_pvc_multi_clone_performance.py" and "test_pvc_multi_snapshot_performance.py" are being modified to address tear down issues. These tests would be run manually on need basis. Also due to https://github.com/red-hat-storage/ocs-ci/issues/5099 compressed scenarios are failing in "test_fio_benchmark.py", hence adding pytest skip marker to all these tests
> Adding pytest skip markers to tests that are being modified to address tear down issues

- tests/manage/mcg/test_host_node_failure.py
We're currently seeing failures after waiting 600 seconds, but the pod seems to reach a Running state after 660~ seconds
> Extend the MCG DB node failure recovery timeout

- ocs_ci/ocs/resources/objectbucket.py
- tests/conftest.py
- tests/manage/rgw/test_host_node_failure.py
Also added general support for passing `timeout` and `interval` functions to the bucket factory.
> Fix `test_host_node_failure` to wait longer for OBC to bind after node restart

- tests/manage/mcg/test_mcg_resources_disruptions.py
We're currently seeing failures after waiting 90 seconds, but the pod seems to reach a Running state after 660~ seconds
> Extend the MCG DB deletion recovery timeout on external clusters

- tests/conftest.py
Currently, we only check for whether there are RGW deployments on the cluster. In external mode clusters, the deployments are not found on the same cluster, and thus another check for the external RGW storageclass was added, to let the tests run on external-mode clusters.
> Fix RGW tests to run on external-mode clusters

- ocs_ci/ocs/resources/cloud_uls.py
Currently, CloudManager lists all the buckets in all of the storage providers for which credentials are supplied.
This takes a lot of time, and is not needed when no underlying storage was created in particular storage providers.
> Skip the deletion flow for ULSs that were not created

- ocs_ci/ocs/ui/views.py
Added PVC key in the directory for 4.9 so that all the existing locators can be accessed by their respective tests and they do not skip or fail because of the missing key. Any locator changes can be added on per need basis if any failures are seen and analyzed with invalid locator error in the near future.
> PVC Key for Locator in 4.9

- tests/e2e/system/test_mcg_recovery.py
On this test, we created PVC for noobaa and delete its old PVC. So we see leftovers saying Resources added & Resources removed.
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-test-pr/1976/testReport/tests.e2e.system.test_mcg_recovery/TestMCGRecovery/test_mcg_db_backup_recovery_2_15_/
> Added ignore_leftovers decorator

- ocs_ci/utility/utils.py
Use Squad marks for assigning failed and skipped tests to squads, instead of assignment based only on text path.
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/5225
> Fix failed and skipped tests squad reporting

- pytest.ini
Fixing the following warning:
```
venv/lib64/python3.9/site-packages/_pytest/mark/structures.py:323
/home/ocsqe/projects/ocs-ci-deploy/venv/lib64/python3.9/site-packages/_pytest/mark/structures.py:323: PytestUnknownMarkWarning: Unknown pytest.mark.yellow_squad - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
warnings.warn(
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
> define yellow_squad marker

- tests/conftest.py
- tests/manage/mcg/test_bucket_policy.py
- tests/manage/mcg/test_mcg_resources_disruptions.py
- tests/manage/monitoring/prometheus/test_noobaa.py
With 4.10 on the horizon, we've already begun to see failures. This will prevent them from recurring.
> Replace naïve version comparisons with semantic ones in MCG tests

- ocs_ci/deployment/aws.py
Without this change, the stdout output from AWS UPI script is not printed to log if there is some failure and it makes the debugging impossible.
For example in [this job](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/8507/console) the log looks like this:
```
2021-12-16 15:04:25  14:04:24 - MainThread - ocs_ci.deployment.aws - INFO - Executing UPI install script
2021-12-16 15:04:25  14:04:24 - MainThread - ocs_ci.deployment.aws - ERROR - 
2021-12-16 15:04:25  14:04:24 - MainThread - ocs_ci.deployment.deployment - ERROR - upi install script failed
2021-12-16 15:04:25  14:04:24 - MainThread - ocs_ci.ocs.utils - INFO - Must gather image: quay.io/openshift/origin-must-gather will be used.
```
> Always log stdout from aws upi scrip even in case of failure

- ocs_ci/framework/conf/ocp_version/ocp-4.10-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.10-upgrade.yaml
Issue: Due to bug https://bugzilla.redhat.com/show_bug.cgi?id=2031049,
OCP deployment is failing on latest stable build on vSphere UPI platform
> Updating OCP installer and client version to specific version ( latest )

- ocs_ci/ocs/cluster.py
This PR Add to the ceph object the functionality of : 
- Creating new pools (RBD / CephFS)
- Deleting pools (RBD / CephFS), while insuring that the defaults polls will not be deleted (accidently)
- Changing the PG number of a pool
- Changing the target_size_ratio of a pool
All of that is for using in heavy loaded test (filling up the cluster), new pools that can be deleted in the end, 
so the actual cleanup will be very fast.
> Extend ceph object

- ocs_ci/ocs/exceptions.py
- ocs_ci/utility/tests/test_version.py
- ocs_ci/utility/utils.py
- ocs_ci/utility/version.py
- fix skipif_ocp_version and skipif_ocs_version functions
- add unittest for the compare_versions function
NOTE: it changes the behavior of `skipif_ocp_version` for multiple expressions passed, but since we use everywhere only one expression, it should be safe and it also unify it with `skipif_ocs_version`.
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/5260
> add compare_versions(expression) function

- tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
This PR is writing all he elasticsearch links (for each individual test from parametrize) to the results into single file, and then push them into the performance dashboard (only if all tests finished OK)
> Pushing PVC create and delete results into performance dashboard

- ocs_ci/helpers/helpers.py
- tests/manage/z_cluster/nodes/test_worker_nodes_network_failures.py
This PR contains following changes:
In test_worker_nodes_network_failures.py:
- Use interface value instead of scenario for parametrization
- Minor enhancements and removal of code which is not required
`scenario` parametrization is not required since now we have separate runs with tainted nodes
The test will now use interface value instead of scenario for parametrization.
Fixes: #4895 
In helpers.py:
- Add SA to an additional `anyuid` SCC to allow it's usage during pod creation when `privileged` SCC not needed. 
Fixes: #4896 
> Fix test failures in test_worker_nodes_network_failures.py 

- tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
This PR implements sending test_multiple_pvc_deletion_measurement_performance ( which measures bulk deletion time) results to the ES for later upload to the Performance Dashboard. 
> bulk_deletion_send_to_es

- conf/ocsci/aws_minimal_deployment.yaml
- conf/ocsci/vsphere_minimal_deployment.yaml
Signed-off-by: Anna Sandler <asandler@redhat.com>
minimal resources deployment by https://issues.redhat.com/browse/KNIP-1598
minimal requirements pre cluster are: 
- 24 CPU (logical)
- 72 GiB memory
- 3 storage devices
> Configuration files for minimal resources deployment

- tests/e2e/performance/csi_tests/test_pvc_bulk_creation_deletion_performance.py
This PR add support for sending test_bulk_pvc_creation_deletion_measurement_performance and test_bulk_pvc_creation_after_deletion_performance results to Performance dashboard ( each test sends to separate dashboard page). 
> sending results to perf dashboard

- tests/e2e/system/test_mcg_recovery.py
Object replication is supported from version 4.9 
#5329
> Skip the test_mcg_db_backup_recovery if the version is lower than 4.9

- ocs_ci/deployment/aws.py
- ocs_ci/deployment/install_ocp_on_rhel.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/repos/ocp_4_10.repo
- ocs_ci/repos/ocp_4_2.repo
- ocs_ci/repos/ocp_4_3.repo
- ocs_ci/repos/ocp_4_4.repo
- ocs_ci/repos/ocp_4_5.repo
- ocs_ci/repos/ocp_4_6.repo
- ocs_ci/repos/ocp_4_7.repo
- ocs_ci/repos/ocp_4_8.repo
- ocs_ci/repos/ocp_4_9.repo
- ocs_ci/utility/mirror_openshift.py
Since the recent changes in authentication method for `mirror.openshift.com/enterprise`, we have to replace the original authentication via certificate by newly used basic auth.
> Use Basic auth for accessing OCP repos

- ocs_ci/ocs/acm/acm_constants.py
Fixing type in acm namespace constant
> fix typo of acm namespace

- setup.py
There is a requirement to be able to run the same test or set of tests multiple times (see issue https://github.com/red-hat-storage/ocs-ci/issues/5009). It seems, that [`pytest-repeat`](https://pypi.org/project/pytest-repeat/) module allows exactly that - via new argument `--count`.
> Add pytest-repeat module

- ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
- ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
- ocs_ci/templates/ocp-deployment/install-config-azure-ipi.yaml.j2
- ocs_ci/templates/ocp-deployment/install-config-gcp-ipi.yaml.j2
- ocs_ci/templates/ocp-deployment/install-config-vsphere-ipi.yaml.j2
Update OCP deployment templates to be able to use different pod network when `conf/ocsci/enable_diff_pod_nw.yaml` conf file is specified.
Few templates already have the required format, this PR is for updating the remaining templates.
> Update OCP deployment templates to be able to use different pod network

- conf/README.md
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/ocs_upgrade.py
- introduce new configuration parameter `DEPLOYMENT["disconnected_env_skip_image_mirroring"]` which allows skipping of preparation for disconnected deployment (index image pruning, mirroring images, catalog source creation,...)
- this will be useful, when the required images are mirrored and the environment is prepared outside of ocs-ci 
> Add possibility to skip index image prune and images mirroring on disconnected environment

- ocs_ci/ocs/bucket_utils.py
- tests/manage/mcg/test_mcg_resources_disruptions.py
after a discussion with dev team we understood that the user used by the db is now the same across previous versions (backported) so the check for version is no longer needed 
Signed-off-by: Amit Berner <aberner@redhat.com>
> Return to const usage for noobaa scc test

- ocs_ci/ocs/amq.py
- ocs_ci/templates/workloads/amq/kafkadrop.yaml
Fixes: #5374
Checks if fips enabled on the cluster and skip it
Kafkdrop pod replaced with `quay.io` images now since it used to fail intermittently before
> Skip amq tests on fips enabled cluster

- tests/e2e/performance/io_workload/test_fio_benchmark.py
Server pod count is reduced from 51 to 9 to achieve high iops in fio tests. As per comments on bug-2015520, multiple tests were run with different pod count and iodepths were run and pod count = 9 and iodepth = 16 was chosen.
> Update fio server pod count in test_fio_benchmark.py

- ocs_ci/utility/load_balancer.py
This should fix #4209 by adding the appropriate port for HTTPS endpoints.
However, I believe we should rewrite this part in a more Pythonic way, that replaces sed with more readable tools
> Use the correct port when adding nodes to the HAProxy config

- ocs_ci/deployment/disconnected.py
Fixing [OCSQE-691](https://issues.redhat.com/browse/OCSQE-691) - update imageContentSourcePolicy name (make it unique).   
> Disconnected upgrade: make imageContentSourcePolicy name unique

- tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Moving the test case ```TestSnapshotAtDifferentPvcUsageLevel.test_snapshot_at_different_usage_level```  from tier1 to tier2 as it's not about basic product functionality.
Partial fix for #5283
> Change test_snapshot_at_different_usage_level to tier2

- ocs_ci/framework/pytest_customization/ocscilib.py
The `return` statement was replaced by `continue` otherwise the configuration for second and following clusters was skipped.
Also switch back to the configuration context of the first cluster at the end of `pytest_configure()` function.
> fix config initialization for multicluster

- ocs_ci/framework/pytest_customization/ocscilib.py
switch to proper default cluster context after config initialization
> switch to default cluster ctx after config inititalization

- ocs_ci/framework/__init__.py
If some of the configuration file passed `--ocsci-conf` parameter is empty, it fails the whole `run-ci` execution with following traceback:
```
$ run-ci --color=yes tests/ecosystem/ -m deployment  --collect-only --ocsci-conf /tmp/test.yaml 
Traceback (most recent call last):
File "/home/dahorak/RedHat/OCS/ocs-ci/venv/bin/run-ci", line 33, in <module>
sys.exit(load_entry_point('ocs-ci', 'console_scripts', 'run-ci')())
File "/home/dahorak/RedHat/OCS/ocs-ci/ocs_ci/framework/main.py", line 265, in main
init_ocsci_conf(arguments)
File "/home/dahorak/RedHat/OCS/ocs-ci/ocs_ci/framework/main.py", line 90, in init_ocsci_conf
process_ocsci_conf(arguments)
File "/home/dahorak/RedHat/OCS/ocs-ci/ocs_ci/framework/main.py", line 130, in process_ocsci_conf
load_config(args.ocsci_conf)
File …
```
> Do not fail when configuration file is emtpy

- ocs_ci/ocs/must_gather/const_must_gather.py
- ocs_ci/ocs/node.py
- tests/conftest.py
- tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
- tests/manage/pv_services/test_raw_block_pv.py
Replacing openshiftdedicated platform specific test conditions as
MANAGED_SERVICE_PLATFORMS to accomodate the change for rosa along with OSD platform
> Update openshiftdedicated conditions as MANAGED_SERVICE_PLATFORMS

- tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
- tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py
- tests/manage/pv_services/test_pvc_disruptive.py
- tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
There are some tier4 tests  in /manage/pv_services which are redundant since the test scenarios are covered in other tests.
These redundant tests are disabled in this PR.
1. tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py  covered in the test  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
2. tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py covered in the test  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py
3. tests/manage/pv_services/test_pvc_disruptive.py covered in the test  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
4.  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py covered in the test …
> Disable the redundant tier4 pv_services tests

- tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
Use the default storage class in the test test_change_reclaim_policy_of_pv if the reclaim policy is "Delete". New storage class should be created only if the reclaim policy is "Retain". This will help running the tests which require the reclaim policy "Delete" on the platforms where the creation of new storage class is not supported/recommended. 
> Use default storage class in test test_change_reclaim_policy_of_pv if the reclaim policy is Delete

- tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py
Fix storage_type parameter in the test test_ceph_daemon_kill_during_pod_pvc_deletion.
Fixes #4907
> Fix storage_type parameter in the test test_ceph_daemon_kill_during_pod_pvc_deletion

- ocs_ci/ocs/registry.py
- tests/e2e/workloads/ocp/registry/test_registry_by_increasing_num_of_image_registry_pods.py
- tests/e2e/workloads/ocp/registry/test_registry_pod_respin.py
- tests/e2e/workloads/ocp/registry/test_registry_pull_and_push_images_to_registry.py
- tests/e2e/workloads/ocp/registry/test_registry_reboot_node.py
- tests/e2e/workloads/ocp/registry/test_registry_shutdown_and_recovery_node.py
Fixes: #5405
Template `eap-cd-basic-s2i` is been removed from openshift samples as a quick fix passing build name when creating images so that template `redis-ephemeral` will be used default and will create a build
> Pass build name when creating images

- tests/manage/pv_services/pvc_clone/test_encrypted_rbd_pvc_clone.py
- tests/manage/pv_services/pvc_snapshot/test_encrypted_rbd_pvc_snapshot.py
- tests/manage/pv_services/pvc_snapshot/test_verify_rbd_trash_purge.py
- tests/manage/pv_services/test_rbd_pv_encryption.py
Skip the pv_services tests which create new storage class on manages services platform.
> Skip the tests which create new storage class on MS

- ocs_ci/utility/rosa.py
Rosa deployment was restricted to single availability zone deployment
This will resolve https://github.com/red-hat-storage/ocs-ci/issues/5468
> Allow availability zone as configurable parameters for Rosa deployment

- ocs_ci/ocs/version.py
- tests/conftest.py
- tests/manage/monitoring/prometheusmetrics/test_mcg_hpa.py
Update  `test_mcg_hpa` to use either horizontal-pod-autoscaler-v1 API (when OCP version < 4.10) or  horizontal-pod-autoscaler-v2 API otherwise.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/5361 again (it turned out we still don't use the stable version branches in production CI jobs).
> test_mcg_hpa uses both 

- ocs_ci/templates/workloads/fio/benchmark_fio_cmp.yaml
currently all FIO test on compressed volume with 16 KiB block size are not completed on time.
This PR is increasing the time of the test, so it will finishe.
> changing compressed FIO test timeout

- docs/usage.md
Tweaking 1st deployment example to list one option per line and stress the need for listing `tests` directory as a test path.
> docs: stress the need for listing `tests` testpath

- tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
The test case is skipped in Managed services platform because the test case creates new CephBlockPool. 
> Skip the test case test_rbd_space_reclaim in MS

- ocs_ci/ocs/perftests.py
when pushing data to the dashboard the test if the test ran on compressed volume is irrelevant, since this test is running after actual tests was ran and the volumes (compressed) was deleted already.
> Performance Dashboard - remove the check if cluster is compressed

- tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Replace existing version comparison with semantic ones in test_rwo_pvc_fencing_unfencing.py
> Use semantic version for version comparison in test_rwo_pvc_fencing_unfencing.py

- conf/ocsci/import_clusters_to_acm.yaml
- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/acm/acm.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/views.py
- tests/ecosystem/deployment/test_acm.py
Signed-off-by: Cem Erginbas <cerginba@cerginba.tlv.csb>
Changes that are required for the importing scenario.
Some of the changes:
- Added a new mark of `acm_import` as it will be a good solution for skipping pytest auto-use calls when entering run-ci
- Added a new config file `conf/ocsci/import_clusters_to_acm.yaml` that skips ocs deployment and configures import_clusters_to_acm=True
- Bug fixes in `ocsci/ocs/acm/acm.py` file that were required for the execution of the UI automation successfully to import the clusters
- in `ocs_ci/ocs/ui/base_ui.py`  added chrome option of: `--disable-dev-shm-usage` when we pass the import_clusters_to_acm configuration. In such a scenario, the kubeconfig needs to be copied and sent as a text via UI automation. Since kubeconfig is a large file, Selenium …
> Import Clusters to ACM Hub including a separated test mark

- ocs_ci/ocs/ui/base_ui.py
Signed-off-by: Cem Erginbas <cerginba@cerginba.tlv.csb>
Motivation:
For future upcoming UI tests, it is beneficial to have auto completions on your IDEs. The child classes are not aware that `self.driver` is actually a WebDriver object.
By using this type-hint, we will see all the available methods no matter which classes you work on that inherits `BaseUI`
Please see the difference in those examples:
Example without the `WebDriver` type hint:
Example with the `WebDriver` type hint:
> Add WebDriver Data type hint in UI Base Class

- ocs_ci/templates/app-pods/performance.yaml
- tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py
- tests/e2e/performance/csi_tests/test_pod_reattachtime.py
The default image pull policy is : Always
Which mean that in the pod attach / reattach we are measuring the pull image time in the total attach time.
This PR change the default image pull policy to : IfNotPresent
So, the image pull time will no calculate in the attach time, since we are pulling it separately in the beginning of the test and not as part as the pod creation process.
This PR also remove some code duplication from the pod_reattach test.
the Pulling image is also implements in the bulk_pod_attach test
some duplicated code remove from the bulk_pod_attach test.
> Change the default imagepullpolicy for performance test

- tests/manage/monitoring/prometheus/test_rgw.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/5398
> Increase time in test_rgw_unavailable to wait for clearing alert

- tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
This PR increases number of sampled clones from 1 to 10. 
The current code also calculates averages of all the measurements and pushed them to the ES. 
> Changing samples number from 1 to 10

- conf/ocsci/vsphere_ipi.yaml
- conf/ocsci/vsphere_upi.yaml
In order to utilize vsphere_upi.yaml and vsphere_ipi.yaml more in day to day testing, I am proposing to increase the worker nodes mem from 32 to 36 GB and reduce the master nodes mem from 16 to 12 GB
> vSphere IPI/UPI specs conf: Reduce master and increase worker memory

- ocs_ci/ocs/perfresult.py
This PR dump the performance results into a JSON file (in the test directory) in anycase.
before, the results was dumps only if it couldn't push them into ElasticSearch server,
and it will dump them to a file even if them pushed into the ElasticSearch.
> dump performance results to a JSON file in any case (ES exists or not)

- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/ocs/defaults.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/ocs_upgrade.py
supports ODF upgrade external cluster dynamically
This PR supports below upgrade scenarios which was missed few steps in previous releases.
Apart from that, In this PR we are creating object store user dynamically if it doesn't exists.
1. upgrade from 4.8 to 4.9
2. upgrade from 4.7 to 4.8
3. upgrade from 4.6 to 4.7
4. upgrade from 4.5 to 4.6
> Upgrade external cluster

- ocs_ci/ocs/perfresult.py
In some cases (espachialy with FIO and SmallFiles), the link to the elasticsearch results pull more the the expected results.
quoting the UUID in the link is solving this issue.
> Fix the ElasticSearch link

- ocs_ci/utility/managedservice.py
This will be used for Managed Service (ODF to ODF deployment).
The `remove_header_footer_from_key()` function can be used like this:
```python
private_key = config.AUTH["managed_service]["private_key"]
private_key_without_header_footer = remove_header_footer_from_key(private_key)
```
> add function for generating onboarding token

- tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
- tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
- tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
- tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py
- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Skip the tests in tests/pv_services which need to access provider and consumer at the same time.
New MS specific test cases will be created for the relevant scenarios skipped in these tests.
> Skip tests on MS platform

- ocs_ci/ocs/constants.py
This just had to be addressed some time as a fix from adding multiple variables with the same value for no reason.
Addressed the following:
- Line 161 was emoved, since 133 has the value of CLUSTER_SERVICE_VERSION = "csv"
- Line 117 was removed since 134 has the value of 
JOB = "Job" (Line 134 overrides "job", so left the one with the lowercase)
- Line 93 was removed since 88 has the value of STATUS_CLBO = "CrashLoopBackOff"
@clacroix12 @petr-balogh This might be too much to handle in our tox.ini, but I believe there must be a way to provide a pre-commit hook that might take a look into values that are used on the fly, while they exist in our `ocs_ci/ocs/constants.py` file.
> Remove duplicated constants

- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/defaults.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/templates/CSI/rbd/csi-kms-connection-details-hpcs.yaml
- ocs_ci/templates/openshift-infra/hpcs/ibm-kp-kms-secret.yaml
- ocs_ci/templates/openshift-infra/hpcs/ocs-kms-connection-details.yaml
- ocs_ci/utility/kms.py
- tests/conftest.py
- tests/manage/pv_services/pvc_clone/test_encrypted_rbd_pvc_clone.py
- tests/manage/pv_services/pvc_snapshot/test_encrypted_rbd_pvc_snapshot.py
- tests/manage/pv_services/test_rbd_pv_encryption.py
This PR includes the below changes:
- Extend `encrypted RBD PV creation and deletion` test case to include IBM's HPCS as KMS option.
**Jenkins Job link** - https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/10655/
**Jenkins Job link for Vault** - https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/10841/
- Extend `encrypted RBD PVC to PVC clone` test case to include IBM's HPCS as KMS option.
**Jenkins Job link** - https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/10638/
**Jenkins Job link for Vault** - https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/10859/
- Extend `encrypted RBD PVC snapshot` test case to include IBM's HPCS as KMS …
> Extend encrypted rbd pv/pvc test cases to include IBM HPCS as KMS option

- ocs_ci/ocs/defaults.py
- ocs_ci/templates/CSI/rbd/csi-kms-connection-details.yaml
- tests/conftest.py
- tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_clone.py
- tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
- tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption.py
- tests/manage/pv_services/pvc_clone/test_encrypted_rbd_pvc_clone.py
This PR contains fixes for the following:
- fixes #5607 
- Move PV encryption tests to anew folder for better management
- Add Key deletion check for kv-v2
> Update PV encryption test cases

- ocs_ci/helpers/helpers.py
- ocs_ci/helpers/performance_lib.py
- ocs_ci/ocs/perfresult.py
- ocs_ci/ocs/perftests.py
- tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
This PR improve the TC runtime and the memory consumption during the test.
The Original TC ran for 5 Hours and 45 Min with memory consumption of up to 2.2 GiB of memory, while after this PR
the TC will run for only 1 Hour and 15 Min, with memory consumption of up to 380 MiB only.
as can be seen in this graph: <img width="1061" alt="Screen Shot 2022-03-27 at 11 35 22" src="https://user-images.githubusercontent.com/54134264/160273649-b7fbfcf8-9eff-4792-8ade-ce274571f720.png">
This PR also:
* reduce duplicated code
* improvement of the ES report
* fix issue with the ES report, said it written even if not
> pvc_create_delete refactoring

- tests/conftest.py
Patch the rook-ceph-tools deployment with ceph.admin key. Applicable for MS platform only to enable rook-ceph-tools to run ceph commands until we have the proper for rook-ceph-tools in consumer cluster.
Added a session scope fixture to perform this at the beginning of the test.
> Patch rook-ceph-tools deployment in consumer cluster

- ocs_ci/ocs/resources/storage_cluster.py
made changes to skip ocs 4.8 as https://bugzilla.redhat.com/show_bug.cgi?id=2069722
> check luks header info for encrypted devices

- tests/conftest.py
The fixture patch_consumer_toolbox_with_secret is updated to:
*  patch the rook-ceph-tools deployment only if the ceph command is failing due to an expected error.
*  wait for the existing  rook-ceph-tools pod to delete.
*  wait for the new rook-ceph-tools pod to reach the state 'Running'
> Update fixture patch_consumer_toolbox_with_secret

- tests/manage/storageclass/test_verify_all_fields_in_sc_yaml_with_oc_describe_sc.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
- tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
- tests/manage/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py
- tests/manage/z_cluster/test_ceph_default_values_check.py
Skip the test cases on Managed Services platform.
1. tests.manage.z_cluster.test_ceph_default_values_check.TestCephDefaultValuesCheck.test_noobaa_postgres_cm_post_ocs_upgrade
2. tests.manage.z_cluster.cluster_expansion.test_verify_ceph_csidriver_runs_on_non_ocs_nodes.TestCheckTolerationForCephCsiDriverDs.test_ceph_csidriver_runs_on_non_ocs_nodes
3. tests.manage.z_cluster.cluster_expansion.test_node_expansion.TestAddNode.test_add_ocs_node
> Skip test cases on MS

- ocs_ci/ocs/ocs_upgrade.py
For ODF 4.10, we need to get json output from exporter script and update
those details in cluster after upgrade is completed
> [external cluster]: update json output after upgrade

- ocs_ci/utility/rosa.py
Usually after 2hours add-on moved to failed status
Also sometime 1 hour is not sufficient for add-on install
hence incresing the add-on install timout to 2 hours
> update time out of add-on install check

- tests/managed-service/test_post_installation_state.py
Add bugzilla marker in the test case tests/managed-service/test_post_installation_state.py::TestPostInstallationState::test_connection_time_out
> Add bugzilla marker in test test_connection_time_out

- ocs_ci/ocs/must_gather/const_must_gather.py
- ocs_ci/ocs/must_gather/must_gather.py
Excluded the files which are not relevant for managed services from the list of files to verify in must-gather.
With this change, the test case given below will be able to run on MS platform.
_tests/manage/z_cluster/test_must_gather.py::TestMustGather::test_must_gather[OTHERS]_
> Update test_must_gather to run on MS

- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/pullsecret_for_non_ga.yaml
The pullsecrete_workaround only if execution is
on non-gaed version so instead of modifying
configs after and before release.Hence seperating
this configuration from other generic configs
> rephrase pullsecret_workaround parameter

- tests/e2e/workloads/test_data_consistency.py
> Use external mode sc in test_log_reader_writer_parallel when executed on external mode clusters

- ocs_ci/ocs/defaults.py
- ocs_ci/ocs/resources/storage_cluster.py
Adding verification of csi users "client.csi-cephfs-node", "client.csi-cephfs-provisioner",
"client.csi-rbd-node" and "client.csi-rbd-provisioner" and caps.
From ODF 4.10, osd blocklist caps are added to csi users
> verify csi users and caps in external mode

- tox.ini
This will prevent tox to install ocs-ci (including dependencies) or
create sdist tarball for testenv:logging, which just performs a source
code check, which doesn't require any of this. This should save us some
small but noticeable time required to run unit tests.
> tox: avoid install or sdist setup for logging env

- ocs_ci/ocs/fiojob.py
- ocs_ci/ocs/tests/test_fiojob.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/1056 issue for fiojob.py module, removes hardcoded storage class names.
> external storage class names in fiojob

- tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
The current PR adds a test : creation of number of samples of Clones for a PVC with multiple files ( ~1 million files). 
The test creates clones for such PVC, calculates creation and deletion times of the samples , also CSI creation and deletion times, and creation /deletion/csi creation/csi deletion averages.
The test sends the results to the ES server and uploads those results to the Performance Dashboard.
> Ypersky clone with multiple files

- tests/manage/z_cluster/test_must_gather.py
Add skipif_ms_consumer marker in the test /home/jijoy/ocs-ci/tests/manage/z_cluster/test_must_gather.py for MS platform.
> Add marker in test based on MS cluster type

- tests/conftest.py
The fixture _patch_consumer_toolbox_with_secret_ is currently failing if the provider cluster is not present. Made changes to continue the tests if provider cluster is not present assuming that the toolbox on consumers are already fixed before the start  of the test. 
> Do do fail the run if provider is not found

- ocs_ci/helpers/disruption_helpers.py
- ocs_ci/ocs/ocp.py
- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Update the test case given below to run on Managed Services platform. Switching between provider and consumer cluster is added because ceph pods will be present in the provider cluster only.
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py::TestResourceDeletionDuringCreationOperations::test_resource_deletion_during_pvc_pod_creation_and_io
> Test case adjustment to run on MS

- ocs_ci/deployment/aws.py
Pass list of nodes to drain_nodes function.
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/5760
> fix remove_rhcos_workers function

- ocs_ci/deployment/aws.py
configure required INSTALLER_BIN variable
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/5749
> fix aws upi deployment

- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
The marker 'skipif_ms_consumer' is not appropriate for the test test_resource_deletion_during_pvc_pod_creation_and_io. Changing it to 'skipif_ms_provider'.
> Fix marker in test_resource_deletion_during_pvc_pod_creation_and_io

- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Update the test case given below to run on Managed Services platform. Switching between provider and consumer cluster is added because ceph pods will be present in the provider cluster only.
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py::TestResourceDeletionDuringMultipleDeleteOperations::test_disruptive_during_pod_pvc_deletion_and_io
> Modify test_disruptive_during_pod_pvc_deletion_and_io to run on MS

- ocs_ci/deployment/rosa.py
- ocs_ci/ocs/managedservice.py
Patch rook-ceph-tools deployment on consumer to run ceph commands. The patch is done after deployment.
> Patch rook-ceph-tools deployment on consumer

- ocs_ci/framework/conf/default_config.yaml
Now in managed service provider add-on of stagging and production
the only available storage cluster size is 20 TiB .
> Update default size to 20 Tib

- tests/e2e/performance/csi_tests/test_pod_reattachtime.py
This small PR handles the following: 
- increasing number of files in the reattache pod
- replacing usage of teardown factory by deleting the pod. 
> increasing num of files in the pod and getting rid of teardown factory

- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
When running MultiCluster job with consumer as the primary cluster and provider as the secondary cluster, the test cases in _tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py_ and _tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py_ are skipped due to the reason 
```
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py::TestResourceDeletionDuringMultipleDeleteOperations::test_disruptive_during_pod_pvc_deletion_and_io[CephBlockPool-mgr]
Reason: Test will not run on Managed service provider cluster
```
This is due to the presence of the marker _skipif_ms_provider_ which should skip these tests only when the cluster context is provider. But the test cases are skipped when the cluster context is …
> Remove skipif_ms_provider from tests

- conf/ocsci/vault_external_standalone_kube_auth_path_v1.yaml
- conf/ocsci/vault_external_standalone_kube_auth_path_v2.yaml
- conf/ocsci/vault_external_standalone_kube_auth_v2.yaml
- ocs_ci/templates/openshift-infra/vault/ocs-kms-connection-details.yaml
- ocs_ci/utility/kms.py
This PR will enable deployment of clusterwide encryption enabled clusters with kubernetes authentication method which uses custom authentication path in Vault
> Add test case for Clusterwide encryption with auth path

- conf/README.md
- conf/ocsci/ms_production_env.yaml
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/utility/openshift_dedicated.py
By default deployment environment consider for managed service is
staging environment. As this is most used environment for deployment and testing
This PR enable deployment in production environment
> Enabling deployment on production environment

- ocs_ci/deployment/deployment.py
skip mcg-operator check for ODF 4.9 with live deployment 
due to bug https://bugzilla.redhat.com/show_bug.cgi?id=2075422
> skip mcg-operator check for ODF 4.9 with live deployment 

- ocs_ci/deployment/deployment.py
As ODF 4.9 is GA'ed, we don't need to decide whether to check mcg-operator or
noobaa-operator based on build number. From ODF 4.9, its mcg-operator
> remove getting internal build number during deployment

- ocs_ci/ocs/cluster.py
There shouldn't be no extra ceph pods on Managed Service Consumer cluster.
Without this change, the Consumer cluster deployment is failing during post deployment checks on this issue https://github.com/red-hat-storage/ocs-ci/issues/5827.
> fix cluster health check for MS Consumer cluster

- tests/conftest.py
- tests/manage/mcg/test_nsfs.py
- Skip NSFS tests below OCS 4.10
- Extend wait for MCG account to be fully ready
- Avoid duplicate account names by adding a random int component to the name
- Add timeout sample for checking the health of exported NSFS buckets after creation
> Fix various NSFS test issues

- tests/e2e/workloads/test_data_consistency.py
Update the test case test_log_reader_writer_parallel to select the correct storage class name in MS platform.
> Modify test test_log_reader_writer_parallel to run on MS

- tests/manage/z_cluster/cluster_expansion/test_delete_pod.py
Skip the test given below if the platform is Managed Services.
tests/manage/z_cluster/cluster_expansion/test_delete_pod.py::TestAddCapacityWithResourceDelete::test_add_capacity_with_resource_delete
> Skip the test test_add_capacity_with_resource_delete on MS

- tests/manage/monitoring/pagerduty/test_deployment_status.py
The test cases given below will require provider cluster to run. Adding the marker runs_on_provider to switch the context to provider cluster if the provider cluster is available in a multicluster run.
tests/manage/monitoring/pagerduty/test_deployment_status.py::test_ceph_osd_stopped_pd
tests/manage/monitoring/pagerduty/test_deployment_status.py::test_ceph_monitor_stopped_pd
tests/manage/monitoring/pagerduty/test_deployment_status.py::test_ceph_mons_quorum_lost_pd[True]
tests/manage/monitoring/pagerduty/test_deployment_status.py::test_ceph_manager_stopped_pd
> Run tier4c pagerduty tests on provider

- tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
Modify the test _test_del_mon_service_and_create_pvc_ to run on Managed Services platform. Switching between provider and consumer cluster context is needed in different steps.
> Modify test_del_mon_service_and_create_pvc to run on MS

- ocs_ci/utility/utils.py
Fixes the DeprecationWarning: The 'text' argument to find()-type methods
is deprecated. Use 'string' instead.
Fixes: #5871 
> use string instead text in soup object

- tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
Move platform check to setup function in test to avoid collection error.
Updated tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
Fixes #5888 
> Move platform check to setup function in test to avoid collection error

- ocs_ci/ocs/hsbench.py
- tests/e2e/scale/noobaa/test_hsbench.py
Increase timeout for bucket health check.
Fixed ResourceLeftoversException issue: [PR#5604](https://github.com/red-hat-storage/ocs-ci/issues/5604)
> test_s3_benchmark_object_bucket: Increase timeout for bucket health check.

- ocs_ci/helpers/helpers.py
- ocs_ci/helpers/performance_lib.py
- tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
The current PR handles the following: 
1) fixes calculation of the total creation time ( different logs are parsed and the calculation is done differently) 
The existing def get_snapshot_time(interface, snap_name, status): was deleted, since the implementation was wrong, and it measuring wrong Total snapshot creation time. 
2) CSI snapshot creation times was added
> Total creation time fix and csi time added

- setup.py
Blowfish is deprecated in cryptography 37.0.0 which was used by paramiko
Fixes: #5902 
> pin cryptography to 36.0.2

- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/platform_nodes.py
In some cases where node takes more time ( > 30 sec ) to come online after reboot, events are
not captured within 30 sec
Fixes: #5882 
> Use timeoutsampler for getting reboot events for node

- ocs_ci/helpers/disruption_helpers.py
- tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
Modify the test case given below to run on Managed Services platform.
tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py::TestResourceDeletionDuringPvcClone::test_resource_deletion_during_pvc_clone
> Modify test test_resource_deletion_during_pvc_clone for MS

- ocs_ci/helpers/helpers.py
The issues #5310 and #5707 are observed in production runs only. The cause of both the issues looks the same. The used size of the pool is not getting updated within the given timeout. Many attempts was done to reproduce these issues locally and using jenkins by running these tests along with some other tests. The issue was not observed in these runs. As a workaround for the issue, the wait time to reflect the correct size of the pool is increased in this PR. This can be considered as a fix if the issue is not reproducible with this code change. 
> Increase wait time of fetch_used_size to workaround 5310 and 5707

- ocs_ci/templates/workloads/jenkins/buildconfig.yaml
```
$ oc -n myjenkins-1 create -f /tmp/BuildConfiglmw_dp44 -o yaml
W0516 17:38:29.390717   12720 shim_kubectl.go:58] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "build.openshift.io/v1" for your resource
```
> fix buildconfig file on jenkins workload

- ocs_ci/ocs/constants.py
Since all are hosts in vSphere are using NTP server as clock1.rdu2.redhat.com,
changing in ocs-ci as well to maintain consistency
> Update NTP server

- ocs_ci/utility/flexy.py
Those changes are related to the recent [changes in flexy-templates for OCP 4.11](https://gitlab.cee.redhat.com/aosqe/flexy-templates/-/merge_requests/1188/diffs).
> Disconnected cluster: update used int-svc user for ocp 4.11

- ocs_ci/ocs/resources/storage_cluster.py
[BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2069722) was raised for the luks header info issue with OCS 4.8. Now its fixed and verified in 4.8.11. Hence removing the condition to skip 4.8 version under osd encryption verification module.
> Including version 4.8 after fix for luks header info issue in 4.8.11

- tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
This PR handles the following: 
1) Adds calculation and reporting ( including uploading to the ES) of CSI measurements for multiple snapshot creation.
2) Changes calculation of Total multiple snapshot creation time ( so that the same method as in the single snapshot test will be used)
3) Removes redundant parts of the code 
4) Fixes teardown problem - no need to try to delete instances ( pvc object ) after Results test . 
>  ypersly - multi snapshot csi times

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/perftests.py
- tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
This PR refractor the test for pvc_clones to reduce the memory consumption.
The original test consume more then 2GiB of memory, which cause the test to failed  , and now the test consume **only** ~400MiB
> refactoring pvc_clones test

- tests/ecosystem/deployment/test_deployment.py
There are case where ceph health check failed during teardown but its recovered after some
retries. To avoid deployment failures, we need to have health check at the end of
deployment test case
Fixes: #5921 
> ceph health check at the end of deploymnet TC

- ocs_ci/ocs/cephfs_workload.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/resources/pod.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
The tests are only for the managed service platform when using provider and consumer.
We test 3 node scenarios on the provider cluster while on the consumer cluster - writing and reading logfile stored on cephfs volume, from all worker nodes of a cluster via k8s Deployment.
The 3 node scenarios are:
- Automated recovery from stopped worker node
- Automated recovery from termination of a worker node
- Automated recovery from unscheduled and rescheduled a worker node.
If we dive into more details, the flow is:
1. writing and reading logfile stored on cephfs volume, from all worker nodes of a cluster via k8s Deployment on the consumer cluster.
2. Start one of the node scenario tests described above on the provider.
3. Check that the OCS pods are running and the worker node's security groups …
> Run the node managed service tests with cephfs workload

- ocs_ci/utility/rosa.py
The consumer size is fixed to 1PB non-mutable in v2.0.2
rosa CLI and UI change by d, below reference PR
https://gitlab.cee.redhat.com/service/managed-tenants/-/merge_requests/2393
This PR is adjust this change in deployment ci automation
> Omit use of size and unit parameter from consumer deployment

- tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
The test case is skipped on External mode cluster because the test case creates new CephBlockPool.
Fixes: #5712 
> Skip the testcase test_rbd_space_reclaim on External mode cluster

- ocs_ci/ocs/pillowfight.py
- tests/conftest.py
- tests/e2e/workloads/app/couchbase/test_couchbase_node_reboot.py
1. Added 10 second wait after the couch base bucket creation, so that newly created bucket will reconcile with the existing couch base cluster
2. Increased timeout used for pillowfight benchmarking. This is used to wait until all three Job completes benchmarking.  
> Increasing timeouts to avoid couchbase failures

- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/ui/base_ui.py
allow configuration of ENV_DATA["client_http_proxy"] for pirvate link cluster
> allow usage of client proxy on private link cluster

- tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
> Skip PV encryption using vaulttenantsa on disconnected and proxy clusters

- docs/usage.md
There are issue like 2 factor authentication and too many current logins if we
use username and password for authentication. To avoid such problems, we
need API key for bugzilla authentication.
> doc update: use bugzilla_api_key for bugzilla authentication

- ocs_ci/framework/main.py
- ocs_ci/utility/proxy.py
- tests/conftest.py
set `http_proxy` and `https_proxy` env variables, if client http proxy is required and configured
> use client http proxy if configured

- ocs_ci/helpers/performance_lib.py
- tests/e2e/performance/csi_tests/test_pod_attachtime.py
This PR contains the following enhancements: 
1) Renaming the test so that similarly to bulk pod attach and pod reattach test this test will be called "pod attach" and not "pvc attach" test
2) Adding CSI measurements for pod attach action and reporting those measurements to the ES. 
> adding csi times and renaming the test

- ocs_ci/deployment/disconnected.py
- ocs_ci/helpers/disconnected.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/ocp-deployment/oc-mirror-imageset-config.yaml
Command `opm index prune ...` doesn't work for index image for ocp 4.11 and higher, so the approach have to be replaced by `oc-mirror` tool.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/5932
> use oc-mirror command for mirroring images

- ocs_ci/ocs/bucket_utils.py
- ocs_ci/ocs/resources/mcg.py
- ocs_ci/ocs/resources/namespacestore.py
- Support CLI creation of stores that use existing secrets by utilizing `yes`
- Add missing `.spec.storeType.secret.namespace` field
> 4.11 MCG fixes

- ocs_ci/utility/prometheus.py
Let's not pollute our logs when prometheus queries are run in bulk.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/6003
> drop unnecessary log info call

- ocs_ci/deployment/azure.py
- ocs_ci/ocs/ui/base_ui.py
From OCP 4.11 versions, default storageclass for Azure platform is managed-csi
> Change default SC in Azure platform

- ocs_ci/framework/__init__.py
- ocs_ci/framework/logger_factory.py
It feels more comfortable looking in the logs by the cluster name rather than the index number, as the number of clusters grows in Managed Services + DR setups, it might be a better idea to simply print the cluster name itself.
Addressed the following in the PR:
- Replaced a debug log in `_refresh_ctx()` with info log inside `switch_context` function. Prints out to what cluster name is changed
- New method in the `MultiClusterConfig` class that retrieves the cluster name from `ENV_DATA` section
- Replaced the call to `cur_index` attribute in the logger prefix, with the cluster name
> Enhance logger for multi cluster + adding cluster name in prefix

- ocs_ci/ocs/resources/storage_cluster.py
Skip storage system validation for upgrade cluster with OCP 4.10 + upgrade OCS version 4.10
Fixes: #6021 
W/A issue: #5995 
> Skip storage system validation for upgrade cluster with OCP 4.10 + upgrade OCS version 4.10

- tests/manage/mcg/test_multi_region.py
**Fix:**
Added retry() to the sync_object_directory() in the
test_multiregion_mirror, as the tests might fail mnay times due to some
race condtions. This will help avoid that issue.
Fixes: #5969
Signed-off-by: nik-redhat <nladha@redhat.com>
> Fix: Added retry for sync_object_directory() in test_multiregion_mirror

- ocs_ci/deployment/disconnected.py
The mirror registry used for disconnected deployment doesn't support
some operations required by oc-mirror command. When ignoring the images
mirrored during deployment, the additional features are not required.
fixes: https://github.com/red-hat-storage/ocs-ci/issues/6028
> fix image mirroring for upgrade on OCP 4.11

- ocs_ci/ocs/resources/pvc.py
Change snapshot apiversion if OCP version is 4.11 or higher.
Fixes #6048
> Change snapshot apiversion based on OCP version

- tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Taint-related tests can be skipped in MS as we do not taint in provider - not possible due to no access and provider resources are anyways separated from workloads running on consumer
> Skip the test 'test_non_ocs_taint_and_toleration' when using MS

- ocs_ci/helpers/disruption_helpers.py
- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/managedservice.py
- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/resources/ocs.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/resources/pvc.py
- tests/conftest.py
- tests/managed-service/test_pod_disruptions.py
RHSTOR-3176 - Managed Service specific pod disruption test
I/O will be running on all consumers when performing pod deletion.
Provider pods to delete:
ocs-osd-controller-manager
alertmanager-managed-ocs-alertmanager
ocs-provider-server
prometheus-operator
prometheus-managed-ocs-prometheus
ocs-operator
Consumer pods to delete:
alertmanager-managed-ocs-alertmanager
ocs-osd-controller-manager
prometheus-managed-ocs-prometheus
prometheus-operator
ocs-operator
> Managed Service pod disruption test

- tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
The test 'test_rwo_pvc_fencing_unfencing' when using ms is not applicable for now; already been tested on the product; network failure on AWS is not a priority for testing.
> Skip the test 'test_rwo_pvc_fencing_unfencing' when using ms

- ocs_ci/deployment/flexy.py
- recent changes in flexy-templates (commit 4a4099541) changed location
of terraform.tfstate file for the vSphere deployment of OCP 4.11
> fix dployment of OCP 4.11 via Flexy on vsphere (Disconnected and Proxy environment)

- ocs_ci/ocs/resources/pod.py
Fixing the test case tests/manage/z_cluster/test_rook_operator_restart_during_mon_failover.py::TestDrainNodeMon::test_rook_operator_restart_during_mon_failover on Managed Services platform.
This test case is running on provider and these pods will be in Completed state.
```
$ oc get pods | grep -v -
NAME                                                              READY   STATUS      RESTARTS       AGE
83c3be2b7fc4205dc1cefb3affc660a2c60990fefc639824a531791870j8xlm   0/1     Completed   0              3h44m
8f0dad2ef3cd12d5193c166e42e56f8ccae06c14bd61e23751e126d13czd4jh   0/1     Completed   0              3h44m
```
Running status check for these pods should be skipped.
Skip the pods which are in 'Completed' state when checking for all pods in the namespace openshift-storage. 'Completed' …
> Skip Running status check of 'Completed' pods when checking for all pods in the namespace openshift-storage

- ocs_ci/ocs/constants.py
As we opened a [BZ2100352](https://bugzilla.redhat.com/show_bug.cgi?id=2100352) to make some order in lvm pods labels the change is in image quay.io/rhceph-dev/ocs-registry:4.11.0-105.
Adjusting the labels to new change.
> Label change in LVMO pods in image quay.io/rhceph-dev/ocs-registry:4.11.0-105

- ocs_ci/deployment/deployment.py
Reverts red-hat-storage/ocs-ci#4884. #4884 seems to have not been tested with any IO tests, and leads to product crashes the moment I/O begins to flow in or out, with endpoint pods entering a CrashLoopBackOff.
> Revert "Reducing limits for nooba-endpoints"

- tests/conftest.py
Currently, the method fails due to the following error -
>               created_bucket.verify_health(timeout=180, **kwargs)
E               TypeError: verify_health() got multiple values for keyword argument 'timeout'
> Allow passing `timeout` to the bucket creation's `verify_health` method

- tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
The test case is failing with the error in managed services cluster.
```
failed on setup with "AssertionError: Block pool cbp-test-fcfd433a65bb4a00ad7a6f1b784b8e4 does not exist"
```
This test case creates new storageclass using storageclass kind yaml and new cephblockpool. This is not supported in Managed Services cluster. This test cases should be skipped in MS.
Fixes #6099 
> Skip the test case test_rbd_space_reclaim_no_space in MS

- ocs_ci/ocs/node.py
This PR is to ignore known is\sue and
reduce the fleakyness in the deployment pipeline
https://github.com/red-hat-storage/ocs-ci/issues/6066
> ignoring node count missmatch error in deployment test for MS

- ocs_ci/ocs/cluster.py
- ocs_ci/utility/utils.py
After a destructive test on the consumer, the rook ceph tool pod may delete, and we will get the error: 
> [errno 1] RADOS permission error (error connecting to the cluster)
command terminated with exit code 1
In such a case, we want to patch the consumer rook ceph tool deployment with the ceph-admin key.
> Patch the consumer ceph-too-pod when checking the ceph health

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
TL;DR
- from 4.11.0-99 lvmo pod in crashloopback. There is an automation workaround and it is applied from 99-110 where it is solved.
- from 4.11.0-105 labels where change.
- from 4.11.0.105 restores of snapshot and clone are empty till a build with the fix will be available
Need to continue deployment for latest versions for other features than snap/clone and for automation effort of snap/clone need to be able to deploy older versions than 4.11.0-105
Till latest will be stable this is the only solution to keep on working. Even PR validations will not work without this fix. not so tldr :)
In 4.11-105 lvmo pods labels were changed and [#6079 ](https://github.com/red-hat-storage/ocs-ci/pull/6079) was merged. Now that we have a blocker …
> WA for lvmo snapshot and clone  for 2 feature_blocker and label change

- ocs_ci/ocs/ocp.py
> Update get_resource() to accurately split title and resource info

- tests/conftest.py
[commit](https://github.com/red-hat-storage/ocs-ci/pull/4893/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R4403-R4404)  from #4893 has erased the return value of the `def storageclass_factory_ui_fixture` factory by mistake. Added return factory
Fixes: #5885
> Fix block pool testcase because some other PR erased return value

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/longevity.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/resources/pod.py
- tests/manage/z_cluster/test_mon_log_trimming.py
This PR covers,
*. Cluster sanity checks for Longevity stages
*.  Collect cluster sanity checks outputs and store the outputs in ocs-ci log directory
*. OCP watchlist BZ#2049102 automation as part of closed loop
> cluster sanity checks for Longevity stages

- tests/e2e/performance/csi_tests/test_pod_reattachtime.py
This PR handles the following: 
- Setup change - create a unique project so that all the PVCs and pods will be created inside it 
- Teardown improvement - delete of the project so that all the nstances will be delated fasted ( improves test run time) 
- getting rid of usage of pvc and pod factories (improves memory consumption) 
> Test_pod_reattachtime - code efficiency and run time  improvements

- ocs_ci/deployment/vmware.py
Coreos-installer v0.15.0 require some lib that have dependencies and SNO deployment is failing. Going back to v0.14.0.
> Replace coreos-installer git with tag v0.14.0

- ocs_ci/deployment/flexy.py
- this should prevent failures, when NFS share or network is slower than
usuall and the deployment fails only because the mirroring of flexy
working directory to cluster dir on NFS share takes longer than usual
> extend timeout for rsync flexy work dir to cluster dir

- ocs_ci/ocs/benchmark_operator.py
This workaround fix issue with benchmark-operator which prevent from creating the fio-client-pod
I created Image from latest working commit, upload it to quay.io/ocsci and use this image in the test.
once the issue will be fix in the original repo (may take some time) this PR can be revert.
> benchmark-operator workaround

- tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
Skip the test `test_check_pod_status_after_two_nodes_shutdown_recovery` because currently, we don't support the shutdown of two worker nodes with MS.
> Skip the test "test_check_pod_status_after_two_nodes_shutdown_recovery"

- tests/e2e/workloads/test_data_consistency.py
Ignore 10% of rsync failures during data fetching phase of `test_log_reader_writer_parallel`.
This change should have little direct impact on the nature of the test, as the data consistency issues should be clearly visible even with 10% of rsync failures.
Fixing https://github.com/red-hat-storage/ocs-ci/issues/5526
> Issue 5526

- docs/usage.md
Added backslashes to the commands so that they don't throw error when copy pasted on the terminal
Signed-off-by: Shivam Durgbuns <sdurgbun@redhat.com>
> Added appropriate backslashes to the commands

- ocs_ci/helpers/performance_lib.py
- tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py
- tests/e2e/performance/csi_tests/test_pod_attachtime.py
- tests/e2e/performance/csi_tests/test_pod_reattachtime.py
This PR handles the following: 
- pod_bulk_attach_csi_time function was added to performance lib to calculate csi time of bulk pod attach operation 
- pod_attach_csi_time was enhanced to return values used later for pod_bulk_attach_csi_time calculation
- as a result test_pod_attachtime and test_pod reattachtime were slightly modified to suit the modified pod_attach_csi_time
- test_bulk_pod_attachtime_performance test was enhanced with the measurement of csi bulk pod attach time
> Adding csi bulk pod attach measurements

- ocs_ci/ocs/osd_operations.py
- ocs_ci/ocs/resources/pod.py
https://bugzilla.redhat.com/show_bug.cgi?id=2057359#c4
https://bugzilla.redhat.com/show_bug.cgi?id=2026007
Test Path:
tests/manage/z_cluster/nodes/test_disk_failures.py::TestDiskFailures::test_recovery_from_volume_deletion
> Added FORCE_OSD_REMOVAL flag on ocs-osd-removal-job

- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/ocp.py
- ocs_ci/utility/utils.py
- tests/conftest.py
- tests/lvmo/test_lvm_clone_base.py
- tests/lvmo/test_lvm_multi_clone.py
- tests/lvmo/test_lvm_multi_snapshot.py
- tests/lvmo/test_lvm_snapshot_base.py
- tests/lvmo/test_lvm_snapshot_bigger_than_disk.py
In my last PR I've changed the way sampling of product works and didn't test it enough and it is failing.
This is a fix to the fail and also if you check lvmcluster and it is not installed, it will not stdout the errors and only log that cephcluster is installed and the other way if cephcluster is not installed  and lvmcluster is.
Also because of all the fixtures in the test (5-6) on every change the finalizers get mixed. I've flattened all the test not have fixtures. Saw that every test that use more than 3-4 factories is flat in the test.
Fixes: #6227
> Fix cephcluster/lvmcluster sampling and silent the error from the cluster that is not found.

- tests/lvmo/test_lvm_clone_base.py
- tests/lvmo/test_lvm_multi_clone.py
- tests/lvmo/test_lvm_multi_snapshot.py
- tests/lvmo/test_lvm_snapshot_base.py
- tests/lvmo/test_lvm_snapshot_bigger_than_disk.py
Change varible fs to storage_type and increase snap and clone tests version to 4.11 
> Change variable fs to storage_type and increase snap and clone tests version to 4.11 

- ocs_ci/ocs/cluster.py
Today implementation like initialize the LVM class there many data requests to the server through ssh. Every command open and close connection. To save time it is changed to have persistent ssh connection.
> Adding permanent ssh connection instead of new connection every call for data.

- ocs_ci/deployment/vmware.py
- ocs_ci/utility/utils.py
Till now terraform for sno was using [https://github.com/shyRozen/installer.git](https://github.com/shyRozen/installer.git) as there is no openshift/installer terraform for SNO.
As I want to do changes and try to commit it to openshift/installer I'm moving the private fork to [https://gitlab.cee.redhat.com/srozen/installer](https://gitlab.cee.redhat.com/srozen/installer) till PR and merge will happen to upstream.
> Replace current working private installer git for SNO

- ocs_ci/helpers/performance_lib.py
- tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
Previous version of the test was measuring Deletion and CSI Deletion times as None. 
Following the current fix Deletion and CSI deletion times will be measured. 
Example from test log: 
17:44:58 - MainThread - test_pvc_creation_deletion_performance - INFO  - Interface: CephBlockPool, PVC size: 5Gi. PVC number 1 was created in 0.087 seconds.
17:44:58 - MainThread - test_pvc_creation_deletion_performance - INFO  - Interface: CephBlockPool, PVC size: 5Gi. PVC number 1 was deleted in 0.078 seconds.
17:44:58 - MainThread - test_pvc_creation_deletion_performance - INFO  - Interface: CephBlockPool, PVC size: 5Gi. PVC number 1 was csi_created in 0.082 seconds.
17:44:58 - MainThread - test_pvc_creation_deletion_performance - INFO  - Interface: CephBlockPool, PVC size: 5Gi. PVC number 1 was …
> test_pvc_creation_deletion_performance.py - fixing deletion measurements

- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/node.py
For run id 1656660125
test-
tests/manage/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py::TestCheckTolerationForCephCsiDriverDs::test_ceph_csidriver_runs_on_non_ocs_nodes
Also fixes #5863
> Increasing timeout for the test case and collecting ocp must-gather in case of failure for debugging purpose

- tests/conftest.py
> Add external mode constants in create_restore_pvc function

- ocs_ci/framework/conf/default_config.yaml
New version of rosa CLI 1.2.5 is available now.
https://github.com/openshift/rosa/releases/tag/v1.2.5
> Update Rosa CLI version to 1.2.5

- ocs_ci/utility/pagerduty.py
- ocs_ci/utility/users.py
-dry-run is deprecated and can be replaced with --dry-run=client
> use dry-run with client

- tests/manage/z_cluster/nodes/test_nodes_restart.py
We can see in the test https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/4875/testReport/tests.manage.z_cluster.nodes.test_nodes_restart/TestNodesRestart/test_nodes_restart_True_/, that when we use the external mode cluster, it searches for the wrong pods. That's why we should use the "SanityExternalCluster" in case we use the external mode in the test "test_nodes_restart".
> In the test "test_nodes_restart" use "SanityExternalCluster" in case we use the external mode

- tests/manage/pv_services/pvc_clone/test_node_restart_during_pvc_clone.py
Fixes #6284 
The check for volume mode is needed only when the volume mode is "Block". Modified the condition to check volume mode "Block" instead of volume mode "FileSystem".
> Fix the condition to get file path on pod

- tests/conftest.py
- tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
- tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Fixes: #6125 
#5310 
Wait time was added after the cluster load is paused before the test execution, to allow the proper used size to be collected.
> Add wait time after cluster load is paused for a test

- ocs_ci/ocs/acm/acm.py
For installing submariner the install button takes time to load.
We can see a timed out execution here (default is 30 sec):
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-dr-setup/52/console
And also a result of passing this through when increased to 120 seconds:
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-dr-setup/54/console
> Increase timeout for EC of submariner install button

- ocs_ci/ocs/quay_operator.py
- tests/e2e/workloads/app/quay/test_quay_operator.py
- Failing tests with correct message, if API calls to Quay endpoint fails
- Added +30 seconds of wait for the Quay endpoint to start serving to avoid unnecessary failures
> Minor fix on Quay workload

- tests/manage/z_cluster/nodes/test_rolling_shutdown_and_recovery.py
Skip the test "test_rolling_shutdown_and_recovery" when using the Managed Service. I will implement a new test in the pr https://github.com/red-hat-storage/ocs-ci/pull/6328.
> Skip the test "test_rolling_shutdown_and_recovery" when using MS

- tests/manage/z_cluster/nodes/test_disk_failures.py
fix https://github.com/red-hat-storage/ocs-ci/issues/6256
> Skip the test 'test_recovery_from_volume_deletion' when using external mode

- ocs_ci/ocs/bucket_utils.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/cloud_manager.py
- tests/manage/mcg/test_noobaa_secret.py
Covers these BZs:
https://bugzilla.redhat.com/show_bug.cgi?id=1992090#c25
https://bugzilla.redhat.com/show_bug.cgi?id=2090956#c8
Modified `cli_create_aws_backingstore()` to use secret name instead of using credentials because using credentials would create one more secret and there is no point of using cld_mgr to create secrets prior which remain unused(?)
> Test MCG secrets

- conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_3w_external.yaml
Proposed deployment configurations for external mode and Metro DR use cases:
- ~deployment of OCP for standalone RHACM Hub~ (proposed config with 0 worker nodes is not a valid configuration from openshift's perspective, so we are dropping this)
> simple OCP deployment for external mode

- ocs_ci/ocs/constants.py
- tests/manage/z_cluster/test_ceph_default_values_check.py
Fix for issue, https://github.com/red-hat-storage/ocs-ci/issues/5738.
Have updated postgres max connections to 600 instead from 300 for ocs version 4.9 and updated the version specific checks.
> Fixing postgress max connections for test_noobaa_postgres_cm_post_ocs_upgrade

- tests/lvmo/test_lvmo_pvc_resize.py
resize pvc beyond thin-pool size, but within thinpool over-provisioning rate
https://bugzilla.redhat.com/show_bug.cgi?id=2111895
> Bz 2111895 automation - PVC resize on lvm cluster

- ocs_ci/ocs/resources/pvc.py
Use snapshot apiVersion "snapshot.storage.k8s.io/v1beta1" if OCP version is below 4.9.
Fixes #6416
> Fix snapshot apiVersion based on OCP version

- ocs_ci/helpers/sanity_helpers.py
- tests/managed-service/test_sanity_ms.py
- tests/managed-service/test_santiy_ms.py
I created a new sanity helper class to efficiently run IO on multiple consumers and check the functionality of the Managed Service cluster/s. To run IO I use the fixture `create_scale_pods_and_pvcs_using_kube_job_on_ms_consumers` defined here https://github.com/red-hat-storage/ocs-ci/blob/master/tests/conftest.py#L5647.
Before we create the resources on the MS consumers, we need to pass an instance of the fixture `create_scale_pods_and_pvcs_using_kube_job_on_ms_consumers` to the `init_create_resources_on_ms_factory` method.
Also, we can specify extra parameters in the method - if not, it uses the default parameters.
After adding this new class, we can quickly modify or create new tests with the Managed Service.
The implementation is a little complicated, but the usage is easy and …
> Create a new sanity helper class for the Managed Sevice

- tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
Verify that unschedule, drain and restart of a worker node in the provider cluster will not cause any functionality issues.
> Test case to verify unschedule, drain and restart of a worker node in the provider

- tests/e2e/workloads/test_data_consistency.py
Dropping error_condition=constants.STATUS_ERROR from
ocp_pod.wait_for_resource() call in the logwriter test to make the error
handling more resilient.
If the pod is able to recover from the error, the test will continue and
will check the feature under test, and if not, the error won't go
unnoticed as it will fail after allowed_failures counter is breached.
fixing https://github.com/red-hat-storage/ocs-ci/issues/6382
> make test_log_reader_writer_paraller more error resilient

- tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Added aws_platform_required tag for the suite to run it only for AWS clusters.
> Added aws_platform_required tag for the suite to run it only for AWS clusters

- ocs_ci/ocs/resources/objectbucket.py
This PR fixes https://github.com/red-hat-storage/ocs-ci/issues/6459
1.  Scales s3 delete objects for buckets having huge number of objects
2. Handle versioning enabled and disabled bucket deletion differently
> Scale s3 delete bucket for buckets having huge number of objects

- ocs_ci/framework/__init__.py
- ocs_ci/framework/pytest_customization/marks.py
- tests/e2e/workloads/test_create_scale_pods_and_pvcs_using_kube_job.py
I implement the following in the pr:
1. Create new markers for checking if we use the Managed Service with provider and consumer clusters:
- **ms_provider_and_consumer_required**
- **skipif_ms_provider_and_consumer**
2. Use these markers in the test "test_create_scale_pods_and_pvcs_using_kube_job".
> Create new markers for checking if we use the Managed Service with provider and consumer clusters

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/lvmo-deployment/lvm-cluster-412.yaml
Change pod label dictionary above 4.11 to default and add pod security label to openshift-storage
Fixes: #6393 
> Change pod label dictionary above 4.11 to default and add pod security label to openshift-storage

- tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Added skipif_external_mode tag for the nfs enabled test suite as external mode support is out of scope
> Added skipif_external_mode tag for the nfs testsuite

- tests/manage/pv_services/test_overprovision_level_policy_control.py
Skip the test tests/manage/pv_services/test_overprovision_level_policy_control.py if the platform is Managed Services.
Fixes #6454 
> Skip the test test_overprovision_level_policy_control in MS

- tests/managed-service/test_post_installation_state.py
The bug 2073025 was recently closed as a duplicate of 2117312. The bugzilla marker is be updated to skip the test.
Fixes #6448
> Update bugzilla marker in the test test_connection_time_out

- tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
Increase timeout while waiting for pod to reach Running state in the test test_change_reclaim_policy_of_pv.
Fixes #6452
> Increase pod wait time in test test_change_reclaim_policy_of_pv

- ocs_ci/framework/pytest_customization/marks.py
- pytest.ini
- tests/conftest.py
- tests/disaster-recovery/regional-dr/test_failover.py
- tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
- tests/disaster-recovery/regional-dr/test_relocate.py
Add basic failover and relocate tests for Regional DR
Test cases added:
1) tests/disaster-recovery/regional-dr/test_failover.py
This covers two cases:
-   Failover to secondary cluster when primary cluster is UP
-   Failover to secondary cluster when primary cluster is DOWN
2) tests/disaster-recovery/regional-dr/test_relocate.py
3) tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
This covers two cases:
-   Failover to secondary cluster when primary cluster is UP and Relocate back to primary cluster
-   Failover to secondary cluster when primary cluster is DOWN and Relocate back to primary cluster once it recovers
> Add failover and relocate tests for Regional DR

- ocs_ci/framework/pytest_customization/marks.py
- pytest.ini
- tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py
- tests/e2e/performance/csi_tests/test_pod_attachtime.py
- tests/e2e/performance/csi_tests/test_pod_reattachtime.py
- tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
- tests/e2e/performance/csi_tests/test_pvc_bulk_creation_deletion_performance.py
- tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
- tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
- tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
- tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
- tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
- tests/e2e/performance/io_workload/test_fio_benchmark.py
- tests/e2e/performance/io_workload/test_perf_pgsql.py
- tests/e2e/performance/io_workload/test_small_file_workload.py
- tests/e2e/performance/mcg/test_mcg_cosbench.py
The porpoise of this PR is to split the Performance test suite, since, currently the suite doesn't completed because of memory consumption (memory Leak).
In this way each part of the suite consume less memory and less time to complete, so the running of the full suite will finish and in less time.
the PR was tested locally - 3 different runs, and it finish.
> Splitting the performance suite to 3

- ocs_ci/ocs/resources/pod.py
Updated the code to split the `count` from the `age` of the pod in the `get_pod_restarts_count()`
Fixes: #6359 
Signed-off-by: nik-redhat <nladha@redhat.com>
> Fix pod count parsing in get_pod_restarts_count()

- ocs_ci/utility/localstorage.py
we are ignoring "stable" channel while listing channels. In this case we are missing latest channel because stable point to latest one.
> get latest lso channel

- ocs_ci/ocs/bucket_utils.py
Up until now the default CA bundle was used; Now, it leads to an SSL error.
This PR changes the behavior of MCG tests and fixtures running over IBM Cloud clusters to use the cluster's ingress certificate.
> Use the ingress cert for IBM Cloud deployments

- ocs_ci/ocs/bucket_utils.py
- ocs_ci/ocs/resources/backingstore.py
- tests/manage/mcg/test_pv_pool.py
This PR modifies the already existing test to cover additional scenarios:
1. Increased number of volumes for Pv pool based backingstores
2. Setting the resource parameters while creating the backingstore through CLI
Links:
https://issues.redhat.com/browse/RHSTOR-3506
https://issues.redhat.com/browse/RHSTOR-3725
> RHSTOR-3506: Qualify "Support resource modification for MCG PV pool pods - Test and Docs only"

- tests/conftest.py
Since, sometimes, the default 60 seconds were not enough
> Extend the S3CLI pod health check timeout

- tests/manage/mcg/test_kms.py
**Fix:**
Updated the string used to validate Nooba with KMS integration,
in the logs.
Fixes: #5968
Signed-off-by: nik-redhat <nladha@redhat.com>
> Fix: Updated kmscondition string to check in logs

- ocs_ci/ocs/node.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/decorators.py
- ocs_ci/utility/rosa.py
- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
The pr is for the Managed Service when using a provider and consumers. 
I added in the pr the verification steps on the MS consumers after a provider node replacement. 
The steps are as follows:
1. Check if the consumer "storageProviderEndpoint" IP is found in the provider worker node ips
1.1 If not found, edit the rosa addon installation - modify the param `storage-provider-endpoint` with the first provider worker node IP.
1.2 Wait and check again if the  consumer "storageProviderEndpoint" IP is found in the provider worker node ips
2. If found, also check that the rook ceph mon endpoint IPs are found in the provider worker node ips
I also implemented a new decorator for wrapping a function related to the Managed Service to ensure we use the original index after the execution.
> Add verification steps on the MS consumers after a provider node replacement

- conf/ocsci/dr_workload.yaml
- ocs_ci/helpers/dr_helpers.py
- ocs_ci/ocs/dr/dr_workload.py
This PR includes required changes in ocs-ci to use the ocs-workloads as default repo and also supports it's new directory structure introduced in https://github.com/red-hat-storage/ocs-workloads/pull/14
> [RDR] Change default workload repo and support new directory structure of ocs-workloads repository

- tests/manage/z_cluster/nodes/test_disk_failures.py
Skip the test cases given below which is not currently relevant in Managed Service platform.
tests/manage/z_cluster/nodes/test_disk_failures.py::TestDiskFailures::test_detach_attach_worker_volume
tests/manage/z_cluster/nodes/test_disk_failures.py::TestDiskFailures::test_detach_attach_2_data_volumes
> Skip volume detach tests in MS

- ocs_ci/ocs/constants.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
Update the test given below to expect OSD in pending state after node drain if the the OSDs are running on dedicated nodes only. This is the change related to pricing and topology changes. OSDs cannot run on worker nodes which does not have the label ```node.ocs.openshift.io/ocd=''```
tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py::TestAutomatedRecoveryFromFailedNodeReactiveMS::test_automated_recovery_from_failed_nodes_reactive_ms[drain_node]
Fixes #6558 
> Update OSD expected state in test_automated_recovery_from_failed_nodes_reactive_ms[drain_node]

- tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Because of the issue: #6579
Disabling those tests which are using sudou mount on jenkins agent.
> Disable NFS tests

- ocs_ci/ocs/cluster.py
> Add repeat for wait_for_rebalance

- ocs_ci/ocs/resources/rgw.py
4.6's Extended Update Support is about to end next week, so I removed the conditions entirely, as far as I'm aware, all supported ODF versions should now be using the same route name
Closes #6167
> Look for the correct external RGW route name

- ocs_ci/ocs/bucket_utils.py
- ocs_ci/ocs/resources/mcg.py
- tests/e2e/scale/noobaa/test_scale_bucket_replication.py
- tests/e2e/system_test/test_mcg_replication_with_disruptions.py
- tests/manage/mcg/test_bucket_replication.py
#6570 took care of the standard OBC creation schema, but not of these two cases.
> Support new MCG replication rules schema for OBC patches and bucketclasses

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/pvc.py
- ocs_ci/templates/CSI/lvm/storageclass.yaml
- ocs_ci/templates/CSI/lvm/storageclass_4_11.yaml
- tests/conftest.py
topolvm domain name changed to "topolvm.io" in 4.12
> added new topolvm domain name support

- ocs_ci/ocs/ui/mcg_ui.py
This test was repeatedly failing, so after debugging a couple of times, it seems the code is perfectly fine but it's flaky because sometimes the clicks are too fast and console is unable to match the timing. So as a temp. fix, I added a few sleeps and ran the PR validation which passed.
For the long term, we would need to design a function to handle such scenarios as using sleep is not recommended in UI automation.
> Adding sleep to avoid flakiness in the MCG test

- conf/ocsci/ciphertrust_kms_deployment.yaml
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/templates/openshift-infra/kmip/ocs-kms-connection-details.yaml
- ocs_ci/templates/openshift-infra/kmip/thales-kmip-ocs-secret.yaml
- ocs_ci/utility/kms.py
- ocs_ci/utility/utils.py
Add support for clusterwide encryption using KMIP (Thales CipherTrust Manager)
Epic link: https://issues.redhat.com/browse/RHSTOR-2179
> Add support for ODF clusterwide encryption using KMIP

- tests/manage/mcg/test_s3_routes.py
nb mgmt is by default clusterIP as per https://github.com/noobaa/noobaa-operator/pull/941#discussion_r920850680
> Disable lb test 4.12 fix

- ocs_ci/deployment/ibmcloud.py
> Limit IBM Cloud IPI deployments to OCP version 4.10 or greater

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/utils.py
How to use start and stop VM's using FQDN
```
node_ips = convert_hostnames_to_ips(node_names)
vms = self.get_vm_from_ips(node_ips, dc)
self.vsphere.stop_vms(vms)
self.vsphere.start_vms(vms)
```
> VM's start/stop using FQDN

- ocs_ci/ocs/managedservice.py
- ocs_ci/utility/utils.py
Currently, we patch the consumer rook-ceph-tool deployment when we get the RADOS error "RADOS permission error". Recently, when running a test, I saw that there is another optional error, "RADOS I/O error" that can occur. So we need to create a new function to check all the RADOS connect errors in the exception.
> Create a new function to check if the rados connect error is in the exception

- ocs_ci/helpers/sanity_helpers.py
- tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
In the test "test_rolling_nodes_restart" for MS, wait more time for the nodes recovery before checking cluster health and before creating resources. See more details in the issue https://issues.redhat.com/browse/ODFMS-324.
> Wait more time for the nodes recovery in the test "test_rolling_nodes_restart" for MS

- ocs_ci/ocs/osd_operations.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/utility/utils.py
Fixes: #6662
Add FORCE_OSD_REMOVAL set to true from the OCS 4.6 version in case the ceph osd safe-to-destroy command is not OK
Add v4.12 to ocs_version_pattern_dict
> ocs-osd-removal update job with review fixes

- setup.py
Updated gevent and greenlet modules with arm64 m1 chip support.
More about issue is in comments to
https://stackoverflow.com/questions/71443345/gevent-cant-be-installed-on-m1-mac-using-poetry
and
https://github.com/pypa/manylinux/issues/687
> setup.py upd with gevent and greenlet latest versions 

- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/utility/utils.py
PR is intended to optimize resource consumption. 
For example during the tests/manage/z_cluster/cluster_expansion/test_add_capacity.py:test_add_capacity and tests/manage/z_cluster/cluster_expansion/test_node_expansion.py:test_add_ocs_node we often get "Cannot allocate memory error". During the tests we frequently request pod.get_ceph_tools_pod() -> 'oc get pod -n openshift-storage -o yaml' which produce 30k lines of text in the log each, around 1.35 Mb. This PR replaces such requests with request specified with selector, reduce memory consumption. 
Since shallow requests were called with get_ceph_tools_pod() common routine, changes may have effect not only on the tests test_add_ocs_node and py:test_add_capacity but on many others.
Additionally prevent logs inflation.
Linked issue: …
> Remove shallow oc get Pod requests

- tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
The pr includes the following changes in the test "test_worker_node_restart_during_pvc_expansion":
- Skip the test if we use an MS provider cluster
- Check that we can execute a Ceph command successfully. In the case of a consumer cluster, it also patches the rook-ceph-tools deployment on the consumer if we have a RADOS connect error.
> Fix the test "test_worker_node_restart_during_pvc_expansion" when using MS

- tests/manage/pv_services/pvc_snapshot/test_verify_rbd_trash_purge.py
Skip the test case given below if the the cluster is external mode. The test case creates CephBlockPool and storageclass.
tests/manage/pv_services/pvc_snapshot/test_verify_rbd_trash_purge.py
> Skip test case in external mode

- tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
- tests/e2e/workloads/test_new_sc_rbd_e2e_workloads.py
Skip the test case given below if the the cluster is external mode. The test case creates CephBlockPool and storageclass.
tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
tests/e2e/workloads/test_new_sc_rbd_e2e_workloads.py
Signed-off-by: vkathole <vkathole@redhat.com>
> Skip test cases in external mode

- ocs_ci/ocs/node.py
> Catch the exception of "NotFoundError" when going over the pods in the function "get_node_pods"

- tests/manage/pv_services/test_verify_new_cbp_creation_not_blocked_by_invalid_cbp.py
Skip the test case given below if the the cluster is external mode. The test case creates CephBlockPool.
tests/manage/pv_services/test_verify_new_cbp_creation_not_blocked_by_invalid_cbp.py::test_verify_new_cbp_creation_not_blocked_by_invalid_cbp
Fixes #6827 
> Skip test_verify_new_cbp_creation_not_blocked_by_invalid_cbp in external mode

- ocs_ci/framework/conf/default_config.yaml
OSD pod memory in Managed Services provider cluster is changed to 5700Mi  in v2.0.11.
Fixes #6872 
> Update ms_osd_pod_memory value

- tests/manage/z_cluster/test_rook_ceph_operator_log_type.py
As per issue https://github.com/red-hat-storage/ocs-ci/issues/6866, skipping the test for external mode cluster
> Skip "test_rook_ceph_operator_log_type" for external mode cluster

- ocs_ci/helpers/managed_services.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/storage_cluster.py
Update the condition for checking the provider topology based on the deployer version. Provider topology verification is relevant if deployer version is 2.0.11 or above.
> Verify provider topology based on deployer version in MS

- tests/manage/mcg/test_s3_with_java_sdk.py
Fixes: #6845
Signed-off-by: Sagi Hirshfeld <shirshfe@redhat.com>
> Add the skipif_disconnected_cluster flag to test_s3_with_java_sdk.py::TestS3WithJavaSDK

- tests/manage/mcg/test_admission_control.py
Fixes: #6838 
Signed-off-by: Sagi Hirshfeld <shirshfe@redhat.com>
> Fix the expected error message when providing an empty secret name at TestAdmissionWebhooks::test_namespacestore_creation_webhook[Empty secret name]

- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/ocs/ui/add_replace_device_ui.py
- ocs_ci/ocs/ui/views.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
We are using `try exception`  method for add capacity test.
https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/z_cluster/cluster_expansion/test_add_capacity.py#L45-L51
When the add capacity process fails via UI, we perform the process via CLI.
In this situtaion, we cant catche bugs like this  https://bugzilla.redhat.com/show_bug.cgi?id=2137616 [there is an option to check the screenshots]
The developers change the locators frequtly, so the test fails even though there is no real bug. 
So I think the method is to split add capacity test to acceptance [cli] and tier1 [ui] 
> Split add capacity test on tier1 suite [ui] and acceptance test [cli]

- tests/manage/mcg/test_admission_control.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/6782
> Fix validation for namespacestore creation webhook test

- tests/manage/mcg/test_bucket_replication.py
Fixes: #6799 
Signed-off-by: sagihirshfeld [shirshfe@redhat.com](mailto:shirshfe@redhat.com)
> Fix a mismatch between the PyTest param and it's ID at test_unidirectional_namespace_bucket_replication

- tests/manage/mcg/test_bucket_creation.py
- tests/manage/mcg/test_bucket_deletion.py
Fixes: #6348
Signed-off-by: sagihirshfeld <shirshfe@redhat.com>
> Add the skipif_mcg_only mark to MCG PVPool tests

- tests/manage/mcg/test_kms.py
Fixes: #6575 
Signed-off-by: Sagi Hirshfeld <shirshfe@redhat.com>
> `test_noobaa_kms_validation` - Also check the logs with --previous if the noobaa-operator pod restarted

- tests/manage/z_cluster/test_mon_log_trimming.py
In External mode there will be no any mon,osd,mds,mgr,rgw pods. [Reference](https://docs.google.com/presentation/d/1H_2D2f9LUWRqQTGbYcPVA3z3YIhEE-4hm3yUEb9WNC0/edit#slide=id.g900445dfe9_0_178)
Deployment: OCS4-12-Downstream-OCP4-12-VSPHERE6-UPI-1AZ-RHCOS-EXTERNAL-3M-3W-tier2-jenkins
Test: [tests.manage.z_cluster.test_mon_log_trimming.TestMonLogTrimming](https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/6898/286901/287073)
Failure message:
Message: failed on setup with "IndexError: Cannot choose from an empty sequence"
Type: None
Text:
self = <tests.manage.z_cluster.test_mon_log_trimming.TestMonLogTrimming object at 0x7f4167ae4040>
request = <SubRequest 'setup' for >
pod_factory = …
> Added skipif_external_mode tag for test_mon_log_trimming testcase

- tests/manage/pv_services/test_rbd_image_metadata.py
Configure the test case test_rbd_image_metadata to fetch the actual CephBlockPool name in external mode.
Fixes #6824 
> Fix test_rbd_image_metadata in external mode

- .pre-commit-config.yaml
Fixes: #6678
Flake8 migrated from https://gitlab.com/pycqa/flake8 to https://github.com/pycqa/flake8
> Update pre-commit-config with new repository of flake8

- ocs_ci/ocs/resources/cloud_manager.py
Fixes: #6837 
`GCPBucket.delete_blobs` in `GoogleClient.delete_uls` could not parse the blobs in HTTPIterator which is the default output of `GCPBucket.list_blobs`, causing an `HTTPIterator has no len` error. This issue is resolved by passing these blobs via a Python List instead.
In addition to solving this issue, this PR includes a minor refactor regarding the way that CloudClients and it's inheritors S3Client, GoogleClient, and AzureClient are deleting ULS':
The TimeoutSampler logic that was used in `S3Client.delete_uls` has been elevated to the abstract parent class and the abstract method `CloudClient.internal_delete_uls`, which is implemented by each inheritor, is the function that is used by the TimeoutSampler.
> Fix the deletion of the underlying storage of GCP BackingStores and minor refactor regarding CloudClient.delete_uls

- ocs_ci/ocs/constants.py
- for ODF 4.12 odf-lvm-operator was removed form ODF and renamed to lvms-operator (but it is not yet GA)
- for ODF prior 4.12, we should still use odf-lvm-operator
https://bugzilla.redhat.com/show_bug.cgi?id=2153255
> Disconnected deplyoment: lvm operator moved out from odf

- tests/manage/mcg/test_host_node_failure.py
See the comment here: https://github.com/red-hat-storage/ocs-ci/issues/6689#issuecomment-1372144623, and the following discussion.
> In the test "test_noobaa_sts_host_node_failure" Change how we check the old noobaa operator status

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/utility/retry.py
1.On test_unprivileged_user_odf_access, a new user was created. [tests/ui/test_non_admin_user.py::TestUnprivilegedUserODFAccess::test_unprivileged_user_odf_access]
When a new user is created, we get this login page:
I added a code to click on "kube:admin"
2.On login_ui, we are using the "retry" decorator.
However, the process of the web page (which failed to login) is still running, which increases CPU consumption and memory consumption. So I added Garbage Collector
> Garbage collector for WebDriver

- tests/manage/pv_services/test_overprovision_level_policy_control_with_capacity.py
> Skip test_overprovision_level_policy_control_with_capacity on external mode

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/ocp.py
- ocs_ci/utility/ocp_upgrade.py
- tests/ecosystem/upgrade/test_upgrade_ocp.py
This step is  recommended in [OCP documentation](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html-single/updating_clusters/index#machine-health-checks-pausing_updating-cluster-cli) for OCP 4.9 and above.
> pause MachineHealthCheck during OCP upgrade

- ocs_ci/ocs/resources/storage_cluster.py
Topology of managed ODF clusters is changing due to Pricing epic. The final version is yet unknown. We need to disable the check so that deployments are not marked as failed.
> Disable managed ODF topology check

- ocs_ci/helpers/managed_services.py
- ocs_ci/ocs/resources/storage_cluster.py
The memory of OSD is changed as part of topology changes. Moving the verification of OSD memory to the function verify_provider_topology will keep the verification of topology changes in on place.
Closes #6957
> MS: Move OSD memory check to verify_provider_topology function

- ocs_ci/ocs/ui/base_ui.py
Changed the closing method from `close` to `quit`
```
failed on setup with "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=45301): Max retries exceeded with url: /session/58d5027e5219c9c63704113e78e2b2ca/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8ae7195fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
```
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6664/testReport/tests.ui.test_validation_ui/TestUserInterfaceValidation/test_dashboard_validation_ui/
https://stackoverflow.com/questions/63944480/maxretryerror-selenium
> Fix login UI urllib3 exceptions MaxRetryError

- tests/manage/mcg/test_cached_buckets.py
- tests/manage/mcg/test_multi_region.py
- tests/manage/mcg/test_namespace_crd.py
- tests/manage/mcg/test_noobaa_secret.py
- tests/manage/mcg/test_object_integrity.py
Fixes: #6855 
Implemented by adding the `@skipif_disconnected_cluster` PyTest mark to tests that make external requests.
These requests are mostly to AWS, as evident by the current `@skipif_aws_creds_are_missing` flag in most of these tests.
> Skip MCG tests that make external requests in disconnected deployments

- conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_6w_arbiter.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/netsplit.py
- ocs_ci/ocs/resources/machineconfig.py
- requirements.txt
Overview:
- implementing https://github.com/red-hat-storage/ocs-ci/issues/4575
- using [ocp-network-split #3](https://gitlab.com/mbukatov/ocp-network-split/-/issues/3) feature, see [Single Cluster Usage](https://mbukatov.gitlab.io/ocp-network-split/usage.html#single-cluster-usage)
- use the latency in `upi_1az_rhcos_vsan_lso_vmdk_3m_6w_arbiter.yaml` config
Verification/Status:
> latency setup for a single cluster

- ocs_ci/ocs/node.py
- tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
Create a new function for generating nodes for the provider worker node tests.
The function generates the node objects as follows:
- If we have 3 worker nodes in the cluster, it generates all the 3 worker nodes
- If we have more than 3 worker nodes, it generates one mgr node, 2 mon nodes, and 2 osd nodes. The nodes can overlap, but at least 3 nodes should be selected(and no more than 5 nodes).
Also, add a new test 'test_rolling_provider_worker_nodes_restart' using the function above.
> Create a new function for generating nodes for the provider worker node tests

- ocs_ci/deployment/terraform.py
- ocs_ci/deployment/vmware.py
- ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml
- ocs_ci/ocs/constants.py
- ocs_ci/utility/load_balancer.py
- ocs_ci/utility/version.py
Fixes: #6906 
This PR contains below important changes
80bf74b1a155d64e9b204987549c04ffd1bd692b : support terraform version 1.0.11 in terraform module
2ea95d8d8780a204920425017e2a7200423a542b : donot remove lb node along with bootstrap node
0d0a129e1138de15866f34ba9fc2f57bcbeaaf7f : support terraform 1.0.11 version in destroy cluster
016cf163414d8a25aa49e6d3b99863412661c920 : use installer 4.12 branch due to failure domain changes in 4.13 branch
ade03ae671f0a9efdc1f8d32d33823e5e6a61b28 : use terraform version 1.0.11 for OCP 4.13
> support Terraform version 1.0.11

- .functional_ci_setup.py
- conf/README.md
- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/framework/pytest_customization/reports.py
- ocs_ci/ocs/constants.py
- ocs_ci/utility/memory.py
- ocs_ci/utility/utils.py
- setup.py
Added memory helper util based on https://github.com/red-hat-storage/ocs-ci/pull/5622
New functionality: during the test run consumed memory is monitored and results with memory peak processes printed into the log:
Leaked memory will be printed in a debug level.
Necessary libraries were added:
"pandas==1.5.2", "tabulate==0.9.0", "psutil==5.9.0"
Library version updated:
"python-dateutil==2.8.2"
Previously opened issue [link](https://github.com/boto/botocore/issues/1872) has been resolved and closed; python-dateutil update is dependancy for pandas version>=2.8.1 [link](https://pandas.pydata.org/docs/getting_started/install.html#:~:text=python%2Ddateutil,2.8.1)
> Add memory monitoring for process/subprocesses

- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
It was decided to wait until cephfs provisioner pod ready after node drain and before create new resources. 
Details in comments to BZ #2162504
> Fix #6953 test_node_maintenence. Add wait ceph plugin provisioner ready

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/validation_ui.py
- ocs_ci/ocs/ui/views.py
- tests/ui/test_validation_ui.py
New automation script for https://bugzilla.redhat.com/show_bug.cgi?id=2096414 test_odf_cephblockpool_compression_status
Validate Compression status for cephblockpool at StorageSystem details and ocs-storagecluster-cephblockpool are matching.
Some refactoring at ocs_ci/ocs/ui/validation_ui.py done in order to have more dry code
> Backlog automation for bz-2096414

- ocs_ci/utility/utils.py
Fix error: Dataframe ---> DataFrame
2023-02-02 20:22:22    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", line 1561, in add_mem_stats
2023-02-02 20:22:22      if "memory" in config.RUN and isinstance(config.RUN["memory"], pd.Dataframe):
2023-02-02 20:22:22    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.8/site-packages/pandas/__init__.py", line 264, in __getattr__
2023-02-02 20:22:22      raise AttributeError(f"module 'pandas' has no attribute '{name}'")
2023-02-02 20:22:22  AttributeError: module 'pandas' has no attribute 'Dataframe'
> Fix pd.DataFrame call in teardown

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/resources/storage_cluster.py
Verify provider topology in Managed Services cluster if the deployer version is 2.0.11 or higher.
Fixes #7000 
> Verify MS provider topology based on version

- ocs_ci/helpers/helpers.py
> Remove SYS_ADMIN capability for fedora DC workload to comply with pod security profiles

- tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
Add fio parameters direct=1 and end_fsync=1 in test_encrypted_rbd_block_pvc_snapshot
Based on discussions in PR #5193 and [Bug 2028757](https://bugzilla.redhat.com/show_bug.cgi?id=2028757) to make the test more stable.
> test_encrypted_rbd_block_pvc_snapshot I/O enhancement

- tests/manage/z_cluster/nodes/test_toleration.py
We need to skip s3cli pod from respin in test_toleration.py as this pod doesnt have the toleration set to "http://node.ocs.openshift.io/storage"
> Skipping s3cli pod from respin in test_toleration.py

- tests/manage/z_cluster/cluster_expansion/test_delete_pod.py
- tests/manage/z_cluster/test_restart_mgr_while_two_mons_down.py
Few test cases are not relevant for external mode cluster
https://github.com/red-hat-storage/ocs-ci/issues/6847 and https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8246/363236/363317/363319/log
> Skipping test cases that are not relevant for external mode cluster

- ocs_ci/deployment/rosa.py
- ocs_ci/ocs/constants.py
Adding workaround for the bug 2166900. Deleting rook-ceph-operator pod will resolve the issue. Applicable for Managed Services consumer cluster.
> Workaround for the bug 2166900

- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Skip 2 tests in Managed Services platform
Skip
_tests.manage.z_cluster.nodes.test_nodes_maintenance.TestNodesMaintenance.test_node_maintenance_restart_activate_
which is covered in tests/manage/z_cluster/nodes/test_nodes_restart_ms.py.
Skip the test case given below which is not relevant. 
_tests.manage.z_cluster.nodes.test_nodes_maintenance.TestNodesMaintenance.test_pdb_check_simultaneous_node_drains_
> Skip tests in MS

- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Increasing the wait time for the pods to reach the state Running.
Fixes #7088 
> Increase timeout waiting for pod to reach running in test test_resource_deletion_during_pvc_pod_creation_and_io

- ocs_ci/utility/decorators.py
- tests/conftest.py
Fix issue https://issues.redhat.com/browse/ODFMS-388.
> Switch to the default cluster index at the "create_scale_pods_and_pvcs_using_kube_job_on_ms_consumers" fixture finalizer

- ocs_ci/ocs/scale_noobaa_lib.py
- tests/e2e/scale/upgrade/test_upgrade_with_scaled_obc.py
- tests/e2e/scale/upgrade/test_upgrade_with_scaled_rgw_obc.py
Fixing scale [issue # 6942](https://github.com/red-hat-storage/ocs-ci/issues/6942):
* Using 2 different data files to store obc status
* Using separate namespace to create scaled obcs
> Fixing OBC bound list count mismatch

- tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
The pr fixes the following in the nodes restart tests for MS:
- In the test `test_osd_node_restart_and_check_osd_pods_status`, check that the osd pods are running when we have more than three worker nodes instead of checking the osd pods on the same node.
- In the test `test_nodes_restart`, restart only one node for the provider, so we don't lose quorum, and pick the node/s randomly.
- Delete the test `test_rolling_provider_worker_nodes_restart` and include it in the existing test `test_rolling_nodes_restart`.
> Fix test nodes restart for MS

- ocs_ci/ocs/resources/pod.py
- tests/manage/z_cluster/nodes/test_rolling_shutdown_and_recovery_ms.py
The pr implemented the following:
- Update the test "test_rolling_shutdown_and_recovery_in_controlled_fashion" to use `SanityManagedService`.
- Generate nodes for a provider cluster using the function `generate_nodes_for_provider_worker_node_tests` in case it's a provider cluster
- Increase the timeout waiting for the pods to be ready in case of a provider cluster
> Generate nodes for provider cluster in the test "test_rolling_shutdown_and_recovery_in_controlled_fashion"

- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Skip the testcase test_nodereplacement_twice which is not relevant for Managed Services.
> Skip the testcase test_nodereplacement_twice in MS

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/mcg_ui.py
- ocs_ci/ocs/ui/views.py
- tests/manage/mcg/ui/test_mcg_ui.py
Adjust test test_obc_creation_and_deletion for 4.12 and add new functionality ~~so BZ #2097772 is covered~~
Description:
now test is runnable for 4.12
test is splited to deletion via "three_dots" and via "Actions"
> test_obc_creation_and_deletion fix

- tests/ecosystem/upgrade/test_logging_upgrade.py
issue- https://github.com/red-hat-storage/ocs-ci/issues/6610
> Skiping the logging upgrade tyestcase due to changes in upgrade process

- tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
Skip the test 'test_check_pods_status_after_node_failure' when using MS because the functionality in the test is not relevant to the Managed Service.
> Skip the test 'test_check_pods_status_after_node_failure' when using MS

- ocs_ci/cleanup/aws/cleanup.py
Destroy AWS cluster base on cluster name
```
aws-cleanup --cluster-name <cluster-name> --force
```
> AWS cleanup via aws-cleanup

- ocs_ci/ocs/cluster.py
> In the function "wait_for_silence_ceph_osd_crash_warning" change the exception from "TimeoutError" to "TimeoutExpiredError"

- ocs_ci/ocs/resources/pod.py
Fixes: #5463
This change allows running md5sum regardless of which type of shell is installed on the pod, as long as it's available in the desired path.
This should be compatible with all platforms, but testing on platforms other than vSphere is still needed to confirm.
Signed-off-by: Sagi Hirshfeld <shirshfe@redhat.com>
> Change pod.py::cal_md5sum to use oc exec instead of oc rsh

- tests/manage/monitoring/conftest.py
Fixes #7071
rsh to toolpod is more vulnerable than `oc get pod <args>`, decision to replace it when unnecessary
> replaced rsh to tool-pod with get_osd_pods

- tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
In the test_pvc_clone_performance test, multiple files test cases: the files number in pvc/clones should be reduced to half due to bz2101874.
> Reducing number of files

- ocs_ci/ocs/ui/deployment_ui.py
We did not click on `Refresh Page`. So I increased the timeout and add "manual refresh"
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6963/testReport/tests.ecosystem.deployment/test_deployment/test_deployment_2/
http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-267vuf1cs36-t4a/j-267vuf1cs36-t4a_20230223T011221/logs/ui_logs_dir_1677117064/screenshots_ui/test_deployment/2023-02-23T01-55-04.155443.png
> Increase timeout of "refresh pop-up"

- tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
> Skip test_check_pod_status_after_two_nodes_shutdown_recovery for External mode

- tests/manage/z_cluster/test_ceph_default_values_check.py
With MCG only deployment we dont check ceph values, Hence this test is skipped. This fixes issue #7100
> Skipping "test_check_mds_cache_memory_limit" for MCG only deployment

- ocs_ci/helpers/performance_lib.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/perftests.py
- tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
This PR contains the following enhancements: 
1) Free ceph capacity calculation is added and the PVC/clones sizes are calculated by diving the free capacity be the required number of maximal PVCs in the cluster ( instead of the total capacity) 
2) Teardown problems should be resolved  
3) Added retries to overcome network glitches during which the test is unable to read data from logs.
> Ypersky multi clones used capacity enhancement

- ocs_ci/ocs/hsbench.py
- tests/e2e/scale/noobaa/test_hsbench.py
Fixed: # [6974](https://github.com/red-hat-storage/ocs-ci/issues/6974)
Added _get_bucket_name() method to query the bucket name.
> Add _get_bucket_name() method to query the bucket name

- ocs_ci/ocs/rados_utils.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/utility/memory.py
- ocs_ci/utility/utils.py
- tests/conftest.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/7140
Commit fixes the test tests/manage/z_cluster/test_ceph_pg_log_dups_trim.py::TestCephPgLogDupsTrimming::test_ceph_pg_log_dups_trim
and 'oc cp' to the pod references.
Due to implemented https://url.corp.redhat.com/RHSTOR-3411 task 'tar', 'yum' utilities were remove from ceph pods to trim an image size.
oc cp command depends on 'tar' utility, see https://linuxhint.com/use-kubectl-cp-command/ and oc cp --help
!!!Important Note!!!
Requires that the 'tar' binary is present in your container
image. If 'tar' is not present, 'oc cp' will fail.
therefore it fails, hence func copy_to_pod_cat and copy_from_pod_oc_exec added to the framework.
Copy to rook-ceph-osd with oc rsync also fails with error:
WARNING: cannot use rsync: rsync not …
> Fix test_ceph_pg_log_dups_trim. Replace oc cp calls (Updated)

- ocs_ci/helpers/helpers.py
- tests/manage/pv_services/test_ceph_capacity_recovery.py
This PR is a fix following https://github.com/red-hat-storage/ocs-ci/issues/7195  and https://github.com/red-hat-storage/ocs-ci/issues/7200. 
The changes which are implemented: 
- added retries for pulling perf image. 
- added skip for disconnected cluster
- added skip for external cluster
> test_ceph_capacity_recovery.py - adding retries for pulling perf image, adding skips for external and disconnected clusters 

- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
The pods mgr, mon, osd and mds are not present in external cluster. So the test cases given below are skipped in external mode cluster.
```
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py::TestResourceDeletionDuringMultipleDeleteOperations::test_disruptive_during_pod_pvc_deletion_and_io[CephBlockPool-mgr]
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py::TestResourceDeletionDuringMultipleDeleteOperations::test_disruptive_during_pod_pvc_deletion_a nd_io[CephBlockPool-mon]
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py::TestResourceDeletionDuringMultipleDeleteOperations::test_disruptive_during_pod_pvc_deletion_and_io[CephBlockPool-osd] …
```
> Skip test_resource_deletion_during_pvc_pod_deletion_and_io tests in external mode

- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Increase the timeout value waiting for pod to reach the state Running in the test given below.
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py::TestResourceDeletionDuringCreationOperations::test_resource_deletion_during_pvc_pod_creation_and_io 
Fixes #7136
> Increase wait time for pod to reach running state

- ocs_ci/helpers/helpers.py
This fixes issue https://github.com/red-hat-storage/ocs-ci/issues/6806. Added a function ("check_cluster_is_compact") to check for compact mode in helpers.py and increased PVCs to go to bound state from 60s to 180s
> Increasing the timeout for checking PVC status of compact mode clusters

- tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
- tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
Fix the test cases given below to run on external mode cluster.
1. tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py::TestResourceDeletionDuringPvcClone::test_resource_deletion_during_pvc_clone
2. tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py::TestResourceDeletionDuringSnapshotRestore::test_resource_deletion_during_snapshot_restore
Add osd and mgr to the list "pods_to_delete" only if the cluster is not external mode.
Fixes #7191 
Fixes #7192
> Fix tests to run on external mode

- ocs_ci/ocs/rados_utils.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/utility/utils.py
Fixes #7263
exec_cmd has **kwargs param. We may use shell=True instead of having use_shell param. Having additional param with same sense is a point of failure for existing and future code
> Remove redundant use_shell from exec_cmd

- tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Update the test tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py to get the actual replica size of the pool.
This change will also fixes #6985 
> Get the actual replica size of pool in test

- ocs_ci/ocs/scale_noobaa_lib.py
- tests/e2e/scale/upgrade/test_upgrade_with_scaled_obc.py
- tests/e2e/scale/upgrade/test_upgrade_with_scaled_rgw_obc.py
Fixing scale issue # 6942:
Using 2 different data files to store obc status
Using separate namespace to create scaled obcs
> Fixing OBC bound list count mismatch (#7021)

- ocs_ci/ocs/bucket_utils.py
Currently, if we reach timeout expiration, then we get the following unhelpful message in RP:
```
Message: TypeError: init() missing 1 required positional argument: 'value'
Type: None
``` 
The reason is that's we're attempting to raise the class of the exception instead of an instance of it:
```
...
...
if not sample.wait_for_func_status(result=True):
logger.error(f"Backing Store {backingstore_name} never reached OPTIMAL state")
raise TimeoutExpiredError
...
...
```
> Fix the use of TimeoutExpiredError in `bucket_utils.py::wait_for_pv_backingstore`

- .readthedocs.yml
> Temporarily disable all format generation for readthedocs

- ocs_ci/framework/__init__.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/managedservice.py
- ocs_ci/utility/utils.py
- tests/managed-service/test_switch_to_correct_index_at_setup.py
fix https://github.com/red-hat-storage/ocs-ci/issues/6881.
The purpose of the pr is to fix the problem described in the issue above.
In the pr, I implemented a functionality to switch to the correct cluster index at the test setup.
I had three goals in the implementation:
1. Stability - means that we can be sure that in every test, it switches to the correct cluster index in the setup method. That's why I preferred creating a function `check_switch_to_correct_cluster_at_setup`, rather than a fixture or decorator.
2. Clean - means that we have a minimum change in the tests. That's why the change is implemented only in the `setup` method and not in the test methods.
3. Easy to analyze - we can quickly look at the test runs and see if the cluster was a provider, consumer, or non-MS cluster …
> Switch to the correct cluster index at setup

- tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
This PR handles occasional teardown problems by adding teardown factory .
Furthermore, the creation of pod factory and pvc factory was abondoned, in order not to exceed memory usage due to objects.
> Test pvc multi snapshot performance - increasing timeout for pod deletion

- requirements.txt
The v0.2.0 is ~2 months old and doesn't contain important fixes like: https://gitlab.com/mbukatov/ocp-network-split/-/issues/14
> use new version of ocp-network-split - v0.3.0

- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
This will resolve https://github.com/red-hat-storage/ocs-ci/issues/7199
> Skip test_automated_recovery_from_stopped_node_and_start for external mode

- ocs_ci/cleanup/aws/cleanup.py
AWS_UPI cluster can be deleted via cli.
Without this fix, only AWS_IPI can be deleted via CLI.
```
aws-cleanup --cluster-name <cluster-name> --force
```
> Fix aws cleanup via cli

- tests/manage/pv_services/test_overprovision_level_policy_control.py
https://bugzilla.redhat.com/show_bug.cgi?id=2158277#c14
Bug - `[odf 4.10] - overprovisionControl- Added "ocs-" prefix to cluster resource quota name` fixed so we need to delete the WA.
> test_over_provision_level_policy_control [BZ-2158277 Fixed]

- ocs_ci/helpers/dr_helpers.py
- ocs_ci/ocs/dr/dr_workload.py
- tests/disaster-recovery/regional-dr/test_failover.py
- tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
Few enhancements for RDR tests
- Added checks for OCS pods and Ceph health after nodes power ON in failover tests
- Added validation for PV deletion
- Added validation for backend RBD image deletion 
Related bugs for above enhancements
-  [2140550](https://bugzilla.redhat.com/show_bug.cgi?id=2140550)
-  [2155976](https://bugzilla.redhat.com/show_bug.cgi?id=2155976)
> [RDR] Additional health checks, validation for PV and backend image deletion

- ocs_ci/framework/pytest_customization/marks.py
- pytest.ini
- tests/disaster-recovery/__init__.py
- tests/disaster-recovery/regional-dr/conftest.py
- tests/disaster-recovery/regional-dr/test_failover.py
- tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
- tests/disaster-recovery/regional-dr/test_relocate.py
Update RDR tests to use existing markers and filter out when running on non RDR cluster.
> Update markers for RDR tests

- ocs_ci/ocs/ui/mcg_ui.py
- ocs_ci/ocs/ui/views.py
- tests/manage/mcg/ui/test_mcg_ui.py
cherry-pick from [#7386](https://github.com/red-hat-storage/ocs-ci/pull/7386)
1. add cloud vers support for test_obc_creation_and_deletion
2. added a test to support ocs-storagecluster-ceph-rgw Storage Class
> 4.12. Cherry-pick. test_obc_creation_and_deletion added RGW sc

- ocs_ci/ocs/resources/namespacestore.py
Fixes: #7358
The "Gi" units were hard coded since this is one of the function's assumptions:
```
def template_pvc(
name,
namespace=config.ENV_DATA["cluster_namespace"],
storageclass=constants.CEPHFILESYSTEM_SC,
access_mode=constants.ACCESS_MODE_RWX,
size=20,
):
"""
Create a PVC using the MCG CLI
Args:
name (str): Name of the PVC
namespace (str): Namespace to create the PVC in
access_mode (str): Access mode for the PVC
size (str): Size of the PVC in GiB
"""
```
Once merged we need to backport this to 4.12, 4.11 and 4.10.
> Fix `template_pvc` to specify the PVC's capacity units

- ocs_ci/helpers/dr_helpers.py
Fixes: #7492 
Remove workaround: Scaling down the RBD mirror daemon deployment on failoverCluster
> Remove workaround of scaling down the RBD mirror daemon 

- tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
Addressing the issue 
Message: failed on setup with "IndexError: list index out of range"
Type: None
Text:
measurement_dir = '/tmp/pytest-of-jenkins/pytest-0/measurement_results'
threading_lock = <unlocked _thread.lock object at 0x7f1e59e67b10>
@pytest.fixture
def measure_stop_ceph_osd(measurement_dir, threading_lock):
"""
Downscales Ceph osd deployment, measures the time when it was
downscaled and alerts that were triggered during this event.
Returns:
dict: Contains information about `start` and `stop` time for stopping
Ceph osd pod
"""
oc = ocp.OCP(
kind=constants.DEPLOYMENT,
namespace=config.ENV_DATA.get("cluster_namespace"),
threading_lock=threading_lock,
)
osd_deployments = oc.get(selector=constants.OSD_APP_LABEL).get("items")
osds = [deployment.get("metadata").get("name") for …
> external mode does not have osds, add skip-mark

- ocs_ci/framework/pytest_customization/marks.py
- tests/ui/test_non_admin_user.py
- tests/ui/test_validation_ui.py
skip IBM cloud managed - cherry pick
Reason:
https://url.corp.redhat.com/ibm-managed
> Skip ui tests for IBM cloud deployment. Cherry-pick 4.12

- ocs_ci/framework/pytest_customization/marks.py
- tests/ui/test_non_admin_user.py
- tests/ui/test_validation_ui.py
skip IBM cloud managed - cherry pick
Reason:
https://url.corp.redhat.com/ibm-managed
> Skip ui tests for IBM cloud deployment. Cherry-pick 4.10

- ocs_ci/framework/pytest_customization/marks.py
- tests/ui/test_non_admin_user.py
- tests/ui/test_validation_ui.py
skip IBM cloud managed - cherry pick
Reason:
https://url.corp.redhat.com/ibm-managed
> Skip ui tests for IBM cloud deployment. Cherry-pick 4.11

- ocs_ci/framework/pytest_customization/marks.py
- tests/ui/test_non_admin_user.py
- tests/ui/test_validation_ui.py
skip IBM cloud managed - cherry pick
Reason:
https://url.corp.redhat.com/ibm-managed
> Skip ui tests for IBM cloud deployment. Cherry-pick 4.9

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/aws.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
- tests/manage/z_cluster/nodes/test_rolling_shutdown_and_recovery_ms.py
Fix issue https://issues.redhat.com/browse/ODFMS-326.
When shutting down a worker node using MS, the node usually goes into a Terminating state.
The current "stop nodes" MS tests expect the node to reach the status stopped(and not terminated). This can cause the following error: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-odf-multicluster/1600/testReport/tests.manage.z_cluster.nodes.test_rolling_shutdown_and_recovery_ms/TestRollingWorkerNodeShutdownAndRecoveryMS/test_rolling_shutdown_and_recovery_in_controlled_fashion_provider_/.
To fix the issue above, I implemented the following:
- Add new functionality to wait for stop and terminate nodes. This functionality implemented in the pr is currently for the AWS platform. But it can be extended later to the other …
> Add new functionality to wait for stop and terminate nodes

- ocs_ci/framework/main.py
Issue: When we run n+1 OCP version with ODF n version, SC was initialized before loading of OCP version.
> Load ocp version in the main module in release 4.12

- ocs_ci/ocs/fusion.py
Remove spaces from onboarding ticket string if present while creating managedfusionoffering DFC.
> Remove spaces from onboarding ticket string if present while creating managedfusionoffering DFC

- ocs_ci/deployment/fusion_aas.py
- ocs_ci/helpers/sanity_helpers.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/defaults.py
- ocs_ci/ocs/fusion.py
- ocs_ci/ocs/resources/storage_cluster.py
- tests/ecosystem/deployment/test_deployment.py
Update post installation checks to support FaaS consumer cluster.
1. Checks which require tools pods are skipped because tools pod is not available in consumer cluster. This will be updated when there is a solution to check ceph commands from consumer.
2. Updated deploy_ocs function in ocs_ci/deployment/fusion_aas.py to skip ocs install if managedfusionoffering is present instead of checking cehph cluster.
3. OCS operator, storagecluster, cephcluster will not be present in FaaS consumer cluster. Checks related to this will be skipped.
4. Added verification of pods in managed-fusion namespace.
> Fix post install verification for FaaS consumer

- ocs_ci/deployment/fusion_aas.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/helpers/managed_services.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/resources/storage_cluster.py
Creted new functions for FaaS provider and consumer verification.
Movied the verification of pods in managed-fusion namespace to the new function.
Verify security in ocs-client-operator pod on consumer.
Verifiy storage client on consumer.
Consumer:
1. Verify CSV phase
2. Verify client endpoint
Provider:
1. Verify CSV phase
2. Verify ocs-provider-server pod is Running
4. Verify that Cephcluster is Ready and hostNetworking is True
5. Verify that the security groups are set up correctly
> Post installation verifications for FaaS

- ocs_ci/ocs/resources/namespacestore.py
4.11 Cherry pick of #7359. 
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/7358
> [Release-4.11 cherry pick] Fix template_pvc to specify the PVC's capacity units

- ocs_ci/ocs/resources/objectbucket.py
This fixes #6849 But we may have to monitor the test run for couple of runs since failure observed in #6849 is not consistent.
> Fixes purge bucket with versioning at the teardown of test_versioning_parallel_ops #6849

- tests/conftest.py
Fixes: #7240
PR #6124 added `deploy_pod_status=status` when calling `create_pod()` in pod_factory_fixture
The status value which it was being set is same as other pods desired status (constants.STATUS_RUNNING).
This assumption that deploy pod status will be same as other pod status is not True and appears that it was added by mistake.
Also see this example output from ODF 4.13 setup where deploy pod goes to Completed state:
```
pod-test-cephfs-ed710c8134b6414ba84a2ff5-1-75rbh    1/1     Running     0          91s
pod-test-cephfs-ed710c8134b6414ba84a2ff5-1-deploy   0/1     Completed   0          92s
pod-test-rbd-2aaee60d8d0840d9a146af0e7d8-1-4p2pk    1/1     Running     0          29s
pod-test-rbd-2aaee60d8d0840d9a146af0e7d8-1-deploy   0/1     Completed   0          30s
```
Hence removing …
> Fix deploy pod status value for DeploymentConfig workload in pod_factory_fixture

- tests/manage/mcg/test_admission_control.py
> [Release-4.12 cherry pick] Fix the expeced error for test_namespacestore_creation_webhook[Empty secret name]

- ocs_ci/deployment/fusion_aas.py
- tests/manage/pv_services/test_pvc_assign_pod_node.py
Skip access token check in test_pvc_assign_pod_node if platform is FaaS. ODF operator pod won't be present in FaaS consumer cluster.
Fixes #7639
> Skip access token check in test_pvc_assign_pod_node if platform is FaaS

- ocs_ci/ocs/node.py
This fixes https://github.com/red-hat-storage/ocs-ci/issues/7086
> Adding try except block in function "wait_for_nodes_status" to ignore "CommandFailed" exception

- tests/manage/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py
Added ignore_leftovers to test_ceph_csidriver_runs_on_non_ocs_nodes testcase to avoid ResourceLeftoversException.
> Added ignore_leftovers to avoid ResourceLeftoversException

- conf/ocsci/README.md
- ocs_ci/deployment/aws.py
- ocs_ci/deployment/disconnected.py
- ocs_ci/deployment/ibmcloud.py
- ocs_ci/deployment/install_ocp_on_rhel.py
- ocs_ci/deployment/ocp.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/ocs/resources/mcg.py
- ocs_ci/utility/utils.py
This patch will allow overwriting the DATA_DIR, which was hardcoded in the code, 
this will allow us to better use this image in the Openshift-CI tests.
See this log for example, 
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/39363/rehearse-39363-periodic-ci-RedHatQE-interop-testing-main-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412/1658776923427311616/artifacts/cnv-odf-tests-aws-upi-ocp412/interop-tests-ocs-tests/build-log.txt
Verified: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/39363/rehearse-39363-periodic-ci-RedHatQE-interop-testing-main-ocp-cnv-odf-4.12-cnv-odf-tests-aws-upi-ocp412/1658854402775060480/artifacts/cnv-odf-tests-aws-upi-ocp412/interop-tests-ocs-tests/build-lo …
> Allow to overwrite DATA_DIR via environment variable

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/mcg_ui.py
- ocs_ci/ocs/ui/views.py
- tests/manage/mcg/ui/test_mcg_ui.py
This is cherry-pick from stable branch (4.13)
during black squad analysis of ODF 4.12 run it was found that we need locators for version 4.13 as some of the tests depend on OCP_version, thus they fail to find locators in views.py when running on OCP 4.13 & ODF 4.12. It is also applicable for upgrade scenarios, so we always should have locators for further version ready.
FIX: https://github.com/red-hat-storage/ocs-ci/issues/7509 for ODF 4.12
FIX: https://github.com/red-hat-storage/ocs-ci/issues/7486 for ODF 4.12
FIX: https://github.com/red-hat-storage/ocs-ci/issues/7605
> cherry-pick for obc_create test, page_has_loaded improve, locators 4.13 for depl 4.12

- ocs_ci/utility/service.py
Adding StrictHostKeyChecking=no while performing operations on kubelet service inside the node.  
Signed-off-by: Aaruni Aggarwal [aaruniagg@gmail.com](mailto:aaruniagg@gmail.com)
> Adding StrictHostKeyChecking=no while doing ssh into the node for IBM Power

- ocs_ci/ocs/scale_lib.py
Observed most of the Azure runs failed to add node in 600sec due to this increased the timeout to 900sec since part of machineset creation node add passed within 900sec.
> Increased timeout to add node to 900sec after machineset creation

- ocs_ci/ocs/constants.py
- tests/conftest.py
Ignore must-gather-helper in environment check.
> Release 4.10 cherry pick PR 7539

- ocs_ci/ocs/constants.py
- tests/conftest.py
Ignore must-gather-helper in environment check.
> Release 4.11 cherry pick PR 7539

- tests/conftest.py
In the environment_checker function, add get_status_after_execution as finalizer only if get_status_before execution is enabled.
Fixes #7689
> Add get_status_after_execution as finalizer only if get_status_before execution is enabled

- tests/disaster-recovery/regional-dr/test_sequential_failover.py
- tests/disaster-recovery/regional-dr/test_sequential_relocate.py
Increase the number of workloads from 3 to 5 in sequential failover, relocate tests
> Increase the number of workloads in sequential failover, relocate tests

- ocs_ci/ocs/node.py
fix https://github.com/red-hat-storage/ocs-ci/issues/7086
> Adding try except block in function "wait_for_nodes_status" to ignore "CommandFailed" exception release-4.12 (#7451)

- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
> remove wait parameter in stop_node since its not exists on all platforms

- ocs_ci/helpers/managed_services.py
- ocs_ci/ocs/resources/storage_cluster.py
Fix the check for storageclassclaims and storageclass in FaaS consumer install verification.
Moved the storageclient check before storageclass check because the storage client should be verified first.
The check for storageclassclaim is updated. Retry is required because the storageclassclaim won't be in Ready state immediately after the storageclient is connected.
Fixes #7693
> Fix the check for storageclassclaims and sc in FaaS consumer

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/mcg_ui.py
- ocs_ci/ocs/ui/views.py
- tests/ui/test_error_improvements.py
Tests cover error message improvements feature https://issues.redhat.com/browse/RHSTOR-4117  for Bucket class name, NamespaceStore name, System storage class name, Object bucket claim name, Blocking pool name, Backing store name.
Tests are UI only.
Known bug fails the test run - https://bugzilla.redhat.com/show_bug.cgi?id=2193109
Multiple tests performed to evaluate performance with given boundary values for the input rules:
OBC
'No more than 253 characters											
'Starts and ends with a lowercase letter or number					
'Only lowercase letters, numbers, non-consecutive periods, or hyphens	
'Cannot be used before												
Backing store
No more than 43 characters											
Starts and ends with a lowercase letter or number					
Only lowercase letters, numbers, non-consecutive periods, …
> test error message improvements for name inputs. new feature

- ocs_ci/templates/CSI/addons/ReclaimSpaceCronJob.yaml
- ocs_ci/templates/CSI/addons/ReclaimSpaceJob.yaml
- ocs_ci/templates/CSI/addons/volumeReplicationCR.yaml
- ocs_ci/templates/CSI/addons/volumeReplicationClass.yaml
- tests/e2e/system_test/test_cr_resources_validation.py
This PR implements the following: 
1) Refactoring the existing code to make a function called with different parameters for different resources
2) Network fence and reclaim space cron job are made different testcases
3) Changing resources names in the yaml files to meaningful ones. 
Please note that changing an exiting cr ( oc edit ...) is done the following way: 
For each property that should be tested for editability, a temporary shell file is created and the appropriate 'oc patch' command is written into it. Then this file is run and the command is executed. I tried different approaches and this one seems to be the only one that works.
> Adding reclaim space cron job tc and refactoring

- ocs_ci/ocs/constants.py
- tests/conftest.py
- tests/manage/rgw/test_bucket_creation.py
- tests/manage/rgw/test_bucket_deletion.py
- tests/manage/rgw/test_multipart_upload.py
- tests/manage/rgw/test_object_integrity.py
Fixes: #7024
Since 4.7 the RGW service is exposed by default, and after the recent fix of https://url.corp.redhat.com/0769663 in 4.13 
there shouldn't be any issues using this default HTTP endpoint
> Remove the `rgw_endpoint` fixture

- ocs_ci/templates/workloads/fio/fio_dc.yaml
Add 2 environment variables to suppress debconf messages
Fixes: #7711 
```
WARNING  - Command stderr: debconf: delaying package configuration, since apt-utils is not installed
```
> Update fio_dc.yaml - to suppress debconf messages | Fixes: #7711

- ocs_ci/helpers/managed_services.py
Fix the verification of onboardingValidationKey in FaaS provider cluster.
The fix is required due to the change in the structure of ManagedFusionOffering CR.
> Fix the verification of onboardingValidationKey

- ocs_ci/ocs/cluster.py
- tests/manage/z_cluster/nodes/test_nodes_restart.py
fix #7737 
In the pr, I implemented the following:
- Run the tests `test_nodes_restart` and `test_rolling_nodes_restart` with vSphere IPI.
- Adjust the test `test_nodes_restart` to run on vSphere IPI.
- Still skip the tests `test_pv_provisioning_under_degraded_state_stop_provisioner_pod_node`, `test_pv_provisioning_under_degraded_state_stop_rook_operator_pod_node` because with vSphere IPI when stopping a node it behaves differently. We may reimplement them in the future if necessary.
> Run the nodes restart tests with vSphere IPI

- tests/manage/z_cluster/test_delete_osd_deployment.py
> In the test "test_delete_rook_ceph_osd_deployment" ignore the "rook-ceph-osd" labels in the leftovers

- tests/conftest.py
> Check for an existing pod before calling `awscli_pod_fixture`, and leverage the retry decorator in it

- ocs_ci/ocs/resources/mcg.py
In 4.14 the URL that was used to make NooBaa RPC requests has been removed, so this PR adjusts the method that was used to make these calls, so it uses the NooBaa CLI instead.
See this google chat thread for details:
https://url.corp.redhat.com/c4c3508
> Adjust send_rpc_query to send RPC requests via the NooBaa CLI

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/mcg_ui.py
- ocs_ci/ocs/ui/views.py
FIXES: #7743
added an optional argument to page_has_loaded.
Should not affect on tests using method page_has_loaded and not using module_loc as it still uses default root HTML loc ("html", By.TAG_NAME)
> BaseUI: added module_loc to page_has_loaded

- ocs_ci/ocs/ui/base_ui.py
- tests/ui/test_quickstarts.py
FIXES: https://github.com/red-hat-storage/ocs-ci/issues/7547
quickstarts titles were changed for ODF 4.13
navigate_overview_page fixed
> Fix  test_quickstart_presence ODF 413

- tests/e2e/system_test/test_cr_resources_validation.py
1) This PR contains a new test case for VolumeReplication CR edit 
2) In order to support creation of CR in other than openshift-storage namespace the cr_resource_not_editable function was enhanced. 
3) This PR also contain fixes of remarks by Karthick from previous pr https://github.com/red-hat-storage/ocs-ci/pull/7593
> Adding a new test case for VolumeReplication CR edit 

- tests/manage/z_cluster/test_delete_osd_deployment.py
> In the test "test_delete_rook_ceph_osd_deployment" ignore the "rook-ceph-osd" labels in the leftovers #7790

- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/7216
> Skipping 'test_pdb_check_simultaneous_node_drains' for more than three worker nodes

- ocs_ci/ocs/node.py
fix https://github.com/red-hat-storage/ocs-ci/issues/7086
> Adding try except block in function "wait_for_nodes_status" to ignore "CommandFailed" exception release-4.10 (#7451)

- tests/manage/mcg/conftest.py
MCG tests were skipped in MS test runs. With the new name of the platform for FaaS, the MCG test skip condition required update to include FaaS platform config name as well.
> Skip mcg tests in FaaS test runs

- tests/manage/z_cluster/nodes/test_toleration.py
This fixes https://github.com/red-hat-storage/ocs-ci/issues/7857
> Increasing 'wait_for_pods_to_be_running' timeout to address intermittent failures in test_toleration.py

- tests/conftest.py
UI tests were skipped in MS test runs. With the new name of the platform for FaaS, the UI test skip condition required update to include FaaS platform config name as well.
> Skip UI tests in FaaS test runs

- tests/managed-service/test_post_installation_state.py
Added runs_on_provider marker in the test cases given below.
1)tests/managed-service/test_post_installation_state.py::TestPostInstallationState::test_provider_server_logs
2)tests/managed-service/test_post_installation_state.py::TestPostInstallationState::test_ceph_clients
Fixes #7886
> Add runs_on_provider marker in MS tests

- tests/manage/mcg/test_nsfs.py
> Ignore the noobaa-endpoint pods leftovers at `test_nsfs.py` 

- tests/manage/mcg/test_kms.py
Fixes: #7659
Looking for "setKMSConditionType <KM type>" should be sufficient, based on the printed logs from past runs and the following code from the noopaa-operator project:
https://github.com/noobaa/noobaa-operator/blob/b45e8b619bca06f91586fdbd523ecbcf55203824/pkg/system/phase2_creating.go#LL830C1-L852C1
And since we're specifying this type under ENV_DATA.KMS_PROVIDER in our conf files, looking for `setKMSConditionType + config.ENV_DATA["KMS_PROVIDER"]` should work for both of the current KM providers as well as future ones.
> `test_noobaa_kms_validation`: Remove the use of RE and generalize the search based on environment config

- conf/ocsci/vsphere_disable_custom_sc_in_deployment.yaml
- ocs_ci/deployment/vmware.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/templates/ocs-deployment/storageclass_thin-csi-odf.yaml
Description:
Since OCP deployment comes with thin-csi as default SC and it has StoragePolicyName as "openshift-storage-policy-<clustername>". ODF deployment uses thin-csi for deployment which inturn creaes RAID 1 disks for osd and mon. To save storage on vSphere, create new SC which has same param as thin-csi and use that for ODF deployment.
> use SC with vSAN Default Storage Policy as default for ODF deployment

- ocs_ci/deployment/flexy.py
- if disconnected deployment using flexy fails before the OCP cluster deployment start (e.g. during images mirroring), the metadata.json file is not created and Destroy job is not properly triggered. This change ensures that at least empty metadata.json file exists and full Destroy job is properly triggerd and all resources are cleaned up.
> discon. cl.: ensure that metadata.json file exists

- tests/e2e/conftest.py
- this fixes issue in PR#7862 - `fspath` contains path to the file with tests, not the test name
- also the original condition in the code `if testname in str(item....)` would remove also tests with partial match - e.g. `test_foo` testname will match also with `test_foo_bar` test.
> fix removal of MS tests from skiped list

- ocs_ci/ocs/scale_lib.py
- tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Enhanced PVC creation and Ceph POD respin test to use kube_job obj way of creating PVCs and PODs, with factory objs observed script is using lot of memory also there were lot of kill messages in logs, with this enhancement memory issue should not be hit.
> Enhance PVC creation to use kube_job which avoids memory issue

- ocs_ci/ocs/scale_noobaa_lib.py
- tests/e2e/scale/noobaa/test_scale_obc_start_time_respin_noobaa_pods.py
Created OBC without I/O running
Created OBC with I/O using mcg_job_factory()
Reset node which Noobaa pod is running on, then measure the startup time when Noobaa pod reaches Running state
>  Scale test obc_start_time_respin_noobaa_pods

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/disconnected.py
- ocs_ci/utility/deployment.py
- moving `get_and_apply_icsp_from_catalog()` to `ocs_ci/utility/deployment.py` to avoid circular imports
- fixes: https://github.com/red-hat-storage/ocs-ci/issues/8103
> Disconnected ODF deployment: apply icsp rules when mirroring images

- tests/manage/mcg/test_pv_pool.py
bug: https://bugzilla.redhat.com/show_bug.cgi?id=2189866
**Need backports?**
no backports needed
> Test if access_key or secret_key details are found in pv pool backingstore pod

- ocs_ci/ocs/fiojob.py
- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/resources/objectbucket.py
- ocs_ci/ocs/resources/packagemanifest.py
- ocs_ci/ocs/tests/test_fiojob.py
- ocs_ci/ocs/ui/odf_topology.py
- ocs_ci/utility/utils.py
remove flake8 errors from tox logs
tox: flake8
flake8: commands[0]> flake8 ocs_ci tests
ocs_ci/ocs/fiojob.py:175:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
ocs_ci/ocs/ocp.py:1309:55: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
ocs_ci/ocs/resources/objectbucket.py:185:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
ocs_ci/ocs/resources/objectbucket.py:187:14: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
ocs_ci/ocs/resources/packagemanifest.py:75:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use …
> Fix for the common tox issue: 'isinstance instead of type(obj) == type'

- ocs_ci/ocs/constants.py
- backport of https://github.com/red-hat-storage/ocs-ci/pull/7437
- related to: https://issues.redhat.com/browse/ONEOCPDEPL-210
> change FLEXY_IMAGE_URL to images.paas.redhat.com - backport for 4.12

- ocs_ci/ocs/constants.py
- backport of https://github.com/red-hat-storage/ocs-ci/pull/7437
- related to: https://issues.redhat.com/browse/ONEOCPDEPL-210
> change FLEXY_IMAGE_URL to images.paas.redhat.com - backport for 4.11

- ocs_ci/ocs/constants.py
- backport of https://github.com/red-hat-storage/ocs-ci/pull/7437
- related to: https://issues.redhat.com/browse/ONEOCPDEPL-210
> change FLEXY_IMAGE_URL to images.paas.redhat.com - backport for 4.10

- ocs_ci/ocs/resources/mcg.py
Fixes #8109 
With this PR we extract the pull-secret (if not already present) from the pullsecret secret in openshift-config namespace and then place it under /data directory
> Extract the pull-secret and place it under /data dir

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/disconnected.py
- ocs_ci/utility/deployment.py
- moving get_and_apply_icsp_from_catalog() to ocs_ci/utility/deployment.py to avoid circular imports
backporting https://github.com/red-hat-storage/ocs-ci/pull/8106
> Disconnected ODF deployment: apply icsp rules when mirroring images - backport for 4.13

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/disconnected.py
- ocs_ci/utility/deployment.py
- moving get_and_apply_icsp_from_catalog() to ocs_ci/utility/deployment.py to avoid circular imports
backporting https://github.com/red-hat-storage/ocs-ci/pull/8106 and https://github.com/red-hat-storage/ocs-ci/pull/7855
> Disconnected ODF deployment: apply icsp rules when mirroring images - backport for 4.12

- tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py
The test case given below is updated to increase the wait for the deletion of voluke in the backend. This change is to fix #7880 which is an intermittent issue.
Test case :
tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py::TestDaemonKillDuringMultipleCreateDeleteOperations::test_daemon_kill_during_pvc_pod_creation_deletion_and_io
> Increase timeout for volume deletion in backend

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/disconnected.py
- ocs_ci/utility/deployment.py
- moving get_and_apply_icsp_from_catalog() to ocs_ci/utility/deployment.py to avoid circular imports
backporting https://github.com/red-hat-storage/ocs-ci/pull/8106, https://github.com/red-hat-storage/ocs-ci/pull/7855 and https://github.com/red-hat-storage/ocs-ci/pull/8166
>  Disconnected ODF deployment: apply icsp rules when mirroring images - backport for 4.11

- ocs_ci/ocs/cluster.py
- tests/encryption/test_mon_failure_in_intransit_encryption.py
Test case to ensure the proper functioning of mon failures with in-transit encryption.
Steps:
1. Ensure that in-transit encryption is enabled on the setup.
2. Scale down two mons.
3. Restart Mgr pod.
4. Sleep for 5 seconds.
5. Scale up mons.
6. Sleep for 10 seconds.
7. Wait for mgr pod to move to the running state.
8. Verify the in-transit encryption configuration after scaling up mons and restarting mgr pod.
> Test automation of mon failure scenarios with intransit encryption.

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/disconnected.py
- ocs_ci/utility/deployment.py
- moving get_and_apply_icsp_from_catalog() to ocs_ci/utility/deployment.py to avoid circular imports
backporting https://github.com/red-hat-storage/ocs-ci/pull/8106, https://github.com/red-hat-storage/ocs-ci/pull/7855 and https://github.com/red-hat-storage/ocs-ci/pull/8166
>  Disconnected ODF deployment: apply icsp rules when mirroring images - backport for 4.10

- ocs_ci/ocs/warp.py
- tests/e2e/scale/noobaa/test_warp.py
* Added multi_client=False to the run_benchmark function. Fixed warp test failing issue #7964
* Added multi_client to cleanup function.
> [Release 4.13 cherry-pick] Added multi_client=False to the run_benchmark function of warp (#7967)

- tests/ecosystem/upgrade/conftest.py
Fixes: #8072 
Required backports:
> Update the RPC payload at `test_buckets_before_upgrade`

- ocs_ci/ocs/fiojob.py
cherry-pick: https://github.com/red-hat-storage/ocs-ci/pull/7592
> [4.10] - get correct pool name for external mode in fiojob

- ocs_ci/ocs/fiojob.py
cherry-pick: https://github.com/red-hat-storage/ocs-ci/pull/7592
> [4.11] - get correct pool name for external mode in fiojob 

- ocs_ci/ocs/ui/base_ui.py
class constructor failing to return 'driver' attribute.
assumption is that python garbage collector deletes the driver when not referred for a long time .
fix creates SeleniumDriver class and sets the driver again if 'driver' attribute not found
FIXES: https://github.com/red-hat-storage/ocs-ci/issues/7859
Verified by specifically added test - https://github.com/red-hat-storage/ocs-ci/pull/8073
https://url.corp.redhat.com/no-driver-attribute
-> all failures analyzed, part of them caused by bad health of the cluster and another part anticipated to fail to check behavior and driver recreation for the test failure
need to be backported:
> 'SeleniumDriver' object has no attribute 'driver' - fix

- ocs_ci/ocs/ocs_upgrade.py
- on Disconnected cluster ICSP from ocs-registry image is not required/valid (there is created another ICSP pointing directly to the mirror registry)
> skip application of icsp from ocs-registry on disonnected cluster

- ocs_ci/ocs/ocs_upgrade.py
- on Disconnected cluster ICSP from ocs-registry image is not required/valid (there is created another ICSP pointing directly to the mirror registry)
backport of https://github.com/red-hat-storage/ocs-ci/pull/8212
>  skip application of icsp from ocs-registry on disonnected cluster - backport 4.12

- ocs_ci/ocs/ocs_upgrade.py
- on Disconnected cluster ICSP from ocs-registry image is not required/valid (there is created another ICSP pointing directly to the mirror registry)
backport of https://github.com/red-hat-storage/ocs-ci/pull/8212
>  skip application of icsp from ocs-registry on disonnected cluster - backport 4.11

- tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Added a platform check for nfs load balancer service as Ingress address is unavailable in loadbalancer service for vsphere. Which is used for out cluster mount testcases.
> updated setup teardown method for nfs testclass

- ocs_ci/deployment/disconnected.py
This is cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/8221
> Disconected deployment: extend time for mirroring images (for 4.10) - cherry-pick for 4.11

- ocs_ci/deployment/disconnected.py
```
2023-08-09 16:14:45  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2023-08-09 16:14:45  ocs_ci/deployment/deployment.py:318: in deploy_cluster
2023-08-09 16:14:45      self.do_deploy_ocs()
2023-08-09 16:14:45  ocs_ci/deployment/deployment.py:215: in do_deploy_ocs
2023-08-09 16:14:45      self.deploy_ocs()
2023-08-09 16:14:45  ocs_ci/deployment/deployment.py:1157: in deploy_ocs
2023-08-09 16:14:45      image = prepare_disconnected_ocs_deployment()
2023-08-09 16:14:45  ocs_ci/deployment/disconnected.py:414: in prepare_disconnected_ocs_deployment
2023-08-09 16:14:45      prune_and_mirror_index_image(
2023-08-09 16:14:45  ocs_ci/deployment/disconnected.py:176: in prune_and_mirror_index_image
2023-08-09 16:14:45      oc_acm_result = exec_cmd(cmd, …
```
> Disconected deployment: extend time for mirroring images (for 4.10)

- Docker_files/ocsci_container/Containerfile.ci
We are using make and kubectl for perf testing
https://github.com/cloud-bulldozer/benchmark-operator
https://github.com/cloud-bulldozer/benchmark-operator/blob/master/Makefile#L117
> Add kubectl and 'make' packages to ocs-ci image

- ocs_ci/ocs/ui/base_ui.py
Backport.
Fix case when SeleniumDriver exists and driver attribute not.
ISSUE: https://github.com/red-hat-storage/ocs-ci/issues/7859
> cherry-pick. SeleniumDriver attribute error fix

- conf/deployment/baremetal/upi_1az_rhcos_multus_cluster_nvme_intel_3m_3w.yaml
- conf/deployment/baremetal/upi_1az_rhcos_multus_nvme_intel_3m_3w.yaml
- conf/deployment/baremetal/upi_1az_rhcos_multus_public_nvme_intel_3m_3w.yaml
On our BM there are 2 NICs [1G,10G]
We need to work on 10G
```
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
name: public-net
namespace: openshift-storage
labels: {}
annotations: {}
spec:
config: '{ "cniVersion": "0.3.1", "type": "macvlan", "master": "enp1s0f1", "mode": "bridge", "ipam": { "type": "whereabouts", "range": "192.168.20.0/24" } }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
name: cluster-net
namespace: openshift-storage
labels: {}
annotations: {}
spec:
config: '{ "cniVersion": "0.3.1", "type": "macvlan", "master": "enp1s0f1", "mode": "bridge", "ipam": { "type": "whereabouts", "range": "192.168.30.0/24" } }'
```
In addition, I verified traffic on enp1s0f1: https://url.corp.redhat.com/4eaeddf
> Change network interface for multus deployment

- ocs_ci/utility/deployment.py
> make icsp unique to avoid conflict during upgrade

- ocs_ci/utility/deployment.py
Backport of https://github.com/red-hat-storage/ocs-ci/pull/8251
> make icsp name unique to avoid conflict during upgrade - backport for 4.13

- ocs_ci/utility/deployment.py
Backport of https://github.com/red-hat-storage/ocs-ci/pull/8251
> make icsp name unique to avoid conflict during upgrade - backport for 4.12

- ocs_ci/utility/deployment.py
Backport of https://github.com/red-hat-storage/ocs-ci/pull/8251
> make icsp name unique to avoid conflict during upgrade - backport for 4.11

- ocs_ci/utility/deployment.py
Backport of https://github.com/red-hat-storage/ocs-ci/pull/8251
> make icsp name unique to avoid conflict during upgrade - backport for 4.10

- ocs_ci/ocs/cluster.py
Description:
There are some corner scenarios like network issue which causes commands to fail. In that cases we are retrying the same based on decorator. In this case, we are getting pods and appending pod to global variable. So same object is appending to global variable multiple times and we are using length of that variable to verify the number of pods which causes incorrect numbers.
Fixes: #8229 
> Fixing incorrect pod count

- ocs_ci/utility/utils.py
- tests/libtest/test_stderr_emoji_filter.py
release-4.12 backport of https://github.com/red-hat-storage/ocs-ci/pull/8077
> [release-4.12 backport] Enhance exec_cmd to Include emoji filtering for stderr output

- ocs_ci/ocs/resources/mcg.py
- tests/manage/mcg/test_nb_mgmt_endpoint.py
In 4.14 RPCs are only possible via the MCG-CLI, but in #7795 we kept making RPCs against the noobaa-endpoint in lower versions just to keep covering the noobaa-mgmt route.
This PR separates the functionality issue from the coverage issue by introducing a dedicated test for the noobaa-mgmt route, and choosing to use the MCG-CLI for RPCs in all other cases.
> Choose to use only the MCG-CLI for RPC calls elsewhere

- ocs_ci/deployment/deployment.py
In external mode deployment, there is no MDS, MON and OSD pods, so there will no PDB's created.
Fixes: #8266 
> PDB verification skip for external mode

- ocs_ci/ocs/resources/objectbucket.py
Fixes: #8270
Required backports:
> Add an S3 readiness check to `ObjectBucket.verify_health`

- ocs_ci/utility/deployment.py
Back-port: https://github.com/red-hat-storage/ocs-ci/pull/8292
> [4.12]: MachineConfigPool skip for IBM Managed cloud

- ocs_ci/utility/deployment.py
Back-port: https://github.com/red-hat-storage/ocs-ci/pull/8292
> [4.11]: MachineConfigPool skip for IBM Managed cloud

- ocs_ci/ocs/resources/mcg.py
- tests/manage/mcg/test_nb_mgmt_endpoint.py
release-4.12 backport of https://github.com/red-hat-storage/ocs-ci/pull/7875
> [release-4.12 backport] Choose to use only the MCG-CLI for RPC calls elsewhere

- ocs_ci/ocs/resources/mcg.py
release-4.12 backport of https://github.com/red-hat-storage/ocs-ci/pull/8181
> [release-4.12 backport]Download the mcg-cli if the current binary has a different minor version than OCS

- ocs_ci/templates/mcg/s3cli-sts.yaml
release-4.13 backport of #8175
> [release-4.13 backport] s3cli-sts: runAsUser 0 with image 2.0

- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
…ated_recovery_from_stopped_node_and_start (#8341)
> [4.11] Wait for nodes to become ready to allow pods to come up in test_automated_recovery_from_stopped_node_and_start

- tests/manage/pv_services/pvc_snapshot/test_rbd_block_pvc_snapshot.py
Update the test case given below to add the parameter direct=1 in fio command.
tests/manage/pv_services/pvc_snapshot/test_rbd_block_pvc_snapshot.py::TestRbdBlockPvcSnapshot::test_rbd_block_pvc_snapshot
Fixes #8312
> Add fio parameter direct=1 in the test case test_rbd_block_pvc_snapshot

- ocs_ci/ocs/resources/storage_cluster.py
With the new ocs-qe-addon, we don't see the version of the ocs-storagecluster. See, for example, the error here https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/28929/console:
> 2023-08-31 19:19:47  16:19:47 - MainThread - ocs_ci.ocs.resources.storage_cluster - INFO  - Verifying storage cluster version
2023-08-31 19:19:47  16:19:47 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get StorageCluster ocs-storagecluster -n openshift-storage -o yaml
2023-08-31 19:19:48  FAILED
> 2023-08-31 19:19:48              log.info("Verifying storage cluster version")
2023-08-31 19:19:48  >           storage_cluster_version = …
> Ignore the post-validation storagecluster version keyError when using MS

- conf/README.md
- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/utility/ssl_certs.py
* ssl_cert: add function configure_trusted_ca_bundle
- separate configuration of cluster-wide trusted CA bundle in Proxy object to new function (and handle situation with existing config map) to be able to re-use it in other modules
* external cluster - enable rgw with ssl
- add functionality to be able to connect to external cluster with secured RGW with SSL
this is backport of https://github.com/red-hat-storage/ocs-ci/pull/7645/files
> Enable external mode using SSL with RGW - backport of PR#7645 to release-4.12

- tests/ui/test_quickstarts.py
Fixes #8372
--Do not backport, 4.14 only--
> Text formatting test_quickstart_presence

- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Due to regression from #7510 node replacement tests were failing for Vmware IPI platform. This fixes https://github.com/red-hat-storage/ocs-ci/issues/8273
> Fixing test_node_replacement tests for Vmware IPI platforms

- tests/e2e/workloads/app/test_jenkins_simulation.py
This reverts commit 133bd66ac1a207b9cd0c43880a6bbbdf626ea334.
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/426/13224/602662/602663/602665/log
The bug was fixed in 4.12
> Revert "BZ #2096395 automation. (#6836)" in 4.11

- ocs_ci/ocs/constants.py
- ocs_ci/utility/environment_check.py
fix https://github.com/red-hat-storage/ocs-ci/issues/8398
> Exclude the pods with the prefix name of 'report-status-to-provider' in the leftovers check

- tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
https://bugzilla.redhat.com/show_bug.cgi?id=1779336 closed as WONTFIX but the issue is not observed anymore.
running steps manually leads to Expected results
----
1. Install OCP/OCS cluster 
2. Login as kubeadmin to OCP Console
3. Go to Monitoring -> Metrics page
4. Type eg. ceph_rbd_write_ops into the query and run it
----
> bz mark is stale.

- ocs_ci/ocs/fiojob.py
cherry pick
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/8081
> get correct pool name for external mode in fiojob

- tests/manage/pv_services/space_reclaim/test_auto_reclaim_space_cronjob.py
In this PR I've added a test case 'test_reclaim_space_cronjob_on_existing_namespace' which verifies the creation and deletion of cronjobs upon pvc creation/deletion in the existing "openshift-monitoring" namespace. 
This test case has a lot of common code with already existing test case 'test_reclaim_space_cronjob' . 
Therefore the shared code was refactored into  __reclaim_space_cronjob method.
> Adding a new test case for test_auto_reclaim_space_cronjob.py test

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/pytest_customization/ocscilib.py
- tests/conftest.py
- tests/test_failure_propagator.py
This test runs second to last and examines the skipped test cases of the execution.
In case of a high rate of skipped tests due to Ceph health not OK, which indicates something went wrong with the cluster during the execution, it will fail and report the potential test case that caused this problematic state.
Below is an example for how it works:
```
2023-09-12 01:03:10 E Failed: This run had 71.875% of the tests skipped due to Ceph health not OK. The test that is likely 
to cause this is test_bucket_creation[3-CLI-DEFAULT-BACKINGSTORE] which is under red_squad's responsibility
```
In this example, since this logic identified the culprit to be a test case belonging to Red Squad, `test_report_skip_triggering_test` was automatically marked with the `red_squad` marker and it will be …
> In case of high skip rate due to Ceph health not OK - Report test case and squad causing that

- tests/manage/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py
> test_ceph_csidriver_runs_on_non_ocs_nodes: remove from tier1

- tests/manage/mcg/test_admission_control.py
- tests/manage/mcg/test_mcg_resources_disruptions.py
- tests/manage/mcg/test_object_integrity.py
- tests/manage/mcg/test_pv_pool.py
- tests/manage/mcg/test_s3_routes.py
1. Fixes #7913: Add the skipif_mcg_only decorator to the listed tests
2. Make sure test_check_object_integrity[DEFAULT-BACKINGSTORE]  is not skipped in disconnected deployments
> Edit multiple Red Squad tests' decorators

- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Due to regression from #7510 node replacement tests were failing for Vmware IPI platform
> Cherry Pick PR 4.13: Fixing test_node_replacement tests for Vmware IPI platforms (#8375)

- ocs_ci/ocs/resources/pod.py
- tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py
In the PR, I implemented the following:
- In the functions `check_pods_after_node_replacement` and `check_pods_in_running_state`, exclude checking the pod statuses with the name prefix `report-status-to-provider-`.
- Add the param `exclude_pod_name_prefixes` to the functions `check_pods_in_statuses` and `get_pods_in_statuses` for excluding the pod names with specific prefixes.
> Exclude checking the pod statuses with the name prefix "report-status-to-provider-"

- ocs_ci/deployment/rosa.py
- ocs_ci/utility/rosa.py
* wait with provider cluster deletion till all consumers are disconnected
* ignore `...service is already deleting` error message (usually happens on second try to destroy the cluster)
fixes: https://github.com/red-hat-storage/ocs-ci/issues/7690
> Enhance destroy of MS clusters to avoid failures

- tests/manage/monitoring/pagerduty/test_deployment_status.py
> Get the pagerduty service id of the default cluster if we use multicluster run

- ocs_ci/ocs/ui/views.py
after merging different PRs in a short period the dictionary of locators (validation_4_14) where duplicated but not merged
> fix wrong PRs merging

- tests/manage/z_cluster/nodes/test_toleration.py
As per the discussion here: https://chat.google.com/room/AAAABfd8ivI/PItgYVWElNc, we decided that the test `test_toleration` is not relevant for MS. Therefore, I am skipping this test when using the Managed Service.
> Skip the test "test_toleration" when using MS

- ocs_ci/utility/prometheus.py
- ocs_ci/utility/workloadfixture.py
- tests/manage/monitoring/conftest.py
Fixed few problems:
1.  Prometheus alerts logging (via method refresh_connection) is now thread safe
2. Used inbuilt threading.Timer instead of the unsafe `while flag do request` construction
What it gives?
We have many failures with uncertain result, such as user not logged for the operation, creation of pod unsuccessful, etc caused by simultaneous `oc` comands
It affects **test_mcg_cpu_usage** and **test_monitoring_reporting_ok_when_idle**
Fixes: #8447
> use threading.lock, use Timer in measure_operation

- ocs_ci/helpers/performance_lib.py
- tests/e2e/performance/csi_tests/test_auto_reclaim_space_multi_clones.py
- tests/manage/pv_services/space_reclaim/test_auto_reclaim_space_cronjob.py
This PR contains the following: 
1) A new performance test tests/e2e/performance/csi_tests/test_auto_reclaim_space_multi_clones.py
that 
- verifies creation of 513 reclaim space cron jobs for an rbd pvc and its 512 clones. 
-  verifies that no reclaim space cron jobs are created for cephfs pvc and its clones
2) Changes to performance_lib ( a method wait_for_cronjobs was added there) 
3) Changes to tests/manage/pv_services/space_reclaim/test_auto_reclaim_space_cronjob.py
- a method that is used in this test was moved to performance_lib
> A new performance test - tests/e2e/performance/csi_tests/test_auto_reclaim_space_multi_clones.py

- ocs_ci/deployment/baremetal.py
- ocs_ci/utility/baremetal.py
Use standard `config.AUTH` object for bare metal deployment related configuration instead of directly loading the auth.yaml file.
This change will allow us to move the BM config from the global auth.yaml file to separated secret file and also automatically locking the resource in resource locker. 
**This PR has to be merged in sync with https://url.corp.redhat.com/d1e37a7 and with changes in Resource Locker!**
> BM deployment: use config.AUTH instead of load_auth_config

- ocs_ci/deployment/baremetal.py
- ocs_ci/utility/baremetal.py
Use standard `config.AUTH` object for bare metal deployment related configuration instead of directly loading the auth.yaml file.
This change will allow us to move the BM config from the global auth.yaml file to separated secret file and also automatically locking the resource in resource locker. 
**This PR has to be merged in sync with https://url.corp.redhat.com/d1e37a7 and with changes in Resource Locker!**
This is backport of https://github.com/red-hat-storage/ocs-ci/pull/8459
> BM deployment: use config.AUTH instead of load_auth_config - backport for 4.10

- ocs_ci/deployment/baremetal.py
- ocs_ci/utility/baremetal.py
Use standard `config.AUTH` object for bare metal deployment related configuration instead of directly loading the auth.yaml file.
This change will allow us to move the BM config from the global auth.yaml file to separated secret file and also automatically locking the resource in resource locker. 
**This PR has to be merged in sync with https://url.corp.redhat.com/d1e37a7 and with changes in Resource Locker!**
This is backport of https://github.com/red-hat-storage/ocs-ci/pull/8459
> BM deployment: use config.AUTH instead of load_auth_config - backport for 4.11

- ocs_ci/deployment/baremetal.py
- ocs_ci/utility/baremetal.py
Use standard `config.AUTH` object for bare metal deployment related configuration instead of directly loading the auth.yaml file.
This change will allow us to move the BM config from the global auth.yaml file to separated secret file and also automatically locking the resource in resource locker. 
**This PR has to be merged in sync with https://url.corp.redhat.com/d1e37a7 and with changes in Resource Locker!**
This is backport of https://github.com/red-hat-storage/ocs-ci/pull/8459
> BM deployment: use config.AUTH instead of load_auth_config - backport for 4.12

- tests/manage/rgw/test_bucket_creation.py
- tests/manage/rgw/test_bucket_deletion.py
- tests/manage/rgw/test_host_node_failure.py
- tests/manage/rgw/test_multipart_upload.py
- tests/manage/rgw/test_obc_quota.py
- tests/manage/rgw/test_object_bucket_size.py
- tests/manage/rgw/test_object_integrity.py
- tests/manage/rgw/test_rgw_pod_existence.py
Fix squad assignment for following tests:
```
test_bucket_creation[3-RGW-OC]              tests/manage/rgw/test_bucket_creation.py
test_duplicate_bucket_creation[3-RGW-OC]    tests/manage/rgw/test_bucket_creation.py
test_bucket_delete[3-RGW-OC]                tests/manage/rgw/test_bucket_deletion.py
test_bucket_delete_with_objects[RGW-OC]     tests/manage/rgw/test_bucket_deletion.py
test_nonexist_bucket_delete[RGW-OC]         tests/manage/rgw/test_bucket_deletion.py
test_rgw_host_node_failure                  tests/manage/rgw/test_host_node_failure.py
test_multipart_upload_operations            tests/manage/rgw/test_multipart_upload.py
test_obc_quota[1-RGW-OC-quota0]             tests/manage/rgw/test_obc_quota.py
test_object_bucket_size                     …
```
> fix squad assignment for manage/rgw tests

- tests/conftest.py
To prevent the squad marker verification from blocking deployment or testing, we will only perform the validation if the pytest `--collectonly` option is set.
More changes here than I wanted but I had to change the name of the ocsci config object as it conflicted with the pytest `config` object that is automatically passed to this hook.
> Squad validation on collectonly

- tests/manage/mcg/test_endpoint_autoscale.py
Extended workload run time, and enable execution for 4.14.
> Extended workload run time for noobaa endpoint

- tests/ecosystem/upgrade/conftest.py
release-4.12 backport of #8074
> [release-4.12 backport] Update the RPC payload at `test_buckets_before_upgrade`

- conf/README.md
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/utility/reporting.py
- ocs_ci/utility/utils.py
- tests/test_failure_propagator.py
* Added skips on Ceph health percentage to the results breakdown
* Added 2 ReportPortal attributes - `ceph_health_skips` and `ceph_health_skips_over_threshold`
* For acceptance suite, the value of config.RUN["skipped_on_ceph_health_threshold"] would be set to 0 so any skip on Ceph health during an acceptance suite execution would cause test_report_skip_triggering_test to fail
> A few improvements for skips Ceph health reporting

- ocs_ci/ocs/resources/mcg.py
- tests/manage/mcg/test_nb_mgmt_endpoint.py
release-4.11 backport of https://github.com/red-hat-storage/ocs-ci/pull/7875
> [release-4.11 backport] Choose to use only the MCG-CLI for RPC calls elsewhere

- ocs_ci/ocs/resources/storage_cluster.py
- tests/conftest.py
- tests/encryption/test_intransit_encryption_sanity.py
Following changes have been added to fix the test failures:
1. Added retries to check in-transit encryption configuration parameters after enabling/disabling encryption.
2. Refined some assert messages.
> Fixed in-transit encryption tests failure.

- ocs_ci/ocs/ui/odf_topology.py
When deployment has no labels it should have empty string but not `null`
Addressed issue hit in automation regression
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/14689/676157/676270/676273/log
> fixed minor logic issue

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/rgw.py
- tests/manage/rgw/test_rgw_routes.py
Covers  [BZ #2139037](https://bugzilla.redhat.com/show_bug.cgi?id=2139037) by testing the following:
1. RGW's service is exposed by both http and https routes
2. Both endpoints use a TLS termination policy
3. Basic I.O functionality is working properly using both endpoints
> BZ 2139037 Coverage - `test_rgw_routes`

- ocs_ci/cleanup/vsphere/cleanup.py
> delete template folder for vsphere IPI in vSphere cleanup

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/ui/validation_ui.py
- ocs_ci/ocs/ui/views.py
adjust locator to changes in html
FIXES #8606
> test_dashboard_validation_ui-adjust-locator-4.14

- tests/encryption/test_mon_failure_in_intransit_encryption.py
Skip the test case test_mon_failures_with_intransit_encryption due to the issue #8464. This is to avoid errors in the test cases that foww this test case.
> Skip the test case test_mon_failures_with_intransit_encryption due to the ocs-ci issue 8464

- ocs_ci/ocs/resources/pod.py
This is backport of #8315
Fixes #8311
> Revert back to default fio timeout value in get_fio_rw_iops() - backport for 4.13

- tests/manage/pv_services/test_write_to_cephfs_pvc_with_nonroot_user.py
Test Steps:
1. Create a pod with scc with runAsUser and runAsNonRoot
2. Perform IOs, should give permission error with both the cephfs access_modes
3. Recreate pod with fsGroup scc
4. Perform io, should be successful on the pods.
https://bugzilla.redhat.com/show_bug.cgi?id=2176354
> [Closed Loop][GSS]Automation of GSS BZ-2176354

- tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Issues Observed: github issue [#2201](https://github.com/red-hat-storage/ocs-operator/issues/2201)
PVC not reaching Bound state due to issues in environment like Ceph Cluster health not in good shape POD not reaching Running state due to lack of resources for running pods in cluster
In above scenarios TC while loop is continued till it creates the required number of resources(PVCs and PODs) in the cluster, due to this TC continued to execute for more than 4 days.
In the PR will be adding a iteration counter to terminate the while loop.
> Fix: Scale ceph pod respin test while loop is not exited

- tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
2023-09-09 04:55:29,516 - Thread-2 - DEBUG - urllib3.connectionpool._new_conn.939 - Starting new HTTPS connection (1): prometheus-k8s-openshift-monitoring.apps.j-039aikt1c33-t1.qe.rh-ocs.com:443
2023-09-09 04:55:29,579 - Thread-2 - DEBUG - urllib3.connectionpool._make_request.433 - https://prometheus-k8s-openshift-monitoring.apps.j-039aikt1c33-t1.qe.rh-ocs.com:443 "GET /api/v1/query?query=cluster%3Aceph_disk_latency%3Ajoin_ceph_node_disk_irate1m&time=1694235329.513803 HTTP/1.1" 200 87
2023-09-09 04:55:29,581 - Thread-2 - DEBUG - /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py.validate_status.303 - content value: {'status': 'success', 'data': {'resultType': 'vector', 'result': []}}
2023-09-09 04:55:29,582 - Thread-2 - WARNING - …
> add bz mark for failing test

- ocs_ci/ocs/ui/mcg_ui.py
- ocs_ci/ocs/ui/page_objects/backing_store_tab.py
- ocs_ci/ocs/ui/page_objects/bucket_class_tab.py
- ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
- ocs_ci/ocs/ui/page_objects/namespace_store_tab.py
- ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py
- ocs_ci/ocs/ui/page_objects/object_buckets_tab.py
- ocs_ci/ocs/ui/page_objects/object_storage.py
- ocs_ci/ocs/ui/page_objects/page_navigator.py
- ocs_ci/ocs/ui/page_objects/resource_list.py
- ocs_ci/ocs/ui/page_objects/resource_page.py
- ocs_ci/ocs/ui/validation_ui.py
- ocs_ci/ocs/ui/views.py
- tests/manage/mcg/ui/test_mcg_ui.py
* refactoring due to a new UI layout and transitions
* test test_store_creation_and_deletion previously running only against ODF 4.8 adapted to new UI and works with ODF 4.14
both NamespaceStore and BackingStore creation
> create store tests adapted to 4.14

- ocs_ci/helpers/performance_lib.py
- tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
This PR is a very much needed fix, since the deletion time notification has changed in the csi logs in ODF 4.14. 
Therefore we need to keep the old code for ODF <=4.13 and implement a new calculation starting 4.14.
> A fixing to performance lib for correct calculation of pvc/clone deletion time in 4.14

- ocs_ci/ocs/resources/mcg_params.py
- ocs_ci/ocs/resources/objectbucket.py
- ocs_ci/ocs/resources/pod.py
- tests/conftest.py
- tests/manage/mcg/test_nsfs.py
- Fix the way we wait for the pods to mount the volume after setting NSFS
- Semantic changes to `mcg_account_factory_fixture`
- Use one of the noobaa-endpoint pods to interface with the volume, instead of the ubi8 pod: Fixes #8451
- Use the bucket_factory fixture with the `mcg-namespace` interface to create the NSFS bucket in the export scenario - removes the need for dealing with creation/cleanup logic in the fixture.
- Following step 6 at https://github.com/noobaa/noobaa-core/wiki/NSFS-on-Kubernetes, add the following policy to the export-scenario bucket:
```
bucket_policy = gen_bucket_policy(
user_list=["*"],
actions_list=["*"],
resources_list=["*"],
)
bucket_policy = json.dumps(bucket_policy)
put_bucket_policy(mcg_obj_session, nsfs_obj.bucket_name, bucket_policy)
```
This fixes #8244 …
> Refactor `nsfs_bucket_factory_fixture` and fix various NSFS issues

- ocs_ci/templates/mcg/s3cli-sts.yaml
> `s3cli-sts.yaml`: Use the new, actually multi-arch 3.0 tag

- ocs_ci/framework/__init__.py
- ocs_ci/framework/pytest_customization/reports.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/html_reports/test_time_table.html.j2
- ocs_ci/utility/utils.py
This functionality will give us a file named session_test_time_report_file.csv that will have time test arranged in ascending order of the total time taken by them to complete the test group by test name.  It will also show time taken for setup of the test,  call of test, and teardown of the test.  
example:
```
(venv-ocsci)[sdurgbun ocs-ci] (feat/testTimingReport)$ cat session_test_time_report_file.csv 
testName        setup   call    teardown        total
tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephFileSystem]   24.09   205.12  44.05   273.26
tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py::TestClone::test_pvc_to_pvc_clone[CephBlockPool]    52.33   213.14  31.28   296.75
(venv-ocsci)[sdurgbun ocs-ci] …
```
> Adding hook to create a timing report for the tests run

- ocs_ci/framework/pytest_customization/reports.py
- ocs_ci/utility/tests/test_utils.py
- ocs_ci/utility/utils.py
- tests/test_failure_propagator.py
Dump configuration to file at the end of the execution similarly as it is done in the beginning.
This might be useful for debugging various issues (e.g. compare the config with the dump from the start).
I have to introduce new function `filter_unrepresentable_values`, which converts _object like_ values from config object to string to be able to dump them to yaml.
I'm also adding few useful log messages to `test_report_skip_triggering_test`.
> dump configuration to file at the end of the execution

- tests/manage/rgw/test_bucket_creation.py
- tests/manage/rgw/test_bucket_deletion.py
- tests/manage/rgw/test_multipart_upload.py
- tests/manage/rgw/test_obc_quota.py
- tests/manage/rgw/test_object_bucket_size.py
- tests/manage/rgw/test_object_integrity.py
> Adds "skipif_mcg_only" decorator to the tests which are using ceph resources for mcg_only deployment

- tests/conftest.py
release-4.12 backport of #7707
> [release-4.12 backport] Mirror ubi8 in disconnected environments for `test_nsfs.py`

- tests/manage/storageclass/test_custom_storageclass_names.py
Skipping RGW type storageclass for AWS deployment
> Skipping RGW type storageclass for AWS deployment

- ocs_ci/ocs/resources/pod.py
fix https://github.com/red-hat-storage/ocs-ci/issues/8412
> When getting the rook-ceph-tool pod use the provider kubeconfig parameter if exist in the run

- ocs_ci/ocs/machine.py
- ocs_ci/ocs/node.py
- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
The pr fixes three small issues in the test "test_simultaneous_drain_of_two_ocs_nodes": 
- fix #7866 - Increase the timeout when draining the osd nodes.
- fix #7868 -  Generate the correct osd nodes for 1AZ deployment. This is implemented in the function `generate_new_nodes_and_osd_running_nodes_ipi`, which generates the right osd nodes.
- fix #8045 - Ensure that the current replica count equals the ready replica count - this is implemented when we delete the machines of the deleted osd nodes and wait for the new machines to come up with new nodes.
> Update the test "test_simultaneous_drain_of_two_ocs_nodes" when we have 1az and 3 racks 4.12 #7987

- conf/README.md
- ocs_ci/framework/conf/default_config.yaml
- tests/test_failure_propagator.py
- set default skipped_on_ceph_health_threshold to 0
- update rounding of skipped_on_ceph_health_ratio to 3 digits
> fix test_failure_propagator

- conf/README.md
- ocs_ci/framework/conf/default_config.yaml
- tests/test_failure_propagator.py
- set default skipped_on_ceph_health_threshold to 0
- update rounding of skipped_on_ceph_health_ratio to 3 digits
This is backport of https://github.com/red-hat-storage/ocs-ci/pull/8688
> fix test_failure_propagator - backport for 4.13

- tests/manage/mcg/test_kms.py
release-4.13 backport of #7660
> [release-4.13 backport] `test_noobaa_kms_validation`: Remove the use of RE and generalize the search based on environment config

- tests/conftest.py
fix https://github.com/red-hat-storage/ocs-ci/issues/8686
> In the "snapshot_restore_factory_fixture" get the correct storageclass(rbd or cephfs) when using MS consumer cluster

- ocs_ci/framework/pytest_customization/reports.py
- ocs_ci/utility/utils.py
This fix should avoid following issues:
```
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/framework/pytest_customization/reports.py", line 166, in pytest_report_teststatus
INTERNALERROR>     GV.TIMEREPORT_DICT[report.nodeid]["total"] += round(report.duration, 2)
INTERNALERROR> KeyError: 'total'
```
and
```
email_reports(session)
File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", line 1744, in email_reports
add_time_report_to_email(session, soup)
File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", line 4497, in add_time_report_to_email
sorted(data.items(), key=lambda item: item[1]["total"], reverse=True)
File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", …
```
> fix add_time_report_to_email keyError issue

- tests/manage/mcg/test_bucket_policy.py
release-4.12 backport of #8477
> [release-4.12 backport] `test_public_website`: Use `s3_get_object` with `retry`

- tests/manage/mcg/test_bucket_policy.py
release-4.13 backport of #8477
> [release-4.13 backport] `test_public_website`: Use `s3_get_object` with `retry`

- tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
Updated the existing test case to cover  OCS-4761.
OCS-4761 - [RHSTOR-2310](https://issues.redhat.com//browse/RHSTOR-2310) Qualify "[Ramen] Improve reporting last sync time for a given DRPlacementControl resource" Verify last sync time in a DR protected application
> Test case OCS-4761

- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
> Wait for node deletion and verify original node count during teardown of test_automated_recovery_from_stopped_node_and_start[True]

- ocs_ci/ocs/cluster.py
- tests/manage/z_cluster/test_ceph_default_values_check.py
fix https://github.com/red-hat-storage/ocs-ci/issues/7101
In the PR, I implement the following:
- Remove the try and except in the function `get_mds_cache_memory_limit`.
- Remove the redundant line in the test `test_check_mds_cache_memory_limit`.
- In the test `test_check_mds_cache_memory_limit`, update the `retry` clause with the correct parameters.
> Remove the try and except from the function "get_mds_cache_memory_limit" and move it to the test "test_check_mds_cache_memory_limit"

- tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
For snapshot of 100GB size cephFS single snapshot test case was failing. 
I increased get_fio_results timeout from 600 ( default) to 1800.
> test_pvc_snapshot_performance.py fix  - increasing get_fio_results timeout

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
- ocs_ci/utility/version.py
from recent ocs operator changes we are trying to
have more than 1 mgr by deafult,
So to imply it we need to check for the mgr pdb
which would get created if mgr count >1
> ci: fix mgr pdb resource count

- setup.py
There are few packages which installs or updates the latest version which breaks the ocs-ci due to conflict versions.
> pin versions for python packages
