- ocs_ci/ocs/node.py
- tests/manage/z_cluster/cluster_expansion/conftest.py
- Add function for adding new LSO UPI worker nodes
- Update the test of node expansion for adding new LSO UPI worker nodes
> Add function for adding new LSO UPI worker node

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/storage_cluster.py
- tests/ecosystem/upgrade/test_upgrade.py
> Fix get_osd_count for upgrade of external cluster

- ocs_ci/ocs/hsbench.py
Fix issue: https://github.com/red-hat-storage/ocs-ci/issues/4233
> Remove nodename when creating hsbench-pod.

- tests/manage/rgw/test_object_bucket_size.py
> Adding rgw annotation to bucket_size test if upgraded from OCS 4.6

- ocs_ci/helpers/helpers.py
- tests/ecosystem/upgrade/test_upgrade.py
- tests/manage/z_cluster/upgrade/test_check_mon_pdb_post_upgrade.py
> Modify test_check_mon_pdb_post_upgrade with the new mon pdb changes

- tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
- tests/manage/pv_services/test_pvc_disruptive.py
> Increase timeout for pod status check

- ocs_ci/ocs/scale_noobaa_lib.py
- tests/e2e/scale/noobaa/test_scale_obc_creation.py
Use fixture for cleanup function.
Fixed https://github.com/red-hat-storage/ocs-ci/issues/4161
> Adding fixture for cleanup function.

- setup.py
> Add ovirt sdk python package in virtual env of ocs-ci execution

- ocs_ci/utility/utils.py
> Skip version comparison and download if unable to expose the OCP version

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/views.py
- tests/ui/test_quickstarts.py
> Add quickstart tests for UI

- ocs_ci/ocs/must_gather/must_gather.py
> Fix Must Gather test, add node names [BM,Azure]

- tests/e2e/workloads/test_jenkins_simulation.py
> Remove test_git_clone from acceptance suite

- ocs_ci/deployment/baremetal.py
> Retry configuring storage for image registry

- docs/getting_started.md
- docs/usage.md
> Update doc sections about UI testing

- ocs_ci/ocs/utils.py
> Wait till toolbox pod will come up

- ocs_ci/framework/conf/default_config.yaml
> Include ignition_version in default_config.yaml

- tests/manage/rgw/test_host_node_failure.py
> Check all noobaa pod are up before creation of OBC

- tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
> Update test_del_mon_service_and_create_pvc.py to be compatible with LSO cluster

- tests/e2e/performance/test_pvc_creation_deletion_performance.py
In this PR the results of the PVC_creation_deletion performance results are push into the ElasticSearch server, so we can display them in the QPAS Performance Dashboard.
> Push pvc_create_delete perf. results into ES server

- conf/deployment/rhv/ipi_1az_rhcos_lso_3m_3w.yaml
- conf/ocsci/rhv_ipi.yaml
- ocs_ci/deployment/factory.py
- ocs_ci/deployment/helpers/lso_helpers.py
- ocs_ci/deployment/on_prem.py
- ocs_ci/deployment/rhv.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/uninstall.py
- ocs_ci/templates/ocp-deployment/install-config-rhv-ipi.yaml.j2
- ocs_ci/utility/rhv.py
- ocs_ci/utility/utils.py
Added support for new platform RHV IPI
- OCP deployment
- OCS deployment
Closes: #4158
> Add support for deployment on RHV

- ocs_ci/utility/rhv.py
> [RHV] Define all arguments with default values 

- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
> Fix checking number of nodes on IMB Cloud

- tests/manage/z_cluster/cluster_expansion/conftest.py
> Enable add node for tier1 over Vmware IPI

- ocs_ci/framework/conf/ocp_version/ocp-4.2-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.2-ga-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.3-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.3-ga-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.4-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.4-ga-config.yaml
> Push version of terraform to 0.11.15

- tests/manage/z_cluster/upgrade/test_check_mon_pdb_post_upgrade.py
> Mon PDB changes applied to 4.6.5

- tests/manage/rgw/test_host_node_failure.py
> Skip test_rgw_host_node_failure for vsphere IPI platform

- ocs_ci/deployment/vmware.py
> Increase timeout for generating CSR's

- ocs_ci/utility/aws.py
> Fixing docstring in update_hosted_zone_record

- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
> OCS4.6/4.8 Installation via UI

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/cosbench.py
- ocs_ci/templates/workloads/cosbench/cosbench_configmap.yaml
- ocs_ci/templates/workloads/cosbench/cosbench_pod.yaml
- tests/e2e/workloads/cosbench/test_cosbench.py
COSBench is a distributed benchmark tool to test cloud object storage systems.
> Creates cosbench pods
> Prepares the workload xml 
> Submits to cosbench
> Get the results
> Cosbench workload for MCG

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/rhv.py
- tests/libtest/test_rhv.py
> [RHV] Add function to stop RHV nodes

- tests/conftest.py
> Revert increased PV deletion timeout for Azure platform

- ocs_ci/ocs/cluster.py
- tests/manage/z_cluster/test_ceph_default_values_check.py
Automates: https://bugzilla.redhat.com/show_bug.cgi?id=1908414
> Validates mon_max_pg_per_osd on ceph cluster

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/validation_ui.py
- ocs_ci/ocs/ui/views.py
- ocs_ci/utility/utils.py
- tests/conftest.py
- tests/ui/test_validation_ui.py
This a general ui test to verify all OCS pages (on OCP console) work as expected.
Example for UI issue:
> UI validation test tier1

- ocs_ci/templates/ocs-deployment/catalog-source.yaml
> Add updateStrategy for catalogSource

- docs/getting_started.md
Addition of few more dependency packages to be listed in getting started doc
> Few more dependency packages to be listed in getting started doc

- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
- conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vmfs_lso_directpath_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vmfs_lso_rdm_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vmfs_lso_vmdk_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vsan_lso_directpath_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vsan_lso_rdm_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_vsan_lso_vmdk_3m_3w.yaml
- conf/ocsci/vsphere_scale_cluster.yaml
> Add rhel_workers to all configs with RHEL

- ocs_ci/utility/utils.py
> Change openshift-release.svc.ci.openshift.org to amd64.ocp.releases.ci.openshift.org

- ocs_ci/utility/utils.py
Fixes: #4400 
Signed-off-by: vavuthu vavuthu@redhat.com
> Donot check svc site when skipping download

- ocs_ci/utility/csr.py
> Handling new CSR for OCP 4.8 deployments

- docs/coding_guidelines.md
> Added some info around our usage of black in our coding guidelines doc

- ocs_ci/ocs/amq.py
> Fix leftover errors in amq

- ocs_ci/ocs/cluster_load.py
> ClusterLoad: fix timeout condition while determining the cluster IOPS limit

- ocs_ci/deployment/deployment.py
> Use catalogSource secrets directly

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/views.py
- Add retry decorator on login_ui function
- Add support flexy deployment
> Add retry decorator on login_ui function

- conf/ocsci/stage.yaml.example
- ocs_ci/deployment/deployment.py
Stage deployment is now done differently and this code is not used anymore, so removing it to cleanup the code.
> Cleanup old unused state deployment related code

- tests/e2e/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
>  Test to create new compressed sc and their support for snapshot-clone

- tests/e2e/workloads/amq/test_rgw_kafka_notifications.py
> Timestamp displayed in the bucket event notifications received

- .readthedocs.yaml
> Fix doc depe issue

- ocs_ci/deployment/vmware.py
- ocs_ci/utility/csr.py
- ocs_ci/utility/vsphere.py
> Improve logic to restart nodes when IP's are not generated

- ocs_ci/deployment/vmware.py
- ocs_ci/utility/utils.py
> Adding filesystem parameter for chrony based on ignition version

- ocs_ci/deployment/aws.py
> Adding environment variable HOSTS_SCRIPT_DIR for AWS UPI deployment

- ocs_ci/deployment/helpers/lso_helpers.py
> Avoid logging object into console

- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Perform node replacement twice.
node_x -> node_y
node_y -> nod_x
> Automate bz#1840539:

- ocs_ci/helpers/pvc_ops.py
- tests/e2e/scale/test_cephfs_many_files.py
Fixed comment in the helper class to be correct.
Fixes #4043
> Fixed timeout to match the value in a similar call in a helper class.

- tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops_crd.py
> mpu operations on namespace cache bucket

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/rhv.py
> [RHV] Add function to reboot RHV VMs

- ocs_ci/deployment/helpers/prechecks.py
- ocs_ci/utility/vsphere.py
> improve performance for prechecks in vSphere platform

- ocs_ci/framework/pytest_customization/ocscilib.py
> Load report portal settings only when option is enabled

- docs/usage.md
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/ui/deployment_ui.py
> Conditions for installing the OCS operator via UI

- ocs_ci/ocs/hsbench.py
- ocs_ci/templates/workloads/hsbench/hsbench_obj.yaml
- tests/e2e/scale/noobaa/test_hsbench.py
- tests/e2e/scale/noobaa/test_scale_namespace_crd.py
- tests/e2e/scale/noobaa/test_scale_namespace_rpc.py
Create namespace rpc and crd test cases, 
Running S3 hs benchmark to write to namespace bucket.
> Scale noobaa namespace test cases

- ocs_ci/ocs/resources/storage_cluster.py
- Automation of  GSS bug https://bugzilla.redhat.com/show_bug.cgi?id=1830215
- Checking if  container images for all of Storagecluster managed components exists and match
> GSS bug bz1830215 automation

- ocs_ci/ocs/osd_operations.py
- ocs_ci/ocs/resources/pod.py
- tests/manage/z_cluster/nodes/test_disk_failures.py
- Fixes https://github.com/red-hat-storage/ocs-ci/issues/4276
- Code for osd replacement is moved to osd_operations file
> OSD device replacement fixes for ocs 4.8

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/rhv.py
> [RHV]  Add function to start -down nodes of a cluster

- ocs_ci/deployment/vmware.py
> Fixing OCP 4.7 installation

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/constants.py
> Adding limits for AWS i3 platform for storageDeviceSets

- tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
> move coredump test from "tier1" to "tier2"

- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
- ocs_ci/utility/ipam.py
> move VIPS needed to constants module

- ocs_ci/ocs/resources/bucketclass.py
- tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
test includes RGW namespace store with RGW OBC as cache bucket along with noobaa obc.
> cache bucket lifecycle test

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/validation_ui.py
- ocs_ci/ocs/ui/views.py
> UI validation on OCP4.8

- ocs_ci/framework/pytest_customization/ocscilib.py
> Add squad marker to test items and junit properties

- ocs_ci/framework/conf/ocs_version/ocs-4.9.yaml
- ocs_ci/framework/main.py
> Adding OCS 4.9 yaml file

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/machine.py
- ocs_ci/ocs/scale_lib.py
- ocs_ci/templates/openshift-infra/machineset-rhv.yaml
In RHV platform create new machineset for scaling nodes and
use this nodes to run app pods
> RHV - create new machineset for scaling nodes to run app pods

- ocs_ci/framework/pytest_customization/ocscilib.py
Added a couple small improvements to the reportportal squad marker tags.
> Squad mark fix

- conf/ocsci/enable_multus.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/ocs-deployment/multus.yaml
> Supporting multus deployment

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/utility/deployment.py
> Supporting external cluster secret data for OCP 4.8 and in upgrade path

- ocs_ci/ocs/constants.py
> Adding Black squad for UI test cases

- docs/getting_started.md
> Adding documentation for prerequisites for vSphere IPI

- conf/README.md
- conf/deployment/aws/ipi_3az_rhcos_3m_4w_arbiter.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_6w_arbiter.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/helpers/lso_helpers.py
- ocs_ci/deployment/zones.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/resources/storage_cluster.py
- tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Implements https://github.com/red-hat-storage/ocs-ci/issues/4399 (progress tracked in the issue)
> Arbiter setup for production CI

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/pytest_customization/ocscilib.py
When running with live_deployment change image and tag
to proper DS image.
> Change must-gather image to live image + tag

- ocs_ci/deployment/factory.py
- ocs_ci/ocs/platform_nodes.py
> Fix ovirt-dependencies

- ocs_ci/ocs/pgsql.py
- tests/e2e/workloads/pgsql/test_pgsql.py
- tests/e2e/workloads/pgsql/test_pgsql_node_drain.py
- tests/e2e/workloads/pgsql/test_pgsql_node_reboot.py
- tests/e2e/workloads/pgsql/test_pgsql_pod_respin.py
1) Fixes: #4393 
2) Few changes are made to the pgsql failure tests to pick a node where pgbench pods are not running instead of selecting randomly.
> Increased the transactions count for pgbench pod and few enhancements to pgsql tests

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/CSI/rbd/csi-kms-connection-details.yaml
- ocs_ci/templates/CSI/rbd/csi-kms-secret.yaml
- ocs_ci/utility/kms.py
- ocs_ci/utility/utils.py
> Helper functions for encrypted storageclass creation with KMS vault

- conf/ocsci/external_rhcs_cluster.yaml
> Add polarion id for external mode conf file

- ocs_ci/ocs/resources/storage_cluster.py
> Fix Add capacity failure for non-LSO cluster.

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/ibmcloud.py
- tests/conftest.py
- tests/libtest/test_ibmcloud.py
- tests/manage/pv_services/pvc_snapshot/test_rbd_block_pvc_snapshot.py
- tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
- tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
- tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
- tests/manage/z_cluster/nodes/test_nodes_restart.py
- tests/ui/test_pvc_ui.py
- tests/ui/test_validation_ui.py
Added the implementation for create_nodes
Skip the test case for Tier1
> Fixed issues to ran Tier1 and 4 on ibmcloud

- conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v1_external_with_namespace.yaml
- conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v2_external_with_namespace.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_external_vault_v1_with_namespace.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_external_vault_v2_with_namespace.yaml
> Seperate v1 and v2 for vault production job yamls

- tests/manage/monitoring/prometheus/test_rgw.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/4497
> Update ClusterObjectStoreState alert message for higher version

- conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_6w_arbiter.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/netsplit.py
- ocs_ci/deployment/zones.py
- ocs_ci/framework/conf/default_config.yaml
- requirements.txt
- setup.py
- tox.ini
implements https://github.com/red-hat-storage/ocs-ci/issues/4554
> optionally use ocp-network-split during deployment

- ocs_ci/ocs/node.py
Regarding this issue https://github.com/red-hat-storage/ocs-ci/issues/4542, we see that the test failed because one of the pods has been deleted while the function "get_node_pods" was running - which cause a CommandFailed exception of "pod not found" error. To fix it, I added one more param `raise_pod_not_found_error` in the function "get_node_pods", with the default value of `False`, so now it will not throw an exception of "pod not found" error unless we pass this param with the value `True`.
> Fix the function "get_node_pods" to not throw an exception in case of pod not found

- ocs_ci/utility/uninstall_openshift_logging.py
> Fixes:4564

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/defaults.py
- ocs_ci/utility/kms.py
> Prameterize kmsid and allow updating connectiondetails

- ocs_ci/ocs/machine.py
- ocs_ci/ocs/node.py
- tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
> Adjust tests in test_node_replacement_proactive.py to run on vSphere IPI

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/ibmcloud.py
> Improve run_ibmcloud_cmd functionality

- ocs_ci/deployment/baremetal.py
> Fix disks cleanup over BM

- tests/manage/z_cluster/test_osd_heap_profile.py
Add a generator to check the content of the folder /var/log/ceph/
#4531
> Add TimeoutSampler generator for test_osd_heap_profile

- tests/e2e/registry/test_registry_by_increasing_num_of_image_registry_pods.py
Fixes: #4489 
Failed due to bug 1981639 as a result one of the registry pod stuck in a pending state which caused other tests to fail. So at the teardown make sure the replica count is set to 2.
> On teardown validate replica count of registry pod

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.8-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.9-config.yaml
> updating template for ocp 48 and ocp 49

- conf/deployment/vsphere/upi_1az_rhcos_multus_vmfs_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhcos_multus_vsan_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_multus_vmfs_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhel_multus_vsan_3m_3w.yaml
> Add multus prod configs

- ocs_ci/ocs/utils.py
> Workaround: Custom toolbox deployment for Multus enabled cluster

- ocs_ci/deployment/deployment.py
- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/helpers_ui.py
- ocs_ci/ocs/ui/validation_ui.py
- ocs_ci/utility/utils.py
- tests/conftest.py
- tests/ui/test_validation_ui.py
> Fix UI infra

- ocs_ci/ocs/constants.py
- tests/manage/z_cluster/test_mon_log_trimming.py
> Validate that mon db gets trimmed.

- tests/manage/z_cluster/test_delete_rook_ceph_mon_pod.py
> Fix BZ automation

- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/ocs_upgrade.py
> Update external cluster upgrade procedure

- ocs_ci/utility/csr.py
Description:
New openshift-monitoring CSR was added in OCP 4.9
> Increase expected CSR count in OCP 4.9

- ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-minus1-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-upgrade.yaml
> 4.8 GA config files

- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/ocs/scale_lib.py
- tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
To create 12 OCS workers, 36 OSDs, 6000 PVCs
Further testing re-spin, reboot and shutdown of pods, nodes
> Scale 12 OCS workers, 36 OSDs and 6000 PVCs attached to PODs and perform tests

- ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-minus1-config.yaml
> Update GA template for OCP 4.8

- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
- tests/test_failure_propagator.py
> Catch and report session scope fixture teardown failures in a separated dedicated test case

- ocs_ci/ocs/constants.py
> Add new Ceph values to ceph config values saved in constants.py

- ocs_ci/deployment/helpers/prechecks.py
> skip template check for vSphere IPI

- ocs_ci/ocs/platform_nodes.py
> log vm names instead of objects

- ocs_ci/ocs/node.py
- ocs_ci/utility/utils.py
> Wait for new nodes to settle down in IBM cloud

- ocs_ci/ocs/node.py
- ocs_ci/ocs/resources/storage_cluster.py
> Fix osd_encryption_verification function

- ocs_ci/helpers/helpers.py
- tests/manage/z_cluster/test_noobaa_console.py
- tests/manage/z_cluster/test_noobaa_xss_vulnerability.py
> GSS bug, Verify there is no xss vulnerability with noobaa management console.

- ocs_ci/utility/ibmcloud.py
> get volume IDs for cluster in IBM cloud

- ocs_ci/utility/ibmcloud.py
- tests/libtest/test_ibmcloud.py
- tests/manage/pv_services/pvc_clone/test_clone_when_pvc_full.py
- tests/manage/z_cluster/nodes/test_disk_failures.py
> Fixing the Tier4b issues

- conf/deployment/baremetal/upi_1az_rhcos_multus_nvme_intel_3m_3w.yaml
> Add multus baremetal configuration

- tests/ecosystem/upgrade/test_upgrade_ocp.py
loading new config file after OCP upgrade
fix issue #4588
> Added load config file functionality, fix issue #4588

- tests/manage/z_cluster/test_mon_log_trimming.py
> Fix BZ 1941939 automation.

- ocs_ci/deployment/deployment.py
> remove duplicate line of subscription_plan_approval

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/helpers/helpers.py
- ocs_ci/utility/kms.py
- tests/conftest.py
- tests/manage/pv_services/test_rbd_pv_encryption.py
Test to verify creation and deletion of encrypted RBD PVC with vaulttoken
OCS-2585 - RBD PVC creation using encryption enabled storageclass (KV-v1)
OCS-2592 - RBD PVC creation using encryption enabled storageclass (KV-v2)
> Test to verify creation and deletion of encrypted RBD PVC with vaulttoken

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/node.py
- tests/manage/z_cluster/test_multiple_mon_pods_stays_on_same_node.py
> A testcase to verifies multiple mons on same node

- tests/e2e/workloads/quay/test_quay_operator.py
> quay operator test for bz1959331

- ocs_ci/templates/ocs-deployment/multus.yaml
Change cniVersion from `0.3.0` to `0.3.1` in NAD template
> [Multus] Update cniVersion in NAD template to align with the docs

- ocs_ci/utility/ibmcloud.py
> Fixing IBM cloud login issue

- ocs_ci/framework/conf/default_config.yaml
> Defaulting to OCS 4.9

- tests/e2e/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py
Fix post upgrade scale test failure: added ipi_deployment_required tier and updated file validation if condition
> Fix post_upgrade scale test failure

- .github/workflows/stale.yml
> Add github action for labeling and closing stale issues and pull requests

- ocs_ci/templates/ocs-deployment/catalog-source.yaml
> Add priority for ocs-catalogsource

- tests/manage/pv_services/test_rbd_pv_encryption.py
> Fix key validation for PV encryption in OCS 4.7

- tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
- tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
Add polarion ID for existing scale tests
> Add polarion ID for existing scale test

- ocs_ci/templates/workloads/fio/benchmark_fio.yaml
- ocs_ci/templates/workloads/fio/benchmark_fio_cmp.yaml
- ocs_ci/templates/workloads/smallfile/SmallFile.yaml
- tests/e2e/performance/test_fio_benchmark.py
replacing the old ripsaw object with the new benchmark operator.
> Fio implement benchmark-operator

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/resources/pod.py
- tests/manage/z_cluster/cluster_expansion/test_add_node_crashcollector.py
- tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
Test Procedure:
1.Get worker node where mgr pod running [worker-node-x]
2.Add worker node with OCS label
3.Check ceph status [wait_for_rebalance]
4.Drain worker-node-x
5.Wait for 3 mon pods to be on running state
6.Verify ceph-crashcollector pod running on worker node where "rook-ceph" pods are running.
7.Schedule worker-node-x
8.Wait for 3 osd pods to be on running state
9.Verify ceph-crashcollector pod running on worker node where "rook-ceph" pods are running.
> Add a new node and verify crashcollector pod created

- ocs_ci/ocs/pgsql.py
- ocs_ci/templates/workloads/pgsql/PGSQL_Benchmark.yaml
- ocs_ci/templates/workloads/pgsql/server/ConfigMap.yaml
- ocs_ci/templates/workloads/pgsql/server/Service.yaml
- ocs_ci/templates/workloads/pgsql/server/StatefulSet.yaml
> Adjust Pgsql with the new benchmark-operator changes

- tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
Fixed file validation issue in tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py test
> Fix file validation in Scale test

- setup.py
- fixes https://github.com/red-hat-storage/ocs-ci/issues/4727
> requre specific google-auth version

- ocs_ci/framework/pytest_customization/reports.py
fixes https://github.com/red-hat-storage/ocs-ci/issues/4724
> fix logging hanledrs hardcoded idex issue

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/ocs_upgrade.py
> Add post upgrade validation for pod ocs_metrics_exporter

- tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
- tests/e2e/registry/test_registry_shutdown_and_recovery_node.py
- tests/e2e/workloads/amq/test_amq_node_reboot_and_shutdown.py
Skipping the stop nodes testcases for ibmcloud
> Skipping the stop nodes testcases for ibmcloud

- setup.py
- fixes https://github.com/red-hat-storage/ocs-ci/issues/4727
> requre specific google-auth version - branch release-4.8

- setup.py
- fixes https://github.com/red-hat-storage/ocs-ci/issues/4727
> requre specific google-auth version - branch release-4.7

- setup.py
- fixes https://github.com/red-hat-storage/ocs-ci/issues/4727
> requre specific google-auth version - branch release-4.6

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/storage_cluster.py
- tests/manage/z_cluster/test_ceph_default_values_check.py
> Update back constants' Ceph config values for 4.7 and below clusters

- .github/workflows/stale.yml
> Refine configuration values for our stale issue/pr workflow

- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/ocs/ui/add_replace_device_ui.py
- ocs_ci/ocs/ui/helpers_ui.py
- ocs_ci/ocs/ui/views.py
- tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
> Run add capacity test via cli if there is a SSL ERROR

- ocs_ci/ocs/scale_lib.py
- tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
Added reboot test to tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
> Adding reboot tests to scale script test_scale_12_OCS_worker_nodes_and_6000_PVCs.py

- .github/workflows/stale.yml
> Remove debug-only from stale workflow

- tests/e2e/performance/test_fio_benchmark.py
- tests/e2e/performance/test_pvc_bulk_clone_performance.py
- tests/e2e/performance/test_pvc_creation_deletion_performance.py
- tests/e2e/performance/test_pvc_multi_clone_performance.py
- tests/e2e/performance/test_pvc_multi_snapshot_performance.py
- tests/e2e/performance/test_pvc_snapshot_performance.py
Add polarion ID "OCS-2622" for test_pvc_multi_clone_performance.py test
>  Add polarion ID for existing performance test

- ocs_ci/ocs/scale_pgsql.py
> Update scale_pgsql with new benchmark-operator changes

- ocs_ci/ocs/ocs_upgrade.py
> Fixing bug in ignoring same SHA iamges

- ocs_ci/ocs/utils.py
> Catch IndexError when unable to find noobaa db pod

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/utility/secret.py
> Fix upgrade for IBM Cloud ROKS cluster

- tests/ecosystem/upgrade/test_upgrade_ocp.py
> Added debug logging before and after upgrade

- tests/e2e/performance/test_pvc_snapshot_performance.py
This PR replace in test_pvc_snapshot_performance the usage of the ripsaw object with the new benchmark operator object.
> Implement the benchmark-operator into pvc_snapshot-performance test

- ocs_ci/ocs/perftests.py
there is a bug in the performance benchmarks tests which in case of Failed status, it will run indefinitely, since it is waiting for Completed state.
This PR is fixing this issue.
> fix benchmark test from run for indefinitely

- tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py
> Add namespace parameter to snapshot test case

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/helpers_ui.py
- ocs_ci/ocs/ui/views.py
> Deployment and Add capacity tests via UI on Azure Internal cluster

- tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
- tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
- tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
- tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py
- tests/manage/pv_services/test_pvc_disruptive.py
- tests/manage/pv_services/test_rbd_thick_provisioning.py
- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
- tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Based on a solution given here https://github.com/red-hat-storage/ocs-ci/issues/2499 for one test change it to multiple till we have some image compiled with fio.
> Change all timeoutsamplars of wl_setup_done from 180 to 360 in relevant tests

- ocs_ci/deployment/deployment.py
> Adding retry mechanism for setup_persistent_monitoring

- ocs_ci/ocs/scale_noobaa_lib.py
- tests/e2e/scale/noobaa/test_scale_endpoint.py
Autoscale test case improvement for scaling up more than 2 endpoints.
> Autoscale scale test case improvement.

- ocs_ci/cleanup/aws/defaults.py
W/A issue: #4784
Once we will find out the issue we need to decrease the time back.
> Increase time for AWS cleanup job

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/resources/pod.py
- tests/ecosystem/upgrade/test_resources.py
bz link: https://bugzilla.redhat.com/show_bug.cgi?id=1974343
> GSS bz 1974343, Verify expected log exist after upgrade

- tests/e2e/scale/test_cephfs_many_files.py
- tests/e2e/scale/test_osd_node_balancing.py
Updated polarion ID to tests test_cephfs_many_files & test_OSD_node_balancing
> Add polarion ID to scale tests

- ocs_ci/utility/utils.py
- tests/conftest.py
> Skip UI tests on openshift dedicated ODF-managed service

- ocs_ci/helpers/helpers.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
> change the condition of waiting for the OSD pod in the test "test_automated_recovery_from_stopped_node_and_start"

- ocs_ci/ocs/ui/helpers_ui.py
> Skip ui_deployment on cluster with  Infra nodes

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/defaults.py
- ocs_ci/templates/ocs-deployment/storagesystem_odf.yaml
- ocs_ci/templates/ocs-deployment/subscription_odf.yaml
> Align ocs-ci to ODF changes

- tests/manage/mcg/conftest.py
> Skip mcg related test on openshift dedicated platform

- ocs_ci/ocs/hsbench.py
Fixing hsbench installation package.
> Fixed certificate issue when getting hsbench package.

- tests/conftest.py
- tests/manage/pv_services/test_rbd_rwx_pvc.py
Test case to verify RBD Block volume mode RWX PVC.
OCS-2599 - FT-Verify RBD RWX PVC
> Test RBD Block volume mode RWX PVC

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/ocs_upgrade.py
> Re-try cluster on PVC validation

- .github/workflows/stale.yml
> Increase max operations per run to 100 for stale workflow

- ocs_ci/templates/ocp-deployment/rhcos_images.yaml
> Add BM Config Files for OCP 4.9

- ocs_ci/ocs/perftests.py
this PR is part of the fix for #4807 
> Fix function which wait for benchmark to finish

- ocs_ci/deployment/aws.py
- ocs_ci/deployment/cloud.py
- ocs_ci/utility/deployment.py
- ocs_ci/utility/tests/test_deployment_utils.py
> Cluster prefix match fix

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/machine.py
- ocs_ci/ocs/scale_lib.py
- ocs_ci/templates/openshift-infra/machineset-vmware.yaml
- tests/e2e/scale/test_scale_3_OCS_worker_nodes_and_1500_PVCs.py
Enhanced scale test cases to use vmware ipi platform using custom machineset
With this PR we can execute all the scale tests in vmware ipi platform
> VMware ipi support for scale tests

- ocs_ci/deployment/deployment.py
> Include odf chnages in external cluster deployment

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/defaults.py
> Verify noobaa-operator during odf deployment

- ocs_ci/deployment/aws.py
> disabling master machine set for AWS UPI deployment

- ocs_ci/utility/utils.py
> Use json instead of hcl for reading terraform state file

- ocs_ci/ocs/resources/bucket_policy.py
> fix for bucket policy tests in 4.9

- tests/e2e/workloads/quay/test_quay_operator.py
> Quay test on 4.6

- ocs_ci/ocs/ocs_upgrade.py
> Add support for upgrade to ODF 4.9

- ocs_ci/framework/pytest_customization/marks.py
Add skip if marker for ROSA platform
Add lib test to verify the added code
> Add skip if marker for ROSA platform

- tests/manage/mcg/conftest.py
> Skip mcg related test on ROSA platform

- ocs_ci/utility/utils.py
- tests/conftest.py
> Skip UI tests on ROSA platform

- ocs_ci/ocs/resources/storage_cluster.py
> Add multus network check to post install verification

- tests/conftest.py
> log marker args instead of Marker

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/storage_cluster.py
> Verify StorageSystem status

- ocs_ci/utility/kms.py
- tests/conftest.py
- tests/manage/pv_services/pvc_snapshot/test_encrypted_rbd_pvc_snapshot.py
Add test case for creating snapshots of encrypted RBD PVCs and restoring them
> Add test case for snapshot and restore of encrypted RBD PVCs

- tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot_when_snapshotclass_deleted.py
> Tests to verify PVC snapshot feature when snapshotclass deleted

- ocs_ci/framework/conf/ocp_version/ocp-4.10-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.10-upgrade.yaml
> Adding OCP 4.10 config files

- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/scale_lib.py
- tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
Updated code to increase the OSD creation timeout
Removed assert so that exception sets flag to skip other test execution
> PR to fix scale_12_OCS worker nodes OSD

- conf/README.md
- conf/ocsci/set_debug_rook_log_level.yaml
- docs/debugging.md
- ocs_ci/deployment/deployment.py
- ocs_ci/helpers/helpers.py
To debug some ROOK related bugs it was requested to have
ability to enable the DEBUG log level. With this change, it's possible
to do that.
> Enable change ROOK LOG LEVEL during the deployment

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/helpers/lso_helpers.py
- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/tests/test_version.py
- ocs_ci/utility/version.py
> Fix version comparison

- ocs_ci/deployment/deployment.py
Reducing the nooba-endpoint limits as per https://bugzilla.redhat.com/show_bug.cgi?id=2000027
> Reducing limits for nooba-endpoints

- conf/deployment/rhv/ipi_1az_rhcos_3m_3w.yaml
- conf/deployment/rhv/ipi_1az_rhcos_lso_3m_3w.yaml
- conf/ocsci/rhv_ipi.yaml
- ocs_ci/templates/ocp-deployment/install-config-rhv-ipi.yaml.j2
> Add support for custom vCPU configuration in RHV platform

- ocs_ci/utility/ibmcloud.py
- tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
Added timeout sampler to wait volume method
> Added timeout sampler to wait volume method

- ocs_ci/helpers/helpers.py
- tests/conftest.py
- tests/manage/pv_services/test_verify_subpath.py
Test case to verify subpath
OCS-2654 - FT-CEPHFS - Verify Subpath
> Test case to verify subpath

- ocs_ci/ocs/must_gather/must_gather.py
- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/resources/bucket_policy.py
- ocs_ci/ocs/resources/mcg.py
- ocs_ci/ocs/resources/objectbucket.py
- ocs_ci/ocs/ui/mcg_ui.py
- ocs_ci/ocs/utils.py
- ocs_ci/ocs/version.py
- ocs_ci/utility/rgwutils.py
- tests/e2e/scale/test_osd_node_balancing.py
I am opening the second PR with more modules changed here:
https://github.com/red-hat-storage/ocs-ci/pull/4872/
The first PR I will let only few commits related to deployment and version module
> Fix version comparison for more modules

- ocs_ci/ocs/constants.py
- tests/e2e/kcs/test_noobaa_rebuild.py
> [Close loop BZ: 1991361] Test case for noobaa rebuild

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/block_pool.py
- ocs_ci/ocs/ui/storageclass.py
- ocs_ci/ocs/ui/views.py
- tests/conftest.py
- tests/ui/test_create_pool_block_pool.py
Pool management [KNIP-1548](https://issues.redhat.com/browse/KNIP-1548) 
Added UI classes for pool and storageclass (basic RBD) and test that create blockpool use them and delete.
There will more tests added for this PR so review but not merge.
> Block pool UI create use and delete

- pytest.ini
> registering the custom markers

- tests/manage/pv_services/pvc_snapshot/test_restore_snapshot_using_different_sc.py
> Skip snapshot restore using different pool for ODF < 4.9

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
> Install ODF Operator via UI

- ocs_ci/ocs/small_file_workload.py
- tests/e2e/scale/test_scale_small_file_workload.py
> Implement benchmark-operator into test_scale_small_file_workload.py

- ocs_ci/ocs/ui/deployment_ui.py
> Fix UI deployment OCP4.8

- ocs_ci/utility/version.py
> Fixing format and typo in returns

- tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
This PR will give a partial fix for #4907 pass end_fsync parameter while running I/O. 
> Fix storage_type parameteer in the test test_disruptive_during_pod_pvc_deletion

- ocs_ci/deployment/deployment.py
- ocs_ci/framework/conf/default_config.yaml
> Enable console plugin

- ocs_ci/utility/localstorage.py
> Fix version comparison for LSO deployment

- ocs_ci/ocs/cluster.py
> Add retry in scan_cluster method

- tests/e2e/performance/test_pod_reattachtime.py
The only change in this PR is https://github.com/ypersky1980/ocs-ci/pull/new/ypersky_test_pod_reattachtime_10samples
> test_pod_reattachtime.py - increase number of samples from 2 to 10

- ocs_ci/utility/utils.py
Fixes: #4923
Fixes: #4965
This improve the logic to do not write execption log if there is no
build id in catalog source like in stage testing.
Also utilize full_version label in the CSV if available.
> Improve  version reporting

- ocs_ci/deployment/baremetal.py
> Enhance Bare Metal locking

- ocs_ci/ocs/ui/views.py
> ODF4.9 UI deployment, fix "enable_default_porjects" locator

- ocs_ci/templates/ocp-deployment/rhcos_images.yaml
> Add GA config file for BM OCP 4.9

- conf/README.md
- conf/ocsci/ibm_flash.yaml
- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
Fix for IBM Flash system
Fixes: #5044
> Disable add node for IBM Flash system

- ocs_ci/deployment/vmware.py
> adding vm_network to install config

- ocs_ci/ocs/scale_noobaa_lib.py
- tests/e2e/scale/noobaa/test_scale_obc_create_delete.py
OBC scale creation and deletion using Multi cloud Object Gateway
* Creating up to max support number of OBCs, capture creation time in sec.
* Deleting OBCs and capture deleting time in sec.
> Obc creation and deletion time

- ocs_ci/templates/workloads/pgsql/PGSQL_Benchmark.yaml
- tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py
- tests/e2e/lifecycle/pvc_snapshot/test_pgsql_pvc_snapshot.py
- tests/e2e/workloads/pgsql/test_pgsql.py
- tests/e2e/workloads/pgsql/test_pgsql_node_drain.py
- tests/e2e/workloads/pgsql/test_pgsql_node_reboot.py
- tests/e2e/workloads/pgsql/test_pgsql_pod_respin.py
- tests/e2e/workloads/pvc_snapshot_and_clone/test_cloned_and_restored_pvc_resize.py
- tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
> Modify pgbench replicas count to 1 in pgsql functional tests

- tests/manage/mcg/test_bucket_policy.py
Changes done based on: https://bugzilla.redhat.com/show_bug.cgi?id=2008502#c15
> Test object policy fix

- .pre-commit-config.yaml
- ocs_ci/ocs/api_client.py
- ocs_ci/ocs/openstack.py
- requirements-dev.txt
- tox.ini
> Update black version

- ocs_ci/ocs/ui/acm_ui.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/views.py
1. Canceled console validation if not default OCP
2. Added ACM locators,
3. Added ACM navigator class
> Added UI infrastructure for ACM

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/defaults.py
> Change of noobaa operator CSV

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/storage_cluster.py
- tests/manage/z_cluster/test_ceph_default_values_check.py
> Add mon_data_avail_warn to rook ceph config saved values

- tests/manage/mcg/test_bucket_replication.py
Signed-off-by: Amit Berner <aberner@redhat.com>
> skip mcg replication tests for versions below 4.9

- ocs_ci/ocs/ocs_upgrade.py
> Fix for IBM cloud upgrade

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/csv.py
> Add upgrade check for all CSV to be in succeeded state

- tests/ecosystem/upgrade/test_noobaa.py
- tests/ecosystem/upgrade/test_resources.py
> Add red_squad marker to noobaa upgrade tests

- ocs_ci/deployment/flexy.py
- ocs_ci/deployment/vmware.py
- ocs_ci/utility/utils.py
- setup.py
> Adding shutdown_wait_timeout for compute and control-plane machines

- tests/manage/z_cluster/test_osd_heap_profile.py
> Fix Test: text_osd_heap_profile

- .pre-commit-config.yaml
> updating pre-commit version to match with requirements-dev

- ocs_ci/templates/ocs-deployment/storagesystem_odf.yaml
> Aligning storagesystem name with UI naming

- tests/ecosystem/upgrade/test_logging_upgrade.py
- tests/ecosystem/upgrade/test_monitoring_after_ocp_upgrade.py
> Add magenta_squad marker to logging and monitoring upgrade tests

- ocs_ci/framework/main.py
> Remove --rp-launch from main function

- ocs_ci/framework/pytest_customization/ocscilib.py
> Donot fail whole execution when rp_launch_tags not found

- .pre-commit-config.yaml
- requirements-dev.txt
> Updating pre-commit-hooks rev to 4.0.1

- ocs_ci/ocs/bucket_utils.py
> Fix doc string

- conf/deployment/rosa/ipi_3az_rhcos_3m_3w.yaml
> Add ROSA platform config for multi zone availability

- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
> ODF4.9, LSO deployment via UI

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/utility/perf_dash/dashboard_api.py
- setup.py
This module will allow to push the performance test results into the Performance dashboard automatically
and also will give us the ability to read results from the dashboard for comparison between the current test and previous
tests to identify regression/progression in automatic way, within the test.
> Adding Performance Dashboard DB management Module

- conf/ocsci/mcg_only_deployment.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/helpers/helpers.py
- ocs_ci/deployment/helpers/mcg_helpers.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/resources/storage_cluster.py
- tests/conftest.py
- tests/ecosystem/deployment/test_deployment.py
This PR contains following important commits
657808e7041e335acf47f87a13c0b2cdabc905cc : MCG only deployment parameters
74071a257c91ac9c930abcb4bde56e4d4f5a1e67 : MCG Only deployment
801ce425c0bc738ca569e9818016bd5327fd6a3d : MCG only post deployment checks
9dd44f103bacab0ddf348382aa6642e58f5ff930 : post install verification
Fixes: #4980
> MCG Only deployment

- tests/e2e/registry/test_simple_registry_workload.py
> Skip registry workload

- ocs_ci/framework/pytest_customization/ocscilib.py
> Stop adding rp_launch_tags to pytest.ini

- conf/ocsci/vault_external_standalone_ca_only_v1.yaml
- conf/ocsci/vault_external_standalone_ca_only_v2.yaml
> Added polarion id to kms_ca_only configuration files

- ocs_ci/ocs/ui/add_replace_device_ui.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/helpers_ui.py
- ocs_ci/ocs/ui/views.py
> Add capactiy via UI on ODF4.9

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/couchbase_new.py
- ocs_ci/ocs/pillowfight.py
- ocs_ci/templates/workloads/couchbase_new/pillowfight/basic-pillowfight.yaml
- ocs_ci/templates/workloads/couchbase_new/server/cb-operatorgroup.yaml
- ocs_ci/templates/workloads/couchbase_new/server/cb-subscription.yaml
- ocs_ci/templates/workloads/couchbase_new/server/couchbase-data-bucket.yaml
- ocs_ci/templates/workloads/couchbase_new/server/couchbase-worker-secret.yaml
- ocs_ci/templates/workloads/couchbase_new/server/couchbase-worker.yaml
- tests/conftest.py
- tests/e2e/workloads/couchbase/test_couchbase.py
- tests/e2e/workloads/couchbase/test_couchbase_node_drain.py
- tests/e2e/workloads/couchbase/test_couchbase_node_reboot.py
- tests/e2e/workloads/couchbase/test_couchbase_pod_respin.py
*. Couchbase workload is redesigned with new implementation. We use couchbase operator available in OperatorHub for Couchbase cluster deployment.
*. Fixes: #4488 
> Couchbase workload new implementation

- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
> UI deployment, Added refresh page [PopUp]

- tests/ui/test_validation_ui.py
Signed-off-by: Aman Agrawal <amagrawa@redhat.com>
> Skipping ODF Storage System UI validation for OCS 4.8 and below versions

- ocs_ci/deployment/helpers/vsphere_helpers.py
- ocs_ci/deployment/install_ocp_on_rhel.py
- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/ocp-deployment/inventory_haproxy.yaml.j2
- ocs_ci/templates/ocp-deployment/scale_up_terraform_with_folder_structure.tfvars.j2
- ocs_ci/utility/load_balancer.py
> Adding RHEL_MAJOR_OS to scale_up_terraform.tfvars file

- tests/e2e/performance/csi_tests/test_pod_reattachtime.py
> adding ES parameters to test_pod_reattachtime.py test 

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.10-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.9-config.yaml
> Update RHCOS template for OCP 4.9

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/couchbase_new.py
- ocs_ci/ocs/pillowfight.py
- ocs_ci/templates/workloads/couchbase_new/pillowfight/basic-pillowfight.yaml
- ocs_ci/templates/workloads/couchbase_new/server/cb-operatorgroup.yaml
- ocs_ci/templates/workloads/couchbase_new/server/cb-subscription.yaml
- ocs_ci/templates/workloads/couchbase_new/server/couchbase-data-bucket.yaml
- ocs_ci/templates/workloads/couchbase_new/server/couchbase-worker-secret.yaml
- ocs_ci/templates/workloads/couchbase_new/server/couchbase-worker.yaml
- tests/conftest.py
- tests/e2e/workloads/couchbase/test_couchbase.py
- tests/e2e/workloads/couchbase/test_couchbase_node_drain.py
- tests/e2e/workloads/couchbase/test_couchbase_node_reboot.py
- tests/e2e/workloads/couchbase/test_couchbase_pod_respin.py
backport couchbase new implementation to 4.8
Fixes: #5127 
> Couchbase workload new implementation - 4.8 (#5108)

- ocs_ci/deployment/vmware.py
> move constants.VM_MAIN json file if it already exists

- ocs_ci/ocs/ui/validation_ui.py
- ocs_ci/ocs/ui/views.py
Signed-off-by: Aman Agrawal <amagrawa@redhat.com>
> ODF dashboard validation changes as per new OCP console

- ocs_ci/utility/prometheus.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/4767
> Add connection refresh when Prometheus service unavailable

- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
> MCG_ONLY Deployment via UI

- tests/e2e/kcs/test_noobaa_rebuild.py
https://access.redhat.com/solutions/5948631
https://bugzilla.redhat.com/show_bug.cgi?id=2019577
> [Close loop BZ: 2019577] Noobaa rebuild: root-master-key secret deletion

- ocs_ci/deployment/rosa.py
- ocs_ci/ocs/node.py
- ocs_ci/utility/openshift_dedicated.py
> Fix ROSA deployment issues

- tests/ecosystem/upgrade/test_configuration.py
- tests/ecosystem/upgrade/test_resources.py
Done for https://github.com/red-hat-storage/ocs-ci/issues/5021
> Add brown squad mark to tests under test_resources.py and test_configuration.py

- ocs_ci/utility/prometheus.py
fixes https://github.com/red-hat-storage/ocs-ci/issues/4297
> Issue 4297 checks

- tests/e2e/logging/test_openshift-logging.py
The validation is changed as the bug is closed as wont fix and we are hitting this recently on many runs,
https://bugzilla.redhat.com/show_bug.cgi?id=1921068
Fixes: #5157 
> Fixes-5157 Changing the validation to check project in EFK stack

- conf/deployment/aws/upi_1az_rhcos_lso_3m_3w_disconnected.yaml
- conf/deployment/aws/upi_3az_rhcos_lso_3m_3w_disconnected.yaml
- ocs_ci/deployment/aws.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/aws.py
* create and attach volumes to workers
* added configuration files:
- `conf/deployment/aws/upi_1az_rhcos_lso_3m_3w_disconnected.yaml`
- `conf/deployment/aws/upi_3az_rhcos_lso_3m_3w_disconnected.yaml`
> disconnected LSO installation on AWS

- ocs_ci/templates/workloads/smallfile/SmallFile.yaml
- tests/e2e/performance/io_workload/test_small_file_workload.py
updating the benchmark parameters names to align with the upstream benchmark names, so we can collect test results.
> Sf parameters

- ocs_ci/utility/reporting.py
> Add logs URL to RP launch description

- ocs_ci/ocs/resources/objectconfigfile.py
- ocs_ci/ocs/scale_lib.py
- tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
Issues Resolved:
1. Teardown issues, enhanced cleanup to delete all the POD, PVC and Clones
2. Enhanced POD creation using kube_job
TODO:
Running IO's in POD is sequential and takes 1min to complete for 1 POD
there are total 50 PODs which will take ~50mins.
> PVC Bulk Clone Performance Test enhancement

- ocs_ci/deployment/helpers/lso_helpers.py
> Change volumeMode to Filesystem for MCG only deployment in localstorage mode

- tests/e2e/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py
> Add bugzilla marker to test

- tests/e2e/performance/io_workload/test_small_file_workload.py
In this PR i fix the logs collection to run in any case  (success/failed) and not only in case of success run, so we can investigate benchmark failure.
> SF| collect test logs after test finish

- tests/conftest.py
PR to address teardown issues in "test_pvc_bulk_creation_deletion_performance::TestPVCCreationPerformance::test_bulk_pvc_creation_deletion_measurement_performance" test. Since PVCs were deleted as part of the test teardown stage used to fail. Added the try-except block to log message in case instance.reclaim_policy attribute is empty(PVC is already in deleted state)
> PR to fix teardown issue in "test_bulk_pvc_creation_deletion_measurement_performance"

- tests/conftest.py
> Add ocs_build attribute to RP launches

- tests/e2e/performance/csi_tests/test_pvc_attachtime.py
> adding missing items for teardown

- tests/e2e/scale/noobaa/test_hsbench.py
> [Close loop BZ: 1998680]: Object bucket with large number of objects

- ocs_ci/utility/vsphere.py
> Function to remove VMs from inventory

- ocs_ci/framework/conf/ocs_version/ocs-4.10.yaml
> Add latest stable tag for ODF 4.10

- ocs_ci/helpers/helpers.py
- tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
Fix https://github.com/red-hat-storage/ocs-ci/issues/5030
> Increase timeout of waiting for the new node's rack or zone in the test "test_crashcollector_pod_existence_on_ceph_pods_running_nodes"

- tests/e2e/system/test_mcg_recovery.py
> Added polarion id -2

- ocs_ci/ocs/constants.py
> Adding yellow squad for managed-services

- conf/deployment/aws/ipi_3az_rhcos_mcg_only_3m_3w.yaml
- conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_mcg_only_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vmfs_mcg_only_3m_3w.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_mcg_only_3m_3w.yaml
> Adding config files for MCG Only deployment for various platforms

- ocs_ci/framework/conf/ocs_version/ocs-4.6-eus.yaml
- ocs_ci/framework/conf/ocs_version/ocs-4.7-eus.yaml
- ocs_ci/framework/conf/ocs_version/ocs-4.8-eus.yaml
- ocs_ci/framework/main.py
> Add EUS config files

- ocs_ci/helpers/sanity_helpers.py
- ocs_ci/ocs/resources/objectbucket.py
- tests/conftest.py
- tests/manage/mcg/test_host_node_failure.py
> Extend tier4 OBC helper health check timeout

- tests/conftest.py
> Improve condition in pytest collect modify items hook

- ocs_ci/templates/workloads/fio/benchmark_fio_cmp.yaml
- tests/e2e/performance/io_workload/test_fio_benchmark.py
> Change FIO compressed test timeout

- ocs_ci/ocs/constants.py
> Fix purple squad

- tests/manage/mcg/test_bucket_deletion.py
> [Close loop BZ: 1980299]: Delete default S3 bucket

- ocs_ci/framework/conf/ocp_version/ocp-4.10-config.yaml
> Update OCP 410 RHCOS template

- ocs_ci/ocs/perfresult.py
- tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
This PR implements sending test results to the ES server.
> Ypersky bulk clone performance es improvement

- ocs_ci/framework/conf/ocp_version/ocp-4.10-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.10-upgrade.yaml
> update OCP installer version to nightly

- ocs_ci/framework/conf/default_config.yaml
> Defaulting ocs-ci to ODF 4.10

- tests/conftest.py
- tests/e2e/workloads/ocp/logging/test_openshift-logging.py
> Fixes:5159

- ocs_ci/ocs/node.py
- ocs_ci/ocs/perftests.py
- ocs_ci/utility/perf_dash/dashboard_api.py
- tests/e2e/performance/io_workload/test_small_file_workload.py
Adding basic function to push results into the performance dashboard
and push the SmallFiles benchmark results into the dashboard
> Push SmallFiles results into performance dashboard

- tests/e2e/workloads/ocp/logging/test_openshift-logging.py
> Adding back the setup fixture for openshift-logging

- tests/e2e/system/test_mcg_recovery.py
> Change the locator of ignore_leftover decorator

- ocs_ci/ocs/machine.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/vsphere.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Fix https://github.com/red-hat-storage/ocs-ci/issues/5065
> Create a new method 'terminate_nodes' for vSphere platform

- ocs_ci/ocs/ocs_upgrade.py
> get locators only incase of UI upgrade

- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/pv_services/pvc_clone/test_encrypted_rbd_pvc_clone.py
- tests/manage/pv_services/pvc_snapshot/test_encrypted_rbd_pvc_snapshot.py
- tests/manage/pv_services/test_rbd_pv_encryption.py
> Skip PV encryption tests if Vault config is not present

- ocs_ci/deployment/baremetal.py
> Update bare metal deployment code to use semantic version

- ocs_ci/templates/ocp-deployment/rhcos_images.yaml
> Add BM Config Files for OCP 4.10

- tests/e2e/performance/csi_tests/test_pvc_bulk_creation_deletion_performance.py
The PR handles sending results of the test_pvc_bulk_creaton_deletion_performance.py to the ES. 
Please note that the file has 2 tests, each one of them sends different results and eventually two different tables/reports should appear in the Performance Dashboard.
> Ypersky test pvc bulk creation es

- ocs_ci/ocs/perftests.py
- tests/e2e/performance/io_workload/test_fio_benchmark.py
> FIO | push performance results into the dashboard

- ocs_ci/ocs/acm/acm.py
- ocs_ci/ocs/acm/acm_constants.py
- ocs_ci/ocs/disaster_recovery/acm.py
- ocs_ci/ocs/ui/views.py
- tests/ecosystem/deployment/test_acm.py
1. Add Page Navigator for ACM console
2. Add ACM detection (Running&version)
3. Add page view for ACM Console (Partial, just whats needed for Import clusters procedure)
4. Add import cluster with ACM automated procedure
> Import cluster with acm

- ocs_ci/deployment/deployment.py
> Wait after approving install plan

- ocs_ci/ocs/perf_pgsql.py
- tests/e2e/performance/io_workload/test_perf_pgsql.py
This test will run pgsql performance benchmark and measure transaction per second and latency.
Steps:-
-> Deploy benchmark operator
-> Create PGSQL pod and pgbench pod
-> Run pgbench workload on pgbench pod and measure the TPS, latency
> PGSQL AUTOMATION

- ocs_ci/ocs/resources/packagemanifest.py
> Fix getting CSV from install plan

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/node.py
- tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
- tests/manage/z_cluster/nodes/test_toleration.py
Automates BZ : https://bugzilla.redhat.com/show_bug.cgi?id=1992472
> <Closed loop BZ: 1992472> Non-ocs Taint and toleration

- ocs_ci/ocs/ocs_upgrade.py
> Fix manual approval strategy upgrade for 4.9

- ocs_ci/framework/__init__.py
- ocs_ci/framework/main.py
- ocs_ci/framework/pytest_customization/ocscilib.py
> Introduce a common cli option '--default-cluster-context-index'

- ocs_ci/ocs/must_gather/const_must_gather.py
- ocs_ci/ocs/must_gather/must_gather.py
https://bugzilla.redhat.com/show_bug.cgi?id=2014849
> Must Gather, verify ceph command does not return an error

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/machine.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/vsphere.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
fix https://github.com/red-hat-storage/ocs-ci/issues/5278
> Fix the test 'test_automated_recovery_from_stopped_node_and_start' to run with vsphere ipi

- ocs_ci/ocs/resources/mcg.py
Because of this BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=2011845
oc cp command is problematic and I found out that rsync works more
reliable. So moving to oc rsync instead of oc cp.
> Use rsync for copy noobaa CLI binary

- ocs_ci/ocs/cluster_load.py
- ocs_ci/utility/prometheus.py
Fixes [#5305](https://github.com/red-hat-storage/ocs-ci/issues/5305)
> Log cluster load massages in debug instead of info

- tests/e2e/performance/csi_tests/test_pod_reattachtime.py
> pod_reattach TC - push the results into the performance dashboard

- ocs_ci/deployment/deployment.py
> Improving manual approval strategy installation and wait for CSV

- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/helpers/sanity_helpers.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/resources/mcg.py
- ocs_ci/ocs/utils.py
- tests/conftest.py
> Enables to run test cases on MCG only deployment

- ocs_ci/deployment/vmware.py
> changing keep_on_remove state to false in state file

- tests/ecosystem/upgrade/test_upgrade_ocp.py
BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=2038690
> Increase timeout for rebalance after OCP upgrade

- tests/conftest.py
> skip record_testsuite_property for OCP only deployments

- tests/e2e/scale/noobaa/test_scale_bucket_replication.py
Test unidirectional bucket replication adding objects to:
- Object buckets - backingstore
- Namespace buckets - namespacestore
Test bidirectional bucket replication.
> Scale bucket replication test cases

- ocs_ci/deployment/vmware.py
> Delete template folder during post destroy

- ocs_ci/ocs/machine.py
Fixed the platform config string when create_custom_machineset 
> Fixing Scale endpoint test failure

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/helpers_ui.py
- ocs_ci/ocs/ui/views.py
Setups:
*FULL DEPLOYMENT - Internal cluster
**There is option to enable Taint Nodes via UI
> OCP4.10, UI deployment

- tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
Enhanced TC test_pvc_bulk_clone_performance.py to integrated dashboard automation.
> Enhanced TC tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py for Dashboard Integration

- tests/e2e/performance/csi_tests/test_pvc_attachtime.py
Adding test_pod_start_time_results for pushing results do dashboard. 
> adding push to dashboard

- ocs_ci/ocs/ocs_upgrade.py
> Fix missing ocs secret for upgrade to 4.9 on IBM Cloud

- ocs_ci/utility/reporting.py
> Add run_id to rp launch attributes

- ocs_ci/helpers/helpers.py
In This PR i add another parameter to the function - fs_name (default value of None for backward compatibility) so we can create the storage class on new ceph-filesystem and not only on the default one.
I also remove some code duplication from the function.
> improve the create_storage_class helper function

- conf/README.md
- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
- conf/ocsci/ocs-live-must-gather.yaml
- conf/ocsci/odf-live-must-gather.yaml
- docs/upgrade.md
- docs/usage.md
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/conf/ocs_version/ocs-4.10.yaml
- ocs_ci/framework/conf/ocs_version/ocs-4.5.yaml
- ocs_ci/framework/conf/ocs_version/ocs-4.6.yaml
- ocs_ci/framework/conf/ocs_version/ocs-4.7.yaml
- ocs_ci/framework/conf/ocs_version/ocs-4.8.yaml
- ocs_ci/framework/conf/ocs_version/ocs-4.9.yaml
- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/utils.py
- ocs_ci/utility/reporting.py
Related BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=2035180
Fixes: #4544
> Update live must gather image for ODF

- tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
> Skip the test test_del_mon_svc below OCS 4.7 version

- ocs_ci/ocs/utils.py
> Must-Gather, disconnected environment, bz-1974959

- ocs_ci/deployment/disconnected.py
- properly handle disconnected upgrade from internal builds and from live content
> Fix disconnected live upgrade

- ocs_ci/utility/utils.py
> Fixing concatenation of variable

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/defaults.py
> Verify odf-csi-addons during deployment

- tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
This PR implements sending test results to the ES and pushing the results to Performance Dashboard.
> Ypersky multi clone dashboard

- conf/ocsci/aws_minimal_deployment.yaml
- conf/ocsci/vsphere_minimal_deployment.yaml
Signed-off-by: Anna Sandler <asandler@redhat.com>
minimal deployment feature is available only via UI install of ODF. added UI deployment parameter to configuration files of minimal clusters
> Add UI deployment parameter to minimal deployment config files 

- tests/manage/monitoring/prometheusmetrics/test_mcg_hpa.py
fixing https://github.com/red-hat-storage/ocs-ci/issues/5361
by moving the test from horizontal-pod-autoscaler-v1 API to
the v2
> upate test_mcg_hpa to horizontal-pod-autoscaler-v2

- tests/manage/z_cluster/test_mon_data_avail_warn.py
> Test mon disk threshold when disk usage >= 85%

- conf/ocsci/rosa.yaml
- ocs_ci/deployment/rosa.py
- ocs_ci/utility/openshift_dedicated.py
- ocs_ci/utility/rosa.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/5262
> Change rosa cli version to 1.1.7

- ocs_ci/deployment/deployment.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2043349
> increase mon timeout during deployment

- ocs_ci/ocs/pgsql.py
- tests/conftest.py
- tests/e2e/flowtest/pvc_snapshot_and_clone/test_pgsql_pvc_snapshot_and_clone.py
- tests/e2e/flowtest/pvc_snapshot_and_clone/test_pgsql_pvc_snapshot_and_clone_with_base_operation.py
- tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py
- tests/e2e/lifecycle/pvc_snapshot/test_pgsql_pvc_snapshot.py
- tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
> Encrypt PVC support for snapshot and clone

- .github/CODEOWNERS
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/job.py
- ocs_ci/ocs/resources/objectconfigfile.py
- ocs_ci/ocs/resources/topology.py
- ocs_ci/templates/workloads/logwriter/README.md
- ocs_ci/templates/workloads/logwriter/cephfs.logreader.yaml
- ocs_ci/templates/workloads/logwriter/cephfs.logwriter.yaml
- ocs_ci/templates/workloads/logwriter/cephfs.reproducer.yaml
- tests/e2e/workloads/test_data_consistency.py
Implementing https://github.com/red-hat-storage/ocs-ci/issues/5242
> Test case for bz 1989301 reproducer

- conf/README.md
- conf/deployment/aws/upi_1az_rhel7_3m_3w.yaml
- conf/deployment/aws/upi_1az_rhel7_lso_3m_3w.yaml
- conf/deployment/aws/upi_3az_rhel7_3m_3w.yaml
- conf/deployment/aws/upi_3az_rhel7_lso_3m_3w.yaml
- conf/ocsci/aws_upi_rhel7_workers.yaml
- conf/ocsci/aws_upi_rhel8_workers.yaml
- ocs_ci/deployment/aws.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/platform_nodes.py
> Add RHEL 7.9 AMI and possibility to define RHEL 8

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/helpers_ui.py
- ocs_ci/ocs/ui/views.py
> Add capacity via UI on OCP4.10

- conf/ocsci/dr_workload.yaml
- conf/ocsci/multicluster_acm_cluster.yaml
- conf/ocsci/multicluster_dr_rbd.yaml
- conf/ocsci/multicluster_primary_cluster.yaml
- conf/ocsci/submariner_upstream.yaml
- ocs_ci/deployment/acm.py
- ocs_ci/deployment/deployment.py
- ocs_ci/framework/__init__.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/dr/dr_workload.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/utils.py
- ocs_ci/templates/ocs-deployment/multicluster/dr_aws_s3_profile.yaml
- ocs_ci/templates/ocs-deployment/multicluster/dr_policy_acm_hub.yaml
- ocs_ci/templates/ocs-deployment/multicluster/mirror_peer.yaml
- ocs_ci/templates/ocs-deployment/multicluster/odf_multicluster_orchestrator.yaml
- ocs_ci/templates/ocs-deployment/multicluster/odf_orchestrator_operatorgroup.yaml
- ocs_ci/templates/ocs-deployment/multicluster/odr_s3_secret.yaml
- ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_cluster_operator.yaml
- ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_hub_operator.yaml
- ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_system.yaml
- ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_system_operatorgroup.yaml
- ocs_ci/templates/ocs-deployment/multicluster/volume_replication_class.yaml
- ocs_ci/utility/utils.py
- setup.py
- tests/conftest.py
- tests/ecosystem/deployment/test_deployment.py
1.odf multiclustr orchestrator deployment and config
2.mirror peer configuration and deployment for rbd
3.openshift dr-cluster and dr-hub operator deployment and config
4.volumereplication class creation
5.odr secret creation
6. DR workload
> OCS deployment with ACM  and DR workload

- tests/e2e/scale/noobaa/test_scale_namespace_crd.py
Create AWS and RGW multi type test cases for namespace resources.
> Add namespace resources creation with multi type test cases.

- ocs_ci/utility/utils.py
> Fix OCP version string while building the testrun name

- tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
In this PR test_pvc_clone_performance_results are pushed into ES server and dashboard. Also base class is changed from E2Etest to PASTest
> Dashboard Integration for test_pvc_clone_performance

- ocs_ci/deployment/baremetal.py
> Improve logging of BM when resource are locked

- tests/conftest.py
> skip pager duty integration till it get fix

- ocs_ci/ocs/ui/base_ui.py
Change the `sleep_time` parameter on `page_has_loaded` function from 10 sec to 1 sec.
#5417
> Fix OCS4.7 UI deployment

- ocs_ci/ocs/ui/pvc_ui.py
- ocs_ci/ocs/ui/views.py
- tests/ui/test_pvc_ui.py
Test case to verify PVC clone from GUI
> Test case to verify PVC clone from GUI

- docs/index.rst
- docs/multicluster_test_example.md
> Add example for multicluster test scenario

- ocs_ci/ocs/ui/validation_ui.py
- ocs_ci/ocs/ui/views.py
fixed #5407 
Signed-off-by: Aman Agrawal <amagrawa@redhat.com>
> Wait and version fixes

- ocs_ci/ocs/constants.py
See also [Bug 2052390](https://bugzilla.redhat.com/show_bug.cgi?id=2052390).
> add newly required packages for disconnected deployment - ODF 4.10

- ocs_ci/utility/pagerduty.py
- ocs_ci/utility/rosa.py
- tests/conftest.py
> Fix ROSA deployment and pagerduty service creation

- ocs_ci/ocs/perftests.py
> adding the backed SC to platform name in the performance dashboard

- conf/deployment/rosa/ipi_1az_rhcos_3m_3w_m52x.yaml
- conf/deployment/rosa/ipi_1az_rhcos_3m_3w_m54x.yaml
- conf/deployment/rosa/ipi_3az_rhcos_3m_3w_m52x.yaml
- conf/deployment/rosa/ipi_3az_rhcos_3m_3w_m54x.yaml
> Update config env data for missing add-on parameter

- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_converged_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_converged_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_converged_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_converged_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
- ocs_ci/utility/rosa.py
Add config for rosa RH-ODF managed service provider configs,
consumers config and its add-on/instances combination.
Rename existing config names with a minor change
> Add configs for rosa RH-ODF-MS provider,consumer ad-ons and its combinations

- tests/e2e/workloads/test_data_consistency.py
Addressing https://github.com/red-hat-storage/ocs-ci/issues/5459
> Additional rsync debugging in OCS-2735

- tests/e2e/scale/noobaa/test_scale_namespace_rpc.py
> Skip namespace bucket creation via MCG RPC.

- ocs_ci/ocs/jenkins.py
https://bugzilla.redhat.com/show_bug.cgi?id=2052568
> Fix "pipeline-utility-steps" plugin version on Jenkins workload

- setup.py
> Update jinja2 template

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
> Add marker for managed service provider and consumer

- tests/ui/test_pvc_ui.py
> Fix test case test_clone_pvc

- pytest.ini
- setup.py
> Move pytest to 6.2.5

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/framework/__init__.py
- ocs_ci/ocs/defaults.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/utility/connection.py
- ocs_ci/utility/deployment.py
- ocs_ci/utility/utils.py
> Dynamic external cluster installation

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/disconnected.py
- ocs_ci/deployment/flexy.py
- ocs_ci/deployment/helpers/lso_helpers.py
- ocs_ci/utility/ssl_certs.py
- ocs_ci/utility/utils.py
> Wait for machineConfigPool after applying SSL cert

- ocs_ci/deployment/helpers/external_cluster_helpers.py
> get rgwendpoint port dynamically

- ocs_ci/ocs/utils.py
> removing tini from external tookbox config in external mode deployment

- ocs_ci/utility/connection.py
> Docstring correction

- ocs_ci/ocs/must_gather/const_must_gather.py
- ocs_ci/ocs/must_gather/must_gather.py
https://bugzilla.redhat.com/show_bug.cgi?id=2026342
> Check Noobaa_diagnose dir content

- setup.py
> Install yq as it's required for AWS UPI deployment

- ocs_ci/deployment/helpers/external_cluster_helpers.py
> get RHEL version from external RHCS cluster

- ocs_ci/framework/conf/ocp_version/ocp-4.11-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.11-upgrade.yaml
For few bug verification, we need OCP 4.11 cluster.
> Add OCP 4.11 config files

- ocs_ci/ocs/perftests.py
- tests/e2e/performance/csi_tests/test_pvc_attachtime.py
This PR making the function which checking the test results an pushing them to the performance dashboard as general function to prevent code duplication.
it also implement it in the pod_attache_time test (as the first test to implement) to verify it is working.
> General function to check test results

- ocs_ci/utility/kms.py
- tests/conftest.py
> Donot raise exception during pytest collections

- ocs_ci/ocs/ui/base_ui.py
> Fix key error in case of 'import_clusters_to_acm'

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/defaults.py
- ocs_ci/templates/CSI/rbd/csi-kms-connection-details.yaml
- ocs_ci/templates/CSI/rbd/rbd-csi-vault-token-reviewer.yaml
- ocs_ci/templates/CSI/rbd/tenant-sa.yaml
- ocs_ci/templates/CSI/rbd/tenant-vault-configmap.yaml
- ocs_ci/utility/kms.py
- tests/conftest.py
Libraries for vaulttenantsa encryptionKMSType used for service account per namespace PV encryption
Issue: [PV encryption - service account per namespace](https://issues.redhat.com/browse/RHSTOR-1883)
> Add libraries for vaulttenantsa encryptionKMSType

- ocs_ci/ocs/constants.py
- tests/manage/z_cluster/test_ceph_default_values_check.py
updated the osd_memory_target_cgroup_limit_ratio to 0.8 wrt bug 2012082 in ocs_ci/ocs/constants.py file
> updated the osd_memory_target_cgroup_limit_ratio to 0.8 wrt bug 2012082

- ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-minus1-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-upgrade.yaml
> Adding OCP 4.10 GA config files

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/quay_operator.py
- tests/e2e/workloads/app/quay/test_quay_operator.py
> Quay workload api ops test

- ocs_ci/deployment/vmware.py
> delete csi users during cluster deletion

- ocs_ci/framework/conf/ocs_version/ocs-4.11.yaml
- ocs_ci/framework/main.py
> Prepare for ODF 4.11

- ocs_ci/ocs/managedservice.py
> Disable odf operator

- tests/conftest.py
https://issues.redhat.com/browse/OCSQE-699
> Add markers as property to junit result file

- ocs_ci/deployment/rosa.py
> Add host_network_update for rosa

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/utility/rosa.py
> Add on boarding-validation-key parameter in provider add-on installation

- setup.py
> Pin pytest-metadata version

- conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v1.yaml
- conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v2.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_vault_v1.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_vault_v2.yaml
> Add KMS vault prod config files without namespaces

- ocs_ci/utility/aws.py
- ocs_ci/utility/rosa.py
> Update get_providers_subnet function

- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/ocs/ocs_upgrade.py
> External cluster upgrade changes for ODF 4.10

- ocs_ci/utility/rosa.py
> Enhancing timeout for rosa Create commands

- conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
> Enabling host network update for provider

- ocs_ci/ocs/must_gather/const_must_gather.py
- ocs_ci/ocs/must_gather/must_gather.py
https://bugzilla.redhat.com/show_bug.cgi?id=2042866
> Added mg files on ODF4.10 [bz-2042866]

- ocs_ci/ocs/managedservice.py
> unifying the use of addon_name config key defination

- conf/examples/vault_external_standalone_mode.yaml
- conf/ocsci/vault_external_standalone_kube_auth_v1.yaml
- conf/ocsci/vault_external_standalone_kube_auth_v2.yaml
- conf/ocsci/vault_external_standalone_mode_v2.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/openshift-infra/vault/ocs-kms-connection-details.yaml
- ocs_ci/utility/kms.py
- ocs_ci/utility/utils.py
- tests/conftest.py
This PR implements the requirements for automating deployment of clusterwide encryption cluster using KMS with kubernetes authentication method.
JIRA: https://issues.redhat.com/browse/RHSTOR-2080
> Clusterwide encryption using KMS with kubernetes auth method

- .pre-commit-config.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/cluster_load.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/fiojob.py
- ocs_ci/ocs/tests/test_fiojob.py
- ocs_ci/utility/kms.py
- requirements-dev.txt
- tests/manage/monitoring/test_workload_with_distruptions.py
- tox.ini
> update black version to 22.3.0

- ocs_ci/deployment/helpers/vsphere_helpers.py
- ocs_ci/deployment/install_ocp_on_rhel.py
- ocs_ci/deployment/vmware.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/templates/ocp-deployment/scale_up_terraform_with_folder_structure.tfvars.j2
Fixes: #5373 
This PR will support the RHEL8 deployment in vSphere platform
> RHEL8 deployment in vsphere platform

- tests/conftest.py
> Add retry to report version fixture

- ocs_ci/utility/managedservice.py
- ocs_ci/utility/rosa.py
Update rosa add-on install command for onbording ticket
and storage-provider-endpoint parameters
> Update consumer add-on install rosa command for additional parameter 

- conf/ocsci/disable_pagerduty.yaml
- tests/conftest.py
> add disable pagerduty config

- ocs_ci/deployment/rosa.py
> Fix#5660 host network update for source

- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_converged_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_converged_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_converged_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_converged_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_converged_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
- conf/ocsci/rosa.yaml
- ocs_ci/deployment/rosa.py
- ocs_ci/utility/rosa.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/5666
> Fix region config place for ROSA deployment

- ocs_ci/framework/conf/default_config.yaml
> Update default storage cluster size as per change in add-on default

- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
- ocs_ci/utility/rosa.py
> Add size and unit parameters for consumer

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/constants.py
The name of cephfilesystemsubvolumegroup is not 'csi' in MS consumer. So changing the code to fetch the correct name of the cephfilesystemsubvolumegroup.
> Get cephfilesystemsubvolumegroup

- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_converged_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_converged_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_converged_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_converged_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_converged_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
- conf/ocsci/rosa.yaml
> increase rosa cli version to v1.1.12

- ocs_ci/utility/kms.py
> Add version check for VAULT_AUTH_METHOD

- tests/e2e/scale/noobaa/test_scale_bucket_replication.py
Added bucket verification timeout, and test case IDs.
> Scale bucket replication

- ocs_ci/ocs/cosbench.py
- tests/e2e/performance/mcg/test_mcg_cosbench.py
Create cosbench test case  to collect performance number for MCG.
> MCG Cosbench performance test

- ocs_ci/templates/ocp-deployment/install-config-rhv-ipi.yaml.j2
> Add affinityGroups and affinityGroupsNames for RHV deployment

- tests/manage/z_cluster/test_delete_osd_deployment.py
This test automates [BZ-2032656](https://bugzilla.redhat.com/show_bug.cgi?id=2032656)
> Add test case for OSD deployment deletion

- ocs_ci/ocs/must_gather/must_gather.py
> skip noobaa diagnostics on managed service platform

- ocs_ci/ocs/constants.py
- tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Signed-off-by: asagare <asagare@fedora.redhat.com>
> "Adding toleration to the OcsInitialization custom resource inside the spec"

- ocs_ci/utility/rosa.py
> Disable auto mode for cluster creation

- tests/e2e/workloads/test_data_consistency.py
fixes https://github.com/red-hat-storage/ocs-ci/issues/5710
> log reader writer: local image mirroring when disconnected

- ocs_ci/deployment/aws.py
- ocs_ci/ocs/node.py
> Update flag of --delete-local-data in all locations since it's deprecated

- docs/getting_started.md
- setup.py
> Remove yq from python requirements

- ocs_ci/deployment/deployment.py
> Wait till subscribe appear before checking for version

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/validation_ui.py
- ocs_ci/ocs/ui/views.py
Covering-
1. Test case failure seen here due to change in locator -
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/3837/
2. `CRITICAL` log seen in the same run id due to change in locator for below test function-
tests/ui/test_validation_ui.py::TestUserInterfaceValidation::test_dashboard_validation_ui
2. Bug- ODF dashboard name change
https://bugzilla.redhat.com/show_bug.cgi?id=2036194
Discussed here- https://chat.google.com/room/AAAAEDRLC3U/Ie1GQk7Bt4A
> Addressing ODF 4.10 console changes

- tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Removes test test_node_maintenance_restart_activate[master]
Signed-off-by: Krishnaram Karthick Ramdoss <kramdoss@redhat.com>
> Fixes #5608

- tests/manage/monitoring/pagerduty/test_ceph.py
- tests/manage/monitoring/pagerduty/test_deployment_status.py
- tests/manage/monitoring/prometheus/test_capacity.py
- tests/manage/monitoring/prometheus/test_deployment_status.py
- tests/manage/monitoring/prometheus/test_rgw.py
- tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
- tests/manage/monitoring/prometheusmetrics/test_rgw.py
- tests/manage/monitoring/sendgrid/test_capacity.py
- tests/manage/monitoring/test_workload_example.py
- tests/manage/monitoring/test_workload_fixture.py
- tests/manage/monitoring/test_workload_with_distruptions.py
> Update monitoring tests with managed services markers

- tests/manage/mcg/test_multipart_upload.py
> Skip tier3 mp test < 4.10

- tests/manage/monitoring/conftest.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/5746
> Fix condition for monitor down alerting tests

- tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py
This PR Fix the issue of trying to dump the results to json file in the wrong path.
> fix the test_bulk_pod_attachtime_performance.py dumping results to file

- ocs_ci/ocs/exceptions.py
- ocs_ci/utility/prometheus.py
fixes https://github.com/red-hat-storage/ocs-ci/issues/5743
> remove assert statements from PrometheusAPI

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/pvc_ui.py
> PVC UI code enhancement

- ocs_ci/ocs/managedservice.py
- tests/managed-service/test_post_installation_state.py
> Add test for consumer's subvolumegroup and cephblockpool

- ocs_ci/ocs/cosbench.py
- tests/e2e/workloads/app/cosbench/test_cosbench.py
> Cosbench workload: small, medium and large size objects

- tests/manage/pv_services/conftest.py
- tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py
Skip snapshot tests on MS platform.
Bug - 2069367
> Skip snapshot tests on MS platform

- ocs_ci/ocs/bucket_utils.py
- ocs_ci/ocs/resources/objectbucket.py
- ocs_ci/utility/utils.py
- tests/manage/rgw/conftest.py
- tests/manage/rgw/test_obc_quota.py
Bz: https://bugzilla.redhat.com/show_bug.cgi?id=1940823
to check if quota feature on rgw bucket works in two scenarios:
* when applied
* when modified with new quota, does that new quota gets applied to the bucket
> #Bz1940823 test obc quota feature

- tests/managed-service/test_post_installation_state.py
> Add cephresources check

- tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py
This PR reduce the runtime of the test from ~4.5 Hours to ~1 Hour
> Bulk attach improvement

- ocs_ci/deployment/vmware.py
- ocs_ci/utility/utils.py
- ocs_ci/utility/version.py
> Fix ignition version for OCP 4.11

- conf/README.md
- conf/ocsci/ibmcloud_disable_odf_addon_deployment.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/resources/mcg.py
Add the logic to deploy ocs with addon
> Add the logic to deploy ocs with addon

- ocs_ci/deployment/deployment.py
> Avoid creating duplicate namespace and operator group

- ocs_ci/ocs/resources/storage_cluster.py
> Add storagecluster postinstall checks

- ocs_ci/framework/pytest_customization/marks.py
- tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_clone.py
- tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
- tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption.py
> Skip PV encryption tests on disconnected and proxy clusters

- ocs_ci/utility/rosa.py
> Support for ocp installer version parameter for MS ROSA deployment

- tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
This PR handles 2 problems: 
1) ES dump bug fix ( cased all the tests cases to fail)
2) Optimises test by replacing teardown factories by deleting the objects without teardown factory. 
> ES dump bug fix 

- ocs_ci/templates/ocp-deployment/rhcos_images.yaml
> Add BM Config Files for OCP 4.11

- ocs_ci/utility/kms.py
- tests/conftest.py
- tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
Automates the following epic partially:
[RHSTOR-1883](https://issues.redhat.com/browse/RHSTOR-1883): PV encryption - service account per namespace - Tech Preview
> Add test cases for PV encryption using vaulttenantsa

- ocs_ci/ocs/resources/storage_cluster.py
> Add some consumer cluster checks

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/resources/storage_cluster.py
W/A issue:
https://github.com/red-hat-storage/ocs-ci/issues/5812
> W/A for nooobaa 4.10 operator installed on ODF 4.9

- ocs_ci/ocs/constants.py
- tests/managed-service/test_post_installation_state.py
> Add provider server log test

- ocs_ci/utility/kms.py
- tests/conftest.py
> Fix auth_path assignment

- ocs_ci/ocs/cosbench.py
- tests/e2e/performance/mcg/test_mcg_cosbench.py
MCG cosbench: upload performance date to portal.
> upload performance data to portal.

- ocs_ci/ocs/managedservice.py
- ocs_ci/ocs/resources/storage_cluster.py
- tests/managed-service/test_post_installation_state.py
> Add test for ceph clients in provider cluster

- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
> commenting sensitive variable as current terraform doesn't support

- Docker_files/performance_image
- Docker_files/scripts/multiple_files.sh
This PR add to the performance image a script to extract the LinuxKernel on the pod.
it also add the LinuxKernet tar.gz file to the image instead of pulling it every time the test on the pod is running.
> Update performance image

- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/ocs/exceptions.py
> get RGW endpoint port using config dump

- ocs_ci/ocs/resources/objectbucket.py
- tests/manage/rgw/test_obc_quota.py
> RGW malformed yaml fix

- ocs_ci/deployment/vmware.py
- ocs_ci/utility/utils.py
> update terraform ignition provider path for destroy job

- tests/conftest.py
- tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
> Increased timeout for some test failures

- ocs_ci/ocs/resources/mcg.py
> Wait for the pod to reach running state before doing rsh into it

- tests/manage/mcg/ui/test_mcg_ui.py
- tests/ui/test_add_capacity_ui.py
- tests/ui/test_capacity_breakdown_ui.py
- tests/ui/test_pvc_ui.py
- tests/ui/test_quickstarts.py
- tests/ui/test_validation_ui.py
Proposed in the email `[Important] Proposal for a change in OCS-CI`, also discussed in the UI automation sync-up call.
> Changing fixture scope to class for improving performance and reducing test execution time for UI test cases

- ocs_ci/ocs/machine.py
- ocs_ci/ocs/node.py
- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
fix https://github.com/red-hat-storage/ocs-ci/issues/5447
> Get the node in the same rack or zone of the new added node

- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_converged_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_converged_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_converged_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_converged_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_converged_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/utility/rosa.py
> Update rosa cli version to 1.2.0 and add in default config

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/pod.py
> Update wait_for_storage_pods() to ignore controller detect version pods and check correct state for osd prepare pods

- ocs_ci/framework/conf/default_config.yaml
> Defaulting ocs-ci to ODF 4.11

- tests/manage/mcg/test_bucket_policy.py
Test part of QE Escalations coverage
> Closed loop 2054540: mpu with bucket policy

- ocs_ci/ocs/resources/storage_cluster.py
> Move the storage system verification after ceph helth.

- ocs_ci/ocs/platform_nodes.py
> Implement get_node_by_attached_volume for vSphere platform

- ocs_ci/ocs/resources/storage_cluster.py
> Add prometheus version check

- conf/examples/acm_hub_downstream_image.yaml
- conf/examples/acm_hub_unreleased_image.yaml
- conf/ocsci/acm_hub_unreleased_deploy.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/constants.py
> Change acm hub downstream references to unreleased

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/multicluster_deployment.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/ui/acm_ui.py
- ocs_ci/ocs/ui/views.py
- ocs_ci/templates/ocs-deployment/multicluster/dr_policy_acm_hub.yaml
- ocs_ci/templates/ocs-deployment/multicluster/mirror_peer.yaml
- ocs_ci/templates/ocs-deployment/multicluster/odf_multicluster_orchestrator.yaml
- ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_hub_operator.yaml
- ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_system_operatorgroup.yaml
- ocs_ci/utility/utils.py
> RDR changes for 4.10

- ocs_ci/deployment/helpers/external_cluster_helpers.py
> Download external exporter script based on csv

- tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Modify the test given below to run on Managed Services platform.
tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py::TestResourceDeletionDuringPvcExpansion::test_resource_deletion_during_pvc_expansion
> Modify test test_resource_deletion_during_pvc_expansion for MS

- ocs_ci/deployment/aws.py
- ocs_ci/framework/conf/default_config.yaml
> Adding bootstrap instance type for AWS UPI deployments

- ocs_ci/utility/aws.py
By default ListResourceRecordSets returns single page results, we need to
list all resource record sets from base domain in AWS.
Fixes: #5937
> get all resource record sets from base domain in AWS

- ocs_ci/helpers/dr_helpers.py
- ocs_ci/ocs/constants.py
> Helper functions for RDR validation from OCP side

- ocs_ci/framework/conf/default_config.yaml
> Update rosa to current released version 1.2.2

- conf/README.md
- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
- conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
- conf/ocsci/ocs-live-must-gather.yaml
- conf/ocsci/odf-live-must-gather.yaml
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/defaults.py
- ocs_ci/ocs/ocs_upgrade.py
- tests/conftest.py
> Update logic for IBM Cloud W/A for must gather image

- ocs_ci/framework/logger_factory.py
- ocs_ci/framework/pytest_customization/ocscilib.py
- pytest.ini
- pytest_unittests.ini
Signed-off-by: Cem Erginbas <cerginba@cerginba.tlv.csb>
> Add cluster ctx to the logger format persistently

- ocs_ci/utility/rosa.py
> Load subnet ids from config if available

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/version.py
> comment sensitive variable based on OCP version

- setup.py
> Add protobuf==3.20.1 to fix google-api package conflict

- conf/ocsci/multicluster_acm_ocp_deployment.yaml
> Remove headless=false from multicluster acm-ocp deployment configuration

- conf/examples/acm_hub_unreleased_image.yaml
- ocs_ci/framework/conf/default_config.yaml
> Update ACM 2.5 image to RC6

- ocs_ci/ocs/resources/storage_cluster.py
- tests/managed-service/test_post_installation_state.py
> Remove storageclass check for provider cluster

- tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
> test_pvc_clones  - fix teardown issues of trying to log doesn't exist object

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/resources/mcg.py
Added the cos deployment with addon
> Added the cos deployment

- tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
This PR add CSI measurements to multi clone test ( csi creation) and pushes those measurements to the ES.
> Ypersky multi clones csi times

- ocs_ci/ocs/bucket_utils.py
- tests/manage/mcg/test_prefix_list.py
- tests/manage/mcg/test_s3_prefix_list.py
uploads objects with various alphanumeric combination of prefixes and then performs list operation to see if the below issue occurs:
https://bugzilla.redhat.com/show_bug.cgi?id=2068110
> test s3 list objects with prefix not giving infinite outputs

- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
- ocs_ci/deployment/rosa.py
- ocs_ci/utility/rosa.py
> Deployment Update for appliance mode

- conf/deployment/rosa/private_link_deployment.yaml
> Add private link mode enabling config for rosa deployment

- conf/ocsci/ms_addon_type_deployment.yaml
> config for add-on deployment for Managed Services

- ocs_ci/utility/rosa.py
> remove unused version parameter in MS

- ocs_ci/helpers/performance_lib.py
- ocs_ci/ocs/perftests.py
- ocs_ci/templates/app-pods/performance.yaml
- tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
This PR re-factoring the TS of the multi_clone to reduce the runtime of the test and to reduce the resource (memory) consumption.
> refactoring the multi_clone TC

- docs/getting_started.md
> Adding RHCOS template locations to download

- ocs_ci/deployment/helpers/lso_helpers.py
- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/utility/utils.py
- ocs_ci/utility/vsphere.py
supports direct I/O deployment for vSphere
> directio deployment for vSphere

- ocs_ci/ocs/acm/acm.py
- ocs_ci/ocs/ui/base_ui.py
Signed-off-by: jimdevops19 <jimdevops@gmail.com>
> Fix typo + Debug line in ACM and UI functions

- ocs_ci/ocs/platform_nodes.py
> Fetch node names from object's existing data

- tests/manage/mcg/test_pv_pool.py
**Fix:**
Added check for SCALING state in test_pv_pool, before
the move to OPTIMAL state.
Fixes: #5568
Signed-off-by: nik-redhat <nladha@redhat.com>
> Fix: Added check for SCALING state in test_pv_pool

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/views.py
Fixes: #6000 
Steps added:
- Calling a new function just after the `driver.get(console_url)`. There seems to be a page that appears just before login that a click on a button is required.
- New function in `base_ui.py` - Currently added as a separated function since we need to call it before login.
- Added three new locators to the common `login` dictionary.
> Handle page appears before the login of UI Console if necessary

- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
- conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
- conf/deployment/rosa/private_link_deployment.yaml
- ocs_ci/deployment/rosa.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/utility/rosa.py
This Pr accomodate the changes for
private link cluster deployment
Define dafult public machine-cidr
Deployment with default machine-cidr
Deployment with custom machine-cidr
> Update deployment code for appliance mode private link cluster

- conf/ocsci/skip_submariner_deploy.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/multicluster_deployment.py
> Generate Ingress certs post ACM managed clusters deployment

- ocs_ci/ocs/resources/storage_cluster.py
> Add endpoint checks

- ocs_ci/utility/rosa.py
> Retry addon status for Ready even after fail

- ocs_ci/ocs/node.py
> Update post deployment check of node counts for managed service platform

- tests/conftest.py
- tests/e2e/kcs/test_monitor_recovery.py
verifies: https://access.redhat.com/solutions/6100031 (needs update)
> Mon recovery procedure validation

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
I created some WA because this issue https://github.com/red-hat-storage/odf-console/issues/264
Signed-off-by: odedviner <oviner@redhat.com>
> ODF4.11 UI deployment

- ocs_ci/ocs/bucket_utils.py
- tests/manage/mcg/test_pv_pool.py
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2064599
> To test modify resource options in PV Pool Backingstore

- ocs_ci/deployment/helpers/rosa_prod_cluster_helpers.py
- ocs_ci/deployment/rosa.py
- ocs_ci/ocs/exceptions.py
> create admin account and login to cluster for ROSA prod env

- ocs_ci/templates/app-pods/performance.yaml
- tests/e2e/performance/csi_tests/test_pod_reattachtime.py
This PR contains the following : 
1) Change to pervormance.yaml ( fixes pod attach problem - without this change pods do not reach status Running)
2)  Adding of csi reattach measurements to the test.
> Ypersky csi pod reattach

- ocs_ci/ocs/resources/namespacestore.py
> Fix for nsfs external sc

- ocs_ci/deployment/deployment.py
- ocs_ci/templates/lvmo-deployment/role_rolebinding.yaml
> Add role binding for BZ2101343

- ocs_ci/ocs/cluster.py
> Fixes health check with no provided ugprade version

- Docker_files/build.sh
> use podman as default instead of docker in the build.sh script

- ocs_ci/framework/conf/default_config.yaml
> Update rosa cli version to  rosa 1.2.3

- ocs_ci/deployment/rosa.py
- ocs_ci/utility/rosa.py
> Add teardown handling for appliance mode

- conf/examples/acm_hub_unreleased_image.yaml
- ocs_ci/framework/conf/default_config.yaml
> Update ACM 2.5 image to 2.5.1

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
Signed-off-by: Oded Viner <oviner@oviner.tlv.csb>
> Fix ui_deployment on ODF4.11

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/ocs/ocs_upgrade.py
If no client role found, fallback to first node.
> Try to get client with proper role for RHCS cluster

- conf/ocsci/enable_restricted_auth_permission.yaml
- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/resources/storage_cluster.py
> external cluster deployment with restricted-auth-permission

- tests/manage/z_cluster/nodes/test_worker_nodes_network_failures.py
> Closed loop 2029690: bucket creation/op post nw failure

- ocs_ci/ocs/resources/mcg.py
- tests/manage/rgw/test_rgw_pod_existence.py
> Move RGW pod existence checks to their own test

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/ocs-deployment/serviceaccount_token_secret.yaml
- ocs_ci/utility/kms.py
> Add creation of token secrets for serviceaccounts in OCP 4.11

- tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
Fixes #5707 
Add wait time between file deletion and the creation of the reclaimspace job.
> Fix test case test_rbd_space_reclaim

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/framework/pytest_customization/ocscilib.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/resources/pvc.py
- ocs_ci/templates/CSI/lvm/restore-pvc.yaml
- ocs_ci/templates/CSI/lvm/storageclass.yaml
- ocs_ci/templates/CSI/lvm/volume-snapshot.yaml
- ocs_ci/utility/environment_check.py
- tests/conftest.py
- tests/lvmo/test_lvm_clone_base.py
- tests/lvmo/test_lvm_snapshot_base.py
Volume snapshot and clone for lvmo base tests
> lvmo shapshot and clone base tests

- tests/conftest.py
> Added continue to lvm mark

- tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
> Skip reclaim space job on external mode

- ocs_ci/helpers/performance_lib.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/perftests.py
- tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
> Clones TC - Improving the teardown phase

- tests/conftest.py
- tests/e2e/scale/conftest.py
- tests/manage/mcg/conftest.py
- tests/manage/pv_services/conftest.py
- tests/manage/rgw/conftest.py
- tests/manage/storageclass/conftest.py
> Change info to debug for pytest_collection_modifyitems

- ocs_ci/deployment/helpers/lso_helpers.py
- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
- Changed osd size attributes on ODF 4.11
- Install lso operator on non-gaed ocp cluster [for UI deployment]
> Fix UI deployment on ODF4.11

- tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
The current PR handles the following
1) Creation of objects will be done in the ceparate project 
2) Usage of pvc_factory and pod_factory was abandoned 
3) Caltulations of csi snapshot restore times ( and average) were added.
> Ypersky snapshots refactoring

- conf/README.md
- conf/upgrade/post_upgrade.yaml
- ocs_ci/utility/utils.py
> Report post-upgrade in mail subject

- ocs_ci/deployment/helpers/external_cluster_helpers.py
> rbd pool name as user configurable value

- ocs_ci/deployment/rosa.py
> Skip testing the cluster for MS production environment in appliance mode

- ocs_ci/utility/kms.py
- tests/conftest.py
- tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_clone.py
- tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
- tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption.py
- tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
> Update PV encryption tests to use vault HCP

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/ocs_upgrade.py
Add the logic to upgrade ocs version
> Add the logic to upgrade ocs version

- ocs_ci/deployment/vmware.py
> get ocp branch using semantic module

- tests/conftest.py
- tests/lvmo/test_lvm_clone_base.py
- tests/lvmo/test_lvm_multi_clone.py
- tests/lvmo/test_lvm_multi_snapshot.py
- tests/lvmo/test_lvm_snapshot_base.py
Multi snapshot test. Create 5 PVC, PODS, snapshots, restore PVC and attach to pod.
Need to merge [#6129](https://github.com/red-hat-storage/ocs-ci/pull/6129) to be able to execute PR validation
> Multi LVM snapshots and clones

- tests/manage/z_cluster/nodes/test_nodes_restart.py
Skipping the test based on this comment https://github.com/red-hat-storage/ocs-ci/pull/6106#issuecomment-1177219052
> Skip test test_nodes_restart on MS

- ocs_ci/framework/conf/ocs_version/ocs-4.99.yaml
- ocs_ci/framework/main.py
> Upstream ODF 4.99 yaml file

- tests/manage/pv_services/pvc_clone/test_clone_with_different_access_mode.py
> Fix condition to get file name on pod

- ocs_ci/ocs/ui/pvc_ui.py
> Fix condition to set volume mode in create_pvc_ui

- ocs_ci/utility/utils.py
> Skip raising exception if grep doesn't found any matching pattern on pod

- ocs_ci/deployment/rosa.py
- ocs_ci/ocs/exceptions.py
> get security group for MS cluster

- ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
- ocs_ci/framework/conf/ocs_version/ocs-4.12.yaml
- ocs_ci/framework/main.py
> Adding ODF 4.12 configuration files

- tests/conftest.py
> Donot check clusters incase of teardown

- ocs_ci/ocs/resources/storage_cluster.py
[External Mode]: Verification of CSI users and provisioner/node secret name for
rbd and cephfs in restricted auth permission mode
> CSI users and provisioner/node secret name verification in external mode

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/resources/pvc.py
- ocs_ci/ocs/utils.py
- ocs_ci/utility/connection.py
- tests/lvmo/test_lvm_snapshot_bigger_than_disk.py
> Extend LVM class and test snapshot bigger than disk

- tests/lvmo/test_lvm_clone_base.py
- tests/lvmo/test_lvm_multi_clone.py
- tests/lvmo/test_lvm_multi_snapshot.py
- tests/lvmo/test_lvm_snapshot_base.py
- tests/lvmo/test_lvm_snapshot_bigger_than_disk.py
> Remove acceptance from LVM tests

- ocs_ci/deployment/rosa.py
- add rules one by one and handle possible `Duplicate` error
> rosa: update SG rules based on cluster specific machine_cidr

- tests/manage/z_cluster/nodes/test_toleration.py
> Fixes:5165

- conf/README.md
- conf/deployment/vsphere/upi_1az_rhcos_vsan_1mw.yaml
- ocs_ci/templates/lvmo-deployment/lvmo_deployment_10_disk_X_200GB.yaml
- ocs_ci/templates/lvmo-deployment/lvmo_deployment_3_disk_X_500GB.yaml
- ocs_ci/templates/lvmo-deployment/lvmo_deployment_5_disk_X_150GB.yaml
- ocs_ci/utility/reporting.py
- ocs_ci/utility/utils.py
> Update reporting for SNO LVMO jobs

- ocs_ci/ocs/ocs_upgrade.py
> MCG Only upgrade

- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/retry.py
> Add retry for encryption verification

- tests/manage/pv_services/test_pvc_evict_ceph_clients.py
> Bug-1901499: Test ceph-fs pvc mount when ceph clients evicted

- ocs_ci/templates/workloads/amq/hello-world-consumer.yaml
- ocs_ci/templates/workloads/amq/hello-world-producer.yaml
> AMQ: Pulling producer & consumer from quay instead of docker hub

- ocs_ci/ocs/scale_noobaa_lib.py
> Fixes #6217

- .github/CODEOWNERS
- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/ocs/constants.py
- pytest.ini
> Aqua squad for lvmo test cases

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/resources/storage_cluster.py
> OSD pod memory size for Managed Service

- ocs_ci/ocs/managedservice.py
> Use correct version when getting odf-operator string

- ocs_ci/framework/conf/ocp_version/ocp-4.12-upgrade.yaml
> Adding OCP 4.12 upgrade configuration file

- tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
The test is applicable only with the Managed Service.
I performed two changes in the test:
1. Update the test to create pods and PVCs and run IO using the Kube job in the test
2. Save the original index, and switch to it in the teardown.
> Update the test "test_automated_recovery_from_failed_nodes_reactive_ms"

- conf/ocsci/external_rhcs_ipv6_rgw_endpoint.yaml
- ocs_ci/deployment/helpers/external_cluster_helpers.py
> Supporting IPv6 in external RHCS deployment

- tests/ecosystem/upgrade/test_noobaa.py
> skip mcg upgrade tests on managed service

- ocs_ci/ocs/scale_noobaa_lib.py
- tests/e2e/scale/noobaa/test_scale_obc_creation.py
- tests/e2e/scale/noobaa/test_scale_obc_creation_repsin_noobaa_pods.py
- tests/e2e/scale/upgrade/test_upgrade_with_scaled_obc.py
* Create scaled MCG OBC using Noobaa storage class before upgrade
* Save scaled obc data in a file for post upgrade validation
* Validate OBC scaled in Bound status after upgrade
> Upgrade test with scaled OBCs

- ocs_ci/helpers/helpers.py
- tests/conftest.py
- tests/manage/storageclass/test_new_sc_rbd_replica2_3.py
Add support to choose between Immediate volume binding mode and WaitForFirstConsumer
> Add support for WaitForFirstConsumer to storageclass

- tests/ecosystem/deployment/test_deployment.py
> Fix issue#6189- Woraround for MS post deplyment test inconsitent issue

- tests/manage/pv_services/pvc_snapshot/test_small_files_pvc_cloned_status.py
> close loop 2039265: Check Test pvc cloned status of small size files

- tests/conftest.py
> Add squad marker decorator values to junit item properties

- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/ocs/resources/storage_cluster.py
> user configurable cephfs for external cluster deployments

- ocs_ci/deployment/vmware.py
- ocs_ci/utility/utils.py
> force checkout option for cloning

- ocs_ci/helpers/dr_helpers.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/drpc.py
- Added methods for context switching based on workload namespace
- Update existing and add new methods for checking resource creation or 
deletion
Also added `drpc.py` for DRPC related functionalities
> Enhancements for DR helper methods

- ocs_ci/ocs/ui/views.py
Fixing the issue encountered here in 4.11:
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-dr-setup/27/consoleFull
> Fix UI title for OCP4.11 in pre-ACM Login

- conf/examples/acm_hub_unreleased_image.yaml
- ocs_ci/framework/conf/default_config.yaml
> Update ACM 2.5 image to 2.5.2

- ocs_ci/templates/lvmo-deployment/lvmo_deployment_3_disk_X_75GB
New installation template, for 3 disks of 75G
> Added new template file, for small disks lvmo installation

- ocs_ci/ocs/bucket_utils.py
- tests/manage/mcg/test_write_to_bucket.py
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2054074
> Check if content-encoding is being stored as object metadata on s3 put

- ocs_ci/ocs/cluster.py
- tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
Create a new file to test the node restart scenarios using the Managed Service.
> Test nodes restart scenarios using the Managed Service

- tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
This PR improve the TC runtime from 2H and 10 Min to **40 Min**
by increasing the parallelism of filling up the PVCs with data.
It also reduce some code duplication.
> TC pvc_bulk_clone performance improvement

- ocs_ci/deployment/vmware.py
> wait for install-complete in vSphere IPI deployments

- tests/conftest.py
> use upstream must gather image for Managed service live deploy
