.travis.yml, tox.ini
All checks (unit test run and flake8 check) are executed via tox.
Tox config now contains multiple environments, so that it's possible
to run flake8 check without running unit tests::
$ tox -e flake8
Running tox still runs all the checks.
This split is useful for the travis job, which will contain two separate
items, one for each tox environment, so that it's immediately visible if
the failure is in flake8 or unit test rerun.
=> add travis and update tox config

run.py, tests/test_ocs_basic_install.py
Renamed instances-name to cluster-name and fixed typo in get for cluster-name in test_data dict
=> cluster-name fix

.gitignore, MANIFEST.in, pytest_customization/ocscilib.py, tox.ini, unittests/conftest.py, unittests/test_pytest.py
This pull requests introduces unit tests of our pytest plugins, tested via pytest via [pytester](https://docs.pytest.org/en/latest/_modules/_pytest/pytester.html), which is official pytest module for testing pytest plugins via pytest.
It contains few simple test cases only, so that it's possible to add unit tests for config and cli option processing later.
Don't squash this pull request into single commit when merging, each commit message is meaningful.
=> Initial support for unit tests of pytest plugins

ocs/ocp.py
For some commands, like "ceph fs ls", the returned output is a list
=> Fix for exec_ceph_cmd

templates/install-config.yaml.j2, tests/ecosystem/deployment/test_ocs_basic_install.py
openshift-install expects the pullSecret value to be a JSON string. Mine is
stored as a multiline object, and so the existing code to read it failed. I
really think a better approach is to use the existing parsers for both JSON and
YAML here, as they are extremely well-tested and supported.
=> Fix pull-secret handling

ocsci/pytest_customization/ocscilib.py
Installer is truncating the cluster name so lets append our clusternames with upto 8
chars from getuser.
=> Installer is truncating the cluster name, use upto 8 chars from username

docs/usage.md, setup.py, tox.ini
simplify our run name, lets just call it run-ci (the repo name is ocs-ci, so it would imply
running ocs-ci)
=> simplify our run name, lets just call it run-ci

templates/CSI/cephfs/pod.yaml, templates/CSI/cephfs/pvc.yaml, templates/CSI/cephfs/secret.yaml, templates/CSI/cephfs/storageclass.yaml, templates/CSI/rbd/pod.yaml, templates/CSI/rbd/pvc-restore.yaml, templates/CSI/rbd/pvc.yaml, templates/CSI/rbd/secret.yaml, templates/CSI/rbd/snapshot.yaml, templates/CSI/rbd/snapshotclass.yaml, templates/CSI/rbd/storageclass.yaml
This PR addresses #106 .
For now, following jinja2 templates have been added under templates/csi-templates:
- csi-cephfs-secret.yaml  
- csi-cephfs-storageclass.yaml  
- csi-rbd-secret.yaml
- csi-rbd-storageclass.yaml
- cephblockpool.yaml
- pvc.yaml
- pod.yaml
Git hub links for the yamls:
https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/example/rbd/
https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/example/cephfs
Some points to add:
a) In storageclass.yaml, for "monitors" , I have used default FQDN name , assuming we have mon-a, mon-b and mon-c.
b) secret.yaml is expecting userid as kubernetes. If the userid is not kubernetes, we may have to add a different username here:
ceph auth get-key kubernetes | base64
**kubernetes**: {{ …
=> PR for CSI templates - rbd and cephfs

ocsci/pytest_customization/ocsci_logging.py, pytest.ini, setup.py
Implementing logging per test case.
* creates the directory structure for logging
* creates symlink for easy access to logs
Example for symlink:
```
[vavuthu@localhost tmp]$ ls -lrt | tail -2
drwxrwxr-x.   3 vavuthu vavuthu     60 Jun  6 15:52 logs_1559816529
lrwxrwxrwx.   1 vavuthu vavuthu     20 Jun  6 15:52 logs -> /tmp/logs_1559816529
[vavuthu@localhost tmp]$ 
```
Example for directory structure:
lets say  tests/manage/test_manage.py conatins class `TestManage` having 2 test cases. 
o/p: 
[vavuthu@localhost tmp]$ ls logs/tests/manage/test_manage/TestManage/
test_manage_test_case1.log  test_manage_test_case2.log
[vavuthu@localhost tmp]$ 
OVERALL logging structure:
======================
```
[vavuthu@localhost tmp]$ tree logs
logs
└── tests
├── ecosystem
│   ├── deployment
│   │   └── …
```
=> Implementing logging per test case.

conf/ocsci/default_config.yaml
Currently the lastest version is pointing to 4.1.0 so we won't need
need to change this version each time when there is new RC like:
4.1.0-rc.9, but need to change just once there will be new version like
4.1.1 or 4.2.0.
=> Change installer and client to version 4.1.0

ocs/constants.py, ocs/defaults.py, resources/pod.py, tests/manage/OCS_336_346.py
resources/pod.py
- Added function get_admin_key_from_ceph_tools(),which returns admin keyring in base64
ocs/defaults.py
-  Added default path of csi templates of pvc and storage class for CEPHFS & RBD
ocs/constants.py
- Added encode value for string 'admin'
tests/manage/OCS_336_346.py
- Added two cases OCS-336 and OCS-346, which covers basics such as secret creation, storage class creation with cephfs and rbd
resources/ocs.py
- Added return statement to delete()
=> OCS-336 and OCS-346 - Test ocs basics

conf/ocsci/default_config.yaml
We agreed with Raz that we want to use latest version of upsteram all
the time so when we define v14 we don't need to maintain this version
when new version released and update it here once we decide to go to
v15.
=> Change of ceph image version to v14

run_ocsci.py
- `utility` module have to be loaded after `init_ocsci_conf(arguments)`
- fixes https://github.com/red-hat-storage/ocs-ci/issues/233
=> load utility module after configuration init

tests/manage/test_create_storageclass_with_same_name.py
This is a new PR for TC - OCS-322 (Test that creation of Storageclass with duplicate name fails)
The old PR #91 has been closed.
Added the recent changes for kind classes. Please review and let me know if there's any error.
**The trial run of the Test case passed:** 
```
20:38:42 - MainThread - root - INFO - All logs are located under /tmp/logs
-------------------------------------------------------------------------------------------------- live log call --------------------------------------------------------------------------------------------------
20:38:42 - MainThread - tests.manage.test_create_storageclass_with_same_name - INFO - Creating a Storage Class
20:38:42 - MainThread - resources.ocs - INFO - Adding StorageClass with name ocs-322-sc
20:38:42 - MainThread - utility.utils - …
```
=> OCS-322 Create Duplicate Storageclass with latest changes

ocsci/pytest_customization/ocsci_logging.py
Use `os.path.expanduser()` for `log_dir` configuration. This will allow following configuration for Jenkins/CI:
```
RUN:
log_dir: "~/current-cluster-dir/logs/"
```
=> expand user for log_dir configuration

conf/ocsci/default_config.yaml, ocs/defaults.py, ocsci/pytest_customization/marks.py, ocsci/pytest_customization/ocscilib.py, pytest.ini, tests/conftest.py, tests/manage/ocs_288.py, tests/manage/test_create_storageclass_with_same_name.py, tests/manage/test_ocs_324.py, tests/manage/test_ocs_336_346.py, tests/manage/test_pvc_deletion_during_io.py, tests/manage/test_pvc_invalid_inputs.py, tests/manage/test_rbd_csi_default_sc.py
Added the ability to mark tests with their respective `polarion_id`s in order to support posting our test results to Polarion. When we export our test results to a junit xml file (`--junit-xml report.xml`) any test cases that are marked with polarion_ids will have a custom property set that reflects the value. 
Ex.
```
<properties><property name="polarion-testcase-id" value="OCS-foo"/></properties>
```
Note that these changes do not add the ability to post the results to Polarion, only to support the tool we will use to take our xml test results and post the results.
=> Polarion support

templates/ocs-deployment/operator-openshift-with-csi.yaml, tests/ecosystem/deployment/test_ocs_basic_install.py
This PR addresses #112 and #181 and #253 
1. Added MDS pods as part of rook-ceph deployment using the new kind classes (fixes #112)
2.  Changed the operator-openshift-with-csi.yaml (fixes #253)
3. Due to chnages in deployment, moved check for agent pods after running cluster.yaml
4. Added checks for Ceph pods (fixes #181)
Note: I already had a PR (#151) which was mistakenly closed by me. Hence creating a new PR 
Old PR - https://github.com/red-hat-storage/ocs-ci/pull/151
Please review
=> Adding MDS pod creation to ocs_basic_install

utility/utils.py
Use `os.path.expanduser()` for `bin_dir` configuration. This will allow for example following configuration for Jenkins/CI:
```
RUN:
bin_dir: "~/bin"
```
=> expand user for bin_dir configuration

docs/README.md
It's better not to use short forms like TOC in the documentation as the user might not always know what could be the abbreviations for them.
=> Changing toc to table of contents in doc/Readme.md

ocs/utils.py, ocsci/main.py, resources/pvc.py, tests/fixtures.py, tests/helpers.py, tests/manage/test_create_storageclass_with_same_name.py, tests/manage/test_ocs_336_346.py, tests/manage/test_pvc_delete_verify_size_is_returned_to_backendpool.py, tests/manage/test_pvc_invalid_inputs.py, tests/test_add_mds_to_cluster.py, tests/test_storageclass_invalid.py, tox.ini, utility/utils.py
This is just *quick fix* (hack), proper fix requires us to use a different
API (eg. function or a fixture, which creates new object of given type).
This consists of 3 changes:
* replacing usage of `copy()` call with `copy.deepcopy()`
* removing [default mutable arguments](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments)
* adding `M511` flake8 plugin to prevent this problem in the future (I will announce this on our list when merged so that all team members will know what this new flake8 error mean)
When merging, *don't use squash and merge* feature, I would like to be able to refer to commit 8ed5847d8024fd828821000cc8fad6a9dcbfeac9 as an example how to handle this problem.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/266
=> fixing accidental changes in mutable default structures

conf/README.md, conf/ocsci/default_config.yaml, ocs/defaults.py, ocsci/main.py, ocsci/pytest_customization/ocscilib.py, ocsci/pytest_customization/tests/test_pytest.py, ocsci/tests/test_config.py, resources/pvc.py
=> Move all defaults from config yaml to defaults.py

templates/CSI/rbd/storageclass.yaml
templates/CSI/rbd/storageclass.yaml
- fixed typo 'clusterID'
=> typo fix: templates/CSI/rbd/storageclass.yaml

ocsci/exceptions.py, ocsci/pytest_customization/ocscilib.py, ocsci/pytest_customization/tests/test_pytest.py, tests/conftest.py, utility/system.py
This is to guard against accidentally writing over an existing clusters information if for whatever reason it could not be accessed temporarily.
Also, I'm adding an ``ocsci.exceptions`` module and ``utility.system`` module. The ``ocsci.exceptions`` module we can use to store custom exceptions which can provide more meaningful exception messages back to the user. I was thinking the ``utility.system`` could contain system-level utility methods, for example file system modifications. Eventually we can port stuff from ``utility.utils`` that make sense to do so. 
This is a followup from #173
=> ensure that the given --cluster-path if empty if --deploy is also provided

tests/manage/test_create_storageclass_with_same_name.py
Modifying the merged Test case [OCS-322](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/test_create_storageclass_with_same_name.py) with following changes:
1. Removed monitors as new RBD SC doesn't have this parameter
sc_data['parameters']['monitors'] = mons
2. Adding clusterID to SC param
sc_data['parameters']['clusterID'] = defaults.ROOK_CLUSTER_NAMESPACE
Thanks
=> Removing [monitors] and adding [clusterID] in SC creation- ocs-322

ocs_ci/ocs/resources/pod.py
Fixes Issue #371 
Added a variable "fio_filename" in ocs_ci/ocs/resources/pod.py **run_io** function
Please review.
**Verified the result:** 
e.g. added fio_filename = name of the app pod for simplicity in validating which pod the file belongs to: 
pod_obj.run_io('fs', '512M', fio_filename=pod_obj.name)
20:10:23 - MainThread - ocs_ci.ocs.workload - INFO - Done submitting..
20:10:23 - ThreadPoolExecutor-1_0 - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-0820075834 --kubeconfig /home/nberry/aws-install/jul8-1/auth/kubeconfig rsh pod-test-0820082948 fio --name=fio-rand-readwrite **--filename=/var/lib/www/html/pod-test-0820082948** --readwrite=randrw --bs=4K --direct=1 --numjobs=1 --time_based=1 --runtime=60 --size=1G --iodepth=4 --invalidate=1 --fsync_on_close=1 …
=> Fixes Issue-371, added ioparam [fio_filename] to pod.run_io

ocs_ci/framework/pytest_customization/ocscilib.py
We cannot collect data like version info from the cluster when it's not
in good shape. So when destroy cluster, we just skip the version
collecting with change in this PR.
Should also fix the issue #335
=> Destroy cluster in bad shape

ocs_ci/ocs/constants.py, tests/fixtures.py, tests/helpers.py, tests/manage/test_create_storage_class_pvc.py, tests/manage/test_pvc_delete_verify_size_is_returned_to_backendpool.py, tests/manage/test_pvc_disruptive.py, tests/manage/test_verify_rbd_based_rwo_pvc.py
- Changed create_pvc() to instanciate PVC
- Modifications in create_pod()
- Added 'interface' to resource name while creating resource
- Added new functions
-- get_all_pvs() --> Returns all pvc in given namespace
-- validate_pv_delete() --> Validates if pv is deleted after pvc deletion with retry()
tests/manage/test_create_storage_class_pvc.py
- Updated fixtures for cephfs and rbd
- Added validate_pv_delete() for validating pv after pvc delete
- Added pod creation for cephfs and rbd with default values
ocs_ci/ocs/constants.py
- Added rbd and cephfs interfaces
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/343
=> Testcase and helpers.py enhancement

pytest.ini
Automatically add --no-print-logs option to suppress dumping logs at the end of a session and to reduce html report file size.
This change solves two issues:
- Captured logs being dumped at the end of a session makes viewing the overall results in the console practically impossible.
- Enormous file size of html reports caused giant load times and reduces the value of these _summary_ reports
Before:
- tier1-report.html - 431M
- 55 sec. load time in browser
After:
- tier1-report.html - 906K
- < 1 sec. load time in browser
I don't think this 100% fixes the issue described in #323 but it is a significant start.
=> Suppress captured logs at end of session

tests/manage/test_rbd_csi_default_sc.py
Fixing #264
Patched tests/manage/test_rbd_csi_default_sc.py
Other scripts were deleting default RBD pool(rbd). So creating my own pool for this test case.
=> Fixing tier1 test for OCS-347. Issue #264

ocs_ci/ocs/cluster.py, tests/helpers.py, tests/test_cluster_utils.py
* Fix tier1 test_cluster_utils failures by introducing setup and teardown per test.
* Introduce mon_resource, mds_resource, user_resource as fixtures for tests
=> Addressing Tier1 test failures for test_cluster_utils

ocs_ci/framework/conf/default_config.yaml, ocs_ci/templates/ocs-deployment/cluster.yaml, ocs_ci/templates/ocs-deployment/common.yaml
Fix for the issue #397
Changed the image name in default_config.yml to **ceph/daemon-base:latest-nautilus-devel**  since this new image is needed for cephfs pvcs to get bound. 
```
image: ceph/daemon-base:latest-nautilus-devel
```
CephFS pvcs were in Pending state if we used the current ceph image mentioned below. : 
**-  ceph_image: 'ceph/ceph:v14'**
Confirmed following:
1. rook ceph cluster install works
2. rbd and cephfs pvc are getting BOUND
=> Updating the yamls based on upstream rook changes

.gitlab-ci.yml
It was failing because of the lack of the py36 interpreter
=> Fix .gitlab-ci

tests/conftest.py
We broke the teardown finalizer recently, by calling the function
immediately and causing None to be passed to addfinalizer(), resulting
in `TypeError: 'NoneType' object is not callable`
Caused by: https://github.com/red-hat-storage/ocs-ci/commit/b21121bf0103a813a582f24196fe21fcc1a6e623#diff-484462fced51d1a06b1d93b4a44dd535R93
=> conftest: Fix teardown finalizer

ocs_ci/framework/pytest_customization/reports.py
- `report.description` is not properly configured, when the test
execution fails. In such case, we should print the original error, not
traceback related to missing description.
- fixes https://github.com/red-hat-storage/ocs-ci/issues/406
=> handle missing description for html reporting

tests/manage/test_create_pvc_random_storage_class.py, tests/manage/test_pvc_concurrent_deletion_creation.py
Fixing the import error delete_all_pvc function
```
tests/manage/test_pvc_concurrent_deletion_creation.py:11: in <module>
from ocs_ci.ocs.resources.pvc import create_multiple_pvc, delete_all_pvcs
E   ImportError: cannot import name 'delete_all_pvcs'
```
=> Fixing import error delete_all_pvcs func

ocs_ci/framework/main.py, ocs_ci/ocs/utils.py, tests/conftest.py
- place pytest logs to `RUN[`log_dir`]` to `pytest-logs-{run_id}` subdirectory
- generate `RUN['run_id']` directly in `run-ci` wrapper, so we can use the
value for the `--logger-logsdir` parameter
- fixes https://github.com/red-hat-storage/ocs-ci/issues/415
=> pass --logger-logsdir parameter to pytest

ocs_ci/ocs/resources/ocs.py
This will be useful for finalizers/teardowns as you can skip this object
which was already deleted from test method for example.
=> Add delete flag to OCS class

conf/ocs_basic_install.yml, conf/ocsci/downstream_config.yaml, ocs_ci/framework/conf/default_config.yaml, ocs_ci/framework/tests/test_config.py, ocs_ci/ocs/defaults.py, ocs_ci/templates/ocs-deployment/operator-openshift-with-csi.yaml, ocs_ci/templates/ocs-deployment/toolbox_pod.yaml
Replaced the latest Rook image with a hardcoded 1.0.4 until the image is fixed,
Also hardcoded 'rook-ceph' as the namespace for all of our deployments until we understand why the pods disappear under 'openshift-storage'
=> Rook mon crashloop and pod disappearance workaround

tests/helpers.py, tests/manage/test_pvc_disruptive.py
* Delete resource while specified operation is in progress
* Additional verification to ensure that the specified operation has started before deleting resource
* Verify that PVCs are reusable by creating new pods
* helpers.py - Added namespace parametor in 'create_pod'
=> Test case enhancement test_pvc_disruptive

ocs_ci/ocs/constants.py, ocs_ci/ocs/defaults.py, tests/helpers.py, tests/manage/test_create_storageclass_with_wrong_provisioner.py
Create StorageClass with wrong provisioner and create PVC using it and verify its status.
This PR covers both RBD and CephFS test cases
=> Testcase: (RBD & Cephfs) Create StorageClass with wrong provisioner

ocs_ci/ocs/constants.py, ocs_ci/ocs/ocp.py, ocs_ci/ocs/resources/ocs.py, ocs_ci/ocs/resources/pod.py, ocs_ci/ocs/resources/pvc.py, ocs_ci/templates/app-pods/nginx.yaml, tests/helpers.py, tests/manage/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
Add Dynamic PVC creation tests with different combinations of accessmodes and reclaim policies
- Add test_dynamic_pvc_accessmodes_with_reclaim_policies.py
tests/fixtures.py
- Add create_project()
ocs_ci/ocs/constants.py
- Add constants for Reclaim Policy and CephFS pod yaml
Edit: Based on discussion with Raz and Elad, this PR tries to provide a basic structure to combine all Dynamic PVC creation tests.
This PR also covers the test tests/manage/test_verify_rbd_based_rwo_pvc.py (PR #337)
=> Add Dynamic PVC creation tests with different combinations of accessmodes and reclaim policies

ocs_ci/framework/main.py, ocs_ci/utility/utils.py, tests/conftest.py
This PR addresses the issues documented in #436. I still wasn't able to determine with 100% certainty what the cause of the issues was, although I highly suspect it was some combination of setting the log_dir through `--logging-logsdir` as well as defining `pytest_logger_logdirlink` in our `conftest.py` which enables symlinking our logs. 
- Removed sym linking of pytest logs
- Moved log directory path construction to utility method
- Removed explicit call to create the log directory as pytest handles this for us
Fixes: #436 
=> Deployment logging fix

tests/helpers.py
Handle the condition when 'nodeName' parameter is not present in pod YAML template.
=> Fix Issue #449 - KeyError: 'nodeName' during pod creation

ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/framework/testlib.py, ocs_ci/ocs/defaults.py, ocs_ci/ocs/resources/pod.py, ocs_ci/utility/spreadsheet/spreadsheet_api.py, tests/conftest.py, tests/helpers.py
- Session scope fixture that is being called before environment_checker fixture. This fixture creates a PVC and a pod and runs FIO on that pod and deletes the file in a while true loop. This is being done as long as the test is running. The IO is being stopped when the test is done
- Added a new cli param: --io_in_bg
=> Run IO in the test background

tests/helpers.py, tests/manage/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
Update tests/manage/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
- Teardown will not get stuck in pvc deletion as pod are deleted first (if exists) during the teardown
Update tests/helpers.py
- create_pod() will wait for 120 seconds instead of default 60 seconds for the pod to reach the desired status
=> Fix issue #456: Teardown getting stuck forever

tests/helpers.py
Saw Rook testing logs and it is very helpful to see
describe of object when it fails reaching some state
=> Improve logging on failures

tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
This PR automates following  Polarion Test cases :
1. [OCS-542](https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-542) - CephFS Based RWX Dynamic PVC creation and deletion with Reclaim policy set to Retain
2. [OCS-529](https://polarion.engineering.redhat.com/polarion/redirect/project/OpenShiftContainerStorage/workitem?id=OCS-529) - CephFS Based RWX Dynamic PVC creation and deletion with Reclaim policy set to Delete
The test for CephFS and RWX with two reclaim Policies (Retain and Delete) are added in the existing file test_dynamic_pvc_accessmodes_with_reclaim_policies.py
Please review and suggest changes.
Thanks,
Neha
=> Added test for RWX with CephFS - OCS-542 and OCS-529

ocs_ci/deployment/aws.py, ocs_ci/deployment/deployment.py, ocs_ci/deployment/factory.py
Changed name of loggers in deployment module to use __name__ instead of __file__. This keeps the deployment module consistent with other loggers in ocs_ci.
=> Deployment logger names

ocs_ci/ocs/ocp.py
00:22:36 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs-dir2/auth/kubeconfig get StorageClass storageclass-test-rbd-0300210683 -o yaml
00:22:37 - MainThread - ocs_ci.ocs.ocp - INFO - StorageClass storageclass-test-rbd-0300210683 got deleted successfully
=> Improve wait_for_delete logging

docs/getting_started.md, ocs_ci/deployment/aws.py, ocs_ci/framework/conf/default_config.yaml, ocs_ci/utility/utils.py
- Updated the OCP client/installer versions to a 4.2 nightly build
- Added .json extension to the terraform.tfvars file
- Changed location of where we pull deployment artifacts from
=> WIP: Update deployment to use a 4.2 nightly build

ocs_ci/ocs/ocp.py, tests/manage/cluster/nodes/test_nodes_restart.py
Addresses issue https://github.com/red-hat-storage/ocs-ci/issues/504.
- Allow getting nodes to wait for
- Logs which nodes failed to reach Ready status
- While polling, logs the nodes that are still not in Ready status
=> Enhancements for ocp.wait_for_nodes_ready()

ocs_ci/framework/conf/default_config.yaml
to current latest nightly builds
It is probably affected by this known issue: https://bugzilla.redhat.com/show_bug.cgi?id=1736800 (affecting clusters running more than 24 hours).
=> update installer and client version

ocs_ci/templates/install-config.yaml.j2
This is needed for noobaa deployment as it requires more resource for work
nodes.
For AZ we need to have this option for:
https://jira.coreos.com/browse/KNIP-622
=> Add AZ and instance type to deployment

ocs_ci/deployment/deployment.py, ocs_ci/templates/ocs-deployment/cluster.yaml, ocs_ci/templates/ocs-deployment/common.yaml, ocs_ci/templates/ocs-deployment/operator-openshift.yaml
Signed-off-by: Neha Berry <nberry@redhat.com>
The rook [repo](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph) has made certain changes to following files - See Rook PR https://github.com/rook/rook/pull/3562.
Based on that, updated the common.yaml, operator-openshift.yaml and cluster.yaml. Also updated the deployment.py with corresponding changes.
Note: Change from upstream, made this false:
- name: ROOK_ENABLE_FLEX_DRIVER
value: "{{ rook_enable_flex_driver | default('false') }}"		          value: "{{ rook_enable_flex_driver | default('false') }}"
Note:
1. Secret **rook-ceph-csi** is now by default created in the openshift-storage project
=> Updated the Deployment yamls and Deployment.py based on rook repo changes

ocs_ci/ocs/constants.py, ocs_ci/ocs/node.py, ocs_ci/ocs/ocp.py, tests/manage/cluster/nodes/test_nodes_restart.py
Add node operations
- Nodes maintenance related functions: 
Scheduling, unscheduling, drain and full maintenance
- Currently, due to the fact that pods are still using local storage, these operations won't work
with OCS. See BZ 1734162
=> Add nodes operations

tests/manage/storageclass/test_rbd_csi_default_sc.py
Improved my initial script by removing global variables, adding fixtures and handling the leftover PV(if any).
=> Updating OCS-347 with fixtures, removing global variable and handling the leftover PV

ocs_ci/framework/__init__.py
- do not process empty configuration section (which leads to
`AttributeError: 'NoneType' object has no attribute 'items'`)
- fixes https://github.com/red-hat-storage/ocs-ci/issues/538
=> skip empty configuration section

tests/manage/pv_services/test_delete_create_pvc_same_name.py
Update tests/manage/pv_services/test_delete_create_pvc_same_name.py 
- Fix Issue #525
- Updated the script to follow new coding guidelines for fixture usage
=> Update TC OCS-324: Fix #525 and use factory fixtures

ocs_ci/framework/conf/default_config.yaml, ocs_ci/utility/utils.py
Currently the builds from URL
https://openshift-release-artifacts.svc.ci.openshift.org/
are removed after 1 week. This allow us to use latest one and don't care
about changing version each week. We can always switch back to specific
version if needed.
=> Add capability to use latest nightly OCP accepted builds

tests/conftest.py
With this fix, the cephfilesystem pool will not be deleted
=> Fix ceph_pool_factory fixture

conf/examples/monitoring.yaml, ocs_ci/deployment/deployment.py, ocs_ci/templates/monitoring/README.md, ocs_ci/templates/monitoring/rbac.yaml
This is a minimal change to allow qe team to enable Prometheus based monitoring, required for OCS Monitoring, Telemeter and Alerting features.
Right now, it works only with upstream rook images, so it still remains disabled by default.
Note that when OCS OLM arrives, this (and most of bundled yaml files from rook) won't be necessary.
Quickstart: use ` --cluster-conf conf/examples/monitoring.yaml` to enable monitoring (checking content of the example config file and README introduced in this commit is suggested though).
Please *don't use squash and merge* github feature when merging this, it would violate DCO and make me revert such commit.
=> Monitoring testing

ocs_ci/ocs/ocp.py, tests/manage/cluster/nodes/test_nodes_restart.py
Using 'oc get' command not in the yaml format, calculates the resource
state in more accurate way and we should use it to fetch the status
=> Get the resource "real" status

tests/helpers.py
Datetime suffix doesn't sufficiently serve as random number when using threadpools where numerous objects are created within millisecond and high possibility of name collision occurs.
=> use uuid4 in hex as random suffix for ocs objects

ocs_ci/ocs/constants.py, ocs_ci/ocs/exceptions.py, ocs_ci/ocs/monitoring.py, ocs_ci/utility/deployment_openshift_logging.py, tests/conftest.py, tests/e2e/test_pvc_creation_performance.py, tests/fixtures.py, tests/helpers.py, tests/manage/pv_services/test_create_pvc_random_storage_class.py, tests/manage/pv_services/test_create_storage_class_pvc.py, tests/manage/pv_services/test_delete_create_pvc_same_name.py, tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py, tests/manage/pv_services/test_pvc_concurrent_deletion_creation.py, tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py, tests/manage/pv_services/test_reclaim_policy.py, tests/manage/storageclass/test_create_multiple_sc_with_same_pool_name.py, tests/manage/storageclass/test_create_storageclass_with_wrong_provisioner.py, tests/manage/storageclass/test_rbd_csi_default_sc.py, tests/sanity_helpers.py
In order to be able to delete a resource in the teardown, we should get the resource object, even if the wait for this resource has ended with a  failure.
=> Separate wait for resource from resource creation

tests/manage/pv_services/test_pvc_disruptive.py
Remove wait=False from create_pvc calls done with a TheadPoolExecutor
=> Fix PVC disruptive TCs

ocs_ci/ocs/constants.py, ocs_ci/ocs/node.py, ocs_ci/utility/aws.py, tests/helpers.py, tests/manage/cluster/nodes/test_nodes_maintenance.py, tests/sanity_helpers.py
- OCS-1269, OCS-1272 -  Maintenance (unschedule and drain) 1 worker/master node and check cluster functionality, then mark the node as scheduble and check cluster and Ceph health
- OCS-1273, OCS-1271 - Maintenance (unschedule and drain), mark as scheduble 2 worker/master nodes and check cluster functionality and health
- OCS-1274 - Maintenance (unschedule and drain) 1 worker+master nodes and check cluster functionality, then mark the nodes as scheduble and check cluster and Ceph health
=> Basic node maintenance tests

ocs_ci/ocs/constants.py, ocs_ci/templates/workloads/pgsql/PGSQL_Benchmark.yaml, tests/e2e/test_pgsql.py
Test run log:
```
Collecting Cluster versions
===================================================================== test session starts =====================================================================
platform darwin -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/tunguyen/OCS/pgsql-pr/ocs-ci, inifile: pytest.ini
plugins: marker-bugzilla-0.9.1.dev2, reportportal-1.0.5, html-1.22.0, logger-0.5.1, metadata-1.8.0
collected 1 item                                                                                                                                              
tests/e2e/test_pgsql.py::TestPgSQLWorkload::test_sql_workload_simple 
----------------------------------------------------------------------- live …
```
=> PGSQL workload: updated review comments

ocs_ci/ocs/monitoring.py, ocs_ci/ocs/resources/pod.py, tests/e2e/monitoring/test_when_respin_ceph_pods_interaction_with_prometheus.py, tests/helpers.py
A testcase to validate respinning ceph pods(osd, mon, mgr) shouldn't have functional impact to prometheus pods, all data/metrics should be collected correctly.
=> OCS-580: Respin ceph pod(osd, mon, mgr) and check the interaction with monitoring pods

.functional_ci_setup.py, Jenkinsfile
There's much less of a risk of exposing credentials via the workspace if we just never write them to disk.
=> Jenkins: Don't write AWS creds to disk

.travis.yml, ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/framework/pytest_customization/reports.py, tox.ini
Fixes issue #628
This allow us to run collect-only option with pytest to check some import errors and collection issues.
=> Allow collect only without running cluster

tests/conftest.py
Ensure that PV is deleted after deleting PVC to avoid errors caused by PV leftover.
=> Wait for PV to delete in pvc_factory finalizer

ocs_ci/ocs/constants.py, ocs_ci/utility/prometheus.py, tests/manage/monitoring/conftest.py, tests/manage/monitoring/prometheus/test_deployment_status.py
- Add `DEPLOYMENT` constant.
- Change Prometheus API calling logs from `INFO` to `DEBUG` severity.
- Add `tests/manage/monitoring/conftest.py` with `measure_operation` function that simplifies workload measurement for monitoring.
- Add `workload_stop_ceph_mgr` fixture.
- Add `test_ceph_manager_stopped`.
Signed-off-by: Filip Balak fbalak@redhat.com
=> Stop Ceph Manager alerting test case

tests/manage/noobaa/test_bucket_creation.py
Name changed for conformity
Test should be skipped until NooBaa will be deployed as part of OCS
=> Change NooBaa bucket creation test filename, skip the test

ocs_ci/ocs/resources/pod.py, ocs_ci/ocs/resources/pvc.py, tests/conftest.py, tests/e2e/test_pv_scale_ocs_create_delete_pvcs.py, tests/helpers.py
Test case to scaleout pvc and pod with create, delete in parallel during test execution check for memory leak on ceph-osd process.
Signed-off-by: Ramakrishnan rperiyas@redhat.com
=> OCS Scale test case to create delete pvc parallel and check for memory leak

ocs_ci/framework/conf/default_config.yaml, ocs_ci/ocs/utils.py
It's also required to run the OCP image twice since by default it will not
collect the worker node service logs (where OCS issues might be otherwise
logged).
Fixes: #673
Signed-off-by: Jason Dillaman <dillaman@redhat.com>
=> Run OCP and OCS must-gather images for failed tests

ocs_ci/ocs/resources/pod.py, tests/e2e/monitoring/test_when_one_of_the_prometheus_node_down.py
When the nodes are down, there should not be any functional impact on monitoring pods. All the data/metrics should be collected correctly.
=> OCS 606: When one of the prometheus node is down interaction with monitoring pods	

tests/manage/pv_services/test_pvc_deletion_during_io.py
- Test also CephFS (OCS-1318)
- Change tier1 to tier2
- Use factory fixtures
- Use wait_for_resource for PVC to reach 'Terminated'
=> test_run_io_and_delete_pvc: Few improvements

ocs_ci/ocs/resources/noobaa.py, tests/manage/noobaa/conftest.py, tests/manage/noobaa/test_bucket_creation.py, tests/manage/noobaa/test_bucket_deletion.py, tests/manage/noobaa/test_write_to_bucket.py
*Implemented new asserts for added assurance
*Moved and merged `create_buckets` into `created_buckets`
*Implemented the ability to create and delete a dynamic amount of buckets
*Fixed an outdated access to a private member that has been changed into a public one
=> Various fixes and improvements for NooBaa tests

tests/conftest.py, tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py, tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Tests modified to use RWX and RWO PVC:
test_disruptive_during_pod_pvc_deletion_and_io
test_disruptive_during_pod_pvc_deletion
Modified multi_pvc_factory to create PVC based on the
provided access modes
=> Modifying tests to use RWX PVC

ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/pod.py, ocs_ci/ocs/resources/pvc.py, ocs_ci/templates/app-pods/raw_block_pod.yaml, tests/conftest.py, tests/fixtures.py, tests/helpers.py, tests/manage/pv_services/test_raw_block_pv.py
tests/manage/pv_services/test_raw_block_pv.py
Testing basics of RBD RWX raw block pv feature
ocs_ci/ocs/constants.py
Added pod template for rbd raw block pv
Added parameter volume_mode to create_pvc() for creating raw block pv
Modified number of retries of function validate_pv_delete() due to bz1726266
ocs_ci/ocs/resources/pod.py
For block IOs, added path of block device
=> Testing basics of RBD RWX raw block pv support:OSC-750 and OCS-751

.functional_ci_setup.py, Jenkinsfile
This assumes the content of bugzilla.cfg is in the `BUGZILLA_CFG` environment variable. I'm choosing here to write `$PWD/bugzilla.cfg`, since the plugin supports it, and there's no real reason to write a system-wide or user-wide file.
=> jenkins: Write bugzilla.cfg

tests/manage/pv_services/test_verify_rwo_using_multiple_pods.py
This test case verifies RWO reclaim policy by trying to mount same RWO
PVC on different pods, delete running pods one by one and ensure that
only one pod is running at a time
=> Test case test_verify_rwo_using_multiple_pods

tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
Pod name will have 'cephfs' or 'rbd' based on the interface.
This update does not bring any change in the functionality
=> Update test case to pass interface parameter to pod_factory

ocs_ci/framework/conf/default_config.yaml
- the file ocs_v1alpha1_storagecluster_cr.yaml was renamed to
ocs_v1_storagecluster_cr.yaml (https://github.com/openshift/ocs-operator/tree/master/deploy/crds)
- fixes https://github.com/red-hat-storage/ocs-ci/issues/723
=> fix ocs_operator_storage_cluster_cr url

ocs_ci/ocs/ocp.py, tests/helpers.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/631
There are few minor fixes for the logging, each change is in a separate commit. Some of hte changes are demonstrated below:
Before, it was not clear what is the purpose of the repeating get operations,
and what is the actual state of resource which we are waiting for:
```
14:07:32 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ocsqe/data/cluster-2019-08-19.1/auth/kubeconfig get PersistentVolume pvc-216d7a12-c279-11e9-a6dc-0625533a766a -o yaml
14:07:33 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/ocsqe/data/cluster-2019-08-19.1/auth/kubeconfig get PersistentVolume pvc-216d7a12-c279-11e9-a6dc-0625533a766a
14:07:36 - MainThread - ocs_ci.utility.utils - …
```
=> Logging improvements for ocs 530

ocs_ci/ocs/constants.py, ocs_ci/utility/deployment_openshift_logging.py, tests/e2e/logging/test_openshift-logging.py
The file contains code for deployment of openshift-logging, testcases related to openshift-logging and 
the teardown of openshift-logging. 
```
test_fixtures():
teardown() # of openshift-logging
setup() # of openshift-logging
class test_logging():
def testcase_657():
def testcase_--(): # Todo
```
=> Testcase OCS-657 for openshift-logging

ocs_ci/deployment/deployment.py, ocs_ci/ocs/defaults.py, ocs_ci/templates/CSI/cephfs/CephFileSystem.yaml
The cpehfs is now created by operator, so finishing this TODO.
Fixes: #740
=> Not create cephfs when deploying via operator

ocs_ci/deployment/deployment.py, ocs_ci/ocs/monitoring.py, ocs_ci/ocs/resources/ocs.py, ocs_ci/ocs/resources/pod.py, ocs_ci/ocs/ripsaw.py, ocs_ci/ocs/tests/test_defaults.py, ocs_ci/utility/deployment_openshift_logging.py, ocs_ci/utility/templating.py, tests/e2e/test_pgsql.py, tests/e2e/test_small_file_workload.py, tests/helpers.py, tests/libtest/test_fio_workload.py, tests/manage/pv_services/test_pvc_invalid_inputs.py, tests/manage/storageclass/test_create_storageclass_with_same_name.py, tests/manage/storageclass/test_storageclass_invalid.py, tests/manage/storageclass/test_verify_all_fields_in_sc_yaml_with_oc_describe_sc.py
This was requested by @vasukulkarni to move this commit from PR #713 .
Changes the name of the method load_yaml_to_dict to just load_yaml.
This is because the method doesn't return just the dict but also generator in case of multi_document=True passed.
=> Change name of load_yaml_to_dict method to load_yaml

tests/e2e/monitoring/test_when_one_of_the_prometheus_node_down.py
TestWhenOneOfThePrometheusNodeDown needs to be adjusted to the changes done in tests/sanity_helpers.py, as part of https://github.com/red-hat-storage/ocs-ci/pull/679/files
=> Adjust prometheus tests to changes in sanity helpers

ocs_ci/deployment/deployment.py
This verbose output will allow us investigate issue when we see error:
UnavailableResourceException: Not enough worker nodes: 2 to label: 3 or
taint: 0!
Fixes: #770
=> Verbose output of nodes

ocs_ci/framework/conf/default_config.yaml, ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
For NooBaa deployment (requires a minimum of m4.xlarge worker machine)
=> Upgrade the default worker instance type from m4.large to m4.xlarge

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
OCS-1012
CEPHFS: Delete csi-cephfsplugin while PVC deletion, Pod deletion and IO are progressing
OCS-1015
RBD: Delete csi-rbdplugin while PVC deletion, Pod deletion and IO are progressing
=> test_ocs_1012_1015

ocs_ci/ocs/resources/csv.py
We didn't raise an exception when CSV wasn't in desired phase.
Now we should fail if the CSV deployment is not successful.
=> Add Raises to the doc for CSV wait_for_phase method

ocs_ci/ocs/ripsaw.py, tests/e2e/test_pgsql.py
Fixed timeout, removed tier1 and added switching back to namespace "openshift-storage" after cleanup.
``` 
Collecting Cluster versions
=============================================================== test session starts ===============================================================
platform darwin -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/tunguyen/OCS/ocs-ci, inifile: pytest.ini
plugins: marker-bugzilla-0.9.1.dev2, reportportal-1.0.5, html-1.22.0, logger-0.5.1, metadata-1.8.0
collected 1 item                                                                                                                                  
tests/e2e/test_pgsql.py::TestPgSQLWorkload::test_sql_workload_simple 
----------------------------------------------------------------- live …
```
=> Fix pgsql test

tests/manage/pv_services/test_pvc_concurrent_deletion_creation.py
The Test case  test_pvc_concurrent_deletion_creation.py was intermittently failing in teardown due to PV leftovers. 
E.g. https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/865/
The failure is due to leftover PVs in Released state. There are some knows bugs around it, e.g. BZ#1729853 and it is an intermittent issue.
Plan - test will be updated to use pvc_factory to get rid of this issue - Won't call it as a automation bug fix because it is not automation bug. 
Why we update the test instead of marking some related bug to skip the test ?
- It is because the bug(PV in released state for long time) is not affecting the test case. The test case is passing. Only teardown is failing.
Also, added check for underlying PV delete once all PVCs are deleted.
@jilju thanks …
=> Fixes the ocs-ci tier2 failure due to leftover PVs in Test case test_pvc_concurrent_deletion_creation.py

ocs_ci/ocs/monitoring.py, tests/e2e/monitoring/test_reboot_node_where_mgr_running.py
Test case to validate rebooting a node where mgr is running should not delete the data collected on prometheus pod.
=> OCS-710: OCP monitoring backed by OCS, Reboot node where MGR is running

tests/disruption_helpers.py, tests/e2e/test_pv_scale_and_respin_ceph_pods.py, tests/helpers.py
tests/disruption_helpers.py 
Updated changes to re-spin particular ceph daemon pod
tests/e2e/test_pv_scale_and_respin_ceph_pods.py
New Test case for pvc scale and respin ceph pods during pvc creation
Updated Create pods in parallel function to support RAW block pvc
Signed-off-by: ramkiperiy rperiyas@redhat.com
=> pvc scale in parallel with ceph pods re-spin test cases

ocs_ci/ocs/resources/pod.py, tests/disruption_helpers.py, tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
pod.py
Added function to get csi-cephfsplugin-provisioner or csi-rbdplugin-provisioner leader pod
disruption_helpers.py
Added resource types cephfsplugin_provisioner and rbdplugin_provisioner
Using selector to fetch pod details
=> Adding test cases OCS-945 OCS-952

ocs_ci/deployment/aws.py, ocs_ci/framework/conf/default_config.yaml, ocs_ci/ocs/exceptions.py
Addresses issue https://github.com/red-hat-storage/ocs-ci/issues/779 - Prevent cluster deployment in case a cluster with the same kerberos ID already exists
=> Prevent deployment according to cluster name prefix

tests/manage/pv_services/test_pvc_disruptive.py
OCS-940	RBD: Delete csi-rbdplugin-provisioner while creating app pods in bulk
OCS-941	RBD: Delete csi-rbdplugin-provisioner while creating RWO and RWX PVCs in bulk
OCS-942	RBD: Delete csi-rbdplugin-provisioner while running IO
OCS-947	CEPHFS: Delete csi-cephfsplugin-provisioner while creating app pods in bulk
OCS-948	CEPHFS: Delete csi-cephfsplugin-provisioner while creating RWO and RWX PVCs in bulk
OCS-949	CEPHFS: Delete csi-cephfsplugin-provisioner while running IO
=> Adding tests in test_pvc_disruptive

tests/e2e/monitoring/test_monitoring_after_reboot_master_node.py
A testcase to validate reboot of OCP master node has no functional impact to OCP monitoring backed by OCS. 
Here using ignore_leftovers marker because when master node is rebooting 'oauth-openshift-xxxxxxxxxx-xxxxx' pod under the namespace 'openshift-authentication' is re-spinning and coming with new name. So it fails during environment check saying one resource added and one resource removed.
https://paste.fedoraproject.org/paste/MKy2rYPKpLWd~E2O4tkJDA
=> OCS-709 - OCP monitoring backed by OCS, reboot master node

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
OCS-946	RBD: Delete csi-rbdplugin-provisioner while PVC deletion, Pod deletion and IO are progressiing
OCS-953	CEPHFS: Delete csi-cephfsplugin-provisioner while PVC deletion, Pod deletion and IO are progressing
=> Adding test cases OCS-946 and OCS-953

ocs_ci/deployment/aws.py
Do not print error message about non terminated instances when there are no such instances present.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/808
=> Fix error message for non terminated instances

setup.py
update pytest-marker-bugzilla that includes additional fix to skip the tests
when also in MODIFIED or POST state.
=> update pytest-marker-bugzilla that includes additional fix 

tests/e2e/test_pgsql_pod_respin.py
Test cases: OCS-802, OCS-803, OCS-804
Respin Ceph pods (mon, osd, mgr) while running pgsql workload.
=> Respin Ceph pods while running pgsql workload

.functional_ci_setup.py, Jenkinsfile
This changes our config to match the downstream_config.yaml
file in ocs-ci. We also pass the original downstream_config.yaml
as an extra --ocsci-conf argument.
The only ocs-operator build I was able to get working was:
http://quay.io/rhceph-dev/ocs-registry:4.2-77.bed1df0.master
=> downstream-ci: fix OCP deployment

tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
OCS-943	RBD: Delete csi-rbdplugin-provisioner while deleting app pods in bulk
OCS-944	RBD: Delete csi-rbdplugin-provisioner while deleting RWO and RWX PVCs in bulk
OCS-950	CEPHFS: Delete csi-cephfsplugin-provisioner while deleting app pods in bulk
OCS-951	CEPHFS: Delete csi-cephfsplugin-provisioner while deleting RWO and RWX PVCs in bulk
=> Additional tests in test_disruptive_during_pod_pvc_deletion

ocs_ci/deployment/deployment.py, ocs_ci/ocs/cluster.py
Fixes Issue #810 
1. Added check for ceph pvcs - mon and osd are BOUND
2. Validate the OSD and MON pods are backed by ceph PVCs
3. Validate that the PVC is mounted on MON pod. 
P.S - In OSD, it is attached with volumeMode Block, hence no similar check can be done
Signed-off-by: Neha Berry <nberry@redhat.com>
=>  Fixes Issue#810 - Added validation for cluster on PVC during deployment

tests/e2e/test_pv_scale_ocs_create_delete_pvcs.py
Updated TC to skip memory leak function due to bz 1750328
Removed TODO for creating RAW block pod creation
Removed executor and implemented threads for parallel execution of function
Removed self variables which doesn't require across Class
Signed-off-by: ramkiperiy <rperiyas@redhat.com>
=> tests/e2e/test_pv_scale_ocs_create_delete_pvcs.py -- Enhanced

.functional_ci_setup.py, ocs_ci/deployment/deployment.py, ocs_ci/framework/conf/default_config.yaml, ocs_ci/ocs/utils.py
This can be opted-out by setting `REPORTING.gather_on_deploy_failure=False`
=> Jenkins: Optionally gather logs on deploy failure

.functional_ci_setup.py
=> downstream ci: use OCS_REGISTRY_IMAGE for ocs_operator_image config

ocs_ci/ocs/resources/pod.py
Fixing the test case test_pvc_rwx_writeable_after_pod_deletions
Fixes: #856 
=> Fixing issue 856

ocs_ci/deployment/deployment.py
Noticed these typos when I was going through source code to better understand tool capabilities and code flow.
Signed-off-by: Mirek Długosz <mzalewsk@redhat.com>
=> Fix typos in deployment add_node method

ocs_ci/framework/conf/default_config.yaml
worker_instance_type is listed twice: on line 81 and on line 101. This
removes second one.
Signed-off-by: Mirek Długosz <mzalewsk@redhat.com>
=> Remove extra worker_instance_type from sample config

docs/debugging.md, docs/getting_started.md, ocs_ci/framework/conf/default_config.yaml
We need to change the default of libra ssh key to the new openshift-dev key.
=> Change default libra to openshift-dev ssh key

ocs_ci/ocs/utils.py
=> collect_ocs_logs(): Skip if there is no kubeconfig

ocs_ci/ocs/resources/pod.py, ocs_ci/ocs/utils.py
Check if ceph_toolbox exists and if not create one, this is needed when OCS is deployed by other CI tools
=> check/create toolbox when ocs is deployed by other CI tools

tests/manage/pv_services/test_pvc_disruptive.py
OCS-925	CEPHFS: Delete Operator while creating app pods in bulk
OCS-927	CEPHFS: Delete Operator while creating RWO and RWX PVCs in bulk
OCS-928	CEPHFS: Delete operator while running IO
OCS-936	RBD: Delete Operator while creating app pods in bulk
OCS-937	RBD: Delete Operator while creating RWO and RWX PVCs in bulk
OCS-938	RBD: Delete operator while running IO
=> Verify rook-ceph-operator deletion during resource creation

tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
OCS-935	CEPHFS: Delete Operator while deleting app pods in bulk
OCS-926	CEPHFS: Delete Operator while deleting RWO and RWX PVCs in bulk
OCS-931	 RBD: Delete Operator while deleting app pods in bulk
OCS-932	RBD: Delete Operator while deleting RWO and RWX PVCs in bulk
=> Test delete operator during resource deletion

tests/helpers.py, tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
OCS-930	CEPHFS: Delete Operator while PVC deletion, Pod deletion and IO are progressing
OCS-934	RBD: Delete Operator while PVC deletion, Pod deletion and IO are progressiing
=> Test delete rook-ceph-operator during deletion of PVCs and pods

ocs_ci/deployment/deployment.py, ocs_ci/ocs/cluster.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/utils.py
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/895
Remove backed PVC verification after deployment, if this needs to be done
It can be a separate test but not part of deployment.
=> Fix for Mon/OSD PVC checks

ocs_ci/deployment/deployment.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/ocp.py, ocs_ci/ocs/registry.py, tests/helpers.py
Updated deployment.py to change registry backend to OCS CEPHFS RWX PVC
registry.py -- registry library functions python file
ocp.py -- added new function to perform path operation in crd
constants.py -- added new constants regarding registry deployment
Requirements KNIP: https://jira.coreos.com/browse/KNIP-1080
Signed-off-by: ramkiperiy <rperiyas@redhat.com>
=> Registry backed by OCS and registry library functions

ocs_ci/deployment/vmware.py
Skip adding disk for operator deployment for vSphere platform
=> Skip adding disk for operator deployment

conf/ocsci/aws_region_us-east-1.yaml
As this issue was found:
https://github.com/noobaa/noobaa-operator/issues/90
We would like to test with us-east-1 region to see if we have other
issues.
=> Add config for us-east-1 region

tests/manage/pv_services/test_pvc_disruptive.py, tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
Updated below tests to create rbd block type RWO volume
tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
tests/manage/pv_services/test_pvc_disruptive.py
=> Adding block type RWO pvc in tests

ocs_ci/framework/conf/default_config.yaml, ocs_ci/ocs/constants.py, ocs_ci/ocs/defaults.py, ocs_ci/ocs/registry.py
The discussion was brought up in email where in CI we are using 'rook-ceph' as clustername which is different from what UI method uses. 
=> Fix storage cluster name to use default name as in UI

ocs_ci/ocs/constants.py, tests/helpers.py, tests/manage/monitoring/conftest.py, tests/manage/monitoring/prometheus/test_ceph.py
- Add `test_corrupt_pg_alerts` test case.
- Add `create_dummy_osd` function. This can be used for Ceph storage manipulation as by using osd created by this function there is no lock on osd data.
=> Corrupted Placement Group alert test case

setup.py
Fixing boto3 install issue.
manually pin python-dateutil to 2.8.0 till
https://github.com/boto/botocore/issues/1872 is fixed
Fixes: #966
=> Fixing boto3 install issue.

docs/getting_started.md
google-auth requires setuptools which is >=40.3.0
Updating the documentation for upgrading setuptools
Fixes: #970
=> google-auth requires setuptools which is >=40.3.0

ocs_ci/utility/utils.py
use --client option to avoid connecting to server, server may not exist when setting up new cluster
should also fix: https://github.com/red-hat-storage/ocs-ci/issues/961
=> Avoid connecting to server when setting up new cluster

ocs_ci/ocs/resources/mcg.py
Quick fix to invalid mcg region issue which was supposed to be fixed in #995. 
Noobaa had changed address scheme which resulted in fetching invalid region name.
=> MCG region fix

conf/ocsci/production_device_size_e2e.yaml
For all performance and scale testing, we will need to run the tests with the actual device size planned for OCS. i.e., 2TB. This PR adds a config to create devices with 2 TB. 
p.s., We are not updating production_device_size.yaml to 2 TB as running CI jobs (which are mostly functional tests) with 2TB OSDs would be an overkill.
=> Adding production device size as '2TB' for perf and scale testing

Jenkinsfile
This starts a job that tags the ocs-registry image as 'latest-stable'
when it passes the acceptance tests.
=> downstream-ci: tag ocs-registry as 'latest-stable' when tests pass

ocs_ci/deployment/vmware.py
PR: #831 limits the default timeout to 600 sec for run_cmd
default timeout is not enough for installation.
Fixes: #1024
=> Adding timeout parameter for vsphere UPI installation.

ocs_ci/ocs/resources/pod.py
- Added timeout parameter to exec_cmd_on_pod(), fixes https://github.com/red-hat-storage/ocs-ci/issues/1026
=> timeout for ocs_ci/ocs/resources/pod.py:exec_cmd_on_pod() 

tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
Consists of test cases to change and verify reclaim policy of PV
OCS-939 | RBD: Change RecalimPolicy of a PV from Delete to Retain
-- | --
OCS-962 | RBD: Change RecalimPolicy of a PV from Retain to Delete
OCS-963 | CEPHFS: Change ReclaimPolicy of PV from Delete to Retain
OCS-964 | CephFS: Change RecalimPolicy of a PV from Delete to Retain
=> Tests: Change reclaim policy of PV

ocs_ci/templates/app-pods/fedora_dc.yaml
Adding resource limit will avoid more resource consumption by fedora pods
=> Add resource limits for fedora pods

ocs_ci/ocs/resources/mcg.py
The NooBaa stats update every 120 seconds. This timeout was too strict, and was extended to 140 to allow edge cases to be caught.
=> Fix test_data_reduction

ocs_ci/ocs/machine.py, tests/manage/cluster/cluster_expansion/test_add_capacity.py
This PR is to test the new OSD limit we are going to support (which is 3 OSD per node with 2 TB per OSD). I've included configurable parameters to vary the amount of OSDxnode and the OSD storage capacity.
=> Provide new configurable storage parameters for OSD

tests/helpers.py
=> Use specific failureDomain while creating new cephblockpool

.functional_ci_setup.py
This just works around an issue where the pull secret might appear to be valid base64, but isn't.
=> Jenkins: Skip base64 if Unicode decoding fails

tests/manage/pv_services/test_no_space_left.py
Removed check for fio failure. fio need not throw error when trying to utilize 100% space.
The intention of test is to validate full utilization of available space.
Fixes #1106 
=> Fix test_pvc_no_space_left

Jenkinsfile
We're changing the parameters to our quay-tag-image job and
need to update them here as well. We also want to tag the
ocs-olm-operator container as latest-stable.
=> downstream-ci: change parameters for the quay-tag-image job

ocs_ci/utility/utils.py
Testrun_name parameter should be taken directly from REPORTING
configuration section, not from polarion subsection.
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/1124
=> look for testrun_name parameter in REPORTING section

ocs_ci/deployment/aws.py
Give cloudformation stacks additional time to successfully delete before we fail
Fixes: #1132 
=> Increase retries for aws upi cloudformation stack deletion check

tests/manage/pv_services/test_no_space_left.py
Wait for pods to delete before using the pvc on another pod
This will avoid multi-attach error
Fixes #1149 
=> Test fix - wait for pod to delete before creating new pod

ocs_ci/utility/prometheus.py, tests/manage/monitoring/test_workload_fixture.py
This branch adds `query_range` function to Prometheus class, implementing qe wrapper for range queries usable for metrics testing. The test provided is just a libtest demonstration.
=> prometheus range query method with example

ocs_ci/templates/ocs-deployment/storage-cluster.yaml
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/1170
As mentioned in BZ https://bugzilla.redhat.com/show_bug.cgi?id=1782110
We should use:
replica: 3
count: 1
in storage cluster specs
=> Fix storageCluster CR for BZ1782110

ocs_ci/ocs/resources/mcg.py
I suspect that multiple test runs have failed because of an attempt to create an S3 bucket with a name that already exists.
This randoms the name and prevents further mishaps that may be caused by this.
=> Change the AWS credential verification bucketname to be random

ocs_ci/templates/app-pods/fedora_dc.yaml
Having this privileged will not allow us to catch this type of [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1777384) 
Because making this privileged dc pod will be able to write on mount point even when normal pod doesn't have permission to write on that mount point
=> Remove securityContext from container section 

ocs_ci/ocs/resources/pod.py, tests/manage/z_cluster/nodes/test_nodes_maintenance.py, tests/manage/z_cluster/nodes/test_nodes_restart.py
Addresses https://github.com/red-hat-storage/ocs-ci/issues/1222 and fixes the failure in tests.manage.z_cluster.nodes.test_nodes_maintenance.TestNodesMaintenance.test_2_nodes_maintenance_same_type
=> Workaround for BZ 1778488 and fix for test_2_nodes_maintenance_same_type

conf/ocsci/ocp-4.2-config.yaml
For this ticket: https://projects.engineering.redhat.com/browse/OCSQE-166
We need to have also static file for OCP 4.2 to allow us to easily pass
from job parameter which one OCP config file to use for specific
version.
This will be also needed if we decide later on to have OCP 4.3 as a
default.
=> Add OCP 4.2 config file

tests/e2e/test_pvc_deletion_performance.py
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/1266
=> Fetch PV reclaim policy before deleting the PVC in the pv deletion perf testcase

ocs_ci/templates/workloads/smallfile/SmallFile.yaml, tests/e2e/test_small_file_workload.py
Fix the testcase to use default storageclass and iterate over both RBD and FS
=> Fix Storageclass name and iterate over both RBD and FS

ocs_ci/framework/pytest_customization/marks.py, tests/manage/mcg/test_bucket_creation.py
* Replace all 'tier2' markers with 'performance'
* Reorder param calls
* Add an always skipif marker
=> Change MCG bucket creation tests markers

ocs_ci/templates/app-pods/raw_block_pod.yaml
Fixes: #1292 
Removed nodeName spec from the template. It will be added by 
helpers.create_pod() dynamically.
=> Remove nodeName spec from ocs_ci/templates/app-pods/raw_block_pod.yaml

tests/manage/pv_services/test_pvc_concurrent_deletion_creation.py
OCS-2018
Test case will verify creation and deletion of cephfs based volume in bulk
Verify that the status of nodes are 'Ready'
=> Test case to verify bulk PVC creation and deletion

ocs_ci/ocs/resources/ocs.py
The CSI driver object should have provisioner names mentioned. Adding this verification in ocs_install_verification function.
Fixes #1332  
=> Verify that CSI driver object contains provisioner names

tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
This kind of problem has been already addressed in commit 54e85512b61ef60d80d2837242ff6fba9e1108ab, but one occurrence was missed there.
=> fix one overlooked copypaste error from metric spec

ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/ocs.py
Verify node and provisioner secret names in ocs-storagecluster-ceph-rbd and ocs-storagecluster-cephfs storage class. There should be different secrets for provisioning and mount.
Fixes #1322 
=> Verify secret names in default storage class

ocs_ci/ocs/constants.py, ocs_ci/ocs/machine.py, ocs_ci/ocs/node.py, tests/e2e/test_small_file_workload.py, tests/helpers.py
Fixes #1340
Signed-off-by: Mirek Długosz <mzalewsk@redhat.com>
-----
This is prompted by BZ#1765923. General idea is that we want to catch critical errors and fail test based on them. Ideally, such check should be performed automatically for all tests.
I tried using autouse fixture that added finalizer, but finalizers are run after test has already completed - they can't change "PASSED" test to failed based on additional condition. They can only "ERROR" test in teardown phase. So for now this is additional helper function that test must call directly.
Another drawback - since all `oc` commands and their output is logged in test log, log files will grow in size. In small file test I saw increase from ~2.5 MB to ~3.5 MB, but during development I saw log over 100 MB (!). This is something we …
=> Check pod/node logs for critical errors

ocs_ci/ocs/ocp.py
Fixes: #1359
Add timeout parameter to ocs_ci/ocs/ocp.py: exec_oc_debug_cmd()
=> Add timeout (default 600 seconds) for exec_oc_debug_cmd()

tests/e2e/logging/test_openshift-logging.py
74271475 (#1267) renamed `delete_deploymentconfig` to
`delete_deploymentconfig_pods`. Then a07a1184 (#1349) reverted this
change in openshift logging test, probably by mistake. Re-revert it and
use correct new name again.
Signed-off-by: Mirek Długosz <mzalewsk@redhat.com>
=> [openshift-logging] Use correct helper function name

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Fixes: #1357 
- Add bugzilla [1793387](https://bugzilla.redhat.com/show_bug.cgi?id=1793387) decorator to test_resource_deletion_during_pvc_pod_deletion_and_io
=> Issue 1357 test decorator

ocs_ci/ocs/constants.py, ocs_ci/ocs/registry.py
Updated registry deployment to use DEFAULT_STORAGECLASS_CEPHFS
Removed DEFAULT_SC_CEPHFS from constants.py
=> Updated registry deployment to use DEFAULT_STORAGECLASS_CEPHFS

ocs_ci/deployment/ocp.py
* (re)raise exception of failed openshift-install destroy cluster command
* fixes: https://github.com/red-hat-storage/ocs-ci/issues/1352
=> do not ignore failed cluster destroy command

Jenkinsfile
Builds that pass the acceptance tests will now be tagged as
`latest-stable-$ocs_version` instead of just `latest-stable`.
=> downstream-ci: include the ocs version in the `latest-stable` tag

ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/ocs.py, ocs_ci/ocs/resources/pvc.py, setup.py
Updated ocs_install_verification function to verify ceph osd tree output.
ceph osd tree output structure and values are verified.
Using JSON Schema to validate the output.
Presence of device set PVC names is also verified along with this. (Verifies bug https://bugzilla.redhat.com/show_bug.cgi?id=1765154)
Implemented in this way because there are more checks to be done
in the output. Added as TODO.
=> Verify osd tree output and ensure it have device set PVC names

Jenkinsfile
This will allow us to easily switch to another
aws user if we need to for any reason.
=> downstream-ci: store aws credentials per user

Jenkinsfile
This is to allow access to the cluster to triage failures
before the cluster is destroyed.
=> downstream-ci: ask for confirmation before cluster teardown

tests/manage/mcg/helpers.py, tests/manage/mcg/test_bucket_deletion.py
Add test case for delete 100 and 1000 buckets and OBCs, delete                                                                                                                                                                            
non-empty bucket and OBC, delete non-existant bucket and OBC.                                                                                                                                                                             
Signed-off-by: Wayne Sun <gsun@redhat.com>
=> Add more bucket and OBC deletion cases

ocs_ci/framework/conf/default_config.yaml
Infra ticket: https://projects.engineering.redhat.com/browse/OCSQE-216
=> Move ocs-ci to use OCP/OCS 4.3 as default

ocs_ci/ocs/constants.py, ocs_ci/ocs/registry.py
=> Change ManagementState for image registry for non cloud platforms

ocs_ci/ocs/ocp.py
Reporting error in test logs when OCP.get() fails is problematic,
because whether this is actual error from the test point of view or not
can be only understood when taking context of the caller in mind.
So to avoid reporting errors when the call is expected to fail, the
loging is changed to warning level. The actuall error is not lost, as
the code throws an exception in the end anyway.
This is a minimal fix of the problem.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/1355
=> fix logging issue in ocs_ci.ocs.ocp.OCP.get()

tests/ecosystem/upgrade/test_configuration.py
https://github.com/red-hat-storage/ocs-ci/pull/1112 changed name of pod function `exec_bash_cmd_on_pod` to `exec_sh_cmd_on_pod`. This PR fixes the use of it in a test.
=> Fix function name

ocs_ci/ocs/constants.py
Removed maximum and minimum value check for crush_weight using schema. Schema had a maximum value parameter for crush_weight which was set to 1. The value can be more than 1.
=> Fix osd tree schema- remove maximum and minimum value for crush_weight

ocs_ci/ocs/ocp.py, ocs_ci/ocs/registry.py, tests/e2e/registry/test_registry_image_push_pull.py
Modified ocs_ci/ocs/ocp.py exec_oc_debug_cmd function timeout to 300 sec
Modified ocs_ci/ocs/ocp.py rsync function to get namespace from OCP obj
Modified ocs_ci/ocs/registry.py updated function get_oc_podman_login_cmd
Added ocs_ci/ocs/registry.py function check_image_in_registry
=> Registry Testcase to perform image push pull.

tests/manage/monitoring/prometheus/test_ceph.py
Skip tests in test_ceph.py because of https://github.com/red-hat-storage/ocs-ci/issues/1477 until further investigation is done.
=> skip test_ceph.py test cases

ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/ocs/exceptions.py, ocs_ci/ocs/resources/packagemanifest.py, ocs_ci/ocs/resources/test_packagemanifest.py
Make the ocs-ci code more robust so that running test is possible even during problem with packagemanifest as reported in https://github.com/red-hat-storage/ocs-ci/issues/1338 (which would make pytest crash immediately otherwise).
This fixes ocs-ci part of the problem covered in https://github.com/red-hat-storage/ocs-ci/issues/1338
=> Don't fail when channel info is missing because of issues/1338

ocs_ci/ocs/constants.py
To address jenkins failure 
```
self.ocp_repo = constants.REPO_MAPPING[version]
E       KeyError: '4.3.0'
``` from the run 
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/4703
=> Address key error failure for vmwre UPI run

conf/ocs_version/ocs-4.2.yaml
Cause of they created new 4.2 build which is not RC:
https://quay.io/repository/rhceph-dev/ocs-olm-operator?tab=tags
It's currently upgrading to this latest build but our jobs
are not aligned yet to provide specific build.
So with this fix we will be able to continu testing upgrade.
=> Move 4.2 to use RC builds as default

tests/e2e/logging/test_openshift-logging.py, tests/e2e/registry/test_registry_image_push_pull.py
We want to have a basic test case after installation of Logging, Monitoring, and Registry as tier1 and move the rest of the scenarios to workloads.
=> Adds basic test for Logging, Monitoring, Registry as tier1

ocs_ci/utility/utils.py
Fix in getting OCP version when we have batch version like 4.2.18
Fixes: #1512
=> Fix in getting OCP version when we have batch version

tests/helpers.py
Fixes #1524 
All scale tests failed as a result of the pre-pull of container images when done in bulk - https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/4856/
=> Remove default pre-pull of images

tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
ocs-ci/tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
The verification whether image or subvolume is delected is being done
just after the PV is deleted. Sometimes it will take more time to delete.
So adding wait time for the verifcation.
=> Add timeout for verifying image/subvolume deletion in testcase

ocs_ci/ocs/registry.py, tests/e2e/registry/test_registry_image_push_pull.py
Added pytest skip marker to skip registry test case execution due to #1547
Updated formatting in registry.py
=> Skip test case due to #1547

ocs_ci/ocs/constants.py, ocs_ci/ocs/machine.py, ocs_ci/templates/openshift-infra/machine-set.yaml
Create custom machineset for creating nodes with different instance type.
Using this machineset we can scale nodes for app pod creation/deletion.
This will not affect the OCS worker node.
ocs_ci/ocs/constants.py --> Updated with new yaml file path
ocs_ci/ocs/machine.py --> Added function to create and delete machineset
ocs_ci/templates/openshift-infra/machine-set.yaml --> machineset yaml file
=> Create custom machineset for creating nodes with different instance type and node scale

pytest.ini, tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
This reverts commit 9fea1c3bc8bc4f6d2959877e8bb1c1709e13869d.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/1324
=> Revert "BZ 1790558 workaround"

ocs_ci/ocs/constants.py
This is quick fix for the issue below.
Fixes: #1561
We will need to do better fix for this to have it dynamically.
=> Add new 4.3.1 to repo map for OCP RHEL

ocs_ci/ocs/resources/storage_cluster.py
The rook-ceph-operator deployment can be in any order in the list of deployments in csv. It is required to fetch the deployment with name instead of sticking to the structure of the output.
=> Update CSI_ENABLE_SNAPSHOTTER value check

ocs_ci/utility/utils.py
When the configuration sets none of the variables
worker_availability_zones, availability_zone_count,
or platform is not equal to 'vmware', then the get_az_count()
function currently returns "3" as a default.
When there are actually less than 3 zones, this leads to
errors in the post-install deployment checks that check
for the failure domain being set to "zone" in the crush map.
The safe default is one zone.
Signed-off-by: Michael Adam <obnox@redhat.com>
=> Fix the get_az_count() function to default to 3.

ocs_ci/ocs/node.py
Existing get_resource_utilization function gets data from adm, which is not more accurate.
Changed existing function to 'get_node_resource_utilization_from_adm_top'.
=> Added new function to get node resource utilization from 'oc describe node'

tests/e2e/performance/test_vdbench_workload.py
Adding new parameter for selecting if the app pod will run on the same
workers as the OCS or on a dedicated worker.
In case of dedicated worker it will create new machineset for that.
This PR is replacing   #1520 
=> VDBench: adding new node for app pod

conf/deployment/vsphere/upi_1az_rhcos_3m_3w_prod_memory.yaml, conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w.yaml, conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml, conf/deployment/vsphere/upi_1az_rhel_3m_3w_prod_memory.yaml, conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml, conf/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml, conf/ocsci/vsphere-upi-ocs4qe-lab.yaml, conf/ocsci/vsphere_upi.yaml, ocs_ci/framework/conf/default_config.yaml, tests/conftest.py, tests/manage/monitoring/conftest.py, tests/manage/monitoring/test_workload_fixture.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/1551
This pull request:
With this PR, a workload fixture run will report into log messages like this:
```
2020-02-28 14:43:32,737 - INFO - tests.manage.monitoring.conftest.workload_fio_storageutilization.669 - Assuming 30.00 MB/s is a minimal write speed of fio.
2020-02-28 14:43:32,738 - INFO - tests.manage.monitoring.conftest.workload_fio_storageutilization.674 - fixture will wait 136.53333333333333 seconds for the Job to write 4 Gi data on OCS backed volume
```
One more line (`Job fio failed to write ...`) is reported in the log when the fio job workload fails on the timeout:
```
16:17:08 - MainThread - ocs_ci.ocs.ocp - INFO - status of  at column STATUS - item(s) were ['Running'], but we were waiting for all 1 of them to be …
```
=> Add fio_storageutilization_min_mbps option

ocs_ci/ocs/resources/pod.py
check_file_existence intermittently fails as described in #1609 . 
The failure is not because of the absence of file. So adding retry to reduce the possibility of test failure.
Retry can be removed after fixing #1609 
=> Adding retry for check_file_existence

ocs_ci/deployment/deployment.py, tests/conftest.py
Move WA for RHEL BZ to deployment
With old WA it didn't collected must gather in case of failure.
This will be the better place where to move WA.
Also added retry to make this more stable.
Fixes: #1608
=> Move workaround for RHEL nodes to different place to enable must-gather

ocs_ci/utility/tests/test_utils.py, ocs_ci/utility/utils.py
This change improves logging in `run_cmd()` utility function so that all aspects of a cmd run (stdout, stderr and retcode) are always logged with at least DEBUG level, so that one can read test DEBUG logs to immediately understand what happened without knowledge of run_cmd internals.
In a positive use case like `run_cmd("echo -n hello")` a test log would contain:
```
19:01:25 - MainThread - ocs_ci.utility.utils - INFO - Executing command: echo -n hello
19:01:25 - MainThread - ocs_ci.utility.utils - DEBUG - Command stdout: hello    
19:01:25 - MainThread - ocs_ci.utility.utils - DEBUG - Command stderr is empty  
19:01:25 - MainThread - ocs_ci.utility.utils - DEBUG - Command return code: 0
```
In a negative use case like `run_cmd("ls /tmp/this/file/isindeednotthereatal")`, log would …
=> improving logging in run_cmd()

ocs_ci/ocs/node.py, ocs_ci/ocs/resources/pod.py
Helper functions for DC based app pods which will require during node failure cases.
*. get_osd_running_nodes
*. get_app_pod_running_nodes
*. get_both_osd_and_app_pod_running_node
*. wait_for_dc_app_pods_to_reach_running_state
=> DC based app pods - Node failure helper functions

ocs_ci/ocs/resources/mcg.py, tests/helpers.py, tests/manage/mcg/helpers.py, tests/manage/mcg/test_multipart_upload.py
This test case covers Multipart Upload which allows the user to upload a single object as a set of parts. After all parts of your object are uploaded, S3 then presents the data as a single object. With this feature you can create parallel uploads.
=> Test case to validate Multipart Upload on buckets

tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
In OCS4.3, post machine delete 'rook-ceph-crashcollector' on the failed node stucks at pending state. BZ 1810014 tracks it.
Instead of skipping the entire test case with this BZ,  as a WA ignoring 'rook-ceph-crashcollector' pod health check so that the functionality will be tested.
=> Fix test_automated_recovery_from_failed_nodes_proactive_IPI test failure by adding WA

ocs_ci/ocs/resources/pod.py
16k is very very slow. 1m is much more sensible default.
Signed-off-by: Yaniv Kaul <ykaul@redhat.com>
=> fio: use a more reasonable IO rate of 1m instead of 16k

setup.py
=> Set pytest to version 5.3.5 because 5.4.0 is breaking unit tests

tests/manage/pv_services/test_pvc_disruptive.py, tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py, tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py, tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Skip tests due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1815078
=> Add bugzilla marker to tests which delete rook-ceph-operator

.pre-commit-config.yaml
=> Allow pre-commit check-yaml to allow multi-document yaml files

tests/conftest.py, tests/manage/pv_services/test_pvc_disruptive.py
This PR fixes #1693 . 
Added timeout of 90sec to test_pvc_disruptive 
test Runs - ocs-ci results for OCS4-3-Downstream-OCP4-3-VSPHERE-UPI-1AZ-RHEL-VMFS-3M-3W-tier4a (BUILD ID: v4.3.0-377.ci RUN ID: 1584631617)
ocs-ci results for OCS4-3-Downstream--AWS-IPI-3AZ-RHCOS-3M-3W-tier4a (BUILD ID: v4.3.0-377.ci RUN ID: 1584613734
=> Fixes Issue 1693: Add timeout of 90 sec for disruptive PVC creation tests

tests/manage/monitoring/conftest.py
Increase timeout for monitor to come back by 2 minutes. This is done to reduce the flakiness for the test.
=> Increase timeout for monitor to come back

conf/upgrade/upgrade_in_current_source.yaml, tests/ecosystem/upgrade/test_upgrade.py
Fixes: #1718
Also with this change it should allow us now to test upgrade on existing
source like live to live content or stage to stage with only change of
channel in the subscription.
=> Fix upgrade test to apply changes in subscription

ocs_ci/ocs/constants.py, tests/manage/z_cluster/test_must_gather.py
Verifies:
Bug [1776723](https://bugzilla.redhat.com/show_bug.cgi?id=1776723) - must_gather_command folder does not have any ceph command output files
Bug [1757863](https://bugzilla.redhat.com/show_bug.cgi?id=1757863) - most must_gather_commands files with output of ceph commands are empty
=> Test to verify must_gather_commands

ocs_ci/ocs/ocp.py, tests/ecosystem/upgrade/test_upgrade_ocp.py
fixed function: confirm_cluster_operator_version:
improved logging, added cluster as new argument, now it checks for each cluster operator if upgrade completed correctly
=> fix test: test_upgrade_ocp

ocs_ci/deployment/deployment.py, ocs_ci/ocs/registry.py
In order to fix stage deployment on OCP 4.3 we need to move change of
registry to managed state after the deployment of OCP.
Fixes: #1706
=> Set registry to managed state after OCP deployment

tests/manage/mcg/test_multi_region.py
The `multiregion_mirror_setup` code was changed to return an object instead of a name. Updating the test code to comply with the change.
=> Fix MCG multi-region test

tests/manage/mcg/test_object_integrity.py, tests/manage/mcg/test_write_to_bucket.py
...and take too long to run
A temporary workaround for #1659
=> Temporarily skip tests that utilize datasets that are too big 

tests/manage/z_cluster/test_must_gather.py
fixed list Comprehension to remove must-gather-*****-helper from list of log directories before compare to list of pods
Fix  #1687
=> Fix  #1687

ocs_ci/ocs/resources/pod.py, tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py, tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py, tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py, tests/manage/pv_services/test_pvc_disruptive.py, tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py, tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Adding more logs in tests for easier analysis. 
tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py
tests/manage/pv_services/test_pvc_disruptive.py
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
=> Improve logging in tests

ocs_ci/cleanup/aws/cleanup.py, ocs_ci/cleanup/aws/defaults.py, ocs_ci/deployment/aws.py, ocs_ci/deployment/ocp.py, ocs_ci/utility/aws.py, ocs_ci/utility/utils.py
aws-cleanup, ci-cleanup: Allow deleting UPI clusters, which are cloudformation based.
- Moved destroy cluster functionality to ocs_ci/utility/utils.py to be called from ocs_ci/deployment/ocp.py and ocs_ci/cleanup/aws/cleanup.py
- Moved AWS UPI related functions from ocs_ci/deployment/aws.py to ocs_ci/utility/aws.py
- Allow ci-cleanup to get --upi arg
- Allow aws-cleanup to send also cloudformation based clusters to ci-cleanup so UPI clusters will be deleted
=> Fixes: #1716 aws-cleanup, ci-cleanup: Allow deletion of UPI clusters

tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
In multiple  tier4b runs, Test case [1] failed as one PVC took more than 60 sec to get BOUND. Increasing time out to resolve this.
[1] tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py::TestDaemonKillDuringResourceCreation::test_ceph_daemon_kill_during_resource_creation[CephFileSystem-create_pvc-mgr]
=> Increase wait time for pvc to Bound

ocs_ci/ocs/ocp.py, tests/ecosystem/upgrade/test_upgrade_ocp.py
This PR checks for each ClusterOperator if its status is "degraded" or "progressing", to avoid rare cases when cluster operator version has been updated but update not yet completed
added function: verify_cluster_operator_status, added this validation as another testing stage
=> add another ocp upgrade validation - check cluter operator status

tests/conftest.py
Current teardown of cluster is doing health check after
cluster is removed. Skip the health check for teardown
of cluster
Fixes: #1826
=> Fix in teardown cluster.

tests/conftest.py
When we use skip_ocs_deployment, teardown is checking for
health_check of OCS cluster. In this PR, we are skipping health_check
for skip_ocs_deployment.
Fixes: #1830
=> Fixing skip_ocs_deployment teardown

tests/e2e/scale/test_pvc_creation_deletion_scale.py, tests/helpers.py
tests/e2e/scale/test_pvc_creation_deletion_scale.py
- Script enhanced to copy creation and deletion csv files to ocs-ci log location
- Script enhanced to parallel execution of code to collect pv and pvc names
- Added waittime of 60 sec to measure_pv_creation_time_bulk
- Added waittime of 60 sec to measure_pv_deletion_time_bulk
=> Fix scale issues observed during jenkins run

tests/conftest.py, tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
ocs-ci/tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
The test is using custom cephblockpool which is created by storageclass_factory.
Modified to use default cephblockpool.
Changed this in storageclass_factory_fixture because creating new cephblockpool
is not a requirement.
=> Update test to use default cephblockpool

ocs_ci/ocs/pillowfight.py
This does not always happen when the project is deleted.
=> Make sure couchbase-operator namespace is deleted. (#1774)

tests/manage/mcg/test_bucket_deletion.py
The test takes around 8 hours to execute because of the time it takes to retrieve and write all the objects to the NooBucket.
It should still be run outside of tiered runs in order to verify we don't experience a regression.
=> Remove the 1TB object deletion test from Tier3 because of a long execution time

ocs_ci/utility/prometheus.py, ocs_ci/utility/tests/test_prometheus.py, tests/manage/monitoring/conftest.py, tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
Test case `test_monitoring_shows_mon_down` now checks only exp. mon downtime, which is provided via `measure_stop_ceph_mon` fixture.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/1709
=> Fix of issue 1709: test OCS-1306 checks only exp. mon downtime

tests/manage/monitoring/conftest.py
Log ceph `mon_osd_*_ratio` values during run of workload storage
utilization fixtures.
fixes https://github.com/red-hat-storage/ocs-ci/issues/1809
=> log ceph mon_osd_*_ratio ratio values

tests/manage/pv_services/test_pvc_assign_pod_node.py
OCS-1257 - RBD: Assign nodeName to a POD using RWX PVC
=> Testcase - RBD: Assign nodeName to a POD using RWX PVC

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Updated test_add_capacity to verify osd-prepare pod status is 'Completed'
after adding capacity.
Verifies bug [1769061](https://bugzilla.redhat.com/show_bug.cgi?id=1769061)
=> Verify status of osd-prepare pods after adding capacity

ocs_ci/utility/utils.py
Up until today, `run_cmd` didn't return anything but a command's resulting `stdout`.
However, after discussion in the team chat, it was agreed that it'd be more beneficial to return the entirety of the `CompletedProcess` object, for the developers to dissect and use as they wish afterwards.
Thus, `exec_cmd` was created as a replacement that returns the entire object. Backwards compatibility is achieved by calling the new function inside `run_cmd` and then extracting the `stdout` and returning it.
I tried to use `warnings` in order to deprecate the old function, but this resulted in a lot of messages filling up the log, and I'm not sure whether it's a good idea to filter all deprecation warnings. I tried filtering by module, but it didn't seem to have effect.
So far I tested the change on …
=> Replace run_cmd with exec_cmd

ocs_ci/templates/workloads/pgsql/server/StatefulSet.yaml
StatefulSet API version needs to update to run with 4.4 images. 
Fixing pgsql failing https://github.com/red-hat-storage/ocs-ci/issues/1885
=> Update StatefulSet api version.

ocs_ci/ocs/constants.py, ocs_ci/templates/workloads/vdbench/VDBench-Basic-FS.yaml, tests/e2e/performance/test_vdbench_workload.py
Making the calculation of the dataset automatically depending on storage size.
Adding test template file for CephFS.
Making the 'workloads' test that will run for both RBD and CephFS with 3
difference workloads :
- Light - 15% of storage capacity
- Medium - 35% of storage capacity
- Heavy - 70% of storage capacity
According issue  #1776
=> vdbench| Dynamicly calculate dataset

ocs_ci/ocs/resources/mcg_bucket.py
Added a TimeoutSampler because we simply wouldn't wait for buckets, although they sometimes take a while to become healthy
=> Improve verify_health to utilize TimeoutSampler and wait for bucket

tests/e2e/performance/test_vdbench_workload.py
Currently, vdbench test is marked with 'workloads' marker. 'performance' marker would be more appropriate.
=> updates vdbench test with performance marker

tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Updated Scale script to validate ceph status after ceph pod respin
Removed bugzilla markers in pytest params
Updated script to perform memory leak test.
=> Scale - Add ceph_health_check in ceph pod respin test

ocs_ci/ocs/ocp.py, tests/ecosystem/upgrade/test_upgrade_ocp.py
Added two more validations:
Before upgrade - checks if new subscription channel is same as current, and use `oc patch` command if not
After upgrade - checks status of `oc get clusterversion`
=> Improve ocp upgrade

tests/disruption_helpers.py
Enhancements:
1. Add retry for finding pid of daemon.
2. Increase wait time for checking new pid. 
=> Add retry for fetching daemon pid

tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
Removing tier4a marker because the test is executing since 1 day 7 hr and it's still running 
Fixes: #1972 
=> Remove tier4a marker from test_scale_osds_fill_75%_reboot_workers.py

ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/ocs/node.py, tests/helpers.py
Collect performance stats and saves them in file in json format.
Performance stats include:
- IOPs and throughput percentage of cluster
- CPU, memory consumption of each nodes
=> collect performance stats when OCS operation fails for scale and perfomance test cases

ocs_ci/utility/utils.py, tests/e2e/scale/test_pvc_creation_deletion_scale.py, tests/manage/storageclass/test_storageclass_invalid.py
Fixes: #1889
Make sure that open calls use file descriptors that can be closed.
=> Make sure that open calls use file descriptors that can be closed Fixes: #1889

ocs_ci/ocs/resources/pod.py, tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py, tests/helpers.py
Create max-size pvc, run IOs and validate pods are not OOMKILLED or restarted. 
Also validate Ceph health is OK and all pods are up and running.
(This verifies the BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1765550)
=> Validate pods are not OOMKILLED

tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Removing Bugzilla decorators for:
- https://bugzilla.redhat.com/show_bug.cgi?id=1818613 - Seems like reproduced when cluster is not in health OK. Now that other tests that were running prior to node drain tests, like add capacity, are stable, this BZ should not occur. 
- https://bugzilla.redhat.com/show_bug.cgi?id=1754287 - BZ verrified
=> Remove BZ decrators from node drain tests

ocs_ci/deployment/vmware.py, ocs_ci/utility/csr.py
Problem:
Current wait_for_all_nodes_csr functionality waits for all
the nodes to generate CSR but we are getting all the nodes using
get_all_nodes. During deployment we have seen some nodes are not shown up
in get_all_nodes and it misses the approving CSR fo rthat node.
Solution:
Add extra parameter "expected_node_num" to wait_for_all_nodes_csr function
so that it will wait till "expected_node_num" number of CSRs generated.
By default, it will get number form config.ENV_DATA
Fixes: #1941 
=> wait for CSRs based on number of nodes

ocs_ci/ocs/fiojob.py
This increases [number of files fio writes to](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-nrfiles) on the target volume from 1
to 8, so that fio doesn't hit max_file_size limit on cephfs volume as
long as the volume size is smaller than 8 TiB.
fixes https://github.com/red-hat-storage/ocs-ci/issues/1959
=> set nrfiles=8 in storage utilization fio config

conf/ocp_version/ocp-4.4-ga-config.yaml
The change have been made because the OCP have GAed 4.4.3 in fast channel and the stable one provides OCP 4.3.18.
Referencing the mail thread here http://post-office.corp.redhat.com/archives/aos-devel/2020-May/msg00071.html
=> Changing OCP channel from stable to fast to install OCP 4.4.3

conf/ocsci/io_in_bg.yaml, ocs_ci/framework/conf/default_config.yaml, tests/conftest.py
* Adjust tests.conftest.run_io_in_background to use factory pod fixture
* Create a config file to allow IO in background
=> Improve run_io_in_background fixture

tests/ecosystem/upgrade/test_noobaa.py, tests/manage/mcg/helpers.py, tests/manage/mcg/test_object_integrity.py, tests/manage/mcg/test_write_to_bucket.py
Up until today, we didn't actually use an anonymous S3 client for MCG testing - it (semi-secretly) relied on the local AWS credentials.
Fixed.
=> Fix creation of anonymous boto3 S3 resource

ocs_ci/ocs/constants.py, ocs_ci/utility/utils.py
- Take out the existing code from `get_ocs_olm_operator_tags` and put it in a dedicated function in order to allow other functions to use it
- Add a constant leading to the authentication config dogs
=> Improve auth config loading mechanism

ocs_ci/utility/localstorage.py
Since there was a requirement to fetch device paths from the worker nodes irrespective of the platform (Aws/Bare Meral etc.)
Added a helper function that does the same.
Signed-off-by: Anubhav Deep <adeep@redhat.com>
=> Added function to fetch all device paths irrespective of platform

ocs_ci/ocs/cluster.py, ocs_ci/ocs/node.py, ocs_ci/ocs/ocp.py, ocs_ci/templates/workloads/smallfile/SmallFile.yaml, requirements.txt, tests/e2e/performance/test_small_file_workload.py
Results push via ripsaw (snafu) and also with some more information
directly by this test.
Also, increas the number of the samples from 1 to 3.
Signed-off-by: Avi liani <alayani@redhat.com>
Also, it will retrieve the previous test results and compare to current result to see if there is a regression / progression or no change.
=> Push the smallfile test results into elasticsearch server.

tests/e2e/workloads/test_couchbase.py
Fixes #2017
Remove default serviceaccount creation (not needed, breaks on 4.4)
=> Fixes #2017

tests/conftest.py
This change is done because official distribution of `fio` in Fedora is not build with `http` ioengine (there are missing prerequisites in fio specfile) and in future tests I would like to use `fio` to utilize s3 interfaces.
=> Change fio container

ocs_ci/ocs/platform_nodes.py, ocs_ci/utility/utils.py
As of now we were randomly chosing cloudformation stack to extract zone info for worker, with this PR we will be iterating  over all available zones and each worker will get a different stack hence different zone. 
Applicable for both RHEL and RHCOS workers.
fixes: https://github.com/red-hat-storage/ocs-ci/issues/2036
=> Make sure we use all available zones for workers

docs/usage.md, ocs_ci/cleanup/aws/cleanup.py, ocs_ci/ocs/cluster.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/platform_nodes.py, ocs_ci/ocs/resources/ocs.py, ocs_ci/pause/pause.py, setup.py, tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py, tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Add option to stop cluster nodes when not in use, this can reduce the overall AWS cost and speed up cluster bring up.
=> Add option to stop cluster nodes when not in use

ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/bucket_policy.py, ocs_ci/ocs/resources/mcg.py, tests/conftest.py, tests/ecosystem/upgrade/test_noobaa.py, tests/helpers.py, tests/manage/mcg/helpers.py, tests/manage/mcg/test_bucket_creation.py, tests/manage/mcg/test_bucket_deletion.py, tests/manage/mcg/test_bucket_policy.py, tests/manage/mcg/test_multi_region.py, tests/manage/mcg/test_multipart_upload.py, tests/manage/mcg/test_object_integrity.py, tests/manage/mcg/test_write_to_bucket.py
Up until now we used `verify=False` and `--no-verify` with markers that would suppress `InsecureRequestWarning` warnings. In this PR I retrieve the self-signed certificate in order to use it for verified communication with NooBaa in all of the APIs.
Warning suppressions removed, code optimized in some places.
=> Use proper certificates for AWS, S3 and RPC requests

ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/mcg.py, tests/conftest.py
Instead of running the commands directly via the operator pod (which requires the NooBaa serviceaccount to have a `cluster-admin` role), we now copy the binary to the local ...ocs-ci/data/ folder, and run everything from there.
=> Run MCG CLI locally instead via operator pod

tests/manage/monitoring/conftest.py, tests/manage/monitoring/prometheus/test_noobaa.py
The test is currently flaky. This change should improve the stability of the test.
=> Add 3 minutes to wait for bucket quota alert

tests/conftest.py, tests/helpers.py, tests/manage/mcg/helpers.py
The workaround was needed after we changed the AWSCLI pod's image *and* started verifying ther MCG certificates. We tested each change separately, but not together - and thus they were merged.
Also fix the signature of `craft_s3_command` that wasn't updated properly in a #2080
=> Work around copying the MCG cert to the AWSCLI pod

tests/manage/z_cluster/test_remove_mon_from_cluster.py
This test case should be disabled, as it was marked as inactive in Polarion (OCS-355) and also, this scenario should not be supported.
Thanks @sidhant-agrawal for raising this 
=> Skip TestRemoveMonFromCluster

tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Temporarily skip some tests in tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py which are making OCS node(s) unresponsive.
A temporary workaround for #2101 
=> Temporarily skip some tests in tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py due to #2101

docs/usage.md, ocs_ci/framework/conf/default_config.yaml, ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/ocs/cluster.py, ocs_ci/ocs/cluster_load.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/pod.py, ocs_ci/utility/utils.py, tests/conftest.py
Reach the target throughput load percentage, and keep it running throughout the test suite execution. 
The number of pods needed for the desired target percentage is determined by creating pods one by one, while examining if the cluster throughput is increased by more than 10%. When it doesn't increased by more than 10% anymore after the new pod started running IO, it means that the cluster throughput limit is reached. Then, the function deletes the pods that are not needed as they are the difference between the limit (100%) and the target percentage (the default target percentage is 30%). This leaves the number of pods needed running IO for cluster throughput to be around the desired percentage.
To be used by https://github.com/red-hat-storage/ocs-ci/blob/5cee08d83ea59d0acae5255c04ef9d519 …
=>  Functionality to determine the cluster throughput limit and run IO at a given percentage of it

ocs_ci/ocs/ripsaw.py
ripsaw's crd directory name has been changed from `resources/crd/` to `resources/crds`. This will break all our tests using ripsaw - https://github.com/cloud-bulldozer/ripsaw/tree/master/resources/crds
=> Fixes the change in ripsaw's crd directory name

tests/e2e/workloads/test_couchbase.py
Fixes #2109
Use oc link for serviceaccount/couchbase setting
=> Fixes #2108

tests/manage/monitoring/prometheus/test_capacity.py
This is done for reporting purpose. It is easier to analyse the results because execution of workload fixtures is done separately.
fixes https://github.com/red-hat-storage/ocs-ci/issues/1967
=> Split capacity tests

ocs_ci/ocs/resources/ocs.py, ocs_ci/ocs/resources/pod.py
Fixes: #2147
Previous NamedTemporaryFile calls saved the entrire file
object and did not release the file descriptor.  Now the
calls only save the name of the file (the only data the
code used from the file object).  The NamedTemporaryFile
call is made within a with clause to insure that the
file descriptor is released.
=> Fix issue 2147

ocs_ci/ocs/resources/storage_cluster.py, tests/ecosystem/upgrade/test_noobaa.py, tests/ecosystem/upgrade/test_upgrade.py, tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Refactored the test to not use `wget` since it's not available on the official AWSCLI Docker image, and thus, on the AWSCLI relay pod.
Also optimized code where possible and replaced an outdated `phase` call with a `status` one
Should be merged after #2176
Fixes #2052, fixes #2179, fixes #2175
=> Fix MCG upgrade tests

tests/manage/monitoring/conftest.py
This change is done because utilization tests that should utilize cluster for a small percentage can become flaky because of utilization that is already run.
=> change method of workload_storageutilization_checksum_rbd to use static size

ocs_ci/ocs/fiojob.py, tests/manage/monitoring/test_workload_fixture.py
Change OCS-2125 test case to utilize 10G instead of 5% target of total capacity. Polarion test case was updated along with this pull request.
This also removes one special case hack from code of fiojob.workload_fio_storageutilization() function, which is no longer necessary
fixes https://github.com/red-hat-storage/ocs-ci/issues/2038
=> change OCS-2125 to use fixed storage size

ocs_ci/ocs/constants.py, ocs_ci/ocs/platform_nodes.py, ocs_ci/utility/aws.py, ocs_ci/utility/vsphere.py, tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py, tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py, tests/manage/z_cluster/nodes/test_nodes_maintenance.py, tests/manage/z_cluster/nodes/test_nodes_restart.py
Fixes #2103
Created two different functions for nodes restart.
1) restart_nodes - which directly calls restart
2) restart_nodes_by_stop_and_start - which does restart by stopping and starting the instances/Vms
=> Changed restart_nodes() implementation to directly call reboot

ocs_ci/ocs/platform_nodes.py
Currently it will fail to get indexes for cluster with
name "jnk-au3c33-t1-no2". We need to split and always get the
last element ( no2 ).
=> Fixing in getting indexes

tests/manage/monitoring/test_workload_with_distruptions.py
The test should be in tier2 because it's a more complicated scenario and it shouldn't be among basic checks. Also keeping it in tier1 affects CI runs negatively.
=> move checksum workload_with_checksum test to tier2

ocs_ci/utility/deployment_openshift_logging.py, tests/conftest.py, tests/e2e/logging/test_openshift-logging.py
Enhancements are listed below
1. If logging already exists in the cluster, skip configuring
2. Modified the code to also support colocated Masters and workers to wait for fluentd pods
3. Skip logging configuration on AWS-i3
4. Reduced the number of retries and delays 
Fixes: #2198 
=> Enhancements for openshift-logging

ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/bucket_policy.py, ocs_ci/ocs/resources/mcg.py, tests/conftest.py, tests/helpers.py, tests/manage/mcg/test_bucket_creation.py
<Title> 
Also added better handling of CLI binary and `service-ca.crt` copying.
=> Refactor tests to work on OCS 4.5, work around missing `service-ca.crt`

ocs_ci/deployment/vmware.py, ocs_ci/utility/vsphere.py
Erasing partition on RDM disk before adding to node.
Erase partition during teardown will be handled separately in another PR since the
logic is different for teardown.
=> Erase partition on RDM disk before adding to node

tests/conftest.py, tests/ecosystem/upgrade/conftest.py
fixes https://github.com/red-hat-storage/ocs-ci/issues/2039
While this is a better default for most normal jobs, negative or upgrade use cases may prefer to still use nonzero backoffLimit. And it obviously needs testing.
=> set fiojob backoffLimit to 0

tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py
Updated fio runtime less than 2min of get_fio_result() timeout value.
Did multiple testing to identify the problem, below is analysis and expected fix.
1. fio pod is not getting OOM kill during IO, it's up and running even if there is a timeout error while calling the function get_fio_result()
2. Did run the same fio profile manually using set_trace in pod, IO completed without any issue.
3. The problem I see here is the fio runtime and get_fio_result() function FIO_TIMEOUT value. i.e. both are 600sec wrt this TC. So due to that, run_io starts the IO but get_fio_result() exactly waits for the same TIMEOUT secs and it reports failure.
The script works perfectly if fio_runtime is less than 540sec, so changed it to 480sec.
=> PR to fix get_fio_result() issue in test_pods_are_not_oomkilled_while_running_ios TC

docs/usage.md, ocs_ci/framework/conf/default_config.yaml, ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/framework/testlib.py, ocs_ci/ocs/cluster.py, ocs_ci/ocs/cluster_load.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/defaults.py, ocs_ci/ocs/resources/pod.py, ocs_ci/templates/workloads/fio/fio_dc.yaml, ocs_ci/utility/environment_check.py, ocs_ci/utility/utils.py, setup.py, tests/conftest.py, tests/e2e/logging/test_openshift-logging.py, tests/fixtures.py, tests/helpers.py
A follow-up on https://github.com/red-hat-storage/ocs-ci/pull/2037 - improvements and fixes for cluster load functionality:
- Detect cluster limit by an exponential increase of the latency
- Instead of background thread to watch the IO load, use DeploymentConfig pods of FIO, which will spin up automatically in case they are stopped during the execution 
- Track cluster latency in the background. Actively adjust the background load in case the latency increases
- Added a few backup mechanisms to determine the cluster limit, in case the latency does not grow exponentially 
- Change the default load from 30% to 50%
- Use Prometheus queries to get the different metrics
- Improve logging
- Change PVC size to be 50% of the sum of the OSD memory pods memory, for all created PVCs
- Examine IOPS …
=> Cluster load: Determine cluster limit by latency growth + use DC pods

ocs_ci/ocs/constants.py, tests/manage/z_cluster/nodes/test_disk_failures.py
- Fixes #2211 
-  Improvement in cleanup to handle node restart if the osd stays at CLBO state
=> Fix TC test_detach_attach_2_data_volumes failures

ocs_ci/ocs/machine.py
=> Throw exception in wait_for_new_node_to_be_ready() when the newly added node failed to reach Ready state

tests/manage/z_cluster/nodes/test_nodes_maintenance.py
test_simultaneous_drain_of_two_ocs_nodes is not having decorator ipi_deployment_required.
So, this test is being picked for execution in AWS-UPI and failing.
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/8188/testReport/junit/tests.manage.z_cluster.nodes.test_nodes_maintenance/TestNodesMaintenance/test_simultaneous_drain_of_two_ocs_nodes_cephfs_/
=> Added decorator ipi_deployment_required to test test_simultaneous_drain_of_two_ocs_nodes

setup.py
google-auth is compatable with latest rsa version
=> Removing the workaround for RSA version since google-auth is compatable with latest rsa version

ocs_ci/ocs/resources/pod.py
Update pod.run_io_in_bg.
Add wait time to start I/O on pod and collect file list if I/O failed to start.
Closes #2160 
=> Add wait time to start I/O on pod and collect file list

ocs_ci/deployment/vmware.py
Disable the bootstrap removal code due to vSphere provider issue
Issue: https://github.com/hashicorp/terraform-provider-vsphere/issues/1111
Choosing to disable the code part instead of passing yaml in MR due to if someone choose to install directly from repo they might hit the issue.
Fixes: #2336 
=> Disable the bootstrap removal code due to vSphere provider issue

ocs_ci/ocs/ocs_upgrade.py, tests/ecosystem/upgrade/test_upgrade.py
This PR is preparation for ocs upgrade tier4a tests 
1. split upgrade into helper file and test file
2. create OCS upgrade class with methods
=> Convert OCS Upgrade to OOP

ocs_ci/ocs/amq.py, ocs_ci/ocs/constants.py, ocs_ci/templates/workloads/amq/amq_workload.yaml, ocs_ci/templates/workloads/amq/benchmark/Chart.yaml, ocs_ci/templates/workloads/amq/benchmark/templates/_helpers.tpl, ocs_ci/templates/workloads/amq/benchmark/templates/benchmark-worker.yaml, ocs_ci/templates/workloads/amq/benchmark/templates/benchmark.yaml, ocs_ci/templates/workloads/amq/benchmark/values.yaml, ocs_ci/templates/workloads/amq/driver-kafka.yaml, ocs_ci/templates/workloads/amq/rbac.yaml, tests/e2e/workloads/amq/test_amq_streamer_creation.py
Creates amq benchmark pods and get the test results. And also supports creation of multiple topics, partitions, producer, consumer pods.
=> Run amq benchmark pod and get test results

tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
added post_ocp_upgrade marker to monitoring tests, as partial fix of https://github.com/red-hat-storage/ocs-ci/issues/2131
=> added post_ocp_upgrade marker into 2 tier1 tests

ocs_ci/ocs/exceptions.py, ocs_ci/ocs/resources/mcg.py
Meant to remedy a case in which `run-ci` is ran on `non-AWS` clusters, with `AWS` as the platform under `ENV_VARS`. Made the error clearer and more concise.
=> Warn about misconfiguration with MCG

tests/e2e/performance/test_small_file_workload.py
This PR is replacing PR #2249
Re-factoring the test to use internal elasticsearch server to used by the ripsaw
and copy all data from the internal ES to the Main ES.
that will deploy elasticsearch as part of the test.
in the end of the test, setting it back
=> smallfile | Integrate Internal ElasticSearch

ocs_ci/deployment/terraform.py, ocs_ci/deployment/vmware.py, ocs_ci/ocs/constants.py, ocs_ci/templates/ocp-deployment/terraform_4_5.tfvars.j2, ocs_ci/utility/connection.py, ocs_ci/utility/load_balancer.py, ocs_ci/utility/templating.py, ocs_ci/utility/utils.py
This PR will align ocs-ci with OCP4.5 folder structure
Below are few important commits
a5b320107824529551cf2e678c4d99c1c0c9cf7c : re-org the structure to accomodate the ocp45 ( folder structure )
cfc4a7c97c086a5e06eade0d6faebf8f1ee21646 : Adding new jinja template for ocp45 ( folder structure )
363e06b8489d195c185da0c49dcb2cf6a68aa673 : Adding connection and load balancer modules
54dd538377912797838864d37d70eaa8b284d48c : Including OCP45 folder structure and other helper functions
64b4adfc8a7c11e354c0da01b8f6646eb2a4bfaf : Sync guest time with host
ec181acf2a9541234dd54a3c9bde8cd1f0c95196 : Removing bootstrap node
cdf663c5c5fbd09c87ab20e1200f78a5509070da : Destroy functionality to support folder structure
7ca3f340dc7abf843ac137db3cd2da049e331a40 : Include retry mechanism for …
=> Align ocs-ci with OCP 4.5 ( folder structure ) for vsphere platform

ocs_ci/ocs/amq.py, ocs_ci/ocs/constants.py, ocs_ci/templates/workloads/amq/amq_simple_workload.yaml, tests/conftest.py, tests/e2e/workloads/amq/test_amq_pod_respin.py
- Created fixture for running amq workload
- AMQ workload test cases : spinning ceph pods and restarting amq pods
=> AMQ fixture and testcase amq workload when spinning ceph pods

ocs_ci/ocs/platform_nodes.py, ocs_ci/utility/azure_utils.py, tests/manage/z_cluster/nodes/test_disk_failures.py
**Description:**
This PR provides the modification for the below tests in tests/manage/z_cluster/nodes/test_disk_failures.py to run on Azure platform
- test_detach_attach_worker_volume 
- test_detach_attach_2_data_volumes 
=> Changes for test disk failures to support on Azure platform

ocs_ci/utility/tests/test_utils.py
=> Fix return code mismatch for unit tests running on OSX

tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
Increased fio setup wait time in test case test_pvc_expand_expanded_pvc 
Closes #2499 
=> Increase wait time for fio setup in test case

tests/manage/pv_services/conftest.py, tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Test cases to verify PVC expansion will succeed when rook-ceph, csi pods are re-spun during expansion
OCS-2224 - FT-PvcExpand-Delete MGR pod while expanding PVC
OCS-2225 - FT-PvcExpand-Delete OSD pod while expanding PVC
OCS-2226 - FT-PvcExpand-Delete rbdplugin pod while expanding PVC
OCS-2227 - FT-PvcExpand-Delete cephfsplugin pod while expanding PVC
OCS-2228 - FT-PvcExpand-Delete rbdplugin-provisioner leader pod while expanding PVC
OCS-2229 - FT-PvcExpand-Delete cephfsplugin-provisioner leader pod while expanding PVC
=> Test case:Verify PVC expansion during rook-ceph, csi pod re-spin

ocs_ci/framework/pytest_customization/ocscilib.py
=> Use metadata.json to set cluster_name in config if one is not provided

ocs_ci/ocs/disruptive_operations.py, ocs_ci/ocs/ocs_upgrade.py, ocs_ci/ocs/resources/pod.py, tests/ecosystem/upgrade/test_upgrade.py
- moved test_ocs_upgrade code to helper file
- added dictionary with tier4 tests and arguments
- create class for tier4 tests with worker_node_shutdown function
- added 2 test function: worker node shutdown - abrupt and permanent
- some minor fixes
=> Tier4a ocs upgrade

ocs_ci/ocs/constants.py, tests/helpers.py
If cluster wide proxy is configured (in Proxy configuration object), use it's values for `http_proxy` and `https_proxy` values in tests. This should enable test execution on proxy environment without special manual configuration.
=> consider cluster wide proxy configuration in tests

setup.py
The previous workaround to dataclasses' requirement on python < 3.6 pins
to the version before the requirement was added; while pinning is of
course a good idea, I wanted to offer a way to pin to the latest version
while preventing the module from being installed at all on python 3.7+,
where the functionality is part of the standard library.
=> Refine dataclasses dependency

ocs_ci/framework/pytest_customization/marks.py, tests/manage/rgw/conftest.py
Currently, the tests run on all platforms, including cloud ones that don't have RGW deployed at all.
Added the marker for future uses - it isn't being used in this PR.
=> Skip RGW tests on non-on-prem platforms

tests/manage/pv_services/pvc_resize/test_pvc_expansion_when_full.py
Test case to verify PVC expansion when the PVC is 100% utilized.
Verify utilization alert will stop firing after volume expansion.
OCS-301 - FT-OCP-PVCExpand- PVC expand when 100% full
=> Test case: Expand PVC when full

ocs_ci/framework/__init__.py, ocs_ci/framework/conf/default_config.yaml
Allow empty section in default config.
Without this change, empty section in `default_config.yaml` cause unit test `TestConfig.test_defaults` fails this way:
```
self = <ocs_ci.framework.tests.test_config.TestConfig object at 0x7f14a9c35b80>
def test_defaults(self):
config_sections = framework.config.to_dict().keys()
for section_name in config_sections:
section = getattr(framework.config, section_name)
>           assert section == framework.config.get_defaults()[section_name]
E           assert {} == None
ocs_ci/framework/tests/test_config.py:16: AssertionError
```
because empty section returns `None` instead of `{}`.
=> properly handle empty section in default config

ocs_ci/ocs/couchbase.py, ocs_ci/ocs/pillowfight.py, ocs_ci/templates/workloads/couchbase/server/pillowfight/basic-pillowfight.yaml
With increasing the number of items to be loaded and the number of threads, IOs will be running for a longer time(like 7-8 minutes each pod) which was very short previously
=> Couchbase:  workload running for longer time

Jenkinsfile, conf/ocs_version/ocs-4.5.yaml, conf/ocs_version/ocs-4.6.yaml, ocs_ci/ocs/constants.py, ocs_ci/utility/utils.py
OCS versions from 4.5 onward should use the ocs-bundle-operator instead of ocs-olm-operator. If the tests pass, make sure to tag ocs-bundle-operator as ``latest-stable-4.*`` instead of ocs-olm-operator for those versions. Also, the old ocs-registry image won't be tagged anymore at all.
=> downstream-ci: change stable tagging for versions that use bundles

ocs_ci/framework/conf/default_config.yaml, tests/conftest.py
Fixes: #2670 
Remove cloning of rook repo since we are not using this repo
keep the code intact incase if we need for future use
=> Remove cloning of rook repo since we are not using this repo

tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
OCS-2235 - FT-PvcExpand-Worker node restart during PVC expansion
Test case to verify PVC expansion will succeed if a worker node is restarted during expansion
=> Test case to verify worker node restart will not hinder PVC expansion

ocs_ci/ocs/node.py, ocs_ci/templates/app-pods/fedora_dc.yaml, tests/conftest.py, tests/manage/z_cluster/nodes/test_worker_nodes_network_failures.py
- Fixes: #2274
- Add tests/manage/z_cluster/nodes/test_worker_nodes_network_failures.py
- Tests for all worker nodes simultaneous abrupt network failure for short duration of ~300 seconds (OCS-1432 and OCS-1433)
=> Add tests for all worker nodes simultaneous abrupt network failure for short duration

ocs_ci/framework/pytest_customization/marks.py, ocs_ci/ocs/resources/cloud_manager.py, ocs_ci/utility/aws.py, tests/ecosystem/upgrade/test_noobaa.py, tests/ecosystem/upgrade/test_resources.py
Right now the tests rely on loading the credentials from the local `auth.yaml`.
This PR also tries retrieving them from our private `ocs-ci-data` bucket, and if it fails - the tests that rely on those credentials will be skipped. (also added missing skip markers that were missing from a few tests)
=> Try loading MCG credentials from all possible sources

ocs_ci/ocs/resources/cloud_manager.py
Revert a change introduced in PR #2442 that caused an SSL failure (AWS communications would be verified with the internal service-ca certificate)
=> Verify AWS SSL with the default certificates

ocs_ci/framework/pytest_customization/marks.py
PR #2664 broke our build validation because we use environment variables to
provide AWS credentials.
=> skipif_aws_creds_are_missing: Check os.environ

tests/e2e/scale/test_pvc_creation_deletion_scale.py
Added pytest marker to skip test case
=> Skip PVC-Create-Deletion TC due to "Cannot allocate memory" Problem

tests/e2e/scale/test_ceph_pod_respin_in_scaled_cluster.py, tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py, tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
Updated tests which can't be executed in external mode with skipif_external_mode marker
=> Added skipif_external_mode for existing automated scale tests

ocs_ci/ocs/cluster.py
When it's a fresh cluster with more OSD's PGs per OSD difference will be high
updated the validation to get average value and check diff of +/- 10
Increase the eval value to 0.025
=> Enhance validate_pg_balancer function

tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
Add ceph health check in test teardown part of teat case:
ocs-ci/tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py::TestNodeRestartDuringPvcExpansion::test_worker_node_restart_during_pvc_expansion
=> Add ceph health check in test case teardown

ocs_ci/ocs/jenkins.py, ocs_ci/templates/workloads/jenkins/buildconfig.yaml, tests/e2e/workloads/jenkins/test_jenkins.py, tests/e2e/workloads/jenkins/test_jenkins_node_reboot.py
- Sort builds by build name number
- Increase number of builds per project
- Change buildconfig.yaml, save up to 30 builds
=> Increase number of builds per project

ocs_ci/framework/pytest_customization/ocscilib.py
We were seeing must-gather failures like this:
```
14:33:26 - MainThread - ocs_ci.framework.pytest_customization.ocscilib - ERROR - Failed to collect OCS logs. Error: list index out of range
```
Just not enough information to figure out what was going on. I went through the module and found all the instances of `log.error()` combined with an attempt to display something helpful about the exception, and modified them to use `log.exception()`, which gives you the entire traceback.
=> ocscilib: Log tracebacks instead of just exceptions

ocs_ci/utility/utils.py
I hit this case when I had an empty auth.yaml file. This fix will cause either a missing or empty file to print out the reminder to consult the docs.
=> utils: fix unhandled exception type when using bad auth.yaml contents

tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Modify the below test case to run on different platforms. Currently the test case is running only on AWS platform.
tests/manage/z_cluster/nodes/test_nodes_maintenance.py::TestNodesMaintenance::test_node_maintenance_restart_activate
Enabling the test case to run on BM is tracked here - https://github.com/red-hat-storage/ocs-ci/issues/2679
Closes #2286
=> Remove aws_platform_required marker from test_node_maintenance_restart_activate

ocs_ci/framework/pytest_customization/ocscilib.py
Partial Fixes (5): https://github.com/red-hat-storage/ocs-ci/issues/2704
We dont have redhat-operator-internal selector when installed via GUI so the get_csv call fails, we can safely ignore this error.
=> Fix hard failure when unable to get csv version for reporting

ocs_ci/ocs/constants.py, tests/manage/z_cluster/test_must_gather.py
change must_gather commands assertion not to fail if there is more actual commands than expected
with current solution, test will pass with warning if actual list of commands is greater than expected (but all expected commands exists)
fix issue:  #2560
=> Fix failure in test_must_gather 

tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
=> skip test_automated_recovery_from_failed_nodes_IPI_reactive shutdown tests with BZ 1845666

tests/conftest.py, tests/ecosystem/deployment/test_deployment.py
In this PR is dropped `autosuse` in `mcgcli_pod_fixture` and making the fixture a prerequisite for `mcg_obj` fixture.
@MeridianExplorer Does it make sense? `mcg_obj` fixture is used in almost all mcg tests. It seems that tests that don't use `mcg_obj` fixture wouldn't benefit from this.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/2821
=> make mcgcli_pod_fixture a prerequisite for mcg_obj fixture

tests/manage/rgw/test_multipart_upload.py
The test was not supposed to be part of our RGW testing, since it uses a Python S3 client, but we do not have access to the RGW cluster from the code executioner, which means this code cannot run successfully.
This will only be possible to use in a future case where RGW traffic is externalized with an endpoint and becomes accessible from outside the cluster.
Done because of #2832
=> Skip multipart upload test

ocs_ci/utility/deployment_openshift_logging.py
Logging by default gets configured with SC used in internal mode hence the installation fails on external mode.
This issue is seen on run https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/11623/
Hence enabling logging to work on both internal and external mode
=> Use Different SC in external mode for openshift-logging

tests/conftest.py, tests/helpers.py
- Update `tests/helpers.py` for getting CephBlockPool and CephFS name 
to work on External Mode.
- Update storageclass_factory_fixture in `tests/conftest.py` to use helper function for 
getting CephBlockPool name.
=> Update in tests/helpers.py and tests/conftest.py for getting CBP & CephFS name

ocs_ci/deployment/helpers/vsphere_helpers.py, ocs_ci/deployment/install_ocp_on_rhel.py, ocs_ci/deployment/vmware.py, ocs_ci/ocs/constants.py, ocs_ci/templates/ocp-deployment/cluster_info.yaml.j2, ocs_ci/templates/ocp-deployment/inventory_haproxy.yaml.j2, ocs_ci/templates/ocp-deployment/scale_up_config.yaml.j2, ocs_ci/templates/ocp-deployment/scale_up_terraform_with_folder_structure.tfvars.j2, ocs_ci/utility/utils.py
Fixes: #2544 
This PR contains following important commits
760bcd692d0f3ee2aa140adff44c62bb0f89d814 : Adding cluster_info and config jinja2 templates
10b2a887c21abdeecb0b319e49e0b112458a8dee : Adding inventory_proxy and scale_up_terraform_with_folder_structure jinja2
templates for RHEL - vSphere
477c68297339f41dc043fade97e2df7dae3e03b0 : Adding constants and utility functions for RHEL deployment for OCP 4.5-vsphere
c703e183febba999f7f4217a27727022072456b4 : Adding vsphere helper module and generate haproxy config for OCP 4.5
a14756faf4d16222100cf6ca9bcb730c2f2b4809 : Supporting RHEL installation for OCP 4.5 in vSphere platform
47c816653bc1d64cda81be6058053855ce44859b : Add destroy functionality for RHEL on OCP 4.5 and removed unused code
Signed-off-by: vavuthu vavuthu@redhat.com
=> Vsphere rhel installation for OCP 4.5

ocs_ci/utility/performance_dashboard.py
The current keys in the codespeed for the environment variables are in uppercase, this fixes the results that were not getting updated due to case sensitive match.
=> Fixed Vsphere and BareMetal naming in codespeed

ocs_ci/ocs/resources/cloud_manager.py
Sometimes, AWS takes longer than 3 minutes to actually clean up buckets.
It'd make no sense to arbitrarily wait for however long this may take, but we also shouldn't report a false failure in such a case.
Closes #2812
=> Log an error instead of raising an exception if ULS is found after deletion

ocs_ci/ocs/machine.py, ocs_ci/ocs/node.py, tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Few fixes to make test_node_replacement_proactive case work on any IPI platform.
Fixing https://github.com/red-hat-storage/ocs-ci/issues/2892
=> IPI fixes for test_node_replacement_proactive case

tests/conftest.py
Skip collecting items for skipif_ocs_version or skipif_upgraded_from in conftest.py for deployments and teardown
Fixes: #2897 
=> Skip collecting items for skipif_ocs_version or skipif_upgraded_from for deployments

ocs_ci/framework/conf/default_config.yaml
Jira: [OCSQE-445](https://projects.engineering.redhat.com/browse/OCSQE-445)
=> Move to OCS 4.6 as default version

Jenkinsfile
We're changing the container name so we need to also change
the tagging after the ocs-ci test run.
=> downstream ci: change ocs-bundle-operator to ocs-operator-bundle

ocs_ci/ocs/constants.py, ocs_ci/templates/authentication/htpasswd_provider.yaml, ocs_ci/utility/users.py, ocs_ci/utility/utils.py, tests/conftest.py, tests/libtest/test_user.py
Users created by the factory will be used for Prometheus API communication - this will help to run monitoring tests on IBM cloud and other platforms that doesn't generate kubeadmin-password file.
=> Add user_factory

docs/usage.md, ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/framework/pytest_customization/reports.py, ocs_ci/ocs/constants.py, ocs_ci/utility/utils.py
Controlled by `--squad-analysis` parameter.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/2920
=> Include squad analysis into email results report

tests/manage/storageclass/test_create_multiple_sc_with_different_pool_name.py
Fixes: #2867 
While creating 3 pools for this test, the number of PGs exceeded the limit for PGs (750) for a 3 OSD cluster and hence failed on a VMware cluster.Hence reducing the pool count to two.
More details in the issue.
=> Decrease the number of pools created to two 

conf/ocp_version/ocp-4.5-upgrade.yaml, tests/ecosystem/upgrade/test_upgrade_ocp.py
When running ocp upgrade with IO, sometime teardown failed due to unclean PGs. adding this check should avoid this situation
fix issue [2602](https://github.com/red-hat-storage/ocs-ci/issues/2602)
=> Add ceph health check at the end of the test

ocs_ci/deployment/vmware.py, ocs_ci/utility/utils.py
Fixes: #2941 
Download terraform ignition provider for destroy job.
usecase: OCP 4.5 to OCP 4.6 upgrade
=> Download terraform ignition provider for destroy job.

ocs_ci/ocs/resources/pvc.py, ocs_ci/templates/CSI/cephfs/pvc-restore.yaml, ocs_ci/templates/CSI/cephfs/snapshot.yaml, ocs_ci/templates/CSI/rbd/pvc-restore.yaml, ocs_ci/templates/CSI/rbd/snapshot.yaml, tests/conftest.py, tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Test to take multiple snapshots of same PVC when the PVC usage is at 0% 20% 40% 60% and 80%, delete the parent PVC and restore the snapshots to create new PVCs.
Test case: OCS-2318 - Snapshot at different PVC usage levels and verify parent PVC deletion when snapshots present
=> Test to verify snapshot when PVC usage is at different levels

.functional_ci_setup.py, ocs_ci/deployment/deployment.py, ocs_ci/framework/conf/default_config.yaml, ocs_ci/ocs/utils.py, tests/conftest.py
Allows to collect logs as well as if the OCS deployment succeeds.
That way we will have information about the cluster as well as if the deployment succeeded.
=> Collecting must gather after every status of deployment

ocs_ci/utility/utils.py
Make "yellow squad" title font black on yellow background for better readability:
=> Squad analysis: highlight yellow title

conf/ocsci/minimum_test_device_size.yaml
This is basically to use in DC-CP for test purpose( the total size provided by vSAN is bottleneck and using reduced disk size will allow us to create more clusters in DC-CP)
=> Add minimum size of '256' GB for test purpose (non production use)

tox.ini
fixes https://github.com/red-hat-storage/ocs-ci/issues/3037
Tested that tox run works on:
=> drop pip requires from tox.ini

docs/usage.md, ocs_ci/framework/conf/default_config.yaml, ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/ocs/utils.py
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/3001
We wanted to provide an option to gather logs on successful deployments, since we don't want to cause over waiting after successful deployments.
=> Optional parameter to gather logs when deployment runs successfully

tests/manage/mcg/test_namespace.py
Right now, all the namespace tests fail in case AWS credentials aren't provided.
Since all NS tests rely on AWS credentials, we should skip them in those cases.
=> Skip namespace tests in case AWS credentials are unavailable

ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/pod.py, ocs_ci/templates/workloads/fio/workload_io_fillup.yaml, tests/internal/test_fio_fillup.py
This PR add the functionality to fill up file on PVC.
It create a file on the PVC, and run 1MB Sequential IO up to the desire size (given as parameter)
this PR contain :
* template YAML file for the FIO parameters
* function that actually do the work
* simple test to test this function
=> Fio fill up functionality

.functional_ci_setup.py, ocs_ci/deployment/deployment.py, ocs_ci/framework/conf/default_config.yaml, ocs_ci/ocs/utils.py, tests/conftest.py
Fixes: #3047
Follow-up discussion for this PR: #3056
In [pull-3025](https://github.com/red-hat-storage/ocs-ci/pull/3025), we were able to accept new ocs-ci parameter `collect_logs_on_success_run`, but the actions of it did not cover all the possible cases.
Besides checking where  `collect_ocs_logs` is being called, I assigned if statement before the variable creation `log_dir_path`, so when we deployed without sending `--collect-ocs-logs`, we received `Local variable is called without any assignment`.
This is reverted, and then this merge calls the `collect_ocs_logs` with status_failure=False, **only** if `--collect-logs-on-success-run` is sent on run-ci
=> Preventing call of collect ocs logs when status_failure=False is sent

tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Unblock parent PVC deletion for cephfs PVC in the test case. Bug 1854501 is fixed
=> Unblock parent PVC deletion for cephfs PVC

ocs_ci/cleanup/aws/defaults.py
- prefix for production clusters will be changed from "jnk-" to "jXXX" where
XXX is last three digits from build number, so adding respective regex
to the defaults for aws cleanup script
=> add new prefix for production clusters to cleanup script

ocs_ci/framework/pytest_customization/marks.py, ocs_ci/utility/utils.py, tests/conftest.py
Since there are some features, like snapshot which cannot be run on all OCP versions, we need this functionality 
using it by adding the marker : @skipif_ocp_version(<expression>) 
for example : @skipif_ocp_version('<4.6') 
=> Adding marker for skip depend on OCP version

tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Increase snapshot restore wait time in test_snapshot_at_different_usage_level
Closes #3021 
=> Increase snapshot restore wait time in test

ocs_ci/ocs/scale_lib.py, tests/e2e/scale/test_pvc_creation_deletion_scale.py
With use of kube_job pvc creations were faster compared to old automated tests
Also memory usage of run-ci command is reduced below 1.5G
This also helped the test to complete the run within 30mins.
=> Enhance pvc creations scale using kube_job

tests/e2e/scale/test_ceph_pod_respin_in_scaled_cluster.py
This is partial fix for https://github.com/red-hat-storage/ocs-ci/issues/2758
1. Change TC fixture scope to class, this is creating problem for other test executions
2. Planning to re-work on the entire TC to implement using kube jobs #2758 will have complete fix there.
=> Change scale TC fixture scope to "Class"

ocs_ci/deployment/deployment.py
When a clock skew was detected, we were running vsphere-specific code on
all deployments, causing premature failures.
=> deployment: Don't run vsphere code on all nodes

ocs_ci/ocs/resources/pod.py, tests/e2e/performance/test_pvc_snapshot_performance.py, tests/helpers.py
This Test is to measure time of Creation one snapshot of one PVC and then measure of Restore from one PVC
the test is going to run for RBD and CephFS with PVC size of 1 / 10 / 100 GiB.
the test will be run 3 times (for each PVC) and will calculate the average time of Creation / Restore time.
before each iteration (3) it will fill the PVC with 25% of data (total of 75%).
the measurement is taken from the csi-snapshoter-controller log - from start creation until it bond.
=> Adding test for PVC snapshot performance - Create and Restore

ocs_ci/ocs/resources/pod.py, tests/helpers.py, tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
Automated the above https://bugzilla.redhat.com/show_bug.cgi?id=1774087 and also https://bugzilla.redhat.com/show_bug.cgi?id=1867092
Testcase to verify After 2 OCS node shutdown and recovery, both MDS pods not running on a same worker node
=> Testcase OCS-2230

ocs_ci/ocs/resources/pod.py, ocs_ci/ocs/resources/pvc.py, tests/conftest.py, tests/manage/pv_services/pvc_clone/test_clone_when_pvc_full.py
Test case: OCS-2353 - FT-Clone when PVC is 100% full
```
Create a clone from an existing PVC when the PVC is 100% utilized.
Verify data integrity.
Expand cloned PVC and ensure utilization alerts are stopped firing.
Verify utilization alert in cloned PVC.
```
Created pvc_clone_factory fixture.
Enhancement in ocs.resources.pvc.create_pvc_clone
=> Test case: PVC clone when full

ocs_ci/ocs/constants.py, tests/ocs-monkey/test_ocs_monkey.py
Added a test to run ocs-monkey, a chaos testing suite for OCS.
https://github.com/red-hat-storage/ocs-monkey
=> Add ocs-monkey test

ocs_ci/utility/utils.py, tests/internal/test_skipif_ocp.py
The purpose of this PR is the get the OCP version from the running cluster and not from the configuration file at the deployment section.
for backward compatibility, and since in the deployment phase we do need the information from the configuration file, i created another function and did not modify the existing one.
I also add a simple test that will used as unit-test for this functionality
This should solve #3115 
=> skipif_ocp get the version from running cluster and not from config file

ocs_ci/deployment/vmware.py
consider `DEPLOYMENT["force_deploy_multiple_clusters"]` for VMware cluster prefix existence check
=> consider `force_deploy_multiple_clusters` for VMware

ocs_ci/ocs/ocs_upgrade.py, ocs_ci/ocs/resources/storage_cluster.py
Fixes #2971 . Modified the ocs_ci/ocs/resources/storage_cluster.py and ocs_ci/ocs/ocs_upgrade.py RHW pod count check to include  scenarios of upgrades to 4.5.z and 4.6 as well
Signed-off-by: Neha Berry <nberry@redhat.com>
=> fixes #2971. RGW pod count verification check modification

tests/manage/pv_services/pvc_clone/test_clone_when_pvc_full.py
Fix log in test test_clone_when_full. Corrected pod name. 
=> Fix pod name in log - test test_clone_when_full

tests/manage/pv_services/pvc_snapshot/test_rbd_block_pvc_snapshot.py
Create and restore snapshot of RBD block volume mode PVC. This test case also verifies that the snapshot can be restored after deleting parent PVC
OCS-2361 - FT-Create and restore snapshot of RBD block volume mode PVC
=> Test to take snapshots of RBD Block VolumeMode PVCs

ocs_ci/ocs/ocp.py
Use kubeconfig from cluster dir for `oc` command executed via `exec_oc_cmd` method (if evn. variable `KUBECONFIG` not set).
When OCP cluster is installed via Flexy, `KUBECONFIG` env. variable is not directly set, but `kubeconfig` file is available in `auth` directory in cluster dir, so it make sense to check if it exists and use it from there. 
=> exec_oc_cmd: use kubeconfig from cluster dir if env. variable KUBECONFIG not set

tests/e2e/scale/conftest.py
The test_scale_pvc_expand and test_ceph_pod_respin_in_scaled_cluster
tests should not be run on vms.
=> Add conftest.py hook for vSphere (#2779)

ocs_ci/ocs/resources/pod.py, ocs_ci/utility/workloads/fio.py
Since we add a "long run" fill-up functionality using FIO, while trying to fill very large volume, the test can be take more then 10 Min. which is the default runtime for the FIO (and for any exec_cmd_on_pod() function).
This PR is taking the runtime for the fill-up functionality and set it as the timeout of the command.
This will fix #3126 
=> Change FIO timeout for long running test

ocs_ci/framework/pytest_customization/ocscilib.py, tests/conftest.py
Introducing development mode option which skips the few checks like collecting version,
collecting logs and health checks
Skips below checks:
1. Collecting cluster versions during initilization
2. Collecting OCS versions during live log setup
3. Health check during live log setup
4. Health check during teardown
=> Introducing development mode option which skips the few checks like collecting version, collecting logs etc

ocs_ci/deployment/deployment.py, ocs_ci/ocs/exceptions.py, ocs_ci/ocs/ocs_upgrade.py, ocs_ci/ocs/resources/ocs.py, ocs_ci/ocs/resources/packagemanifest.py
In order to live upgrade for z-streams we need to load CSV name
different way out of latest approved install plan.
Fixes: #2653
=> Allow z-stream upgrade from live content

conf/ocsci/production_powervs_upi.yaml, ocs_ci/deployment/ibm.py, ocs_ci/utility/utils.py
This PR fixes:
* _Some_ of the issues destroying OCS while leaving OCP intact on IBM Power
* An issue with ocs-ci assuming the wrong OCP version (it's trivial to detect it)
* The improper setting of `bin_dir` in one of the stock config files
=> Fixes for IBM Power

tests/conftest.py
pvc_clone_factory is checking status of source PVC instead of cloned PVC. This PR will update pvc_clone_factory to check status of cloned PVC
=> Fix PVC status check in pvc_clone_factory

ocs_ci/ocs/node.py
#3187 introduced some faulty logic in how we match the platform to how we retrieve the compute node names. This change aims to fix that logic and ensure that we are using the right method for each platform.
=> Fixed how we determine method for retrieving compute node names based on platform

tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Since BZ 1779336 was closed with NOTABUG resolution:
https://bugzilla.redhat.com/show_bug.cgi?id=1779336#c34
The test case covering affected feature will be now disabled until rbd
metrics are evaluated as necessary for OCS Monitoring again.
=> disable test_ceph_rbd_metrics_available test

ocs_ci/ocs/ocs_upgrade.py
with this BZ https://bugzilla.redhat.com/show_bug.cgi?id=1840729 moved to verify, im removing the workaround we had in the code, time out set to 10 minutes again
=> removed workaround for OSD timeout after upgrade

tests/manage/pv_services/pvc_resize/test_pvc_expansion.py, tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py, tests/manage/pv_services/test_pvc_assign_pod_node.py, tests/manage/pv_services/test_raw_block_pv.py, tests/manage/pv_services/test_verify_rwo_using_multiple_pods.py
Fixes: #2800 
Revert: #2793 
The related bug [1871314](https://bugzilla.redhat.com/show_bug.cgi?id=1871314) and [1871315](https://bugzilla.redhat.com/show_bug.cgi?id=1871315) have been `CLOSED NOTABUG` due to setup/configuration issue. Reverting the skips so that test cases will be executed in next run after fixing those issues.
=> Revert "Skip relevant pv_services test cases on IBM cloud due to Bug 1871314 and 1871315"

conf/ocp_version/ocp-4.6-ga-config.yaml, conf/ocp_version/ocp-4.6-ga-minus1-config.yaml, conf/ocp_version/ocp-4.6-ga-upgrade.yaml
As OCP 4.6 is GAed, we need to add the GA config for OCP 4.6.
This is done in this commit.
=> Create configs for OCP 4.6 GA

ocs_ci/ocs/couchbase.py, ocs_ci/ocs/pillowfight.py
In couchbase teardown method, added validation for project deletion. 
Fixes https://github.com/red-hat-storage/ocs-ci/issues/3229
=> Couchbase teardown failure fix

ocs_ci/ocs/defaults.py
This will allow us to run more clusters in vSphere Common pool, Current restriction is due to datastore (storage) rather than CPU/Memory.
=> Changing default osd size to 100

conf/ocsci/flexy_baremetalpsi_upi.yaml, conf/ocsci/lso_enable_rotational_disks.yaml, ocs_ci/deployment/deployment.py, ocs_ci/framework/conf/default_config.yaml
Fixes: #3230
Enable rotational disk devices for LSO deployment over PSI +
adding configuration file for enable this option.
=> Enable rotational disks for LSO PSI deployment

conf/ocsci/scale.yaml, ocs_ci/ocs/utils.py
OCS4.6 must_gather failed to complete in 600sec
oc adm must-gather --image=quay.io/rhceph-dev/ocs-must-gather:latest-4.6
`image=quay.io/rhceph-dev/ocs-must-gather:latest-4.6 --dest-dir=/home/jenkins/current-cluster-dir/logs/deployment_1603639721/ocs_must_gather 17:07:50 - MainThread - ocs_ci.ocs.utils - ERROR - Timeout 600s for must-gather reached, command exited with error: Command '['oc', '--kubeconfig', '/home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig', 'adm', 'must-gather', '--image=quay.io/rhceph-dev/ocs-must-gather:latest-4.6', '--dest-dir=/home/jenkins/current-cluster-dir/logs/deployment_1603639721/ocs_must_gather']' timed out after 600 seconds`
Must-gather has many changes in 4.6 which add more time to the …
=> increase the timeout for collection must-gather on OCS4.6

ocs_ci/helpers/helpers.py, ocs_ci/ocs/constants.py, tests/conftest.py, tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
After deleting VolumeSnapShot , verify VolumeSnapShotContent is also deleted.
Added this check in test case test_snapshot_at_different_usage_level and snapshot_factory fixture finalizer
=> Verify VolumeSnapshotContent is deleted in testcase and fixture finalizer

tests/manage/pv_services/pvc_clone/test_clone_when_pvc_full.py, tests/manage/pv_services/pvc_clone/test_clone_with_different_access_mode.py, tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py
Add skipif_ocp_version marker in PVC clone test cases to skips the tests if OCP version is below 4.6
=> Skip PVC clone test cases if OCP version is below 4.6

tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py, tests/manage/pv_services/pvc_snapshot/test_rbd_block_pvc_snapshot.py, tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Add skipif_ocp_version marker in PVC snapshot tests. Tests should be skipped if OCP version < 4.6
=> Skip snapshot tests if OCP version is below 4.6

ocs_ci/templates/mcg/aws-cli-service-ca-configmap.yaml, tests/conftest.py, tests/manage/mcg/test_write_to_bucket.py
awscli fixture wasnt assigning different name for each awscli pod created, which causes an issue when trying to create multiple pods (for example session and function scopes).
For now to resolve issue #3255 we'll also use the function scope awscli pod in the compression and deduplication tests
=> Change awscli pod to random naming and fix awscli_pod_session teardown issue

ocs_ci/ocs/resources/packagemanifest.py
We need to raise an exception for get function in packageManifest class
in the case we will not find the resource with proper name.
This case the wait_for_resource and timeout sampler will work properly.
Fixes: #3260
=> Raise an exception for get packagemanifest function

tests/conftest.py
=> Retry fetching Noobaa endpoint pods data in case of KeyError

tests/manage/mcg/test_endpoint_autoscale.py
The test will do the following:
1. Setup the cluster with a 1-2 endpoint autoscale configuration
2. Assert that the cluster is only running 1 endpoint pod
2. Start a Job that will load the NooBaa s3 service
3. Wait and  assert that the cluster is only running 2 endpoint pods
4. Stop the Job
5. Wait and  assert that the cluster is only running 1 endpoint pod 
Signed-off-by: nb-ohad <mitrani.ohad@gmail.com>
=> NooBaa endpoint autoscale tests

tests/conftest.py, tests/ecosystem/upgrade/test_resources.py, tests/ecosystem/upgrade/test_upgrade_ocp.py, tests/manage/mcg/test_mcg_resources_disruptions.py, tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py, tests/manage/z_cluster/cluster_expansion/test_add_capacity.py, tests/manage/z_cluster/nodes/test_nodes_maintenance.py
We would like to re-enable pre and post upgrade test cases that run IOs. For that, we need to pause the cluster load while upgrade and while IO takes place from these tests.
This will partially address https://github.com/red-hat-storage/ocs-ci/issues/3165
=> Allow only pausing and only resuming cluster load

tests/manage/rgw/test_host_node_failure.py
1. Power off a node which was hosting the RGW pod
2. See if after 10 minutes , a new RGW pod is spun up on another node. The original pod should stay in terminating state
3. Power on a node, cluster health should be OK
=> Fail node hosting RGW pods

docs/code_review.md
Added section to code review doc around commit messages when squashing and merging
=> Code review doc addition

ocs_ci/ocs/fio_artefacts.py, ocs_ci/templates/workloads/fio/config_s3.fio, tests/manage/mcg/test_endpoint_autoscale.py
Add options for FIO profile to generate S3 load to >80% of CPU utilization.  This will trigger noobaa autoscale creating additional endpoint.
This will fix the issue: https://github.com/red-hat-storage/ocs-ci/issues/3282
=> Add options for FIO profile to generate S3 load for noobaa autoscale

ocs_ci/ocs/constants.py, ocs_ci/templates/ocs-deployment/subscription.yaml
In UI deployment the subscription is called ocs-operator,
so we should follow the same naming convention.
Fixes: #2478
=> Name ocs subscription the same like done by UI

ocs_ci/ocs/ocp.py, ocs_ci/utility/prometheus.py
- For successful Prometheus API communication on IBM Cloud needs to be set `ibm_apikey` in `AUTH` configuration.
=> Use api key in Prometheus API communication on IBM Cloud

.pre-commit-config.yaml, docs/conf.py, docs/python-examples/fixtures/test_fixtures.py, ocs_ci/ocs/pod_exec.py, tests/manage/monitoring/test_workload_example.py, tests/manage/monitoring/test_workload_with_distruptions.py, tox.ini
This PR fixes various issues that were causing pre-commit to fail after formatting the repo with black. These failures were coming up now because pre-commit runs against files in your changeset and not against the entire repository. These problems existed before black formatting was being done.
=> Black formatting preparation

.git-blame-ignore-revs, .pre-commit-config.yaml, .travis.yml, requirements-dev.txt, tox.ini
Addresses a few of the outstanding tasks in #2952 by adding `black` to our developer requirements, pre-commit hooks, tox, and travis-ci. Also adds a file that can be used to clean up `git blame` output by ignoring changes done in the reformatting commit.
=> dev workflow updates for black

ocs_ci/templates/CSI/cephfs/pod.yaml, ocs_ci/templates/CSI/rbd/pod.yaml, ocs_ci/templates/app-pods/nginx.yaml, ocs_ci/templates/app-pods/raw_block_pod.yaml
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/3320
=> pull nginx image from quay.io instead of docker to avoid rate limit issue

ocs_ci/ocs/platform_nodes.py
Since we already have "vm_network" parameter in the initial configuration, there is no need to add extra parameter
for adding nodes. Since all the nodes in the same cluster should share the same network.
Fixes: #3295 
=> Changing network_adapter parameter

ocs_ci/utility/utils.py
This PR improves ceph health check by:
adding TimeoutExpired exception to ceph_health_check retries, 
decreasing timeout when trying to connect to rook-ceph-tools pod (default was 600 sec)
=> Improve Health Check

ocs_ci/templates/app-pods/fedora_dc.yaml, ocs_ci/templates/workloads/pgsql/server/StatefulSet.yaml
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/3367
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/3368
=> use fedora and postgres images from quay.io to avoid docker rate limits

ocs_ci/deployment/ibm.py, ocs_ci/ocs/ocp.py
With these changes, deploying OCS after it has already been deployed and destroyed works *usually*; I plan on continuing this work but want to get this in as it's more functional than before.
Proof it doesn't regress: https://storage-jenkins-csb-ceph.cloud.paas.psi.redhat.com/job/ocs-ci-kvm/120/testReport/
=> Rewriting OCS destroy on IBM Power

tests/conftest.py, tests/manage/pv_services/pvc_snapshot/test_restore_snapshot_using_different_sc.py
Test to verify snapshot restore using a storage class different than that of parent.
OCS-2424 - FT-Restore snapshot using an SC different than that of the parent
=> Test to verify snapshot restore using a SC different than that of parent

tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py
Failure is due to compute-0-debug not in running state, which is expected
i.e. compute-0-debug pod used to be created for running some OC commands and
it will be destroyed after that, it's better to avoid validation of debug pod
=> fix-3370 -- Exclude compute-o-debug pod in Validation

ocs_ci/helpers/helpers.py, tests/e2e/scale/test_pvc_creation_deletion_scale.py
The problem is in code should provide ample time for log generation to complete
During PVC deletion process, immediately after kube_job deletion we are collecting
CSI logs to capture PVC delete data.
With 10 or 100 no of PVCs logs are getting generated faster but when we perform delete
of 500/1000/2000 PVCs in bulk, immediately collecting logs missing PVC delete data.
Due to this reason in code list is getting empty data i.e. no respective PVC data in logs.
Fixing the problem by adding 5min wait time
Note: This is just a quick fix, better to have separate function to get the required timeout value based on PVC count.
=> fix-3371 -- Add 5mins waittime after PVC deletion.

ocs_ci/ocs/resources/backingstore.py, ocs_ci/ocs/resources/cloud_manager.py
Should fix failures that stem from a misconfigured/outdated `auth.yaml`
Also:
- hotfix CLI PV backingstore creation bug
- Add CLI BS deletion retry
=> Instantiate all cloud clients as None by default

ocs_ci/helpers/helpers.py
Enhanced the code to check for end succeed data
Observed this failure in recent Jenkins run
```
end = [i for i in logs if re.search(f'delete "{pv_name}": succeeded', i)]
>           end = end[0].split(" ")[1]
E           IndexError: list index out of range
```
=> Fix-3371 - More fix to github issue

ocs_ci/ocs/registry.py
Fixes: #3065
Added a condition to check if s390s platform pull supported openshift `redis-ephemeral ` images.
=> Fixes: unable to locate templates "eap-cd-basic-s2i" on s390s platform.

tests/manage/pv_services/test_expansion_snapshot_clone.py
This test verifies that the clone, snapshot and parent PVCs are independent and any operation in one will not impact the other.
OCS-2408 - FT-PVC snapshot, clone, expansion combination test
=> PVC snapshot, clone, expansion combination test

ocs_ci/ocs/bucket_utils.py, tests/manage/mcg/test_namespace.py
* Add some tier2 and tier3 tests for mcg namespace feature.
* Remove @aws_platform_required marker. All tests should be available on all platforms.
=> Namespace bucket tier2 and tier3 tests

conf/ocsci/allow_lower_instance_requirements.yaml, conf/ocsci/aws_ipi.yaml, conf/ocsci/aws_lower_resource_reqs.yaml, conf/ocsci/aws_upi.yaml, conf/ocsci/vsphere_upi.yaml, ocs_ci/framework/conf/default_config.yaml, ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2, ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
Cause of we've seen a lot of issues like:
https://github.com/red-hat-storage/ocs-ci/issues/3449
Which caused issues in some of runs we decided to have this value as
default and create non production config files.
Fixes: #3463
=> Change default instance type to m5.4xlarge

ocs_ci/ocs/must_gather/const_must_gather.py
Delete 'rook-ceph-mon-a.yaml' because we don't create PVCs for MONs instead we use host path to save mon data.
Fixes #3479
=> must gather, delete 'rook-ceph-mon-a.yaml'

ocs_ci/utility/performance_dashboard.py
This is to brevet test that runs outside of Red-hat network (mostly at IBM) to failed since the codespeed server have access only from within Red-hat network.
this will fix #3471
=> Change the codespeed Error to Warning for non RH runs

conf/examples/without_presistent_monitoring.yaml
New example config file disables ocs persistent monitoring reconfiguration, while keeping monitoring enabled.
This is useful to disable such setup easily from deployment job if necessary.
=> add without_presistent_monitoring.yam conf file

ocs_ci/templates/ocs-deployment/storageclass.gcp.yaml
Fixes https://github.com/red-hat-storage/ocs-ci/issues/3396 based on [bz 1885692](https://bugzilla.redhat.com/show_bug.cgi?id=1885692).
We could wait for the BZ 1885692 to be fixed (which means the docs to be updated), but imho it's safe to merge this now wrt both testing and deployment stability.
=> use delete reclaim policy for GCP storageclass

ocs_ci/deployment/deployment.py
- in the recen versions of OCS, it is not required to prepare openshift-storage namespace and OperatorGroup if it is installed from UI
- fixes: https://github.com/red-hat-storage/ocs-ci/issues/2266
- fixes: https://github.com/red-hat-storage/ocs-ci/issues/2553
=> disable workaround from deploy-with-olm.yaml

ocs_ci/helpers/helpers.py
change the default source_image in create_build_from_docker_image
function from `fedora` to `quay.io/ocsci/fedora` to avoid docker.io rate
limit issues
fixes: https://github.com/red-hat-storage/ocs-ci/issues/3495
=> replace fedora image by quay.io/ocsci/fedora

conf/ocsci/production_powervs_upi.yaml, ocs_ci/deployment/deployment.py
Deploying OCS using ocs-ci on IBM Power Systems if there are more than 1 storage disk available in an OCP cluster.
=> Deploying ocs if storage disks increases

ocs_ci/helpers/helpers.py, tests/manage/z_cluster/nodes/test_nodes_restart.py
- Get pv names and then restart a node.
- After a node-reboot, verify there is not additional unexpected PV.
https://bugzilla.redhat.com/show_bug.cgi?id=1873938
** I used `test_rolling_nodes_restart` to save running time.
=> bug 1873938, Unexpected PV is created after node reboot

tests/e2e/scale/test_cephfs_many_files.py
Node name does not have to be specified for the testcase.  It doesn't matter which worker node is used to run the pod, so don't specify a node name.  Tested on a power server running the ocs-ci scale testsuite.
Signed-off-by: Luke Browning <lukebrowning@us.ibm.com>
=> Invalid node name - compute-0

ocs_ci/ocs/node.py, ocs_ci/ocs/resources/storage_cluster.py, tests/manage/z_cluster/nodes/test_disk_failures.py
- Add support for multiple OSDs verification per node on function `osd_encryption_verification`
for example:
```
ocs-deviceset-OSD1-block-dmcrypt
253:1      0   512G  0 crypt
ocs-deviceset-OSD2-block-dmcrypt
253:1      0   512G  0 crypt
```
Device replacement procredure:
- Scale down the OSD deployment for the OSD to be replaced
- Remove the old OSD from the cluster so that a new OSD can be added.
- Create a new OSD for a new device.
- Verify new OSD encrypted
=> device replacement, verify new device is encrypted

ocs_ci/utility/utils.py
- move summary (passed, failed, skipped...) to the top of the email report
- add passed percentage to the subject of email report
fixes: https://github.com/red-hat-storage/ocs-ci/issues/3507
=> email report enhancement

ocs_ci/ocs/resources/storage_cluster.py, tests/manage/z_cluster/cluster_expansion/test_add_capacity.py, tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py, tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
- Fix function `osd_encryption_verification()`,   (Worked until now because we used nodes with one osd.)
Add Capacity test procedure:
- there are 3 OSDs
- add 100G
- Three new OSDs were created (6 OSD)
- Verify all OSD encrypted
Expected results:
6 OSD Encrypted, 2 OSDs per Node
```
ocs-deviceset-OSD1-block-dmcrypt
253:1      0   512G  0 crypt
ocs-deviceset-OSD2-block-dmcrypt
253:1      0   512G  0 crypt
```
**There is an issue that ceph status stuck on `health_warn` after add capacity with encryption.
=> add capacity, verify all relevant osds are encrypted

conf/README.md, ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/framework/pytest_customization/reports.py, ocs_ci/utility/utils.py
- if RUN["logs_url"] is defined, include it to the Environment part of html
and email report and fix Log File links to point ot the logs_url
instead of local log_dir
- fixes: https://github.com/red-hat-storage/ocs-ci/issues/3511
=> add Logs URL to html test report and email report

tests/e2e/scale/test_cephfs_many_files.py
Log error if Exception is generated by rsync.
When creating new cephfs pod, use template values for namespace and node_name.
Signed-off-by: Warren Usui <wusui@redhat.com>
=> Fix 3453 in tests/e2e/scale/test_cephfs_many_files.py

ocs_ci/templates/app-pods/awscli.yaml
Recently, we've begun to hit the Dockerhub image pull rate limit. Thus, I mirrored the AWSCLI image to Quay.
=> Mirror the AWSCLI image to Quay

ocs_ci/deployment/deployment.py
The reason for the PR is we are using localvolumeset it will create PV on all the disk and in some case, we might have more disk and ocs-ci was failing. This will not fail the deployment if we have more PV create at the time of deployment.
fixes #3217 
=> Don't fail deployment if we have more PV's

setup.py
OCS 4.6 GA is 17.12. so we should move the version here to 4.6.0.
=> Bump version to 4.6.0

ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/storage_cluster.py, ocs_ci/ocs/utils.py, tests/manage/mcg/test_mcg_resources_disruptions.py
The pod label was changed in 4.7, and usage of the old label caused a cluster verification failure.
Closes #3551.
=> Use the correct NB DB pod label for 4.7

tests/e2e/scale/test_pvc_creation_deletion_scale.py
in test_multiple_pvc_creaation_deletion_scale().
This results in a full test no longer throwing an UnexpectedBehaviour
exception.  The elapsed time of the full test increases by about 5%
=> Increase wait_time of measure_pvc_creation_time_bulk call

ocs_ci/ocs/resources/backingstore.py
Fixes #2842 for `tests.manage.mcg.test_bucket_creation.TestBucketCreation.test_bucket_creation`
=> Use external RBD storageclass for NooBaa PV backingstore creation in external mode

ocs_ci/helpers/helpers.py, ocs_ci/ocs/resources/backingstore.py
Up until now, we did not verify that the PV was deleted after a PV backingstore was deleted.
We did confirm that the related pod and PVC were deleted, but sometimes, a PV is left for a few seconds after the PVC is gone, which has caused false failures in teardowns.
This PR verifies that the PV is also deleted thoroughly, before moving on to the rest of the teardown.
=> Verify thorough PV backingstore deletion

ocs_ci/ocs/disruptive_operations.py, ocs_ci/ocs/ocs_upgrade.py, tests/ecosystem/upgrade/test_upgrade.py
Disruptive upgrade test: reboot OSD during upgrade. 
Test case: OCS-1558
=> Disruptive upgrade test: reboot OSD during upgrade.

conf/ocsci/openshift_dedicated.yaml, ocs_ci/framework/pytest_customization/marks.py, tests/manage/mcg/test_bucket_creation.py, tests/manage/mcg/test_bucket_deletion.py, tests/manage/mcg/test_write_to_bucket.py
**Description**
- This PR has the changes to skip the MCG related tests as part of openshift dedicated acceptance testing.
- `conf/ocsci/osd_cluster.yaml` will be passed as a value for `--ocsci-conf` parameter
=> Skipping mcg related tests for openshift dedicated acceptance testing

ocs_ci/ocs/node.py, tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
**Description**
This PR has the below changes
- Changes required to filter out the infra nodes from worker nodes
- Changes required to expand PVC with a small amount to fall behind default quota
**This PR is dependent on** https://github.com/red-hat-storage/ocs-ci/pull/3543 
=> Acceptance test related changes for openshift dedicated

ocs_ci/framework/pytest_customization/reports.py
Closes #1862
Checked locally and the warning does not appear anymore after moving the import.
Needs more thorough verification.
=> Move RPLogHandler import to prevent PytestAssertRewriteWarning

ocs_ci/ocs/resources/cloud_manager.py
As part of `test_bucket_deletion`, we delete an OBC containing objects.
This means that NB has to delete all the objects by itself once the OBC is deleted.
However, we proceed to try and clean up + delete the ULS once the test is done, and it seems like we ran into a race condition where both we and NB try to delete the same blobs.
This PR should retry blob deletion until the bucket is completely empty and ready for removal.
=> Handle GCP ULS deletion race condition

ocs_ci/ocs/exceptions.py, ocs_ci/ocs/resources/objectbucket.py, tests/conftest.py
Seems like OBCs are not always included in the `must-gather`, so this change allows us to have a better idea of what was their state at the time of the failure
=> Print OBC YAML and `oc describe` if it fails to bind on creation

tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Increase snapshot restore wait time in test_snapshot_at_different_usage_level due to [BZ 1899968](https://bugzilla.redhat.com/show_bug.cgi?id=1899968)
=> BZ 1899968 workaround

ocs_ci/deployment/vmware.py
Skipping configuring chrony in vSphere environment due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1910738
=> Skip configuring chrony in vSphere for OCP version 4.7

tests/manage/monitoring/prometheusmetrics/test_ocs_utilization.py
Since the CI test runs can't provide idle environment as expected by
test_mcg_cpu_usage test case, we need to increase cpu utilization limit
from 10% to 25%, which would cover common peak value of 15% seen in CI,
but still safely caught BZ 1849309 regression. Original limit 10% was
based on observation in actual idle state, and multiplied 10x.
Fixes https://github.com/red-hat-storage/ocs-ci/issues/3547
=> increate limit for noobaa cpu utilization test

ocs_ci/helpers/helpers.py, ocs_ci/ocs/elasticsearch.py, ocs_ci/templates/app-pods/esclient.yaml, tests/conftest.py, tests/fixtures.py, tests/libtest/test_elasticsearch.py
In this PR, there is improvement of the Internal elasticsearch retrieving methodology.
I added a '**dumper**'  pod  in the elastic-system namespace which can dump all the data from the internal ES server to a .tgz file, and copy it outside of the cluster.
later one, the data from this file can be pushed to an ES server for reporting.
This will fix Issues: #3533 , #2901 and  #3492
=> Improve internal ElasticSearch module

tests/e2e/performance/test_small_file_workload.py
In the Ripsaw repository the server + port parameters replaced with the url parameter.
i just added the url parameter and not replaced the server+port to prevent more changes in the code that use thous parameters
This will fix #3645 
=> Adding the url parameter to the CRD file for the smallfile workload.

tests/e2e/performance/test_fio_benchmark.py
In the Ripsaw repository the server + port parameters replaced with the url parameter.
i just added the url parameter and not replaced the server+port to prevent more changes in the code that use thous parameters
This PR along with PR #3647 will fix #3645
=> Adding the url parameter to the CRD file for the FIO workload

ocs_ci/ocs/defaults.py, ocs_ci/utility/environment_check.py
**Description**
This fixes the tear down failure on various tests in openshift-dedicated, by ignoring the openshift-build-test namespace. As multiple namespace of openshift-build-test* pattern gets created even after the successful cluster creation which then interferes with the OCS-CI tear down process.
=> [Openshift-Dedicated] Exclude openshift-build-test namespace on teardown

ocs_ci/ocs/resources/mcg.py
We started seeing a pattern in recent OCS 4.7 runs where the NB token retrieval RPC call would fail.
We do not log it, and thus, can't know what is the issue.
=> Log MCG RPC token retrieval calls

ocs_ci/ocs/resources/packagemanifest.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/3285
Verification: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/15944/consoleFull
(You can ctrl+f `kind: CatalogSource` to see results)
=> Adding retries to get Catalog Source for OCS Internal Operator

ocs_ci/ocs/constants.py, ocs_ci/utility/localstorage.py
Use selector to ensure optional operators packagemanifest is selected for LSO when OCP is not GA
=> optional operators selector

tests/conftest.py
Test cases are failing in tear down due to timeout error while waiting for PV to get deleted after deleting the PVC.
eg: tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py::TestResourceDeletionDuringPvcExpansion::test_resource_deletion_during_pvc_expansion[mgr]
Test result.
Bug - https://bugzilla.redhat.com/show_bug.cgi?id=1915706
Increased the PV deletion wait time to 720 seconds in pvc_factory_fixture fixture.
Fixes #3678
=> Increase PV deletion wait time if platform is azure

tests/conftest.py
- Print warning if new alerts are raised during test to help with test analysis.
- Most of the code is in try, except blocks to prevent fails if Prometheus is not available.
=> Check if new alerts are raised during test

ocs_ci/utility/rgwutils.py
Use semantic version to calculate prior ocs version when determining rgw_count
=> rgw_count semantic version

ocs_ci/ocs/machine.py
Should Fix: #3695 
Increase timeout for `wait_for_new_node_to_be_ready()` in `machine.py`
=> Give extra time for new nodes to reach Ready state

tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Add end_fsync=1 fio parameter in test test_resource_deletion_during_pvc_expansion.
According to this [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1915706#c9)  it is advisable to add end_fsync if the volume will be deleted immediately after the IO. 
=> Add end_fsync while running fio in test

tests/manage/mcg/test_endpoint_autoscale.py
For more information, see #3720
=> Skip `test_endpoint_autoscale`

ocs_ci/ocs/platform_nodes.py
Fixes: #3735 
In Azure platform, node(s) takes longer time to reach Ready state (takes around 12 minutes sometimes) after node restart. Hence, increased the timeout to 900 seconds.
=> Increase timeout value in restart_nodes() for Azure platform

ocs_ci/ocs/platform_nodes.py, tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
This PR Fixes #3709
Use dc pod in test_worker_node_restart_during_pvc_expansion because pods might respin on different node after a node reboot. The verification of PVC capacity after expansion should be done after identifying the re-spun pods. This will ensure thet the filesystem resize is completed.
=> Use dc pod in test_worker_node_restart_during_pvc_expansion

tests/manage/rgw/test_bucket_deletion.py
Due to a change done in #3623, the OB deletion assertion is [no longer returning a value](https://github.com/red-hat-storage/ocs-ci/pull/3623/files#diff-182979f19c5a44501b1e65af59e1067af0e96e8b479ca0eb150e208459b16934L164-R164).
Thus, the test assertion would lead to an `assert None` case.
=> Remove object bucket deletion assertion from test_bucket_delete

tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
Fixes #3744 
Test case ```test_add_capacity_node_restart``` is updated to use the default value of platform specific restart node timeout which is given in ```restart_nodes``` function.
=> Fix restart node timeout error in test

ocs_ci/ocs/elasticsearch.py, ocs_ci/ocs/perfresult.py, tests/e2e/performance/test_fio_benchmark.py
With this PR the FIO test will be able to run and collect data at environment without an elasticsearch server to push the results into (e.g. IBM)
If Elasticsearch server does not exist, the test will not failed.
Also some more changes :
* do not push results of dev-mode run to codespeed
* use the global ES fixture
* do not raise excaption if no connection to elasticsearch
=> FIO | use the new algorithm for environment without elasticsearch server

tests/ocs-monkey/test_ocs_monkey.py
[Chaos_runner](https://github.com/red-hat-storage/ocs-monkey/blob/master/chaos_runner.py) is a randomized fault injector which will run pod delete operations - rbdplugin, rbdplugin-provisioner, mon, osd, operator pods. Chaos_runner will be triggered along with workload_runner.
Closes #3132 
=> Add chaos_runner in test_ocs_monkey

ocs_ci/deployment/deployment.py, ocs_ci/utility/utils.py
Fixes: #3764 
SSD tuning will be auto-applied after OCS deployment as a workaround for bug [1909793](https://bugzilla.redhat.com/show_bug.cgi?id=1909793)
For an existing cluster (without this tuning), follow the steps given in this doc: https://docs.google.com/document/d/1GVUazTDTmFKJ5budSuFPGWs3aYjzzxWpSaga22kXO9M/edit?usp=sharing
=> [AZURE] Apply SSD tuning as a workaround for bug 1909793

tests/ecosystem/upgrade/test_noobaa.py
- mcg_workload_job fixture teardown is called after upgrade so that the IO is ran during upgrade even when the test is skipped.
=> Skip test_upgrade_mcg_io due to BZ 1874243

setup.py
At least until the ppc64le issue is fixed.
=> Pin greenlet to pre-1.0.0 versions

ocs_ci/utility/utils.py
This commit updates config options in `apply_ssd_tuning_azure()`
- Remove suffix _ssd from config options as with _ssd sufix options are ignored for the disks
- Add config option 'bluestore_max_blob_size'
=> [AZURE] Update SSD tuning config options

Jenkinsfile
I've tested this and python3.8 is installed and used: https://storage-jenkins-csb-ceph.cloud.paas.psi.redhat.com/job/ocs-ci/215/console
=> downstream ci: use python3.8

ocs_ci/ocs/node.py, tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
When we use more than 3 OCS worker nodes, if we replace an existing OCS worker node, one of the **existing** OCS worker nodes will replace the old one. So in the verification steps, we should consider the option that the new OCS worker node **will not** be associated with one of the OSD's. Instead, one of the existing OCS worker nodes will be associated with the OSD's.
=> Update Node replacement verification steps when we use more than 3 OCS worker nodes

ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/mcg.py
The CLI commands were changed in 4.7 (CLI 5.7.0) in order to support creation of bucketclasses that contain namespace stores.
This PR aims to fix placement-policy-based BC creation via CLI on 4.7
=> Fix MCG CLI bucketclass creation in 4.7

ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/objectbucket.py
In OCS 4.7, the field name was changed from *O*bjectBucketName, to *o*bjectBucketName
=> Look for the right ObjectBucketName field dependent on version

ocs_ci/ocs/perfresult.py, ocs_ci/ocs/perftests.py, tests/e2e/performance/test_small_file_workload.py
This PR is implementing the new way of using internal elastic-search server within the cluster and retrieving data from it to the main elastic-search server.
without this fix the test will not work properly, since we saw that the old method did not work all the time.
it also implement new Library for the Performance & Scale tests to prevent code duplication.
=> Smallfiles - use the new ES method to retrieve data from internal ES

tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
delete_and_create_osd nodes only handle cloud and vsphere platforms, it does nothing for IBM and in the end verification fails, we should skip this test.  Seen during one of the dev failures https://storage-jenkins-csb-ceph.cloud.paas.psi.redhat.com/job/ocs-ci-kvm/152/testReport/
=> Skip node_replacement_proactive test for IBM as the logic doesn't handle the IBM specific instance

ocs_ci/helpers/proxy.py
Improve logging and performace of get_cluster_proxies function:
- change log level from info to debug
- save loaded proxy configuration to config object
- related to https://github.com/red-hat-storage/ocs-ci/issues/3800
=> get proxies: logging and performance improvement

docs/getting_started.md, ocs_ci/deployment/disconnected.py, ocs_ci/deployment/flexy.py, ocs_ci/framework/conf/default_config.yaml, ocs_ci/helpers/disconnected.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/exceptions.py, ocs_ci/utility/utils.py
This patch is implementing installation of live (released) OCS in disconnected OCP environment.
It mostly follows steps from official OCP documentation [3.8. Using Operator Lifecycle Manager on restricted networks](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html-single/operators/index#olm-restricted-networks).
Additionally it contains few small doc string fixes for issues from previous PR.
=> OCS disconnected installation from live content

tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
The below test case is failing with CephHealthException while waiting for ceph health status to be HEALTH_OK.
tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py::TestAddCapacityNodeRestart::test_add_capacity_node_restart[1-workload_storageutilization_rbd0]
Add capacity succeeded. But recovery is taking more than the given wait time. Increasing the retries will resolve the issue.
Fixes #3832
=> Increase ceph health check timeout in test test_add_capacity_node_restart

tests/manage/mcg/test_bucket_policy.py
Fixes #3839 
Adding an allow statement in bucket policy denied already given access to the bucket - only deny should do it and bucket_owner was allowed access even if specific deny access appeared. 
https://github.com/noobaa/noobaa-core/pull/6252
=> Fix for test_object_actions with explicit allow

conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml, conf/deployment/azure/ipi_3az_rhcos_3m_3w.yaml, conf/ocsci/azure2_qe_rh_ocs_com_domain.yaml, conf/ocsci/azure_qe_rh_ocs_com_domain.yaml, docs/supported_platforms.md
- remove `base_domain` from azure config, to support more azure Accounts with different `base_domain`
- create new config files defining `base_domain` for the two available Azure accounts (usable for manual execution, in Jenkins this is handled as Credential files)
- related to https://projects.engineering.redhat.com/browse/OCSQE-596
- the merge should be coordinated with [MR!545](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/545)
=> remove base_domain from azure configs

Jenkinsfile
We don't need it, and it has caused some problems lately when using
non-ephemeral nodes. Since this is all we needed the ipv6 stuff for,
drop it as well.
=> Jenkins: Drop postfix

tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Currently, the Node replacement proactive test can work on vSphere and cloud platforms. 
So we don't need to add the annotations of `cloud_platform_required` and `vsphere_platform_required`.
=> Change Node replacement proactive test to run on vSphere and cloud platforms

tests/manage/mcg/test_namespace.py
=> Skip namespace tests when unsupported OCS version is installed

tests/manage/z_cluster/nodes/test_nodes_restart.py
Replaces aws_platform_required with cloud_platform_required in test_nodes_restart
=> Modify test_nodes_restart to run on all Cloud platforms

ocs_ci/ocs/resources/backingstore.py
The teardown currently fails because it looks for the PVC in the default namespace, instead of `openshift-storage`.
=> Look for backingstore PVCs in the right namespace

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
A workaround for https://github.com/red-hat-storage/ocs-ci/issues/3856
=> Skip pre upgrade add capacity test over on prem

ocs_ci/ocs/node.py, ocs_ci/ocs/platform_nodes.py, ocs_ci/utility/powernodes.py, ocs_ci/utility/service.py
This is an implementation of node stop/start/restart for
IBM Power environment other than libvirt. In libvirt
environment, the same is implemented using virsh stop/start etc.
For IBM Power environment other than Libvirt, the same is
attempted with stop/start of kubelet service inside the nodes.
Signed-off-by: gitsridhar <svenkat@us.ibm.com>
=> Implement node stop/start/restart for Power

ocs_ci/ocs/constants.py, tests/manage/rgw/test_host_node_failure.py
The test currently only verifies the pod name in 4.6 and below.
I changed it to work with the new pod name. This should address, at least partially, #3926
=> Fix test_rgw_host_node_failure to look for the correct NB DB pod name

conf/deployment/vsphere/eagerzeroedthick_storage_class.yaml, conf/deployment/vsphere/thick_storage_class.yaml, conf/deployment/vsphere/zeroedthick_storage_class.yaml, ocs_ci/deployment/vmware.py, ocs_ci/ocs/constants.py, ocs_ci/templates/ocs-deployment/vsphere_storageclass_thick.yaml
https://issues.redhat.com/browse/KNIP-1610
According to https://bugzilla.redhat.com/show_bug.cgi?id=1932280#c10:
There is no "diskformat: thick" supported in OCP. There is only "thin", "zeroedthick" and "eagerzeroedthick" - see https://docs.openshift.com/container-platform/4.7/storage/dynamic-provisioning.html#vsphere-definition_dynamic-provisioning
=> [4.8 feature] vSphere deployment with thick storageclass

Docker_files/build.sh, Docker_files/performance_image
This PR Adding Dockerfile, with specific name for container image which will be pre-loaded with tools that we need (fio / rsync / git)
is also adding a build scrip which will build and push the image to the repository.
it can create multi-arch image that can ran on x86_64 / s390 / ppc64
The purpose of it is to use pre-loaded images instead of installing tolls on pods during the tests.
this addressing #3958
=> Adding Dockerfile and build script for performance container image

ocs_ci/deployment/disconnected.py
* do not mark Red Hat Operators on disconnected cluster as `ocs-operator-internal`
* use proper ocs-registry image
=> Disconnected ocs upgrade - small fixes

ocs_ci/ocs/constants.py, ocs_ci/templates/app-pods/performance.yaml, tests/e2e/performance/test_pod_reattachtime.py
The main issue that this PR is fixing is, adding 'sync' command after we are writing data, so all data will be actually will be written to the PVC and not stay in the cache.
also, it replace the 'nginx' image (for the pod) with pre-loaded image with the rsync command, so we do not need to install the rsync on the pod during the test.
the test was create new SC and now it use the default SC
=> Pod reattach | adding sync after writing data

ocs_ci/ocs/resources/backingstore.py, tests/conftest.py
we currently return all created buckets and backingstores in these factories instead we should only return the currently requested objects.
=> Return the MCG resources created for the current factory scope instead of all scopes

tests/e2e/performance/test_pvc_creation_performance.py
The reason for increasing multiple creation time threshold by 5 secs ( from 45 to 50 secs) is the fact that the test was failing on Azure encrypted cluster- multiple creation time was 46.71secs ( and on number of different runs it was always 46 - 47 secs)  
See 4.6 Performance report for this measurement : 
https://docs.google.com/document/d/11q_DqV30XY7DG_AgwZWVvl3k0KI5PNjqLLFqjUs5tns/edit#
Therefore after consulting @Avilir we've agreed that it's ok to raise this threshold up to 50 secs.
=> fixing github issue #3569 - increasing multiple creation time by 5 secs

ocs_ci/utility/service.py
This PR will fix the errors that we are getting while restarting and stopping node in our powerVS environment. 
When systemctl status command is executed via ssh, it does not always return 0. It returns 3 if the service is in stopped state. So we need to ignore non-zero return code. 
Signed-off-by: Aaruni Aggarwal <aaruniagg@gmail.com>
=> Fix error while checking node status

ocs_ci/deployment/deployment.py
The PR #3953 removed the condition for arbiter deployment
over AWS.
Fixes: #4029
=> Fix arbiter deployment

ocs_ci/framework/conf/ocs_version/ocs-4.8.yaml
Cause we already have stable tag and we have deployment blocker
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1941448
which block 4.8 deployment with latest tag only we should
start consuming stable tagged builds from now on.
=> Use stable 4.8 tag

ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/ocs/exceptions.py, ocs_ci/ocs/ocp.py, ocs_ci/ocs/resources/catalog_source.py, ocs_ci/ocs/resources/cloud_manager.py, ocs_ci/utility/utils.py
This PR makes some improvements to ocs-ci's error reporting; specifically, it should save some time when triaging failures related to timeouts or wrong-state errors.
If you're like me, you typically review failures inside Jenkins, viewing the console log (either for the entire build or just one pipeline stage), starting from the bottom of the traceback and scrolling up from there.
The things I wanted to improve in this PR are:
1. The lack of information in `TimeoutExpiredError`
2. Having to scroll past hundreds or thousands of lines of `describe` output before seeing the "wait for _ resource at column _ to reach..." message
3. `ResourceWrongStatusException`: Instead of only reporting `Resource <name>`, can report as much as `<kind> resource <name> in column <col> was in state <actual> but …
=> Improve timeout/wrong-state reporting

ocs_ci/ocs/resources/storage_cluster.py
Fixes: #4000 
For LSO Direct I/O cluster, storage value is "1" unlike other cluster ( 100Gi ).
=> Fixing get_osd_size for LSO Direct I/O cluster

ocs_ci/ocs/perftests.py
Removing the @performance & @scale markers from the PASTest class, so only markers on the particular tests classes will selected, and performance tests will not run when using @scale marker and scale tests will not run when using @performance marker.
=> remove markers from PAStest class

ocs_ci/ocs/cluster.py
This PR add a function which find the default pool replica count from the `ceph status` command.
it also change the get_ceph_capacith() function, to use the new replica count function, to fix #4053 
=> Adding function to find the default pull replica count

tests/e2e/scale/test_pv_scale_ocs_create_delete_pvcs.py
Removed TODO to uncomment memory leak function
Earlier due to bz-1750328 commented those lines, now the code is expected to work
It's already working in TC tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
=> Start using Memory leak function

tests/manage/mcg/test_namespace_crd.py
The test failed because the bucketclass factory expects `namespacestores` to be a list of NamespaceStore objects, but the test passes an object instead
=> Pass NSS list instead of object in `test_namespace_bucket_creation_with_many_resources_crd`

ocs_ci/deployment/deployment.py, ocs_ci/ocs/resources/storage_cluster.py
Enable Flexible scaling parameter on lso cluster with less than 3 zones, on OCS 4.7 and above
Verify failure domain is "host"
=> Enable Flexible Scaling on LSO cluster

ocs_ci/ocs/resources/mcg.py
Although all cloud clients should be initialized as None by default, this change makes the code more robust by not having to rely on them being initialized at all
=> Modify NSS_MAPPING's get_attr_chain usage to be safer

ocs_ci/ocs/resources/cloud_manager.py
The default behavior of the cloud manager is to initialize any clients with missing credentials as None.
This fixes the RGW client to follow suit, instead of not being initialized at all
=> Initialize RGW cloud client as None in case regular init failed

ocs_ci/ocs/constants.py, ocs_ci/ocs/scale_lib.py, tests/e2e/scale/test_ceph_pod_respin_in_scaled_cluster.py, tests/e2e/scale/test_scale_pvc_expand.py
Enhanced TC tests/e2e/scale/test_ceph_pod_respin_in_scaled_cluster.py to use
POD creation using kube_job, TC used to fail for memory allocator issue
with this fix it should work without any issues
=> Enhance TC scale/test_ceph_pod_respin_in_scaled_cluster.py to use kube_job for pod creation

tests/manage/pv_services/test_rbd_thick_provisioning.py
PVC provisioning is taking more than the given timeout of 120 seconds. Increasing timeout.
Fixes #4136 
=> Increase PVC provisioning timeout in test test_rbd_thick_provisioning 

ocs_ci/helpers/helpers.py, tests/manage/pv_services/conftest.py, tests/manage/pv_services/test_expansion_snapshot_clone.py
This PR covers the following test cases:
1. PVC snapshot restore, clone and expansion using think provision storage class.
OCS-2502 - FT-ThickProvisioning-PVC snapshot, clone, expansion test
2. Use thick provision storage class while restoring the snapshot of a thin provisioned PVC. Perform  expansion and clone operations on the restored PVC.
OCS-2507 - FT-Thick provision storage class to restore the snapshot of a thin provisioned PVC
3. Use thin provision storage class while restoring the snapshot of a thick provisioned PVC. Perform  expansion and clone operations on the restored PVC.
OCS-2508 - FT- Thin provision storage class to restore snapshot of a thick provisioned PVC
Updated create_pvcs_and_pods fixture to enable the capability to create CephFS or RBD PVC alone with the storage …
=> RBD thick provisioning - verify PVC expansion, snapshot and clone

tests/e2e/scale/test_scale_amq.py
Skip AMQ tests/e2e/scale/test_scale_amq.py TC due to issue #3372
This failure is observed in all the test run and the plan to fix this
issue is for now lower, so adding skip marker.
=> Skip tests/e2e/scale/test_scale_amq.py TC due to issue #3372

ocs_ci/ocs/small_file_workload.py, tests/e2e/scale/test_scale_small_file_workload.py
Remove elastic search usage from Scale test tests/e2e/scale/test_scale_small_file_workload.py
=> Remove elastic search usage from Scale tests

.github/CODEOWNERS
This change allows us to more granularly control the approval and merge procedures of MCG-related PRs by requiring reviews from specific members
=> Define MCG code owners

tests/ecosystem/upgrade/test_noobaa.py
The current assertions are problematic because `bucket.status` returns a CompletedProcess object for CLI OBCs, and the tests try to compare a string to the entire object. This PR fixes it by using the internal `verify_health()` logic that takes this into account
=> Use `verify_health()` in test_noobaa

tests/ecosystem/upgrade/test_noobaa.py
`verify_health()` has no return value,  leading the assertions to fail.
=> Remove test_noobaa verify_health() assertions

ocs_ci/utility/utils.py
The original code would not work properly when given a list of expressions, and would always return `False` when more than one expression was given.
This PR aims to fix that while also shortening the code.
=> Fix `skipif_ocs_version` logic

Docker_files/osd_cache_dropping, ocs_ci/ocs/resources/cache_drop.py, ocs_ci/templates/workloads/fio/drop_cache_pod.yaml
This PR update the yaml file for creating cache_drop_pod to use multi-arch image.
It also add the Dockerfile to build the multi-arch image for cache dropping
and it create an object to implement the use of this new pod.
the new object implement :
- pod Deployment
- pod deletion (in the end of the test - teardown)
- Drop the OSD cache
=> Adding Osd cache drop for performance tests

tests/e2e/scale/noobaa/test_scale_endpoint.py, tests/manage/mcg/test_endpoint_autoscale.py
Creating 10 FIO pods running in parallel to generate enough load to trigger Noobaa autoscale feature.
Fixing issue: https://github.com/red-hat-storage/ocs-ci/issues/4129
=> Add additonal FIO workload to trigger Noobaa autoscale 

ocs_ci/ocs/ui/base_ui.py
*Added arguments for ignore ssl because this github issue https://github.com/red-hat-storage/ocs-ci/issues/4209
*Change resolution of screenshot (headless)
=> Added arguments for ignore ssl

.github/CODEOWNERS
On the Manage team call that was held yesterday, it was decided to add the test analysis squads as CODEOWNERS ("top level reviewers") for each squad's appropriate test directories. Once this PR is merged, particular sets of people will _have_ to review and approve certain PRs in order to merge them into `master`. This change is supposed to help improve code quality and accountability across the project.
The teams can be seen [here](https://github.com/orgs/red-hat-storage/teams/ocs-qe/teams)
=> Define OCS-CI CODEOWNERS by squads

ocs_ci/ocs/node.py, ocs_ci/ocs/resources/pod.py, tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Currently, the node replacement verification steps are working. Still, when we have many OSD's(for example, after adding capacity to the cluster), sometimes the verification steps can fail. So we need to extend the verification steps to work on any cluster - no matter the number of the OSD's and worker nodes.
=> Extend the node replacement verification steps to work with more than 3 OSDs

.github/workflows/pr_checks.yml
This package provides `curl-config`, which is dependency for `ovirt-engine-sdk-python` on Github actions
This change is required by following two PRs: https://github.com/red-hat-storage/ocs-ci/pull/4192, https://github.com/red-hat-storage/ocs-ci/pull/4159
=> Github actions: install libcurl4-openssl-dev package

ocs_ci/deployment/disconnected.py
On disconnected installation from live, we didn't wait for machineconfigpool status to be updated after creation of imageContentSourcePolicy. This causes failures when creating StorageCluster when not all mon pods were running in time (or at all).
Related to [BZ1959935](https://bugzilla.redhat.com/show_bug.cgi?id=1959935).
=> Disconnected instalation from live: wait for machineconfig status

ocs_ci/ocs/amq.py
Fixes: #4302 
Description:
From python 3.8, there is new warning added for using identity checks
for certain type of literals.
Use equality ( == and != ) instead of identity checks ( is and is not )
=> Use equality instead of identity checks 

ocs_ci/utility/utils.py
- fixes https://github.com/red-hat-storage/ocs-ci/issues/4280
=> run load_cluster_info_file before cluster_load

ocs_ci/ocs/resources/storage_cluster.py
With OCS 4.8 there will be a new storage class ```ocs-storagecluster-ceph-rbd-thick``` created during installation. Adding this to the list of the storage class to be verified after installation.
=> Check RBD thick storage class in install verification

tests/manage/mcg/test_object_integrity.py
Caching not supported in ocs 4.6
=> Skipping noobaa cache test on ocs 4.6

ocs_ci/ocs/cluster.py, ocs_ci/ocs/constants.py, tests/manage/z_cluster/cluster_expansion/test_add_capacity.py, tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py, tests/manage/z_cluster/cluster_expansion/test_delete_pod.py, tests/manage/z_cluster/conftest.py
According to the last failures of the "add_capacity" tests, we need to perform some changes in the test:
1. Increase timeout when running IO in the background in the "add_capacity" test.
2. Label the OCS worker nodes before the "add_capacity" the test `test_add_capacity_with_resource_delete` starts.
3. If we use the vSphere platform, we might need to add 3 extra worker nodes and label them before the test `test_add_capacity_with_resource_delete` starts.
=> Update add capacity tests

ocs_ci/framework/pytest_customization/marks.py, tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
- Combine three test cases of coredump [osd,mon,mgr] because long running time of coredump test (~ 30m on tier1 suite)
- Skipping coredump test on cluster with rhel  #4310
- Skipping coredump test on external cluster  #4342
=> Combine 3 test case of coredump test

ocs_ci/deployment/vmware.py, ocs_ci/ocs/constants.py
- replace deprecated https://gitlab.cee.redhat.com/aosqe/cluster-launcher.git
by https://gitlab.cee.redhat.com/aosqe/v4-scaleup.git
- fixes https://github.com/red-hat-storage/ocs-ci/issues/4343
=> change cluster-launcher repo to v4-scaleup

docs/usage.md, ocs_ci/framework/pytest_customization/ocscilib.py, setup.py
This new parameter allows to re-trigger only failed tests from the
previous execution provided as path to junit xml file.
=> Add --re-trigger-failed-tests parameter

docs/getting_started.md
Add requied packages `libcurl-devel` and `libxml2-devel` to  getting_started doc.
Related to https://github.com/red-hat-storage/ocs-ci/pull/4192.
=> update doc with requirements for ovirt-engine-sdk

tests/manage/z_cluster/test_osd_heap_profile.py
gss bug: https://bugzilla.redhat.com/show_bug.cgi?id=1938049
Test Procedure:
1.Start heap profiler for osd
$ oc exec rook-ceph-tools-85ccf9f7c5-v7bgk ceph tell osd.0 heap start_profiler
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
osd.0 started profiler
2.Dump heap profile
$ oc exec rook-ceph-tools-85ccf9f7c5-v7bgk ceph tell osd.0 heap dump
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
osd.0 dumping heap profile now.
MALLOC:      439066216 (  418.7 MiB) Bytes in use by application
MALLOC: +            0 (    0.0 MiB) Bytes in page heap freelist
MALLOC: +     43649688 (   41.6 MiB) Bytes in central cache freelist
MALLOC: + …
=> GSS-BUG: Generate heap profile dump file for OSD

ocs_ci/ocs/bucket_utils.py, tests/manage/mcg/test_namespace_crd.py
test_read_cached_object have failed in recent automation runs due to slowness in execution, therefore I've adjusted the TTL of the test to 5 minutes instead of 1 to prevent slow execution time and latency from causing failures in the future.
=> extend test_read_cached_object ttl

tests/e2e/performance/test_io_performance.py
Removing the performance marker from the basic IO test since it is not performance test, just an I/O functionality test
=> io - Remove performance marker

ocs_ci/helpers/helpers.py
Increase the timeout from 3mins to 6mins, Observed issues of no PVC creation/deletion data in CSI logs after 3mins
increating this value to 6mins, if we hit this problem again then have to report bugzilla for missing PVC creation logs.
=> Increased the CSI log timout to 6mins to add more wait for PVC creation data in CSI logs

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
We can see in the Jenkins job https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-aws-ipi-3az-rhcos-3m-3w-acceptance/45/ that the test "test_add_capacity" failed on timeout when waiting for the Ceph rebalance to complete. 
So in this PR, I increased the Ceph rebalance timeout.
=> Increase timeout in the test 'test_add_capacity'

ocs_ci/deployment/vmware.py
Fixes: #4373
destroy_cluster and deploy_ocp methods of vSphere IPI should be under VSPHEREIPI class
Description: During teardown of cluster for vSphere IPI, destroy method
is calling the aws destroy method instead of it own
=> destroy_cluster and deploy_ocp methods of vSphereIPI should be under its own class

ocs_ci/deployment/disconnected.py, ocs_ci/deployment/flexy.py, ocs_ci/ocs/constants.py
* Prepare `cluster-logging` and `elasticsearch-operator` for installation on a disconnected cluster.
* mirror required images from `redhat-operators` catalog
* Extend timeout for rsync flexy-dir command.
The patch looks like lot of changes, but there is not much new code - mostly it is restructuring and moving the existing functionality. Previously we were creating/mirroring `redhat-operators` only for Live installation, now we are mirroring the related images and creating `redhat-operators` catalog source also for OCS installation from internal builds - to be able to install also `cluster-logging`, `elasticsearch-operator` and `local-storage-operator`.
=> Disconnected cluster: prepare installation of cluster-logging operator

ocs_ci/deployment/deployment.py
vcpus are platform specific:
-  1 vcpu is 1/2 of a processor core for x86
-  1 vcpu is 1/8 of a processor core for power
The ocs-ci suite includes a performance test and limits seem contrary to the goal
of measuring performance.  These limits would have to be scaled to make sense for
power.  But, is it desirable to have limits on a storage resource?  A limit on
storage performance is an indirect limit on workload performance.
The UI deployment of ocs does not impose cpu and memory limits.  Shouldn't ocs-ci
emulate customer configuration?   I don't think it is needed or desirable.
By default, the linux scheduler and virtual memory management provide fairness.
The use of limits makes sense when a subsystem is cpu intensive or memory intensive,
but ceph is neither.
Signed-off-by: Luke …
=> Remove cpu and memory limits for ceph pods

ocs_ci/utility/utils.py
- this will ensure, that email with test results will be send even when
the get_ocs_build_number() fails for example because some network
issue or because the cluster was deleted
fixes https://github.com/red-hat-storage/ocs-ci/issues/4387
=> Ensure that email with test results is send even in case of failure in sessionfinish 

tests/manage/storageclass/test_create_storageclass_with_same_name.py
Fix test_create_storageclass_with_same_name to initiate storage class delete process only if it is actually created.The value of SC_OBJ will be None if the storage class is not created.
Fixes #4404 
=> Fix test_create_storageclass_with_same_name to initiate SC delete only if it is created

ocs_ci/framework/pytest_customization/marks.py, tests/conftest.py, tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
This PR resolves #2969, resolves #3981 and include following changes: 
-  Update node_restart_teardown fixture in conftest.py
- Enhance test_rwo_pvc_fencing_unfencing.py for internal and external mode
- Support relevant and skip irrelevant tests in external mode
- Skip irrelevant tests when nodes are tainted
- Remove skip for add node in vSphere
- Other minor updates
=> Enhancements for pv_services/test_rwo_pvc_fencing_unfencing.py

ocs_ci/ocs/node.py, ocs_ci/ocs/resources/pod.py, tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
Creating a new test to automate [BZ-1861021](https://bugzilla.redhat.com/show_bug.cgi?id=1861021). 
The test checks the rook ceph pods status after a node failure event - the pods should be in a "Running" or "Completed" state.
=> Check rook ceph pods status after a node failure event

ocs_ci/utility/aws.py
This PR should fix following issue, when there are multiple buckets for one cluster as visible from following log, but the deletion is skipped (because it expect only one bucket).
```
13:53:13 - MainThread - /home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/ocs_ci/utility/aws.py - INFO - Found buckets: ['nb.1618218687702.apps.fbalak-aws.qe.rh-ocs.com', 'nb.1618225114521.apps.fbalak-aws.qe.rh-ocs.com', 'nb.1618407891258.apps.fbalak-aws.qe.rh-ocs.com', 'nb.1618474410587.apps.fbalak-aws.qe.rh-ocs.com', 'nb.1618566480071.apps.fbalak-aws.qe.rh-ocs.com', 'nb.1619699741758.apps.fbalak-aws.qe.rh-ocs.com', 'nb.1619790281615.apps.fbalak-aws.qe.rh-ocs.com', 'nb.1620213703129.apps.fbalak-aws.qe.rh-ocs.com', 'nb.1620813394439.apps.fbalak-aws.qe.rh-ocs.com', …
```
=> fix delete_cluster_buckets function

ocs_ci/helpers/helpers.py, ocs_ci/ocs/resources/pvc.py, tests/manage/pv_services/test_expansion_snapshot_clone.py
Added RBD thick provision verification in the test test_expansion_snapshot_clone. This is done by verifying the used size of rbd image.
Added a function to get default thick provision storage class.
Added thick provision storage class name as constants.
Added a function to get image name.
Added bugzilla marker to relevant tests.
=> Add RBD thick provision verification in test

ocs_ci/helpers/disruption_helpers.py, ocs_ci/helpers/helpers.py, tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
Test case to verify that rbd provisioner leader pod deletion will not break thick provisioning. This test case will delete RBD provisioner leader pod while creating a PVC using thick provision enabled storage class and ensure that the provisioning will succeed.
=> Testcase-Verify rbd provisioner pod deletion will not break thick provisioning

conf/deployment/aws/upi_1az_rhcos_3m_3w_disconnected.yaml, conf/deployment/aws/upi_1az_rhcos_3m_3w_proxy.yaml, conf/deployment/aws/upi_3az_rhcos_3m_3w_disconnected.yaml, conf/deployment/aws/upi_3az_rhcos_3m_3w_proxy.yaml, conf/ocsci/aws_upi_flexy_rhcos_3m_3w_disconnected.yaml, conf/ocsci/aws_upi_flexy_rhcos_3m_3w_proxy.yaml, ocs_ci/deployment/flexy.py, ocs_ci/framework/conf/default_config.yaml
Some of the existing parameters wasn't properly considered for flexy deployment (for example `master_instance_type`, `worker_instance_type`, `master_replicas`, `worker_replicas`, `availability_zone_count`) and they have to be specifically configured in `FLEXY` section.
=> Flexy deployment: use common configuration parameters

tests/manage/pv_services/test_rbd_thick_provisioning.py
The test case
tests/manage/pv_services/test_rbd_thick_provisioning.py::TestRbdThickProvisioning::test_rbd_thick_provisioning
is failing due to timeout while creating the PVC.
The PVC is not reaching Bound state within the given time of 150 seconds. This error is also seen in another test run.
From csi-provisioner logs of csi-rbdplugin-provisioner pod it is observed that the provisioning took more than 150 seconds. So the timeout is increased to 300 seconds. 
Fixes #4426 
=> Increase PVC creation timeout in test test_rbd_thick_provisioning

tests/manage/pv_services/test_pv_creation.py
If the test case test_pv_creation is skipped due to degraded cluster, teardown will execute and try to delete the PVC and yaml file which is not actually present. Temporary yaml file will be present only if the test case is executed. 
Fixes #4403 
=> Fix test case test_pv_creation to skip PVC and yaml file deletion based on its existence

conf/README.md, conf/ocsci/enable_huge_pages.yaml, docs/usecases/enable_huge_pages.md, ocs_ci/deployment/deployment.py, ocs_ci/ocs/constants.py, ocs_ci/templates/ocp-deployment/huge_pages.yaml, ocs_ci/utility/utils.py
=> Add function to enable huge pages

ocs_ci/utility/aws.py
Remove s3 bucket with name like `CLUSTER_NAME-XXXXXXXX` (e.g. `jnk-pr4435-b893-06150613`).
=> aws: update delete_cluster_buckets

ocs_ci/ocs/must_gather/must_gather.py
Add patterns to `compare_running_pods` function
this function compare running pods list on openshift-storage project to "/pods" subdirectories
#4375
=> Add patterns to must-gather test

ocs_ci/templates/workloads/fio/workload_io_fillup.yaml
this is to resolve problem which cause to data not present in restored from snapshot PVC
=> Adding fsync in the end to fio command

conf/README.md, ocs_ci/deployment/disconnected.py, ocs_ci/deployment/helpers/lso_helpers.py
When LSO is used on unreleased OCP version, we need to prepare optional-operators for the disconnected installation.
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/4448
=> Prepare optional-operators for installation on disconnected cluster

ocs_ci/deployment/vmware.py, ocs_ci/ocs/exceptions.py, ocs_ci/utility/aws.py, ocs_ci/utility/ipam.py
This PR will lift the limitation of deploying single cluster in vSphere IPI. Below are important changes with this PR
1. Lifted the limitation of deploying 1 cluster, with this PR we can deploy n number of clusters based on our VMware resources
2. Dynamic creation and deletion of DNS records
3. Dynamic allocation and releasing of IP's
4. Changed base domain to qe.rh-ocs.com
5. vSphere IPI is deployed with the same cluster name as we passed as parameter to ocs-ci
Important commits with this PR:
d55e00e87fdf1abec4562ccd176051ef2ce39a79 : Adding IPAM module
ca65de0e4861a9084e7b7f8dd466dd82608ee339 : fetching hosted zone ID and record sets for domain in aws
b9bb4fb96c68b72704c9f031391b1dd4f3c45f05 : Assigning IPs in IPAM server and creating DNS records in aws …
=> Dynamic installation of vSphere IPI cluster

ocs_ci/utility/utils.py
Need to fix the "skipif_ui" decorator, return None if key does not exist [expected KeyError]
#4458
=> fix "skipif_ui" decorator

tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
Skip the test test_delete_provisioner_pod_while_thick_provisioning if OCS version is below 4.8. RBD thick provision feature is not present in OCS versions below 4.8.
=> Skip RBD thick test if OCS version is below 4.8

ocs_ci/deployment/vmware.py
fixes: https://github.com/red-hat-storage/ocs-ci/issues/4503
=> Fix OCP 4.6 installation on vSphere: use main.tf for updating gateway

ocs_ci/deployment/vmware.py
See also https://github.com/red-hat-storage/ocs-ci/pull/4506 and https://github.com/red-hat-storage/ocs-ci/issues/4503
=> Fix OCP 4.6 installation on vSphere: use main.tf for updating gateway - branch release-4.6

ocs_ci/deployment/vmware.py
=> Fix OCP 4.6 installation on vSphere: use main.tf for updating gateway - branch release-4.7

tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
Fixes: #4507 
Test will now use a helper function to get the default Ceph block pool instead of using constant value.
=> Fix test_delete_provisioner_pod_while_thick_provisioning failure on external mode

tests/manage/pv_services/test_delete_plugin_pod.py
The test case verifies that I/O will not be impacted by deletion of rbd-plugin pod.
OCS-2550 - FT-CephFS-Verify the impact of cephfs-plugin pod deletion on app pod
OCS-2551 - FT-RBD-Verify the impact of rbd-plugin pod deletion on app pod
=> Test case to verify the impact of plugin pod deletion on app pod

ocs_ci/ocs/resources/storage_cluster.py
Skip rbd-thick storage class verification in external mode until the bug [1978542](https://bugzilla.redhat.com/show_bug.cgi?id=1978542) gets fixed
=> Skip rbd-thick storage class verification in external mode

ocs_ci/helpers/helpers.py, tests/manage/pv_services/test_verify_thick_pvc_utilization.py
Test to verify storage utilization of RBD thick provisioned PVC
OCS-2537 - FT-Verify storage utilization of RBD thick provisioned PVC
Modified ocs_ci.helpers.helpers.fetch_used_size to fix #4349
=> Test to verify storage utilization of RBD thick provisioned PVC
