ocs_ci/ocs/node.py
=> wait for all nodes to create in vSphere IPI deployment

ocs_ci/framework/conf/ocp_version/ocp-4.10-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-minus1-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.11-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
=> Update ACM channel to 2.5

ocs_ci/ocs/cluster.py
=> Remove first fail from sampler as there is a fail with sampler timeout

ocs_ci/ocs/resources/pod.py
=> Find leader csi-provisioner pods using log messages

ocs_ci/ocs/ui/views.py
=> Fix UI deployment ODF4.11 on Azure

ocs_ci/helpers/helpers.py, tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py, tests/e2e/scale/test_pv_scale_ocs_create_delete_pvcs.py
Adding the option to handle nested lists in the creation of PVCs.
Fixes: #6268 
=> Scale - wait for resource is getting a list of nested PVC list instead of PVC obj list. 

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/helpers_ui.py, ocs_ci/ocs/ui/views.py
=> UI deployment + UI Add capacity on GCP

ocs_ci/utility/localstorage.py
=> Get LSO channel fix

ocs_ci/ocs/must_gather/const_must_gather.py
=> Remove 'odf-csi-addons-operator.yaml' file from 4.11 Must-Gather

conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml, conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml, ocs_ci/utility/ibmcloud.py
=> Add IBM cloud stage configs

tests/ecosystem/upgrade/test_upgrade_ocp.py
=> Fix issue with upgrade OCP and specific image

ocs_ci/ocs/pgsql.py, ocs_ci/utility/utils.py
some minor correction to the code 
=> Fix PGSQL parse logs and validate run

tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
This PR fix some issues in the PVC snapshot TC.
* Don't deploy ElasticSearch server if it is defined already.
* replacing the Nginx image with the Perf image so, no FIO installation is needed.
* reuse of existing code
The changes reduce the memory consumption and the running time of the test.
=> pvc_snapshot TC Improvements

tests/ecosystem/upgrade/test_upgrade_ocp.py
=> SKip ceph health check after OCP upgrade in MCG Only deployment

ocs_ci/utility/rosa.py
=> add subnet_ids to provider when set

ocs_ci/ocs/cluster.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/pod.py, ocs_ci/utility/utils.py, ocs_ci/utility/workloads/fio.py, tests/lvmo/test_lvm_alerts.py
new test case:
1. test different capacity alerts
2. verify topolvm metrics vs actual size query from node os
3. fix https://github.com/red-hat-storage/ocs-ci/issues/6254
=> Test topolvm alerts - thin pool capacity

ocs_ci/ocs/constants.py, ocs_ci/ocs/ocp.py, ocs_ci/templates/app-pods/raw_block_pod.yaml, ocs_ci/utility/version.py, tests/manage/pv_services/test_pvc_assign_pod_node.py, tests/manage/pv_services/test_raw_block_pv.py
=> Update namespace and app pod config to comply with podsecurity profiles

ocs_ci/framework/conf/ocp_version/ocp-4.11-ga-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.11-ga-minus1-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.11-ga-upgrade.yaml
=> Adding OCP 4.11 GA config files

ocs_ci/deployment/vmware.py, ocs_ci/ocs/platform_nodes.py, ocs_ci/utility/utils.py
=> get terraform ignition provider for adding nodes

ocs_ci/utility/utils.py
=> remove selinux_permissions for RHEL nodes

ocs_ci/ocs/ocp.py
=> get running OCP version while creating new project

tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
=> fix the collection of deletion performance

conf/ocsci/enable_ovn_network.yaml, ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2, ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2, ocs_ci/templates/ocp-deployment/install-config-azure-ipi.yaml.j2, ocs_ci/templates/ocp-deployment/install-config-baremetal-upi.yaml.j2, ocs_ci/templates/ocp-deployment/install-config-gcp-ipi.yaml.j2, ocs_ci/templates/ocp-deployment/install-config-rhv-ipi.yaml.j2
=> Enable OVN network

ocs_ci/utility/kms.py
=> raise exception for KMS deployments if encryption is not enabled

ocs_ci/framework/conf/default_config.yaml
Rosa relase page is update with latest version as 1.2.6
https://github.com/openshift/rosa/releases
=> Update rosa cli version to 1.2.6

ocs_ci/utility/nfs_utils.py, tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
@Rakshith-R @nixpanic @BlaineEXE @msainiRedhat
=> Added automation tests for happy path validations for nfs feature testing

ocs_ci/deployment/deployment.py, ocs_ci/ocs/cluster.py, ocs_ci/ocs/resources/storage_cluster.py
bug: https://bugzilla.redhat.com/show_bug.cgi?id=2075422
=> skip mcg-operator check for ODF 4.10 live deployment

tests/lvmo/test_lvm_clone_bigger_than_disk.py
=> Test lvm clone when clone is bigger than one disk

ocs_ci/ocs/resources/pod.py
=> remove unused OCP object from verify_pods_upgraded

ocs_ci/utility/rosa.py
Quick Fixes ODFMS-262 using existing byo-vpc 
Default exiting byo-vpc will be used for cluster creation. 
Default subnet configuration can be overwritten with config parameter subnet_ids or  vpc_name
ex:
ENV_DATA:
subnet_ids: subnet-123xyz1,subnet-subnet-123xyz2,subnet-subnet-123xyz3
or 
ENV_DATA:
vpc_name: qe-am-triage
=> Quick fix for addon based deployment using byo-vpc ODFMS-262

conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml, conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
=> Modifying qe provider addons storage cluster default configuration to 4 T

ocs_ci/framework/conf/ocs_version/ocs-4.12.yaml
=> installation of ODF 4.12 to stable builds

ocs_ci/deployment/terraform.py
function to change the terraform statefile which is needed for node replacement
=> function to change the terraform statefile

tests/conftest.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/5397
=> Skip PagerDuty integration when there is no CephCluster available

tests/manage/pv_services/test_rbd_image_metadata.py
covers : https://bugzilla.redhat.com/show_bug.cgi?id=2099965
=> Test if RBD images have metadata being set 

ocs_ci/framework/__init__.py, ocs_ci/framework/pytest_customization/marks.py, ocs_ci/ocs/cluster.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/managedservice.py, tests/managed-service/test_ms_markers.py
fix https://github.com/red-hat-storage/ocs-ci/issues/6162
=> Modify the Managed service markers to use the default cluster context

ocs_ci/helpers/dr_helpers.py, ocs_ci/helpers/helpers.py, ocs_ci/ocs/dr/dr_workload.py, tests/conftest.py
Improve resource leftover detection on managed cluster and added resource cleanup helper method to cleanup the resources to avoid further test failures.
=> [RDR] Improve resource leftover detection on managed cluster and cleanup

ocs_ci/deployment/helpers/lso_helpers.py, ocs_ci/helpers/disruption_helpers.py, ocs_ci/helpers/helpers.py, ocs_ci/ocs/node.py, ocs_ci/ocs/ocp.py, ocs_ci/ocs/resources/pod.py, ocs_ci/ocs/resources/storage_cluster.py, ocs_ci/templates/app-pods/performance_block.yaml, tests/conftest.py, tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py, tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py, tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py, tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
Fixes: #6364 
Fixes included in the PR:
- Update oc debug commands to run in `openshift-storage` namespace
- Update fio for rbd workload
=> Fix issues related to pod security admission 

ocs_ci/ocs/couchbase.py, ocs_ci/ocs/pillowfight.py, tests/conftest.py
=> Added the flexibilty to skip waiting for the workload to complete to all workload fixtures

ocs_ci/ocs/node.py, ocs_ci/ocs/platform_nodes.py
=> Add the step of terminating the VM in the node replacement UPI steps

ocs_ci/ocs/resources/storage_cluster.py
=> Add consumer's capacity check

ocs_ci/utility/reporting.py
Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2124418
=> set must gather tag to v4.11.0 for ODF 4.11 GA'ed versions

ocs_ci/ocs/cluster.py, tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Fix to https://github.com/red-hat-storage/ocs-ci/issues/6306 and https://github.com/red-hat-storage/ocs-ci/issues/5609
=> Increasing re balance timeout and retrying  to get PDB's post node drain

ocs_ci/ocs/constants.py
=> squad for nfs feature

ocs_ci/ocs/managedservice.py, ocs_ci/ocs/resources/storage_cluster.py
=> Add wait for managedocs components to get ready

ocs_ci/deployment/deployment.py, ocs_ci/ocs/utils.py
=> Add label to NS openshift-storage for PodSecurity admission

ocs_ci/ocs/osd_operations.py
=> Fix disk replacement test

ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
=> update RHCOS template for OCP 4.12

ocs_ci/ocs/utils.py, tests/ecosystem/upgrade/test_upgrade_ocp.py
W/A for BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=2124593
=> Fix OCP 4.12 upgrade

ocs_ci/ocs/must_gather/const_must_gather.py
=> Added must-gather on ODF4.12

tests/ui/test_validation_ui.py
=> Added marker polarion_id for TestUserInterfaceValidation

tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py, tests/manage/pv_services/test_verify_rwo_using_dc_pod.py, tests/manage/pv_services/test_verify_rwo_using_multiple_pods.py
=> Update cephfs RWO PVC tests for ODF 4.12

tests/e2e/scale/upgrade/test_upgrade_with_scaled_obc.py
=> skip test_scale_obc  pre and post upgrade tests in managed service

tests/ui/test_validation_ui.py
=> Added Polarion-ID,UI storage_system

tests/manage/mcg/test_object_versioning.py
https://bugzilla.redhat.com/show_bug.cgi?id=2111544#c13 
=> Test object versioning with parallel ops

ocs_ci/deployment/baremetal.py
=> Add 4.12 Images for BareMetal Deployment

ocs_ci/ocs/constants.py, ocs_ci/ocs/ui/base_ui.py
=> Fix login UI function

tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
=> Revert  changes made in PR 6420

ocs_ci/ocs/node.py, ocs_ci/utility/utils.py
adapted 1 reference to that function accordingly
fix [6324](https://github.com/red-hat-storage/ocs-ci/issues/6324) 
=> fix function convert_device_size 

ocs_ci/ocs/exceptions.py, ocs_ci/ocs/resources/pod.py, ocs_ci/utility/lvmo_utils.py, tests/lvmo/test_lvm_alerts.py
=> Add lvm cluster health check

ocs_ci/helpers/performance_lib.py, tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py, tests/e2e/performance/csi_tests/test_pod_attachtime.py, tests/e2e/performance/csi_tests/test_pod_reattachtime.py
This PR fixes pod_attach_csi_time function so that bulk_pod_attach_time test will have a correct calculation of bulk attach time. 
=> fixing pod_attach_csi_time function

ocs_ci/framework/conf/default_config.yaml
=> Defaulting ocs-ci to ODF 4.12

ocs_ci/deployment/baremetal.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/ocp.py
=> Use Different namespace for debug for Baremetal Deployment

ocs_ci/ocs/ui/helpers_ui.py, ocs_ci/ocs/ui/views.py
=> Add capacity on ODF4.12 via UI

ocs_ci/deployment/aws.py, ocs_ci/ocs/ui/base_ui.py
=> Set AWS SC to gp2-csi from 4.12

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
=> Polarion ID on Flexible Scaling

ocs_ci/ocs/constants.py
=> Fix test_validate_ceph_config_values_in_rook_config_override for ODF 4.10

ocs_ci/helpers/sanity_helpers.py
=> Increasing timeout for cluster health check

ocs_ci/ocs/ui/deployment_ui.py, ocs_ci/ocs/ui/views.py
https://bugzilla.redhat.com/show_bug.cgi?id=2124379
=> UI deployment on 4.12

ocs_ci/deployment/helpers/lso_helpers.py
=> Add securityAdmissions for Localstorage

ocs_ci/ocs/constants.py
- fixes https://github.com/red-hat-storage/ocs-ci/issues/6494
=> Disconnected deployment: add required packages for OCP/ODF 4.12

ocs_ci/ocs/bucket_utils.py, ocs_ci/ocs/constants.py, ocs_ci/templates/app-pods/fedoraServiceCA.yaml, ocs_ci/templates/app-pods/fedora_with_linuxtar_files.yaml, tests/conftest.py, tests/e2e/performance/mcg/test_list_objects.py, tests/e2e/scale/noobaa/test_list_objects.py
=> <GSS Closed Loop BZ: 2052079> To list whole objects without any failures

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/views.py
=> Fix UI GCP 4.12 SC for deployment

ocs_ci/ocs/ocp.py
=> Fix get resource for node status

tests/manage/mcg/test_object_expiration.py, tests/manage/mcg/test_s3_routes.py
Validates  2067079 2063691
Added bz marker for 2029298 in object expiration test.
=> Closed loop 2067079 2063691: Test s3 routes update/reconcile

setup.py
=> update cryptography to 38.0.1

ocs_ci/ocs/ocs_upgrade.py
=> Increase timeout for mon pods to upgrade

conf/deployment/rosa/managed_1az_consumer_dev_3m_3w_m52x.yaml, conf/deployment/rosa/managed_1az_consumer_dev_3m_3w_m54x.yaml, conf/deployment/rosa/managed_1az_provider_dev_3m_3w_m54x.yaml, conf/deployment/rosa/managed_3az_consumer_dev_3m_3w_m52x.yaml, conf/deployment/rosa/managed_3az_consumer_dev_3m_3w_m54x.yaml, conf/deployment/rosa/managed_3az_provider_dev_3m_3w_m54x.yaml
=> Add dev addon config files

ocs_ci/utility/prometheus.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/6462
=> Use TimeoutIterator to fix too many failed Prometheus requests after upgrade

tests/e2e/workloads/ocp/logging/test_openshift-logging.py
=> Fix logging test skip condition

tests/manage/z_cluster/test_ceph_default_values_check.py
As the bug fix available only in 4.9
https://bugzilla.redhat.com/show_bug.cgi?id=2012930
=> Skip test <4.9 ocs version

ocs_ci/helpers/managed_services.py, ocs_ci/ocs/resources/storage_cluster.py
Verify topology in Managed Services Provider cluster
1. Verify replica count
2. Verify total size
3. Verify OSD size
4. Verify OSD running worker nodes count
5. Verify worker node instance type
6. Verify OSD count
7. Verify OSD cpu
8. Verify machine pools
9. Verify OSD running nodes are part of the correct machinepool
10. Verify that other pods are not running on OSD nodes
=> Verify topology in MS

ocs_ci/helpers/managed_services.py, ocs_ci/ocs/resources/storage_cluster.py
Update topology check in Managed Services Provider cluster.
* Perform the check for dev addon only.
* Address comments from the initial PR #6516
=> Update topology check in MS

ocs_ci/framework/pytest_customization/ocscilib.py
=> Collect OCP must-gather for all cluster expansion test

ocs_ci/deployment/deployment.py
=> Fix network split setup for arbiter deployment

ocs_ci/ocs/resources/namespacestore.py
=> Respect the amount parameter that's passed in a namespacestore's dictionary

tests/manage/mcg/test_s3_routes.py
=> closed loop 1954708: Validate noobaa disableLoadBalancerService

ocs_ci/ocs/cosbench.py
=> switch to default namespace before deleting cosbench namespace

ocs_ci/ocs/resources/bucket_policy.py, tests/manage/mcg/test_bucket_policy.py
=> Bucket policy fixes

ocs_ci/ocs/constants.py, ocs_ci/utility/deployment_openshift_logging.py, ocs_ci/utility/uninstall_openshift_logging.py, tests/conftest.py
=> Enhancements for openshift-logging

ocs_ci/helpers/managed_services.py
Update the OSD CPU request  and limit in the topology verification of Managed Services provider cluster.
=> Update OSD cpu in MS topology check

conf/ocsci/skip_dr_deploy.yaml, ocs_ci/deployment/deployment.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/ui/acm_ui.py, ocs_ci/ocs/ui/views.py, ocs_ci/templates/ocs-deployment/multicluster/dr_policy_acm_hub.yaml, ocs_ci/utility/utils.py
=> changes for : ACM 2.5 and odf4.11

ocs_ci/deployment/aws.py, ocs_ci/framework/conf/default_config.yaml
=> adding heterogeneous variable for AWS UPI deployments

ocs_ci/ocs/ui/deployment_ui.py
=> Fix UI LSO deployment for 4.12

ocs_ci/utility/utils.py
=> Fix rhel UPI deployment

ocs_ci/ocs/bucket_utils.py, tests/manage/mcg/test_cached_buckets.py
Addresses:
1. Test cached bucket mechanism between cache & hub bucket when we use `s3 cp` command to download objects
2. Test cached bucket mechanism between cache & hub bucket when we use `s3 sync` command to download objects
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2024107#c3 
=> Test MCG cached buckets

ocs_ci/helpers/helpers.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/ocp.py, ocs_ci/templates/lvmo-deployment/lvm-cluster-default.yaml, ocs_ci/utility/lvmo_utils.py, tests/lvmo/conftest.py, tests/lvmo/test_lvm_manual_diskpath.py
- Infrastructure for manual path selection in lvmcluster CR
- test manual path selection
=> LVMO - Manual disk path

ocs_ci/utility/pagerduty.py, ocs_ci/utility/workloadfixture.py, tests/conftest.py, tests/manage/monitoring/conftest.py, tests/manage/monitoring/pagerduty/test_ceph.py, tests/manage/monitoring/pagerduty/test_deployment_status.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/6455
=> Filter PagerDuty incidents based on a service

ocs_ci/ocs/ui/validation_ui.py, ocs_ci/ocs/ui/views.py
=> Locator changes based upon ODF version

ocs_ci/ocs/resources/objectbucket.py
=> Update the OBC replication schema

conf/deployment/ibmcloud/ipi_3az_rhcos_3m_3w.yaml, ocs_ci/deployment/deployment.py, ocs_ci/deployment/factory.py, ocs_ci/deployment/ibmcloud.py, ocs_ci/deployment/ocp.py, ocs_ci/framework/conf/default_config.yaml, ocs_ci/ocs/exceptions.py, ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
Jira: https://issues.redhat.com/browse/OCSQE-768
=> Add IBM Cloud IPI Deployment support

ocs_ci/templates/lvmo-deployment/lvm-cluster-411.yaml, ocs_ci/templates/lvmo-deployment/lvm-cluster-412.yaml
fix [6458](https://github.com/red-hat-storage/ocs-ci/issues/6458)
=> updated lvmcluster name to be aligned with dev configuration

setup.py
=> Pin google-auth-oauthlib to specific version

ocs_ci/cleanup/vsphere/cleanup.py
=> supporting vSphere IPI cleanup

ocs_ci/deployment/flexy.py
add retry to rsync (and related) command for backup flexy work dir to NFS share
=> add retry to post flexy backup commands

ocs_ci/ocs/utils.py
=> Increase MG timeout for ODF4.11 and above

ocs_ci/deployment/rosa.py
=> Fix patching the consumer toolbox with MS consumer deployment

ocs_ci/deployment/baremetal.py, ocs_ci/deployment/deployment.py, ocs_ci/deployment/helpers/lso_helpers.py, ocs_ci/ocs/ui/deployment_ui.py, ocs_ci/utility/utils.py, tests/ecosystem/upgrade/test_upgrade_ocp.py
=> Remove WA BZ-2124379 [PodSecurity admission]

tests/conftest.py
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2138917
This is to avoid expected issues in teardown described in bug above.
=> Allow re-try for check ceph health after add_capacity_test

ocs_ci/framework/pytest_customization/ocscilib.py
=> Collect OCP must-gather logs for node related tests

ocs_ci/ocs/resources/storage_cluster.py
=> Fix AWS LSO verification on devicesets

ocs_ci/ocs/resources/storage_cluster.py
=> Adjust the number of alertmanager pods

ocs_ci/ocs/resources/mcg.py
=> Update the bucketclass CLI creation to support the replication schema of ODF >= 4.12

ocs_ci/ocs/resources/rgw.py, tests/manage/rgw/test_obc_quota.py
=> Ext rgw test fixes

ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.13-upgrade.yaml
=> Adding OCP 4.13 config files

ocs_ci/ocs/utils.py, tests/conftest.py
This PR intends to collect conatiner rpm package information during ocs collect logs phase which can be used to verify CVE bugs.
=> PR to collect container rpm package details during ocs collect logs phase

ocs_ci/cleanup/vsphere/cleanup.py
Issue: UPI flow is not deleting routes from AWS
=> fix for vsphere cleanup for UPI

ocs_ci/ocs/utils.py
=> remove tini from multus tool box

ocs_ci/helpers/helpers.py, tests/manage/pv_services/test_overprovision_level_policy_control.py
=> Fix test_overprovision_level_policy_control

ocs_ci/deployment/deployment.py, ocs_ci/ocs/resources/pvc.py, tests/conftest.py
=> Fix wrong condition that cause clone_yaml to be None

ocs_ci/utility/lvmo_utils.py
Sometimes lvmcluster created, but its status not yet appears in its description.
=> added exception for lvmcluster status not exist right after its creation

ocs_ci/ocs/ocp.py
=> Fix test case error when SC is marked as default

tests/manage/monitoring/prometheus/test_deployment_status.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/6657
=> skip test_ceph_mons_quorum_lost if ocs version is <4.9

tests/ui/test_pv_encryption_ui.py
=> Skip PV Encryption UI test for all versions except OCS 4.8

ocs_ci/ocs/resources/storage_cluster.py
=> include Loader in yaml.load function

conf/ocsci/multus_public_network_interface_412_vsphere.yaml
=> multus public interface config file for OCP 4.12

ocs_ci/deployment/baremetal.py
=> Make baremetal debug namespace as privileged

conf/deployment/aws/ipi_3az_rhcos_3m_6w_arbiter.yaml, ocs_ci/deployment/aws.py, ocs_ci/deployment/helpers/lso_helpers.py, ocs_ci/ocs/exceptions.py, ocs_ci/utility/aws.py
=> Add arbiter deployment over 6 worker nodes in AWS

ocs_ci/templates/ocp-deployment/install-config-rhv-ipi.yaml.j2
=> Update machine CIDR and take it from config

ocs_ci/ocs/resources/namespacestore.py
=> Increase namespacestore verify_health timeout to 180s

conf/deployment/aws/ipi_1az_rhcos_3m_3w_thales.yaml
=> Add a production config for thales kms on aws

ocs_ci/helpers/helpers.py, tests/e2e/kcs/test_noobaadb_pw_reset.py
=> Test case to verify noobaa db pw reset

ocs_ci/helpers/helpers.py, ocs_ci/ocs/constants.py, ocs_ci/templates/security/scc.yaml, tests/conftest.py, tests/manage/z_cluster/test_custom_scc.py
https://bugzilla.redhat.com/show_bug.cgi?id=1938647
OCS deployments were getting affected when custom scc were created. This PR is to test the same.
=> Test OCS deployments/pods with creation of custom SCC

ocs_ci/ocs/resources/storage_cluster.py
Epic https://issues.redhat.com/browse/ODFMS-198
=> Add managedocs security checks

ocs_ci/ocs/resources/pod.py
Signed-off-by: Daniel Osypenko <dosypenk@redhat.com>
=> review fix

tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
=> skip test_crashcollector_pod_existence_on_ceph_pods_running_nodes on baremetal

conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_3w_external_vault_v1_with_namespace.yaml, conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_3w_external_vault_v2_with_namespace.yaml
=> Add vsphere ipi vault external namespace configs

docs/getting_started.md
=> Fix Installation Doc because Numpy issue

ocs_ci/utility/reporting.py
=> set tag to v4.y instaed of v4.y.0 for GA'ed versions

tests/conftest.py
Fixes: #6653
Signed-off-by: sagihirshfeld <shirshfe@redhat.com>
=> Fix the mcg-cli command in the mcg_account_factory fixture

ocs_ci/deployment/helpers/lso_helpers.py
=> relax the exact PVs verification for BM platform

tests/manage/pv_services/test_rbd_image_metadata.py
=> Check metadata for rbd images created during the test only

ocs_ci/ocs/ui/views.py
=> Update XPath for resize value in UI

ocs_ci/utility/prometheus.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/6807
Signed-off-by: fbalak <fbalak@redhat.com>
=> Use different login method only for managed ibm cluster

tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Improve the non ocs taint and toleration testing #6531
=> Test taint toleration

ocs_ci/ocs/jenkins.py
=> Add resource type for oc describe command

tests/manage/pv_services/test_pvc_delete_subvolumegroup.py
Test PVC in 'bound' state after SubvolumeGroup deletion
=> BZ #2124469 automation

tox.ini
=> fix tox issue

ocs_ci/framework/conf/ocs_version/ocs-4.13.yaml, ocs_ci/framework/main.py
=> Adding ODF 4.13 config files

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/validation_ui.py
Fixes BZ #2096513
Signed-off-by: Daniel Osypenko <dosypenk@redhat.com>
=> Added BlockPools tabs count verification to cover BZ #2096513

tests/e2e/workloads/ocp/logging/test_openshift-logging.py
=> Removing skip version 4.12

tests/e2e/system_test/test_mcg_replication_with_disruptions.py, tests/manage/mcg/test_admission_control.py
=> Fixes #6870 and bz marker

tests/e2e/workloads/app/test_jenkins_simulation.py
This test added to exist test for reuse of pvc and pod creation
Signed-off-by: Yosi Ben Shimon <yosibsh@gmail.com>
=> BZ #2096395 automation.

ocs_ci/helpers/dr_helpers.py
Dummy image workaround is removed from 4.12 through [bug 2132359](https://bugzilla.redhat.com/show_bug.cgi?id=2132359).
Update helper methods to not expect dummy images in 4.12 and above.
Also fixes: #6630 
=> [RDR] Update mirroring status related helper methods to check correct replaying image count

ocs_ci/ocs/dr/dr_workload.py
=> Include Deployment resource kind to be removed during DR workload cleanup

.github/CODEOWNERS, ocs_ci/framework/pytest_customization/marks.py, ocs_ci/ocs/constants.py, pytest.ini
=> Turquoise squad for RDR test cases

tests/e2e/workloads/app/couchbase/test_couchbase.py, tests/e2e/workloads/app/couchbase/test_couchbase_node_drain.py, tests/e2e/workloads/app/couchbase/test_couchbase_node_reboot.py, tests/e2e/workloads/app/couchbase/test_couchbase_pod_respin.py
=> Skip couchbase workload tests on OCP version >= 4.12

ocs_ci/ocs/constants.py, tests/manage/z_cluster/test_ceph_default_values_check.py
=> Fix test_validate_ceph_config_values_in_rook_config_override for ODF 4.12

tests/manage/z_cluster/test_delete_rook_ceph_mon_pod.py
Fixes: #6831
Added skip annotation for external mode deployments
=> added skip annotation for external mode deployments

tests/manage/pv_services/test_overprovision_level_policy_control.py
https://bugzilla.redhat.com/show_bug.cgi?id=2158277
Fixes [#6491](https://github.com/red-hat-storage/ocs-ci/issues/6491)
=> Fix test_over_provision_level_policy_control on ODF4.10 because bz-2158277

ocs_ci/ocs/node.py
=> wait for all nodes to create in IBM Cloud IPI

ocs_ci/deployment/deployment.py, ocs_ci/ocs/cluster.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/pvc.py, ocs_ci/templates/CSI/lvm/volume-snapshot-lvms.yaml, ocs_ci/templates/lvmo-deployment/lvms-bundle.yaml, ocs_ci/templates/lvmo-deployment/lvms-cluster.yaml, ocs_ci/utility/lvmo_utils.py, tests/conftest.py, tests/lvmo/test_lvm_manual_diskpath.py
Signed-off-by: paraggit <pakamble@redhat.com>
=> config changes required after renaming operator name lvmo to lvms.

ocs_ci/ocs/constants.py, ocs_ci/ocs/defaults.py, ocs_ci/templates/CSI/rbd/csi-kms-connection-details-kmip.yaml, ocs_ci/templates/CSI/rbd/thales-kmip-csi-secret.yaml, ocs_ci/utility/kms.py, tests/conftest.py, tests/manage/pv_services/pv_encryption/test_kmip_rbd_pv_encryption.py
PV encryption test using Ciphertrust as KMS
https://issues.redhat.com/browse/RHSTOR-2179
=> Add test for PV encryption using Ciphertrust

tests/conftest.py
=> Donot fail teardown incase of KMS cleanup failures

tests/ui/test_quickstarts.py
=> Adding black squad for test_quickstarts

ocs_ci/framework/conf/default_config.yaml
=> update rosa version

ocs_ci/helpers/managed_services.py
Update Managed Services provider topology verification.
=> Update MS provider topology verification

ocs_ci/deployment/vmware.py
=> comment senstive variable in destroy cluster

ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-minus1-config.yaml
=> Add OCP 4.12-ga files

ocs_ci/utility/rosa.py, ocs_ci/utility/utils.py
Increasing timeout and ignoring return code
will help in resolving error in ocs-ci due to
https://github.com/openshift/rosa/issues/1024
=> Increase timeout to rosa version command

ocs_ci/utility/rosa.py
=> Enable subnet ids from config parameter for appliance mode provider

conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_external_vault_v1_with_namespace.yaml
=> add VAULT_CA_ONLY to the external_vault_v1_with_namespace config

ocs_ci/framework/conf/default_config.yaml, ocs_ci/utility/rosa.py
Signed-off-by: fbalak <fbalak@redhat.com>
=> Add billing model paramater to rosa install addon command

conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_3w_external_vault_v1_with_namespace.yaml, conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_3w_external_vault_v2_with_namespace.yaml, conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_external_vault_v2_with_namespace.yaml
=> add VAULT_CA_ONLY parameter to external vault config files

ocs_ci/deployment/deployment.py
=> Don't create custom catalog in UI live deployment

ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-minus1-config.yaml
=> use GA'ed RHCOS template for OCP 4.12 GA'ed version

ocs_ci/ocs/resources/storage_cluster.py
Verify provider topology for dev-addon in MS. The topology change is currently present in dev addon only
=> Verify provider topology for dev-addon

tests/manage/pv_services/pv_encryption/test_vault_namespace_override_using_tenant_configmap.py
=> Skip test on disconnected/proxy clusters

ocs_ci/ocs/must_gather/const_must_gather.py
=> Delete noobaa-scc-describe.txt from mg list

ocs_ci/ocs/resources/storage_cluster.py
=> Add retry for OSD schema validation in post upgrade

tests/manage/monitoring/prometheus/test_noobaa.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/6979
Signed-off-by: fbalak <fbalak@redhat.com>
=> Update markers of NooBaa alerting tests

ocs_ci/ocs/resources/storage_cluster.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/7009
Signed-off-by: fbalak <fbalak@redhat.com>
=> Fix local variable reference in post deployment check

tests/e2e/workloads/app/quay/test_quay_operator.py
1. Failing tests due to nooba core would need time to reconnect to db and endpoint and the background workers after respin.
2. Added @retry for multiple try of commands to avoid failures.
3. issue- https://github.com/red-hat-storage/ocs-ci/issues/7017 
=> fix for Quay workload

tests/manage/z_cluster/upgrade/test_check_pdb_post_upgrade.py
=> Fix #6726 skip test_check_mon_pdb_post_upgrade on MS-consumers

conf/README.md, ocs_ci/deployment/deployment.py, ocs_ci/deployment/helpers/external_cluster_helpers.py, ocs_ci/ocs/exceptions.py, ocs_ci/ocs/ocs_upgrade.py
=> Add option for SSH key in external cluster deployment

conf/examples/acm_hub_unreleased_image.yaml, ocs_ci/framework/conf/default_config.yaml
=> Update ACM to latest image

ocs_ci/deployment/helpers/external_cluster_helpers.py, ocs_ci/deployment/vmware.py
=> delete rbd images from external RHCS cluster after cluster teardown

setup.py
=> Update project version to 4.12

ocs_ci/ocs/utils.py
=> Increase must gather timeout on ODF4.10

docs/release_guidelines.md
=> Add documentation around release branches

conf/ocsci/collect_memory_usage.yaml
=> Added collect_memory_usage.yaml

ocs_ci/deployment/baremetal.py, ocs_ci/utility/aws.py
=> Create BareMetal cluster with user provided cluster_name

tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py, tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
=> Skip ceph daemon tests on external mode

tests/conftest.py
=> Increase timeout for PVC clone

ocs_ci/helpers/dr_helpers.py, ocs_ci/ocs/constants.py
=> [RDR] Updated failover procedure to include the WA for Bug 2007376

ocs_ci/framework/conf/default_config.yaml, setup.py
=> Defaulting ocs-ci to ODF 4.13

ocs_ci/ocs/bucket_utils.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/exceptions.py, ocs_ci/ocs/resources/backingstore.py, ocs_ci/ocs/resources/pod.py, ocs_ci/templates/mcg/scale-cli-service-ca-configmap.yaml, ocs_ci/templates/mcg/scalecli_pod.yaml, tests/conftest.py, tests/e2e/scale/noobaa/test_list_objects.py
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=2110504 
Fixes #6876 
=> Bug 2110504 List large number of objects with prefix and delimeter

ocs_ci/framework/conf/default_config.yaml, ocs_ci/helpers/managed_services.py
=> Update osd cpu and memory check in MS

ocs_ci/utility/utils.py
=> Fixing mem table issue which was failing to send email reports

ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
=> updated RHCOS template for 4.12

tests/e2e/workloads/app/test_jenkins_simulation.py
=> Validation for BZ-2132270

conf/deployment/rosa/custom_primary_cidr_config.yaml, conf/deployment/rosa/custom_secondary_cidr1_config.yaml, conf/deployment/rosa/custom_secondary_cidr2_config.yaml, conf/deployment/rosa/private_link_deployment.yaml, ocs_ci/deployment/rosa.py, ocs_ci/utility/rosa.py
=> Enable multi-cidr deployment using config

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/deployment_ui.py
=> Fix LSO UI deployment

ocs_ci/deployment/vmware.py, ocs_ci/utility/load_balancer.py
=> remove RHCOS compute IP's from load balancer in RHEL deployments

ocs_ci/helpers/managed_services.py, ocs_ci/ocs/resources/storage_cluster.py
Verify the OSDs per zone in Managed Services Provider cluster.
Fixes #7105 - Update osd deployer version check to match with the current version format 
Signed-off-by: Jilju Joy [jijoy@redhat.com](mailto:jijoy@redhat.com)
=> Verify osd distribution on provider

tests/manage/pv_services/test_pvc_assign_pod_node.py
=> PR for verification of bug 2136852 

ocs_ci/ocs/machine.py, ocs_ci/ocs/scale_lib.py, ocs_ci/templates/openshift-infra/machineset-azure.yaml
Update Azure machineset yaml and libraries for scale tests
=> Update Azure machineset yaml and libraries for scale tests

tests/ecosystem/upgrade/test_logging_upgrade.py
issue- https://github.com/red-hat-storage/ocs-ci/issues/6610
=> Skiping the logging upgrade testcase due to changes in upgrade process

tests/manage/pv_services/test_pvc_assign_pod_node.py
=> Verify OCS version in test test_pvc_assign_pod_node

tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py
Fix Teardown issue in Scale Pod OOM Kill tc
=> Fix teardown issue in Scale POD OOM KILL Test case

tests/ecosystem/upgrade/test_logging_upgrade.py
issue- https://github.com/red-hat-storage/ocs-ci/issues/6610
=> Skiping the logging upgrade tyestcase due to changes in upgrade process

ocs_ci/helpers/managed_services.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/7152
=> Fix verify_provider_topology

ocs_ci/deployment/vmware.py
Related BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=2169779
=> Change to thin-csi from OCP 4.13

ocs_ci/templates/ocp-deployment/install-config-vsphere-upi.yaml.j2
=> Add cluster to install config for vsphere UPI

ocs_ci/ocs/constants.py
* add required packages for ODF 4.13 disconnected deployment
=> Changes for disconnected ODF 4.13 deployment

ocs_ci/ocs/node.py
=> Fix test_nodereplacement_proactive by waiting for node deletion on AWS

ocs_ci/deployment/rosa.py
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/7175
=> do not fail MS destroy job for non-existing cluster

tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py
Update the test "test_rolling_terminate_and_recovery" for MS and non-MS clusters:
- Generate nodes for a provider cluster using the function 'generate_nodes_for_provider_worker_node_tests' if it's a provider cluster. 
- Wait for the new worker node to be ready
- Label the new worker node in case of a non-MS cluster
=> Update the test "test_rolling_terminate_and_recovery" for MS and non-MS clusters

ocs_ci/utility/memory.py
extracted unrelated changes from #7178
=> Removed log of ZombieProcess and NoSuchProcess exceptions

ocs_ci/helpers/helpers.py, tests/manage/monitoring/prometheus/test_deployment_status.py, tests/manage/monitoring/prometheus/test_prometheus_rules.py
https://bugzilla.redhat.com/show_bug.cgi?id=2142763
=> BZ-2142763 Prometheus File

ocs_ci/ocs/platform_nodes.py
=> Rename restart_nodes_teardown with restart_nodes_by_stop_and_start_teardown for BM

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/mcg_ui.py, ocs_ci/ocs/ui/views.py, tests/manage/mcg/ui/test_mcg_ui.py
Verifies scenario from BZ #[2097772]
Steps to Verify:
1. Go to Object Bucket Claims and Create a OBC.
2. Navigate to Object Buckets tab. After clicking on delete the Object Bucket, it asks for confirmation. Click delete to confirm.
3. Three dots options which provides option for deletion gets disabled and hoverMessage 'The corresponding ObjectBucketClaim must be deleted first.' is shown.
=> Try remove Object Bucket before OBC Test Case

ocs_ci/ocs/longevity.py, tests/e2e/longevity/test_stage0.py
=> Longevity stage0 fix

tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
=> Skip test for external mode (#7174)

ocs_ci/ocs/node.py
=> Fix test_nodereplacement_proactive by waiting for node deletion (#7145)

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/mcg_ui.py, ocs_ci/ocs/ui/views.py, tests/manage/mcg/ui/test_mcg_ui.py
cherry-pick from https://github.com/red-hat-storage/ocs-ci/pull/7111
=> test_obc_creation_and_deletion fix. cherry-pick 412

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/mcg_ui.py, ocs_ci/ocs/ui/views.py, tests/manage/mcg/ui/test_mcg_ui.py
cherry-pick from https://github.com/red-hat-storage/ocs-ci/pull/7111
=> Test_obc_creation_and_deletion fix. cherry-pick 411

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/mcg_ui.py, ocs_ci/ocs/ui/views.py, tests/manage/mcg/ui/test_mcg_ui.py
cherry-pick from https://github.com/red-hat-storage/ocs-ci/pull/7111
=> Test_obc_creation_and_deletion fix. cherry-pick 49

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/mcg_ui.py, ocs_ci/ocs/ui/views.py, tests/manage/mcg/ui/test_mcg_ui.py
cherry-pick from https://github.com/red-hat-storage/ocs-ci/pull/7111
=> Test_obc_creation_and_deletion fix. cherry-pick 48

ocs_ci/ocs/resources/backingstore.py
Limit of the error handling in `Backingstore.py::delete` only to when we intend to retry the deletion after the first failed attempt.
Fixes: #7250
=> Modify `Backingstore.py::delete` so it raises deletion errors if retrying is disabled

ocs_ci/helpers/helpers.py
fix https://github.com/red-hat-storage/ocs-ci/issues/7234.
In the pr, I fixed the following:
- In the function `wait_for_ct_pod_recovery`, catch the "AssertionError" if the rook-ceph-tool pod is not ready yet
- Replace the function `wait_for_resource_count_change` with the method `wait_for_resource` in the `ocs_ci/ocs/ocp.py` file
=> In the function 'wait_for_ct_pod_recovery' catch the 'AssertionError' if the rook-ceph-tool pod is not ready yet

ocs_ci/ocs/resources/packagemanifest.py
=> remove unused variable selector

ocs_ci/deployment/baremetal.py
=> Fail the run if BM cluster has lock

ocs_ci/ocs/utils.py
=> fix pg_dump command for nbcore

ocs_ci/helpers/helpers.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/warp.py, ocs_ci/templates/workloads/warp/warp_service.yaml, tests/e2e/conftest.py, tests/e2e/kcs/test_noobaa_db_backup_and_recovery.py
Covers,
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2141035
KCS to MCG DB backup and recovery: https://access.redhat.com/solutions/6686081
=> Automate KCS (https://access.redhat.com/solutions/6686081) and Bug 2141035

ocs_ci/ocs/ui/add_replace_device_ui.py, ocs_ci/ocs/ui/base_ui.py
fixes #7090
added parameter to ocs_ci/ocs/ui/base_ui.py::do_click() to refresh page if page is stale
add_capacity_ui now uses avoid_stale=True
=> add avoid_stale to do_click

ocs_ci/deployment/baremetal.py
- Improve disk cleanup
- reduce multiple debug 
- remove unused code for lmv cleanup
Fixes: #7377
=> Improve Disk Cleanup for Bare Metal 

ocs_ci/ocs/ui/mcg_ui.py, ocs_ci/ocs/ui/views.py, tests/manage/mcg/ui/test_mcg_ui.py
added support for ODF 4.13
added support to verify OBC-RGW creation - BZ [2175685](https://bugzilla.redhat.com/show_bug.cgi?id=2175685)
=> Tc try remove object bucket 4.13

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/mcg_ui.py, ocs_ci/ocs/ui/views.py, tests/manage/mcg/ui/test_mcg_ui.py
cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/7134
=> Tc try remove object bucket UI 412

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/mcg_ui.py, ocs_ci/ocs/ui/views.py, tests/manage/mcg/ui/test_mcg_ui.py
cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/7134
adjust test for ODF 4.11
=> Tc try remove object bucket UI 411

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/mcg_ui.py, ocs_ci/ocs/ui/views.py, tests/manage/mcg/ui/test_mcg_ui.py
cherry-pick from https://github.com/red-hat-storage/ocs-ci/pull/7134
Fixes: #7249
=> Tc try remove object bucket UI 410

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/mcg_ui.py, ocs_ci/ocs/ui/views.py, tests/manage/mcg/ui/test_mcg_ui.py
cherry-pick from https://github.com/red-hat-storage/ocs-ci/pull/7134
=> Tc try remove object bucket UI 49

tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py
fix https://github.com/red-hat-storage/ocs-ci/issues/7208
=> Adjust test rolling nodes terminate for provider release412

ocs_ci/deployment/helpers/external_cluster_helpers.py
Ticket:
https://issues.redhat.com/browse/OCSQE-913
=> Use specific RGW endpoint from zone for MDR deployment

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Release 4.9 cherry pick pr #7137
=> Release 4.9 cherry pick pr 7137

tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Release 4.9 cherry pick pr #6987
=> Release 4.9 cherry pick pr 6987

tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py, tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
Backport PR #7202 to release-4.9
=> Backport PR 7202 to release-4.9

ocs_ci/ocs/constants.py
- related to: https://issues.redhat.com/browse/ONEOCPDEPL-210
=> change FLEXY_IMAGE_URL to images.paas.redhat.com

tests/e2e/workloads/app/test_jenkins_simulation.py
Fix for https://github.com/red-hat-storage/ocs-ci/issues/7384
=> Fix the testcase test_git_clone

ocs_ci/framework/conf/ocp_version/ocp-4.14-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.14-upgrade.yaml
=> Adding OCP 4.14 config files

tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Release 4.9 cherry pick pr #7194
=> Release 4.9 cherry pick pr 7194

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Release 4.12 cherry pick pr #7190
=> Release 4.12 cherry pick pr 7190

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Release 4.11 cherry pick pr #7190
=> Release 4.11 cherry pick pr 7190

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Release 4.10 cherry pick pr #7190
=> Release 4.10 cherry pick pr 7190

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Release 4.9 cherry pick pr #7190
=> Release 4.9 cherry pick pr 7190

tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Release 4.10 cherry pick pr #7194
=> Release 4.10 cherry pick pr 7194

tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Release 4.11 cherry pick pr #7194
=> Release 4.11 cherry pick pr 7194

tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Release 4.12 cherry pick pr #7194
=> Release 4.12 cherry pick pr 7194

ocs_ci/framework/conf/ocs_version/ocs-4.13.yaml
=> use latest-stable tag for ODF 4.13 version

ocs_ci/deployment/helpers/vsphere_helpers.py, ocs_ci/deployment/terraform.py, ocs_ci/deployment/vmware.py, ocs_ci/framework/conf/default_config.yaml, ocs_ci/ocs/constants.py
=> Use v4scaleup for rhel - vSphere

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Release 4.10 cherry pick pr #7137
=> Release 4.10 cherry pick pr 7137

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Release 4.11 cherry pick pr #7137
=> Release 4.11 cherry pick pr 7137

tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Release 4.12 cherry pick pr #7137
=> Release 4.12 cherry pick pr 7137

tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Release 4.12 cherry pick pr #6987
=> Release 4.12 cherry pick pr 6987

tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Release 4.11 cherry pick pr #6987
=> Release 4.11 cherry pick pr 6987

tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py, tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
Release 4.12 cherry pick pr #7202
=> Release 4.12 cherry pick pr 7202

tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py, tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
Release 4.11 cherry pick pr #7202
=> Release 4.11 cherry pick pr 7202

tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py, tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
Release 4.10 cherry pick pr #7202
=> Release 4.10 cherry pick pr 7202

ocs_ci/utility/utils.py, tests/conftest.py
It's causing the issues to fail IBM Cloud deployment
=> Fix deployment for IBM ROKS

ocs_ci/utility/rosa.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/7472
=> Use --replicas flag

.dockerignore, Docker_files/Containerfile.ci, Docker_files/ocsci_container/scripts/run-managed-service.sh
This PR allow us to build the tests images in a more optimized matter.
Note: The image is still very big, that is because of the azure package, which with a lot of legacy code, there is an issue about this opened in there repo, https://github.com/Azure/azure-sdk-for-python/issues/17801
=> Add Multi-Stage build Containerfile

ocs_ci/ocs/rados_utils.py
backward support https://github.com/red-hat-storage/ocs-ci/pull/7275
=> increase-num-dups-411

ocs_ci/ocs/rados_utils.py
backward support https://github.com/red-hat-storage/ocs-ci/pull/7275
=> increase-num-dups-49

ocs_ci/ocs/rados_utils.py
=> increase-num-dups-412

tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
Add the `cluster_type` param to the node restart MS tests. 
See more details in the Jira issue https://issues.redhat.com/browse/ODFMS-400.
=> Add the 'cluster_type' param to the nodes restart MS tests

ocs_ci/deployment/vmware.py
=> Handle deleting rbd images during teardown for deployment failure scenario

ocs_ci/templates/ocp-deployment/install-config-vsphere-upi.yaml.j2
=> Add cluster to installconfig for vSphere UPI

ocs_ci/framework/conf/default_config.yaml
=> Use rhel 8.7 for RHEL deployments

ocs_ci/helpers/helpers.py, ocs_ci/ocs/cluster.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/resources/pod.py, ocs_ci/utility/vsphere.py, tests/manage/pv_services/test_cephfs_with_mds_network_failure.py
Test scenario automated from the BZ: 2130925.
Test MDS crash by causing network interruption to the standby-replay daemon.
=> Test Automation: CephFS Testing under MDS Pod Network Failure Scenarios for BZ 2130925

tests/managed-service/test_storageclassclaim.py
Fixes #7368
Fixed the position of log as well.
=> Fix test_verify_storageclassclaim

ocs_ci/deployment/vmware.py
=> change default sc to thin-ci in vsphere for release branch 4.12

ocs_ci/ocs/resources/storage_cluster.py
Verify defult storageclass claims in MS consumer if ODF version is 4.11 or higher.
=> Verify defult storageclassclaims in MS consumer

ocs_ci/ocs/constants.py, ocs_ci/utility/monitoring_tool.py, ocs_ci/utility/utils.py, tests/internal/conftest.py, tests/internal/test_monitoring_tool.py
Test OCS-4844 steps:
1. clone ODF monitoring tool from [https://url.corp.redhat.com/odf-monitoring-tools ](https://url.corp.redhat.com/odf-monitoring-tools%C2%A0) 
2. clone upstream and downstream versions of prometheus rules files
3. run 'comparealerts' against downstream and upstream prometheus rules YAML files
4. run 'comparealerts' against two identical prometheus rules YAML files, check no "No diffs found"
5. replace alert name in one of identical prometheus rules YAML file, run 'comparealerts' and verify deviations found
6. convert two prometheus rules files with deviation to JSON and verify deviations found
7. run 'comparealerts' against two identical prometheus rules JSON files, check "No diffs found"
=> test covers the new feature Alert improvements Follow-ups

ocs_ci/framework/pytest_customization/marks.py
Thanks to Elena catch - fixing the broken logic now. All older branches updated and PR's on review.
=> fix broken logic

ocs_ci/helpers/managed_services.py, ocs_ci/ocs/constants.py
Functions to verify storageclient and storageclassclaims. Applicable for Managed Services clusters.
=> Functions to verify storageclient and storageclassclaims

conf/ocsci/custom_config.yaml, ocs_ci/ocs/constants.py, ocs_ci/utility/nfs_utils.py, tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
=> Updated nfs tests to fix failures

tests/e2e/scale/upgrade/test_upgrade_with_scaled_obc.py, tests/e2e/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py, tests/ecosystem/upgrade/test_upgrade_ocp.py, tests/manage/z_cluster/nodes/test_node_replacement_proactive.py, tests/manage/z_cluster/upgrade/test_check_pdb_post_upgrade.py
Tagged tests with squads.
Issue: https://github.com/red-hat-storage/ocs-ci/issues/7324
=> Tagged the tests to squads

ocs_ci/framework/main.py
Issue: When we run n+1 OCP version with ODF n version, SC was initialized before loading of OCP version.
Fixes: #7549 
=> Load ocp version in the main module.

ocs_ci/deployment/flexy.py, ocs_ci/deployment/vmware.py, ocs_ci/helpers/disconnected.py, ocs_ci/ocs/dr/dr_workload.py
=> use explicit parameters in clone_repo

ocs_ci/helpers/managed_services.py, ocs_ci/ocs/constants.py
Function to verify the status of pods in managed-fusion namespace.
=> Function to verify the status of pods in managed-fusion namespace

ocs_ci/ocs/jenkins.py
=> Fix jenkins workload on OCP4.13

ocs_ci/ocs/node.py
=> Verify all nodes are created for MS incaseof pull secret update

ocs_ci/ocs/fiojob.py
=> get correct pool name for external mode in fiojob

tests/manage/z_cluster/test_delete_osd_deployment.py
=> Increased timeout to wait for new osd deployment to come up

tests/ui/test_validation_ui.py
WONTFIX https://bugzilla.redhat.com/show_bug.cgi?id=2189623
=> update test_odf_cephblockpool_compression_status with skip for 4.10

ocs_ci/ocs/rados_utils.py
backward support https://github.com/red-hat-storage/ocs-ci/pull/7275
=> increase-num-dups

ocs_ci/ocs/bucket_utils.py
=> Increase the timeout of `wait_for_pv_backingstore` by a minute

ocs_ci/ocs/bucket_utils.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/exceptions.py, ocs_ci/ocs/resources/backingstore.py, ocs_ci/ocs/resources/pod.py, ocs_ci/templates/mcg/scale-cli-service-ca-configmap.yaml, ocs_ci/templates/mcg/scalecli_pod.yaml, tests/conftest.py, tests/e2e/scale/noobaa/test_list_objects.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/7447
=> [Release-4.11 cherry pick] PR6499 and PR7066

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/mcg_ui.py, tests/manage/mcg/ui/test_mcg_ui.py
FIX: https://github.com/red-hat-storage/ocs-ci/issues/7509
FIX: https://github.com/red-hat-storage/ocs-ci/issues/7486
=> fix storage class for external cluster, improve page_has_loaded

ocs_ci/deployment/deployment.py, ocs_ci/ocs/resources/storage_cluster.py
=> move in-transit verification to ocs_install_verification

ocs_ci/ocs/exceptions.py, ocs_ci/ocs/node.py, ocs_ci/ocs/platform_nodes.py, ocs_ci/utility/csr.py, tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Fixes :#7172
Fixes: #7390 
Fixes: #6724 
Fixes: #1821
=> Fixing node replacement issue in vSphere platform

ocs_ci/helpers/managed_services.py
Add one more verification: 
Verify that the ocs-metrics-exporter pod is Running.
=> Update verify faas provider resources

ocs_ci/deployment/fusion_aas.py, ocs_ci/ocs/fusion.py, ocs_ci/templates/fusion-aas/operatorgroup.yaml
Update OperatorGroup yaml and label namespaces for FaaS installation.
=> Update OperatorGroup yaml and label namespaces for FaaS installation

ocs_ci/ocs/exceptions.py, ocs_ci/utility/azure_utils.py
Terraform file name has changed since newer version and thus this fix will iterate over the names of file and pick the right one.
=> Fixes bug of Terraform file name

ocs_ci/ocs/ui/base_ui.py
=> Fix UI deployment ODF4.13 on Vsphere

ocs_ci/deployment/fusion_aas.py
Increase wait time to check machineconfigpool before updating pull secret.
=> Increase wait time to check machineconfigpool before updating pull secret

ocs_ci/helpers/helpers.py, ocs_ci/helpers/managed_services.py, ocs_ci/helpers/performance_lib.py, ocs_ci/ocs/uninstall.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/7606
=> Get rid of hardcoded namespace

conf/README.md, ocs_ci/framework/conf/default_config.yaml, ocs_ci/ocs/acm/acm.py, ocs_ci/templates/acm-deployment/auto-import-secret.yaml, ocs_ci/templates/acm-deployment/managed-cluster.yaml, tests/ecosystem/deployment/test_acm.py
Manual procedure:
https://url.corp.redhat.com/91f0590
=> [DR] Import cluster via CLI

ocs_ci/utility/azure_utils.py, setup.py, tests/ecosystem/deployment/test_deployment.py
Adds a check for  Azure Storage Property 'allowBlobPublicAccess': 'False'  
Jira: https://issues.redhat.com/browse/OCSQE-947
=> Issue ocsqe947

tests/manage/pv_services/pvc_resize/test_pod_deletion_during_pvc_expansion.py
bz - https://bugzilla.redhat.com/show_bug.cgi?id=2164617
=> [GSS]Unable to expand ocs-storagecluster-ceph-rbd PVCs provisioned in Filesystem mode

ocs_ci/deployment/helpers/external_cluster_helpers.py
=> check error from external script

ocs_ci/deployment/helpers/external_cluster_helpers.py, ocs_ci/ocs/resources/storage_cluster.py
=> use realm in external script

ocs_ci/ocs/pgsql.py
https://github.com/red-hat-storage/ocs-ci/issues/6922
Testcase failing in teardown because of ResourceLeftoversException. PVs are not deleted and are in released state.
=> Validate pv deletion in teardown (#7266)

ocs_ci/deployment/vmware.py
=> catch exception during teardown when toolbox is in bad shape

ocs_ci/ocs/constants.py, tests/conftest.py
Ignore must-gather-helper in environment check.
=> Release 4.9 cherry pick pr 7539

ocs_ci/framework/pytest_customization/marks.py, tests/conftest.py, tests/manage/z_cluster/cluster_expansion/test_add_capacity.py, tests/ui/test_add_capacity_ui.py
=> Allow ceph health re-try for specific test cases

ocs_ci/helpers/managed_services.py, ocs_ci/ocs/utils.py, tests/conftest.py
Create tools pod on consumer cluster in FaaS configuration.
=> Create tools pod on FaaS consumer

tests/manage/mcg/test_mcg_resources_disruptions.py
=> Disregard the users array of noobaa-db SCC at test_db_scc

ocs_ci/helpers/helpers.py, ocs_ci/ocs/benchmark_operator_fio.py, ocs_ci/ocs/quay_operator.py, ocs_ci/ocs/ui/deployment_ui.py
=> pass parameter to TimeoutExpiredError exception

tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
=> Skip test_automated_recovery_from_stopped_node_and_start for IBM Cloud platform

tests/e2e/workloads/app/test_jenkins_simulation.py
Fix https://github.com/red-hat-storage/ocs-ci/issues/7384 for 4.12
=> [Release-4.12 cherry pick] test fix up (#7385)

ocs_ci/ocs/resources/pod.py, ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/block_pool.py, ocs_ci/ocs/ui/storageclass.py, ocs_ci/ocs/ui/views.py, tests/ui/test_create_pool_block_pool.py
Updating UI functions of BlockPoolUI so that it supports ODF 4.13  
No changes are done since OCS 4.8
=> Updating functions of BlockPoolUI 

ocs_ci/ocs/node.py
fix https://github.com/red-hat-storage/ocs-ci/issues/7086
=> Adding try except block in function "wait_for_nodes_status" to ignore "CommandFailed" exception release-4.11 (#7451)

conf/README.md, ocs_ci/deployment/helpers/external_cluster_helpers.py, ocs_ci/utility/ssl_certs.py
Related to: https://url.corp.redhat.com/5479bff
Jenkins jobs related changes: https://url.corp.redhat.com/7c604db
=> Enable external mode using SSL with RGW

ocs_ci/helpers/disruption_helpers.py, ocs_ci/ocs/resources/pod.py, tests/e2e/scale/test_scale_3_OCS_worker_nodes_and_1500_PVCs.py
Added new TC to respin operator pods with scaled 1500+ PVCs and 76 PODs
Signed-off-by: Ramakrishnan [rperiyas@redhat.com](mailto:rperiyas@redhat.com)
=> Test Coverage for BZ https://bugzilla.redhat.com/show_bug.cgi?id=2092737

ocs_ci/ocs/resources/storageclassclaim.py, tests/managed-service/test_storageclassclaim.py
Fix the check for storageclassclaims in test_verify_storageclassclaim.
Addionally, updated the function that creates storageclassclaim to support the new changes.
Fixes #7699
=> Fix the check for storageclassclaims in test_verify_storageclassclaim

ocs_ci/utility/ibmcloud.py
=> ibmcloud fix node_restart

ocs_ci/ocs/constants.py, ocs_ci/ocs/machine.py, ocs_ci/ocs/scale_lib.py, ocs_ci/templates/openshift-infra/machineset-ibm-cloud.yaml
PR to add IBM machineset yaml and to scale nodes in IBM IPI platform
=> IBM Cloud machineset yaml support

ocs_ci/utility/ibmcloud.py
* Fixes: #7281
Signed-off-by: Gayathri M <Gayathri.M@ibm.com>
(cherry picked from commit 0f5b40896ec11a5911eec519a72834caa86f47b5)
=> ibmcloud fix node_restart (#7612)

ocs_ci/deployment/deployment.py, ocs_ci/deployment/helpers/external_cluster_helpers.py
=> Enable in-transit encryption for external mode deployment

tests/manage/z_cluster/nodes/test_nodes_restart.py
=> In the test "test_rolling_nodes_restart" add retry decorator when creating resources 

ocs_ci/ocs/rados_utils.py, ocs_ci/ocs/resources/pod.py, ocs_ci/utility/utils.py, tests/conftest.py
Cherry picked the fix for, https://github.com/red-hat-storage/ocs-ci/pull/7140 to release-4.12 branch.
=> Fix test_ceph_pg_log_dups_trim. Replace oc cp calls (Updated) (#7178)

ocs_ci/ocs/resources/storage_cluster.py
=> fix patch cmd to enable in-transit encryption

ocs_ci/ocs/constants.py
=> Adding green squad for encryption feature

ocs_ci/ocs/fusion.py, ocs_ci/templates/fusion-aas/managedfusionoffering-dfc.yaml.j2, ocs_ci/templates/fusion-aas/managedfusionoffering.yaml.j2
Update ManagedFusionOffering template and remove storageclassclaim CRD workaround. These are the changes to suppport latest builds of agent.
=> Update ManagedFusionOffering template and remove storageclassclaim CRD workaround

ocs_ci/deployment/deployment.py
Get ImageContentSourcePolicy file from catalog image (if present) and apply it on the cluster.
=> get and apply ICPS from catalog image

ocs_ci/helpers/managed_services.py
Fix the verification of usableCapacityInTiB in FaaS provider cluster.
Fixes #7758
=> Fix the verification of usableCapacityInTiB

ocs_ci/deployment/deployment.py
* get and apply ICPS from catalog image
* run get_and_aply_icsp_from_catalog in create_catalog_source(..)
=> get and apply ICPS from catalog image - backport to 4.12

ocs_ci/deployment/deployment.py
* get and apply ICPS from catalog image
* run get_and_aply_icsp_from_catalog in create_catalog_source(..)
=> get and apply ICPS from catalog image - backport to 4.10

ocs_ci/deployment/deployment.py
* get and apply ICPS from catalog image
* run get_and_aply_icsp_from_catalog in create_catalog_source(..)
=> get and apply ICPS from catalog image - backport to 4.9

ocs_ci/deployment/deployment.py
* get and apply ICPS from catalog image
* run get_and_aply_icsp_from_catalog in create_catalog_source(..)
=> get and apply ICPS from catalog image - backport to 4.8

tests/manage/monitoring/conftest.py, tests/manage/monitoring/prometheus/test_capacity.py, tests/manage/monitoring/sendgrid/test_capacity.py
- Fixes https://github.com/red-hat-storage/ocs-ci/issues/7751
=> Increase capacity of utilization tests

ocs_ci/ocs/fusion.py
Create ImageContentSourcePolicy in FaaS consumer only when "not_ga_wa" is True.
=> Create ICSP only if non GA

ocs_ci/deployment/deployment.py
=> Fix issue with applying ICSP for upgrade scenario

ocs_ci/ocs/quay_operator.py
=> Added flexibility to pull desired channel for Quay operator deployment

ocs_ci/ocs/jenkins.py, ocs_ci/templates/workloads/jenkins/buildconfig.yaml
=> Jenkins Workload, change the image

ocs_ci/ocs/cosbench.py, tests/e2e/workloads/app/cosbench/test_cosbench.py
=> Fixes:7468

tests/manage/rgw/test_obc_quota.py
=> Add wait to avoid race condition in test_obc_quota

ocs_ci/utility/vsphere_nodes.py
=> supporting IPI for ntp update

conf/ocsci/external_rhcs_cluster.yaml
=> Remove rbdpool from rhcs external config file

tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
Fixes: #6794
Addresses the changes that were introduced in https://github.com/noobaa/noobaa-core/pull/6998
=> `test_mcg_namespace_lifecycle_crd`: Add allow policies to bucket for the new user

ocs_ci/ocs/ui/base_ui.py
Fix for test_odf_cephblockpool_compression_status and test_odf_storagesystems_ui
=> fix for failing tests

ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml
=> update RHCOS template for 4.13

ocs_ci/framework/pytest_customization/ocscilib.py
=> Don't collect must gather twice for deployment

ocs_ci/ocs/must_gather/const_must_gather.py
fixes https://github.com/red-hat-storage/ocs-ci/issues/7831
=> added exclude for noobaa-db-pg-0-init.log

tests/e2e/workloads/app/amq/test_rgw_kafka_notifications.py
Skipping this test due to BZ https://bugzilla.redhat.com/show_bug.cgi?id=2209616
=> Skipping test on 4.13 due to bz2209616

ocs_ci/framework/conf/default_config.yaml, ocs_ci/utility/reporting.py
=> Use old must gather live image when installing pre 4.13 versions

ocs_ci/deployment/deployment.py
=> use insecure for disconnected environment

ocs_ci/framework/conf/ocs_version/ocs-4.14.yaml
=> use stable build for ODF 4.14

ocs_ci/deployment/vmware.py
=> gather bootstrap logs when deployment failed with TimeoutExpired exception

tests/e2e/workloads/ocp/registry/test_registry_shutdown_and_recovery_node.py
Fix for https://github.com/red-hat-storage/ocs-ci/issues/7418
=> Fix test_registry_shutdown_and_recovery_node failure

tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
=> Support test_non_ocs_taint_and_tolerations for external mode

ocs_ci/ocs/constants.py, ocs_ci/utility/environment_check.py, tests/libtest/test_skip_labeled_leftover.py, tests/managed-service/test_pod_disruptions.py
See more details here https://github.com/red-hat-storage/ocs-ci/pull/7710#issue-1731113243.
=> Enhance the `ignore_leftover_label` to support labels other than app for release-4.12 (#7710)

ocs_ci/ocs/constants.py, ocs_ci/utility/environment_check.py, tests/libtest/test_skip_labeled_leftover.py, tests/managed-service/test_pod_disruptions.py
See more details here https://github.com/red-hat-storage/ocs-ci/pull/7710#issue-1731113243.
=> Enhance the ignore_leftover_label to support labels other than app for release-4.11 (#7710)

ocs_ci/ocs/constants.py, tests/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py
Test to verify failure of node hosting pods of different components in Regional-DR solution
=> RDR node failure tests

tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
Removed skip markers in 12 node scale test
=> Remove Skip marker in 12 node Scale Test

conf/ocsci/multicluster_mode_mdr.yaml, ocs_ci/helpers/dr_helpers.py, tests/conftest.py
Update to the orignal values as per the PR [7430](https://github.com/red-hat-storage/ocs-ci/pull/7430)
=> Update the multicluster_mode_mdr.yaml

ocs_ci/ocs/ui/block_pool.py, ocs_ci/ocs/ui/views.py, tests/conftest.py, tests/manage/storageclass/test_creation_and_deletion_of_sc_and_rbdpool.py, tests/ui/test_creation_and_deletion_of_sc_and_rbdpool.py
This contains test automation for
OCS-3885: https://polarion.engineering.redhat.com/polarion/redirect/project/OpenShiftContainerStorage/workitem/question_mark/id=OCS-3885
OCS-3886: https://polarion.engineering.redhat.com/polarion/redirect/project/OpenShiftContainerStorage/workitem/question_mark/id=OCS-3886
=> Adding test automation for OCS-3885 and OCS-3886

tests/conftest.py, tests/manage/mcg/test_bucket_creation.py
=> skip test_bucket_creation[3-S3-DEFAULT-BACKINGSTORE]

ocs_ci/ocs/ui/base_ui.py
remove redundant screenshot on login, improve logging and login_ui method
PR to help trace issues, save test-run time and make login_ui more stable
=> login_ui minor improvements

ocs_ci/ocs/ui/views.py
new locator for delete button - fixed
=> add additional locator to confirm delete action

ocs_ci/helpers/managed_services.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/7910
=> Increase wait for storageclassclaim

tests/manage/mcg/test_s3_routes.py
=> Patch ocs-storagecluster instead the NooBaa CR at `test_disable_nb_lb`

ocs_ci/deployment/deployment.py, ocs_ci/ocs/defaults.py
=> remove fusion catalog source

ocs_ci/ocs/constants.py, ocs_ci/utility/environment_check.py, tests/libtest/test_skip_labeled_leftover.py, tests/managed-service/test_pod_disruptions.py
See more details here https://github.com/red-hat-storage/ocs-ci/pull/7710#issue-1731113243.
=> Enhance the ignore_leftover_label to support labels other than app for release-4.10 (#7710)

tests/manage/pv_services/test_overprovision_level_policy_control.py
test_over_provision_level_policy_control [BZ-2158277 Fixed] . Cherrypick PR https://github.com/red-hat-storage/ocs-ci/pull/7466
=> Release 4.10 cherry pick pr 7466

ocs_ci/ocs/constants.py
=> disconnected packages for ODF 4.14 deployment

conf/ocsci/acm_2.7.yaml, conf/ocsci/acm_2.8.yaml, conf/ocsci/acm_2.9.yaml, ocs_ci/deployment/deployment.py, ocs_ci/framework/conf/default_config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-minus1-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.14-config.yaml, ocs_ci/utility/utils.py
* Use latest image for ACM Install
=> Use latest image tag for ACM unreleased Install (#7918) Backport 4-13

ocs_ci/deployment/vmware.py
=> delete PVC's before teardown

ocs_ci/ocs/constants.py, ocs_ci/utility/nfs_utils.py, tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Cherry picked the changes, https://github.com/red-hat-storage/ocs-ci/pull/6687 to release-4.12 branch.
=> Release 4.12 cherry pick pr 6687

ocs_ci/ocs/constants.py, ocs_ci/utility/nfs_utils.py, tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Cherry picked the changes, https://github.com/red-hat-storage/ocs-ci/pull/6687 to release-4.11 branch.
=> Updated nfs tests to fix failures (#6687)

conf/deployment/aws/ipi_1az_rhcos_lso_sno.yaml, conf/deployment/aws/upi_1az_rhcos_3m_3w_disconnected.yaml, conf/deployment/aws/upi_1az_rhcos_3m_3w_proxy.yaml, conf/deployment/aws/upi_1az_rhcos_lso_3m_3w_disconnected.yaml, conf/deployment/aws/upi_3az_rhcos_3m_3w_disconnected.yaml, conf/deployment/aws/upi_3az_rhcos_3m_3w_proxy.yaml, conf/deployment/aws/upi_3az_rhcos_lso_3m_3w_disconnected.yaml
=> change instance type for disconnected deployments

ocs_ci/ocs/managedservice.py, ocs_ci/ocs/resources/pod.py, ocs_ci/utility/utils.py
In the pr, I implemented the following:
Use the function `get_ceph_tools_pod` in the utility `ceph_health_check_base`. That way, we can easily extend it for MS and FAAS clusters. Also, it will make the function `ceph_health_check_base` more generic.
Another three more small updates related to the change above:
- Update the function `get_ceph_tools_pod` to get the `namespace` param, and patch the MS consumer rook-ceph-tool deployment.
- Update the function `patch_consumer_toolbox` to get the rook-ceph-tools pod param if provided, and add a return value of the new pod object after patching the rook-ceph-tools deployment.
- Update the method `exec_ceph_cmd` to get two more additional parameters: `out_yaml_format`, `timeout`.
=> Use the function "get_ceph_tools_pod" in the utility "ceph_health_check_base" to make it more generic

tests/manage/mcg/test_pv_pool.py
covers: https://bugzilla.redhat.com/show_bug.cgi?id=2187789
=> Test if pv pool BS pod node ephemeral storage getting consumed

ocs_ci/ocs/constants.py
=> Add squad for disaster recovery

ocs_ci/ocs/acm/acm.py, ocs_ci/ocs/constants.py, ocs_ci/templates/acm-deployment/klusterlet-addon-config.yaml
=> Create klusterlet addons on managed clusters

ocs_ci/deployment/fusion.py
=> correct doc string for fusion deployment

ocs_ci/ocs/resources/storage_cluster.py
=> verify storage cluster version

ocs_ci/deployment/vmware.py
=> [4.13]: Remove pvc before teardown

ocs_ci/ocs/resources/storage_cluster.py
bug: https://bugzilla.redhat.com/show_bug.cgi?id=2222022
=> disable storage cluster version check

tests/e2e/kcs/test_disable_mcg_external_service.py
Covers:
- KCS: https://access.redhat.com/articles/6970745
- Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2186171
**Need backports?**
Yes need to be backported to release-4.13
=> Test KCS: Disabling Multicloud Object Gateway external service and make sure disableLoadBalancerService isn't reconciled

ocs_ci/ocs/exceptions.py, tests/manage/mcg/test_noobaa_prometheus.py
Covers: https://bugzilla.redhat.com/show_bug.cgi?id=2168010
**Need backports?**
Yes, need to be backported to release-4.13
=> test noobaa_bucket_used_bytes prometheus metrics

ocs_ci/ocs/ui/base_ui.py, tests/ui/test_quickstarts.py
* Update quickstart titles
* make test_quickstart_presence PASS
=> Cherry pick 412  test_quickstart_presence

ocs_ci/ocs/ui/base_ui.py, tests/ui/test_quickstarts.py
* Update quickstart titles
* make test_quickstart_presence PASS
=> Cherry pick 411  test_quickstart_presence

ocs_ci/ocs/ui/base_ui.py, tests/ui/test_quickstarts.py
* Update quickstart titles
* make test_quickstart_presence PASS
=> Cherry pick 410  test_quickstart_presence-a

tests/conftest.py
=> revert the workaround of noobaa endpoint count

ocs_ci/ocs/warp.py, tests/e2e/scale/noobaa/test_warp.py
Fixed warp test failing issue #7964
=> Added multi_client=False to the run_benchmark function of warp

tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py, tests/e2e/scale/test_pv_scale_ocs_create_delete_pvcs.py
Removed memory leak code from the test case, with memory leak function we haven't captured any issues, also due to environmen and threading it's very flaky.
=> PR to remove memory leak function

tests/ecosystem/upgrade/test_upgrade_sc_allowexpansion_false.py
=> adding squad for allowexpansion test case

ocs_ci/deployment/deployment.py
=> Fix attribute error for RDRMultiClusterDROperatorsDeploy class

ocs_ci/ocs/scale_noobaa_lib.py, tests/e2e/scale/noobaa/test_scale_obc_create_delete.py
Fixed issue #6692 
Fixed the search string for start time.
=> Fixed issue of test_scale_obc_create_delete_time

ocs_ci/ocs/constants.py, tests/disaster-recovery/mdr/conftest.py
=> run MDR tests only incase of MDR deployments

ocs_ci/deployment/deployment.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/7814
=> Fix packagemanifest timeout for acm

tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
Combined the test cases OCS-2495 and OCS-2494. The only difference was the PVC type. Now both CephFS and RBD PVC will be created in the test case OCS-2494.
Current test cases:
tests/manage/pv_services/test_del_mon_service_and_create_pvc.py::TestPvcCreationAfterDelMonService::test_pvc_creation_after_del_mon_services[CephBlockPool]
tests/manage/pv_services/test_del_mon_service_and_create_pvc.py::TestPvcCreationAfterDelMonService::test_pvc_creation_after_del_mon_services[CephFileSystem]
Combined and optimized test case:
tests/manage/pv_services/test_del_mon_service_and_create_pvc.py::TestPvcCreationAfterDelMonService::test_pvc_creation_after_del_mon_services
Reduced sleep time between mon failure from 300 seconds to 60 seconds because health check is already performed before this sleep time. …
=> Combine test cases OCS-2495 and OCS-2494 to save run time

ocs_ci/ocs/resources/mcg.py
=> correcting logging info for downloading mcg-cli

ocs_ci/ocs/resources/storage_cluster.py
=> verify maximum openshift version allowed

ocs_ci/framework/pytest_customization/marks.py, tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Cherry picked the changes of pr https://github.com/red-hat-storage/ocs-ci/pull/7873 to release-4.11 branch
=> cherry picked changes of pr 7873

ocs_ci/ocs/resources/storage_cluster.py, ocs_ci/utility/version.py
=> version check for verifying max openshift version

setup.py
=> Pin new version of webdriver_manager to 3.9.1

ocs_ci/deployment/deployment.py, ocs_ci/helpers/dr_helpers.py, ocs_ci/templates/ocs-deployment/multicluster/backupschedule.yaml
=> update backupschedule for mdr hub recovery

ocs_ci/deployment/deployment.py, ocs_ci/helpers/dr_helpers.py, ocs_ci/ocs/utils.py
=> Configuration of DRclusters to enable fencing

ocs_ci/helpers/helpers.py, tests/manage/z_cluster/nodes/test_node_replacement_proactive.py, tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
https://bugzilla.redhat.com/show_bug.cgi?id=2102304
=> GSS Automation, Remove the entry of removed node from Storagecluster under Node Topology

ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-upgrade.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-upgrade.yaml
=> Add OCP 4.12 and 4.13 GA upgrade config files

ocs_ci/helpers/helpers.py, ocs_ci/ocs/cluster_load.py, ocs_ci/ocs/constants.py, ocs_ci/templates/workloads/fio/fedora_deployment.yaml, ocs_ci/templates/workloads/fio/fio_dc.yaml, tests/conftest.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/7506
=> ClusterLoad: Replace FIO DeploymentConfig with Deployment

ocs_ci/utility/utils.py
=> use absolute path for bin directory

ocs_ci/deployment/vmware.py
=> delete custom sc backed pvc's during teardown

ocs_ci/ocs/fiojob.py, ocs_ci/ocs/ocp.py, ocs_ci/ocs/resources/objectbucket.py, ocs_ci/ocs/resources/packagemanifest.py, ocs_ci/ocs/tests/test_fiojob.py, ocs_ci/utility/utils.py
cherry-pick
https://github.com/red-hat-storage/ocs-ci/pull/8127
=> flake8 isinstance backport 4.13

ocs_ci/ocs/fiojob.py, ocs_ci/ocs/ocp.py, ocs_ci/ocs/resources/objectbucket.py, ocs_ci/ocs/resources/packagemanifest.py, ocs_ci/ocs/tests/test_fiojob.py, ocs_ci/utility/utils.py
cherry-pick
https://github.com/red-hat-storage/ocs-ci/pull/8127
=> flake8 isinstance backport 4.12

ocs_ci/ocs/fiojob.py, ocs_ci/ocs/ocp.py, ocs_ci/ocs/resources/objectbucket.py, ocs_ci/ocs/resources/packagemanifest.py, ocs_ci/ocs/tests/test_fiojob.py, ocs_ci/utility/utils.py
cherry-pick
https://github.com/red-hat-storage/ocs-ci/pull/8127
=> flake8 isinstance backport 4.11

ocs_ci/ocs/fiojob.py, ocs_ci/ocs/ocp.py, ocs_ci/ocs/resources/objectbucket.py, ocs_ci/ocs/resources/packagemanifest.py, ocs_ci/ocs/tests/test_fiojob.py, ocs_ci/utility/utils.py
cherry-pick
https://github.com/red-hat-storage/ocs-ci/pull/8127
=> flake8 isinstance backport 4.10

ocs_ci/ocs/acm/acm.py
Fixes #8010 
Signed-off-by: Sidhant Agrawal sagrawal@redhat.com
=> Fix TypeError when calling install_submariner_ui and submariner_validation_ui

tests/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py
=> Add Polarion ID for RDR node failure tests

conf/README.md, tests/manage/mcg/test_db_nfs_mount.py
https://bugzilla.redhat.com/show_bug.cgi?id=2115616
**Needs backport?**
yes release 4.13
=> test if nb db successfully initializes after nfs mount

tests/e2e/workloads/test_create_scale_pods_and_pvcs_using_kube_job.py
https://github.com/red-hat-storage/ocs-ci/issues/8158
=> skip test_create_scale_pods_and_pvcs_using_kube_job on baremetal

ocs_ci/templates/mcg/s3cli-sts.yaml, tests/conftest.py, tests/manage/mcg/test_write_to_bucket.py
=> Enable chmod +x of /test_objects of the s3cli pod

ocs_ci/ocs/rados_utils.py, ocs_ci/ocs/resources/pod.py, ocs_ci/utility/utils.py
Remove shell arg exec_cmd 4.12
=> cherry-pick remove redundant param use_shell from exec_cmd

ocs_ci/templates/mcg/s3cli-sts.yaml, tests/conftest.py
=> s3cli-sts: runAsUser 0 with image 2.0

ocs_ci/ocs/constants.py
=> [4.13]: Add squad for disaster recovery

ocs_ci/deployment/disconnected.py
if icsp is configured, the oc mirror command might fail (return non 0 rc), even though we use --continue-on-error and --skip-missing arguments (not sure if it is because of a bug in oc mirror plugin or because of some other issue), but we want to continue to try to mirror the images manually with applied the icsp rules
It looks like that the issue appears in `oc-mirror` from `release-4.12` and lower branches, but I'm going to fix/workaround it also in `master` and our `4.13` branches, to be sure.
=> ignore oc mirror command failure if icsp is used

ocs_ci/deployment/disconnected.py
if icsp is configured, the oc mirror command might fail (return non 0 rc), even though we use --continue-on-error and --skip-missing arguments (not sure if it is because of a bug in oc mirror plugin or because of some other issue), but we want to continue to try to mirror the images manually with applied the icsp rules
=> ignore oc mirror command failure if icsp is used - backport for 4.12

ocs_ci/deployment/disconnected.py
if icsp is configured, the oc mirror command might fail (return non 0 rc), even though we use --continue-on-error and --skip-missing arguments (not sure if it is because of a bug in oc mirror plugin or because of some other issue), but we want to continue to try to mirror the images manually with applied the icsp rules
It looks like that the issue appears in oc-mirror from release-4.12 and lower branches, but I'm going to fix/workaround it also in master and our 4.13 branches, to be sure.
=> ignore oc mirror command failure if icsp is used - backport for 4.13

ocs_ci/ocs/resources/mcg.py
=> Download the mcg-cli if the current binary has a different minor version than OCS

conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
=> chnage vmc7 proxy repo

conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
=> [4.13]: fix repo http proxy

conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
=> [4.12]: chnage vmc7 proxy repo

conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
=> [4.11]: chnage vmc7 proxy repo

conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
=> [4.10]: chnage vmc7 proxy repo

ocs_ci/ocs/fiojob.py
=> [4.12] -  get correct pool name for external mode in fiojob

ocs_ci/ocs/scale_noobaa_lib.py, tests/e2e/scale/noobaa/test_scale_obc_create_delete.py
* Fixed the search string for start time.
=> [Release 4.13 cherry-pick] Fixed issue of test_scale_obc_create_delete_time (#7767)

ocs_ci/utility/utils.py, tests/libtest/test_stderr_emoji_filter.py
=> Enhance exec_cmd to Include emoji filtering for stderr output

ocs_ci/ocs/resources/pod.py, tests/conftest.py, tests/manage/mcg/test_bucket_replication.py
bug: https://bugzilla.redhat.com/show_bug.cgi?id=2168788
**needs backport?**
yes release-4.13
=> Automate bug 2168788

ocs_ci/deployment/deployment.py, ocs_ci/ocs/cluster.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/exceptions.py
=> PDB verification

ocs_ci/deployment/deployment.py
=> patch correct SC when using custom storageclass

ocs_ci/ocs/bucket_utils.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/exceptions.py, ocs_ci/ocs/resources/backingstore.py, ocs_ci/ocs/resources/pod.py, ocs_ci/templates/mcg/scale-cli-service-ca-configmap.yaml, ocs_ci/templates/mcg/scalecli_pod.yaml, tests/conftest.py, tests/e2e/scale/noobaa/test_list_objects.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/7446
=> [Release-4.10 cherry pick] PR6499 and PR7066

tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py
Cherry Pick PR 7135 to branch release-4.12
=> Cherry Pick PR 7135 to branch release-4.12

tests/e2e/scale/test_cephfs_many_files.py
Cherry Pick PR 7845 to branch release-4.12
=> Cherry Pick PR 7845 to branch release-4.12

ocs_ci/ocs/machine.py, ocs_ci/ocs/scale_lib.py, ocs_ci/templates/openshift-infra/machineset-azure.yaml
Cherry-pick PR #7107  to release-4.12 branch to fix Azure machine-set issue
Fix for issue https://github.com/red-hat-storage/ocs-ci/issues/8056
=> Cherry-pick PR 7107 to release-4.12 branch to fix Azure machineset issue

tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py, tests/e2e/scale/test_pv_scale_ocs_create_delete_pvcs.py
Cherry Pick PR 7847 to branch release-4.13
=> Cherry Pick PR 7847 to branch release-4.13

tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py, tests/e2e/scale/test_pv_scale_ocs_create_delete_pvcs.py
Cherry Pick PR #7847 to branch release-4.12
=> Cherry Pick PR 7847 to branch release-4.12

tests/ecosystem/upgrade/test_upgrade_sc_allowexpansion_false.py
=> [4.13] - add marker for test upgrade sc allowexpansion false

ocs_ci/framework/conf/ocs_version/ocs-4.15.yaml, ocs_ci/framework/main.py
=> Adding ODF 4.15 config files

ocs_ci/ocs/bucket_utils.py, tests/manage/mcg/test_bucket_replication.py
=> [MCG] Assert when objects in source & target bucket don't match

.github/CODEOWNERS, tests/encryption/test_intransit_encryption_data_integrity.py, tests/encryption/test_intransit_encryption_sanity.py, tests/encryption/test_mon_failure_in_intransit_encryption.py
Adding 'green_squad' marker to encryption tests.
=> Adding 'green_squad' marker to encryption tests.

ocs_ci/utility/utils.py, tests/libtest/test_stderr_emoji_filter.py
release-4.13 backport of #8077
=> [release-4.13 backport] Enhance exec_cmd to Include emoji filtering for stderr output

ocs_ci/cleanup/vsphere/cleanup.py
=> destroy folder in templates in vsphere-cleanup script

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/block_pool.py, ocs_ci/ocs/ui/page_objects/block_pools.py, ocs_ci/ocs/ui/page_objects/edit_label_form.py, ocs_ci/ocs/ui/page_objects/page_navigator.py, ocs_ci/ocs/ui/views.py, tests/ui/test_error_improvements.py
Added new test check to the complex test test_blocking_pool_creation_rules
* Notes
1. Class EditLabelForm will be removed from base_ui.py to separate files - issue https://github.com/red-hat-storage/ocs-ci/issues/7704
2. Test has an opened bugzilla(s) 2215910 and 2193109 but passes locally, depending on randomly chosen values -> http://pastebin.test.redhat.com/1102952
=> block_pool_edit_label_check_added

tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/6794 in 4.12
=> Add allow policies to the MCG user (#7726)

ocs_ci/ocs/resources/mcg.py
release-4.13 backport of #8181
=> [release-4.13 backport]Download the mcg-cli if the current binary has a different minor version than OCS

ocs_ci/ocs/constants.py
=> fix mcg-cli download issue

ocs_ci/ocs/resources/storage_cluster.py
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2222022
=> revert the workaround of storage cluster version check

ocs_ci/ocs/resources/mcg.py, tests/manage/mcg/test_nb_mgmt_endpoint.py
release-4.13 backport of #7875
=> [release-4.13 backport] Choose to use only the MCG-CLI for RPC calls elsewhere

ocs_ci/utility/deployment.py
=> MachineConfigPool skip for IBM Managed cloud

ocs_ci/templates/workloads/jenkins/buildconfig.yaml
https://quay.io/repository/ocsci/jenkins-agent-maven?tab=tags
https://url.corp.redhat.com/a9349e8
```
podman pull quay.io/openshift/origin-jenkins-agent-maven:4.X
podman image tag quay.io/openshift/origin-jenkins-agent-maven:4.X quay.io/ocsci/jenkins-agent-maven:4.X
podman push  quay.io/ocsci/jenkins-agent-maven:4.X
```
=> Jenkins Workload, Create our own repo for maven job

ocs_ci/utility/deployment.py
=> [4.13]: MachineConfigPool skip for IBM Managed cloud

conf/ocsci/use_device_class_fast.yaml, conf/ocsci/use_device_class_hdd.yaml, ocs_ci/deployment/deployment.py, ocs_ci/ocs/resources/storage_cluster.py
=> Use deviceclass in storagecluster

tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
Test from the backlog
BZ: 2046677
Polarion-id: OCS-4582
Backport:
=> Test reclaim chronjob by annotation

ocs_ci/ocs/resources/objectbucket.py
=> Fix ObjectBucket::verify_health to only check S3 existence of MCG buckets

conf/ocsci/submariner_upstream.yaml, ocs_ci/deployment/acm.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/8167
=> Provide option for choosing specific upstream submariner based on tags

ocs_ci/ocs/constants.py, ocs_ci/ocs/ui/odf_topology.py, ocs_ci/ocs/ui/page_objects/odf_topology_tab.py, ocs_ci/ocs/ui/views.py, tests/ui/test_odf_topology.py
test test_validate_topology_configuration is not passing because open BZ -> https://bugzilla.redhat.com/show_bug.cgi?id=2233027
Local test run -> http://pastebin.test.redhat.com/1107757
http://pastebin.test.redhat.com/1107758
locators changed, external mode check removed, tests verifying details adjusted
=> Topology tests adjustments 4.14

ocs_ci/ocs/resources/storage_cluster.py
=> DeviceClass verification in ceph osd tree

tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
=> Increase timeout to allow pods to reach Running state in test_non_ocs_taint_and_tolerations after pod respin

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/views.py
FIXES: https://github.com/red-hat-storage/ocs-ci/issues/8097
we need 4.14 locators to follow scenarios of the upgrade and scenarios with mixed versions
OCP 4.14, ODF 4.13, etc.
failures:
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/12976/594644/594920/594921/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/465/12976/594644/594922/594923/log
=> fix mixed deployments OCP 4.14 OCS 4.13

ocs_ci/ocs/scale_lib.py, tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Cherry Pick PR 8017 to release-4.13
=> Cherry Pick PR 8017 to release-4.13

ocs_ci/ocs/scale_lib.py, tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Cherry Pick PR 8017 to release 4.12
=> Cherry Pick PR 8017 to release 4.12

tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
…_taint_and_tolerations after pod respin (#8035)
=> [4.12] Increase timeout to allow pods to reach Running state in test_non_ocs_taint_and_tolerations after pod respin

tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
=> Wait for nodes to become ready to allow pods to come up in test_automated_recovery_from_stopped_node_and_start

tests/conftest.py, tests/manage/mcg/test_s3_with_java_sdk.py
- (partially) fixes: https://github.com/red-hat-storage/ocs-ci/issues/7853
=> update various pods with proxy env vars

ocs_ci/ocs/node.py, tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
fix https://github.com/red-hat-storage/ocs-ci/issues/8326
=> Change the method 'is_node_rack_or_zone_exist' to get the node name instead of the node object

tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
…_taint_and_tolerations after pod respin (#8035)
=> [4.13] Increase timeout to allow pods to reach Running state in test_non_ocs_taint_and_tolerations after pod respin

tests/manage/mcg/test_s3_routes.py
release-4.13 backport of #7657
=> [release-4.13 backport] Patch ocs-storagecluster instead the NooBaa CR at `test_disable_nb_lb`

tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
…ated_recovery_from_stopped_node_and_start (#8341)
=> [4.13] Wait for nodes to become ready to allow pods to come up in test_automated_recovery_from_stopped_node_and_start

ocs_ci/ocs/must_gather/const_must_gather.py, ocs_ci/ocs/must_gather/must_gather.py
first step for fixing issue #8320
=> Add prints for must-gather-log

tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
…ated_recovery_from_stopped_node_and_start (#8341)
=> [4.12] Wait for nodes to become ready to allow pods to come up in test_automated_recovery_from_stopped_node_and_start

ocs_ci/ocs/cluster.py, ocs_ci/ocs/resources/pod.py, tests/manage/monitoring/test_workload_with_distruptions.py
* utilities moved to common classes
* polarion-id added
* full_ratio threshold added instead of static value
=> RFE from pr 8139

ocs_ci/ocs/couchbase.py, tests/e2e/workloads/app/couchbase/test_couchbase.py, tests/e2e/workloads/app/couchbase/test_couchbase_node_drain.py, tests/e2e/workloads/app/couchbase/test_couchbase_node_reboot.py, tests/e2e/workloads/app/couchbase/test_couchbase_pod_respin.py
https://github.com/red-hat-storage/ocs-ci/issues/8359
=> Added flexibility to pull latest image to create couchbase cluster

ocs_ci/ocs/jenkins.py, ocs_ci/templates/workloads/jenkins/buildconfig.yaml
=> Release 4.12 cherry pick pr 7727

ocs_ci/helpers/helpers.py, ocs_ci/ocs/constants.py, ocs_ci/templates/app-pods/csi-cephfs-rox.yaml, tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py
Adding test for a new feature for ROX accessmode  
Test Plan: https://docs.google.com/document/d/1ofePv7Mi_Hx-MFfusVKrpySftDXXcUKulybnsg4VFP0/edit#heading=h.7h72qs105ymr
Jira: https://issues.redhat.com/browse/RHSTOR-4287
=> Adding new test and template for the pvc to check rox access mode

ocs_ci/deployment/disconnected.py, ocs_ci/ocs/amq.py, ocs_ci/ocs/benchmark_operator.py, ocs_ci/ocs/benchmark_operator_fio.py, ocs_ci/ocs/pgsql.py, ocs_ci/ocs/resources/ocs.py, ocs_ci/ocs/scale_pgsql.py, ocs_ci/utility/utils.py, tests/manage/z_cluster/test_scc.py
Couple of fixes for various tests related to disconnected deployment. Mostly related to mirroring required image.
=> Disconnected cluster related fixes for various tests

conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy_flexy.yaml, ocs_ci/deployment/vmware.py, ocs_ci/utility/load_balancer.py
- implementing vSphere UPI deployment behind proxy without containerized Flexy
=> vSphere UPI deployment behind proxy

ocs_ci/framework/pytest_customization/marks.py, ocs_ci/ocs/ui/page_objects/block_pools.py, ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py, ocs_ci/ocs/ui/page_objects/page_navigator.py, ocs_ci/ocs/ui/page_objects/searchbar.py, ocs_ci/ocs/ui/views.py, tests/conftest.py, tests/manage/mcg/ui/test_mcg_ui.py, tests/manage/storageclass/test_delete_rbd_pool_attached_to_sc.py
continuing OCS-3889 added tests that verifying that RBD pools cannot be deleted from cluster when referred by a Storage class.
=> add a tests to try delete rbd reffered by sc

ocs_ci/ocs/cluster.py, ocs_ci/ocs/constants.py, ocs_ci/ocs/fiojob.py, ocs_ci/ocs/resources/pod.py, tests/manage/monitoring/test_workload_with_distruptions.py
=> Test_ceph_osd_low_ops_alert backport 4.13

ocs_ci/deployment/vmware.py
=> use appropriate installer release

ocs_ci/ocs/bucket_utils.py, tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
=> Adjust `namespace_bucket_update` to the new schema

ocs_ci/ocs/couchbase.py, tests/e2e/workloads/app/couchbase/test_couchbase.py, tests/e2e/workloads/app/couchbase/test_couchbase_node_drain.py, tests/e2e/workloads/app/couchbase/test_couchbase_node_reboot.py, tests/e2e/workloads/app/couchbase/test_couchbase_pod_respin.py
Added flexibility to pull latest image to create couchbase cluster (#8363)
=> cherry-pick fix_couchbase 4.12

ocs_ci/ocs/resources/storage_cluster.py, ocs_ci/utility/utils.py
=> remove ceph crashes after upgrade

tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/8406
=> bz mark is stale -to remove

conf/README.md, conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_custom_storageclass_names.yaml, conf/ocsci/custom_storageclass_names.yaml
Added deployment config for custom storageclass names
=> Added deployment config for custom storageclass names

ocs_ci/ocs/pgsql.py
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/426/13431/613350/613369/613371/log
=> cherry-pick Validate pv deletion in teardown (#7266) 4.11

ocs_ci/ocs/node.py, tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
Backport PR https://github.com/red-hat-storage/ocs-ci/pull/8344.
=> Change the method 'is_node_rack_or_zone_exist' to get the node name instead of the node object 4.12 #8344

ocs_ci/templates/app-pods/esclient.yaml
Updating esclient.yaml to address https://url.corp.redhat.com/74274ab
=> Updating ocs_ci/templates/app-pods/esclient.yaml to address security context issues

ocs_ci/ocs/cluster.py, ocs_ci/ocs/constants.py
=> PDB changes for arbiter deployment

ocs_ci/ocs/managedservice.py, ocs_ci/ocs/node.py, tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
=> Run the consumers verification steps if we use the ocs-provider-server service type 'NodePort' on Provider

ocs_ci/framework/logger_helper.py, ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/page_objects/backing_store_tab.py, ocs_ci/ocs/ui/page_objects/bucket_class_tab.py, ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py, ocs_ci/ocs/ui/page_objects/namespace_store_tab.py, ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py, ocs_ci/ocs/ui/page_objects/object_service.py, ocs_ci/ocs/ui/page_objects/overview_tab.py, ocs_ci/ocs/ui/page_objects/resource_list.py, ocs_ci/ocs/ui/page_objects/searchbar.py, ocs_ci/ocs/ui/page_objects/storage_system_details.py, ocs_ci/ocs/ui/validation_ui.py, ocs_ci/ocs/ui/views.py, tests/ui/test_validation_ui.py
test_dashboard_validation_ui reworked. 
locators validated and some of them fixed
test works as a 'complex scenario test' - do not fail the test on first bad verification, record failure and test further. 
Important - do not backport! For version 4.14 and above.
=> test_dashboard_validation_ui rework. added acceptance mark

ocs_ci/ocs/platform_nodes.py, tests/ui/test_odf_topology.py
Fixes: #8382
Backport to branch
=> Test stop start node validate topology fix

ocs_ci/ocs/ui/views.py
=> fix locator for skip_tour

ocs_ci/ocs/ui/odf_topology.py, tests/ui/test_odf_topology.py
Bug https://bugzilla.redhat.com/show_bug.cgi?id=2214023 was fixed. Now node details have full provider ID, but not the shorten version of provider id.
=> adjust provider id

ocs_ci/ocs/ui/deployment_ui.py
=> UI Deployment, add a new step 'Data Protection'

ocs_ci/ocs/exceptions.py, ocs_ci/utility/azure_utils.py, setup.py
Fixes: #8487 
To release-4.11 branch.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2168839
=> Backporting missing parts from #7579

ocs_ci/ocs/constants.py, tests/manage/z_cluster/test_ceph_default_values_check.py
issue [8505](https://github.com/red-hat-storage/ocs-ci/issues/8505)
=> Adjust the ROOK_CEPH_CONFIG_VALUES for 4.14,  issue#8505

ocs_ci/ocs/resources/mockup_bucket_logger.py
Fixes: #8399
- Change logs-dir to be under the default rsh directory
- Improve the test's performance building one big command on the ocs-ci agent and run it once via the s3cli-pod to create a batch of logs on the s3cli pod, instead of uploading them one by one to the pod.
=> `test_log_based_bucket_replication.py` Change logs-dir and improve the test's performance

tests/e2e/kcs/test_mon_crash_recovery_scenario.py
https://github.com/red-hat-storage/ocs-ci/issues/8531
=> Skip test_mon_crash_recovery_scenario

ocs_ci/ocs/jenkins.py, ocs_ci/templates/workloads/jenkins/buildconfig.yaml
=> cherry-pick jenkins_failure 4.11

ocs_ci/helpers/helpers.py, ocs_ci/ocs/cluster_load.py, ocs_ci/ocs/constants.py, ocs_ci/templates/workloads/fio/fedora_deployment.yaml, tests/conftest.py
Cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/7604 to release-4.10 branch
=> [4.10] ClusterLoad: Replace DeploymentConfig with Deployment

ocs_ci/helpers/helpers.py, ocs_ci/ocs/cluster_load.py, ocs_ci/ocs/constants.py, ocs_ci/templates/workloads/fio/fedora_deployment.yaml, tests/conftest.py
Cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/7604 to release-4.11 branch
=> [4.11] ClusterLoad: Replace DeploymentConfig with Deployment

ocs_ci/helpers/helpers.py, ocs_ci/ocs/cluster_load.py, ocs_ci/ocs/constants.py, ocs_ci/templates/workloads/fio/fedora_deployment.yaml, tests/conftest.py
Cherry-pick of #7604 to release-4.12 branch
=> [4.12] ClusterLoad: Replace DeploymentConfig with Deployment

ocs_ci/helpers/helpers.py, ocs_ci/ocs/cluster_load.py, ocs_ci/ocs/constants.py, ocs_ci/templates/workloads/fio/fedora_deployment.yaml, tests/conftest.py
Cherry pick #7604 to release-4.13 branch
=> [4.13] ClusterLoad: Replace FIO DeploymentConfig with Deployment

ocs_ci/ocs/constants.py, tests/disaster-recovery/mdr/conftest.py
=> [4.13]: Run mdr tests only in case of mdrconfig release 4.13

tests/manage/mcg/test_bucket_policy.py
=> `test_public_website`: Use `s3_get_object` with `retry`

tests/manage/monitoring/prometheusmetrics/test_mcg_hpa.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/8420
=> Change name of noobaa hpa in metrics test

ocs_ci/ocs/bucket_utils.py, tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
release-4.13 backport of #8235
=> [release-4.13 backport] Adjust `namespace_bucket_update` to the new schema

tests/README.md, tests/cross_functional/README.md, tests/functional/README.md, tests/libtest/README.md
Jira: https://issues.redhat.com/browse/OCSQE-839
=> Introduce new top level test directory modules

ocs_ci/framework/conf/ocp_version/ocp-4.15-config.yaml, ocs_ci/framework/conf/ocp_version/ocp-4.15-upgrade.yaml
=> Adding OCP 4.15 config files

tests/manage/mcg/test_mcg_resources_disruptions.py
release-4.12 backport of #7638
=> [release-4-12 backport] Disregard the users array of noobaa-db SCC at test_db_scc

ocs_ci/ocs/resources/storage_cluster.py
Fixed in-transit encryption tests failure for external mode cluster
=> Fixed in-transit encryption tests failure for external mode cluster

conf/README.md, ocs_ci/framework/conf/default_config.yaml, ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/utility/reporting.py, ocs_ci/utility/utils.py, tests/conftest.py, tests/test_failure_propagator.py
Cherry pick of https://github.com/red-hat-storage/ocs-ci/pull/8443 and https://github.com/red-hat-storage/ocs-ci/pull/8481 to release-4.13
=> [release-4.13] Ceph health skip reporting

conf/README.md, ocs_ci/framework/conf/default_config.yaml, ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/utility/reporting.py, ocs_ci/utility/utils.py, tests/conftest.py, tests/test_failure_propagator.py
Cherry pick of https://github.com/red-hat-storage/ocs-ci/pull/8443 and https://github.com/red-hat-storage/ocs-ci/pull/8481 to release-4.12
=> [release-4.12] Ceph health skip reporting

conf/README.md, ocs_ci/framework/conf/default_config.yaml, ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/utility/reporting.py, ocs_ci/utility/utils.py, tests/conftest.py, tests/test_failure_propagator.py
Cherry pick of https://github.com/red-hat-storage/ocs-ci/pull/8443 and https://github.com/red-hat-storage/ocs-ci/pull/8481 to release-4.11
=> [release-4.11] Ceph health skip reporting

conf/README.md, ocs_ci/framework/conf/default_config.yaml, ocs_ci/framework/pytest_customization/ocscilib.py, ocs_ci/utility/reporting.py, ocs_ci/utility/utils.py, tests/conftest.py, tests/test_failure_propagator.py
Cherry pick of https://github.com/red-hat-storage/ocs-ci/pull/8443 and https://github.com/red-hat-storage/ocs-ci/pull/8481 to release-4.10
=> [release-4.10] Ceph health skip reporting

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/pvc_ui.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/6302
=> Fix failure to clear field

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/page_objects/page_navigator.py, ocs_ci/ocs/ui/views.py
=> namespace-selection-fix

ocs_ci/ocs/ui/page_objects/resource_list.py
this block is broken, remove redundant parameter - By.XPATH
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/557/14647/673543/673695/673696/log
=> fix function call args test_obc_creation_deletion fails

tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
=> Increase timeout for nodes ready check in test_check_pods_status_after_node_failure

ocs_ci/ocs/constants.py, ocs_ci/ocs/ui/views.py, tests/manage/mcg/ui/test_verify_region_list.py
covers: https://bugzilla.redhat.com/show_bug.cgi?id=2183480
=> Compare AWS regions and Noobaa regions list

ocs_ci/utility/utils.py
=> Extend timeout for waiting for machineconfigpoool

ocs_ci/utility/prometheus.py, ocs_ci/utility/workloadfixture.py, tests/manage/monitoring/conftest.py
🍒 https://github.com/red-hat-storage/ocs-ci/pull/8500
=> Measure operation thread safe 4.11

ocs_ci/utility/prometheus.py, ocs_ci/utility/workloadfixture.py, tests/manage/monitoring/conftest.py
🍒 https://github.com/red-hat-storage/ocs-ci/pull/8500
=> Measure operation thread safe 4.12

ocs_ci/utility/prometheus.py, ocs_ci/utility/workloadfixture.py, tests/manage/monitoring/conftest.py
=> Measure operation thread safe 4.13

tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Cherry Pick PR https://github.com/red-hat-storage/ocs-ci/pull/8634 for 4.12 release branch
=> Cherry Pick PR-8634 for release 4.12

tests/ui/test_odf_topology.py
=> extend finalizer to fix teardown issue

ocs_ci/ocs/ui/base_ui.py, ocs_ci/ocs/ui/views.py
=> remove OCP title validation on login

ocs_ci/utility/prometheus.py, ocs_ci/utility/workloadfixture.py, tests/manage/monitoring/conftest.py
🍒 https://github.com/red-hat-storage/ocs-ci/pull/8500
=> Measure operation thread safe 4.10

tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Cherry Pick PR https://github.com/red-hat-storage/ocs-ci/pull/8634 to 4.13 release branch
=> Cherry Pick PR 8634 to 4.13 release branch

ocs_ci/ocs/exceptions.py, ocs_ci/ocs/osd_operations.py, ocs_ci/ocs/platform_nodes.py, ocs_ci/utility/vsphere.py
=> get volume path in vsphere using volumeHandle from PV

ocs_ci/ocs/constants.py
=> change ceph debug_mon to 30

tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
This PR contains increasing timeouts for bulk pod attach and bulk clone creation.
=> Increasing timeouts for bulk pod attach and bulk clone creation

tests/manage/mcg/test_kms.py
release-4.12 backport of https://github.com/red-hat-storage/ocs-ci/pull/7660
=> [release-4.12 backport] test_noobaa_kms_validation: Remove the use of RE and generalize the search based on environment config

ocs_ci/utility/metadata_utils.py, tests/manage/add_metadata_feature/test_metadata.py
Updated metadata validation test cases to fix https://github.com/red-hat-storage/ocs-ci/issues/7459
=> Updated metadata validation testcases to fix issue#7459

ocs_ci/utility/pagerduty.py, tests/manage/monitoring/conftest.py, tests/manage/monitoring/pagerduty/test_ceph.py, tests/manage/monitoring/pagerduty/test_deployment_status.py
- Fixes https://github.com/red-hat-storage/ocs-ci/issues/8501
- Fixes https://github.com/red-hat-storage/ocs-ci/issues/8668
=> Check both incidents CephOSDDisdUnavailable and CephOSDDiskNotResponding in test_ceph_osd_stopped_pd

ocs_ci/ocs/exceptions.py, ocs_ci/ocs/osd_operations.py, ocs_ci/ocs/platform_nodes.py, ocs_ci/utility/vsphere.py
=> [release-4.13] get volume path in vsphere using volumeHandle from PV

ocs_ci/utility/utils.py, tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
=> storage device check after add capacity

ocs_ci/ocs/bucket_utils.py, tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
release-4.12 backport of #8235
=> [release-4.12 backport] Adjust `namespace_bucket_update` to the new schema

ocs_ci/ocs/cluster.py, tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
Test reclaim chronjob by label 4.10
https://github.com/red-hat-storage/ocs-ci/pull/8194
=> cherry-pick test_reclaim_space_cronjob_with_annotation 4.10

ocs_ci/ocs/cluster.py, tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
Test reclaim chronjob by label 4.11
https://github.com/red-hat-storage/ocs-ci/pull/8194
=> cherry-pick test_reclaim_space_cronjob_with_annotation 4.11

tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
Test reclaim chronjob by label 4.13
#8194
=> cherry-pick test_reclaim_space_cronjob_with_annotation 4.13

ocs_ci/ocs/cluster.py, tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
Test reclaim chronjob by label 4.12
https://github.com/red-hat-storage/ocs-ci/pull/8194
=> cherry-pick test_reclaim_space_cronjob_with_annotation 4.12

ocs_ci/framework/pytest_customization/reports.py
Fixes Issue: https://github.com/red-hat-storage/ocs-ci/issues/8679
=> Adding FileNotFoundError exception

ocs_ci/templates/workloads/fio/fedora_deployment.yaml
Fixes https://github.com/red-hat-storage/ocs-ci/issues/8087
=> Replace FIO image for cluster load

tests/manage/monitoring/conftest.py
- fixes https://github.com/red-hat-storage/ocs-ci/issues/8728
- fixes https://github.com/red-hat-storage/ocs-ci/issues/8721
=> Differentiate between platforms in measure_operation and add threading_lock where missing

setup.py
=> update cryptography to latest version

setup.py
=> [release-4.12] update cryptography to latest version

setup.py
=> [release-4.11]  Update cryptography release 411

ocs_ci/repos/ocp_4_15_rhel8.repo
=> Add RHEL repo for OCP 4.15

ocs_ci/ocs/node.py, tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
Backport PR https://github.com/red-hat-storage/ocs-ci/pull/8344.
=> Change the method 'is_node_rack_or_zone_exist' to get the node name instead of the node object 4.11 #8344

tests/manage/mcg/test_bucket_policy.py
https://bugzilla.redhat.com/show_bug.cgi?id=2210289
=> Add coverage for Bz 2210289

ocs_ci/framework/pytest_customization/reports.py
=> fix rounding issue in reports

tests/manage/monitoring/prometheus/test_noobaa.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/8764
=> Skip test_noobaa_bucket_quota in 4.12

tests/manage/rgw/test_rgw_routes.py
=> Add squad for rgw routes test case

ocs_ci/framework/conf/ocs_version/ocs-4.15.yaml
=> use stable build for ODF 4.15

tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
This PR contains increase of bulk pod attach timeout amd increase of accepted creation time.
=> test_pvc_creation_deletion_performance.py - creation deletion fix 

ocs_ci/utility/utils.py
=> Increase timeout in wait for machine config pool

ocs_ci/ocs/resources/storage_cluster.py
=> use get for multicluster_mode

tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
* updated setup teardown method for nfs testclass
* Addressed review comments updated to constants.AWS_PLATFORM
---------
=> cherry picked pr 7884 to release 4.12

tests/manage/z_cluster/conftest.py
=> Add the "threading_lock" fixture to "workload_storageutilization_rbd" and "workload_storageutilization_cephfs"

tests/ui/test_capacity_breakdown_ui.py
replace green_squad with black_squad
=> test ownership on test_requested_capacity_breakdown

ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
=> fix-_check_only_lower_case_numbers_periods_hyphens_rule

ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
=> add redunancy _check_all_rules_exist

tests/disaster-recovery/mdr/test_app_failover_and_relocate.py, tests/disaster-recovery/regional-dr/test_failover.py, tests/disaster-recovery/regional-dr/test_failover_and_relocate.py, tests/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py, tests/disaster-recovery/regional-dr/test_negative_failover_relocate_ui.py, tests/disaster-recovery/regional-dr/test_relocate.py, tests/disaster-recovery/regional-dr/test_sequential_failover.py, tests/disaster-recovery/regional-dr/test_sequential_relocate.py
=> Add turquoise_squad to DR test cases
