tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py

This PR contains the following :
test_pvc_multi_clone_performance.py and test_pvc_multi_snapshot_performance.py - adding ignore_leftovers marker to those very long tests. 
Since those test cases is very long - sometimes other pods ( mds) are restarted, with no relation to the tests that are running, but still causes failure in the teardown of the test cases since new pods exist by the end of the teardown. 
Therefore those long tests need this marker.

test_pvc_multi_clone_performance.py and test_pvc_multi_snapshot_performance.py - adding ignore_leftovers marker to very long tests

---

ocs_ci/ocs/resources/mcg.py

Increase timeout to 300 sec in check_data_reduction function.
Fixed https://github.com/red-hat-storage/ocs-ci/issues/8274

Increase timeout in retrieve reduction data

---

tests/conftest.py

Fixed issue: https://github.com/red-hat-storage/ocs-ci/issues/8809
Added timeout for 60s and retry 10s for running pod status.

Added timeout 60s and retry 10s for to check nsfs running pod status.

---

ocs_ci/ocs/resources/storage_cluster.py

https://bugzilla.redhat.com/show_bug.cgi?id=2245978
OSD YAML before fix:
```
k8s.v1.cni.cncf.io/networks: openshift-storage/private-net, openshift-storage/public-net
```
OSD YAML after fix:
```
k8s.v1.cni.cncf.io/networks: '[{"name":"public-net","namespace":"openshift-storage"},{"name":"private-net","namespace":"openshift-storage"}]'
```

Fix Multus Deployment

---

tests/ui/test_odf_topology.py

One of the pending PRs merged after threadingLock became mandatory to Prometheus API. 
Now adding it.

added ThreadingLock to prometheusApi instantiation

---

ocs_ci/ocs/resources/mcg.py

For Fusion HCI to ru test cases, there is no need for pull-secret to download mcg-cli. ocs-ci will download the same form the existing secrets but its failing since data folder doesn't exist.

creata data directory for downloading mcg-cli

---

ocs_ci/ocs/resources/storage_cluster.py

revert PR 8411 - remove ceph crashes after upgrade

---

ocs_ci/ocs/cluster.py
ocs_ci/ocs/must_gather/must_gather.py
ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/resources/storage_cluster.py
ocs_ci/ocs/scale_noobaa_lib.py
tests/conftest.py
tests/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py
tests/e2e/kcs/test_disable_mcg_external_service.py
tests/e2e/kcs/test_selinux_relabel_solution.py
tests/e2e/scale/noobaa/test_scale_obc_start_time_respin_noobaa_pods.py
tests/manage/mcg/test_bucket_replication.py
tests/manage/mcg/test_db_nfs_mount.py
tests/manage/mcg/ui/test_namespace_store.py
tests/manage/z_cluster/test_add_mds_to_cluster.py
tests/manage/z_cluster/test_delete_local_volume_sym_link.py
tests/manage/z_cluster/test_multiple_mon_pods_stays_on_same_node.py
tests/manage/z_cluster/test_no_liveness_probe.py

- Fixes https://github.com/red-hat-storage/ocs-ci/issues/8853

Replace OPENSHIFT_STORAGE_NAMESPACE and ROOK_CLUSTER_NAMESPACE usage with configuration

---

ocs_ci/framework/pytest_customization/marks.py
tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
tests/manage/z_cluster/nodes/test_rolling_shutdown_and_recovery_ms.py
tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py
tests/managed-service/test_acceptance.py
tests/managed-service/test_pod_disruptions.py
tests/managed-service/test_post_installation_state.py

Applied MS TC with managed_service_required to HCI Provider-Client platform using hci_pc_platform_required marker

Applied MS TC to hci PC platform using hci_pc_platform_required marker

---

tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py

Add marker in the test cases given below to ignore the pod rook-ceph-detect-version during environment check.
1. tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py
2. tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
Fixes #8800

Add marker in tests to ignore the pod rook-ceph-detect-version during environment check

---

tests/conftest.py

This Fixes the issue 8863 for 45 Test cases , error at `openshift-storage not found` while running on client cluster

Fixing issue of openshift-storage not found in awscli_pod_fixture function

---

ocs_ci/ocs/must_gather/must_gather.py

Many tests failed because of content issues [ceph commands return errors != return 0]
https://bugzilla.redhat.com/show_bug.cgi?id=2049204
https://bugzilla.redhat.com/show_bug.cgi?id=2125204
`csi-addons-controller-manager` pod is reset after running the must-gather command 
https://bugzilla.redhat.com/show_bug.cgi?id=2245246

Skipping verify_ceph_file_content method because know issues

---

tests/manage/mcg/test_namespace_crd.py

Fixes #7870
Note that due to the findings in comments 28 and 30 in https://bugzilla.redhat.com/show_bug.cgi?id=2165907, this TC should be skipped in all cluster types and not just AWS-IPI-KMS_THALES.

Skip `test_respin_mcg_pod_and_check_data_integrity_crd` until bug 2165907 is resolved

---

ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/resources/storage_cluster.py
ocs_ci/utility/utils.py

This reverts commit 0899c2f45c505d6f800051c41ff03e6c2e0c00b9.
Related to:
https://bugzilla.redhat.com/show_bug.cgi?id=2249844
Where we just got new build with RHCS 6.1-z3 where bug should be fixed.
So we should test without the W/A.

Revert "remove ceph crashes after upgrade"

---

.pre-commit-config.yaml
docs/getting_started.md
setup.py

- required for python 3.12
- set minimal python version to 3.8.1
Python 3.12 is the default python on Fedora 39 and older versions of `flake8` (more precisely older versions of `pycodestyle` which is dependency for `flake8`) doesn't work on Python 3.12.
Example issues on Python 3.12 and older `flake8`:
```
bootstrap_ignition_url = (
f"http://{config.ENV_DATA.get('httpd_server')}/"
f"{path_to_bootstrap_on_remote}"
)
```
will raise following error (line 2229 is the second line from the code snippet above):
```
ocs_ci/deployment/vmware.py:2229:15: E231 missing whitespace after ':'
```
or this code:
```
logger.info(
f"Resource pool {pool} does not exist in cluster {self.cluster}"
)
```
will raise following error (line 393 is the second line from the code snippet):
``` …
```

update flake8 to new version (6.1.0)

---

tests/disaster-recovery/regional-dr/test_node_operations_during_failover_relocate.py

Tests cases to verify that the failover and relocate operations are not affected when node is drained while the failover/relocate operations are going on.
<google-sheets-html-origin>
OCS-4441 | ([RHSTOR-2139](https://issues.redhat.com//browse/RHSTOR-2139) Regional DR for RBD - Mature from TP to GA) During Failover from C1 to C2, Drain the node in C2 where the rbd mirror pod is running
-- | --
OCS-4442 | ([RHSTOR-2139](https://issues.redhat.com//browse/RHSTOR-2139) Regional DR for RBD - Mature from TP to GA) During Relocate from C2 to C1, Drain the node in C1 where the rbd mirror pod is running
OCS-4443 | ([RHSTOR-2139](https://issues.redhat.com//browse/RHSTOR-2139) Regional DR for RBD - Mature from TP to GA) During Failover from C1 to C2, Drain the node in C2 where ODR operator pod is …

Tests to verify that the failover and relocate operations are not affected by node drain

---

tests/manage/mcg/test_endpoint_autoscale.py

Fixed issue https://github.com/red-hat-storage/ocs-ci/issues/8843

Fixed issue with Endpoint pod count is not expected

---

tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
tests/e2e/workloads/test_new_sc_rbd_e2e_workloads.py
tests/manage/monitoring/test_workload_with_distruptions.py
tests/manage/pv_services/pvc_snapshot/test_verify_rbd_trash_purge.py
tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
tests/manage/storageclass/conftest.py
tests/manage/z_cluster/test_scc.py

As Per Tier2 analysis, Skipping the Test cases on HCI Provider Client setup where Cephblockpool or storageclass creation is involved

Cephblockpool and sc creation is ideally not supported to customer on HCI PC platform

---

tests/conftest.py

Fix the failures of clone tests in HCI Provider Client setup due to the error
```
UnboundLocalError: local variable 'clone_yaml' referenced before assignment
```
Test run: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-odf-multicluster/2147/

Fix clone fixture error for HCI Provider Client setup

---

tests/e2e/flowtest/pvc_snapshot_and_clone/test_pgsql_pvc_snapshot_and_clone.py
tests/e2e/flowtest/pvc_snapshot_and_clone/test_pgsql_pvc_snapshot_and_clone_with_base_operation.py
tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py
tests/e2e/lifecycle/pvc_snapshot/test_pgsql_pvc_snapshot.py
tests/encryption/test_intransit_encryption_sanity.py
tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
tests/manage/pv_services/test_pvc_assign_pod_node.py
tests/manage/pv_services/test_raw_block_pv.py
tests/manage/storageclass/test_create_multiple_sc_with_different_pool_name.py
tests/manage/storageclass/test_create_multiple_sc_with_same_pool_name.py

Skip the Test after Tier1 and Tier2 analysis for unsupported Feature:
1. NFS
2. Encryption
3. TC which involves the creation of new storageclass
4. Adjust test step to skip verification with  for above unsupported feature

Skip unsupported Feature Encryption, new SC  and NFS TC for HCI PC Platform

---

tests/manage/pv_services/pvc_resize/test_pvc_expansion.py

Update the test test_pvc_expansion to check a range of filesystem size.
Fixes #8973 
Test case: tests/manage/pv_services/pvc_resize/test_pvc_expansion.py::TestPvcExpand::test_pvc_expansion

Update the test test_pvc_expansion to check a range of filesystem size

---

conf/ocsci/dr_workload.yaml
ocs_ci/helpers/dr_helpers.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/dr/dr_workload.py
tests/conftest.py
tests/disaster-recovery/regional-dr/test_failover.py

Test cases to verify failover with CephFS based workloads.
OCS-4726 -  Failover to secondary cluster when primary site is DOWN
OCS-4729 -Failover to secondary cluster when primary site is UP

Tests to verify RDR failover with CephFS

---

ocs_ci/ocs/fiojob.py

Update the function to get pool name in HCI platform.
This will fix the type of issue given below in different test cases.
```
failed on setup with "AssertionError: Pool: cephblockpool-storageconsumer-6d144005-903d-482b-8ba7-25b0dbc6eca8 doesn't exist!"
```
Fixed the code to generate the correct pool name.

Update the function to get pool name in HCI platform

---

ocs_ci/ocs/resources/storageclassclaim.py

Fix storageclassclaim creation for HCI provider-client setup.
This change is to fix the error found in the test run https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-odf-multicluster/2159/testReport/junit/tests.managed-service.test_storageclassclaim/TestStorageClassClaim/test_verify_storageclassclaim/.

Fix storageclassclaim creation for HCI provider-client setup

---

.pre-commit-config.yaml
docs/getting_started.md
setup.py

- required for python 3.12
- set minimal python version to 3.8.1
Backport of https://github.com/red-hat-storage/ocs-ci/pull/8917

[release-4.12] Update flake8 and minimal python version

---

tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py

Add runs_on_provider marker in the tests test_monitoring_defaults. This will make the test to run on the provider cluster while using a multicluster configuration.

Add runs_on_provider marker in the tests test_monitoring_defaults

---

ocs_ci/helpers/helpers.py

Fixes #8997
Changing the method to switch because "switch_to_consumer" method is not applicable for HCI provider-client platform.

Fix cluster switching in the function storagecluster_independent_check

---

tests/manage/pv_services/test_pvc_assign_pod_node.py

Update tests/manage/pv_services/test_pvc_assign_pod_node.py to skip the check for api access token in HCI provider-client platform.
Fixes #9034

Update test_pvc_assign_pod_node to skip the check for api access token in HCI provider-client platform

---

ocs_ci/ocs/resources/mcg.py

Fixes mirroring timeout issue

---

tests/manage/z_cluster/nodes/test_nodes_restart.py

After the rolling nodes restart, it can take a little more time to successfully create resources (approximately 5 minutes).
This is not a bug because the process finished successfully, and the scenario of rolling restart nodes rarely happens.
fix #8649

Increase timeout for creating the resources after rolling nodes restart

---

ocs_ci/ocs/resources/objectbucket.py

release-4.12 backport of #8330

[release-4.12 backport] Fix ObjectBucket::verify_health to only check S3 existence of MCG buckets

---

ocs_ci/ocs/resources/objectbucket.py

release-4.13 backport of #8330

[release-4.13 backport] Fix ObjectBucket::verify_health to only check S3 existence of MCG buckets

---

tests/ecosystem/upgrade/test_noobaa.py

Fixes: #7754
See https://bugzilla.redhat.com/show_bug.cgi?id=1874243 for more info.

Skip `test_upgrade_mcg_io` until https://url.corp.redhat.com/c960ed4 is complete

---

ocs_ci/ocs/resources/objectbucket.py

Fixes: #8546
This allows each subclass to qualify when a bucket is considered missing or already deleted:
- OC buckets: CommandFailed exception with "not found"
- S3 buckets: botocore.errorfactory.NoSuchKey exception
- MCG-CLI buckets: If the response from the deletion attempt doesn't include "deleting" and the name of the bucket, which is the first part of the mcg-cli response when attempting to delete an OBC that exists in the system, as opposed to the empty response of an attempt to delete an OBC that doesn't:
```
$ mcg-cli obc delete non-existant-bucket
$ mcg-cli obc delete my-bucket
INFO[0001] 🗑️  Deleting: ObjectBucketClaim "my-bucket"  
INFO[0003] 🗑️  Deleted : ObjectBucketClaim "my-bucket"  
```

Move the check for "not found" buckets from ObjectBucket.delete to its subclasses

---

tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_creation_deletion_and_io.py

Combine the 26 test cases in the two modules given below to form a single test case.
1. tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
2. tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
New test :
tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_creation_deletion_and_io.py
This is to save the run time.

Combine pv_services disruption testcases

---

tests/manage/z_cluster/test_delete_rook_ceph_mon_pod.py
tests/manage/z_cluster/test_rook_ceph_log_rotate.py
tests/manage/z_cluster/test_rook_ceph_operator_log_type.py

Add runs_on_provider marker in the test cases:
1. tests/manage/z_cluster/test_delete_rook_ceph_mon_pod.py::TestDeleteRookCephMonPod::test_delete_rook_ceph_mon_pod
2. tests/manage/z_cluster/test_rook_ceph_log_rotate.py::TestRookCephLogRotate::test_rook_ceph_log_rotate
3. tests/manage/z_cluster/test_rook_ceph_operator_log_type.py::TestRookCephOperatorLogType::test_rook_ceph_operator_log_type

Provider-Client: Add runs_on_provider marker in test case

---

tests/manage/mcg/test_bucket_creation_deletion.py
tests/manage/mcg/test_bucket_deletion.py

This PR is intended to optimize run time for the test bucket creation/deletion tests under MCG by merging them into single tests and hence eliminating the time involved in test setup for individual when run as separate tests.
Total execution time before merging the bucket creation and deletion acceptance tests: 1084s
Total execution time for the acceptance testing with the changes in the PR: 532s
**We are able to reduce the execution time by 51%**

Optimize MCG test bucket creation/deletion tests

---

ocs_ci/ocs/resources/pod.py

Add cluster kubeconfig while using tools pod in provider-client setup.
Fixes #9173

Add cluster kubeconfig while using tools pod in provider-client setup

---

tests/ecosystem/upgrade/test_noobaa.py

release-4.14 backport of #9004

[release-4.14 backport] Skip `test_upgrade_mcg_io` until https://url.corp.redhat.com/c960ed4 is complete

---

tests/functional/object/mcg/test_bucket_policy.py

Fixes: #9013
Requires a backport to 4.14

`test_anonymous_read_only`: Use s3_get_object with retry 

---

ocs_ci/ocs/constants.py
tests/conftest.py
tests/libtest/test_awscli_leftovers.py

Fixes: #8909
Two measures were taken to address the issue:
1. Setting up the teardown function so it'll actually get called if the setup fails at any point.
2. Making sure there are no leftovers from previous runs by calling said teardown function before attempting to create the resources.

Refactor awscli fixture to avoid "s3cli already exists" leftovers

---

tests/ecosystem/upgrade/test_noobaa.py

release-4.13 backport of #9004

[release-4.13 backport] Skip `test_upgrade_mcg_io` until https://url.corp.redhat.com/c960ed4 is complete

---

ocs_ci/ocs/resources/mcg.py
tests/cross_functional/kcs/test_noobaa_rebuild.py

Fixes: #8811
Note that even though this test is under Magenta Squad, this issue failed many Red Squad tests.

Fix `test_noobaa_rebuild` and make sure it updates the mcg_obj_session s3 credentials after resetting the noobaa-admin secret

---

ocs_ci/helpers/disruption_helpers.py

Use the correct namespace of the initial pod while waiting for new pod in disruption_helpers.
Fixes #9187

Use the correct namespace while waiting for new pod in disruption_helpers

---

ocs_ci/ocs/node.py
tests/functional/pv/pv_encryption/test_encrypted_rbd_pvc_clone.py
tests/functional/pv/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
tests/functional/pv/pv_encryption/test_kmip_rbd_pv_encryption.py
tests/functional/pv/pv_encryption/test_rbd_pv_encryption.py
tests/functional/pv/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
tests/functional/ui/test_pv_encryption_ui.py

Encryption tests are failing because the crypt device is not visible from the pod in the new image. After a discussion with the dev team, we have decided to move the device check from the pod to the node.

Replacing crypt device check from pod to node.

---

tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py

Update timeout value to wait for pods in tests given below
1. tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py::TestResourceDeletionDuringCreationOperations::test_resource_deletion_during_pvc_pod_creation_and_io
2. tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py::TestResourceDeletionDuringMultipleDeleteOperations::test_disruptive_during_pod_pvc_deletion_and_io
Fixes #9210

Update timeout value to wait for pods in resource deletion tests

---

ocs_ci/ocs/resources/pod.py

In provider-client setup there will be context switching during the test run with multicliuster job. In test cases which needs to find the provisioner/snapshotter leader pod, the correct value of the namespace is required to pass to the function get_pod_logs. Othwerwise, if there is a context switch and the namespace value is taken frum ENV_DATA , it will be of a different cluster.
Fixes #9209

Update get_plugin_provisioner_leader to pass namespace to the function get_pod_logs

---

tests/functional/pv/pvc_resize/test_resource_deletion_during_pvc_expansion.py

Update the test test_resource_deletion_during_pvc_expansion to check a range of filesystem size.
Fixes #9161
Test case: 
tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py::TestResourceDeletionDuringPvcExpansion::test_resource_deletion_during_pvc_expansion[mgr]
It is expected to have a slight difference in the size of filesystem from the PVC size.

Update PVC expansion check on pods in test

---

ocs_ci/deployment/assisted_installer.py

Newest version of Assisted Installer API deprecated `api_vip` and `ingress_vip` keys in favor of `api_vips` and `ingress_vips`.

assisted installer api: removing deprecated keys

---

ocs_ci/ocs/node.py

When using the HCI provider cluster, the master nodes also have the worker label.
In the tests, we want to get worker nodes without the master nodes with the worker label to test the master and worker nodes' functionality separately.

Exclude the master nodes when using HCI Provider

---

ocs_ci/ocs/cluster.py

There are scenerios in external cluster where "noobaa-default-backing-store" is not created immediatly and given retry mechanism is not honored because its failed with CommandFailed.
So adding CommandFailed excepton for retry

Adding CommandFailed exception for retry

---

tests/functional/z_cluster/test_ceph_default_values_check.py

fix https://github.com/red-hat-storage/ocs-ci/issues/9244

Change the value of the mds cache memory limit

---

setup.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/9250
This is a temporary workaround since we can expect that other OCS-CI dependencies or needs will require the latest boto3 sometime in the future.

Downgrade the boto3 version from 1.34.14 to 1.24.96

---

conf/deployment/fusion_hci_pc/provider_bm_upi_1az_rhcos_nvme_3m_3w.yaml
ocs_ci/framework/pytest_customization/marks.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/platform_nodes.py
ocs_ci/utility/ibmcloud_bm.py
tests/functional/z_cluster/nodes/test_nodes_restart_hci.py

Create the node functionalities for IBMCloud with Bare Metal.
I used the IBM docs: https://cloud.ibm.com/docs/cli?topic=cli-sl-manage-bare-metal.
In this PR, I implemented the following:
- Create a new class `IBMCloudBMNodes`, in the platform_nodes file for HCI IBMCloud with Bare Metal.
- Create a new utility file `ocs_ci/utility/ibmcloud_bm.py`, for HCI IBMCloud with Bare Metal.
- Create a new test file `tests/functional/z_cluster/nodes/test_nodes_restart_hci.py`, for testing the node restart scenarios for HCI IBMCloud with Bare Metal. 
I am still not testing termination and creating new machines, as I need more information.
Also, I didn't use IO in the test file cause we still need to figure out the best way to run IO on multiple clients. I will add it in the next PR.

Create the node functionalities for IBMCloud with Bare Metal

---

setup.py

release-4.14 backport of #9257

[release-4.14 backport] Downgrade the boto3 version from 1.34.14 to 1.24.96

---

setup.py

release-4.13 backport of #9257

[release-4.13 backport] Downgrade the boto3 version from 1.34.14 to 1.24.96

---

setup.py

release-4.12 backport of #9257

[release-4.12 backport] Downgrade the boto3 version from 1.34.14 to 1.24.96

---

tests/functional/object/mcg/test_admission_control.py

Increase the timeout for internal bucket health verification, Fixed issue [8986](https://github.com/red-hat-storage/ocs-ci/issues/8986)

Increase the timeout for internal bucket health verification

---

ocs_ci/deployment/assisted_installer.py

The timeout for OCP deployment via Assisted installer were set to 1 hour, but we spotted few cases when it takes little bit longer (e.g. 70 minutes or so) and the deployment was still successful. For example:
https://url.corp.redhat.com/8ee7238
It might be related to the data center occupation and performance.
I'm proposing to extend the timeout to two hours in this PR.

Extend timeout for ocp deployment via Assisted Installer

---

ocs_ci/deployment/baremetal.py
ocs_ci/utility/baremetal.py

```
ENV_DATA:
baremetal:
bm_path_to_upload: "..."
bm_install_files: "..."
bm_httpd_server_user: …
```

restructure baremetal configuration

---

ocs_ci/deployment/assisted_installer.py

This fix is related/similar to PR https://github.com/red-hat-storage/ocs-ci/pull/9234, but in this case it is about response from Assisted installer API.

update assisted_installer code base on recent changes in api

---

ocs_ci/ocs/resources/storage_cluster.py

Currently, the MS deployment failed with the error: 
> 2024-02-05 14:39:15  12:39:14 - MainThread - ocs_ci.ocs.ocp - WARNING  - Failed to get resource: noobaa-endpoint of kind: Deployment, selector: None, Error: Error during execution of command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Deployment noobaa-endpoint -n openshift-storage -o yaml.
2024-02-05 14:39:15  Error is Error from server (NotFound): deployments.apps "noobaa-endpoint" not found
See, for example, the failed deployment here: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/33416/console.
We need to remove the check in the function `check_if_mcg_root_secret_public`.

Ignore 'check if MCG root secret is public' if we use MS

---

ocs_ci/deployment/baremetal.py
ocs_ci/utility/baremetal.py

This is backport of https://github.com/red-hat-storage/ocs-ci/pull/9274
```
ENV_DATA:
baremetal: …
```

restructure baremetal configuration - backport 4.14

---

ocs_ci/deployment/baremetal.py
ocs_ci/utility/baremetal.py

This is backport of https://github.com/red-hat-storage/ocs-ci/pull/9274
```
ENV_DATA:
baremetal: …
```

restructure baremetal configuration - backport 4.13

---

ocs_ci/deployment/baremetal.py
ocs_ci/utility/baremetal.py

This is backport of https://github.com/red-hat-storage/ocs-ci/pull/9274
```
ENV_DATA:
baremetal: …
```

restructure baremetal configuration - backport 4.12

---

ocs_ci/deployment/baremetal.py
ocs_ci/utility/baremetal.py

This is backport of https://github.com/red-hat-storage/ocs-ci/pull/9274
```
ENV_DATA:
baremetal: …
```

restructure baremetal configuration - backport 4.11

---

ocs_ci/ocs/awscli_pod.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/ocp.py
ocs_ci/ocs/resources/objectbucket.py
tests/conftest.py
tests/functional/object/mcg/test_provider_client.py

- move awscli_pod resources to [ocs_ci/ocs/awscli_pod.py](https://github.com/red-hat-storage/ocs-ci/compare/master...fbalak:mcg-client?expand=1#diff-dbd3f05a9264c49748dd0fd2257e0d7254e0b43543e1e7a965b54850a9b6fae9)
- add test_write_file_to_bucket_on_client
- execute oc commands with correct context
- delete buckets with correct context

Use cluster context with cluster resources and add test - write to bucket from client

---

ocs_ci/ocs/resources/bucket_policy.py
tests/conftest.py
tests/functional/object/mcg/flowtest/test_mcg_namespace_disruptions_crd.py
tests/functional/object/mcg/test_bucket_policy.py

Fixes: #9130
The structure of the bucket policy jsons that are accepted by MCG has been changed in https://github.com/noobaa/noobaa-core/commit/f37589305dc77157ce318f08344a369755f53796 and https://github.com/noobaa/noobaa-core/commit/47d93c442439331ccb5d6ede40a8fc82eda91422.
This PR adjusts OCS-CI to these new constraints.

Update MCG bucket policy usage to fix MalformedPolicy errors 

---

tests/functional/object/mcg/test_log_based_bucket_replication.py

- Fixes #9320
- Sorts the imports of the test file

Add  the `skipif_disconnected_cluster` decorator to `test_log_based_bucket_replication.py`

---

ocs_ci/ocs/dr/dr_workload.py

Skip deletion of drpc.yaml when deleting Subscription-based workloads, as the DRPC is now automatically deleted (See bug [2234428](https://bugzilla.redhat.com/show_bug.cgi?id=2234428))

[RDR] Skip deletion of drpc.yaml when deleting Subscription-based workloads

---

conf/ocsci/acm_2.10.yaml
ocs_ci/framework/conf/ocp_version/ocp-4.15-config.yaml
ocs_ci/framework/conf/ocp_version/ocp-4.16-config.yaml

Update ACM version to 2.10 and Submariner version to 0.17.0 for OCP 4.15 and 4.16 config files

Bumps ACM and Submariner versions for OCP 4.15 and later

---

ocs_ci/ocs/resources/storage_cluster.py
tests/functional/encryption/test_intransit_encryption_sanity.py
tests/functional/encryption/test_mon_failure_in_intransit_encryption.py

Following changes done.
1.  reduce waiting time to confirm Ceph configs.
2. Removed check for Ceph protocol version v2 check since it's being by default.
3. Fixed tests cases error by initialising the empty list `self.mons = []` at the begning   of test case.

Refined in-transit encryption test cases.

---

ocs_ci/helpers/helpers.py
ocs_ci/templates/app-pods/fedora_dc.yaml
tests/functional/pv/pv_services/test_run_io_multiple_dc_pods.py
tests/functional/workloads/ocp/registry/test_pod_from_registry.py

#9333
Created a new image with FIO. We don't need to install FIO with `rsh` command. We can build the image with FIO.
Dockerfile:
```
FROM quay.io/ocsci/fedora:latest
RUN dnf install -y fio bash util-linux
```
Build and Push the image to quay:
```
docker buildx build --platform linux/amd64,linux/ppc64le,linux/s390x,linux/arm64 -t quay.io/ocsci/fedora:fio . --push
```
Relevant tests:
```
tests/functional/pv/pv_services/test_run_io_multiple_dc_pods.py::TestRunIOMultipleDcPods::test_run_io_multiple_dc_pods[CephBlockPool]
tests/functional/pv/pv_services/test_run_io_multiple_dc_pods.py::TestRunIOMultipleDcPods::test_run_io_multiple_dc_pods[CephFileSystem]
tests/functional/workloads/ocp/registry/test_pod_from_registry.py
```

Create a new image for Fedora with FIO

---

ocs_ci/ocs/ui/views.py

Fixes: #9342 
Updated locators for Submariner UI installation to work with OCP 4.15

Fix Submariner UI installation for OCP 4.15

---

ocs_ci/deployment/disconnected.py
ocs_ci/utility/utils.py

* extend timeout for oc mirror command execution
* mirror_image: handle missing configuration
* extend timeout for oc image mirror command
* if DEPLOYMENT["mirror_registry"] is not configured, raise error with explanation what could be the root cause
fixes: https://github.com/red-hat-storage/ocs-ci/issues/9379
fixes: https://github.com/red-hat-storage/ocs-ci/issues/9377
cherrypick of: https://github.com/red-hat-storage/ocs-ci/pull/9391

[release-4.13] Disconnected deployment fixes/enhancements

---

tests/functional/storageclass/test_csi_subvolume_group_property.py

This PR contains a new test for verification of the default csi subvolume group pinning value. 
This is an automation of RHSTOR-3270- Enable distributed ephemeral pins on "csi" subvolume group.

Adding a new test for verification of the default csi subvolume group pinning value. 

---

tests/functional/z_cluster/test_rook_operator_restart_during_mon_failover.py

fix https://github.com/red-hat-storage/ocs-ci/issues/9430

In the test "test_rook_operator_restart_during_mon_failover" increase timeout waiting for the pods

---

ocs_ci/deployment/baremetal.py
ocs_ci/ocs/constants.py
ocs_ci/templates/ocp-deployment/dnsmasq.common.conf
ocs_ci/templates/ocp-deployment/dnsmasq.common.conf.j2
ocs_ci/templates/ocp-deployment/dnsmasq.pxe.conf
ocs_ci/templates/ocp-deployment/dnsmasq.pxe.conf.j2
ocs_ci/utility/connection.py

This PR should separate dnsmasq configuration from BM UPI deployment to separated methods to make it reusable in other types of deployment (e.g. via Assisted Installer).
There were only small functional changes:
* it uses `syslinux-tftpboot` instead of `syslinux-nonlinux` to get the fails required for PXE boot
* it sets the tftp root to `/tftpboot/` (based on what uses the syslinux-nonlinux package)
This is backport of [PR#9344](https://github.com/red-hat-storage/ocs-ci/pull/9344/)
**This PR has to be merged together with related [MR!1700](https://url.corp.redhat.com/dc31e6c).**

BM UPI deployment - dnsmasq configuration - backport for release-4.13

---

ocs_ci/deployment/baremetal.py
ocs_ci/ocs/constants.py
ocs_ci/templates/ocp-deployment/dnsmasq.common.conf
ocs_ci/templates/ocp-deployment/dnsmasq.common.conf.j2
ocs_ci/templates/ocp-deployment/dnsmasq.pxe.conf
ocs_ci/templates/ocp-deployment/dnsmasq.pxe.conf.j2
ocs_ci/utility/connection.py

This PR should separate dnsmasq configuration from BM UPI deployment to separated methods to make it reusable in other types of deployment (e.g. via Assisted Installer).
There were only small functional changes:
* it uses `syslinux-tftpboot` instead of `syslinux-nonlinux` to get the fails required for PXE boot
* it sets the tftp root to `/tftpboot/` (based on what uses the `syslinux-nonlinux` package)
**This PR has to be merged together with related [MR!1700](https://url.corp.redhat.com/dc31e6c).**

BM UPI deployment - dnsmasq configuration

---

ocs_ci/ocs/resources/namespacestore.py
tests/functional/object/mcg/test_namespace_crd.py

So far we've only been testing IBMCOS as an underlying storage with backingstores. This PR adds the option to create IBMCOS based Namespacestore buckets using the bucket_factory fxiture, and adds a basic IBMCOS NSS creation test case as a param to `test_namespace_bucket_creation_crd`.

Add IBMCOS Namespacestore creation support and a basic creation test case

---

ocs_ci/deployment/baremetal.py
ocs_ci/ocs/constants.py
ocs_ci/templates/ocp-deployment/dnsmasq.common.conf
ocs_ci/templates/ocp-deployment/dnsmasq.common.conf.j2
ocs_ci/templates/ocp-deployment/dnsmasq.pxe.conf
ocs_ci/templates/ocp-deployment/dnsmasq.pxe.conf.j2
ocs_ci/utility/connection.py

This PR should separate dnsmasq configuration from BM UPI deployment to separated methods to make it reusable in other types of deployment (e.g. via Assisted Installer).
There were only small functional changes:
* it uses `syslinux-tftpboot` instead of `syslinux-nonlinux` to get the fails required for PXE boot
* it sets the tftp root to `/tftpboot/` (based on what uses the syslinux-nonlinux package)
This is backport of [PR#9344](https://github.com/red-hat-storage/ocs-ci/pull/9344/)

BM UPI deployment - dnsmasq configuration - release-4.15

---

ocs_ci/utility/utils.py
tests/functional/upgrade/test_upgrade_ocp.py

display and archive ceph crashes in OCP upgrade

---

ocs_ci/ocs/awscli_pod.py
ocs_ci/templates/mcg/s3cli-sts.yaml
tests/conftest.py

Currently awscli_pod_fixture is creating s3cli and statefulset in openshift-storage and cleaning the same resources irrespective which testcase is created. since resource are deleted during setup, when running testcases throuh ITR, test cases are failing.

create s3cli in separate NS

---

tests/functional/pv/pvc_clone/test_pgsql_pvc_clone.py
tests/functional/pv/pvc_snapshot/test_pgsql_pvc_snapshot.py
tests/functional/workloads/pvc_snapshot_and_clone/test_cloned_and_restored_pvc_resize.py
tests/functional/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
tests/functional/workloads/test_new_sc_rbd_e2e_workloads.py

Added skip tags for tier2 workload tests in disconnected cluster and proxy cluster.
Added skip tags for disconnected and proxy cluster in three test files in workloads.

Skip tier2 workload tests in disconnected proxy clusters

---

ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/resources/stretchcluster.py
ocs_ci/utility/utils.py
tests/disaster-recovery/sc_arbiter/test_netsplit.py
tests/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py

This PR was raised to fix the loop holes in automation script where we failed to find the IO pause during netsplit window. I have fixed this by noting down the zones that are reported as out of quorum and making sure the zones available still be able to serve IO. Additionally, I noted that the read logs from the logreader jobs was very fequent and because of it stdout buffer was getting filled very soon and causing loss of logs. This log was very important to analyze if there was any read pause. I made neccessary changes to the logreader script and now its fixed.

[Stretch cluster] Detect IO pause during netsplit window

---

ocs_ci/ocs/ocp.py
tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py

Adding test cases for RHSTOR-4574- cephfs: snapshot/clone functionality for shallow volumes for the ROX accessModes
Issue: https://issues.redhat.com/browse/OCSQE-1300
Polarian IDs:
https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-5444
https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-5445
https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-5446
https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-5447

Adding Test cases for RHSTOR-4754

---

ocs_ci/ocs/ui/base_ui.py
ocs_ci/ocs/ui/storageclass.py
ocs_ci/ocs/ui/views.py
tests/cross_functional/ui/test_create_pool_block_pool.py
tests/cross_functional/ui/test_creation_and_deletion_of_sc_and_rbdpool.py

Tests were fixed with locator fix and page_has_loaded injections.
The management console ui elements and transition flow changes frequently, which is a reason of the failures. 
Considering the tests are mostly UI and similar tests implemented with CLI approach are existing, I moved tests to **black squad** to not loose them from view and tune in timely manner.
Fixes: #6980
Fixes: #6302
Fixes: #9026
Fixes: #9462

test_new_sc_new_rbd_pool and test_create_delete_pool fixed, moved to black squad

---

ocs_ci/framework/pytest_customization/ocscilib.py

with PR: https://github.com/red-hat-storage/ocs-ci/pull/9182 Since we reorganized the directory, we must update the path correctly in order to gather the ocp logs for the failed z_cluster test.

Collect OCP logs for whole z_cluster directory

---

conf/examples/acm_hub_unreleased_image.yaml
conf/examples/submariner_unreleased_image.yaml
ocs_ci/deployment/deployment.py
ocs_ci/ocs/acm/acm.py

This PR allows users to specify the desired versions of ACM and Submariner during installation. 
Previously, the latest versions were always pulled.

Allow user-specified versions for installing unreleased ACM and Submariner

---

tests/manage/mcg/test_bucket_policy.py

release-4.14 backport of #9057

[release-4.14 backport] `test_anonymous_read_only`: Use s3_get_object with retry 

---

tests/functional/object/mcg/test_bucket_policy.py

Fixes: #9446
Required backports:

Add hardcoded sleep after applying the policy in `test_bucket_policy.py::test_object_actions`

---

ocs_ci/deployment/vmware.py

Remove the Kubernetes manifest files that define control plane machine sets according to OCP documentation.

remove control-plane machine-set

---

ocs_ci/ocs/constants.py
ocs_ci/templates/app-pods/nfs_test_app.yaml
tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py

Updated test_respin_app_pod_exported_nfs_volume_incluster to handle deployment deletion and pvc deletion if test fails. Fixes #9172

Modify test_respin_app_pod_exported_nfs_volume_incluster to address teardown of deployment pod and pvc

---

tests/functional/monitoring/conftest.py
tests/functional/monitoring/prometheus/alerts/test_ceph.py

- Fixes https://github.com/red-hat-storage/ocs-ci/issues/8138
- Fixes https://github.com/red-hat-storage/ocs-ci/issues/9509

increase alert cleared timeout for test_ceph_health and alert collection for measure_noobaa_ns_target_bucket_deleted

---

ocs_ci/framework/conf/default_config.yaml
ocs_ci/helpers/sanity_helpers.py
ocs_ci/ocs/cluster.py
ocs_ci/ocs/constants.py
tests/libtest/test_sanity_provider_mode.py

The PR implements a new sanity helper class `SanityProviderMode` for the Provider Mode platform, that will extend the existing class `Sanity` with the following functionalities:
- Create and delete resources and run IO on multiple clients(It will use the fixture `create_scale_pods_and_pvcs_using_kube_job_on_hci_clients` to create the pods and PVCs and run IO on multiple clients).
- If the test runs on the provider, it will also check the cluster health of all the clients(Unless specified otherwise in the relevant param).

Create a new sanity helper class "SanityProviderMode" for the Provider Mode platform

---

tests/cross_functional/performance/csi_tests/test_pod_reattachtime.py

This PR handles 2 issues: 
1) Increasing pod creation timeout in test_pod_reattachtime.py test following failures on this.
From https://github.com/red-hat-storage/ocs-ci/issues/9336 :
The following test cases failed :
[tests.cross_functional.performance.csi_tests.test_pod_reattachtime.TestPodReattachTimePerformance.test_pod_reattach_time_performance[CephFileSystem-3-120-70]](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/35137/testReport/tests.cross_functional.performance.csi_tests.test_pod_reattachtime/TestPodReattachTimePerformance/test_pod_reattach_time_performance_CephFileSystem_3_120_70_/)
Error:
ocs_ci.ocs.exceptions.PerformanceException: Pod creation time is 87.04964661598206 and greater than 70 seconds …

test_pod_reattachtime.py  - Increasing pod creation timeout and reducing number of files for cephfs many files test case 

---

ocs_ci/helpers/performance_lib.py
tests/cross_functional/performance/csi_tests/test_pvc_multi_snapshot_performance.py

This PR contains :
* adding retries while searching logs , to overcome occasional network disconnections. 
* ignoring exception on ceph pool deletion ( fix of occdasional teardown failures) - similarly to the way it is implemented in test_pvc_clone_performance.py test ( lines 143-145) .

Fix to a multi snapshots test 

---

tests/manage/mcg/test_bucket_policy.py

release-4.14 backport of #9447

[release-4.14 backport] Add hardcoded sleep after applying the policy in `test_bucket_policy.py::test_object_actions`

---

ocs_ci/framework/pytest_customization/marks.py
ocs_ci/ocs/resources/objectbucket.py
tests/conftest.py

Add a way of fetching the marks of the current test from anywhere in ocs-ci and increase the verification timeout of obc deletion on tier4 tests

---

tests/conftest.py
tests/manage/mcg/test_s3_with_java_sdk.py

This is backport of https://github.com/red-hat-storage/ocs-ci/pull/8301 to `release-4.13` branch.

update various pods with proxy env vars - release-4.13

---

.github/CODEOWNERS

The latest directory restructure of OCS-CI has left obsolete paths in the CODEOWNERS file, which means that squads are no longer being requested to review or get notified of changes to tests under their main directories. 
This PR updates these paths as closely as possible to the original structure.

Update the squad paths under CODEOWNERS

---

ocs_ci/ocs/ui/views.py

Fix test_create_delete_pool UI tests that were failing on 4.16:
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/36175/testReport/

Fix pool deletion via UI

---

ocs_ci/ocs/bucket_utils.py
tests/cross_functional/system_test/test_mcg_replication_with_disruptions.py

The fix for this bug https://bugzilla.redhat.com/show_bug.cgi?id=2266805 requires us to remove the replication policy by setting replicationPolicy: "". And also some other minor fixes

Fix log based replication deletion

---

ocs_ci/ocs/constants.py
ocs_ci/utility/cco.py

Related W/A issue:
https://github.com/red-hat-storage/ocs-ci/issues/9674

W/A for ccoctl and glibc_2.34 not found

---

ocs_ci/ocs/exceptions.py
ocs_ci/ocs/resources/osd_resize.py
ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/resources/pv.py
ocs_ci/ocs/resources/pvc.py
ocs_ci/ocs/resources/storage_cluster.py
tests/functional/z_cluster/cluster_expansion/test_resize_osd.py

The PR implements the basic test scenario of the resize osd feature. For more details about the feature, see https://issues.redhat.com/browse/RHSTOR-5251, and for the test details, see the test plan spreadsheet: https://docs.google.com/spreadsheets/d/1wCSwMk_L4SikzZ2UarUH1-VCXyGkHs-ZNdDEtWPG7f4/edit#gid=105186681&range=B8. 
In the test, we will perform the following:
- Prepare all the relevant data before the resizing(Save the old pods, PVCs, PVs, create pods and PVCs and run IO, save the file md5sum). 
- Resize the osd by multiplying 2(This will be done by patching the storagecluster storage param).
- Check that the resources are in the expected state and that the new size is reflected in the resources and Ceph. Also, check that the md5sum of the files didn't change after the resize osd. …

Create new test file for testing resize OSD

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/ui/base_ui.py
ocs_ci/ocs/ui/page_objects/alerting.py
ocs_ci/ocs/ui/page_objects/page_navigator.py
ocs_ci/ocs/ui/page_objects/searchbar.py
ocs_ci/ocs/ui/views.py
tests/functional/ui/test_alert_text.py

Automation for https://issues.redhat.com/browse/RHSTOR-3613 and https://issues.redhat.com/browse/RHSTOR-5154
Validate alerts:
CephClusterErrorState CephClusterWarningState CephOSDVersionMismatch PersistentVolumeUsageCritical CephClusterCriticallyFull CephClusterNearFull CephClusterReadOnly CephMonVersionMismatch CephPoolQuotaBytesCriticallyExhausted CephPoolQuotaBytesNearExhaustion CephMgrIsAbsent CephMgrIsMissingReplicas CephMdsMissingReplicas CephMonQuorumAtRisk CephMonQuorumLost CephMonHighNumberOfLeaderChanges CephNodeDown CephOSDCriticallyFull ObcQuotaObjectsAlert ObcQuotaBytesExhausedAlert ObcQuotaObjectsExhausedAlert ClusterObjectStoreState KMSServerConnectionAlert ODFRBDClientBlocked OdfMirrorDaemonStatus OdfPoolMirroringImageHealth CephOSDFlapping CephOSDNearFull …

add runbooks for internal mode and provider mode clusters

---

conf/ocsci/dr_ui.yaml
tests/conftest.py
tests/functional/disaster-recovery/regional-dr/test_failover.py
tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate.py
tests/functional/disaster-recovery/regional-dr/test_relocate.py

This pull request addresses an issue where the setup_acm_ui fixture was running for all tests, including those focused on the CLI functionality. This caused unnecessary setup steps and test failures when running CLI tests.
Now, the fixture will only be executed when running tests with `conf/ocsci/dr_ui.yaml` conf.

Run setup_acm_ui fixture only for UI tests

---

tests/conftest.py

Fixes #9689 
Append ctx before workload deployment to ensure proper teardown even if the setup fails.

Fix teardown failures in dr_workload

---

conf/deployment/aws/ipi_3az_rhcos_3m_3w_ctrplane_hosting.yaml

AWS controle plan hosting cluster is required for onboarding ODF on AWS HCP cluster

Add deployment config of AWS control plane hosting cluster

---

tests/functional/object/mcg/test_bucket_policy.py

release-4.15 backport of #9447

[release-4.15 backport] Add hardcoded sleep after applying the policy in `test_bucket_policy.py::test_object_actions`

---

tests/cross_functional/scale/noobaa/test_warp.py

Since the GCP credentials got updated, remove skipped label for GCP credential issue for S3 benchmark warp test case.

Remove GCP skipped label.

---

tests/conftest.py

Fixed https://github.com/red-hat-storage/ocs-ci/issues/8809

Added retry when command failing if /nsfs not existing

---

tests/manage/mcg/test_bucket_policy.py

release-4.13 backport of #9447

[release-4.13 backport] Add hardcoded sleep after applying the policy in `test_bucket_policy.py::test_object_actions`

---

tests/manage/mcg/test_bucket_policy.py

release-4.13 backport of #9057

[release-4.13 backport] `test_anonymous_read_only`: Use s3_get_object with retry 

---

ocs_ci/ocs/constants.py
ocs_ci/utility/cco.py

Related W/A issue:
https://github.com/red-hat-storage/ocs-ci/issues/9674
Since OCP 4.16.0-0.nightly-2024-04-08-024331 is rotated out, use cco image directly

use cco image directly

---

tests/manage/mcg/test_endpoint_autoscale.py

* Fixed issue Endpoint pod count is not expected, Timed out after 900s. Endpoint pod count is not expected, Timed out after 900s running get("", True, "noobaa-s3=noobaa") https://github.com/red-hat-storage/ocs-ci/issues/8843

[release 4.14] cherry-pick: fixed issue with Endpoint pod count is not expected (#8857)

---

ocs_ci/ocs/scale_lib.py

Fixing 
As part of this fix, we are  getting default machineset zone from the cluster, instead of hard coded with single value as "a". Because when it is a single zone cluster we may get "a" or "b" or "c" as zone. So we are getting that value from the cluster deployed and parsing it in the test case.
#9477

Stabilize test_create_scale_pods_and_pvcs_using_kube_job

---

ocs_ci/framework/main.py
ocs_ci/utility/utils.py

In the Jenkins job, when it's aborted it's trying to SIGTERM with signal 15 which doesn't allow the pytest to finish gracefully.
With changing it to SIGINT, the pytest should attempt to finalize the fixtures and clean up the resources gracefully.

Handle SIGTERM as SIGINT for first attempt

---

tests/functional/storageclass/test_cross_sc_clone_snap_restore.py

As part of work on [RHSTOR-4130](https://issues.redhat.com//browse/RHSTOR-4130) in 4.16 this PR is a new test that implements the following flow: 
1. Create two storage classes in the same pool
2. Create a pvc in the first sc
3. Create a clone on the same sc
4. Create a clone on another sc
5. Create pvc's shapshot
6. Restore the snapshot on the same sc
7. Restore the snapshot on another sc
Test cases with similar flow for sc in different than pvc pool will be handled ceparately in another PR.

Addding a new test for cross sc clone and snapshot restore - in the same pool 

---

ocs_ci/deployment/flexy.py

This should fix following issue:
```
01:53:21 - MainThread - ocs_ci.utility.utils - INFO  - Cloning repository into /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/data/flexy-dir/flexy-ocs-private
01:53:21 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: git clone --depth=1 https://git-repository-url/flexy-ocs-private.git /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/data/flexy-dir/flexy-ocs-private
01:53:21 - MainThread - ocs_ci.utility.utils - WARNING  - Command stderr: fatal: could not create work tree dir '/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/data/flexy-dir/flexy-ocs-private': Permission denied
01:53:21 - MainThread - ocs_ci.deployment.deployment - ERROR  - Error during execution of command: git clone --depth=1 …
```

make sure flexy working directory is writable by group

---

tests/functional/pv/space_reclaim/test_rbd_reclaimspace_cronjob.py

When we calculate the used size of the pool, the negligible difference between the expected size and actual size is 1.5Gb, but in my case sometimes, very rarely, it exceeds 1.5Gb to 2Gb, because of that script will fail. In this test we calculate the pool size after creating 4 files cumulatively. So assumed, calculating the pool size after each file creation would resolve the issue.

Fix for the ocs-ci issue 7290

---

conf/ocsci/deploy_gitops_operator.yaml
ocs_ci/deployment/deployment.py

- Skip checking for gitops config as it's required every time 
- Install Gitops operator on both cluster
- Install gitopscluster only on active cluster

Skip checking for Gitops config

---

ocs_ci/helpers/disruption_helpers.py
ocs_ci/helpers/osd_resize.py
tests/functional/z_cluster/cluster_expansion/test_resize_osd.py

The PR implements two small test cases as described in the [OSD resize test plan](https://docs.google.com/spreadsheets/d/1wCSwMk_L4SikzZ2UarUH1-VCXyGkHs-ZNdDEtWPG7f4/edit#gid=105186681):
1. Test resize OSD when one of the worker nodes got restarted in the middle of the process.
2. Test resize OSD when one of the resources got deleted in the middle of the process.

Test resize OSD when one of the worker nodes got restarted or one of the resources got deleted in the middle of the process

---

ocs_ci/deployment/cnv.py

Need for creating this PR is that when we choose cluster for DR then there are 2 diff subscription api ie `subscriptions.apps.open-cluster-management.io` and `subscriptions.operators.coreos.com` so it's better to use full api path

Use full api path for subscription for CNV workload

---

ocs_ci/helpers/helpers.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/osd_operations.py
ocs_ci/utility/utils.py
tests/functional/z_cluster/nodes/test_disk_failures.py

https://bugzilla.redhat.com/show_bug.cgi?id=2234479
Test path:
```
tests/functional/z_cluster/nodes/test_disk_failures.py::TestDiskFailures::test_recovery_from_volume_deletion_cli_tool
```

Test CLI tool for disk replacement proceudre

---

ocs_ci/deployment/deployment.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/dr/dr_workload.py
ocs_ci/ocs/ocp.py
ocs_ci/templates/DR/clusterrolebinding_appset_pullmodel.yaml
tests/conftest.py
tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate.py

Starting ACM 2.10, appset gitops provides an option to choose between pull and push model, where push model was default so far. Starting ODF 4.16, we would recommend and switch to using pull model with ACM 2.10 and above versions.

Appset deployment using pull model

---

ocs_ci/deployment/deployment.py

Fixes: #9803 
Address deployment regression that emerged after recent code changes.
This pull request introduces a fix to prevent the GitOps operator from being deployed twice on the same cluster.

RDR deployment fix: Prevent duplicate deployments of GitOps operator

---

tests/functional/z_cluster/nodes/test_nodes_restart.py

Test_nodes_restart fails at sanity_helpers.create_resources stage with error service unavailable error post node restart, Hence adding retries to fix the issue

Fix test_nodes_restart test for timeout issue

---

conf/ocsci/dr_workload.yaml
tests/conftest.py
tests/functional/disaster-recovery/regional-dr/test_cnv_app_failover_and_relocate.py

Added tests to verify CNV based application (Subscription and ApplicationSet) deployment and failover/relocate between managed clusters on a RDR setup
CNV workload added in ocs-workloads: 
- https://github.com/red-hat-storage/ocs-workloads/pull/66
- https://github.com/red-hat-storage/ocs-workloads/pull/73

RDR+CNV app deployment and failover/relocate

---

tests/functional/disaster-recovery/regional-dr/conftest.py

Fixes: #9809 
This pull request fixes a typo in the check_subctl_cli fixture located in tests/functional/disaster-recovery/regional-dr/conftest.py.
The typo caused an AttributeError in functional tests due to a misspelling of the attribute name MULTICLUSER (should be MULTICLUSTER).

[RDR] Fix Functional Test: Typo in check_subctl_cli Fixture

---

ocs_ci/ocs/node.py

This fixes https://github.com/red-hat-storage/ocs-ci/issues/9709

Fix to address change in ceph osd status output format

---

tests/functional/odf-cli/test_pvc_stale_volume_cleanup_cli.py

Feature link: https://issues.redhat.com/browse/RHSTOR-5150
Test will deploy a ODF cluster (this feature is only available for version > 4.16)
1. Create Storage class with retain policy
2. Create PVC with the same storage class
3. Check of subvolumes
4. Delete the PVC
5. Check for subvolume, you will see a  stale subvolume
6. Delete the subvolume using odf-cli

Test for feature of cleanup of stale subvolumes

---

tests/functional/object/mcg/test_noobaa_db_cleartext_postgres_password.py
tests/functional/pod_and_daemons/test_noobaa_db_cleartext_postgres_password.py

https://bugzilla.redhat.com/show_bug.cgi?id=2274193

GSS bz-2274193 noobaa db cleartext postgres password

---

tests/functional/storageclass/test_cross_sc_clone_snap_restore.py

The new test case implements the following flow: 
1. Create first storage class on default pool
2. Create a pvc in the first storage class
3. Create second storage class on another pool
4. Clone pvc created on the first storage class to the second storage class
5. Create pvc's shapshot
6. Restore the snapshot to a pvc on the second storage class
Also , since previous test cases and the new one have common code - it was refactorred to a ceparate function, for more efficient coding.

Adding a new test case for clone/restore to a different pool

---

ocs_ci/ocs/resources/bucket_policy.py
tests/functional/object/mcg/test_bucket_policy.py

Test bucket policy for for NotPrincipal, NotAction and NotResource.

Bucket policy test cases for for NotPrincipal, NotAction and NotResource.

---

ocs_ci/deployment/assisted_installer.py

The `openshift_cluster_id` reference is not always available in the cluster details, so we have to ignore it if it is missing.

fix destroy of cluster installed via Assisted Installer

---

tests/functional/z_cluster/nodes/test_check_pods_status_after_node_failure.py

fix https://github.com/red-hat-storage/ocs-ci/issues/9820
I didn't move the small functions: `get_rook_ceph_pod_names_in_node` and `get_rook_ceph_pod_names_not_in_node` to the `pod` file because they are not typical and are more specific for this test.

Wait for change in the rook-ceph pods status associated with the node instead of the ones not in the node

---

tests/functional/pv/pv_services/test_rbd_rwx_pvc.py

Set fio parameter direct=1 for block volume mode RBD PVC in the test case 
tests/manage/pv_services/test_rbd_rwx_pvc.py::TestRbdBlockPvc::test_rbd_block_rwx_pvc

Set fio parameter direct in test_rbd_block_rwx_pvc

---

tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py

Increase the timeout value for restoring the PVC in the test tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py. This is to fix the issue given below.
Fixes #9483

Increase timeout for snapshot restore

---

ocs_ci/ocs/resources/storageconsumer.py
ocs_ci/utility/prometheus.py
tests/functional/monitoring/conftest.py
tests/functional/monitoring/prometheus/alerts/test_provider_client.py

* Fixes https://github.com/red-hat-storage/ocs-ci/issues/9394
* Fixes test_change_client_ocs_version_and_stop_heartbeat test case
* Updates check_alert_list function to correctly check alerts with same label but different message

Fix test_change_client_ocs_version_and_stop_heartbeat test

---

ocs_ci/templates/mcg/s3cli-sts.yaml
tests/functional/object/mcg/test_virtual_hosted_buckets.py

Fixes #9715 
Added "s3cmd" package in below container image
quay.io/ocsci/s3-cli-with-test-objects-multiarch:5.0
DOCKERFILE
```
FROM alpine:3.17
ADD test_objects /test_objects
RUN apk add --no-cache vim aws-cli bash s3cmd --repository https://dl-cdn.alpinelinux.org/alpine/v3.17/community
WORKDIR /aws
RUN chmod 777 /test_objects /aws
```

Fixes permission issue while adding package

---

conf/examples/acm_hub_unreleased_image.yaml
conf/examples/submariner_unreleased_image.yaml
ocs_ci/framework/conf/ocp_version/ocp-4.16-config.yaml

Update ACM version to 2.11 and Submariner version to 0.18.0 for OCP 4.16

[RDR] Bumps ACM and Submariner versions for OCP 4.16

---

ocs_ci/ocs/ui/views.py

Fixes: #9833 
Updated locator dict for Submariner (downstream_unreleased) UI installation to work with OCP 4.16

Update 4.16 locator for ACM page

---

tests/functional/pv/pvc_clone/test_node_restart_during_pvc_clone.py

Increase pod wait timeout in test test_worker_node_restart_during_pvc_clone. This Fixes #9449

Increase pod wait timeout in test test_worker_node_restart_during_pvc_clone

---

ocs_ci/framework/pytest_customization/marks.py
ocs_ci/helpers/keyrotation_helper.py
ocs_ci/ocs/constants.py
tests/functional/encryption/test_encryption_keyrotation.py

Following scenario is automated
Test to verify the key rotation of the OSD
Steps:
1. Disable Keyrotation and verify its disable status at rook and storagecluster end.
2. Record existing OSD keys before rotation is happen.
3. Enable Keyrotation and verify its enable status at rook and storagecluster end.
4. Set keyrotation status to every 3 minutes.
5. wait for 3 minute.
6. Verify the keyrotation is happen for each osd by comparing the old keys with new keys.
7. Change the keyrotation value to default.
Test to verify the keyrotation for noobaa.
Steps:
1. Disable Keyrotation and verify its Disable status at noobaa and storagecluster end.
3. Record existing NooBaa Volume and backend keys before rotation is happen.
4. Set keyrotation status to every 3 minutes.
5. wait for 3 minute.
6. Verify …

Keyrotation test automation scenarios

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/backingstore.py
tests/conftest.py
tests/libtest/test_clone_backingstore.py

Fixes: #9485
This PR also introduce a small libtest that verifies the cloning logic on various backingstore types.

Separate the cloning logic from `override_default_backingstore_fixture`

---

tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py

As per the [discussion](https://github.com/red-hat-storage/ocs-ci/pull/9811/files#r1606364971), we intent to skip running this test starting ODF 4.16.
Most of the steps in this test have to be modified according to the new 4.16 custom taint features. Here is the [PR](https://github.com/red-hat-storage/ocs-ci/pull/9808) for new test case.

Skip test_non_ocs_taint_and_toleration.py starting ODF 4.16

---

ocs_ci/ocs/resources/pod.py
tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py

The process for enabling the toolbox & adding tolerations to them had changed in ODF 4.15.
https://issues.redhat.com/browse/RHSTOR-5012
ODF 4.15 onwards we need to add an entry for "toolbox" in storagecluster CR
spec:
placement:
toolbox:
tolerations:
- effect: NoSchedule
key: xyz
operator: Equal
value: "true"

Add changes for toleration of toolbox pod

---

ocs_ci/ocs/ui/validation_ui.py

Remove the Hardcoading of cluster namespace "openshift-storage" to use custom storage namespace depend og platform Fix#9870

Fix the use of hardcoded namespace to use of custom namespace

---

ocs_ci/helpers/helpers.py
tests/cross_functional/kcs/test_selinux_relabel_solution.py

Fix selinux relabeling testcase

---

tests/manage/storageclass/test_delete_rbd_pool_attached_to_sc.py

Backport the fix from PR #9790 to release-4.14 branch.
Due to directory restructuring, the automated cherry-pick workflow couldn't be used.

[release-4.14] Fix failure in test_delete_rbd_pool_associated_with_sc

---

ocs_ci/ocs/ui/validation_ui.py

In Test case test_ocs_operator_is_not_present the use of namespace "openshift-storage" is hardcoded, hence this test is failing on platform where custom name is used for ODF deployment, like ROSA/AWS HCP Fix for: https://github.com/red-hat-storage/ocs-ci/issues/9876

Fixes test_ocs_operator_is_not_present for utilizing custom namespace

---

tests/e2e/conftest.py
tests/e2e/workloads/app/amq/test_rgw_kafka_notifications.py

Fixes https://github.com/red-hat-storage/ocs-ci/issues/9008 and https://github.com/red-hat-storage/ocs-ci/issues/8461 in 4.14

Backport changes from PR-8367

---

tests/functional/pv/add_metadata_feature/test_metadata.py

Removed skip test marker form the  following metadata tests  since related issue fixed and closed https://github.com/red-hat-storage/ocs-ci/issues/8759
test_metadata_not_enabled_by_default[ocs-storagecluster-cephfilesystem-ocs-storagecluster-cephfs]
test_verify_metadata_details[ocs-storagecluster-cephfilesystem-ocs-storagecluster-cephfs]
test_metadata_details_available_only_when_metadata_flag_enabled[ocs-storagecluster-cephfilesystem-ocs-storagecluster-cephfs]
test_metadata_details_available_only_when_metadata_flag_enabled[ocs-storagecluster-cephblockpool-ocs-storagecluster-ceph-rbd]
test_metadata_update_for_PV_Retain[ocs-storagecluster-cephblockpool-ocs-storagecluster-ceph-rbd]

Removed skip test marker form the test

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/storage_cluster.py
tests/functional/z_cluster/test_performance_profile_validation.py

This automates test cases from [RHSTOR-4547](https://issues.redhat.com//browse/RHSTOR-4547)

Test to automate validation of performance profiles and change the performance profiles post deployment

---

ocs_ci/utility/ibmcloud.py

There seems to be some change and `ibmcloud iam account-policies` command is not available anymore:
```
$ ibmcloud iam account-policies --output json 
FAILED
'account-policies' is not a registered command. Check your list of installed plug-ins. See 'ibmcloud iam help'.
```
the command was probably replaced by `ibmcloud iam access-policies`

change ibmcloud iam account-policies to access-policies

---

ocs_ci/helpers/helpers.py
tests/internal/test_cephfilesystem_creation.py

Adding test to see if the cephfilesystem can not be created with the same name if it already exists
bug: https://bugzilla.redhat.com/show_bug.cgi?id=1969216
Polarian: [OCS-5793](https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-5793)

 Cephfilesystem creation test based on bug

---

conf/deployment/ibmcloud/ipi_1az_us_east1_rhcos_3m_3w.yaml
conf/deployment/ibmcloud/ipi_1az_us_east2_rhcos_3m_3w.yaml
conf/deployment/ibmcloud/ipi_1az_us_east3_rhcos_3m_3w.yaml
conf/deployment/ibmcloud/ipi_3az_rhcos_3m_3w.yaml
conf/deployment/ibmcloud/ipi_3az_rhcos_lowerreq_3m_3w.yaml
conf/ocsci/ibmcloud_region_dynamic_switching.yaml
ocs_ci/deployment/ibmcloud.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/defaults.py
ocs_ci/ocs/exceptions.py
ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
ocs_ci/utility/cco.py
ocs_ci/utility/ibmcloud.py
tests/conftest.py

This PR contains backports of following PRs:
* [PR#9640](https://github.com/red-hat-storage/ocs-ci/pull/9640) use region dynamically for IBM cloud based on load balancers
* [PR#9774](https://github.com/red-hat-storage/ocs-ci/pull/9774) Add functionality for IBM Cloud Account Policies and Service IDs cleanup
* [PR#9591](https://github.com/red-hat-storage/ocs-ci/pull/9591) download ccoctl from image for IBM cloud
* [PR#9780](https://github.com/red-hat-storage/ocs-ci/pull/9780) Add zones to ibm cloud ipi
* [PR#9915](https://github.com/red-hat-storage/ocs-ci/pull/9915) change ibmcloud iam account-policies to access-policies

Backport ibm cloud fixes and enhancements - release 4.15

---

ocs_ci/framework/pytest_customization/ocscilib.py

While fetching the osd_size parameter we were missing the suffix , hence in case of multicluster this returns none and we will not have the value of osd_size which actually looks like osd_size{suffix} in case of multicluster.

Add suffix to the osd_size parsed argument

---

ocs_ci/helpers/keyrotation_helper.py
tests/functional/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py

Added OSD keyrotation  verification checks in the `test_add_capacity_entry_exit_criteria.py` test.

Keyrotation verification added in the add_capacity test

---

tests/conftest.py

Volumesnapshot class names are not constant anymore in client clusters. Updated the snapshot restore fixture to handle this.
Fixes #9943

Update snapshot fixture to handle provider mode client

---

docs/usage.md
ocs_ci/framework/main.py
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/framework/testlib.py
ocs_ci/ocs/ocp.py
ocs_ci/utility/environment_check.py
ocs_ci/utility/resource_check.py
ocs_ci/utility/utils.py
tests/conftest.py
tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py

This PR will allow us to run ocs-ci to run parrallely with ITR framework and it shouldn'tcause any functionality break of existing flow.
Introduces below 3 cli parameters
--disable-environment-checker: this will disable the left over checks in existing flow
--resource-checker: this will identify the leftover which was created by test cases. This is similiar to environment-checker, only difference is resource-checker will track the resources created during test case run where as environment-checker will track all resources in cluster irrespective of who created.
--kubeconfig: location of kubeconfig. 

ITR - Allow ocs-ci to run parallely

---

ocs_ci/ocs/ui/validation_ui.py

tests/cross_functional/ui/test_validation_ui.py::TestUserInterfaceValidation::test_dashboard_validation_ui
https://bugzilla.redhat.com/show_bug.cgi?id=2185042

GSS automation, Verify  "Used Raw Capacity"  string in  System Capacity card 

---

ocs_ci/utility/workloadfixture.py

rerun_filter function needs to have defined parameters

Fix rerun_filter for ignore_next_measurement_file

---

tests/functional/pv/pv_services/test_rbd_image_metadata.py

This PR fixes https://github.com/red-hat-storage/ocs-ci/issues/9966
Currently, we create source pvc with block volumemode but during restore snapshot , by default it take filesystem, which causes test case to fail.
This fix add additional param called volume_mode to snapshot_restore_factory

Adding volumeMode param to snapshot_restore_factory

---

tests/functional/object/mcg/test_write_to_bucket.py

This PR automates
https://bugzilla.redhat.com/show_bug.cgi?id=2264480
https://bugzilla.redhat.com/show_bug.cgi?id=2259189

Test noobaa db activitylogs table for unnecessary logs when in default log level

---

ocs_ci/helpers/osd_resize.py
ocs_ci/ocs/constants.py
ocs_ci/utility/utils.py
tests/conftest.py
tests/functional/z_cluster/cluster_expansion/test_resize_osd.py

Create two new test cases: 
- Test resize osd when the cluster capacity is near full
- Test resize osd for large differences
- Add the MAX cluster size, and check that the expected size is less than the Max cluster size.
- Add verification steps for OSD encryption.

Create two new test cases for resize osd and add verification for OSDs encryption

---

ocs_ci/ocs/resources/pvc.py

This fixes several cases on provider mode where the deviceset name is different from on prem mode.

use deviceset name from StorageCluster definition

---

ocs_ci/framework/conf/ocp_version/ocp-4.16-ga-config.yaml
ocs_ci/framework/conf/ocp_version/ocp-4.16-ga-minus1-config.yaml
ocs_ci/framework/conf/ocp_version/ocp-4.16-ga-upgrade.yaml

Adding OCP 4.16-ga files

---

ocs_ci/utility/prometheus.py

- Variable name target_alerts conflicted with previously defined variable.
- Fixes https://github.com/red-hat-storage/ocs-ci/issues/10019

Fix variable name to allow search for firing alerts

---

ocs_ci/deployment/hosted_cluster.py

we fail to reach fields that are instantiated in the Deployment constructor. Addressing this.
The issue is seen below:
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/39107/

add Deployment init to constructor

---

ocs_ci/deployment/deployment.py

I moved the old section on modifying the operator csv up into the loop on all operator csvs. I.e. now all csvs will undergo the modify_csv() procedure. In our special case, this worked out well and deplyoments are now OK with changed image references.

Fix broken modify_csv() feature #9869

---

ocs_ci/ocs/ocs_upgrade.py

check pv-backingstore pod before upgrade

---

tests/functional/z_cluster/cluster_expansion/test_resize_osd.py

As per the discussion here: https://app.slack.com/client/E27SFGS2W/C06DWD30QTZ, we decided to remove this feature from 4.16.
We need to skip all the tests in the resize osd feature until the related BZs are fixed and the feature is ready.
In the PR, we skip the resize osd tests until the following BZs are fixed:
- https://bugzilla.redhat.com/show_bug.cgi?id=2279843
- https://bugzilla.redhat.com/show_bug.cgi?id=2295778

Skip all the tests in the resize osd feature until the related BZs are fixed

---

tests/functional/pv/pv_services/test_rwop_pvc.py

This PR adds the following flow to RWOP test : 
- after we make sure that only one pod with the same priority can be attached to RWOP PVC, we resize the PVC and try to create another pod with the same priority and attach it to the PVC, making sure the operation will still not success.

Adding pvc resize functionality to RWOP test

---

ocs_ci/ocs/node.py
tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_clone.py
tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
tests/manage/pv_services/pv_encryption/test_kmip_rbd_pv_encryption.py
tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption.py
tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
tests/ui/test_pv_encryption_ui.py

[cherry-pick-9177][Release 4.12] Replacing crypt device check from pod to node.

[cherry-pick-9177][Release 4.12] Replacing crypt device check from pod to node.

---

tests/functional/z_cluster/cluster_expansion/test_add_capacity.py

We saw multiple failures on VSphere IPI for test `test_add_capacity_ui` with data re-balance issue however the test passes on AWS IPI. Increasing the re-balance timeout should stabilise it.

Increase timeout for allow successful data re-balance on VSphere/Azure platforms

---

tests/functional/pv/pv_services/test_rwop_pvc.py

This PR adds pod deletion to the esxisting functionality of RWOP test and verifies that after the first pod is deleted, the second pod is attached to the PVC and reaches status Running.

Adding pod deletion and verification that second pod is reaching Running state 

---

ocs_ci/framework/pytest_customization/marks.py
tests/functional/pv/pv_encryption/test_azure_kms_pv_encryption.py

Added skip marker to test if azure KV config is not set.

Added skip marker to test if azure KV config is not set.

---

ocs_ci/utility/utils.py
ocs_ci/utility/version.py

[release-4.15]: download OCP nightly through GA'ed version incase of failures

---

tests/functional/pv/pv_services/test_rwop_pvc.py

This PR contains adding new test cases for creating clone and snap and snap restore for rwop pvc for both RBD and CephFS interfaces.

Adding new test cases for creating clone and snap and snap restore for rwop pvc

---

ocs_ci/helpers/helpers.py
tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py

This test implements the following flow:
1) Creating a RWO PVC for RWD/CephFS pvcs
2) Implementing migration prodecure ( https://kubernetes.io/docs/tasks/administer-cluster/change-pv-access-mode-readwriteoncepod/#migrating-existing-persistentvolumes )
3) After PVC mode is changed from RWO to RWOP - verifying that after the first pod is attached , the second pod with the same priority is not attached to the PVC and is in status Pending.
4) A change in helpers.py to create a PVC on a specific PV.

Adding a new test for rwo to rwop migration

---

tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py

This PR contains changing tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py  marker from tier1 to tier2

Changing tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py  marker from tier1 to tier2

---

ocs_ci/ocs/ui/add_replace_device_ui.py
ocs_ci/ocs/ui/views.py
ocs_ci/utility/localstorage.py
tests/functional/z_cluster/cluster_expansion/test_add_capacity.py

Failure seen in https://url.corp.redhat.com/9c00079
When existing locator was checked, the data test attribute has changes in and it also has a missing closing bracket.
Before-
`"kebab_storage_cluster": ('button[data-test-id="kebab-button"', By.CSS_SELECTOR),`
After-
`"kebab_storage_cluster": ('button[data-test="kebab-button"]', By.CSS_SELECTOR),`

Fix kebab menu locator for add capacity UI test

---

ocs_ci/helpers/sanity_helpers.py
tests/functional/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py

fix #10064 
Also, the PR fixed two other small issues:
- fix #10062 
- fix #10063

Reduce the number of PVCs created and IO running in the test "tests/functional/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py"

---

ocs_ci/helpers/helpers.py
tests/functional/pv/pv_services/test_rwop_pvc.py
tests/functional/pv/pv_services/test_rwop_pvc_reclaim_space.py

This PR contains the following: 
1) Adding a new test case for creating reclaim space job and reclaim space cron job on RWOP PVC
2) Two new functions in helpers.py for testing the desired job/cronjob status.

Adding a new test case for reclaim space job and cronjob on rwop pvc

---

tests/internal/test_secrets_on_pods.py

Completing Checks for bugs 
- https://bugzilla.redhat.com/show_bug.cgi?id=2171965 
- https://bugzilla.redhat.com/show_bug.cgi?id=2144067 
- https://bugzilla.redhat.com/show_bug.cgi?id=2180732

Adding test to check for values in securityKeyRef in pod

---

ocs_ci/ocs/node.py

vsphere ipi deployment - not all nodes created

---

ocs_ci/ocs/bucket_utils.py

Fix s3_list_objects_v2 function keyword args default value

---

tests/functional/pv/space_reclaim/test_auto_reclaim_space_cronjob.py

This PR Disables following tests.
test_reclaim_space_cronjob
test_reclaim_space_cronjob_on_existing_namespace
test_skip_reclaim_space
These tests would validate auto create of reclaim space cron job for namespaces with prefix `openshift-*` by adding reclaimspace cron job annotation to the namespace. As there was an issue with ARO cluster, this feature was removed and will be implemented at storageclass level rather than at the namespace level in 4.17
4.17 EPIC to implement the same at storageclass level - https://issues.redhat.com/browse/RHSTOR-5876

Disable auto reclaimspace cronjob test at namespace level

---

ocs_ci/ocs/cluster.py
tests/functional/z_cluster/upgrade/test_check_pdb_post_upgrade.py

https://bugzilla.redhat.com/show_bug.cgi?id=2264553

change pdb max unavailable to 2 if we have at least 5 mons in a cluster

---

ocs_ci/ocs/resources/pod.py

fix [issue](https://github.com/red-hat-storage/ocs-ci/issues/10012)

removed osd_removal_job support for versions older than 4.6

---

ocs_ci/deployment/deployment.py

MDR runs were failing because while creating credentials for s3 we were passing only access key.

Pass secret key as one of the arguments to create credentials

---

tests/conftest.py
tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate.py

This pull request updates the dr_workload fixture to prioritize user-defined appset_model value. If model value is not specified, the default behavior now uses "pull" model for ODF versions 4.16 and above.
Removes redundant "pull" model tests from `test_failover_and_relocate.py` as they are now covered by the default behavior for ODF 4.16 and above.

Update dr_workload fixture and test_failover_and_relocate.py

---

tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py

The aim of this PR is automatic reboot of NFS Client VM in case it is not accessible.
To make this work properly, following two new configuration parameters are required:
```
ENV_DATA:
nfs_client_vm_cloud: NAME_OF_CLOUD_DEFINED_IN_CONFIG
nfs_client_vm_name: NFS_CLIENT_VM_NAME
```
The logic is, that it firstly try to connect to the NFS Client VM and if it fails, it reboots it, wait some time and try to connect again (with retry this time).

reboot nfs_client_vm if not accessible and retry connection

---

ocs_ci/deployment/deployment.py
ocs_ci/deployment/helpers/hypershift_base.py
ocs_ci/deployment/helpers/lso_helpers.py
ocs_ci/deployment/hosted_cluster.py
ocs_ci/deployment/metallb.py
ocs_ci/helpers/managed_services.py
ocs_ci/ocs/node.py
ocs_ci/ocs/resources/storage_client.py
ocs_ci/ocs/resources/storage_cluster.py
ocs_ci/ocs/scale_lib.py
ocs_ci/ocs/ui/deployment_ui.py
tests/libtest/test_provider_create_hosted_cluster.py

Changes:
-  fix leftover, to prevent issues such as https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/39701/consoleFull (metallb installation and latest OCP fetch from release notes)
- changed made ODF and Hosted cluster installation done by completing jenkins stage 1. Deploy OCP cluster stage 2. Install OD, dependencies and Hosted Cluster 
- clean ODF provider and native client validation. Fixed some issues failing on waiting just deployed resources
- ODF with "latest-4.16" now can be a version, set in
```
clusters: 
hcp416-bm2-a:
hosted_odf_version: "latest-4.16" 
```
- "--olm-disable-default-sources" parametrization added
FIXES #10160

Provider mode deployment with Hosted clusters

---

ocs_ci/ocs/cluster.py
ocs_ci/ocs/node.py
ocs_ci/ocs/resources/storage_cluster.py
ocs_ci/utility/decorators.py
tests/functional/z_cluster/nodes/test_nodes_restart_hci.py

The PR implements the following: 
- Create two new tests: `test_stop_provider_endpoint_node_and_check_client_connection` and `test_stop_provider_mgr_node_and_check_client_connection`.
- Update the tests in the file `tests/functional/z_cluster/nodes/test_nodes_restart_hci.py` to use the `SanityProviderMode` health checks.
- Create a new decorator `switch_to_client_for_function` for switching to the client cluster for the function execution.

Create two tests: "test_stop_provider_endpoint_node_and_check_client_connection'" and "test_stop_provider_mgr_node_and_check_client_connection"

---

ocs_ci/ocs/ui/block_pool.py
ocs_ci/ocs/ui/page_objects/edit_label_form.py
ocs_ci/ocs/ui/page_objects/storage_system_details.py
ocs_ci/ocs/ui/views.py
tests/functional/ui/test_error_improvements.py

Fixes tests.functional.ui.test_error_improvements.TestErrorMessageImprovements.test_blocking_pool_creation_rules failing due to UI changes in 4.17 related to Replica2 with cephfs: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/39732/testReport/tests.functional.ui.test_error_improvements/TestErrorMessageImprovements/test_blocking_pool_creation_rules/

Update pools locator

---

tests/cross_functional/performance/csi_tests/test_auto_reclaim_space_multi_clones.py

Disabling this test as creating reclaim space cron job for namespace with prefix openshift-* has been deprecated since 4.16. This will be implemented at storageclass level rather than at the namespace level in 4.17
This fixes https://github.com/red-hat-storage/ocs-ci/issues/10156

Disabling test_auto_reclaim_space_multi_clones test

---

ocs_ci/utility/utils.py

include back slash for url

---

conf/README.md
conf/ocsci/ceph_full_threshold.yaml
ocs_ci/deployment/deployment.py

EPIC:
https://issues.redhat.com/browse/RHSTOR-5929

Make Ceph Full threshold to be configurable

---

ocs_ci/helpers/disruption_helpers.py

The test case test_daemon_kill_during_pvc_pod_creation_deletion_and_io was failing with the error reported in the issue #9166.
This is due to the presence of the bash process by osd which is also present in the output of the process list filtered using "grep". To avoid this situation, use "pidof" command to get the process id.
Logs are also improved.
Fixes #9166

Fix the method to obtain pids of ceph daemons

---

ocs_ci/helpers/e2e_helpers.py
ocs_ci/ocs/longevity.py
tests/cross_functional/conftest.py
tests/cross_functional/longevity/test_stage2.py
tests/cross_functional/longevity/test_stage3.py
tests/cross_functional/longevity/test_stage4.py

Longevity enhancements

---

setup.py

Looks like this PR https://github.com/SergeyPirogov/webdriver_manager/pull/666 from webdriver-manager is a specific fix for issue isuue https://github.com/red-hat-storage/ocs-ci/issues/10173.
The webdriver-manager fix is in 4.0.2 new version

Bumping webdriver-manager version to 4.0.2 due to selenium issue

---

ocs_ci/ocs/ui/deployment_ui.py

The dev team removed the 'data protection' page from the storage system creation procedure. 
https://url.corp.redhat.com/77c7e95
4.17.0-45 [without  "data protection" page]
https://url.corp.redhat.com/6406492
4.17.0-37 [with  "data protection" page]
https://url.corp.redhat.com/6dd5f76

ODF4.17 UI deployment, remove 'data protection' page

---

tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py

Update the tests test_pvc_to_pvc_rox_shallow_vol_post_clone and test_pvc_to_pvc_rox_shallow_vol_clone to have the cephfilesystem name despite the mode of installation.
Fixes #10003

Fix cephfilesystem name in rox clone tests

---

ocs_ci/ocs/ui/base_ui.py
ocs_ci/ocs/ui/deployment_ui.py

Take more screenshot and add logs for BM LSO deployment

---

tests/functional/object/mcg/test_default_backingstore_override.py

These tests attempt to create a backingstore of the same type as the original default noobaaa backingstore, which can result in failure when the platform is not on vSphere. 
In the case of a disconnected cluster on the AWS platform, the default backingstore is using an AWS bucket so the tests attempts to create such a backingstore and fails.

Skip the default backingstore override tests in deployments with limited connectivity

---

ocs_ci/deployment/baremetal.py
ocs_ci/deployment/provider_client/storage_client_deployment.py
ocs_ci/ocs/resources/storage_client.py
ocs_ci/templates/ocs-deployment/provider-mode/ocs_storagecluster.yaml
ocs_ci/templates/ocs-deployment/provider-mode/ocs_storagecluster_updated.yaml

Added a flag, mark_masters_schedulable to mark master nodes scheduleble if required and csv major version check between native client and provider

Added a flag, mark_masters_schedulable to mark master nodes scheduleable

---

ocs_ci/framework/pytest_customization/marks.py
tests/functional/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py

fixes https://github.com/red-hat-storage/ocs-ci/issues/10088

[release-4.15] Skip test_automated_recovery_from_stopped_node_and_start on compact mode deployment

---

conf/deployment/baremetal/ai_1az_rhcos_nvme_intel_3m_3w.yaml
conf/deployment/baremetal/upi_1az_rhcos_compact_mode.yaml
conf/deployment/baremetal/upi_1az_rhcos_multus_cluster_nvme_intel_3m_3w.yaml
conf/deployment/baremetal/upi_1az_rhcos_multus_nvme_intel_3m_3w.yaml
conf/deployment/baremetal/upi_1az_rhcos_multus_public_nvme_intel_3m_3w.yaml
conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml
conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_4w.yaml
conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_5w.yaml
conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_mcg_only_3m_3w.yaml
conf/deployment/baremetal/upi_1az_rhel_nvme_intel_3m_3w.yaml

- remove `disk_pattern` option from baremetal configuration files as this is environment specific and will be configured in credentials file for the particular environment
- this PR has to be merged together (or after) related MR with credential config files update

Remove environment specific `disk_pattern` configuration from baremetal config files

---

tests/functional/pv/pv_services/test_rwop_pvc_reclaim_space.py

This PR contains only adding polarion ids to tests/functional/pv/pv_services/test_rwop_pvc_reclaim_space.py for ODF 4.16 functionality testing.

Adding polarion ids to tests/functional/pv/pv_services/test_rwop_pvc_reclaim_space.py

---

tests/functional/storageclass/test_cross_sc_clone_snap_restore.py

This PR contains only adding polarion ids to tests/functional/storageclass/test_cross_sc_clone_snap_restore.py for ODF 4.16 functionality testing.

Adding polarion ids to tests/functional/storageclass/test_cross_sc_clone_snap_restore.py

---

tests/functional/pv/pv_services/test_rwop_pvc.py

This PR contains only adding polarion ids to tests/functional/pv/pv_services/test_rwop_pvc.py for ODF 4.16 functionality testing.

Adding polarion ids to tests/functional/pv/pv_services/test_rwop_pvc.py

---

tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py

This PR contains only adding polarion ids to  tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py for ODF 4.16 functionality testing.

Adding polarion id to tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py

---

ocs_ci/ocs/constants.py

Add list of required packages for disconnected ODF 4.17 deployment.
fixes: https://github.com/red-hat-storage/ocs-ci/issues/10262

Fix disconnected ODF 4.17 deployment

---

tests/functional/z_cluster/test_ceph_default_values_check.py

Decorate the test case to run on provider cluster when running in provider mode multicluster configuration.
Test case : tests/functional/z_cluster/test_ceph_default_values_check.py::TestCephDefaultValuesCheck::test_noobaa_postgres_cm_post_ocs_upgrade
Fixes #10307

Add runs_on_provider decorator in test_noobaa_postgres_cm_post_ocs_upgrade

---

conf/README.md
ocs_ci/deployment/deployment.py

- add `DEPLOYMENT.lso_standalone_deployment` parameter to allow LSO deployment separately (without ODF)
- this change will be helpful for HCP scenarios

allow standalone LSO deployment (without ODF)

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/storage_cluster.py

Verify the owner of CSI deployments and daemonsets in provider mode cluster.
Changes done: Removed the if condition and updated the logs statements. Added new constant.

Verify the owner of CSI deployments and daemonsets in provider and client

---

ocs_ci/ocs/bucket_utils.py

When creating GCP and Azure Backingstores via OC + YAMLs, we've been using `openshift-storage` namespace regardless of the actual namespace we're using in a run. This PR simply sets the namespace from `config.ENV_DATA["cluster_namespace"]`.

Set the namespace dynamically in OC BS creation of GCP and Azure

---

ocs_ci/utility/utils.py

use oc instead of specific rhel version in extracting client

---

tests/functional/pv/pv_services/test_pvc_creation_in_megabytes.py

Link to BZ : [2239208](https://bugzilla.redhat.com/show_bug.cgi?id=2239208)
This  new test case will take care of:
1. Creating Cephfs PVC with small size 499M, 500M, 501M.
2. Passing size_unit as 'M' [mega-bytes] and the created PVC size will be displayed in 'Mi' format in pvc yaml.
3. Verifying the created PVC size by converting it from 'Mi' [mebi-bytes] to 'bytes' and comparing it with the given size.
4. The expectation here is the created PVC sized should be greater than or equal to the given size. It should not be lesser than the given size.

[Close loop BZ: 2239208] Test case to create PVC in megabytes

---

ocs_ci/deployment/helpers/odf_deployment_helpers.py
ocs_ci/ocs/defaults.py

Add ceph-csi operator to the list of csvs. This ensures proper verification of cephcsi-operator csv status.
Applicable for versions from 4.17.

Add cephcsi-operator in the list of required csv

---

ocs_ci/framework/testlib.py
tests/functional/object/mcg/test_nsfs.py

The checking for leftover resources after a test suite(=PyTest test class), comparisons are made between the list of pods in the cluster from before and after the tests . However, some MCG tests might remove original endpoint pods and create new ones due to scaling or mounting of PVCs, thus raising a false ResourceLeftoversException.
This PR aims to ignore these false "discrepancies" by adding `ignore_leftover_label` label to the base `MCGTest` class.

Ignore noobaa-endpoint pods leftovers in MCG tests

---

ocs_ci/helpers/helpers.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/resources/storage_cluster.py
tests/functional/object/mcg/test_noobaa_db_cleartext_postgres_password.py
tests/functional/object/mcg/test_noobaa_secret.py

This PR addresses:
1. Automate bug: https://bugzilla.redhat.com/show_bug.cgi?id=2277186
2. PR #8981  introduced the test_noobaa_root_secret which is run as tier2 and also it does check post the ocs installation if secret is exposed. the check at installation verification is removed as it could potentially fail the deployment despite everything went right. Also made the test as acceptance to give it more priority there.
3. Automate bug: https://bugzilla.redhat.com/show_bug.cgi?id=2240778

[GSS] Test secrets are not exposed in Noobaa

---

ocs_ci/ocs/node.py
tests/functional/pod_and_daemons/test_cephtoolbox_pod_nodeaffinity.py

Automated below two tests from  https://docs.google.com/spreadsheets/d/1wCSwMk_L4SikzZ2UarUH1-VCXyGkHs-ZNdDEtWPG7f4/edit#gid=1509950578
**1.  Add nodeAffinity to cephToolbox pod**
Test steps:
"1) Identify the ceph toolbox running node. Let's say Compute-0
2) Add node affinity for the toolbox pod to run on a different node than it is running by updating the storagecluster CR.
Let's say set it to Compute-1
eg:
spec:
placement:
toolbox:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: kubernetes.io/hostname
operator: In
values: 
- compute-1
3) Check if the toolbox pod get's scheduled to the new node."
**2. "Fail the tool box pod node affinity node by rebooting the node**
Test steps:
"1) Add node affinity for the toolbox pod to run on …

[BZ-2249640] verify nodeAffinity for cephtoolbox pod

---

ocs_ci/helpers/dr_helpers.py
ocs_ci/ocs/dr/dr_workload.py
ocs_ci/ocs/resources/pvc.py
tests/conftest.py

This PR introduces improvements to the backend volume deletion verification process and other enhancements:
- Optimized backend volume verification: Instead of checking each backend volume individually on managed clusters, the entire list is now fetched from Ceph side and comparing against PVC-associated volumes. This reduces the number of command execution and improves performance.
- Redundant Code Removal: The code related to force deletion of resources has been removed as it was unnecessary and not suitable for CephFS based, other new types of workloads.

[DR] Improved backend volume deletion verification and removed redundant code

---

ocs_ci/framework/testlib.py
tests/functional/object/mcg/test_nsfs.py

release-4.15 backport of #10350

[release-4.15 backport] Ignore noobaa-endpoint pods leftovers in MCG tests

---

ocs_ci/framework/testlib.py
tests/functional/object/mcg/test_nsfs.py

release-4.16 backport of #10350

[release-4.16 backport] Ignore noobaa-endpoint pods leftovers in MCG tests

---

ocs_ci/deployment/helpers/external_cluster_helpers.py

remove rgw user "rgw-admin-ops-user" from external RHCS cluster if it exists since it will be created by external python script with all necessary caps.
This is to avoid any unnecessary deployment failure wrt to caps
bug: https://bugzilla.redhat.com/show_bug.cgi?id=2304135

remove rgw user from external RHCS

---

ocs_ci/helpers/keyrotation_helper.py
ocs_ci/ocs/resources/ocs.py
ocs_ci/utility/kms.py
tests/functional/pv/pv_encryption/test_pv_keyrotation.py

Test Encrypted PVC keyrotation.
Following steps will be verified with Vault KMS, using a combination of (v1, v2) and with and without Vault namespaces.
Steps:
1.	Create an encrypted RBD storage class.
2.	Add an annotation to the encrypted storage class.
"keyrotation.csiaddons.openshift.io/schedule='*/3 * * * *'"
3.	Configure the Persistent Volume (PV) encryption settings with the Vault service.
4.	Create a PVC using the encrypted storage class.
5.	Deploy a Pod that utilizes the previously created PVC for storage.
6.	Start an IO workload with verify=True option.
7.	Wait for the key rotation to occur for the PV.
8.	Check for any error messages that appear during the IO operation.

Test Automation for feature PV key rotation.

---

ocs_ci/deployment/helpers/hypershift_base.py
ocs_ci/ocs/cluster.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/platform_nodes.py
ocs_ci/utility/decorators.py
ocs_ci/utility/kubevirt_vm.py
ocs_ci/utility/utils.py
tests/functional/z_cluster/nodes/test_nodes_restart_hci.py

As part of the Provider mode platform testing, we need to test the hosted cluster node functionalities. 
Currently, we have two types of hosted clusters: `Kubevirt` and `Agent`. 
This PR is implementing the `Kubevirt` hosted cluster node functionalities. The `Kubevirt` nodes are VMs that run on the provider worker nodes. For performing the VM operations, we use the `virtctl` command line tool: https://docs.openshift.com/container-platform/4.16/virt/getting_started/virt-using-the-cli-tools.html#vm-management-commands_virt-using-the-cli-tools

Add the kubevirt VM node functionalities for the hosted cluster

---

conf/README.md
ocs_ci/deployment/deployment.py
ocs_ci/deployment/ingress_node_firewall.py
ocs_ci/ocs/constants.py
ocs_ci/templates/ingress-node-firewall-deployment/config.yaml
ocs_ci/templates/ingress-node-firewall-deployment/namespace.yaml
ocs_ci/templates/ingress-node-firewall-deployment/operatorgroup.yaml
ocs_ci/templates/ingress-node-firewall-deployment/rules.yaml
ocs_ci/templates/ingress-node-firewall-deployment/subscription.yaml

There is a requirement to be able to restrict SSH access to the OCP nodes. For that reason, we can install Ingress Node Firewall and configure rules to allow SSH access only from configured subnets.
This PR introduces two new `ENV_DATA` configuration variables:
* `restrict_ssh_access_to_nodes` - Deploy and configure Ingress Node Firewall Operator to restrict SSH access to nodes.
* `allow_ssh_access_from_subnets` - Defines a list of subnets wit allowed SSH access to nodes.
[OCSQE-2491](https://url.corp.redhat.com/edacc37)

Deploy and configure Ingress Node Firewall to be able to restrict SSH access to nodes.

---

tests/functional/z_cluster/test_ceph_default_values_check.py

fix https://github.com/red-hat-storage/ocs-ci/issues/10375

Remove the Bugzilla decorators from the test "test_check_mds_cache_memory_limit"

---

ocs_ci/deployment/deployment.py

Pass `osdSize` parameter to `ibmcloud ks cluster addon enable openshift-data-foundation ...` command to configure OSD Size.

Allow osd_size configuration for IBM Cloud Managed clusters

---

ocs_ci/helpers/helpers.py
tests/conftest.py
tests/functional/storageclass/test_storageclass_reclaim_space.py

Test Space Reclaim Operation with Storageclass annotation.
Steps:
1. Create a RBD storageclass with  reclaimspace annotations.
"reclaimspace.csiaddons.openshift.io/schedule: */3 * * * *".
2. Create a pvc
4. Create a pods
5. Write a 2.0GiB data on rbd block
6. destroy pod
7. wait for reclaimspace operation to be complete
6. verify reclaimspace Job ran successfully for the storageclass.

Test Automation for space reclaim with storageclass annotations.

---

ocs_ci/deployment/deployment.py

Pass osdSize parameter to ibmcloud ks cluster addon enable openshift-data-foundation ... command to configure OSD Size.
This is backport of https://github.com/red-hat-storage/ocs-ci/pull/10413

Allow osd_size configuration for IBM Cloud Managed clusters - backport to release 4.13

---

tests/functional/object/mcg/test_s3_routes.py

Update the test case to the latest expecations, and cover https://bugzilla.redhat.com/show_bug.cgi?id=2283797 by:
- Changing `spec.multiCloudGateway.denyHTTP` to true on the ocs-storagecluster resource
- Validating that as a result, `spec.tls.insecureEdgeTerminationPolicy` is reconciled to None on the S3 route

Update `test_s3_route_reconcile` to 4.16 expectations

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/storage_cluster.py

The name, label and ownerreference of provisioner and plugin pods has changed in provider mode.
The name prefix and label of these pods are replaced with the name of the respective drivers.
The change is currently applicable in provider and client clusters only.

[Provider mode] Update the verification of the number of CephFS, RBD pods and owner verification of deployments and daemonsets

---

setup.py

This change is necessary to support python 3.11. This got missed as a part of the initial work somehow.

Update numpy version to 1.23.2

---

ocs_ci/templates/workloads/helper_scripts/file_creator_io.py
ocs_ci/templates/workloads/helper_scripts/meta_data_io.py

This was introduced because of changes I am making to support python 3.11 which has temporarily made it so our PR checks weren't verifying logging statements.

Fix direct use of logging module

---

conf/README.md
ocs_ci/deployment/deployment.py
ocs_ci/deployment/ingress_node_firewall.py
ocs_ci/ocs/constants.py
ocs_ci/templates/ingress-node-firewall-deployment/config.yaml
ocs_ci/templates/ingress-node-firewall-deployment/namespace.yaml
ocs_ci/templates/ingress-node-firewall-deployment/operatorgroup.yaml
ocs_ci/templates/ingress-node-firewall-deployment/rules.yaml
ocs_ci/templates/ingress-node-firewall-deployment/subscription.yaml

There is a requirement to be able to restrict SSH access to the OCP nodes. For that reason, we can install Ingress Node Firewall and configure rules to allow SSH access only from configured subnets.
This PR introduces two new `ENV_DATA` configuration variables:
* `restrict_ssh_access_to_nodes` - Deploy and configure Ingress Node Firewall Operator to restrict SSH access to nodes.
* `allow_ssh_access_from_subnets` - Defines a list of subnets wit allowed SSH access to nodes.
[OCSQE-2491](https://url.corp.redhat.com/edacc37)
This is backport of https://github.com/red-hat-storage/ocs-ci/pull/10377

 Deploy and configure Ingress Node Firewall to be able to restrict SSH access to nodes - release-4.16

---

ocs_ci/deployment/deployment.py
ocs_ci/deployment/ingress_node_firewall.py

- extend timeout for Ingress Node Firewall deployment
- ignore any failure in the deployment and configuration, to not break whole deployment

ignore failure in Ingress Node Firewall deployment

---

ocs_ci/deployment/deployment.py
ocs_ci/deployment/ingress_node_firewall.py

- extend timeout for Ingress Node Firewall deployment
- ignore any failure in the deployment and configuration, to not break whole deployment
This is backport of https://github.com/red-hat-storage/ocs-ci/pull/10471

ignore failure in Ingress Node Firewall deployment - release-4.16

---

ocs_ci/ocs/ocs_upgrade.py
tests/conftest.py

fix failures like bellow
```
oc adm must-gather --image=quay.io/rhceph-dev/ocs-must-gather:latest-4.16 --dest-dir=/tmp/tmpabk43f_b_ocs_logs/dosypenk-59hcp/ocs_must_gather
[must-gather      ] OUT Using must-gather plug-in image: quay.io/rhceph-dev/ocs-must-gather:latest-4.16
When opening a support case, bugzilla, or issue please include the following summary data along with any other requested information:
ClusterID: a9a5c73f-ffeb-4249-93e1-986c1b38a189
ClusterVersion: Stable at "4.16.9"
ClusterOperators:
clusteroperator/insights is not available (Reporting was not allowed: your Red Hat account is not enabled for remote support or your token has expired: {"errors":[{"status":401,"detail":"UHC services authentication failed","meta":{"response_by":"gateway"}}]}
) because Reporting was not …
```

mustgather for rosa hcp. change the image regestry

---

tests/conftest.py
tests/functional/pv/pv_encryption/test_encrypted_pvc_no_expansion_option.py

This intermittent issue caused the test to exit with a `ResourceWrongStatusException` Upon checking the logs, I found the wait_for_resource_state function has a default timeout of 60s. It reported the PVC as ‘Pending’, but the must-gather logs showed it in ‘Bound’. This suggests the PVC sometimes takes longer to bind. I’ve increased the timeout to 120s (from the default 60s) to resolve this.
test exited due to PVC status in not reached to 'Bound' status.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=
```
E           ocs_ci.ocs.exceptions.ResourceWrongStatusException: Resource pvc-test-47565298be334d8eb0f2cc0c9f0887e describe output: Name:          pvc-test-47565298be334d8eb0f2cc0c9f0887e
E           Namespace:     namespace-test-13715505cce745548e9586ab8
E           StorageClass: …
```

Fix resource wrong status exception

---

ocs_ci/helpers/helpers.py
tests/functional/storageclass/test_rbd_default_storageclass.py

test `test_pvc_creation_without_storageclass_name` was failing in case of custom sorageclass present in the cluster and there are multiple default RBD storage class in the cluster.

Fixed default sc tests case which was failing

---

ocs_ci/ocs/ocs_upgrade.py

Fix to avoid error: 
> 2024-09-17 15:11:11          if (
> 2024-09-17 15:11:11              (live_deployment and upgrade_in_same_source)
> 2024-09-17 15:11:11              or (managed_ibmcloud_platform and not use_upstream_mg_image)
> 2024-09-17 15:11:11  >           or config["ENV_DATA"].get("platform") == constants.ROSA_HCP_PLATFORM
> 2024-09-17 15:11:11          ):
> 2024-09-17 15:11:11  E       TypeError: 'MultiClusterConfig' object is not subscriptable
> 2024-09-17 15:11:11  
> 2024-09-17 15:11:11  ocs_ci/ocs/ocs_upgrade.py:346: TypeError
https://github.com/red-hat-storage/ocs-ci/pull/10466/files#r1763307854

quick syntax fix

---

conf/README.md
ocs_ci/deployment/deployment.py
ocs_ci/ocs/constants.py
ocs_ci/templates/ocp-deployment/workaround-ssd-machine-config.yaml
ocs_ci/utility/deployment.py

This PR add possibility to create MachineConfig  defining new service `workaround-ssd`, which configures all sd* disks as SSD (not rotational).
This is useful for example on some Bare metal servers where are SSD disks not properly recognized as SSD, because of     wrong RAID controller configuration or issue.

WORKAROUND: add possibility to mark disks as ssd

---

ocs_ci/deployment/ingress_node_firewall.py

I've changed this timeout to 30 minutes in the previous PR, because I wasn't exactly sure about the root cause of failures during deployment (my initial assumption was, that it takes longer than expected). But since the reason is missing Ingress Node firewall Operator in the OCP 4.17 catalog source, it doesn't make much sense to uselessly extend the deployment time, while 15 minutes should be enough for normal deployment.

lower ingress node firewall timeout to 15 minutes

---

ocs_ci/ocs/utils.py

Remove client specific parameter "-pc" when collecting must-gather from client cluster. This enables must-gather to collect all resources including client specific resources.

Remove must-gather parameter -pc for clients

---

ocs_ci/ocs/ui/base_ui.py

fix to address cascade failures, when chtome browser closed but we still want to close it properly
```
def finalizer():
close_browser()
tests/conftest.py:4931: 
ocs_ci/ocs/ui/base_ui.py:1021: in close_browser
take_screenshot("close_browser")
ocs_ci/ocs/ui/base_ui.py:774: in take_screenshot
SeleniumDriver().save_screenshot(filename)
venv/lib64/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:1055: in save_screenshot
return self.get_screenshot_as_file(filename)
venv/lib64/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:1032: in get_screenshot_as_file
png = self.get_screenshot_as_png()
venv/lib64/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:1064: in get_screenshot_as_png
return base64.b64decode(self.get_screenshot_as_base64().encode('ascii')) …
```

try-exept_on_close_browser

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/ocp.py

In provider mode multicluster run, set 'cluster_kubeconfig' if the resource kind is available only in provider cluster.
* Created a primary list of 'Kind' which are available in provider cluster.
* Set the cluster_kubeconfig value to provider cluster kubeconfig path if the Kind is available in the list.
Advantages:
* When using the class OCP or OCS, need not switch cluster context to provider to get/create/delete/patch/decribe etc.. a resource that is in provider cluster.
Example: Need not bother about the current cluster context when using the function https://github.com/red-hat-storage/ocs-ci/blob/0b95c6fa7e9a190726079bfd3018daa190e0413b/ocs_ci/ocs/resources/storage_cluster.py#L1658 and also when using the returned object.
* Enables simultaneous usages of two instances of different …

Set cluster_kubeconfig based on the type of resource available in provider cluster only

---

tests/functional/object/mcg/test_noobaa_prometheus.py

Fixes #9489 
Response receiving to method:
`
19:30:27 - MainThread - mcg.test_noobaa_prometheus - INFO  - {'status': 'success', 'data': {'resultType': 'vector', 'result': [{'metric': {'__name__': 'NooBaa_bucket_used_bytes', 'bucket_name': 's3-bucket-2617cd552c404b46833d0f2712abd0', 'container': 'core', 'endpoint': 'mgmt', 'instance': '10.131.0.27:8080', 'job': 'noobaa-mgmt', 'namespace': 'openshift-storage', 'pod': 'noobaa-core-0', 'service': 'noobaa-mgmt'}, 'value': [1726754427.034, '0']}]}}
`
The type of `'value': [1726754427.034, '0']` is `str` and it is getting compared with `int 0` in below test
tests/functional/object/mcg/test_noobaa_prometheus.py::TestNoobaaaPrometheus::test_bucket_used_bytes_metric

Fixes incorrect comparison for test_bucket_used_bytes_metric

---

requirements.txt
setup.py

Use `ocp-network-split` from our fork https://github.com/red-hat-storage/ocp-network-split.git, because it contains important fix.

use ocp-network-split from red-hat-storage org fork

---

tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
tests/functional/odf-cli/test_pvc_stale_volume_cleanup_cli.py

Adding three tests:
OCS-6193 | Check for the NFS driver stale volume and then delete it
OCS-6194 | Check for ROX PVC stale volume can be deleted
OCS-6195 | Check for stale volume snapshots can be deleted

tests for rhstor5518

---

ocs_ci/helpers/helpers.py
ocs_ci/ocs/scale_lib.py
ocs_ci/utility/ibmcloud_bm.py

The PR fixes the following:
- Modify and add new login error messages that may happen when getting the IBMCloud Baremetal Server list. 
- Since sometimes the client storageclass names differ for different client types, get the current storageclass names when creating resources using "scale_lib".

Add another error message when getting the IBMCloud Baremetal servers

---

conf/README.md
ocs_ci/deployment/deployment.py

- introduce specific configuration parameter to enable deployment of hosted clusters: `DEPLOYMENT["deploy_hosted_clusters"]`

introduce deploy_hosted_clusters configuration parameter

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/resources/storage_cluster.py
ocs_ci/utility/utils.py
tests/functional/provider_mode/test_ceph_csi_image_versions.py

Check that the ceph-csi version matches the OCP version on the hosted clusters.
The test will perform the following:
1. Iterate over the clients
2. Get the ceph csi ctrl pods container images of the client
3. Get the csi images for the client OCP version
4. Check that the ceph csi ctr pod container images exist in the csi images of the client OCP version

Check that the ceph-csi version matches the OCP version on the hosted clusters

---

requirements.txt
setup.py

Use `ocp-network-split` from our fork https://github.com/red-hat-storage/ocp-network-split.git, because it contains important fix.
Backport of https://github.com/red-hat-storage/ocs-ci/pull/10505

use ocp-network-split from red-hat-storage org fork - release-4.14

---

requirements.txt

Use `ocp-network-split` from our fork https://github.com/red-hat-storage/ocp-network-split.git, because it contains important fix.
Backport of https://github.com/red-hat-storage/ocs-ci/pull/10505

use ocp-network-split from red-hat-storage org fork - release-4.13

---

requirements.txt

Use `ocp-network-split` from our fork https://github.com/red-hat-storage/ocp-network-split.git, because it contains important fix.
Backport of https://github.com/red-hat-storage/ocs-ci/pull/10505

use ocp-network-split from red-hat-storage org fork - release-4.12

---

tests/functional/pod_and_daemons/test_mgr_enable_rook_backend_module.py

[bz:2274165] Test to verify mgr does not crash after enabling rook module

---

tests/functional/pv/space_reclaim/test_rbd_space_reclaim.py

This PR addresses the issue [9560](https://github.com/red-hat-storage/ocs-ci/issues/9560)
In this test, reclaim space job was created immediately after the deletion of app pod, which caused the reclaim space job failure.
There was a miss to validate pod deletion prior to the creation of the reclaim space job. This PR adds the validation of pod deletion.

Add validation of pod deletion

---

ocs_ci/deployment/helpers/hypershift_base.py
ocs_ci/deployment/hosted_cluster.py

- create kubeconfig for hosted clusters in "standard" location (`auth/`  directory instead `auth_path/`)

fix kubeconfig path for hosted clusters

---

ocs_ci/helpers/keyrotation_helper.py
ocs_ci/utility/kms.py

Fixed PVKeyrotation tests failures

Fixed PVKeyrotation tests failures

---

ocs_ci/framework/main.py

Fixes issue:
```
2024-10-11 16:49:22      def signal_term_handler(sig, frame):
2024-10-11 16:49:22          print(f"Got SIGTERM: {sig}")
2024-10-11 16:49:22          if hasattr(framework.config, "RUN"):
2024-10-11 16:49:22              framework.config.RUN["aborted"] = True
2024-10-11 16:49:22          logdir = framework.config.RUN["log_dir"]
2024-10-11 16:49:22  >       with open(os.path.join(logdir, "traceback.log"), "w") as f:
2024-10-11 16:49:22  E       FileNotFoundError: [Errno 2] No such file or directory: '~/current-cluster-dir/logs/traceback.log'
2024-10-11 16:49:22  
2024-10-11 16:49:22  ocs_ci/framework/main.py:26: FileNotFoundError
```

Expand user in path for traceback log

---

tests/cross_functional/ui/test_odf_topology.py

Check the ODF topology UI and verify that it functions as expected.
https://bugzilla.redhat.com/show_bug.cgi?id=2245068

GSS-BZ-2245068: Add an unlabeled pod to the openshift-storage ns

---

ocs_ci/deployment/hosted_cluster.py

To fix, https://github.com/red-hat-storage/ocs-ci/issues/10647

Added networkpolicy creation for hosted clusters before creating storageclient

---

ocs_ci/utility/localstorage.py

with existing retry params func check_pvs_created will be executed during 3,631 years. 
I changed params to make it work only 1H to avoid this stucks and abortions:
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/13537/consoleText

make check_pvs_created last max 1H6m

---

ocs_ci/helpers/helpers.py
tests/functional/storageclass/test_rbd_default_storageclass.py

test test_pvc_creation_without_storageclass_name was failing in case of custom sorageclass present in the cluster and there are multiple default RBD storage class in the cluster.

[Cherry-Pick-10141][Release-4.16] Fixed default sc tests case which was failing

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/backingstore.py
tests/conftest.py
tests/libtest/test_clone_backingstore.py

release-4.15 backport of #9515

[release-4.15 backport] Separate the cloning logic from `override_default_backingstore_fixture`

---

tests/conftest.py

release-4.16 backport of #9892

[release-4.16 backport] Set a priviliged service account for the NSFS interface deployment for NSFS tests

---

tests/functional/object/mcg/test_multi_region.py

bz:2294723, test to update placement from spread to mirror of multiregion bucketclass

---

tests/cross_functional/system_test/test_nsfs_system.py

Fixes: #10016 
Combined changes of PR's 10599 and https://github.com/nagendra202/ocs-ci/pull/1 to stabilize the test case test_nsfs_system

Fix test_nsfs_system test case

---

ocs_ci/helpers/helpers.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/storage_cluster.py
tests/functional/z_cluster/test_performance_profile_validation.py

This fixes https://github.com/red-hat-storage/ocs-ci/issues/10053

Fixing test_performance_profile_validation

---

ocs_ci/ocs/resources/storage_cluster.py

For external mode upgrade, it took more time for storagesystem to get in expected state

increase retries ( 10 min ) to verify storagesystem status

---

ocs_ci/ocs/dr/dr_workload.py
tests/conftest.py

[RDR] Remove redundant argument from conftest.py and dr_workload.py

---

ocs_ci/helpers/dr_helpers.py
tests/functional/disaster-recovery/regional-dr/test_disable_dr.py

This test 
1. Creates appset based and subscription based workload,
2. Configures RDR
3. Perform disable dr on it, 
4. Validate drpc deletion, vrg deletion, pods, pvc on primary cluster

disable dr

---

ocs_ci/ocs/resources/pod.py
tests/functional/pod_and_daemons/test_csi_logs_rotation.py

This PR contains a new functional test tests/functional/pod_and_daemons/test_csi_logs_rotation.py to verify proper log rotation of csi plugin pods in openshift-storage namespace ( https://issues.redhat.com/browse/OCSQE-2149 )

Adding a new test for csi logs rotation feature

---

ocs_ci/templates/DR/observability-metrics-configmap.yaml

Since the existing configmap name is incorrect, metrics are not getting whitelisted and data is not reflecting on the graphs.

Fix configmap name to whitelist metrics needed for ACM observability on DR monitoring dashboard 

---

tests/cross_functional/ui/test_create_pool_block_pool.py
tests/cross_functional/ui/test_creation_and_deletion_of_sc_and_rbdpool.py
tests/functional/pv/pvc_snapshot/test_small_files_pvc_cloned_status.py

This PR increases timeout (Fix for [10029](https://github.com/red-hat-storage/ocs-ci/issues/10029)) and replaces black squad marker with green squad.

increasing timeout and add marker

---

ocs_ci/deployment/assisted_installer.py
ocs_ci/deployment/helpers/rosa_cluster_helpers.py
ocs_ci/deployment/rosa.py
ocs_ci/ocs/constants.py
ocs_ci/utility/deployment.py
ocs_ci/utility/rosa.py

1. tuned create_openshift_install_log_file  and added to rosahcp
2. added delete resources such as oidc-config, account-roles, etc into destroy_cluster

add ocp install log, delete cluster

---

tests/conftest.py

release-4.15 backport of #9452

[release-4.15 backport] Use the nsfs-deployment pod for file access commands in `nsfs_bucket_factory` instead of the noobaa-endpoint pods

---

tests/functional/object/mcg/test_bucket_delete_using_obc_creds.py

Adds test script for validating bucket delete operation using OBC generated credentials
GSS bug: https://bugzilla.redhat.com/show_bug.cgi?id=2301657#c16

Adds test script for validating bucket delete operation using OBC generated credentials

---

ocs_ci/ocs/bucket_utils.py
ocs_ci/ocs/constants.py
tests/conftest.py
tests/functional/object/mcg/test_obj_owner_md.py

This PR adds test coverage for the feature that was added in https://github.com/noobaa/noobaa-core/pull/8062
Specifically, the following test cases were added under `tests/functional/object/mcg/test_obj_owner_md.py::TestObjOwnerMD`:
- test_ownership_in_s3_buckets
- test_ownership_in_obc_buckets[aws-backingstore]
- test_ownership_in_obc_buckets[aws-nss]
- test_ownership_in_obc_buckets[azure-nss]
- test_ownership_in_obc_buckets[ibmcos-nss]

[4.17] RHSTOR-5501 Feature automation: Store relevant Owner metadata for MCG objects

---

ocs_ci/deployment/assisted_installer.py
ocs_ci/deployment/baremetal.py

From time to time, OCP deployment via assisted installer fails, because some of the node didn't properly boot to the mode. Usually it is sufficient to reboot the server once more time, which is the aim of this PR.
Related to: [OCSQE-2955](https://url.corp.redhat.com/4e960e8)

reboot server if not properly discovered by Assisted Installer

---

ocs_ci/deployment/helpers/external_cluster_helpers.py

- add missing `key_file` parameter

fix external_cluster_helpers.upload_rgw_cert_ca

---

ocs_ci/utility/aws.py

4.17 STS deployments requires an addition to the associated AWS Role, `system:serviceaccount:openshift-storage:noobaa-core`: 
```
{
“Version”: “2012-10-17",
“Statement”: [
{
“Effect”: “Allow”,
“Principal”: {
“Federated”: “arn:aws:iam::123456789123:oidc-provider/mybucket-oidc.s3.us-east-2.amazonaws.com”
},
“Action”: “sts:AssumeRoleWithWebIdentity”,
“Condition”: {
“StringEquals”: {
“mybucket-oidc.s3.us-east-2.amazonaws.com:sub”: [
“system:serviceaccount:openshift-storage:noobaa”,
“system:serviceaccount:openshift-storage:noobaa-endpoint”,
“system:serviceaccount:openshift-storage:noobaa-core” 
]
}
}
}
]
}
```
See https://bugzilla.redhat.com/show_bug.cgi?id=2322124 for more details.

Add the noobaa-core SA to the trust policy for STS deployments

---

ocs_ci/utility/aws.py

4.17 STS deployments requires an addition to the associated AWS Role, `system:serviceaccount:openshift-storage:noobaa-core`: 
```
{
“Version”: “2012-10-17",
“Statement”: [
{
“Effect”: “Allow”,
“Principal”: {
“Federated”: “arn:aws:iam::123456789123:oidc-provider/mybucket-oidc.s3.us-east-2.amazonaws.com”
},
“Action”: “sts:AssumeRoleWithWebIdentity”,
“Condition”: {
“StringEquals”: {
“mybucket-oidc.s3.us-east-2.amazonaws.com:sub”: [
“system:serviceaccount:openshift-storage:noobaa”,
“system:serviceaccount:openshift-storage:noobaa-endpoint”,
“system:serviceaccount:openshift-storage:noobaa-core” 
]
}
}
}
]
}
```
This is essentially a  backport of https://github.com/red-hat-storage/ocs-ci/pull/10780, and is needed in 4.16 to support upgrade runs to 4.17, and the new 4.16 installation procedure. …

[4.16] Add the noobaa-core SA to the trust policy for STS deployments

---

ocs_ci/framework/conf/default_config.yaml
ocs_ci/helpers/disconnected.py
ocs_ci/helpers/github.py
ocs_ci/helpers/virtctl.py
tests/conftest.py

This PR is adding new fixture to get virtctl tool. It checks if this tool is available and if not, it firstly try to get it from the CNV if installed on the cluster and as a fall-back it downloads it from upstream github repository.
Also separating getting asset from github to separated function and use it in the new `get_virtctl_tool` function and also in `get_opm_tool`.
fixes: https://github.com/red-hat-storage/ocs-ci/issues/10366

Download virtctl tool

---

tests/functional/object/rgw/conftest.py

test_rgw_pod_existence.py test case make sure we don't have rgw existance in cloud platforms

include rgw existance test case for cloud platforms

---

ocs_ci/utility/utils.py

- `kubectl` binary is used by some 3rd party scripts (e.g. ACM deployment script)
- in case that downloading of openshift-client from openshift-release-artifacts doesn't work and `oc` binary is extracted from an image, we have to specifically extract also the `kubectl` binary

get also kubectl binary when extracting oc from image

---

tests/cross_functional/system_test/test_clone_deletion_after_max_cluster_space_utilization.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/10680

Fixed calculations of osd full ratio by restructuring code.

---

ocs_ci/helpers/osd_resize.py
ocs_ci/ocs/cluster.py

Add a new check for the resize osd tests: 
Check that the ceph osd df tree weight and size are equal and reflect the current osd size.
See more details in the thread: https://ibm-systems-storage.slack.com/archives/C06DWD30QTZ/p1724321789366579?thread_ts=1724316882.105889&cid=C06DWD30QTZ.
One more note regarding the implementation in the PR: When getting the `ceph osd df tree` output, I used the regular format and not the JSON format because the JSON format lacks the values of `WEIGHT` and `SIZE`.

Check that the ceph osd df tree weight and size are equal and reflect the current osd size

---

ocs_ci/ocs/cluster.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/ui/page_objects/block_and_file.py
ocs_ci/ocs/ui/page_objects/storage_system_details.py
ocs_ci/ocs/ui/validation_ui.py
ocs_ci/ocs/ui/views.py
tests/functional/ui/test_odf_storage_consumption_trend.py

Automated below two test cases.
1. Verify the widget for “Consumption trend”
steps:
1. Login to the ODF dashboard and check the widget for “Consumption trend” is displayed or not.
3. Verify the text information on the widget
2. Verify the accuracy of ‘Estimated days until full’  in the widget
steps:
1. Get the value of storage utilised, total storage, age of the cluster
and calculate Average of storage consumption and 'Estimated days until full'.
2. Compare the above calculated value with the ‘Estimated days until full’ in the widget (UI)

[New Feature Automation] RHSTOR-4624 ODF used capacity trend

---

ocs_ci/deployment/deployment.py
ocs_ci/ocs/defaults.py

set IBM cloud managed OSD size to minimum requirement 512Gi

set IBM cloud managed OSD size to minimum requirement

---

ocs_ci/deployment/deployment.py

Add possibility to install and configure MetalLB operator independently on ODF/hosted clusters deployment. This is required for Provider-Client pipeline where are all dependencies installed as part of separated stage.

install MetalLB as part of dependencies

---

ocs_ci/deployment/hosted_cluster.py

get the latest z-stream version for ocp version x.y for hosted cluster

handle hosted cluster ocp version in form x.y

---

ocs_ci/ocs/machine.py
ocs_ci/ocs/node.py
ocs_ci/ocs/ocp.py

fix https://github.com/red-hat-storage/ocs-ci/issues/10055

Increase timeout waiting for the machine to delete

---

ocs_ci/helpers/helpers.py
ocs_ci/ocs/ocs_upgrade.py
ocs_ci/ocs/utils.py
ocs_ci/utility/utils.py
tests/libtest/test_nb_db_psql_version.py

Noticeable changes made:
1. Added three util functions:
- `get_nb_db_psql_version_from_image`: extract the version from the image name in the noobaa-db-pg statefulset. The equivalent of:
```
oc -n openshift-storage get statefulsets.apps noobaa-db-pg -o yaml | grep image:
image: .../postgresql-12@sha256:28ab5b075817fb23ac1b8619371c858d39205d962309de35dea4434a95d67ee2
```
- `query_nb_db_psql_version`: Extract the version from the DB itself. The equivalent of:
```
$ oc -n openshift-storage exec noobaa-db-pg-0 -- psql -t  -c "SELECT substring(version() from 'PostgreSQL ([0-9\.]+)')"
15.6
```
- `get_expected_nb_db_psql_version`: Extract the PostreSQL version that's listed at the NooBaa CR, which by [the noobaa-db reocvery KCS](https://access.redhat.com/articles/7079321), seems to set the …

Verify the NooBaa DB PostreSQL version at upgrade

---

ocs_ci/ocs/ui/block_pool.py

The test is failing when one capacity is 313.5m and the other is 314m. Adding flexibility to tollerate ~1 difference.

Adding flexibility to check capacity between ui and cli

---

conf/ocsci/external_rhcs_custom_user.yaml
ocs_ci/deployment/helpers/external_cluster_helpers.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/defaults.py
ocs_ci/ocs/resources/storage_cluster.py

add run-as-user param in external mode deployment

---

ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py

Fix issue with this stack trace:
```
self = ObjectBucketClaimsTab Web Page
locator = ('input[placeholder="Select BucketClass"],input[class="pf-c-form-control pf-m-search"], input[id="search-bar"], input[data-test="name-filter-input"]', 'css selector')
text = 'noobaa-default-bucket-class', timeout = 30
def do_send_keys(self, locator, text, timeout=30):
"""
Send text to element on OpenShift Console
locator (tuple): (GUI element needs to operate on (str), type (By))
text (str): Send text to element
timeout (int): Looks for a web element repeatedly until timeout (sec) happens.
"""
if not self.get_elements(locator):
self.page_has_loaded()
wait = WebDriverWait(self.driver, timeout)
try:
if (
version.get_semantic_version(get_ocp_version(), True)
<= version.VERSION_4_11
):
element = wait.until( …
```

fix test_obc_creation_and_deletion test

---

tests/conftest.py

test_create_new_project_to_verify_logging - avoid creating ns 2 times

tune failures tier1 

---

tests/cross_functional/ui/test_odf_topology.py

stop failures upon missing CephNodeDown alert

add bz number to test_stop_start_node_validate_topology

---

ocs_ci/deployment/terraform.py
ocs_ci/ocs/exceptions.py
ocs_ci/ocs/platform_nodes.py

pass vm index for changing tfstate file

---

tests/functional/z_cluster/nodes/test_disk_failures.py

Fixes #10884 
Since node restart code already exists in the teardown which would mount the disk on the node (if not already), by checking ceph health we are allowing the cluster to recover. If ceph recovers, other tests would not be skipped and we would have progress on the currently skipped tests.

Ceph health check during teardown after node restart for test_detach_attach_worker_volume

---

ocs_ci/ocs/resources/bucket_logging_manager.py
tests/functional/object/mcg/test_bucket_logs.py

A small fix to `ocs-ci/tests/functional/object/mcg/test_bucket_logs.py::TestBucketLogs::test_bucket_logs_integrity`:
- Fix the use of `append` to `add` on the `expected_ops_set` at `BucketLoggingManager:verify_logs_integrity`
- Update the expectation for incoming logs to start with a forward-slash at `test_bucket_logs_integrity`

Fix guaranteed bucket logs tests

---

ocs_ci/deployment/helpers/external_cluster_helpers.py
ocs_ci/ocs/constants.py
tests/functional/external_mode/test_external_mode_script.py

From 4.18, we can get the external exporter script from the configmap. However, we still have the option to get the external exporter script from the CSV. We test in the PR that both options are valid and equal.
See more details in the feature: https://issues.redhat.com/browse/RHSTOR-6397.

Test that the external mode script from the CSV is equal to the external mode script from the configmap

---

tests/functional/monitoring/prometheus/alerts/test_alert_mds_cache_high_usage.py

Automated below test case:
[RHSTOR-4798](https://issues.redhat.com//browse/RHSTOR-4798) Fail prometheus and verify that the alert still exists after recovering it.
1. Deploy cluster and run workloads.
2. Run IO pods to fill MDS memory to 95%.
3. Now, the alert is triggered to increase memory limit. Don't take any action on the alert.
4. Fail Prometheus, and recover it.
5. Make sure that the alert is still firing after recovering Prometheus.

4.15 automation [OCS-5576]: Fail prometheus and verify that the alert still exists after recovering it.

---

ocs_ci/deployment/baremetal.py

With 4.18, bluestore replicates its metadata at multiple places on the device (at 0 / 1Gb / 10Gb / 100Gb / 1000Gb etc).
This has to be cleaned up before installing any other version of ODF once 4.18 is installed on the same machines.

Update disk cleanup to remove metadata at different locations

---

ocs_ci/ocs/resources/pod.py
tests/functional/z_cluster/nodes/test_nodes_restart.py
tests/functional/z_cluster/nodes/test_rolling_terminate_and_recovery.py

The PR fixes the following issues:
- fix https://github.com/red-hat-storage/ocs-ci/issues/10859
- fix https://github.com/red-hat-storage/ocs-ci/issues/10834
- fix https://github.com/red-hat-storage/ocs-ci/issues/10833

Wait for the ceph command to execute successfully in the rolling nodes terminate and rolling nodes restart tests

---

tests/functional/z_cluster/nodes/test_nodes_maintenance.py

address failure with stuck trace:
```
[2024-11-22T11:39:24.366Z] >       assert typed_nodes, f"Failed to find a {node_type} node for the test"
[2024-11-22T11:39:24.366Z] [1m[31mE       AssertionError: Failed to find a master node for the test[0m
[2024-11-22T11:39:24.366Z] [1m[31mE       assert [][0m
[2024-11-22T11:39:24.366Z] 
[2024-11-22T11:39:24.366Z] [1m[31mtests/functional/z_cluster/nodes/test_nodes_maintenance.py[0m:154: AssertionError
```
execution failure: https://url.corp.redhat.com/0d04066

add skip_if_rosa_hcp

---

ocs_ci/ocs/perftests.py

We don't have access to master nodes in a managed control plane clusters, such as ROSA HCP.
We need to stop collecting data from master nodes, to prevent index errors while listing data from these nodes;
It affects tests/functional/pv/pv_services/test_ceph_capacity_recovery.py::TestCephCapacityRecovery::test_capacity_recovery
[2024-11-23T08:19:40.087Z]     def get_node_info(self, node_type="master"):
[2024-11-23T08:19:40.087Z]         """
[2024-11-23T08:19:40.087Z]         Getting node type hardware information and update the main environment
[2024-11-23T08:19:40.087Z]         dictionary.
[2024-11-23T08:19:40.087Z]     
[2024-11-23T08:19:40.087Z]         Args:
[2024-11-23T08:19:40.087Z]             node_type (str): the node type to collect data about,
[2024-11-23T08:19:40.087Z] …

add skipp collecting data on CP for managed_cp. test_capacity_recovery

---

tests/functional/object/mcg/test_bucket_creation_deletion.py
tests/functional/object/mcg/test_bucket_deletion.py
tests/functional/object/mcg/test_multicloud.py
tests/functional/object/mcg/test_namespace_crd.py
tests/functional/object/mcg/test_object_integrity.py
tests/functional/object/mcg/test_write_to_bucket.py
tests/functional/upgrade/test_noobaa.py
tests/functional/upgrade/test_resources.py

As part of the initiative to remove obsolete or redundant tests in OCS-CI, it was agreed that Red Squad will remove the tests from the following spreadsheet: https://url.corp.redhat.com/6011089

[Red Squad] - Remove obsolete and redundant tests

---

ocs_ci/ocs/bucket_utils.py

This typo breaks some tests when OCS-QE CA Ingress certificate is used.
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/11012

fix typo in retrieve_verification_mode

---

conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_6w_intransit_encryption.yaml

qe-trigger-vsphere-ipi-intransit-encryption-1az-rhcos-vsan-3m-6w
Related ticket:
https://issues.redhat.com/browse/OCSQE-2963

Add new production configuration for job intransit encryption

---

tests/functional/z_cluster/nodes/test_disk_failures.py

test_detach_attach_worker_volume makes cascade skips because of a bug https://issues.redhat.com/browse/DFBUGS-1038
Prevent failure: 
```
[2024-12-10T19:37:11.198Z] tests/functional/z_cluster/nodes/test_disk_failures.py::TestDiskFailures::test_detach_attach_worker_volume 
[2024-12-10T19:37:11.198Z] [1m-------------------------------- live log setup --------------------------------[0m
[2024-12-10T19:37:11.198Z] 14:37:11 - MainThread - ocs_ci.utility.utils - [32mINFO[0m  - testrun_name: dosypenk-OCS4-17-Downstream-OCP4-17-ROSA_HCP-MANAGED_CP-1AZ-RHCOS-0M-3W-tier4a
[2024-12-10T19:37:11.198Z] 14:37:11 - MainThread - tests.conftest - [32mINFO[0m  - Checking for Ceph Health OK 
[2024-12-10T19:37:11.198Z] 14:37:11 - MainThread - ocs_ci.utility.utils - [32mINFO[0m  - Executing command: oc …
```

test_detach_attach_worker_volume add jira ticket to prevent cascade skips

---

tests/functional/z_cluster/test_rook_ceph_log_rotate.py

avoid getting error on ROSA HCP and managed platforms, where RGW pods do not exist
```
[2024-12-03T22:30:03.082Z] [31mFAILED[0m
[2024-12-03T22:30:03.082Z] _______________ TestRookCephLogRotate.test_rook_ceph_log_rotate ________________
[2024-12-03T22:30:03.082Z] 
[2024-12-03T22:30:03.082Z] self = <tests.functional.z_cluster.test_rook_ceph_log_rotate.TestRookCephLogRotate object at 0x7fe517ca1790>
[2024-12-03T22:30:03.082Z] 
[2024-12-03T22:30:03.082Z]     def test_rook_ceph_log_rotate(self):
[2024-12-03T22:30:03.082Z]         """
[2024-12-03T22:30:03.082Z]         Test Process:
[2024-12-03T22:30:03.082Z]             1.Verify the number of MGR,MDS,OSD,MON,RGW logs
[2024-12-03T22:30:03.082Z]             2.Add logCollector to spec section on Storagecluster
[2024-12-03T22:30:03.082Z] …
```

add managed platforms to exclusion and stop collect rgw-data for test

---

tests/functional/object/mcg/ui/test_mcg_ui.py

In case when storage namespace is not 'openshift-storage' the tests tests/functional/object/mcg/ui/test_mcg_ui.py::TestObcUserInterface::test_obc_creation_and_deletion are failing. 
This PR makes the test fetch the name of noobaa storage class dynamically, one time during test class execution

test_obc_creation_and_deletion  add dynamic noobaa sc name

---

ocs_ci/deployment/rosa.py
ocs_ci/utility/rosa.py

With this PR we perform steps suggested by a Customer Support
> Most recent comment: On 2024-12-08 09:33:29, Mchugh, Brendan commented:
> "Hello,
> 
> I am looking at this case on behalf of Red Hat Global Support Services in EMEA region and I will assist you through this issue for now.
> 
> It seems the cluster was misidentified as deleted due to being in the Stage environment while we work predominantly via support cases with clusters in the Production environment.
> 
> 
> Can you please try having the owner "[fbalak@redhat.com](mailto:fbalak@redhat.com)" deleting the cluster using the ocm CLI from the cluster owning account 7129148 with the best_effort=true parameter as outlined in the following article. [1]
> 
> In addition you will need to add the --url stage parameter to the ocm …

improve destroy rosa hcp cluster

---

ocs_ci/helpers/dr_helpers.py
ocs_ci/ocs/dr/dr_workload.py
ocs_ci/ocs/resources/drpc.py
tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps.py

Check for Kube Object Sync time before running failover for Discovered Apps

---

tests/functional/pv/pv_encryption/test_secrets_on_pods.py

The `test_securityContext_in_Crashcollector` test will not work in an external mode setup because the crashcollector pods are not being spun up. Therefore, the test is being skipped in the case of external mode.

Skip test_securityContext_in_Crashcollector test in external mode deployment

---

conf/deployment/vsphere/upi_1az_rhcos_multus_public_cluster_vsan_3m_3w.yaml
ocs_ci/deployment/vmware.py
ocs_ci/helpers/helpers.py
ocs_ci/ocs/constants.py
ocs_ci/templates/ocs-deployment/node_network_configuration_policy.yaml
ocs_ci/utility/vsphere.py

Adding support for Multus in Vsphere.
Most of the changes is adding interface to each compute node and defining the network policy for vsphere.

Multus for vsphere

---

ocs_ci/ocs/ui/deployment_ui.py

Openshift Data Foundation client operator is taking more time to install which leads to timeout of verification.

UI deployment verification for operators

---

ocs_ci/ocs/node.py

stop fails on waiting new node in machinepool, add TimeoutSampler
Verification executed locally: https://url.corp.redhat.com/df6f756

[ROSA HCP] test_nodereplacement_proactive - fixed

---

ocs_ci/ocs/resources/pod.py

constructions like bellow should be avoided. 
This creates 90+ Mb debug test file.
One Log Record with 30k lines, consisting data of all pods in storage namespace (only) creates a memory spike during buffering while copying output into test log file.  
```
ocp_pod_obj = OCP(
kind=constants.POD,
namespace=namespace,
cluster_kubeconfig=cluster_kubeconfig,
)
running_ct_pods = list()
for pod in ct_pod_items:
pod_status = ocp_pod_obj.get_resource_status(
pod.get("metadata").get("name")
)
```
https://url.corp.redhat.com/d216c1f

get_ceph_tools_pod - stop collecting and printing yaml's of all pods

---

ocs_ci/ocs/resources/pod.py

Reverts red-hat-storage/ocs-ci#11068
There is some problem with this patch: https://url.corp.redhat.com/33a28d6

Revert "[release-4.16] get_ceph_tools_pod - stop collecting and printing yaml's of all pods"

---

ocs_ci/ocs/resources/pod.py

Reverts red-hat-storage/ocs-ci#11047
There is some problem with this patch: https://url.corp.redhat.com/33a28d6

Revert "get_ceph_tools_pod - stop collecting and printing yaml's of all pods"

---

conf/deployment/vsphere/upi_1az_rhcos_vsan_compact_mode_3m_0w.yaml
conf/deployment/vsphere/upi_1az_rhcos_vsan_compact_mode_3m_0w_disconnected.yaml
ocs_ci/deployment/vmware.py
ocs_ci/utility/load_balancer.py

Config for compact mode upi deployment on vsphere:
- set `mastersSchedulable` to `true`
- configure haproxy to route ingress traffic to control plane nodes
Based on: https://docs.openshift.com/container-platform/4.17/installing/installing_vsphere/installing-vsphere-three-node.html
Related to [OCSQE-2983](https://url.corp.redhat.com/37017b7)

add vsphere upi compact mode configs and related automation

---

ocs_ci/ocs/ui/odf_topology.py
ocs_ci/ocs/ui/page_objects/odf_topology_tab.py

fix the issue when CLI has no value on public ip for the node. It also not shown on UI in this case. Test fails by adding expected External IP : "None"
failed run: https://url.corp.redhat.com/332b831

[ROSA HCP] exclude external dns if unavailable in CLI

---

ocs_ci/deployment/helpers/external_cluster_helpers.py

See issue https://issues.redhat.com/browse/RHSTOR-5519

Deploy an external mode cluster and create resources with the rbd rados namespace

---

tests/functional/object/mcg/test_mcg_cli.py

This PR contains adding a new file for mcg cli commands validation. 
Currently there is one test for validation of mcg cli bucket list command. 
The test implements the following flow:
1) runs this command to count the number of existing buckets
2) creates number of buckets
3) runs bucket list command again
4) verifies that the number of current buckets equals the number of previously existing and the added ones

Adding a new test file for mcg cli commands validation with bucket list command verification

---

ocs_ci/ocs/ui/page_objects/buckets_tab.py
ocs_ci/ocs/ui/page_objects/confirm_dialog.py
ocs_ci/ocs/ui/page_objects/object_storage.py
ocs_ci/ocs/ui/page_objects/page_navigator.py
ocs_ci/ocs/ui/page_objects/resource_list.py
ocs_ci/ocs/ui/page_objects/resource_page.py
ocs_ci/ocs/ui/views.py
tests/functional/object/mcg/ui/test_mcg_ui.py

Object Bucket page was replaced with Bucket page
Slack conversation on this: https://ibm-systems-storage.slack.com/archives/C070P0YKFKM/p1733818926176809
https://url.corp.redhat.com/e9dc468
FIXES: #11039

redesign of bucket page, init changes

---

tests/functional/ui/test_error_improvements.py

stop failures with output due to a known issue:
```
[2024-11-25T22:54:37.069Z] +----------------------------------------------------------------------+-----------------------------------------------------+----------------+
[2024-11-25T22:54:37.069Z] | rule                                                                 | check_func                                          | check_status   |
[2024-11-25T22:54:37.069Z] +======================================================================+=====================================================+================+
[2024-11-25T22:54:37.069Z] |                                                                      | _check_all_rules_exist                              | True           |
[2024-11-25T22:54:37.069Z] …
```

add jira mark DFBUGS-410

---

tests/functional/object/mcg/test_object_expiration.py

Adds the `skipif_noobaa_external_pgsql` decorator to the TestObjectExpiration class. These tests make queries to the noobaa-db in order to change the creation date of objects.
Fixes: #9889

Skip MCG object expiration tests in external PostgreSQL noobaa-db deployments

---

ocs_ci/helpers/stretchcluster_helper.py
ocs_ci/ocs/cnv/virtual_machine.py
ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/resources/stretchcluster.py
tests/conftest.py
tests/functional/disaster-recovery/sc_arbiter/test_mon_osd_failures.py
tests/functional/disaster-recovery/sc_arbiter/test_netsplit.py
tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py

This PR addresses:
- Stabilization of stretch cluster test cases
- Add support for CNV workload in mon & osd failure test cases

[Stretch cluster] Stabilize stretch cluster tests and support CNV workloads in MON & OSD failure test cases

---

tests/functional/pv/pv_encryption/test_secrets_on_pods.py

As per the comment in BZ: https://ibm.biz/BdGBA6 , "dmcrypt-key" appeared in the env variable in case KMIP kms is configured

Fixed tests failure test_secrets_in_env_variables

---

ocs_ci/ocs/bucket_utils.py
ocs_ci/ocs/resources/mcg_replication_policy.py
tests/functional/object/mcg/test_bucket_replication_with_versioning.py

Cover the happy path of MCG bucket replication with versioning support: https://url.corp.redhat.com/45368c5

[4.18] Test bucket replication with versioning - utility functions and happy path validation

---

tests/functional/pod_and_daemons/test_mgr_enable_rook_backend_module.py

Added jira mark "[DFBUGS-1284](https://issues.redhat.com//browse/DFBUGS-1284)" for https://github.com/red-hat-storage/ocs-ci/blob/master/tests/functional/pod_and_daemons/test_mgr_enable_rook_backend_module.py
stop failures with output due to a known issue. [Mgr crash]
{ "backtrace": [ " File \"/usr/share/ceph/mgr/orchestrator/_interface.py\", line 796, in get_prometheus_access_info\n raise NotImplementedError()", "NotImplementedError" ], "ceph_version": "19.2.0-53.el9cp", "crash_id": "2025-01-01T12:19:36.669894Z_2ab3c979-3a1d-43ea-9376-3c2367607b88", "entity_name": "mgr.a", "mgr_module": "rook", "mgr_module_caller": "ActivePyModule::dispatch_remote get_prometheus_access_info", "mgr_python_exception": "NotImplementedError", "os_id": "rhel", "os_name": "Red Hat Enterprise Linux", …

add jira mark DFBUGS-1284

---

ocs_ci/ocs/resources/pod.py

avoid circular import when importing MCG

---

tests/functional/pod_and_daemons/test_csi_logs_rotation.py

trim testcase path for test_pods_csi_log_rotation

---

conf/deployment/vsphere/upi_1az_rhcos_multus_public_cluster_vsan_3m_3w_ipv6.yaml
conf/ocsci/vsphere_upi_enable_multus_ipv6_single_stack.yaml
ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/helpers/helpers.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/storage_cluster.py
ocs_ci/templates/ocs-deployment/multus-cluster-net-ipv6.yaml
ocs_ci/templates/ocs-deployment/multus-public-net-ipv6.yaml
ocs_ci/templates/ocs-deployment/node_network_configuration_policy_ipv6.yaml

Multus ipv6 deployment for ipv6

Multus ipv6 on vsphere

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/ui/helpers_ui.py
ocs_ci/ocs/ui/page_objects/encryption_module.py
ocs_ci/ocs/ui/page_objects/storage_system_details.py
ocs_ci/ocs/ui/views.py
tests/functional/encryption/test_encryption_configuration_dashboard.py

Test Automation for encryption dashboard summary.
Following encryption summary details validated against storagecluster and noobaa spec.
Object Storage Encryption Summary details
1. Navigate to object details page
2. Open encryption details.
3. verify encryption data with the nooba and storagecluster spec.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Block And File Encryption summary details
1. Navigate to file and block details page
2. Open encryption details.
3. verify encryption data with the nooba and storagecluster spec.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Test Automation for encryption dashboard summary

---

tests/conftest.py
tests/functional/encryption/test_intransit_encryption_sanity.py

``` 
Test to validate in-transit encryption enable-disable state transitions.
Steps:
1. Create a cephfs, rpd pvcs with different access mode.
2. Change in-transit Encryption state.
3. Create a pods and attach the PVC to it.
4. Start IO from  All pods.
5. During the IO running on the pod toggle intransit encryption state.
```

Updated in-transit encryption test automation for enable/disable operations.

---

ocs_ci/ocs/resources/bucketclass.py
ocs_ci/ocs/resources/mcg.py
tests/functional/object/mcg/test_namespace_crd.py

This PR implements the following enhancement to cli_create_bucketclass method : in the past it was creating only backingstore with mcg-cli and from now on it will be able to create a bucketclass with mcg-cli command also for namespacestore. 
Following this enhancement it was possible to add a new test case which implements creation of namespacestore and bucketclass for rgw using mcg-cli commands. 
In the next PR I will implement automation of https://issues.redhat.com/browse/DFBUGS-1035 ( creating namespacestore and bucketclass on rgw bucket and writing IO to this bucket).

Adding support in creation of bucket class with mcg cli and a new test case for creation of rgw namespacestore using mcg-cli 

---

ocs_ci/utility/kms.py

This is for Vault Configuration.
fixes: https://issues.redhat.com/browse/OCSQE-1636

Adding functionality to set same token value across cluster

---

tests/conftest.py
tests/functional/monitoring/prometheus/alerts/test_alert_mds_cpu_high_usage.py

https://issues.redhat.com/browse/RHSTOR-5823 
Automatic Alert what type of mds pod scaling is needed.

Test case changes for RHSTOR-5823

---

ocs_ci/helpers/helpers.py
tests/functional/pv/space_reclaim/test_disable_reclaimspace_operation.py

Adding test automation for reclaimspace disable operation
Steps:
1.	Create a PVC from the CephBlockPool and attach it to a pod.
2.	To disable the reclaimspace operation for the PVC, set suspend = true and change the state annotation
to unmanaged.
3.	Verify that the reclaimspace operation is disabled for the PVC by checking that suspend = true is set.
4.	Re-enable the reclaimspace cronjob by removing suspend = true and changing the state annotation back
to managed for each PVC.
5.	Verify that all reclaimspace cronjobs are enabled.

Adding test automation for reclaimspace disable operation

---

tests/conftest.py

Fixes https://github.com/red-hat-storage/ocs-ci/issues/11142

Label the s3cli pod's Namespace with `S3CLI_APP_LABEL` to ignore potential false leftover error

---

ocs_ci/utility/kms.py

fix the error
```
2025-01-15 17:26:02  10:26:02 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc create -f /tmp/clientkeyrshnu5m_
2025-01-15 17:26:03  10:26:02 - MainThread - ocs_ci.utility.templating - INFO  - apiVersion: v1
2025-01-15 17:26:03  data:
2025-01-15 17:26:03    token: '*****'
2025-01-15 17:26:03  kind: Secret
2025-01-15 17:26:03  metadata:
2025-01-15 17:26:03    name: ocs-kms-token
2025-01-15 17:26:03    namespace: openshift-storage
2025-01-15 17:26:03  type: Opaque
2025-01-15 17:26:03  
2025-01-15 17:26:03  10:26:02 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc create -f /tmp/tokenq0lo5hay
2025-01-15 17:26:03  10:26:03 - MainThread - ocs_ci.utility.utils - WARNING  - Command stderr: Error from server (NotFound): error when creating …
```

[ROSA HCP] storage encryption. fix namespace issue

---

ocs_ci/helpers/osd_resize.py

test fails but we don't have screenshot of actual storage capacity
fixes: 11143

add screenshot to prove numbers in logs

---

ocs_ci/ocs/resources/pod.py

increase timeout to copy the file. 
should help with weak node machines and large files

test_ceph_pg_log_dups_trim - fix the test

---

ocs_ci/ocs/warp.py

The hostname for wrap s3 benchmark-tool is now dynamic, tuned to a storage namespace.
test run Pass: https://url.corp.redhat.com/218b7dc

wrap s3 benchmark-tool - ns in hostname fixed

---

tests/functional/object/mcg/test_mcg_resources_disruptions.py

prevent failure with output: 
```
[2024-11-25T21:25:03.352Z]         log.info(f"Verifying {service_account} was added to the anyuid scc")
[2024-11-25T21:25:03.352Z] >       assert helpers.validate_scc_policy(
[2024-11-25T21:25:03.352Z]             sa_name=scc_name,
[2024-11-25T21:25:03.352Z]             namespace=config.ENV_DATA["cluster_namespace"],
[2024-11-25T21:25:03.352Z]             scc_name=constants.ANYUID,
[2024-11-25T21:25:03.352Z]         ), "SA name is not present in anyuid scc"
[2024-11-25T21:25:03.352Z] [1m[31mE       AssertionError: SA name is not present in anyuid scc[0m
[2024-11-25T21:25:03.352Z] [1m[31mE       assert False[0m
[2024-11-25T21:25:03.352Z] [1m[31mE        +  where False = <function validate_scc_policy at 0x7fb730d11670>(sa_name='noobaa-db', …
```

[ROSA HCP] test_db_scc correct service acc namespace

---

tests/functional/workloads/app/amq/test_amq_node_reboot_and_shutdown.py
tests/functional/workloads/app/couchbase/test_couchbase_node_reboot.py
tests/functional/z_cluster/nodes/test_nodes_maintenance.py

the platform is forbidding operations with master nodes. master nodes are not available for customer

[ROSA HCP] skip tests related to master nodes operations

---

tests/functional/monitoring/prometheus/alerts/test_alerting_works.py

Fixes https://github.com/red-hat-storage/ocs-ci/issues/11134
Reruns test_prometheus_rule_failures if failed to prevent disruption from previous test case

Mark test_prometheus_rule_failures as flaky

---

ocs_ci/framework/pytest_customization/marks.py
ocs_ci/helpers/keyrotation_helper.py
ocs_ci/utility/kms.py
tests/functional/encryption/test_encryption_keyrotation.py

Test OSD KEyrotation operation for vault KMS.
Steps:
1. Deploy cluster with clusterwide encryption
2. enable keyrotation and set keyrotation schedule for every 2 minute.
3. create a multiple PVC and attach it to the pod.
4. start IO's on PVC to pods.
5. Verify keyrotation operation happening for every 2 minutes.

Test Automation for clusterwide encryption keyrotation

---

ocs_ci/ocs/utils.py

Fixes: #8934 
This PR introduces a change to ensure that the working directory is preserved during the execution of the `collect_ocs_logs`

Preserve the working directory during log collection

---

ocs_ci/ocs/rados_utils.py
ocs_ci/ocs/resources/pod.py

replaced copy_from_pod_oc_exec with new utility copy_file_with_base64 to pg log dups count

 test_ceph_pg_log_dups_trim increase timeout on log copy process

---

tests/functional/object/mcg/test_write_to_bucket.py

This PR contains additional test case for testing writing to bucket created on RGW namespacestore created with CLI. 
Adding the original bug for context: https://issues.redhat.com/browse/DFBUGS-1035

Adding a new test case for rgw namespacestore created with cli

---

tests/functional/object/mcg/test_bucket_logs.py

This PR contains only adding a skip following https://github.com/red-hat-storage/ocs-ci/issues/10983 ( the test was failing on external deployments).

test_bucket_logs.py - Adding skip on external deployments following issue 10983

---

ocs_ci/ocs/resources/bucket_logging_manager.py

`test_bucket_logs_integrity` - fix race condition by waiting for logs to appear before awaiting their removal

---

tests/functional/object/mcg/test_multicloud.py
tests/functional/object/mcg/test_write_to_bucket.py

Fixes #10561 
Log link where run skipped IBM cloud backed backingStore creation for FIPS enabled cluster:
https://jenkins-csb-odf-qe-ocs4.dno.corp.redhat.com/job/qe-deploy-ocs-cluster/45315/console

Adds condition for skipping BS creation on IBM cloud for FIPS enabled cluster

---

conf/deployment/aws/rosa_hcp_1az_3w_m5.12x.yaml
conf/deployment/aws/rosa_hcp_1az_6w_m5.2x.yaml
ocs_ci/deployment/rosa.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/ocp.py
ocs_ci/utility/rosa.py
ocs_ci/utility/version.py
tests/functional/upgrade/test_upgrade_ocp.py

- remove OCM and ROSA cli versions to make automation fetch the latest ones 
- modify ocp upgrade to work on ROSA HCP
- add version utilities

[ROSA HCP] prep for production CI jobs

---

tests/functional/storageclass/test_cross_sc_clone_snap_restore.py

Skipping test `test_cross_class_different_pool_clone_snap_restore` for external mode setup.
For more details refer this comment: https://github.com/red-hat-storage/ocs-ci/issues/11221#issuecomment-2619283669

Skip test_cross_class_different_pool_clone_snap_restore test for external mode

---

ocs_ci/ocs/resources/mcg.py
ocs_ci/ocs/resources/pod.py
tests/conftest.py
tests/functional/disaster-recovery/sc_arbiter/test_mon_osd_failures.py
tests/functional/disaster-recovery/sc_arbiter/test_noobaa_in_stretch.py

Fix `MCG::reset_endpoint_pods` race condition - use rollout restart instead of deleting pods by name

---

tests/conftest.py

Skipping test cases with kubeadmin password - release4.17

Skipping test cases with kubeadmin password - release4.17

---

ocs_ci/helpers/keyrotation_helper.py
ocs_ci/ocs/constants.py
tests/functional/pv/pv_encryption/test_disable_pv_keyrotation.py

Test 1:
Test disable PV keyrotation globally by anotating storageclass.
```
Steps:
1. Add an annotation to the StorageClass to disable key rotation.
2. Verify that the key rotation jobs are deleted.
3. Remove the annotation from the StorageClass.
4. Verify that the key rotation CronJobs are created again.
```
Test 2:
Test disable PV keyrotation  by RBAC User.
```
Steps:
1. Disable PV key rotation by modifying the keyrotationcronjob for the respective PVC. Add `state: unmanaged` and `suspend: true`.
2. Verify that the key rotation job’s suspend state is set to true.
3. Re-enable the key rotation job by changing `suspend: false`, or by removing the `suspend` key and setting `state: managed`.
4. Verify that key rotation is functioning correctly for the PVC.
```

Added Test Automation for disable keyrotation operation

---

ocs_ci/deployment/helpers/mcg_helpers.py
tests/conftest.py
tests/functional/object/mcg/test_bucketclass.py
tests/functional/object/mcg/test_noobaa_secret.py

Addresses:
https://bugzilla.redhat.com/show_bug.cgi?id=2152143
https://bugzilla.redhat.com/show_bug.cgi?id=2272084

[GSS] Test if MCG secrets are used in env variables and bucketclass can be modified

---

conf/README.md
ocs_ci/deployment/deployment.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/defaults.py
ocs_ci/ocs/ocp.py
ocs_ci/ocs/utils.py
ocs_ci/utility/utils.py
tests/conftest.py

Fixes: #10526
Fixes: #11159
Several improvements in MG logs like preventing running MG over and over
when it's still failing or getting timeouted.
Collecting OCP logs for Ecosystem tests like upgrade decorated with purple
squad.
Not collect logs again at the end of execution on success when it was
collected at least once during execution by some failed test.

Improvements for MG collections

---

ocs_ci/ocs/amq.py
ocs_ci/ocs/resources/bucket_notifications_manager.py
ocs_ci/ocs/resources/mcg.py
tests/functional/object/mcg/test_bucket_notifications.py

**Changes made:**
1. Setup and teardown of the AMQ cluster that is used to setup Kafka takes a long time (~5 mins). This hinders the debugging and development process. 
To fix this issue I've enabled local re-running of the test without destroying and re-creating the AMQ cluster - just use `run-ci` with the --`dev-mode` option. 
Note that this will affect PR verifications on an existing cluster the AMQ cluster is already set up, so to bypass this one needs to destroy the cluster manually:
```
$ oc delete namespace myproject
$ oc delete all -l app=strimzi
```
2. Added  a retry to the fetching of the PVC in `enable_bucket_notifs_on_cr` - the test would often fail on new clusters because MCG was still creating the PVC when we were trying to read the resource.
3. Adjust …

Stabilize and adjust `test_bucket_notifications`

---

ocs_ci/deployment/baremetal.py

- avoid boot loop to discovery mode for server in uefi boot mode by renaming discovery.ipxe file

baremetal AI deployment: support uefi boot mode

---

ocs_ci/deployment/ibmcloud.py
ocs_ci/ocs/constants.py
ocs_ci/utility/ibmcloud.py

Issue: https://url.corp.redhat.com/db47959

Delete leftover dns records when destroying ibmcloud clusters

---

ocs_ci/deployment/ibmcloud.py
ocs_ci/utility/ibmcloud.py

Delete leftover dns records when destroying ibmcloud clusters

[release-4.16] Delete leftover dns records when destroying ibmcloud clusters

---

ocs_ci/deployment/ibmcloud.py
ocs_ci/utility/ibmcloud.py

Delete leftover dns records when destroying ibmcloud clusters

[release-4.15] Delete leftover dns records when destroying ibmcloud clusters

---

ocs_ci/deployment/ibmcloud.py
ocs_ci/utility/ibmcloud.py

Delete leftover dns records when destroying ibmcloud clusters

[release-4.14] Delete leftover dns records when destroying ibmcloud clusters

---

ocs_ci/ocs/resources/bucket_logging_manager.py

As seen [here](https://url.corp.redhat.com/2eeffd1), bucket logs tests often fail because the pods fail to mount the logging PVC in time.
There might be a more nuanced race-condition that causes this, but I wasn't able to reproduce it locally or via Jenkins. If increasing the timeout won't fix the issue, then that would at least be a hint we can further use to find the root cause.

`BucketLoggingManager::wait_for_logs_pvc_mount_status` - Increase the timeout from 2 minutes to 5

---

ocs_ci/ocs/constants.py
ocs_ci/utility/environment_check.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/11323
Note that I've used @petr-balogh's approach from https://github.com/red-hat-storage/ocs-ci/pull/11198

Ignore rook-ceph-osd-key-rotation leftovers

---

conf/ocsci/submariner_downstream.yaml
ocs_ci/framework/conf/ocp_version/ocp-4.16-config.yaml
ocs_ci/framework/conf/ocp_version/ocp-4.16-ga-config.yaml
ocs_ci/framework/conf/ocp_version/ocp-4.16-ga-minus1-config.yaml

Bumps ACM and Submariner version for OCP 4.16

Bumps ACM and Submariner version for OCP 4.16

---

tests/functional/z_cluster/nodes/test_node_replacement_proactive.py

Server doesn't have a resource type "Machine" issue fixed in IBM cloud managed platform

Server doesn't have a resource type "Machine" issue fixed in IBM cloud managed platform

---

tests/functional/pv/pv_encryption/test_secrets_on_pods.py

This is fix for the issue: https://github.com/red-hat-storage/ocs-ci/issues/11288

Added rook-ceph-osd-encryption-key name in EXPECTED_NAMES list

---

ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
ocs_ci/ocs/ui/views.py

locators have been changed, data-id removed with ODF 4.18. 
Improve locators with multiple parents, to fix:
```
_locator = ("(//[@class='pf-topology__node__label']//[contains(text(), 'j031vi1cv30t3-czpjd-master-0')]/parent::/parent::/parent::/parent:://*[@class='pf-topology__node__decorator'])[2]", 'xpath')
_timeout = 60, _enable_screenshot = True, _copy_dom = False
def _do_click(_locator, _timeout=30, _enable_screenshot=False, _copy_dom=False):
if not self.get_elements(_locator):
self.page_has_loaded()
screenshot = (
ocsci_config.UI_SELENIUM.get("screenshot") and enable_screenshot
)
if screenshot:
self.take_screenshot()
if _copy_dom:
self.copy_dom()
wait = WebDriverWait(self.driver, timeout)
try:
if (
version.get_semantic_version(get_ocp_version(), True)
<= version.VERSION_4_11
): …
```

update locators test_validate_topology_configuration

---

ocs_ci/ocs/bucket_utils.py
tests/functional/object/mcg/test_bucket_replication_with_versioning.py

Remove the option of getting the uploaded versions' etags via the `upload_obj_versions`. One can just use `get_obj_versions` after uploading the versions.

Simplify `bucket_utils.py::upload_obj_versions`

---

ocs_ci/ocs/resources/mcg.py
tests/functional/object/mcg/test_namespace_crd.py

This PR contains adding a new test case for bucketclass NSS creation with Cache  via CLI, following issue #https://github.com/red-hat-storage/ocs-ci/issues/11128 from the backlog.

Adding a new test case for bucketclass NSS creation with Cache  via CLI

---

ocs_ci/ocs/resources/storage_cluster.py

The code `ocp_obj.check_phase(constants.STATUS_READY)` returns a boolean, whereas the earlier code was comparing it with a status string, causing an exception. This PR fixes the issue.

Fixed storagecluster status check code

---

ocs_ci/ocs/cluster_load.py
setup.py

cluster load: Refresh prometheus_api connection in case of connection error

---

tests/functional/object/mcg/test_bucket_policy.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/10982
Since adding a 60 seconds sleep in https://github.com/red-hat-storage/ocs-ci/pull/9447 reduced the hit ratio from 20% (according to https://github.com/red-hat-storage/ocs-ci/issues/9446) to ~5%, then there's room to believe this is still a race condition issue that more timeout will solve.

`test_object_actions` - double the sleep from 60 seconds to 120

---

ocs_ci/ocs/resources/mockup_bucket_logger.py
tests/functional/object/mcg/test_log_based_bucket_replication.py

Backlog item: add automation coverage for log-based bidirectional replication with deletion sync

Add `test_bidirectional_deletion_sync` to `TestLogBasedBucketReplication`

---

tests/functional/monitoring/prometheus/alerts/test_alert_mds_cache_high_usage.py

The below Jira requires feature deprecation till further decision on metrics measurement for cache usage.
[DFBUGS-368](https://issues.redhat.com/browse/DFBUGS-368)
[DFBUGS-1034](https://issues.redhat.com/browse/DFBUGS-1034)
[DFBUGS-1033](https://issues.redhat.com/browse/DFBUGS-1033)
[DFBUGS-1032](https://issues.redhat.com/browse/DFBUGS-1032)
For time being the test need to be skipped for all 4.15.z, 4.16.z, 4.17.z, 4.18. Hence added Jira mark to the test case and added deprecate tag for all tests.

[DFBUGS-368] Deprecate test_alert_mds_cache_high_usage.py till further changes.

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/ocp.py
ocs_ci/ocs/ocs_upgrade.py
ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/utils.py

cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/10723

[release-4.17] exclude NOOBAA_PSQL_12_IMAGE for image verification after upgrade

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/ocp.py
ocs_ci/ocs/ocs_upgrade.py
ocs_ci/ocs/resources/pod.py
ocs_ci/ocs/utils.py

cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/10723

[release-4.16] exclude NOOBAA_PSQL_12_IMAGE for image verification after upgrade

---

ocs_ci/framework/pytest_customization/marks.py
tests/functional/monitoring/prometheus/alerts/test_alert_mds_cpu_high_usage.py

This test case was failing due to insufficient load on the Vsphere clusters. It is common to encounter backend bottlenecks in Vsphere clusters, often caused by hardware-related latency issues. I have successfully tested the same scenario on BM, AWS, and IBM Cloud, where it functions as expected. Since this is a performance-related test case, it is crucial to run it on hardware that ensures minimal latency. To avoid unnecessary test failures, I have added a skip marker for Vsphere and disconnected cluster modes.
Fixing Ocs-ci issue #11334

Stabilize MDSCPUUsageHigh alert test case

---

ocs_ci/ocs/ui/page_objects/bucket_class_tab.py
ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
ocs_ci/ocs/ui/page_objects/namespace_store_tab.py
ocs_ci/ocs/ui/page_objects/storage_system_tab.py
ocs_ci/ocs/ui/views.py
tests/functional/ui/test_error_improvements.py

fix repetitive issue caused by locators change: PR link https://url.corp.redhat.com/acf7b7e

[4.18]TestErrorMessageImprovements: fix locator and logic

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/ui/odf_topology.py
ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
ocs_ci/ocs/ui/workload_ui.py
ocs_ci/templates/app-deployments/ubi8-simple.yaml
tests/cross_functional/ui/test_odf_topology.py
tests/functional/ui/test_capacity_breakdown_ui.py

Fix the problem with containers unavailable on disconnected clusters:
```
[2025-02-02T13:54:30.118Z] 08:54:29 - MainThread - ocs_ci.ocs.ui.workload_ui - [32mINFO[0m  - Run IO on pod busybox-1gi-1738504443067-798b6b5495-qklft
[2025-02-02T13:54:30.118Z] 08:54:29 - MainThread - ocs_ci.utility.utils - [32mINFO[0m  - Executing command: oc -n project-ui-54b8b3e820a649f187b42d53d2d2b rsh busybox-1gi-1738504443067-798b6b5495-qklft dd if=/dev/urandom of=/tmp/testfile bs=64M count=16
[2025-02-02T13:54:30.371Z] 08:54:30 - MainThread - ocs_ci.utility.utils - [33mWARNING[0m  - Command stderr: error: unable to upgrade connection: container not found ("busybox")
```
RP link: https://url.corp.redhat.com/fdcd710

requested_cap_breakdown: replace busybox with ubi8 for disconected clusters

---

tests/functional/monitoring/prometheus/metrics/test_monitoring_defaults.py

Having discussion in this Pull Request https://github.com/red-hat-storage/ocs-ci/pull/9506, in comments section we decided to exclude metrics-related tests from regression execution until better solution will be found.
Main reason - ODF does not support metrics from external ceph storage. All settings should be done by user, hence testing our own prometheus settings makes no direct sense.

exclude-metrics-dependant-tests-for-external-mode

---

tests/functional/monitoring/prometheus/alerts/test_ceph.py

reduced osd_op_complaint_time from default 30 sec to 200 ms 
if this will not stabilized - we will need to add check per osd, that it took action and minimize further
check from logs:
`ceph daemon osd.<id> config show | grep osd_op_complaint_time`
check directly:
`ceph config get osd.3 osd_op_complaint_time`
monitor slow requests:
`ceph health detail`
Fixes: #9643

test_ceph_osd_slow_ops_alert minimize osd complient time

---

tests/functional/object/rgw/test_object_bucket_size.py

Fixes: #9697
This test verifies the output of the `read_bucket` RPC method in on-prem deployments. However, using RPC's is no longer supported as a customer-facing feature so we can't expect fixes for it.

Deprecate test_object_bucket_size

---

tests/functional/object/mcg/test_nsfs.py

These tests are failing often due to [DFBUGS-153](https://issues.redhat.com/browse/DFBUGS-153), so adding this decorator will make sure they are skipped until we receive the fix.

test_nsfs.py - add the Jira label for DFBUGS-153

---

ocs_ci/ocs/bucket_utils.py
ocs_ci/ocs/resources/bucket_notifications_manager.py
tests/conftest.py
tests/functional/object/mcg/test_bucket_notifications.py

This PR adds the following tests to [test_bucket_notifications.py](https://github.com/red-hat-storage/ocs-ci/blob/7148326e2bbda967deb64acda44f2fb30082fc5e/tests/functional/object/mcg/test_bucket_notifications.py):
1.` test_multi_notif_event_types`: check that other operations besides PutObject result in the expected notificaitons
2. `test_multiple_bucket_notifs_setups`: verify that MCG can handle bucket notifications configurations, where different buckets are each sending notifications to a separate Kafka topic. 
3. `test_bucket_notifs_shared_topic`: test that multiple buckets can send their notifications to the same Kafka topic
Additionally, the following fixes were made:
- A typo error in `delete_object_tags`
- Typos in `test_bucket_notifications.py`
- The polarion IDs of …

[4.18] MCG Bucket Notifications - add advanced tests

---

tests/functional/z_cluster/nodes/test_disk_failures.py

Increase bucket creation timeout for test_recovery_from_volume_deletion

---

ocs_ci/framework/pytest_customization/marks.py
pytest.ini
tests/conftest.py
tests/test_failure_propagator.py

Ensure that get_current_test_marks doesn't return non-relevant marks for utility tests such as test_failure_propagator

---

tests/functional/pv/pv_services/test_pvc_evict_ceph_clients.py

Added skip marker to the invalid test scenario.
The test fails because of this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2269108. This is not an issue but the expected behaviour. So, after discussing it with Mahesh, who automated it, I decided to skip the test.

skip the test

---

ocs_ci/ocs/bucket_utils.py
tests/functional/object/mcg/test_bucket_replication_with_versioning.py

- Add utility functions that deal with the comparison of object versions between two buckets
- Generalize `test_bucket_replication_with_versioning` to support multiple pairs and make the original a test case the case for `bucket_pairs_amount==1` (`test_bucket_replication_with_versioning` --> `test_bucket_replication_with_versioning[single_bucket_pair]`)
- Add `test_bucket_replication_with_versioning[multiple_bucket_pairs]`
- Add `test_bidirectional_replication_with_versioning`
- Add `test_bucket_replication_with_versioning_suspension`

[4.18] Test bucket replication with versioning - minor refactor to existing test + advanced tests

---

docs/usage.md
ocs_ci/utility/rosa.py
ocs_ci/utility/version.py
setup.py

This endpoint will allow us to get list of all available OCP versions from ROSA and also check if particular OCP version is available there (and get the latest z-stream version for that OCP version).
This is the help for the new endpoint:
```
$ rosa-ocp-version -h
usage: rosa-ocp-version [-h] [--debug] [--get-available-versions] [--check-available-version OCP_VERSION] --ocsci-conf OCSCI_CONF
Get information about available OCP versions from ROSA
options:
-h, --help            show this help message and exit
--debug, -d           Print logging messages (mainly useful for debugging).
--get-available-versions, -a
Get all available OCP versions from ROSA
--check-available-version OCP_VERSION, -c OCP_VERSION
Check if provided OCP version is available in ROSA, if available, returns latest …
```

Add rosa-ocp-version endpoint

---

conf/README.md
conf/examples/provider_mode_ibm_cloud_baremetal_kubevirt_clients.yaml
ocs_ci/deployment/deployment.py
ocs_ci/deployment/helpers/hypershift_base.py
ocs_ci/deployment/hosted_cluster.py
ocs_ci/deployment/hyperconverged.py
ocs_ci/deployment/mce.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/ocs/exceptions.py
ocs_ci/ocs/resources/deployment.py
ocs_ci/templates/hyperconverged-deployment/hyperconverged-catsrc.yaml
ocs_ci/templates/hyperconverged-deployment/hyperconverged.yaml
ocs_ci/templates/hyperconverged-deployment/hyperconverged_namespace.yaml
ocs_ci/templates/hyperconverged-deployment/hyperconverged_operator_group.yaml
ocs_ci/templates/hyperconverged-deployment/hyperconverged_subscription.yaml
ocs_ci/templates/mce-deployment/mce_catsrc.yaml
ocs_ci/templates/mce-deployment/mce_subscription.yaml
ocs_ci/utility/managedservice.py
ocs_ci/utility/utils.py
tests/libtest/test_provider_create_hosted_cluster.py

In past we had a problem with deploying ODF on Hosted Client clusters that were deployed with latest unreleased CVN and latest unreleased ACM.
The nature of the problem was not determined, but installing upstream hyperconverged along with upstream mce proved to be sustainable. 
This PR is also giving us a backdoor option, when CNV ureleased version is still not available and upstream HCO is already been populated via unstable index-tag of quay.io/kubevirt/hyperconverged-cluster-index
Link to the issue: https://issues.redhat.com/browse/OCPBUGS-32196  
Link to verification run: https://privatebin.corp.redhat.com/?08e39cfadafad0c6#E5JtjD7BpRWhLi22Jobta6U3FX6hJ3RfgUJZcAvqjsUT
Added int parameter in configuration `ENV_DATA.clusters.<cluster_name>.storage_quota`. Default value - no …

add-hyperconverged-into-dependencies

---

tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py

The PVC creation from snapshot took more time to reach Bound state. Increased the timeout to 180 seconds to avoid failure.
Test : tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py::TestPvcSnapshot::test_pvc_snapshot
Fixes #11600

Increase timeout when creating PVC from snapshot in test test_pvc_snapshot

---

ocs_ci/ocs/resources/namespacestore.py
tests/functional/object/mcg/test_namespace_crd.py

This PR handles requirements specified in https://github.com/red-hat-storage/ocs-ci/issues/11129 and there are 4 new test cases which were added:
CLI NSS creation over Azure
CLI NSS creation over IBMCOS
CLI NSS creation over AWS
CLI NSS creation over GCP
In order to support creation of NSS over GCP a support was added to namespacestore.py.

Adding 4 new test cases for aws/azure/ibmcos and gcp and a support for nss creation for gcp platform

---

ocs_ci/ocs/resources/mcg.py

This PR contains a fix following a failure of test_namespace_bucket_creation_crd[RGW-CLI-Cache]
Report Portal link: https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-6338
The problem in that line of code is that it’s not injecting the value of the constant variable constants.DEFAULT_NOOBAA_BACKINGSTORE into the string as you intended - it’s just using the string “constants.DEFAULT_NOOBAA_BACKINGSTORE” in the mcg-cli command. 
The result is this error:
E               ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/data/mcg-cli bucketclass create namespace-bucketclass cache cli-bucketclass-9634d20140c2433b905feba1 …

A fix to test_namespace_bucket_creation_crd[RGW-CLI-Cache] failure 

---

tests/functional/workloads/ocp/monitoring/test_monitoring_on_negative_scenarios.py

Fixed #11616 
Problem: Script used to timeout while checking for Ceph health after node reboot.
Solution: Increased the retries from 30 to 60, its passing now. Tested multiple times, working fine.

Increased retries to validate ceph health metrics is updated on prometheus pod during mgr running node reboot.

---

ocs_ci/ocs/resources/mcg.py
ocs_ci/ocs/ui/page_objects/buckets_tab.py
ocs_ci/ocs/ui/page_objects/page_navigator.py
ocs_ci/ocs/ui/views.py
ocs_ci/utility/utils.py
tests/functional/object/mcg/ui/test_mcg_ui.py

Testing Object Storage Browser p2 

---

ocs_ci/ocs/cluster.py

The `validate_pdb_creation` function can raise both `PDBNotCreatedException` and `AssertionError` exceptions.
This should prevent failures like this: https://url.corp.redhat.com/ec8e179
```
2025-03-13 13:52:31  08:52:31 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get PodDisruptionBudget  -n openshift-storage -o yaml
2025-03-13 13:52:31  08:52:31 - MainThread - ocs_ci.deployment.deployment - ERROR  - rook-ceph-osd was not created
...
2025-03-13 14:23:42      @retry(PDBNotCreatedException, tries=9, backoff=2)
2025-03-13 14:23:42      def validate_pdb_creation():
...
2025-03-13 14:23:42          for required, given in zip(pdb_required, pdb_list):
2025-03-13 …
```

fix retry for validate_pdb_creation function

---

tests/cross_functional/conftest.py
tests/cross_functional/system_test/test_object_expiration.py
tests/cross_functional/system_test/test_object_expiration_system.py

Fixes:
- Bucket creation failure because of noobaa pod restart from patch
- Teardown function for Noobaa db backup and recovery fixture
- Add node restart teardown factory to the test hence making sure at teardown all the nodes are up and ready

Stabilize object expiration system test

---

ocs_ci/deployment/provider_client/storage_client_deployment.py
ocs_ci/ocs/constants.py
ocs_ci/templates/ocs-deployment/provider-mode/ocs_storagecluster_converged.yaml

following changes from https://github.com/red-hat-storage/ocs-operator/pull/3037 we deprecated fields that will not be in use in Converged deployments in ocs-ci:4.19

StorageCluster changes. DisableStorageClass and DisableSnapshotClass removed

---

conf/README.md
ocs_ci/deployment/baremetal.py
ocs_ci/utility/baremetal.py

We are facing an issue with one of the baremetal servers, that UEFI boot order getting changed during OCP deployment and PXE boot is not on first place which leads to an issue during the next deployment.
This workaround will try to change the boot order using `efibootmgr` command and set PXE boot on the first place.

add workaround for issues with uefi boot order

---

docs/usage.md

Mainly moving **# Usage for run-ci tool** section to the beginning of the file (before usage of auxiliary tools `ci-cleanup`, `vsphere-cleanup`, `ocs-build`, `rosa-ocp-version` and similar).

update docs/usage.md documentation

---

tests/cross_functional/scale/upgrade/test_upgrade_with_scaled_rgw_obc.py
tests/functional/monitoring/workload/test_workload_with_distruptions.py
tests/functional/pod_and_daemons/test_mgr_pods.py
tests/functional/storageclass/test_cross_sc_clone_snap_restore.py
tests/functional/upgrade/test_configuration.py

There are few test cases failed in run https://url.corp.redhat.com/7148982 due to CephToolBoxNotFoundException. In MCG Only deployment, ceph cluster doesn't exist, so skipping those test cases for MCG Only deployment.

Skip test cases which require tool box in MCG Only deployment

---

tests/functional/upgrade/test_resources.py

As part of the initiative "Efficiency: Identify and remove redundant/unwanted tests - within and across the ocs-ci test suites" 
Test `test_start_pre_upgrade_pod_io` is being marked as deprecated after discussing it with @fbalak. 
Quoting him for future reference:-
```
There is currently run io in bg during upgrade that conflicted with those tests. It would be good to refactor io workloads for upgrade but until there is such initiative it can be removed.
```
Refer spreadsheet- https://url.corp.redhat.com/63d158c

Renamed deprecated_test_start_pre_upgrade_pod_io under Brown squad

---

ocs_ci/helpers/dr_helpers.py
ocs_ci/ocs/dr/dr_workload.py
tests/functional/disaster-recovery/regional-dr/test_cnv_failover_and_relocate_discovered_apps.py
tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps.py

All the discovered apps vrg are created in `openshift-dr-ops` to make it compatible for the future. We should individually check for VRG that belong to the given workload and not check for all VRG in that NS. This PR will fix this problem

Improve vrg discovered app

---

tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py

test case is failing with timeout during checking of pod status.
job: https://url.corp.redhat.com/fe0ea3b

 Increase timeout for restore pod

---

ocs_ci/ocs/ocs_upgrade.py

From 4.19, new pod "cnpg-controller-manager-84bfbc5b49-c2zxc" was added. So increased the noobaa default pod count by 1.

Increase default noobaa pod count by 1 due to cnpg pod

---

ocs_ci/templates/DR/dpa_discovered_apps.yaml

This is required for [RHSTOR-6413](https://issues.redhat.com/browse/RHSTOR-6413)

Add kubevirt as plugin to DataProtectionApplication

---

tests/ecosystem/upgrade/test_upgrade_ocp.py

[release-4.14] use semantic version instead of parse_version

---

tests/functional/upgrade/test_upgrade_ocp.py

[release-4.16] use semantic version instead of parse_version

---

tests/functional/upgrade/test_upgrade_ocp.py

[release-4.17] use semantic version instead of parse_version

---

tests/functional/encryption/test_encryption_keyrotation.py
tests/functional/pv/pv_encryption/test_disable_pv_keyrotation.py

SKIP encryption external KMS config tests in case if disconnect environment.

Skip external KMS encryption tests if discunnect env deployed

---

tests/functional/z_cluster/cluster_expansion/test_add_capacity.py

This is a fix for an issue : https://github.com/red-hat-storage/ocs-ci/issues/11712
Adding retry to `osd_encryption_verification` operation

Adding retry to osd_encryption_verification operation

---

ocs_ci/helpers/managed_services.py
ocs_ci/ocs/resources/storage_cluster.py
ocs_ci/templates/ocs-deployment/provider-mode/ocs_storagecluster_converged.yaml

Following dev PR https://github.com/red-hat-storage/ocs-operator/pull/3019 we are removing spec field `allowRemoteStorageConsumers` 
Slack thread created to remove doubts about FaaS usage of that field
https://ibm-systems-storage.slack.com/archives/C081L5H77H7/p1741711111645139

remove spec field allowRemoteStorageConsumers from checks

---

ocs_ci/framework/pytest_customization/marks.py
ocs_ci/ocs/ui/views.py
tests/conftest.py
tests/functional/disaster-recovery/regional-dr/test_negative_failover_relocate_ui.py
tests/functional/disaster-recovery/regional-dr/test_rdr_monitoring_dashboard_ui.py
tests/functional/disaster-recovery/regional-dr/test_warning_and_alerting.py

Test to verify that "VolumeSynchronizationDelay" warning level alert is fired on the DR dashboard when the lastGroupSyncTime is lagging behind 2x or critical level alert when this value is behind 3x the sync interval defined in DRPolicy applied to a particular workload.
No DR action is performed in this test case. We scale down rbd-mirror daemon deployment on the secondary cluster and mds daemons on the primary cluster and scale them up back to their original count.
Also added and updated the name to marker to `@rdr_ui` as per my discussion with @sidhant-agrawal

VolumeSynchronizationDelay alert on the DR dashboard due to sync delays

---

ocs_ci/deployment/deployment.py
ocs_ci/deployment/helpers/odf_deployment_helpers.py

Increasing bluestore_slow_ops_warn_threshold and bluestore_slow_ops_warn_lifetime due to bug https://issues.redhat.com/browse/DFBUGS-1913

increase bluestore_slow_ops_warn_threshold and bluestore_slow_ops_warn_lifetime

---

tests/functional/ui/test_alert_text.py
tests/functional/ui/test_capacity_breakdown_ui.py
tests/functional/z_cluster/cluster_expansion/test_resize_osd.py

we do not have access to create lkubeadmin credentials and login to management-console on IBM Cloud
Usually we see:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeadmin-password'
Report Portal https://url.corp.redhat.com/686f7ce

add skipif ibm cloud managed in more ui tests

---

ocs_ci/ocs/platform_nodes.py
ocs_ci/utility/ibmcloud_bm.py
tests/libtest/test_ibm_cloud_bm.py

IBMCloudBMNodes stop_nodes method is waiting for node NotReady status after powering off the machines. In certain cases, the cluster will not be accessible after the nodes are down. In such cases, added an alternate way to check if the machine is powered off.
Used the output from sensor data to check if the RPM sensor data is available. This is not available if the machine is off.
Fixes #11732

Add an alternate way to verify if the IBM cloud BM machines are stopped

---

ocs_ci/deployment/mce.py

Trying to extend the timeout for `check_resource_existence` in `mce` `check_supported_versions`, because the deployment is failing like this:
```
08:12:26 - MainThread - ocs_ci.ocs.ocp - WARNING  - Failed to get resource: supported-versions of kind: ConfigMap, selector: None, Error: Error during execution of command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n hypershift get ConfigMap supported-versions -n hypershift -o yaml.
Error is Error from server (NotFound): configmaps "supported-versions" not found
08:12:26 - MainThread - ocs_ci.ocs.ocp - WARNING  - Number of attempts to get resource reached!
08:12:26 - MainThread - ocs_ci.ocs.ocp - INFO  - Resource: 'supported-versions', selector: 'None' was not found.
08:12:26 - MainThread - …
```

extend timeout in mce check_supported_versions

---

ocs_ci/ocs/utils.py

This PR backports #11183 to the release-4.16 branch.

[release-4.16] Preserve the working directory during log collection

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/utils.py

The pods with name "status-reporter" will have its expected state as Completed and may automatically removed from the cluster. By the time of getting RPM package after collecting the pod list, these pods might have gone from the cluster. This will trigger NotFound error.
Fixes #11626

Skip status-reporter type of pod in rpm package collection

---

tests/functional/z_cluster/cluster_expansion/test_add_capacity.py

Cherry-Pick from 4.19 -> 4.18
This is a fix for an issue : https://github.com/red-hat-storage/ocs-ci/issues/11712
Adding retry to osd_encryption_verification operation

[release-4.18] [cherry-pick-11724] Adding retry to osd_encryption_verification operation

---

ocs_ci/deployment/mce.py

Fixing this small issue (the `-n` parameter is not separated from the `.../image-override.json`  file parameter):
```
2025-04-02 11:21:28  05:21:28 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc create cm hypershift-override-images-new --from-file=/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/templates/mce-deployment/image-override.json-n multicluster-engine
2025-04-02 11:21:28  05:21:28 - MainThread - ocs_ci.utility.utils - WARNING  - Command stderr: error: exactly one NAME is required, got 2
2025-04-02 11:21:28  See 'oc create configmap -h' for help and examples
```

add missing space to oc create cm command in mce.py module

---

ocs_ci/deployment/deployment.py
tox.ini

Fix #11775 
Set the namespace="default" in exec_oc_debug_cmd to avoid PodSecurity violations in restricted namespaces like openshift-storage. The debug command now runs successfully using the default namespace.
Debug node on openshift-storage before OCS installation:
```
$ oc debug nodes/compute-0 --to-namespace=openshift-storage  -- chroot /host /bin/bash -c "ip link set promisc on ens224 || echo \'CMD FAILED\';" --overwrite
error: PodSecurity violation error:
Ensure the target namespace has the appropriate security level set or consider creating a dedicated privileged namespace using:
"oc create ns <namespace> -o yaml | oc label -f - security.openshift.io/scc.podSecurityLabelSync=false pod-security.kubernetes.io/enforce=privileged pod-security.kubernetes.io/audit=privileged …
```

Fix oc debug PodSecurity violation by setting namespace to 'default'

---

ocs_ci/utility/environment_check.py

Due to the new convergence changes in 4.19 a cronjob is consistently creating and destroying a pod in order to report the client status:
```
storageclient-737342087af10580-status-reporter-29065673-nhwnk     0/1     Completed           0               63s
storageclient-737342087af10580-status-reporter-29065673-nhwnk     0/1     Completed           0               63s
storageclient-737342087af10580-status-reporter-29065675-5z8v8     0/1     Pending             0               0s
storageclient-737342087af10580-status-reporter-29065675-5z8v8     0/1     Pending             0               0s
storageclient-737342087af10580-status-reporter-29065675-5z8v8     0/1     Pending             0               0s
storageclient-737342087af10580-status-reporter-29065675-5z8v8     0/1     ContainerCreating …
```

Ignore the storageclient-status-reporter pod leftovers

---

ocs_ci/deployment/hosted_cluster.py
ocs_ci/helpers/managed_services.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/storage_client.py
ocs_ci/ocs/resources/storage_cluster.py
ocs_ci/ocs/resources/storageclassclaim.py
tests/functional/storageclass/test_storageclassclaim.py

With change in this dev PR https://github.com/red-hat-storage/ocs-client-operator/pull/302 we are removing use of StorageClaim.
Important! StorageClaim on upgraded clusters will not be automatically removed, but will stop to reconcile

storage claim removal

---

ocs_ci/deployment/provider_client/storage_client_deployment.py
ocs_ci/helpers/helpers.py
ocs_ci/ocs/resources/storage_client.py
tests/libtest/test_provider_create_hosted_cluster.py

With change in this dev PR https://github.com/red-hat-storage/ocs-client-operator/pull/302 we are removing use of StorageRequest.
Important! StorageRequest on upgraded clusters will not be automatically removed, but will stop to reconcile

storage request removal

---

ocs_ci/ocs/bucket_utils.py

Stabilize `test_default_buckets_backingstore` by using a `retry` when fetching data about a bucket's tiers

---

tests/functional/object/mcg/test_admission_control.py

This test has been consistently skipped in our regression runs because it didn't have a tier decorator.

Restore `test_pvpool_downscaling` by adding a tier decorator

---

ocs_ci/ocs/resources/objectbucket.py

The test_bucket_list test case was occasionally failing due to deletion timeout of 60 secs. 
Github issue: 
https://github.com/red-hat-storage/ocs-ci/issues/11846
The timeout was increased to 120sec.
The second timeout for tier4 remains 15 mins ( in seconds).

Increasing bucket deletion timeout - fix to issue#11846

---

ocs_ci/deployment/disconnected.py

The aim of this change is to prevent failures like this: https://url.corp.redhat.com/41607b4
```
[2025-03-31T09:12:21.070Z] E               error: unable to retrieve source image registry.redhat.io/odf4/odf-cosi-sidecar-rhel9 manifest sha256:c510d8c75abb7aa0c60d05ede47c4b12bdc4491b1520cc007cccba5f5cf5057b: received unexpected HTTP status: 502 Bad Gateway
[2025-03-31T09:12:21.070Z] E               error: an error occurred during planning
[2025-03-31T09:12:21.070Z] 
[2025-03-31T09:12:21.070Z] ocs_ci/utility/utils.py:722: CommandFailed
```
This approach will most probably not solve all possible issues with mirroring packages via oc mirror command, the main reason is that we are not able to apply ICSP/IDMS rules during the mirroring process via `oc mirror` command, so some of the images from …

add @retry to mirror_index_image_via_oc_mirror

---

conf/README.md
ocs_ci/framework/conf/default_config.yaml
ocs_ci/framework/pytest_customization/ocscilib.py

If `kubeconfig` file is not provided and there is `OCP_URL` and `KUBEADMIN_PASSWORD` environment variables set, it tries to login to the OCP cluster via the provided OCP URL and `kubeadmin` password and create `kubeconfig`.
This will be helpful for tests execution in environments where the `kubeconfig` is not available and rest of the automation rely on OCP URL and `kubeadmin` password.

allow login to OCP via provided OCP URL and kubeadmin password

---

tests/functional/monitoring/prometheus/metrics/test_monitoring_defaults.py

This PR introduces a test to verify the connectivity of `rook-ceph-exporter` pods to OpenShift Prometheus over **IPv6**.  
1. Retrieve the **IPv6 addresses** of `rook-ceph-exporter` pods.  
2. Identify the `prometheus-k8s` pod in the **openshift-monitoring** namespace.  
3. Use `curl` from within the `prometheus-k8s` pod to access the `/metrics` endpoint of each exporter via IPv6.  
4. Verify that the response contains the expected Ceph metric: **`ceph_AsyncMessenger_Worker_msgr_connection`**.

Verify IPv6 Connectivity Between Rook-Ceph-Exporter and OCP Prometheus

---

setup.py

The new version of `marshmallow` (4.0.0) seems to be broken, any execution of run-ci command is failing with following traceback:
```
File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_result.py", line 100, in get_result
raise exc.with_traceback(exc.__traceback__)
File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.9/site-packages/pluggy/_callers.py", line 103, in _multicall
res = hook_impl.function(*args)
File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.9/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
self.parse(args)
File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.9/site-packages/_pytest/config/__init__.py", line 1283, in …
```

Workaround: freeze older version of marshmallow==3.26.1

---

setup.py

This is a backport of https://github.com/red-hat-storage/ocs-ci/pull/11933
because of issue:
https://github.com/rhevm-qe-automation/pytest_jira/issues/153

Workaround: freeze older version of marshmallow==3.26.1 - backport to 4.18

---

setup.py

This is backport of https://github.com/red-hat-storage/ocs-ci/pull/11933

Workaround: freeze older version of marshmallow==3.26.1 (backport 4.17)

---

ocs_ci/ocs/resources/bucket_notifications_manager.py

MCG's bucket notification connection secret scheme for Kafka is getting updated in https://github.com/noobaa/noobaa-core/pull/8889 - this change is simply catching up to the change.

Update MCG's bucket notification connection secret scheme for Kafka

---

ocs_ci/deployment/assisted_installer.py

Properly set config.RUN["kubeconfig"] during OCP deployment via Assisted Installer.

set config.RUN["kubeconfig"] to the propper path for AI OCP deployment

---

ocs_ci/ocs/ocp.py

Fixes #11972 
This expects ENV_DATA key 'odf_provider_mode_deployment' which is now commonly used in deployment job only and not in test runs. Use the string 'hci_' to check in ENV_DATA.platform to confirm the cluster is provider mode.

Use hci keyworkd instead of odf_provider_mode_deployment to identify the cluster configuration

---

ocs_ci/ocs/bucket_utils.py

This PR contains a fix to https://github.com/red-hat-storage/ocs-ci/issues/11410.
During a discussion with @sagihirshfeld the following came up :
We had many tests in test_bucket_policy.py that failed in a similar way, and they stopped failing once we added a wait of some sort after setting the bucket policy on the bucket. Either via hardcoded sleep or by using retry on the failing operation:
https://github.com/red-hat-storage/ocs-ci/issues/10982
https://github.com/red-hat-storage/ocs-ci/issues/9013
https://github.com/red-hat-storage/ocs-ci/issues/8156
Therefore this PR contains adding retries for setting bucket policy.

Adding a retry after setting the bucket policy on the bucket to fix issue #11410 

---

ocs_ci/deployment/helpers/hypershift_base.py
ocs_ci/deployment/hosted_cluster.py
ocs_ci/ocs/constants.py
tests/conftest.py
tests/libtest/test_provider_create_hosted_cluster.py

This PR does: 
1. rework for fixture create_hypershift_clusters, splitting it to 3 different fixtures:
a) create_hypershift_clusters_push_config - will create hosted cluster with default preferences, provision it with similar OCP and ODF versions that Provider has
b) create_config_of_existing_hosted_clusters - will add config only if cluster exist in deployment but multicluster config does not
c) refresh_hosted_config - will replace configs of existing clusters with newly generated
2.  rework for fixture destroy_hosted_cluster, splitting it to 2 different fixtures
a) destroy_hosted_cluster
b) hosted_cluster_remove_config
**it allows us to remove config during test suit execution, when hitting unhealthy cluster** 
-----
Pr is a necessary rework that partially allows us to run all tests …

generate and update multicluster config on flight

---

ocs_ci/utility/utils.py

Fix "Executing command: " log message from `exec_cmd` with `shell=True`.
The output without this fix looks like this:
```
2025-04-24 11:23:57  05:23:57 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: c d ' ' / t m p / t m p x l i a f k _ g ' ' '&' '&' ' ' m a k e ' ' h y p e r s h i f t ' ' p r o d u c t - c l i
```

fix log output from exec_cmd

---

ocs_ci/templates/ocs-deployment/provider-mode/storage_client.yaml

minor issue that causes duplicates in storageClass distribution. 
> Rewant Soni
> Is 4.19.0-49k the latest version? There was a bug with a workaround does this build include that fix?
> For most of the backend related issue that you have I see that you have used a different name for the storage client name - "storage-client". This is an unsupported configuration. The only customers we have for Provider Mode are Fusion and they are using the name "ocs-storagecluster" for the external clients well and they will continue to do that. Using a different name means that the storageClass name will be different and things will break. Please fix the ci to use the right storage client name for external clients "ocs-storagecluster" and then run the upgrade test using the latest version.
> For 4.18 …

rename storageClient. address issue with distribution of sc

---

ocs_ci/ocs/constants.py

it seems to be not available in redhat-operator-index:v4.19

remove elasticsearch operator for 4.19

---

tests/functional/disaster-recovery/regional-dr/test_neutral_hub_failure_and_recovery.py

When the active ACM hub cluster is at a neutral site and goes down, we perform hub recovery and switch to the passive hub using backup and restore. After successful hub recovery, the primary managed cluster is brought down and workloads are failedover. 
Post successful failover, we recover the down managed cluster and ensure it undergoes cleanup of all the failedover workloads. Post cleanup, we relocate these workloads back to their original primary cluster.

[RDR] Neutral ACM hub failure and recovery

---

ocs_ci/ocs/bucket_utils.py
ocs_ci/ocs/resources/mcg_lifecycle_policies.py
tests/functional/object/mcg/test_lifecycle_configuration.py

This PR adds the happy path coverage for the additional S3 lifecycle configuration options that are being added to MCG in https://issues.redhat.com/browse/RHSTOR-6624:
- `test_abort_incomplete_multipart_upload` - tests the option to auto-abort multipart uploads that have not been completed within a certain number of days
- `test_noncurrent_version_expiration` - tests the option to expire non-current versions based on time and the number of existing versions
- `test_expired_object_delete_marker` - tests the option to automatically delete delete markers when no current version of the object exists

[RHSTOR-6624] - Missing MCG Lifecycle Configuration rules: basic tests and utils

---

ocs_ci/ocs/ocs_upgrade.py

noobaa-default-backing-store-noobaa-pod is part of default_noobaa_pods in MCG only deployment

---

ocs_ci/ocs/resources/pod.py
tests/functional/pod_and_daemons/test_csiaddon_pod_security.py

This PR adds a new test case to validate the CSI Addon pods’ compliance with Pod Security Standards.
The test ensures that the csi-addons container inside the CSI RBD Nodeplugin pod:
- Is securely reachable over HTTPS.
- Correctly rejects insecure (plain HTTP) connections.

Add CSI Addon Pod Security Validation Test

---

ocs_ci/utility/framework/fusion_fdf_init.py
ocs_ci/utility/framework/initialization.py

When the `run_id` is taken just from seconds timestamp, there is a possibility that two runs will get the same `run_id`:
* https://url.corp.redhat.com/209791b
* https://url.corp.redhat.com/6cc73a3
This situation breaks the reporting to Report Portal and might cause another issues.
To minimize this risk, we can use miliseconds as run_id.

Make sure run_id is unique by using miliseconds instead of only seconds

---

conf/deployment/fusion_hci_pc/client_bm_upi_1az_rhcos_nvme_2w.yaml
conf/deployment/fusion_hci_pc/client_bm_upi_1az_rhcos_nvme_3w.yaml

`nodepool_replicas` were not used and `worker_replicas` used instead, when deployment job expected to get  `nodepool_replicas`, hence default value '2' always takes place

fix existing yaml configs with nodepool replicas

---

tests/functional/pv/pvc_resize/test_pvc_expansion_when_full.py

Use different files to write data instead of overwriting the same file.
Add fsync parameter in run_io.
These changes will avoid the delay in deleting the PV and fixes the two issues given below.
Fixes #10740 
Fixes #10739

Use separate fio files and add sync after I/O in test test_pvc_expansion_when_full

---

tests/functional/workloads/ocp/logging/test_openshift-logging.py

Logging stack is different from logging 6.0 (lokistack) and logging 5.8(EFK) is no more supported from OCP 4.19. Hence the cluster operator fails to deploy using the old stack, The existing deployment and few tests are not relevant anymore in >= 4.19. 
https://github.com/red-hat-storage/ocs-ci/issues/11604

Skipping logging deployment/tests on 4.19 and above using old stack(EFK)

---

tests/conftest.py
tests/functional/monitoring/prometheus/alerts/test_alert_mds_cache_high_usage.py
tests/functional/monitoring/prometheus/alerts/test_alert_mds_cpu_high_usage.py
tests/functional/pv/pv_services/test_cephfs_pvc_with_chunk_size.py
tests/functional/pv/pv_services/test_run_io_multiple_pods.py
tests/functional/pv/pv_services/test_rwo_pvc_fencing_unfencing.py
tests/functional/z_cluster/nodes/test_worker_nodes_network_failures.py

The name of the fixture function 'dc_pod_factory' is now 'deployment_pod_factory'. Updating this change in the test cases which are not updated.
In addition to this one comment is also updated with the new function argument name.
Fixes #12105

Update fixture name dc_pod_factory to deployment_pod_factory in tests

---

tests/functional/object/rgw/test_rgw_read_affinity.py

Adds happy path testing for RGW ReadAffinity feature

Adds happy path testing for RGW ReadAffinity feature

---

ocs_ci/deployment/aws.py
ocs_ci/deployment/azure.py
ocs_ci/deployment/deployment.py
ocs_ci/deployment/gcp.py
ocs_ci/deployment/helpers/storage_class.py
ocs_ci/deployment/ibmcloud.py
ocs_ci/deployment/rhv.py
ocs_ci/deployment/tests/test_cloud.py
ocs_ci/deployment/vmware.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py

Issue: https://url.corp.redhat.com/ce3ae0e

Refactor determination of storageclass for deployments

---

tests/functional/z_cluster/nodes/test_node_replacement_proactive.py

Skipping ibmcloud testcase for machine not found error: v4.17

Skipping ibmcloud testcase for machine not found error: v4.17

---

tests/functional/object/mcg/test_bucket_replication.py

- Update the noobaa-db queries to be made against the primary noobaa-db CNPG pod
- Add the Jira decorator for this regression bug that fails the test: https://issues.redhat.com/browse/DFBUGS-2353

Update noobaa-db queries at test_unidirectional_bucketclass_replication and add jira decorator for bug

---

tests/functional/object/mcg/test_verify_noobaa_status.py

Update the test to query the primary noobaa-db pod instead of the old one from 4.18

Fix `test_verify_noobaa_db_service`

---

ocs_ci/deployment/mce.py

Similar increase in time for checking supported-version cm we already have on master branch. 
Because of more robust module in master I could not cherry-pick `ocs_ci/deployment/mce.p`y from master to 4.18 
Please review this PR same way as a cherry-pick.
PR should fix this error
`https://jenkins-csb-odf-qe-ocs4.dno.corp.redhat.com/job/qe-deploy-ocs-cluster/50765/consoleFull`

add time to deploy mce on cluster 4.18

---

ocs_ci/deployment/hosted_cluster.py

Recently we changed name of the storage-client. The Convergence changes forced us to rename storage-client to specific name that our  customer uses (Fusion HCI). Doing this prevents duplication of storage classes upon distribution to clients after upgrade.  
It fixes the failure that we see in logs:
```
2025-05-15 20:30:13  >       assert all(
2025-05-15 20:30:13              client_setup_res
2025-05-15 20:30:13          ), "Storage client was not set up on all hosted ODF clusters"
2025-05-15 20:30:13  E       AssertionError: Storage client was not set up on all hosted ODF clusters
```

correct storage client name to customer used one

---

tests/conftest.py

[release-4.18] Delete thanos bucket created for ACM observability during cluster teardown

---

setup.py

We are seeing issues with our destroy jobs due to this dependency. I suspect something weird happening with the version that was released today so I am pinning this to the last version we were using successfully.
Example failure: https://url.corp.redhat.com/8858210

Pin oslo.utils version

---

ocs_ci/framework/__init__.py
ocs_ci/ocs/acm/acm.py
tests/functional/deployment/test_acm.py

Use active ACM cluster context for running the test case tests/functional/deployment/test_acm.py::test_acm_import.
Update the class RunWithAcmConfigContext to identify the active ACM index instead of expecting the first ACM cluster in the config as the active ACM cluster.
Added the decorator `switch_to_orig_index_at_last` in the function `get_clusters_env` to change back the cluster context to the initial value instead of just changing the cluster context to the first cluster in the configuration.
Fixes #12154

Use active ACM cluster context for the test test_acm_import

---

ocs_ci/ocs/resources/pod.py

Use provider cluster's `cluster_namespace` parameter if provider kubeconfig is used for tools pod in provider-client configuration.
Fixes #12184

Use provider cluster_namespace if provider kubeconfig is used for tools pod

---

tests/functional/pv/pv_encryption/test_secrets_on_pods.py

Add `runs_on_provider` decorator in the test cases under tests.functional.pv.pv_encryption.test_secrets_on_pods.TestSecretsAndSecurityContext. These test cases search for the pods that are not present in the client cluster.
This decorator is used to run the test case on provider cluster in provider mode multicluster run. 
Fixes #12218

Add runs_on_provider decorator in the tests TestSecretsAndSecurityContext

---

ocs_ci/ocs/resources/objectbucket.py

The test_bucket_list test case was occasionally failing due to deletion timeout of 60 secs.
Github issue:
https://github.com/red-hat-storage/ocs-ci/issues/11846
The timeout was increased to 180sec.
The second timeout for tier4 remains 15 mins ( in seconds).

Increasing bucket deletion timeout - fix to issue #11846

---

tests/functional/pv/pv_services/test_ceph_capacity_recovery.py

This test has to be skipped due to the benchmark operator issue temporarily
Slack chat ref - https://ibm-systems-storage.slack.com/archives/C06EEKSUPPZ/p1748332444578669

Skip test_ceph_recovery

---

ocs_ci/ocs/acm/acm.py

To import managed cluster where Multicluster Engine (MCE) is installed, the annotation klusterlet-config is needed. There is also another spec `leaseDurationSeconds` added which is obtained from ACM documentation.  
Reference : https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.13/html-single/multicluster_engine_operator_with_red_hat_advanced_cluster_management/index#hosted-import-mce 
Fixes #12271

Add the klusterlet-config annotation in ManagedCluster CR to import MCE cluster

---

ocs_ci/helpers/dr_helpers.py

Fetch mirroring status from the CBPR resource starting with ODF version 4.19

[RDR] Retrieve mirroring status from CBPR for ODF 4.19

---

terraform/ai/vsphere/vm/main.tf

Recently vSphere deployments via Assisted Installer are failing, because the installation seems to count with EFI boot mode, while the VMs are configured to legacy BIOS mode. Changing the boot mode to EFI explicitly.

Fix OCP deployment on vSphere via Assisted Installer

---

ocs_ci/ocs/bucket_utils.py
ocs_ci/ocs/resources/mcg_replication_policy.py
ocs_ci/ocs/resources/mockup_bucket_logger.py
tests/conftest.py
tests/cross_functional/conftest.py
tests/cross_functional/system_test/test_mcg_replication_with_disruptions.py

This PR covers the system test automation for 4.18 feature "MCG Bucket Replication - Support versioning"

[4.18 system test] Test bucket replication with object versioning

---

ocs_ci/ocs/ocs_upgrade.py

The disconnected upgrade seems to be failing there, becuase the packagemanifest is available a moment after the timeout expires.
I check some successful upgrades and the packagemanifest were available after about 45 seconds, so extending the timeout from 1 minute to 2 minutes to have some space for slower environments.
Example failed jobs:
* https://url.corp.redhat.com/80c7a87
* https://url.corp.redhat.com/cc13e5d

extend time for waiting for packagemanifest in set_upgrade_channel

---

ocs_ci/ocs/resources/mcg.py

Sometimes MCG.wait_for_ready_status() fails with the following error:
```
ValueError: timeout should be larger than sleep time
```
This PR fixes this edge case by making sure that the timeout is at least 60 seconds, regardless of how much time was spent in the first part of the method.
RP reference: https://url.corp.redhat.com/ad29a7d

Address edge case in MCG.wait_for_ready_status()

---

ocs_ci/ocs/bucket_utils.py
tests/functional/object/mcg/test_lifecycle_configuration.py

- Changes to docstrings and comments
- Extend expire_multipart_upload_in_noobaa_db to also expire the parts
- Remove the final step of the test where we're waiting for the parts to be marked as "deleted". While local and automated attempts have shown they do eventually get deleted, I couldn't find a way to speed up this process. Since it can take up to an hour, it's just best to remove this verification.

Fix test_abort_incomplete_multipart_upload

---

ocs_ci/deployment/hosted_cluster.py
ocs_ci/deployment/provider_client/storage_client_deployment.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/storage_client.py
ocs_ci/ocs/resources/storage_cluster.py
ocs_ci/ocs/resources/storageconsumer.py
ocs_ci/templates/ocs-deployment/provider-mode/native_storage_client.yaml
tests/functional/z_cluster/nodes/test_nodes_restart_hci.py

following the set of rules:
1. UI distributes all default storage classes, that were provisioned by odf operator
2. virtualization storage is filtered out by automation script as this is a preferable behavior, and no use sace for having this storage class
3. automation logic will be that we'd want to have all storage classes that provider have to have the same on clients, to continue with that set in testing
4. automation allows tests to delete storage classes from distribution. For that purpose user must modify StorageConsumer cr on provider's side.

added storage classes to storage consumer for distribution

---

tests/functional/storageclass/test_csi_subvolume_group_property.py

Add `polarion_id` and `jira` marker in the test case tests/functional/storageclass/test_csi_subvolume_group_property.py::TestCSISubvolumeGroup::test_subvolume_group_pinning
Changed from tier3 to tier2 because this is not a negative test case.
Fixes #12358

Add polarion and jira marker in the test case test_subvolume_group_pinning

---

.gitignore
ocs_ci/deployment/fusion_data_foundation.py
ocs_ci/helpers/helpers.py

These changes address some circular import issues I hit when trying to use `get_worker_nodes`.  This is also to help backporting the FDF changes to release-4.18.

FDF import fix

---

tests/functional/pv/pvc_clone/test_clone_when_pvc_full.py

Update the label selector for the provisioner pod to the value in 4.19.
Additionally, add missing whitespace around arithmetic operator.
Fixes #12363

Update provisioner label in the test test_clone_when_full

---

ocs_ci/deployment/assisted_installer.py
ocs_ci/deployment/baremetal.py

Handle pending user action during OCP deployment on baremetal servers via Assisted Installer. This usually means, that the server didn't properly boot from the disk when rebooted during the deployment. It seems to be usually just temporary issue and another reboot fixes the issue.
Fixes: [OCSQE-3815](https://issues.redhat.com//browse/OCSQE-3815)

BM OCP deployment via Assisted Installer: handle pending user action

---

ocs_ci/ocs/resources/pod.py
tests/cross_functional/kcs/test_noobaa_db_backup_and_recovery.py
tests/cross_functional/kcs/test_noobaadb_pw_reset.py

Fixes https://github.com/red-hat-storage/ocs-ci/issues/12379 and https://github.com/red-hat-storage/ocs-ci/issues/12380 
and deprecate test_noobaa_db_backup_and_recovery[According to new changes introduced in 4.19 https://issues.redhat.com/browse/RHSTOR-6436, the existing backup-and-recovery procedure for the noobaa-db(https://access.redhat.com/solutions/6686081) is no more valid]

fix test cases

---

ocs_ci/ocs/resources/pod.py
tests/functional/pod_and_daemons/test_csi_logs_rotation.py

this PR is fixing issue with indexError and incorrect plugin labels

fix test_pods_csi_log_rotation 4.18,4.19

---

ocs_ci/deployment/helpers/hypershift_base.py

Added parameter to apply to a nodepool on kubevirt cluster creation.
"Enables machine autorepair with machine health checks, default True"

Enables machine autorepair with machine health checks

---

tests/functional/object/mcg/test_pv_pool.py

This PR contains 3 test cases for happy path testing of [RHSTOR-6635](https://issues.redhat.com//browse/RHSTOR-6635) - Qualify "NooBaa Backing Store Data Distribution and Rebalancing". 
The dataset is 20 files, 10MB each.
In each test cases the test verifies data distribution of the dataset on 2 pv-backed backinstores, each one has 1/5/10 backed pvs. 
The data should be distributed evenly between all the pvs, while the accepted standard deviation of the average data written to the PVs is 20%.

Ypersky pv based bs data distribution

---

ocs_ci/ocs/constants.py
ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py

fixes failing test_error_improvements.py::TestErrorMessageImprovements::test_obc_creation_rules as the wording of the 'not used before' rule changed in 4.19 https://jenkins-csb-odf-qe-ocs4.dno.corp.redhat.com/job/qe-deploy-ocs-cluster/48762/consoleFull

Change wording of obc creation rule

---

ocs_ci/utility/utils.py

Resolve timing issue:
```
ests/functional/upgrade/test_upgrade_ocp.py::TestUpgradeOCP::test_upgrade_ocp immediately after test execution: 6602.12
2025-06-21 18:47:02  FAILED
2025-06-21 18:47:02  _______________________ TestUpgradeOCP.test_upgrade_ocp ________________________
2025-06-21 18:47:02  
2025-06-21 18:47:02  node_names = ['baremetal1-04'], status = 'Ready', timeout = 360, sleep = 30
2025-06-21 18:47:02  
2025-06-21 18:47:02      def wait_for_nodes_status(
2025-06-21 18:47:02          node_names=None, status=constants.NODE_READY, timeout=180, sleep=3
2025-06-21 18:47:02      ):
2025-06-21 18:47:02          """
2025-06-21 18:47:02          Wait until all nodes are in the given status
2025-06-21 18:47:02      
2025-06-21 18:47:02          Args:
2025-06-21 18:47:02 …
```

add more time for wait node: multi-client upgrade

---

tests/functional/pv/pv_services/test_rwop_pvc.py

There was a problem -  because of how polarion plugin works - it updates the test run of a single polarion test case per each test , which means that only one of the polarion IDs gets updated and all others are not. 
Therefore the polarion test cases that referred to the same flow were unified to one. 
Irrelevant test cases would be removed from Polarion.

Removing irrelevant polarion ids

---

ocs_ci/ocs/resources/storageconsumer.py

avoid failure seen in this run: https://url.corp.redhat.com/086b8af 
```
@if_version(">4.18")
def get_onboarding_ticket_secret(self):
"""
Get OnboardingTicketSecret from storageconsumer resource status. Optional field.
Reference to name of an onboarding secret cr.
Returns:
string: OnboardingTicketSecret
"""
with config.RunWithConfigContext(self.consumer_context):
return (
>               self.ocp.get(resource_name=self.name)
.get("status")
.get("onboardingTicketSecret")
.get("name")
)
E           AttributeError: 'NoneType' object has no attribute 'get'
```

get_onboarding_ticket_secret add retry

---

ocs_ci/ocs/bucket_utils.py

Fix issue seen here: https://url.corp.redhat.com/d5642c9
```
tests/functional/deployment/test_deployment.py::test_deployment immediately after test execution: 17.05
2025-06-24 15:35:42  FAILED
2025-06-24 15:35:42  _______________________________ test_deployment ________________________________
2025-06-24 15:35:42  
2025-06-24 15:35:42  pvc_factory = <function pvc_factory_fixture.<locals>.factory at 0x7f72da0def70>
2025-06-24 15:35:42  pod_factory = <function pod_factory_fixture.<locals>.factory at 0x7f72da0de8b0>
2025-06-24 15:35:42  
2025-06-24 15:35:42      @purple_squad
2025-06-24 15:35:42      @deployment
2025-06-24 15:35:42      @polarion_id(get_polarion_id())
2025-06-24 15:35:42      def test_deployment(pvc_factory, pod_factory):
2025-06-24 15:35:42          deploy = …
```

add retry on backingstore readiness

---

ocs_ci/ocs/resources/storageconsumer.py

Added catch for Assertion errror for storageconsumer and  config map verification on fresh deployments.
We expected to have these changes in secret names as a part of the fix of https://issues.redhat.com/browse/DFBUGS-2840.

disable consumer check to prevent build failures

---

ocs_ci/ocs/resources/storageconsumer.py

following #12556 closing gaps with TypeError and other possible exceptions

disable-consumer-check-tmp-typeerror

---

ocs_ci/deployment/hosted_cluster.py
ocs_ci/ocs/acm_upgrade.py
ocs_ci/ocs/provider_client_upgrade.py

following the discussion in slack thread: we need to manually bump image tag in catalog sources of client clusters before starting or during ODF upgrade: https://url.corp.redhat.com/c02f0d2

bump catsrc of hcp clients on upgrade

---

conf/ocsci/dr_ui.yaml
ocs_ci/framework/pytest_customization/marks.py
ocs_ci/helpers/dr_helpers.py
ocs_ci/helpers/dr_helpers_ui.py
ocs_ci/ocs/acm/acm.py
tests/conftest.py
tests/functional/disaster-recovery/regional-dr/test_failover.py
tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate.py
tests/functional/disaster-recovery/regional-dr/test_negative_failover_relocate_ui.py
tests/functional/disaster-recovery/regional-dr/test_rdr_monitoring_dashboard_ui.py
tests/functional/disaster-recovery/regional-dr/test_relocate.py
tests/functional/disaster-recovery/regional-dr/test_warning_and_alerting.py

As discussed in RDR-QE syncup meeting, we want to parameterize rdr_ui tests with CLI and remove using global config so that we have coverage from both sides in a single pipeline job, be it acceptance or regression runs.
Also fixes issue #12067

Parameterize rdr_ui tests with CLI and remove using global config

---

ocs_ci/deployment/helpers/external_cluster_helpers.py

Discussed here:
https://ibm-systems-storage.slack.com/archives/C06P8GN3W85/p1751557620150609
In ramen-dr-tech-discussion channel

Fix MDR setup with avoiding removal rgw-admin-ops-user for non primary cluster

---

ocs_ci/ocs/ui/deployment_ui.py
ocs_ci/ocs/ui/page_objects/page_navigator.py
ocs_ci/ocs/ui/views.py

In ODF 4.19, StorageSystem CR and StorageSystem button has been removed from the Installed Operators page which was under the ODF operator. 
This PR is to fix the broken UI deployment and make it adjustable to the new flow. 
Fixes #12581

Fix 4.19 UI deployment to meet convergence changes

---

tests/cross_functional/system_test/test_mcg_replication_with_disruptions.py

Fixes: https://github.com/red-hat-storage/ocs-ci/issues/10736

To skip system_test.test_mcg_replication_with_disruptions on aws

---

ocs_ci/deployment/provider_client/storage_client_deployment.py

in provider_client/storage_client_deployment.py module
The original `retry` logic didn't work properly, because for example in this job: https://url.corp.redhat.com/edcdcb0 the StorageCluster creation command was executed only once and wasn't re-tried:
```
2025-07-15 18:11:04  12:11:01 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig apply -f /home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/templates/ocs-deployment/provider-mode/ocs_storagecluster_converged.yaml
2025-07-15 18:11:04  12:11:01 - MainThread - ocs_ci.utility.utils - WARNING  - Command stderr: error: resource mapping not found for name: "ocs-storagecluster" namespace: "openshift-storage" from …
```

fix retry code for StorageCluster creation

---

conf/ocsci/disable_high_recovery_during_rebalance.yaml
ocs_ci/deployment/helpers/odf_deployment_helpers.py
ocs_ci/framework/conf/default_config.yaml
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/helpers/odf_cli.py
ocs_ci/ocs/cluster.py
ocs_ci/ocs/constants.py
ocs_ci/utility/decorators.py
tests/functional/conftest.py
tests/functional/z_cluster/cluster_expansion/test_add_capacity.py
tests/libtest/test_wait_for_ceph_rebalance.py

fix https://github.com/red-hat-storage/ocs-ci/issues/11290.
The PR implements the following:
- Extend the `ODFCliRunner` to include methods for setting the recovery profile using the CLI tool and add a new helper function `odf_cli_setup_helper` to easily get the `ODFCliRunner` instance.
- Add two new decorators: 
- `enable_high_recovery` - to temporarily switch the Ceph recovery profile to 'high_recovery_ops' during the execution of the wrapped function, and revert it afterward. 
- `enable_high_recovery_if_io_flag` - to temporarily switch the Ceph recovery profile to 'high_recovery_ops' during the execution of the wrapped function, and revert it afterward only if the IO flag is marked(and we run IO in the background). 
- Use the decorator `enable_high_recovery_if_io_flag` for the method …

Create new decorator to enable the recovery profile High in the Ceph rebalance

---

tests/functional/object/mcg/test_namespace_crd.py

Skips executing IBM backed NSFS creation test if FIPS is enabled on cluster
Fixes #12634

Skips executing IBM backed NSFS creation test if FIPS is enabled on cluster

---

tests/functional/encryption/test_mon_failure_in_intransit_encryption.py

Add the marker `runs_on_provider` in the test tests/functional/encryption/test_mon_failure_in_intransit_encryption.py::TestMonFailuresWithIntransitEncryption::test_mon_failures_with_intransit_encryption
The test steps are designed to run on the provider cluster only.
Removed duplicate marker `green_squad`.
Fixes #12645

Add runs_on_provider decorator in TestMonFailuresWithIntransitEncryption

---

ocs_ci/ocs/ui/workload_ui.py

In disconnected deplyoments, mirror images used in WorkloadUi to mirror registry.
This is fixing test_requested_capacity_breakdown test failure on disconnected deployments.

enable workload_ui.WorkloadUi for disconnected clusters

---

ocs_ci/ocs/resources/namespacestore.py

This PR resolves issue https://github.com/red-hat-storage/ocs-ci/issues/12132 and https://github.com/red-hat-storage/ocs-ci/issues/12112 .
The upper limit of the timeouts was increased, while the timeout sampler will make sure that in case the operation takes less than timeout - the test will proceed and will not wait for 240 sec.

Inscreasing timeouts for nss creation and nss deletion

---

tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py

There is https://issues.redhat.com/browse/DFBUGS-3636 issue with kubelet that is triggered after the node crash. This will impact other test as well. Hence we need to skip this test until we have fix or WA implemented

Skip crash test in stretch cluster until we have WA implemented or fix

---

ocs_ci/helpers/disconnected.py

Recently mirroring images for 4.17 failed with following error:
```
$ oc mirror --config imageset-config-1753355846917.yaml docker://mirror-registry.example.com:5000 --dest-skip-tls --ignore-history
...
error: the manifest type *ocischema.DeserializedImageIndex is not supported
error: the manifest type *ocischema.DeserializedImageIndex is not supported
error: the manifest type *ocischema.DeserializedImageIndex is not supported
error: an error occurred during planning
```
This seems to be some limitation of older `oc-mirror` version, changing it to the latest one (`main`) where it seems to be fixed.

use latest oc-mirror version for images mirroring - release-4.17

---

ocs_ci/ocs/ui/workload_ui.py

In disconnected deplyoments, mirror images used in WorkloadUi to mirror registry.
This is fixing test_requested_capacity_breakdown test failure on disconnected deployments.

enable workload_ui.WorkloadUi for disconnected clusters - backport to release-4.17

---

ocs_ci/helpers/helpers.py
ocs_ci/ocs/cluster.py
tests/functional/z_cluster/cluster_expansion/test_storage_auto_scaling.py

This PR introduces a new test to validate the behavior of the StorageAutoScaler when the OCS operator is deleted during scaling, alongside improvements to cluster fill-up logic and test class structure. 
In the PR, I implemented the following:
- Added new test: test_auto_scaling_with_ocs_operator_delete
- Refactored test class hierarchy to introduce TestStorageAutoscalerBase for shared utilities
- Improved fill_up_cluster method with fast_fill_up option to reduce runtime
- Moved verify_autoscaler_no_trigger_steps to base class for reuse
- Added Polarion IDs to multiple autoscaler tests

Add a new test for autoscaler behavior with OCS operator deletion and updates metadata for existing autoscaler-related tests

---

ocs_ci/utility/deployment_openshift_logging.py
tests/functional/workloads/ocp/logging/test_openshift-logging.py

Logging tests on 4.18 and 4.17 too were failing on the issue https://github.com/red-hat-storage/ocs-ci/issues/11604
From the recent debuging session we found out that the logging version 5.8-6.1 is moved to maintenance support and full support is revoked.
https://access.redhat.com/product-life-cycles?product=Red%20Hat%20Enterprise%20Linux,Red%20Hat%20OpenShift%20Logging

Skipping ocp-logging due to issue 11604 (#12699)

---

tests/functional/object/mcg/test_custom_credentials_using_mcg_cli.py

This PR is a fix to https://github.com/red-hat-storage/ocs-ci/issues/11878 . 
The problem was the following: 
When the update account command was run with access key or secret key containing either "  or "" - we got a parsing error. 
The fix was to exclude " and "" from the characters selected randomly from the list of punctuation marks.

test_account_update_with_custom_creds_using_cli - a fix to occasional failures

---

conf/README.md
ocs_ci/framework/__init__.py

When there are more more than one provider cluster in the config (RDR test , for example), the current implementation will fetch the lower index among the provider mode cluster indexes. This PR add an additional step in the function to get the provider index based on ENV_DATA parameter `provider_cluster_name`. The client cluster config can have this value to easily identify the associated provider cluster. If the parameter is not present, current implementation will execute.

[RDR][Mulitclient]Get provider index based on config value if present

---

ocs_ci/deployment/hosted_cluster.py
ocs_ci/ocs/awscli_pod.py
ocs_ci/utility/ssl_certs.py

* Configure `trustedCA` in proxy object for hosted clusters (through `hostedclusters` object on the hosting cluster).
* provide custom CA certificate to AWS S3 cli pod, if required
The aim of this PR is to fix following failures of some tests on Provider - Client scenario:
```
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc --kubeconfig /home/jenkins/clusters/j015-pcbaie-pm/openshift-cluster-dir/auth/kubeconfig -n s3cli-w8vslw3wbjzz3 rsh s3cli-0 sh -c 'AWS_CA_BUNDLE=/tmp/ca-bundle.crt AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=.... AWS_DEFAULT_REGION=us-east aws s3 --endpoint=https://s3-openshift-storage.apps.cluster.example.com:443  cp /test_objects/airbus.jpg s3://oc-bucket-.../airbus.jpg'.
Error is upload failed: ../test_objects/airbus.jpg to …
```

configure proxy trustedCA in hosted clusters and provide custom CA certificate to AWS s3 cli pod

---

ocs_ci/helpers/osd_resize.py
tests/functional/z_cluster/cluster_expansion/test_resize_osd.py

fix https://github.com/red-hat-storage/ocs-ci/issues/11663
In this PR, we changed the Ceph capacity validation to be based on the expected storage size per OSD and the number of OSDs. This provides a direct and accurate way to verify that the Ceph raw capacity reflects the updated OSD sizes after a resize operation.

Fix the Ceph capacity validation after the OSD resize test

---

tests/functional/storageclass/test_custom_storageclass_names.py

Creating a StorageClass as a Day 2 operation is not supported in provider mode; hence, skipping the custom StorageClass test cases.

Skip customstorageclass tests on provider mode

---

ocs_ci/utility/kms.py

raise appropriate error when Noobaa encryption key not found in CipherTrust Manager

---

ocs_ci/templates/ocs-deployment/multicluster/mirror_peer_rdr.yaml

This PR updates the MirrorPeer template to remove deprecated fields
- Removed schedulingIntervals field: Deprecated and no longer needed.
- Also updated labels and type field

[release-4.18] [RDR] Update MirrorPeer template to remove deprecated field

---

ocs_ci/deployment/hosted_cluster.py

syntax issue - fix
failure:
https://url.corp.redhat.com/1b33f35
```
2025-08-13 14:09:09  Error is Error from server (NotFound): storageconsumers.ocs.openshift.io "consumer-<ocs_ci.deployment.hosted_cluster.HostedODF" not found
```

consumer-verification-on-client-creation fix

---

ocs_ci/deployment/helpers/hypershift_base.py
ocs_ci/deployment/hosted_cluster.py
ocs_ci/deployment/ocp.py
ocs_ci/framework/exceptions.py
ocs_ci/framework/pytest_customization/marks.py
ocs_ci/framework/pytest_customization/ocscilib.py
ocs_ci/ocs/constants.py
ocs_ci/ocs/resources/ocs.py
ocs_ci/ocs/resources/packagemanifest.py
ocs_ci/ocs/resources/pod.py
ocs_ci/utility/version.py
tests/conftest.py
tests/functional/object/mcg/test_provider_client.py
tests/functional/pod_and_daemons/test_ephemeral_pod.py
tests/functional/pv/pv_services/test_create_large_sized_pvc_while_io_in_progress.py
tests/functional/pv/pv_services/test_pvc_concurrent_deletion_creation.py
tests/functional/pv/pv_services/test_pvc_deletion_during_io.py
tests/functional/pv/pv_services/test_pvc_rwx_writeable_after_pod_deletions.py
tests/functional/pv/pv_services/test_raw_block_pv.py
tests/functional/pv/pv_services/test_run_io_multiple_pods.py
tests/functional/pv/pv_services/test_rwop_pvc.py
tests/functional/pv/pv_services/test_verify_rwo_using_multiple_pods.py
tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py
tests/functional/pv/pvc_resize/test_pvc_expansion.py
tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py
tests/functional/pv/pvc_snapshot/test_rbd_block_pvc_snapshot.py
tests/functional/pv/pvc_snapshot/test_snapshot_restore_with_different_access_mode.py
tests/libtest/test_multicluster.py

This PR is a clean rebase of #12007 Draft. Draft 12007 was initially done for demonstration purpose. 
Due to complexity of the changes and fact of #12007 heavy relying on already merged #11864 decided to push another PR
----
Additionally, to make test_pod_with_same_priority Pass without errors on health check and pre-run hooks issues were addressed: 
1) Collect ceph version and versions of images from provisioning plugins
2) Get tool pod for multi-client scenarios (executed on ceph cluster even when running test on client)
3) Ceph health checks for multi-client scenarios (executed on ceph cluster even when running test on client)

Run on all clients push missing configs

---

ocs_ci/framework/pytest_customization/marks.py

fix issue after run-ci for OCP Deployment and single Deploy OCS without multiple clusters provided. 
traceback:
```
2025-08-14 15:21:21  Traceback (most recent call last):
2025-08-14 15:21:21    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/bin/run-ci", line 33, in <module>
2025-08-14 15:21:21      sys.exit(load_entry_point('ocs-ci', 'console_scripts', 'run-ci')())
2025-08-14 15:21:21    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/framework/main.py", line 30, in main
2025-08-14 15:21:21      return pytest.main(arguments)
2025-08-14 15:21:21    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.9/site-packages/_pytest/config/__init__.py", line 143, in main
2025-08-14 15:21:21      config = _prepareconfig(args, plugins) …
```

fix setup_multicluster_marker

---

tests/functional/workloads/test_create_scale_pods_and_pvcs_using_kube_job.py

Description:
From the discussions https://ibm-systems-storage.slack.com/archives/C06GGES4810/p1755105146062679, we are moving the tests to orange squad

Moving test_create_scale_pods_and_pvcs_using_kube_job to orange squad

---

tests/functional/object/mcg/test_bucket_replication.py

Fixes #12919
Update the way we check whether the replication configuration was deleted after deleting the OBC it was set on.
In the past we were expecting the replication configuration to get deleted immediately from the DB, but now it's initially only soft-deleted by setting a `deleted` timestamp in its data. After enough time or deleted configurations have accumulated, they're supposed to get hard-deleted. More context here: https://issues.redhat.com/browse/DFBUGS-2353?focusedId=27211791&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-27211791
Update the `exec_nb_db_query` to fetch the JSON string of the relevant configuration, and then check whether it has the "deleted" key as expected.

Fix the DB query in test_unidirectional_bucketclass_replication

---

ocs_ci/framework/__init__.py
tests/libtest/test_multicluster.py

Introduce a new decorator to wrap functions or methods, as if their content were ran inside a `with config.RunWithProviderConfigContextIfAvailable():` block. The purpose of which is to make sure certain code runs only on the provider cluster and not on the clients.
We need to modify many functions and methods (especially on MCG relalted tests) so they run only on provider. The current solution works, but it results in messy code and big PRs where we'll indent hundreds if not thousands of rows to fit inside `with config.RunWithProviderConfigContextIfAvailable()` blocks.
This decorator would simplify this process.
- Added @staticmethod MultiClusterConfig.run_with_provider_context_if_available
- Added a new libtest to verify its functionality

Add decorator to wrap functions with RunWithProviderConfigContextIfAvailable

---

tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py

Increase timeout for snapshot restore in test the test tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py::TestPvcSnapshot::test_pvc_snapshot[CephFileSystem]
Fixes #11824

Increase timeout for snapshot restore in test test_pvc_snapshot

---

ocs_ci/deployment/metallb.py

With this PR we cover another case, when optional-operators catsrc exists but we still want to apply idms correction.
This function need to be called earlier, to make metallb stop pulling images from adm-d image which is propagated during  ACM/MCE deployment.
correct conflicting idms redirection should happen earlier, even in case if CatalogSource already exist.

remove adm-d mirrors for metallb installation

---

ocs_ci/ocs/benchmark_operator_fio.py
tests/conftest.py
tests/functional/z_cluster/cluster_expansion/test_storage_auto_scaling.py
tests/libtest/test_benchmark_operator.py

fix https://github.com/red-hat-storage/ocs-ci/issues/12997
This PR introduces a new parameter `max_servers` to the BenchmarkOperatorFIO class and related test fixtures, allowing users to control the maximum number of FIO server pods deployed during benchmark execution. This enhances scalability and flexibility in benchmarking scenarios.
This update adds support for a new max_servers parameter in the FIO benchmark setup, allowing users to define the upper limit of server pods used. Key changes include:
- setup_benchmark_fio: Added max_servers argument with default value of 20.
- calc_number_servers_file_size: Updated logic to dynamically calculate the number of servers and file size per server based on total_size and max_servers, ensuring better parallelism and balanced workload …

Add max_servers parameter to control FIO server pod count

---

ocs_ci/ocs/resources/bucket_notifications_manager.py
tests/functional/object/mcg/test_bucket_notifications.py

Fixes #12811
[NooBaa's bucket notifications tests](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/functional/object/mcg/test_bucket_notifications.py) have been failing due to a KeyError because of the TestEvent which doesn't match the expected schema of an actual bucket notification. 
This PR fixes that by filtering it out from the output of BucketNotificationsManager::get_events

Update BucketNotificationsManager::get_events to filter out NooBaa's TestEvent

---

ocs_ci/ocs/acm/acm.py

Add missing key when importing MCE cluster to ACM

---

ocs_ci/helpers/helpers.py
ocs_ci/ocs/constants.py
tests/functional/pod_and_daemons/test_csiaddon_pod_security.py

This is a Fix for the issue: https://github.com/red-hat-storage/ocs-ci/issues/13144
The issue was that in ODF 4.20, the CSI addon functionality has been restructured:
Before ODF 4.20: CSI RBD nodeplugin pods contained csi-addons containers directly
ODF 4.20+: CSI addon functionality is in separate dedicated pods with names like:
openshift-storage.rbd.csi.ceph.com-nodeplugin-csi-addons-*
The test was using the old approach (looking for csi-addons containers in traditional RBD nodeplugin pods), which no longer works in ODF 4.20.
New constants for ODF 4.20 CSI addon pod labels
Simplified, efficient pod discovery logic
Removed unnecessary version constraints

fix(test_csiaddon_pod_security.py): adapt CSI addon pod security test for ODF 4.20 version

---

tests/conftest.py
tests/functional/z_cluster/test_performance_profile_validation.py

This fixes https://github.com/red-hat-storage/ocs-ci/issues/12565

Ignore failures in rpm collector which causes test_change_cluster_resource_profile to fail

---

tests/functional/z_cluster/test_multiple_mds.py
tests/functional/z_cluster/test_storagesystem.py

Added 'skipif_hci_client' marker to below test cases, 
> ocs-ci/tests/functional/z_cluster/test_multiple_mds.py 
> ocs-ci/tests/functional/z_cluster/test_storagesystem.py
And added 'storagesystem' unavailable error as part of the test case
validation of test_storagesystem.py: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/ammahapa-419-upi/ammahapa-419-upi_20250708T075206/logs/test_report_1752486428.html

Added marker to skip for hci-clients

---

ocs_ci/helpers/keyrotation_helper.py
tests/functional/pv/pv_encryption/test_disable_pv_keyrotation.py

This is a fix for the issue :[ test_disable_pv_keyrotation_globally](https://github.com/red-hat-storage/ocs-ci/issues/13226)
- Increase timeout in wait_till_all_pv_keyrotation_on_vault_kms from 5 to 10 retries to allow adequate time for key rotation after cronjob recreation (100s -> 200s)
- Add wait_for_keyrotation_cronjobs_recreation() method to validate cronjobs are properly recreated and active before checking key rotation
- Enhance test_disable_pv_keyrotation_globally to include intermediate validation step that ensures cronjobs are recreated after re-enabling key rotation

fix(test_disable_pv_keyrotation_globally): resolve timing issue in PV key rotation disable/enable test

---

tests/functional/object/mcg/test_credentials_reset.py

In a rush to fix a blocker via https://github.com/red-hat-storage/ocs-ci/pull/13217, I've accidentally overridden [test_credentials_reset.py](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/functional/object/mcg/test_credentials_reset.py) with the content of the updated [test_nb_mgmt_endpoint.py](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/functional/object/mcg/test_nb_mgmt_endpoint.py).
This PR restores `test_credentials_reset.py` to its previous state ([see the 4.19 version](https://github.com/red-hat-storage/ocs-ci/blob/release-4.19/tests/functional/object/mcg/test_credentials_reset.py)), but also deprecates the `test_change_nb_admin_pw` test specifically, as was originally intended.

test_credentials_reset.py: Restore tests that were accidentally removed

---

tests/functional/pv/pvc_resize/test_pvc_expansion.py

Run IO during PVC expansion in the test case tests/functional/pv/pvc_resize/test_pvc_expansion.py::TestPvcExpand::test_pvc_expand_expanded_pvc
Fixes #11854

Run IO during PVC expansion in test case test_pvc_expand_expanded_pvc

---

conf/README.md
ocs_ci/deployment/deployment.py
ocs_ci/framework/__init__.py
ocs_ci/helpers/dr_helpers.py
ocs_ci/ocs/acm/acm.py
ocs_ci/utility/version.py

Support RDR deployment on provider and client clusters.
* Added support to configure everything related to RDR for client clusters except submariner and backup.
* Use provider cluster for verification required, eg: verifying mirrorpeer, verify mirror pods.
* Use unique name for mirrorpeer and drpolicy.
* Updated the functions get_provider_index and get_consumer_indexes_list to avoid error if provider or client cluster is not available in config.
* Added a new parameter MULTICLUSTER.dr_cluster_relations to identify the pair of RDR clusters. There will be 1 pair for deployment and multiple pair for test execution. Updated README.md to add new parameter 'dr_cluster_relations'.
* Skip creating serviceexport for multiclient mode(provider mode) because hostNetwork is True.

Support RDR deployment on provider and client clusters

---

ocs_ci/deployment/acm.py
ocs_ci/ocs/acm/acm.py

Install submariner addon on client clusters when provider, client clusters configs are present.
* Select the drclusters under test to install submariner. Use the parameter `dr_cluster_relations` from the PR https://github.com/red-hat-storage/ocs-ci/pull/12978 
* Use `ENV_DATA.cluster_set` as clusterset name if present

Submariner install on client clusters

---

ocs_ci/deployment/hosted_cluster.py

Set the default value of '`disable_default_sources`' True for hcp clusters.
This is needed because to enabled RDR on hcp clusters(used as client clusters) we need to have custom catalogsource redhat-operators created to install df operator automatically. If the default sources are not disabled, the custom catalogsource redhat-operators will be reconciled.

Make 'disable_default_sources' default True for hcp clusters

---

ocs_ci/ocs/resources/namespacestore.py

This PR is a fix for  https://github.com/red-hat-storage/ocs-ci/issues/13286.

test_obj_owner_in_obc_buckets.py - increasing timeout for nss reaching healthy state

---

ocs_ci/ocs/resources/backingstore.py
tests/functional/object/mcg/test_pv_pool.py

This PR is a fix to https://github.com/red-hat-storage/ocs-ci/issues/13273 which is increasing backingstore deletion timeout.

A fix to test_pv_data_dist - increasing backingstore deletion timeout

---

ocs_ci/deployment/fusion_data_foundation.py
ocs_ci/framework/conf/fdf_version/fdf-4.18.yaml
ocs_ci/templates/fusion-data-foundation/data-foundation-instance.yaml

Following things are being fixed with these changes 
**Not able to create a idms**
If IDMS is with the same name is there on the cluster script will and stop the pipeline there itself. for that we are checking if the df-repo is already there we are applying the latest changes.
**Not able to change FSD**
In fusion Service Definition while patching we are hardcoding the ocp version that i am getting runtime and patching the FSD correctly in this branch.
**Not able to install correct and mentioned version of the FDF**
Its always installing the gaed version, its not installing the dev version always failing the reason was simple it was not able to edit the FSD correctly.
**Backing Storage**
By default we are going for local rather dynamic because mostly Z-stream as test on Local mode.
**How …

Fixing Bugs for FDF Deployment on some SDS cluster
