- ocs_ci/ocs/bucket_utils.py
- tests/manage/mcg/test_namespace_crd.py
> Fixes object upload failure issue

- tests/conftest.py
Quick workaround
Fixes https://github.com/red-hat-storage/ocs-ci/issues/8858
> Skip env check for provider/client setup

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/gcp.py
- setup.py
Create the Google Cloud Platform node functionalities. 
Fix issue https://issues.redhat.com/browse/OCSQE-1494.
> Create the Google Cloud Platform node functionalities

- ocs_ci/framework/conf/default_config.yaml
- setup.py
> Defaulting ocs-ci to ODF 4.15

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/cloud_manager.py
- ocs_ci/ocs/resources/cloud_uls.py
- ocs_ci/ocs/resources/mcg_replication_policy.py
- ocs_ci/ocs/resources/namespacestore.py
- tests/libtest/test_azure_with_logs_infra.py
- tests/manage/mcg/test_log_based_bucket_replication.py
- Add the required support for implementing the coverage for https://url.corp.redhat.com/3f98fec.
- Add a very basic libtest to validate the above and serve as future reference
> Implement the option to create Azure NSS buckets using the new logs-enabled storage account

- conf/ocsci/vsphere_enable_hw_virtualization.yaml
- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
> Supporting Hardware Virtualization for Fusion HCI deployment in vSphere

- conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
> [release-4.11] chnage gcp project

- conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
> [release-4.12] change gcp project

- ocs_ci/utility/connection.py
> use utf-8 for decoding

- ocs_ci/framework/pytest_customization/reports.py
> remove redundant logger

- ocs_ci/ocs/utils.py
> Remove WA: Custom toolbox deployment for Multus

- conf/README.md
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_enable_hw_virtualization.yaml
> Update doc and add config file for HW virtualization

- ocs_ci/ocs/resources/pod.py
- tests/manage/z_cluster/nodes/test_disk_failures.py
fix https://github.com/red-hat-storage/ocs-ci/issues/8839
> Update getting the "ocs-osd-removal-job" name

- ocs_ci/utility/prometheus.py
Partial fix for https://github.com/red-hat-storage/ocs-ci/issues/4767
> Refresh prometheus with any error

- tests/conftest.py
Skipping due to bug https://bugzilla.redhat.com/show_bug.cgi?id=2251741
> skip verifying noobaa endpoint count

- tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
> mask the values

- ocs_ci/framework/conf/default_config.yaml
> default skip_reason_test_found to empty dictionary

- ocs_ci/ocs/ui/views.py
> Fix UI Deployment on ODF4.15

- conf/deployment/gcp/ipi_1az_rhcos_3m_3w_shielded_compute.yaml
- conf/deployment/gcp/ipi_1az_rhcos_3m_3w_shielded_control_plane.yaml
- conf/deployment/gcp/ipi_1az_rhcos_3m_3w_shielded_machines.yaml
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/templates/ocp-deployment/install-config-gcp-ipi.yaml.j2
See more details in the Jira issue: https://issues.redhat.com/browse/OCSQE-1616, and the link here: https://docs.openshift.com/container-platform/4.14/installing/installing_gcp/installing-gcp-customizations.html#installation-gcp-enabling-shielded-vms_installing-gcp-customizations.
> Support shielded nodes (VMs) for GCP

- ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
> FIPS for IBM platform

- ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
> [release-4.14] FIPS for IBM platform

- ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
> [release-4.13] FIPS for IBM platform

- tests/e2e/workloads/ocp/registry/test_pod_from_registry.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/8794
> Fix test_run_pod_local_image testcase

- tests/ui/test_validation_ui.py
> Skip test_dashboard_validation_ui from acceptance suite

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/utils.py
Fixes : #8991 
From 4.15, need to create tool box using storage-cluster
> create toolbox using storagecluster

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/resources/mcg.py
- tests/conftest.py
- tests/manage/mcg/test_credentials_reset.py
Coverage for: https://url.corp.redhat.com/3746d39
RFE: https://bugzilla.redhat.com/show_bug.cgi?id=2027849
> Test coverage for changing MCG's credentials

- terraform/ai/vsphere/main.tf
- terraform/ai/vsphere/terraform.tfvars.example
- terraform/ai/vsphere/variables.tf
- update terroform scripts for deployment on vSphere via Assisted Installer to create API and Ingress DNS records
> vSphere Assisted Installer deployment (terraform scripts): create api and ingress records

- tests/manage/mcg/test_noobaa_prometheus.py
> Fixes missing argument issue

- ocs_ci/deployment/ocp.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/utility/assisted_installer.py
Creating low-level api module for interaction with Assisted Installer API
> Create assisted_installer low level api module

- ocs_ci/deployment/assisted_installer.py
- ocs_ci/ocs/exceptions.py
This PR depends on https://github.com/red-hat-storage/ocs-ci/pull/8994/
> Assisted Installer deployment module

- tests/e2e/workloads/ocp/monitoring/test_monitoring_on_negative_scenarios.py
> Fix threading_lock missing arg issue in test test_monitoring_shutdown_mgr_pod

- tests/conftest.py
release-4.12 backport of #7345
> [release-4.12 backport] Check for an existing pod before calling `awscli_pod_fixture`, and leverage the retry decorator in it

- tests/manage/mcg/test_azure_noobaa_sa.py
> Fixes ClientSecretCredential token issue

- conf/ocsci/disable_storage_cluster_version_check.yaml
- ocs_ci/ocs/resources/storage_cluster.py
This is useful when we have custom builds.
> User defined storage cluster version check

- conf/ocsci/cnv_deployment.yaml
- ocs_ci/deployment/cnv.py
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/ocp.py
- ocs_ci/templates/cnv-deployment/catalog-source.yaml
- ocs_ci/templates/cnv-deployment/hyperconverged.yaml
- ocs_ci/templates/cnv-deployment/namespace.yaml
- ocs_ci/templates/cnv-deployment/operatorgroup.yaml
- ocs_ci/templates/cnv-deployment/subscription.yaml
release-4.14 backport of #8873 to enable CNV deployment on 4.14 for CNV-MDR
> [Release-4.14 backport] CNV deployment

- tests/manage/mcg/test_virtual_hosted_buckets.py
https://bugzilla.redhat.com/show_bug.cgi?id=2183092
> Test s3 upload/download in virtual hosted bucket

- ocs_ci/ocs/resources/objectbucket.py
> catch botocore exception for fetching bucket versioning

- tests/manage/mcg/test_bucket_policy.py
> Fixes Invalid principal in policy issue

- tests/manage/mcg/test_bucket_policy.py
> Fixes bucket policy issue

- ocs_ci/ocs/resources/mcg_params.py
- ocs_ci/ocs/resources/objectbucket.py
- ocs_ci/ocs/resources/pod.py
- tests/conftest.py
- tests/manage/mcg/test_nsfs.py
release-4.12 backport of #8452
> [release-4.12 backport] Refactor nsfs_bucket_factory_fixture and fix various NSFS issues 

- ocs_ci/ocs/resources/mcg_params.py
- ocs_ci/ocs/resources/objectbucket.py
- ocs_ci/ocs/resources/pod.py
- tests/conftest.py
- tests/manage/mcg/test_nsfs.py
release-4.13 backport of #8452
> [release-4.13 backport] Refactor nsfs_bucket_factory_fixture and fix various NSFS issues

- tests/functional/pv/pv_services/test_write_to_cephfs_pvc_with_nonroot_user.py
> Fixes:8872

- ocs_ci/deployment/cloud.py
- ocs_ci/deployment/deployment.py
- ocs_ci/utility/ibmcloud.py
Issue: https://url.corp.redhat.com/1b7b3ca
> Use COS as noobaa backing store for IBM Cloud IPI

- tests/conftest.py
- tests/functional/pv/pvc_snapshot/test_snapshot_restore_with_different_access_mode.py
BZ- https://bugzilla.redhat.com/show_bug.cgi?id=2249601.
> PR for accesing restored pvc with ROX mode.

- ocs_ci/ocs/node.py
> raise exception with existing node count

- ocs_ci/framework/conf/ocp_version/ocp-4.16-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.16-upgrade.yaml
> Adding OCP 4.16 config files

- tests/conftest.py
> Revert skip bucket creation

- ocs_ci/deployment/helpers/mcg_helpers.py
- ocs_ci/ocs/resources/storage_cluster.py
- tests/manage/mcg/test_noobaa_secret.py
- tests/manage/mcg/test_s3_regenerate_creds.py
https://bugzilla.redhat.com/show_bug.cgi?id=2246328
https://bugzilla.redhat.com/show_bug.cgi?id=2219522
> Verify noobaa root secrets are not publicly exposed

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/defaults.py
- ocs_ci/ocs/elasticsearch.py
- ocs_ci/ocs/perfresult.py
- ocs_ci/ocs/perftests.py
- ocs_ci/templates/workloads/osd_scale/osd_scale_benchmark.yaml
- ocs_ci/templates/workloads/smallfile/SmallFile.yaml
- setup.py
- tests/e2e/performance/io_workload/test_fio_benchmark.py
- tests/e2e/performance/io_workload/test_small_file_workload.py
- tests/libtest/test_elasticsearch.py
Added suggestions from dependabot PRs here:
https://github.com/red-hat-storage/ocs-ci/security/dependabot
> Add security fixes

- ocs_ci/utility/ibmcloud.py
Removing workaround for https://bugzilla.redhat.com/show_bug.cgi?id=2255557
> Only apply region node to worker nodes for noobaa IBM Cloud COS 

- ocs_ci/helpers/helpers.py
Fix get_cephfs_subvolumegroup function for HCI provider-client setup.
Example of test cases that will be fixed with this change :
* tests/manage/pv_services/test_change_reclaim_policy_of_pv.py::TestChangeReclaimPolicyOfPv::test_change_reclaim_policy_of_pv[CephFileSystem-Delete]
* tests/manage/pv_services/test_pvc_concurrent_deletion_creation.py::TestMultiplePvcConcurrentDeletionCreation::test_multiple_pvc_concurrent_creation_deletion[CephFileSystem]
> Fix get_cephfs_subvolumegroup function for HCI client setup

- ocs_ci/ocs/resources/storage_cluster.py
> check exporter pod count based on ceph pods

- conf/deployment/vsphere/ai_1az_rhcos_vsan_3m_3w.yaml
- conf/deployment/vsphere/ai_1az_rhcos_vsan_3m_3w_hci.yaml
- ocs_ci/deployment/assisted_installer.py
- ocs_ci/deployment/factory.py
- ocs_ci/deployment/helpers/prechecks.py
- ocs_ci/deployment/vmware.py
- ocs_ci/framework/conf/default_config.yaml
- terraform/ai/vsphere/main.tf
- terraform/ai/vsphere/terraform.tfvars.example
- terraform/ai/vsphere/variables.tf
- terraform/ai/vsphere/vm/main.tf
- terraform/ai/vsphere/vm/variables.tf
This PR implements OCP deployment on vSphere via Assisted Installer.
It depends on [PR#8994](https://github.com/red-hat-storage/ocs-ci/pull/8994) and [PR#9042](https://github.com/red-hat-storage/ocs-ci/pull/9042) PRs.
> OCP Deployment on vSphere via Assisted Installer

- ocs_ci/ocs/bucket_utils.py
Needed for further investigation of #4003
> Log the md5sum list in case of an IndexError exception in verify_s3_object_integrity(

- tests/functional/object/mcg/test_s3_routes.py
> Patch the noobaa CR instead of the OCS StorageCluster at `test_disable_nb_lb`

- tests/e2e/scale/noobaa/test_warp.py
Increasing NooBaa Testing coverage:
* Added warp test run on pv, aws, azure and gcp
> Warp - Added test cases for pv, aws, azure and gcp

- ocs_ci/ocs/bucket_utils.py
- tests/functional/object/rgw/test_multipart_upload.py
> Adds functionality of downloading objects using s3cmd utility

- ocs_ci/deployment/ibmcloud.py
> Make sure ccoctl binary is downloaded if doesn't exist in destroy job

- ocs_ci/deployment/deployment.py
Related bz:
https://bugzilla.redhat.com/show_bug.cgi?id=2258638
> Fix deployment for IBM Cloud ROKS deployment with enabling Noobaa

- ocs_ci/ocs/acm/acm.py
> [RDR] Fix deployment failure with downstream submariner

- ocs_ci/ocs/resources/ocs.py
- ocs_ci/ocs/resources/storage_cluster.py
Fix the failing post-deployment checks for client cluster in provider/client setup
> Fix post-installation checks for client cluster

- tests/functional/object/mcg/conftest.py
- tests/functional/object/rgw/conftest.py
> Fixes directory path for skipping irrelevant tests

- ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
- ocs_ci/ocs/ui/page_objects/page_navigator.py
- ocs_ci/ocs/ui/validation_ui.py
- ocs_ci/ocs/ui/views.py
* shortened page_has_loaded check-interval
* adjusted locators
* added check for Overview tab
* etc
> 4.15 project dropdown and test_dashboard_validation

- ocs_ci/deployment/deployment.py
- ocs_ci/utility/ibmcloud.py
Backporting support for IBM Cloud COS backingstore for IBM IPI deployments.
PR: #9072 
PR: #9147
> Release 4.13 cherry pick pr 9072 9147

- ocs_ci/deployment/deployment.py
- ocs_ci/utility/ibmcloud.py
Backporting support for IBM Cloud COS backingstore for IBM IPI deployments.
PR: #9072 
PR: #9147
> Release 4.12 cherry pick pr 9072 9147

- ocs_ci/deployment/deployment.py
- ocs_ci/utility/ibmcloud.py
Backporting support for IBM Cloud COS backingstore for IBM IPI deployments.
PR: #9072 
PR: #9147
> Release 4.11 cherry pick pr 9072 9147

- ocs_ci/deployment/deployment.py
- ocs_ci/utility/ibmcloud.py
Backporting support for IBM Cloud COS backingstore for IBM IPI deployments.
PR: #9072 
PR: #9147
> Release 4.14 cherry pick pr 9072 9147

- ocs_ci/deployment/baremetal.py
There shouldn't be any functional change in this PR, it is just separation of common functionality for BM deployment to `BAREMETALBASE` class.
This will help with further development of IPI deployment or deployment via Assisted Installer.
> Bare metal deployment: create BAREMETALBASE class

- ocs_ci/cleanup/aws/cleanup.py
- ocs_ci/utility/aws.py
> sweeping S3 buckets in aws cleanup script

- conf/deployment/ibmcloud/ipi_3az_rhcos_3m_6w.yaml
> config file IBM cloud 3M-6W

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/constants.py
> Fix for backupstoragelocation name and drpolicy name(mdr)

- tests/functional/pv/conftest.py
- tests/functional/storageclass/conftest.py
> Fix directory path in conftest

- ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
- ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
- ocs_ci/templates/ocp-deployment/install-config-azure-ipi.yaml.j2
- ocs_ci/templates/ocp-deployment/install-config-gcp-ipi.yaml.j2
- ocs_ci/templates/ocp-deployment/install-config-rhv-ipi.yaml.j2
> change default networkType to OVNKubernetes

- conf/deployment/aws/ipi_1az_rhcos_3m_3w.yaml
- conf/deployment/aws/ipi_1az_rhcos_3m_3w_thales.yaml
- conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v1.yaml
- conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v1_external_with_namespace.yaml
- conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v2.yaml
- conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v2_external_with_namespace.yaml
- conf/deployment/aws/ipi_1az_rhcos_lowerreq_3m_3w.yaml
- conf/deployment/aws/ipi_1az_rhcos_lso_3m_3w.yaml
- conf/deployment/aws/ipi_1az_rhcos_lso_sno.yaml
> use us-east-2c availability zone for single AZ configs

- ocs_ci/ocs/ceph_debug.py
- ocs_ci/utility/utils.py
> add multicluster conditional while prepending kubeconfig

- ocs_ci/utility/utils.py
> Fix subcmd string check

- ocs_ci/ocs/constants.py
- ocs_ci/templates/rgw/cephobjectstoreuser.yaml
- tests/functional/object/rgw/test_cephobjectstore_user.py
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2196858
> Test role capabilities for ceph-objectstoreuser CRD

- conf/README.md
- conf/ocsci/performance_profiles/balanced.yaml
- conf/ocsci/performance_profiles/lean.yaml
- conf/ocsci/performance_profiles/performance.yaml
- ocs_ci/deployment/deployment.py
> Add performance profile for deployment

- tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
* updated setup teardown method for nfs testclass
* Addressed review comments updated to constants.AWS_PLATFORM
---------
> cherry picked pr 7884 to release 4.13

- ocs_ci/deployment/deployment.py
> [MDR] Change msa name

- ocs_ci/helpers/helpers.py
- tests/functional/z_cluster/test_rook_ceph_osd_flapping.py
https://bugzilla.redhat.com/show_bug.cgi?id=2223959
> Test Rook Ceph OSD Flapping GSS BZ-2223959 

- ocs_ci/helpers/dr_helpers.py
- ocs_ci/ocs/constants.py
> [RDR] Exclude PVCs created by VolSync when fetching image_uuids

- tests/manage/pv_services/test_pvc_delete_subvolumegroup.py
Update test_pvc_delete_subvolumegroup.py
- Enhance log messages
- Implement test skip on registry removal failure
Fixes: #9268 
> Enhancements for test_pvc_delete_subvolumegroup.py

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/resources/pod.py
- tests/functional/pv/space_reclaim/test_rook_reclaim_namespace.py
- tests/functional/z_cluster/test_rook_ceph_osd_flapping.py
- tests/functional/z_cluster/test_rook_reclaim_namespace.py
https://bugzilla.redhat.com/show_bug.cgi?id=2214838#c51
> GSS BZ-2214838 Automation, Test Rook Reclaim Namespace

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/constants.py
> MDR 4.14 deployment fixes

- conf/ocsci/enable_restricted_auth_permission_with_cluster_name.yaml
- conf/ocsci/enable_restricted_auth_permission_with_k8s_cluster_name.yaml
- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/framework/conf/default_config.yaml
> use k8s-cluster-name in external mode

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/ocs/acm/acm.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/odf_topology.py
- ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
- ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py
- ocs_ci/ocs/ui/page_objects/object_storage.py
- ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
- ocs_ci/ocs/ui/page_objects/page_navigator.py
- ocs_ci/ocs/ui/pvc_ui.py
- ocs_ci/ocs/ui/validation_ui.py
- ocs_ci/ocs/ui/views.py
- tests/conftest.py
- tests/cross_functional/ui/test_add_capacity_ui.py
- tests/cross_functional/ui/test_create_pool_block_pool.py
- tests/cross_functional/ui/test_creation_and_deletion_of_sc_and_rbdpool.py
- tests/cross_functional/ui/test_odf_topology.py
- tests/cross_functional/ui/test_validation_ui.py
- tests/functional/ui/test_capacity_breakdown_ui.py
- tests/functional/ui/test_error_improvements.py
- tests/functional/ui/test_non_admin_user.py
- tests/functional/ui/test_pvc_ui.py
- tests/functional/ui/test_quickstarts.py
skips added,
pvc_creation tests work, 
ui marks added, 
skipif_hci_provider_or_client mark added
> Tune the UI tests for Provider

- tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py
Passing correct accessmode to pvc for the test
> Passing correct accessmode to the tests pvc

- ocs_ci/utility/utils.py
- tests/test_failure_propagator.py
> display test case which breaks ceph health in reports/email

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/ibmcloud_bm.py
fix https://github.com/red-hat-storage/ocs-ci/issues/9374
> Get the HCI provider IBMCloud Baremetal machines by the node names instead of the node IPs

- conf/deployment/ibmcloud/ipi_3az_rhcos_3m_3w.yaml
- ocs_ci/deployment/ibmcloud.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/utility/utils.py
> use infraID in ccoctl

- tests/functional/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py
Add check for Ceph daemon crash warnings
- Suppress the crash warnings to allow test execution to continue
- Fail test case if Ceph daemon crash warnings are found, even if they are suppressed.
Bugs related to Ceph daemon crash #2214499, #2255648, #2265110
> [RDR] Fail tests on suppressed Ceph daemon crash warnings

- tests/functional/disaster-recovery/regional-dr/test_relocate.py
Added test to verify ApplicationSet-based application relocate with RBD workloads.
- OCS-5007 Perform Relocate Operation on Applicationset workload
> [RDR] Tests to verify ApplicationSet-based application relocate with RBD workloads

- ocs_ci/utility/utils.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/9345
> Fixing test_node_restart test on aws platform

- ocs_ci/framework/conf/ocp_version/ocp-4.15-ga-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.15-ga-minus1-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.15-ga-upgrade.yaml
> Adding OCP 4.15-ga files

- pytest.ini
> marker description correction in pytest.ini

- tests/functional/pod_and_daemons/test_mgr_pods.py
> update squad for pod_and_daemons test cases

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/rgwutils.py
> fix mon count for upgrade in arbiter deployments

- ocs_ci/deployment/disconnected.py
- ocs_ci/utility/utils.py
Fixes:
* https://github.com/red-hat-storage/ocs-ci/issues/9377
* https://github.com/red-hat-storage/ocs-ci/issues/9379
> Disconnected deployment fixes/enhancements

- tests/functional/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
fix https://github.com/red-hat-storage/ocs-ci/issues/9425
> Skip the test "test_add_capacity_node_restart" with external mode

- tests/functional/pv/pv_services/test_rbd_rwop_pvc.py
Test steps:-
1) Create RWOP pod with no priority set explicitly
2) Create second pod with no priority set explicitly that uses the same PVC --> This pod is expected to go Pending state.
> Test RWOP access mode with no priority pod

- tests/functional/monitoring/conftest.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/9348
> Update timeout for alert collecting during stop_mgr

- conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_5w.yaml
- conf/deployment/ibmcloud/ipi_3az_rhcos_3m_6w.yaml
- conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_6w.yaml
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_6w.yaml
> label nodes according to deployment configuration

- ocs_ci/deployment/deployment.py
- ocs_ci/helpers/dr_helpers.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/utils.py
- ocs_ci/templates/ocs-deployment/multicluster/backupschedule.yaml
- ocs_ci/utility/utils.py
Backports: #8005 #7978 #9241 #8561
> [release-4.13] MDR deployment/fencing fixes

- ocs_ci/deployment/vmware.py
> post destroy checks for vSphere IPI

- conf/README.md
- conf/ocsci/noobaa_external_pgsql.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/templates/ocs-deployment/external-pgsql-noobaa-secret.yaml
- ocs_ci/utility/pgsql.py
- setup.py
Ticket:
https://issues.redhat.com/browse/OCSQE-2046
> Add utility for postgresql + noobaa deployment with external pgsql

- ocs_ci/ocs/ocp.py
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/9372
> Add full api path for project

- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/helpers_ui.py
```
--cluster-path ~/ClusterPath -m deployment --ocp-version 4.15 --ocs-version 4.15 --ocsci-conf conf/ocsci/ui_deployment.yaml --ocsci-conf conf/ocsci/myconfig.yaml --ocsci-conf conf/ocsci/skip_ocp_deploy.yaml --ocsci-conf  conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml --cluster-name cluster tests/ --deploy
```
> Deploy ODF BM cluster via UI

- ocs_ci/deployment/helpers/vsphere_helpers.py
> use shared_credentials_files in vSphere RHEL deployment

- tests/functional/z_cluster/test_ceph_default_values_check.py
fix https://github.com/red-hat-storage/ocs-ci/issues/9470
> In the test "test_check_mds_cache_memory_limit" restart the mds pods if we get "ENOENT" error

- ocs_ci/framework/pytest_customization/marks.py
- tests/conftest.py
- tests/functional/z_cluster/nodes/test_worker_nodes_network_failures.py
fix https://github.com/red-hat-storage/ocs-ci/issues/8829
> Fix the test "test_all_worker_nodes_short_network_failure" for GCP platform

- conf/ocsci/mdr_workload.yaml
- ocs_ci/helpers/cnv_helpers.py
- ocs_ci/helpers/dr_helpers.py
- ocs_ci/ocs/cnv/virtctl.py
- ocs_ci/ocs/dr/dr_workload.py
- ocs_ci/ocs/node.py
- tests/conftest.py
- tests/functional/disaster-recovery/metro-dr/test_cnv_app_failover_relocate.py
> mdr+cnv test case io and data integrity checks on VMs

- ocs_ci/deployment/helpers/vsphere_helpers.py
- ocs_ci/deployment/vmware.py
- ocs_ci/ocs/constants.py
> remove dynamic logic from constants

- ocs_ci/framework/conf/ocp_version/ocp-4.16-config.yaml
> update RHCOS 4.16 template

- conf/deployment/vsphere/upi_1az_rhcos_external_noobaa_db_vsan_3m_3w.yaml
Ticket:
https://issues.redhat.com/browse/OCSQE-2063
> Production conf for external pgsql for noobaa

- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
> Add configure_performance option to UI deployment

- tests/functional/ui/test_error_improvements.py
> skip tests reaching outside network for disconnected cluster

- ocs_ci/framework/conf/default_config.yaml
- setup.py
> Defaulting ocs-ci to ODF 4.16

- tests/functional/workloads/app/quay/test_quay_operator.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/9563
> Fix in quay workload

- tests/functional/object/rgw/test_cephobjectstore_user.py
collect-only is failing with missing squad
> add squad for TestObjectStoreUserCaps

- ocs_ci/utility/workloadfixture.py
- tests/functional/monitoring/prometheus/metrics/test_ocs_utilization.py
- Makes changes allowing workload_idle fixture to be retried
- Fixes https://github.com/red-hat-storage/ocs-ci/issues/9022
> Mark test_mcg_cpu_usage as flaky

- ocs_ci/utility/cco.py
> download ccoctl from image for IBM cloud

- tests/functional/z_cluster/test_hugepages.py
> Run test_hugepages last to prevent failure of other testcases

- ocs_ci/framework/conf/ocs_version/ocs-4.16.yaml
> use stable tag for ODF 4.16

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/helpers/odf_deployment_helpers.py
- ocs_ci/ocs/defaults.py
> CSVs for ODF 4.16

- ocs_ci/ocs/node.py
release-4.13 backport of #9267
> [release-4.13 backport] Add the sleep param to the function "wait_for_nodes_status"

- ocs_ci/ocs/ui/deployment_ui.py
> Fix ui deployment 4.15.1

- setup.py
> Pin ping3 version

- ocs_ci/deployment/assisted_installer.py
There seems to be cases, when the first interface is not used and the actual provisioning interface is the second (or later) one.
So I'm changing the logic of `get_host_id_mac_mapping` method to prepare combination of all used mac addresses to host IDs and during updating of the name and role ignoring `KeyError`s of the mac addresses not used for the mapping.
> OCP AI deployment: enhance host id to mac mapping

- conf/deployment/aws/ipi_3az_rhcos_3m_3w_graviton.yaml
- ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
Ticket:
https://issues.redhat.com/browse/RHSTOR-2044
> Add Graviton type deployment

- tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py
> remove dynamic path from test case name

- tests/functional/z_cluster/test_multiple_mon_pods_stays_on_same_node.py
> Added skipif_no_lso so as to avoid running finalizer and resulting in test failure

- ocs_ci/ocs/ui/views.py
> UI deployment on ODF4.16

- conf/README.md
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_multi_storagecluster.yaml
- conf/ocsci/enable-multi-storagecluster.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/templates/ocs-deployment/multi-storagecluster-external-namespace.yaml
- ocs_ci/templates/ocs-deployment/storagesystem_odf_external.yaml
- ocs_ci/utility/deployment.py
- ocs_ci/utility/utils.py
- tests/conftest.py
Multi-storagecluster deployment according to https://issues.redhat.com/browse/RHSTOR-4422
> Multi-storagecluster deployment

- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/ocs/resources/csv.py
- ocs_ci/ocs/utils.py
> get external script from rook csv

- ocs_ci/ocs/ui/views.py
> Fix UI deployment on ODF4.14

- ocs_ci/ocs/resources/storage_cluster.py
> Allow re-try for osd tree schema validation

- ocs_ci/utility/vsphere.py
> Fix issue in teardown when folder vsphere doesn't exist

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/ocs.py
- ocs_ci/templates/CSI/addons/priorityclass.yaml
- tests/conftest.py
- tests/functional/pv/pv_services/test_rbd_rwop_pvc.py
Test RWOP with priority classes. 
This PR covers creating priority classes, and create pods using priority classes to set priority.
> Rwop high priority pod

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
Fixes: #9651
In addition on ODF4.16 two operators installed [ODF + ODF clinet]
> Fix UI deployment on ODF4.16

- ocs_ci/ocs/resources/storage_cluster.py
> convert osd size to int

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/ocs/bucket_utils.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/resources/backingstore.py
- ocs_ci/ocs/resources/cloud_manager.py
- ocs_ci/ocs/resources/cloud_uls.py
- ocs_ci/utility/utils.py
- tests/functional/object/mcg/test_bucket_deletion.py
- tests/functional/object/mcg/test_bucket_replication.py
- tests/functional/object/mcg/test_sts_bucket.py
Jira: https://url.corp.redhat.com/bcff339
> [4.15] RHSTOR-4676 Feature automation: AWS-STS backingstore creation and other related tier1, tier2 tests

- conf/README.md
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_multi_storagecluster.yaml
- conf/ocsci/enable-multi-storagecluster.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/templates/ocs-deployment/multi-storagecluster-external-namespace.yaml
- ocs_ci/templates/ocs-deployment/storagesystem_odf_external.yaml
- ocs_ci/utility/deployment.py
- ocs_ci/utility/utils.py
- tests/conftest.py
Cherry- pick to release 4.15 - multistoragecluster deployment (#9323)
> Cherry- pick to release 4.15 - multistoragecluster deployment (#9323)

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/views.py
> Fix UI deployment in 4.16 of performance profiles

- ocs_ci/deployment/deployment.py
- ocs_ci/utility/utils.py
> Skip checking cephblockpool status on passive cluster 

- tests/functional/object/mcg/test_bucket_replication.py
> Fixes bi-directional bucket replication tests issue

- tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py
Updating the test markers for the tests.
> Adding markers to the tests

- tests/functional/object/mcg/test_s3_routes.py
Fixes: #7656
This PR is just the appliance of `git revert` on #8979
I'm not sure why the back-and-forth changes were made in the first place, but this seems to be the procedure that works now and it matches the documentation: [Chapter 15. Disabling Multicloud Object Gateway external service after deploying OpenShift Data Foundation](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.14/html/troubleshooting_openshift_data_foundation/disabling-multicloud-object-gateway-external-service-after-deploying-openshift-datat-foundation_rhodf#:~:text=When%20you%20deploy%20OpenShift%20Data,variable%20in%20the%20storagecluster%20CRD.)
Required backports:
> Revert #8979 to patch `ocs-storagecluster` again instead of the noobaa CR at `test_disable_nb_lb` 

- tests/functional/workloads/cnv/test_vm_lifecycle_and_io.py
- tests/functional/workloads/cnv/test_vm_single_disk_hot_plugging_unplugging.py
Remove workloads marker from cnv tests as they are not supposed to run in workload test suit
> Remove workloads marker

- ocs_ci/ocs/ocs_upgrade.py
> upgrade: verify required csv's after upgrade

- tests/functional/workloads/cnv/test_vm_lifecycle_and_io.py
- tests/functional/workloads/cnv/test_vm_single_disk_hot_plugging_unplugging.py
Cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/9696
> Remove workloads marker 

- ocs_ci/deployment/assisted_installer.py
- consider only records with `kind: cluster`
> assisted_installer: fix lookup for existing cluster

- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
- ocs_ci/ocs/ui/page_objects/searchbar.py
- tests/functional/ui/test_alert_text.py
PR to fix the missed cleanup on management-console for all the tests using SearchBar pom class
* TestErrorMessageImprovements - all tests
* test_runbooks
> update the search cleanup with gradual text removal

- ocs_ci/ocs/ocs_upgrade.py
> timeout for checking noobaa pods after upgrade

- ocs_ci/ocs/ui/deployment_ui.py
- ocs_ci/ocs/ui/views.py
> fix LSO deployment

- ocs_ci/ocs/constants.py
- ocs_ci/utility/cco.py
- ocs_ci/utility/utils.py
- ocs_ci/utility/version.py
> fetch ccoctl dynamically

- ocs_ci/ocs/bucket_utils.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/9743
> Stop using boto3.client.get_object with an empty version id

- ocs_ci/ocs/ui/page_objects/block_and_file.py
- ocs_ci/ocs/ui/views.py
- ocs_ci/utility/utils.py
- tests/libtest/test_ui_pom.py
- tests/libtest/ui_tests.py
pls use the new functionality using this Page Object Model approach:
```
block_and_file = (
PageNavigator()
.nav_odf_default_page()
.nav_storage_systems_tab()
.nav_storagecluster_storagesystem_details()
.nav_block_and_file()
)
used, available = block_and_file.get_raw_capacity_card_values()
used_bytes = human_to_bytes(used)
logger.info(f"Used capacity: {used_bytes}")
available_bytes = human_to_bytes(available)
logger.info(f"Available capacity: {available_bytes}")
```
> add new functionality to BlockAndFile page

- ocs_ci/helpers/helpers.py
Select the name of the default volumesnapshotclass in provider mode setup. The name of volumesnapshotclass and storageclass will always be same.
> Select default volumesnapshotclass in provider-client setup

- ocs_ci/utility/deployment.py
- ocs_ci/utility/utils.py
> download openshift-install using oc

- ocs_ci/utility/utils.py
> support for RHEL8 builders

- ocs_ci/utility/utils.py
> remove ocp version for FIPS

- ocs_ci/ocs/ui/page_objects/block_pools.py
- ocs_ci/ocs/ui/page_objects/object_buckets_tab.py
- ocs_ci/ocs/ui/page_objects/resource_list.py
- ocs_ci/ocs/ui/views.py
Fixes test_obc_creation_and_deletion[openshift-storage.noobaa.io-noobaa-default-bucket-class-Actions-True] and test_obc_creation_and_deletion[openshift-storage.noobaa.io-noobaa-default-bucket-class-three_dots-True] failing in 4.16
> Adjust locators to patternfly5

- tests/functional/disaster-recovery/regional-dr/test_failover.py
Added tests to verify ApplicationSet-based application failover with RBD workloads.
- OCS-5006 Perform Failover Operation on Applicationset workload
- OCS-5008 Perform Failover Operation on Applicationset workload when Primary cluster is Down
> [RDR] Tests to verify ApplicationSet-based application failover with RBD workloads

- ocs_ci/framework/pytest_customization/marks.py
- tests/functional/object/mcg/test_bucket_replication.py
- tests/functional/object/mcg/test_verify_noobaa_status.py
> Added marker to skip test running on cluster deployed with ext pgsql

- tests/functional/pod_and_daemons/test_mgr_pods.py
> update test marker

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/aws.py
- tests/functional/z_cluster/nodes/test_disk_failures.py
> Fix fetching volumeHandle and manually attach Volumes on AWS post detach

- ocs_ci/deployment/aws.py
- ocs_ci/deployment/ocp.py
> AWS UPI FIPS

- ocs_ci/deployment/assisted_installer.py
This PR is backport of [PR#9711](https://github.com/red-hat-storage/ocs-ci/pull/9711) and [PR#9823](https://github.com/red-hat-storage/ocs-ci/pull/9823).
> Fix assisted installer destroy process - backport for release 4.15

- ocs_ci/deployment/acm.py
Handle  tar command execution failures
> Increase sleep time for oc extract

- ocs_ci/ocs/machine.py
> Fix AWS Infra node deployment

- conf/README.md
- ocs_ci/deployment/deployment.py
For testing BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=2276694
> Allow test upgrade waitTimeoutForHealthyOSDInMinutes

- tests/functional/odf-cli/test_pvc_stale_volume_cleanup_cli.py
removing from acceptance suite
jira ticket: https://issues.redhat.com/browse/RHSTOR-5931
> Removing from acceptance suite

- ocs_ci/ocs/ui/views.py
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/9874
> Adjust the locator constants as per cluster namespace

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/ephernal_storage.py
- ocs_ci/templates/app-pods/ephemeral_fs.yaml
- ocs_ci/templates/app-pods/ephemeral_rbd.yaml
- tests/functional/pod_and_daemons/test_ephemeral_pod.py
Create test case and infrastructure for ephemeral storage
> New test cast - Ephemeral storage

- ocs_ci/utility/kms.py
- tests/conftest.py
- tests/functional/pv/pv_encryption/test_azure_kms_pv_encryption.py
Verify Azure KV encryption operation with PV encryption.
Steps:
1. Set up Azure KV with the cluster.
2. Create multiple PVCs and attach them to pods.
3. Verify in Azure secrets that each PV has its corresponding secrets stored.
4. Start IO from the pods on the encrypted PVCs.
5. Verify that each PV's encrypted device is present on the node.
6. Wait until IO is complete.
7. Delete all the pods and PVCs that were created.
8. Verify that after deleting the PVCs, the respective secrets are also removed from the Azure Vault.
> Test Automation for validation of PV encryption with Azure KV

- ocs_ci/ocs/resources/storage_cluster.py
> use get for resourceProfile timeout

- setup.py
> progress bar plugin

- ocs_ci/utility/bootstrap.py
> use appropriate installer for bootstrap logs

- conf/deployment/azure/ipi_1az_rhcos_3m_3w_encryption_azure_kv.yaml
Added Deployment ID to the azure KV deployment configuration
> Added Deployment ID to the azure KV deployment configuration

- ocs_ci/utility/bootstrap.py
> fix exception error

- pytest.ini
> add --show-progress as default option to ocs-ci

- ocs_ci/cleanup/aws/defaults.py
> dr prefix for RDR/MDR buckets for aws-cleanup jobs

- tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py
Fixes #9171 which is an intermittent issue.
> Increase wait time for clone in the test test_pvc_to_pvc_clone

- ocs_ci/framework/conf/ocp_version/ocp-4.17-config.yaml
> OCP 4.17 RHCOS template

- ocs_ci/utility/deployment.py
- ocs_ci/utility/utils.py
> [release-4.15]: download openshift-install using oc

- conf/ocsci/mdr_workload.yaml
- ocs_ci/ocs/dr/dr_workload.py
- tests/conftest.py
- tests/functional/disaster-recovery/metro-dr/test_cnv_app_failover_relocate.py
Adds Appset pull model for cnv apps, fixes issue #9934  and other improvements.
> mdr+cnv appset pull app and other fixes

- ocs_ci/framework/conf/ocs_version/ocs-4.17.yaml
> use stable tag for ODF 4.17

- ocs_ci/utility/utils.py
- ocs_ci/utility/version.py
> download OCP nightly through GA'ed version incase of failures

- ocs_ci/utility/version.py
> add VERSION_4_17 in version module

- ocs_ci/utility/utils.py
> [release-4.14]: openshift installer download using oc

- ocs_ci/utility/utils.py
> [release-4.13]: openshift installer download using oc

- ocs_ci/utility/utils.py
> [release-4.12]: openshift installer download using oc

- ocs_ci/utility/utils.py
> move get_openshift_mirror_url to try block

- conf/deployment/aws/ipi_3az_rhcos_sts_3m_3w_thales.yaml
Ticket:
https://issues.redhat.com/browse/OCSQE-2469
> Add production configuration for STS deployment with KMS Thales

- .github/workflows/pr_checks.yml
- docs/getting_started.md
- docs/unit_tests.md
- setup.py
- tox.ini
> [release-4.12] Python 3.10 support 

- tests/functional/storageclass/test_cross_sc_clone_snap_restore.py
This PR contains adding test cases for compressed pool ( for RBD and CephFS interfaces).
> Cross Class Clone and Restore - adding support for compressed pool

- ocs_ci/ocs/constants.py
- tests/functional/z_cluster/test_ceph_default_values_check.py
> test_validate_ceph_config_values_in_rook_config_override - Test ready for 4.16

- tests/manage/add_metadata_feature/test_metadata.py
Removed skip test marker form the test
> [cherry-pick-9885][release-4.14]Removed skip test marker form the test

- tests/functional/pv/add_metadata_feature/test_metadata.py
Removed skip test marker form the test
> [cherry-pick-9885][release-4.15]Removed skip test marker form the test

- ocs_ci/ocs/node.py
- tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_clone.py
- tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
- tests/manage/pv_services/pv_encryption/test_kmip_rbd_pv_encryption.py
- tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption.py
- tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
- tests/ui/test_pv_encryption_ui.py
Release 4.13 cherry pick pr 9177
> [cherry-pick-9177][Release 4.13] Replacing crypt device check from pod to node. 

- ocs_ci/ocs/node.py
- tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_clone.py
- tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
- tests/manage/pv_services/pv_encryption/test_kmip_rbd_pv_encryption.py
- tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption.py
- tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
- tests/ui/test_pv_encryption_ui.py
Cherry-Pick PR: 9177 to release-4.14
> [Cherry-pick-9177][release-4.14] Replacing crypt device check from pod to node.

- ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
- ocs_ci/ocs/ui/views.py
- tests/cross_functional/ui/test_odf_topology.py
> test_store_creation_and_deletion fix

- ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
- tests/cross_functional/ui/test_odf_topology.py
address issue https://github.com/red-hat-storage/ocs-ci/issues/9519
> fix tearDown_and_improve_read_alerts test

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/factory.py
- ocs_ci/deployment/hosted_cluster.py
- ocs_ci/deployment/metallb.py
address several failures to make Provider mode run with hosted clusters deployment
issues addressed: 
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/39396/console
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/39553/consoleFull
also:
metallb installation failure
Fixes #10083
> add hci_baremetal deployment type to map

- ocs_ci/ocs/ui/odf_topology.py
- ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
- tests/cross_functional/ui/test_odf_topology.py
- tests/functional/ui/test_error_improvements.py
first portion of the test fixes after analisys of 4.16 failures
> first portion of fixes. Topology tests and error msg improvements

- ocs_ci/deployment/hosted_cluster.py
- tests/libtest/test_metallb.py
- tests/libtest/test_provider_create_hosted_cluster.py
lib tests to run installation of the dependencies on existing cluster
> Dependency installation separate

- ocs_ci/ocs/ocs_upgrade.py
> skip fetching upgrade version if its external mode

- .pre-commit-config.yaml
> change python version from 3.8 to 3.9 in precommit yaml file

- tests/lvmo/test_lvm_clone_base.py
- tests/lvmo/test_lvm_multi_clone.py
- tests/lvmo/test_lvm_multi_snapshot.py
- tests/lvmo/test_lvm_snapshot_base.py
> removed unused dynamic variable at class level

- Docker_files/ocsci_container/Containerfile.ci
> use silent and location for curl downloads

- ocs_ci/deployment/deployment.py
> Fix OADP operator install

- ocs_ci/ocs/ui/add_replace_device_ui.py
- ocs_ci/ocs/ui/helpers_ui.py
tests/functional/z_cluster/cluster_expansion/test_add_capacity.py::TestAddCapacity::test_add_capacity_ui
> add capacity via UI odf4.17

- ocs_ci/ocs/constants.py
added ENTER_KEY, needed for odf cli testing
> Add carriage_return to const file

- ocs_ci/ocs/utils.py
- ocs_ci/utility/utils.py
> fixing the get_latest_release_version

- tests/functional/pv/pv_services/test_rwop_pvc.py
The only change in this PR is to add Post upgrade marker to the class.
> Adding post upgrade marker to tests/functional/pv/pv_services/test_rwop_pvc.py test 

- tests/functional/storageclass/test_cross_sc_clone_snap_restore.py
The only change in this PR is to add Post upgrade marker to the class.
> Adding post upgrade marker to tests/functional/storageclass/test_cross_sc_clone_snap_restore.py test

- ocs_ci/framework/conf/default_config.yaml
- setup.py
> Defaulting ocs-ci to ODF 4.17

- ocs_ci/helpers/e2e_helpers.py
- tests/cross_functional/conftest.py
Also fixes: https://github.com/red-hat-storage/ocs-ci/issues/9480
> Fix the issue in object expiration failure in system test runs

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/ocs/machine.py
- tests/functional/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
> Skip test_automated_recovery_from_stopped_node_and_start failed on Compact mode deployments

- ocs_ci/utility/utils.py
- ocs_ci/utility/version.py
> [release-4.14]: download OCP nightly through GA'ed version incase of failures

- ocs_ci/utility/utils.py
- ocs_ci/utility/version.py
> [release-4.13]: download OCP nightly through GA'ed version incase of failures

- ocs_ci/utility/utils.py
- ocs_ci/utility/version.py
> [release-4.12]: download OCP nightly through GA'ed version incase of failures

- docs/writing_tests.md
- ocs_ci/framework/pytest_customization/marks.py
- setup.py
Ticket:
https://issues.redhat.com/browse/OCSQE-2441
> Pytest jira plugin

- ocs_ci/utility/kms.py
> Fixing validation for keys fro ciphertrust Thales KMS

- ocs_ci/ocs/resources/backingstore.py
> Fixes TypeError while creating default backing_store

- ocs_ci/ocs/ui/base_ui.py
- tests/conftest.py
- tests/cross_functional/ui/test_validation_ui.py
- tests/functional/object/mcg/ui/test_mcg_ui.py
- tests/functional/object/mcg/ui/test_namespace_store.py
- tests/functional/ui/test_pvc_ui.py
Fixes #10017 and other similar issues when login_ui utility happens before switch to provider context/configuration
> adding setup_ui_class_factory fixture

- ocs_ci/ocs/resources/fips.py
- ocs_ci/ocs/resources/pod.py
> ignore rook-ceph-detect-version pods if FIPS checking

- conf/ocsci/dr_workload.yaml
- tests/functional/disaster-recovery/regional-dr/test_cnv_app_failover_and_relocate.py
RDR CNV workload updates for Appset pull model, unique namespace and other improvements.
> RDR CNV workload updates for Appset pull model and unique namespace

- ocs_ci/deployment/deployment.py
> Pass ACM Backup Namespace to get OADP version

- tests/functional/z_cluster/nodes/test_disk_failures.py
> Wait and check for crashes before archiving them to avoid failures in later steps

- ocs_ci/deployment/helpers/hypershift_base.py
works both for 4.16 and 4.17 binaries
> hcp version request correction

- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/osd_operations.py
- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/vsphere.py
> volume path for LSO disk operations

- conf/deployment/fusion_hci_pc/client_bm_upi_1az_rhcos_nvme_2w.yaml
- conf/deployment/fusion_hci_pc/client_bm_upi_1az_rhcos_nvme_3w.yaml
- conf/deployment/fusion_hci_pc/provider_bm_upi_1az_rhcos_nvme_3m_3w.yaml
- ocs_ci/ocs/utils.py
Add ODF must-gather parameter "--provider' if the cluster is a client cluster in provider mode configuration.
Remove the obsolete must-gather tag from the config files.
> Add must-gather parameter for client cluster

- ocs_ci/utility/utils.py
> GLIBC version for Ubuntu

- tests/functional/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
> Skip test_crashcollector_pod_existence_on_ceph_pods_running_nodes on compact mode deployments

- tests/functional/object/mcg/test_object_versioning.py
- tests/functional/object/rgw/test_obc_quota.py
1. 2240714: https://bugzilla.redhat.com/show_bug.cgi?id=2240714
2. 2188032: https://bugzilla.redhat.com/show_bug.cgi?id=2188032
> GSS bug automation:  #2240714 and #2188032

- ocs_ci/ocs/ui/base_ui.py
issue can be seen https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-rdr-setup/1089/consoleFull
black squad discussion https://ibm-systems-storage.slack.com/archives/C06EVA2KCGM/p1724177290133069
> fix login issue

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/storage_cluster.py
Check the presence of the pod ocscsi-controller-manager during install verification.
> Check the presence of ceph-csi pod

- ocs_ci/helpers/cnv_helpers.py
- ocs_ci/ocs/cnv/virtual_machine.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/cnv-vm-workload/vm-standalone-pvc/dv.yaml
- ocs_ci/templates/cnv-vm-workload/vm-standalone-pvc/pvc.yaml
- ocs_ci/templates/cnv-vm-workload/vm-standalone-pvc/vm.yaml
- tests/conftest.py
- tests/functional/workloads/cnv/test_vm_lifecycle_and_io.py
- tests/functional/workloads/cnv/test_vm_single_disk_hot_plugging_unplugging.py
> Support cnv workloads dv/dvt

- tests/functional/pv/pvc_resize/test_pvc_expansion_when_full.py
Feature RHSTOR-5183. 
Cover scenario with alerts checks upon violating thresholds.
> PVC alert threshold checks added

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/workloads/helper_scripts/chunk.py
- tests/functional/pv/pv_services/test_cephfs_pvc_with_chunk_size.py
BZ: [2171225](https://bugzilla.redhat.com/show_bug.cgi?id=2171225)
Created a new test case to run large chunk file IO on fedora dc pod and verify errors in MDS pod logs.
Signed-off-by: nagendra202 <nagreddy@redhat.com>
~
> [Close loop BZ: 2171225] Test case to run large chunk file IO 

- tests/functional/object/mcg/test_custom_credentials_using_mcg_cli.py
Adds test coverage for feature "MCG - Set credentials manually to an account"
> Adds test coverage for "Set credentials manually to an account" feature

- tests/functional/workloads/app/amq/test_rgw_kafka_notifications.py
> fix test_rgw_kafka_notifications

- ocs_ci/helpers/helpers.py
Workaround the issue #7837 by adding a second attempt to get the mountpoints from a node using a different command.
Reduced timeout to avoid more delay in waiting.
The test cases that fails are present in release-4.15 and older release branches only.
> Add second attempt to fetch the mountpoints from the node

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/helpers/lso_helpers.py
- ocs_ci/deployment/provider_client/storage_client_deployment.py
Created a method for pre cleanup required for lso install and called that in before installation of LSO with odf or without odf
> Created a method for pre cleanup required for lso install

- ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-config.yaml
> remove extra doublequote in config file

- ocs_ci/ocs/resources/cloud_manager.py
- tests/cross_functional/scale/noobaa/test_warp.py
Removes CephBlockPool interface from parameterised argument
> Removes CephBlockPool interface from parameterised argument

- ocs_ci/ocs/ceph_debug.py
- tests/conftest.py
- tests/cross_functional/kcs/test_maintenance_pod.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/9539
> Fix issue with maintenance pod

- ocs_ci/cleanup/aws/cleanup.py
The PR opened because some aws s3 cleanup jobs failed 
https://url.corp.redhat.com/0433241
> S3 cleanup with new method

- ocs_ci/ocs/bucket_utils.py
- ocs_ci/utility/utils.py
following the conversation https://ibm-systems-storage.slack.com/archives/C06EEKSUPPZ/p1723712754818339 added verification mode rule
PR to fix issue with console log
> [2024-08-15T21:45:18.318Z]         except URLLib3SSLError as e:
> [2024-08-15T21:45:18.318Z] >           raise SSLError(endpoint_url=request.url, error=e)
> [2024-08-15T21:45:18.318Z] [1m[31mE           botocore.exceptions.SSLError: SSL validation failed for https://s3-odf-storage.apps.rosa.rosahcp148.3oyi.s3.devshift.org:443/oc-bucket-c55c1856f23c4630a3d74db072fa30 [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)[0m
> fix object storage issues

- ocs_ci/ocs/cluster.py
- tests/functional/z_cluster/test_ceph_default_values_check.py
fix https://github.com/red-hat-storage/ocs-ci/issues/10246
> Parsing and validation for ceph df details

- ocs_ci/framework/conf/ocs_version/ocs-4.18.yaml
- ocs_ci/framework/main.py
> Adding ODF 4.18 config files

- ocs_ci/framework/__init__.py
- ocs_ci/ocs/resources/storageconsumer.py
- tests/functional/monitoring/conftest.py
Simplify context usage for Provider client setups.
> Provider client context manager

- tests/conftest.py
> Set a priviliged service account for the NSFS interface deployment for NSFS tests

- tests/functional/monitoring/conftest.py
- tests/functional/monitoring/prometheus/alerts/test_rgw.py
> Fixes issue:8631: Update the steps of test case to get rgw_alerts

- ocs_ci/ocs/ui/pvc_ui.py
- ocs_ci/ocs/ui/views.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/10248
> Update PVC access mode choice

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/constants.py
https://github.com/red-hat-storage/odf-operator/blob/main/hack/install-odf.sh#L34-L44
Related to this BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=2309191
> Add deployment checks

- setup.py
This is to support python 3.11.
> [release 4.16] Update numpy version to 1.23.2

- ocs_ci/ocs/dr/dr_workload.py
> Fix RDR tests fails with "KeyError: 'matchExpressions'"

- ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
- tests/functional/object/mcg/ui/test_mcg_ui.py
> logs improved, timeout increased

- tests/manage/monitoring/conftest.py
Fixing a formatting issue blocking #10489 from being merged.
> Run black to fix formatting in conftest.py

- ocs_ci/deployment/deployment.py
- ocs_ci/framework/conf/default_config.yaml
Reverts red-hat-storage/ocs-ci#10323
> Revert "Remove Bluestore-rdr check"

- ocs_ci/ocs/ui/deployment_ui.py
> ODF4.17 UI deployment, add 'data protection' page

- ocs_ci/utility/deployment.py
> increase timeout for MCP incase of more nodes

- ocs_ci/helpers/odf_cli.py
- tests/functional/odf-cli/test_get_commands.py
- tests/functional/odf-cli/test_operator_restart.py
- tests/functional/z_cluster/test_rook_ceph_operator_log_type.py
Infra and tests for ODF CLI
also fix for [issue](https://github.com/red-hat-storage/ocs-ci/issues/10444)
> New Test for ODF CLI 

- ocs_ci/framework/conf/ocp_version/ocp-4.17-ga-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.17-ga-minus1-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.17-ga-upgrade.yaml
> Adding OCP 4.17-ga files

- ocs_ci/utility/utils.py
This will prevent deadlocks when exception during subprocess.run hit.
Related issue:
https://github.com/red-hat-storage/ocs-ci/issues/10586
Hopefully it will fix this issue above.
> Release lock when exception hit in exec_cmd

- ocs_ci/framework/main.py
Related to:
https://github.com/red-hat-storage/ocs-ci/issues/10586
> Add traceback dump

- ocs_ci/deployment/ingress_node_firewall.py
- ocs_ci/deployment/qe_app_registry.py
- ocs_ci/ocs/constants.py
- create QE App Registry catalog source for Ingress Node Firewall
- create also ICSP for Brew registry
> Ingress Node Firewall deployment on un-released OCP version (from QE App Registry catalog)

- ocs_ci/deployment/deployment.py
- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/constants.py
[OCSQE-2057](https://url.corp.redhat.com/bd014ea)
> Installing volsync addon on managed clusters with unreleased ACM version

- ocs_ci/helpers/helpers.py
Fixed odf_cli  failing tests cases
> Fixed odf_cli tests cases

- ocs_ci/ocs/resources/storage_cluster.py
> Add retry for storageSystem check

- ocs_ci/framework/pytest_customization/marks.py
- pytest.ini
- tests/functional/disaster-recovery/regional-dr/test_cnv_app_failover_and_relocate.py
- tests/functional/disaster-recovery/regional-dr/test_failover.py
- tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate.py
- tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps.py
- tests/functional/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py
- tests/functional/disaster-recovery/regional-dr/test_negative_failover_relocate_ui.py
- tests/functional/disaster-recovery/regional-dr/test_node_operations_during_failover_relocate.py
- tests/functional/disaster-recovery/regional-dr/test_rdr_monitoring_dashboard_ui.py
- tests/functional/disaster-recovery/regional-dr/test_relocate.py
- tests/functional/disaster-recovery/regional-dr/test_sequential_failover.py
- tests/functional/disaster-recovery/regional-dr/test_sequential_relocate.py
Added a new mark of `rdr` to mark regression testcases for RDR
> Added new marker "rdr" for running RDR related tests

- tests/conftest.py
- tests/functional/pv/pv_encryption/test_encrypted_pvc_no_expansion_option.py
[Cherry-pick-10493] [Release-4.16]Fix resource wrong status exception.
> [Cherry-pick-10493] [Release-4.16]Fixed resource wrong status exception.

- conf/ocsci/dr_workload.yaml
> Fix Path for Cephfs Workloads RDR

- tests/functional/z_cluster/test_ceph_default_values_check.py
> add post_ocs_upgrade marker for pg num checking

- ocs_ci/ocs/resources/mcg.py
Having retry twice for function along with property is showing some wierd behaviour
> remove double retry decorator

- tests/conftest.py
> include IndexError while collect upgrade marks

- tests/functional/pv/space_reclaim/test_rbd_space_reclaim.py
Update the test case of RBD space reclaim and remove skip marker for provider mode.
> Remove provider mode skip marker from space reclaim tests

- ocs_ci/helpers/keyrotation_helper.py
- tests/functional/encryption/test_encryption_keyrotation.py
Fixed keyrotation test failures
> Fixed keyrotation test failures

- ocs_ci/deployment/helpers/lso_helpers.py
- ocs_ci/templates/ocs-deployment/local-volume-set.yaml
> remove Rotational duplicate in LocalVolumeSet

- ocs_ci/framework/conf/ocp_version/ocp-4.18-config.yaml
> RHCOS 4.18 template

- ocs_ci/framework/pytest_customization/marks.py
- pytest.ini
- tests/cross_functional/system_test/multicluster/test_post_installation_state.py
- tests/functional/monitoring/prometheus/alerts/test_alerting_works.py
- tests/functional/monitoring/prometheus/alerts/test_ceph.py
- tests/functional/monitoring/prometheus/alerts/test_deployment_status.py
- tests/functional/monitoring/prometheus/metrics/test_monitoring_defaults.py
- tests/functional/monitoring/prometheus/metrics/test_ocs_utilization.py
- tests/functional/monitoring/test_monitoring_tool.py
- tests/functional/object/mcg/test_bucket_policy.py
- tests/functional/object/mcg/ui/test_mcg_ui.py
- tests/functional/pv/pv_services/test_change_reclaim_policy_of_pv.py
- tests/functional/pv/pv_services/test_create_large_sized_pvc_while_io_in_progress.py
- tests/functional/pv/pv_services/test_delete_create_pvc_same_name.py
- tests/functional/pv/pv_services/test_no_space_left.py
- tests/functional/pv/pv_services/test_pvc_concurrent_deletion_creation.py
- tests/functional/pv/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
- tests/functional/pv/pv_services/test_pvc_deletion_during_io.py
- tests/functional/pv/pv_services/test_pvc_evict_ceph_clients.py
- tests/functional/pv/pv_services/test_pvc_rwx_writeable_after_pod_deletions.py
- tests/functional/pv/pv_services/test_raw_block_pv.py
- tests/functional/pv/pv_services/test_run_io_multiple_pods.py
- tests/functional/pv/pv_services/test_verify_rwo_using_multiple_pods.py
- tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py
- tests/functional/pv/pvc_resize/test_pvc_expansion.py
- tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py
- tests/functional/pv/pvc_snapshot/test_rbd_block_pvc_snapshot.py
- tests/functional/pv/pvc_snapshot/test_snapshot_restore_with_different_access_mode.py
Added provider_mode_acceptance and yellow_squad tags to mark regression testcases for provider-client clusters
> Added provider_mode tags to mark regression testcases for provider-client clusters

- tests/cross_functional/kcs/test_noobaa_db_backup_and_recovery.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/10046
> Fix test_noobaa_db_backup_recovery_locally

- setup.py
paramiko will install cryptography as dependency package
> remove cryptography package

- ocs_ci/utility/utils.py
- tests/functional/workloads/ocp/registry/test_pod_from_registry.py
> Fix update_container_with_mirrored_image for local images

- ocs_ci/helpers/odf_cli.py
- tests/functional/conftest.py
- tests/functional/odf-cli/test_get_commands.py
> Added setup fixture to test "get_cli_cmd"

- ocs_ci/deployment/baremetal.py
- ocs_ci/utility/connection.py
- handle failed commands
- add secrets masking to remote exec_cmd method
> fix BM AI deployment on octo argo

- tests/cross_functional/kcs/test_monitor_recovery.py
- tests/cross_functional/system_test/multicluster/test_ms_markers.py
- tests/functional/disaster-recovery/sc_arbiter/test_add_capacity.py
- tests/functional/z_cluster/cluster_expansion/test_add_capacity.py
- tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
- tests/libtest/test_hci_pc_markers.py
> fix ordering of testcases

- ocs_ci/framework/conf/ocs_version/ocs-4.18.yaml
> use stable tag for ODF 4.18

- ocs_ci/templates/ocs-deployment/storageclass.gcp.yaml
See more details in the BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2318494.
> Add the param 'allowVolumeExpansion: true' to allow resize OSD with GCP

- ocs_ci/deployment/deployment.py
> increase mon timeout for IBM cloud managed

- ocs_ci/deployment/acm.py
- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/acm/acm.py
- ocs_ci/ocs/resources/storage_cluster.py
> Disable globalnet when disable globalnet is checked in jenkins

- ocs_ci/ocs/resources/storage_cluster.py
> Fix multicluster_mode KeyError

- ocs_ci/deployment/helpers/lso_helpers.py
- ocs_ci/deployment/vmware.py
- ocs_ci/utility/vsphere.py
> mark disks as ssd while creating

- conf/ocsci/external_rhcs_custom_user.yaml
- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/framework/conf/default_config.yaml
> add run-as-user param in external mode deployment

- docs/writing_tests.md
- ocs_ci/framework/pytest_customization/marks.py
- setup.py
Ticket:
https://issues.redhat.com/browse/OCSQE-2441
> Add pytest-jira plugin

- ocs_ci/ocs/utils.py
- scripts/bash/mg_external.sh
cherry-pick https://github.com/red-hat-storage/ocs-ci/pull/10594
> [release-4.16] Collect ceph data for External mode

- conf/examples/acm_hub_unreleased_image.yaml
- conf/examples/submariner_unreleased_image.yaml
Update ACM and Submariner unreleased image to latest version which contains the fix for [ACM-14575](https://issues.redhat.com/browse/ACM-14575)
> Update ACM and Submariner unreleased image to latest version

- ocs_ci/deployment/deployment.py
> Add additional condition check to ensure observability is successfully enabled

- ocs_ci/framework/conf/default_config.yaml
- setup.py
> Defaulting ocs-ci to ODF 4.18

- ocs_ci/ocs/resources/pod.py
> Skip ceph-file-controller-detect-version pod check in test_add_capacity[10]

- conf/README.md
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_ipv6.yaml
- conf/ocsci/vsphere_upi_enable_ipv6_single_stack.yaml
- ocs_ci/deployment/vmware.py
- ocs_ci/utility/framework/initialization.py
- ocs_ci/utility/ipam.py
- ocs_ci/utility/load_balancer.py
- ocs_ci/utility/proxy.py
- tests/conftest.py
ipv6 single stack deployment of ODF.
Most of the changes are in openshift installer git for terraform and ipam.
[https://gitlab.cee.redhat.com/srozen/installer_ipv6](https://gitlab.cee.redhat.com/srozen/installer_ipv6)
[https://gitlab.cee.redhat.com/srozen/ipv6_script](https://gitlab.cee.redhat.com/srozen/ipv6_script
)
> ipv6 single stack deployment

- ocs_ci/ocs/node.py
- ocs_ci/ocs/osd_operations.py
- ocs_ci/ocs/platform_nodes.py
> create ssd disks for LSO for disk replacement

- ocs_ci/ocs/platform_nodes.py
- ocs_ci/utility/ibmcloud.py
- tests/functional/object/mcg/ui/test_mcg_ui.py
- tests/functional/object/mcg/ui/test_namespace_store.py
- tests/functional/storageclass/test_delete_rbd_pool_attached_to_sc.py
- tests/functional/z_cluster/nodes/test_check_pods_status_after_node_failure.py
* IBM Cloud node stop and start added
> IBM Cloud node stop and start added (#10707)

- ocs_ci/deployment/rosa.py
- ocs_ci/utility/aws.py
fix the problem: 
```
2024-11-07 10:40:18  ERR: Failed to create cluster: There must be a minimum of '1' tag quota available to add tags to the subnet '[subnet-08d4ad834dec518c0 subnet-06de2b94c676e2e1b]'
```
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/43788/console
> Fix tags quota violation

- ocs_ci/ocs/ui/page_objects/resource_page.py
minor improvement fix for "test_obc_creation_and_deletion" - avoid stale element exception
> add stale el exception handling

- conf/README.md
- conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_ipv6.yaml
- conf/ocsci/vsphere_upi_enable_ipv6_single_stack.yaml
- ocs_ci/deployment/vmware.py
- ocs_ci/framework/main.py
- ocs_ci/utility/ipam.py
- ocs_ci/utility/load_balancer.py
- ocs_ci/utility/proxy.py
- tests/conftest.py
Cherry pick to 4.16
ipv6 single stack deployment of ODF.
Most of the changes are in openshift installer git for terraform and ipam.
https://gitlab.cee.redhat.com/srozen/installer_ipv6
https://gitlab.cee.redhat.com/srozen/ipv6_script
> [release-4.16] ipv6 single stack deployment (#10609)

- ocs_ci/ocs/cluster.py
> Exception message for Noobaa Health check

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/pod.py
> exclude NOOBAA_PSQL_12_IMAGE for image verification after upgrade

- ocs_ci/ocs/node.py
fix https://github.com/red-hat-storage/ocs-ci/issues/10534
> In the function "get_node_rack_or_zone" reload the node object data

- ocs_ci/utility/utils.py
> use GA'ed installer when nightly is unavailable

- conf/README.md
- conf/ocsci/encryption_in_transit.yaml
- add new config with in_transit_encryption parameter
- move `in_transit_encryption` in doc to proper section (from `DEPLOYMENT` to `ENV_DATA`)
> add encryption_in_transit.yaml config and fix doc

- ocs_ci/ocs/ui/deployment_ui.py
> ODF4.18, UI deployment, Skip on  step

- ocs_ci/deployment/deployment.py
> Remove Bluestore-rdr check

- tests/functional/workloads/app/amq/test_amq_streamer_creation.py
Deprecated tests/functional/workloads/app/amq/test_amq_streamer_creation.py
> Deprecate test_amq_streamer_creation.py

- tests/conftest.py
> Set the namespace of the NSFS interface deployment dynamically

- tests/functional/object/mcg/test_custom_credentials_using_mcg_cli.py
> Fixes dynamic namespace selection issue for test_account_update_with_custom_creds_using_cli script

- ocs_ci/helpers/odf_cli.py
- tests/functional/odf-cli/test_pvc_stale_volume_cleanup_cli.py
Pull request to address issue [#10445](https://github.com/red-hat-storage/ocs-ci/issues/10445)
> config namespace reference is set to every odf cli call

- scripts/bash/mg_external.sh
> remove gather_common_ceph_resources in external mg script

- conf/README.md
- conf/ocsci/external_rhcs_with_rbd_namespace.yaml
- ocs_ci/deployment/helpers/external_cluster_helpers.py
- ocs_ci/ocs/exceptions.py
> RBD namespace in external cluster

- ocs_ci/ocs/awscli_pod.py
> Move awscli pod CA setup related commands to container startup

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/ocs/machinepool.py
- ocs_ci/ocs/node.py
- ocs_ci/ocs/platform_nodes.py
- tests/functional/z_cluster/cluster_expansion/conftest.py
- tests/functional/z_cluster/cluster_expansion/test_nodes_rosa_hcp.py
Automate scenario: [[ROSA HCP] Create ocs node in a new machinepool	](https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-6270)
Introduce rosahcp_required test decorator
> add-new-test--test_add_ocs_node_non_default_machinepool

- tests/functional/workloads/ocp/monitoring/test_monitoring_on_negative_scenarios.py
> Added code to select active mgr pod always

- ocs_ci/ocs/must_gather/const_must_gather.py
fix [issue](https://github.com/red-hat-storage/ocs-ci/issues/11029)
> Added 4.18 to must gather const

- conf/README.md
- conf/deployment/aws/rosa_hcp_1az_3w_m5.12x.yaml
- conf/deployment/aws/rosa_hcp_1az_6w_m5.2x.yaml
- ocs_ci/deployment/rosa.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/machinepool.py
- ocs_ci/utility/rosa.py
will help address issues related to node autoscaling
Fixes #11021
> Rosa hcp node labeling

- ocs_ci/utility/deployment_openshift_logging.py
- tests/conftest.py
install_logging fixture creates resources that exist on ROSA HCP cluster.
```
[2024-11-22T10:28:56.481Z] 05:28:56 - MainThread - ocs_ci.utility.utils - [33mWARNING[0m  - Command stderr: Error from server (AlreadyExists): error when creating "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-namespace.yaml": namespaces "openshift-logging" already exists
[2024-11-22T10:28:56.481Z] 
[2024-11-22T10:28:56.736Z] 05:28:56 - MainThread - ocs_ci.framework.pytest_customization.reports - [32mINFO[0m  - duration reported by tests/functional/workloads/ocp/logging/test_openshift-logging.py::Testopenshiftloggingonocs::test_create_new_project_to_verify_logging immediately after test execution: 51.11 …
```
> fix error in test 0.2

- conf/ocsci/dr_workload.yaml
- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/helpers/dr_helpers.py
- ocs_ci/ocs/dr/dr_workload.py
- ocs_ci/ocs/resources/drpc.py
- ocs_ci/ocs/resources/pvc.py
- pytest.ini
- tests/conftest.py
- tests/functional/disaster-recovery/regional-dr/test_cnv_app_failover_and_relocate.py
- tests/functional/disaster-recovery/regional-dr/test_failover.py
- tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate.py
- tests/functional/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py
- tests/functional/disaster-recovery/regional-dr/test_negative_failover_relocate_ui.py
- tests/functional/disaster-recovery/regional-dr/test_node_operations_during_failover_relocate.py
- tests/functional/disaster-recovery/regional-dr/test_rdr_monitoring_dashboard_ui.py
- tests/functional/disaster-recovery/regional-dr/test_relocate.py
- tests/functional/disaster-recovery/regional-dr/test_sequential_failover.py
- tests/functional/disaster-recovery/regional-dr/test_sequential_relocate.py
This PR backports several fixes and enhancements from the master branch to the release-4.16 branch. The changes correspond to the following original PRs from the master branch:
- https://github.com/red-hat-storage/ocs-ci/pull/10194 
- https://github.com/red-hat-storage/ocs-ci/pull/10360
- https://github.com/red-hat-storage/ocs-ci/pull/10230
- https://github.com/red-hat-storage/ocs-ci/pull/10623
- https://github.com/red-hat-storage/ocs-ci/pull/10252
- https://github.com/red-hat-storage/ocs-ci/pull/10406 
- https://github.com/red-hat-storage/ocs-ci/pull/10874
Also update dr_workload.yaml based on recent directory restructure in `red-hat-storage/ocs-workloads`
> [release-4.16] Backport RDR Fixes and Enhancements

- ocs_ci/helpers/cnv_helpers.py
- ocs_ci/ocs/cnv/virtual_machine.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/cnv-vm-workload/clone_dv.yaml
- ocs_ci/templates/cnv-vm-workload/dv_cluster_role.yaml
- ocs_ci/templates/cnv-vm-workload/dv_role_binding.yaml
- ocs_ci/templates/cnv-vm-workload/vm.yaml
- tests/conftest.py
- tests/functional/workloads/cnv/test_vm_cloning_ops.py
> CNV vm pvc/dv/dvt cloning ops

- tests/cross_functional/system_test/test_mcg_replication_with_disruptions.py
> [MCG] Assert when objects are not replicated in MCG replication system test and fix replication sync issue

- ocs_ci/templates/app-pods/fedora_with_linuxtar_files.yaml
> Adds label parameter to session-fedora-pod 

- ocs_ci/ocs/resources/mcg.py
- ocs_ci/ocs/resources/objectbucket.py
> mcg-cli delete for object which doesn't exist

- ocs_ci/ocs/node.py
- ocs_ci/ocs/resources/storage_cluster.py
> stretch cluster add capacity with ssd disks

- ocs_ci/ocs/amq.py
> Fix AMQ setup by cloning the latest compatible branch of strimzi-kafka-operator

- ocs_ci/utility/ibmcloud.py
> fix variable overwrite for storing IBM cloud buckets

- setup.py
> Upgrade paramiko to 3.5.0

- ocs_ci/ocs/ocs_upgrade.py
> Fix upgrade for non managed IBM Cloud platforms

- ocs_ci/utility/kms.py
Adding setter function for vault_path_token to work in tests.
addresses issue: https://github.com/red-hat-storage/ocs-ci/issues/11180
> Adding setter function for vault_path_token

- ocs_ci/utility/kms.py
> Fix vault path token condition

- ocs_ci/ocs/constants.py
- ocs_ci/utility/environment_check.py
> Ignore controller-detect-version pods in leftover check

- ocs_ci/helpers/helpers.py
https://issues.redhat.com/browse/DFBUGS-932
> Add toleration on api-server pod

- tests/conftest.py
Skipping test cases with kubeadmin password for ROKS
> Skipping test cases with kubeadmin password

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/views.py
- ocs_ci/utility/rosa.py
- ocs_ci/utility/users.py
- tests/functional/ui/test_non_admin_user.py
fix the error:
```
[2024-09-20T03:20:18.852Z] self = ValidationUI Web Page, locator = ('page-sidebar', 'id')
[2024-09-20T03:20:18.852Z] attribute = 'innerHTML', safe = False
[2024-09-20T03:20:18.852Z] 
[2024-09-20T03:20:18.852Z]     def get_element_attribute(self, locator, attribute, safe: bool = False):
[2024-09-20T03:20:18.852Z]         """
[2024-09-20T03:20:18.852Z]         Get attribute from WebElement
[2024-09-20T03:20:18.852Z]     
[2024-09-20T03:20:18.852Z]         Args:
[2024-09-20T03:20:18.852Z]             locator (tuple): (GUI element needs to operate on (str), type (By)).
[2024-09-20T03:20:18.852Z]             attribute (str): the value of this attribute will be extracted from WebElement
[2024-09-20T03:20:18.852Z]             safe(bool): if True exception will not raise when …
```
> make test_unprivileged_user_odf_access work on ROSA and ROSA HCP

- ocs_ci/helpers/dr_helpers.py
- ocs_ci/ocs/dr/dr_workload.py
- tests/functional/disaster-recovery/regional-dr/test_disable_dr.py
This test performs disable dr for discovered apps for rbd based workloads.
> disable dr for discovered apps

- ocs_ci/ocs/ocs_upgrade.py
> Fix IBM Cloud upgrade

- .pre-commit-config.yaml
- ocs_ci/deployment/deployment.py
- ocs_ci/helpers/dr_helpers.py
- ocs_ci/utility/retry.py
- scripts/python/checks/validate_retry_usage.py
- tests/cross_functional/system_test/test_graceful_nodes_shutdown.py
- tests/cross_functional/system_test/test_mcg_replication_with_disruptions.py
- tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
- tests/functional/monitoring/conftest.py
- tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
- tests/functional/workloads/app/amq/test_amq_node_reboot_and_shutdown.py
- tests/functional/workloads/app/couchbase/test_couchbase_node_reboot.py
- tests/functional/workloads/ocp/monitoring/test_monitoring_on_negative_scenarios.py
- tests/functional/workloads/ocp/registry/test_registry_reboot_node.py
- tests/functional/workloads/ocp/registry/test_registry_shutdown_and_recovery_node.py
- tox.ini
> Update retry logic with some limits

- tests/functional/object/mcg/test_bucket_replication.py
> Fix memory leak in Get bucket replication test

- ocs_ci/utility/kms.py
> Try to get vault path token in deploy function

- tests/functional/pv/pv_encryption/test_pv_keyrotation.py
Skipping test if KMS configured other that vault
> Skipping test if KMS configured other than vault

- ocs_ci/ocs/ocs_upgrade.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/11297
> Fix config path for upgrade strategy

- tests/functional/z_cluster/nodes/test_node_replacement_proactive.py
fix https://github.com/red-hat-storage/ocs-ci/issues/10776
> Clear crash warnings and osd removal leftovers in the teardown of the node replacement test 

- tests/conftest.py
- tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
Skipping test case with kubeadmin password for IBM Cloud
> Skipping test case with kubeadmin password for IBM Cloud

- ocs_ci/utility/kms.py
Added ttl value to the vault token generation command
> Added ttl value to the vault token generation command

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/storage_cluster.py
Fixed intransit encryption test case
> Fixed intransit encryption test case

- tests/conftest.py
> Stabilize add-env-var MCG fixtures

- ocs_ci/framework/conf/ocp_version/ocp-4.19-config.yaml
> OCP 4.19 RHCOS template

- tests/functional/odf-cli/test_pvc_stale_volume_cleanup_cli.py
This PR is a FIX of issue: https://github.com/red-hat-storage/ocs-ci/issues/11286
> Fixed index error in the code

- tests/functional/encryption/test_encryption_configuration_dashboard.py
This is fix for the issue : https://github.com/red-hat-storage/ocs-ci/issues/11337
> string comparison check reformatted

- ocs_ci/ocs/node.py
fix https://github.com/red-hat-storage/ocs-ci/issues/11182
Fix and rearrange the functions:
- check_taint_on_nodes
- untaint_nodes
> Fix the functions "check_taint_on_nodes" and "untaint_nodes"

- ocs_ci/ocs/exceptions.py
- ocs_ci/ocs/node.py
> fix getting host names from ceph

- ocs_ci/templates/DR/observability-metrics-configmap.yaml
> Remove Unused metric

- ocs_ci/helpers/dr_helpers_ui.py
- ocs_ci/ocs/acm/acm.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/ui/acm_ui.py
- ocs_ci/ocs/ui/views.py
- tests/functional/disaster-recovery/regional-dr/test_warning_and_alerting.py
Covers happy path for [RHSTOR-6144](https://issues.redhat.com/browse/RHSTOR-6144) or [OCSQE-3197](https://issues.redhat.com/browse/OCSQE-3197)
Tested with ODF 4.18.0-112.stable
OCP 4.18.0-0.nightly-2025-01-25-163410 and ACM 2.13.0-DOWNSTREAM-2025-01-05-19-09-28
> [RDR] "Inconsistent data on target cluster" warning alert on Failover/Relocate modal due to Sync delays

- ocs_ci/ocs/cluster_load.py
- tests/conftest.py
> Handle cluster load problems causing stuck execution

- ocs_ci/ocs/cluster_load.py
Cherry-pick of #11327 to release-4.16
> [release-4.16] cluster load: Refresh prometheus_api connection in case of connection error

- tests/conftest.py
> Skip RPM collection for development mode

- tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
Skipping test case with kubeadmin password for IBM Cloud - 4.17
> Skipping test case with kubeadmin password for IBM Cloud - 4.17

- tests/functional/object/mcg/test_obc_quota_update_using_cli.py
Adds script to validate OBC quota update functionality using mcg cli
Customer bug: https://issues.redhat.com/browse/DFBUGS-1173
> Adds script to validate OBC quota update functionality using mcg cli

- ocs_ci/ocs/resources/bucket_notifications_manager.py
- tests/functional/object/mcg/test_bucket_notifications.py
> `test_bucket_notifications` - update the get-bucket-notification command

- ocs_ci/ocs/cluster_load.py
Reverts red-hat-storage/ocs-ci#11327
> Revert "cluster load: Refresh prometheus_api connection in case of connection error"

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/utils.py
- setup.py
cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/10723
> [release-4.15] exclude NOOBAA_PSQL_12_IMAGE for image verification after upgrade

- ocs_ci/ocs/utils.py
> Ignore detect-version pods in rpm version collection

- ocs_ci/utility/aws.py
> Delete OIDC provider during teardown

- tests/functional/monitoring/prometheus/metrics/test_monitoring_negative.py
bug: https://issues.redhat.com/browse/DFBUGS-308
> test_monitoring_shows_mon_down add jira decorator

- ocs_ci/utility/ibmcloud.py
> get buckets and their regions for IBM cloud

- ocs_ci/ocs/constants.py
> adding regions in constants

- ocs_ci/framework/conf/ocp_version/ocp-4.18-ga-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.18-ga-minus1-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.18-ga-upgrade.yaml
> Adding OCP 4.18-ga files

- tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
> Add re-tries on pod toleration check for test_non_ocs_taint_and_tolerations post re-spin

- ocs_ci/deployment/provider_client/storage_client_deployment.py
the check is buggy and is breaking cluster deployment
> Remove unneeded catsource check

- ocs_ci/helpers/keyrotation_helper.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/utils.py
- ocs_ci/utility/kms.py
- tests/functional/encryption/test_encryption_keyrotation.py
Fixed keyrotaion tests for KV2 version.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--
In the KV-2 version, secrets are stored in the /data/data path, whereas in the KV-1 version, they are directly stored in the /data path.
> Fixed keyrotaion tests for KV2 version

- tests/conftest.py
Here I am changing the order of parameters of storage class fixture according to the order of execution
> Changing order of parameters of SC fixture

- ocs_ci/utility/vsphere.py
> graceful shutdown VM's in vSphere

- ocs_ci/ocs/resources/mcg.py
- tests/functional/object/mcg/test_namespace_crd.py
This PR implements a new test case for creation of bucket over Multi NSS and bucket class of Multi type via CLI .
> Adding a new test case for NSS creation with Multi bucketclass type via CLI

- tests/functional/z_cluster/cluster_expansion/test_node_expansion.py
Added in-transit encryption enable-disable operation after adding worker node to the cluster.
> Added in-transit encryption enable-disable operation after adding worker node to the cluster.

- tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
> [ODF 4.15] Add re-tries on pod toleration check for test_non_ocs_taint_and_tolerations post re-spin

- ocs_ci/ocs/resources/objectbucket.py
> Increase bucket creation timeout for test_recovery_from_volume_deletion_cli_tool

- ocs_ci/framework/pytest_customization/marks.py
- tests/functional/ui/test_alert_text.py
- tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
Skipuitest with kubeadmin for IBM Cloud v4.17
> Skipuitest with kubeadmin for IBM Cloud v4.17

- ocs_ci/deployment/deployment.py
- ocs_ci/utility/rosa.py
Issue in failed deployment: https://url.corp.redhat.com/6055907
Function parameter shadows lib reference, hence parameter was renamed version -> version_str
> ROSA HCP Deployment, fix parametrization issue

- ocs_ci/ocs/resources/storage_cluster.py
> storage classes check for provider cluster

- ocs_ci/ocs/resources/bucket_notifications_manager.py
> Stabilize enable_bucket_notifs_on_cr

- tests/cross_functional/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
Removes missed redundant tests from orange squad
> Removes missed redundant tests from orange squad

- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/utility/version.py
- setup.py
> Defaulting ocs-ci to ODF 4.19

- ocs_ci/helpers/stretchcluster_helper.py
- ocs_ci/ocs/cnv/virtual_machine.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/resources/pv.py
- ocs_ci/ocs/resources/stretchcluster.py
- tests/conftest.py
- tests/functional/disaster-recovery/sc_arbiter/test_device_replacement.py
- tests/functional/disaster-recovery/sc_arbiter/test_mon_osd_failures.py
- tests/functional/disaster-recovery/sc_arbiter/test_netsplit.py
- tests/functional/disaster-recovery/sc_arbiter/test_rgw_in_stretch.py
- tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
This PR includes stretch cluster stable code which is necessary for successful execution of tests in z stream ci runs.
> [4.17] Backport stretch cluster stable code to 4.17 release branch

- tests/functional/upgrade/test_upgrade_ocp.py
> use semantic version instead of parse_version

- ocs_ci/deployment/provider_client/storage_client_deployment.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/ocs-deployment/provider-mode/ocs_storagecluster_converged.yaml
repeat of original request
cc @dahorak
> DisableStorageClass and DisableSnapshotClass fields are deprecated

- tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
> limit retry logic under threshold ( 4 hours ) for test_reboot_on_tainted_node

- ocs_ci/ocs/ocs_upgrade.py
> move cnpg pod addition to after initialization of MCG Only block

- ocs_ci/ocs/utils.py
> skip collecting ceph external when OCP deployment failed

- tests/functional/z_cluster/nodes/test_nodes_maintenance.py
> test_node_maintenance_on_ROSA_HCP. fix extended mon termination issue

- ocs_ci/framework/conf/default_config.yaml
update rosa cli version to latest for 419
source: https://console.redhat.com/openshift/downloads#tool-rosa
> update rosa cli version to latest for 419

- ocs_ci/ocs/resources/storageconsumer.py
- ocs_ci/ocs/version.py
following https://github.com/red-hat-storage/ocs-operator/pull/3062 with this PR we enhance StorageConsumer cr and python class
> Enhance StorageConsumer cr and class

- tests/functional/ui/test_odf_storage_consumption_trend.py
> skip-ibm-cloud-ui-tests-consumption-trend-master

- ocs_ci/deployment/deployment.py
> use bluestore_slow_ops_warn only from ODF 4.19 version

- conf/ocsci/submariner_downstream.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.18-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.18-ga-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.18-ga-minus1-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.19-config.yaml
Bumps ACM and Submariner version for OCP 4.18 and later
> Bumps ACM and Submariner version for OCP 4.18 and later

- ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
This reverts commit 60d31c4a68407dcb4a9ecceb5dc90e606d483c0a.
> Revert "Add W/A for IBM Cloud IPI Deployment blocker OCPBUGS-53258"

- ocs_ci/utility/vsphere.py
> stop VM's only when powered on

- ocs_ci/helpers/dr_helpers_ui.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/helpers_ui.py
- ocs_ci/ocs/ui/views.py
- ocs_ci/utility/utils.py
- tests/functional/disaster-recovery/regional-dr/test_rdr_monitoring_dashboard_ui.py
- tests/functional/disaster-recovery/regional-dr/test_warning_and_alerting.py
- tests/functional/ui/test_pv_encryption_ui.py
- tests/functional/ui/test_pvc_ui.py
> Fix 4.19 locators and update logic to use previous locators if new are not defined

- tests/functional/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
fix https://github.com/red-hat-storage/ocs-ci/issues/11298
> Modified timeouts and number of retry attempts

- ocs_ci/utility/utils.py
fixes: https://github.com/red-hat-storage/ocs-ci/issues/11819
> fix issue with missing installer_path key in ENV_DATA

- ocs_ci/ocs/ui/pvc_ui.py
Should fix failures like https://reportportal-ocs4.apps.dno.ocp-hub.prod.psi.redhat.com/ui/#OCS/launches/632/30582/1507309/1507576/log
> Update condition to 4.15 version

- ocs_ci/ocs/ocs_upgrade.py
> set bluetsore threshold and lifetime values after upgrade

- ocs_ci/deployment/deployment.py
> use stdout instead of CompletedProcess in ResourceWrongStatusException

- ocs_ci/ocs/ocs_upgrade.py
> chnage csi cephfs and rbd plugin labels for upgrade

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/storageconsumer.py
- ocs_ci/templates/ocs-deployment/provider-mode/storage_consumer.yaml
Storage consumer helper class updated in comply with https://github.com/red-hat-storage/ocs-operator/pull/3062
> updated storage_consumer due merged product changes

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/ocsconfigmaps.py
- ocs_ci/templates/ocs-deployment/multicluster/ocs_operator_cm.yaml
- ocs_ci/templates/ocs-deployment/multicluster/storage_consumer_cm.yaml
new functionality for storage hub clusters, following changes from dev PR https://github.com/red-hat-storage/ocs-operator/pull/3115
> ocs configmaps module added, replaced storageRequest

- ocs_ci/deployment/mce.py
Fixes: #[11834](https://github.com/red-hat-storage/ocs-ci/issues/11834)
> fix syntax issue with mce install and override

- tests/functional/upgrade/test_configuration.py
Test to verify zero value i.e zero and zero percent value for csi_rbd_plugin_update_strategy_max_unavailable and csi_cephfs_plugin_update_strategy_max_unavailable   in update strategy configuration
> Test to verify zero value of max_unavaialable in update strategy configuration

- tests/functional/object/mcg/test_kms.py
Fixes: #11489
This change drops the `--previous` backup strategy in favor of a new one - I've noticed that the desired logs are written relatively soon after the noobaa-operator is restarted. Hence, the new backup strategy is to reset the pod and to wait up to five minutes for the logs to show.
> Stabilize test_noobaa_kms_validation

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/helpers/odf_deployment_helpers.py
- ocs_ci/ocs/resources/storage_cluster.py
Currently this PR is for testing custom image
> remove creation of storagesystem

- ocs_ci/deployment/deployment.py
- ocs_ci/deployment/hosted_cluster.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/storage_cluster.py
following dev change https://github.com/red-hat-storage/ocs-operator/pull/3096 added check on network preferences
> Check odf prerequisites on client connect host network

- ocs_ci/ocs/resources/storage_cluster.py
This completes the Test case with title:
[ODF] CSI Driver is owned by client operator not by Rook after convergence in both internal and external mode
> Add check on csi drivers

- ocs_ci/utility/utils.py
> [DNM]: Add 1 mgr modules have recently crashed to ceph health fixes pattern

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
* Add feature request template
* Remove blank issue option
> Issue templates - add feature request template + remove blank issue option

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/utils.py
> donot check mirroring.enabled on recovery cluster

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/utils.py
Description:
update fetching postgresql image from  ["spec"]["dbImage"] to ["spec"]["dbSpec"]["image"]
> update fetching postgresql image

- ocs_ci/framework/pytest_customization/marks.py
- tests/functional/object/mcg/test_bucket_deletion.py
- tests/functional/object/mcg/test_multicloud.py
- tests/functional/object/mcg/test_namespace_crd.py
- tests/functional/object/mcg/test_object_integrity.py
- tests/functional/object/mcg/test_write_to_bucket.py
> Skips deployment of IBM BS on fips enabled cluster

- ocs_ci/ocs/resources/storage_cluster.py
- tests/functional/object/mcg/test_bucket_policy.py
This PR covers the scenarios mentioned in the BZ 2302507:
- Test upgrade Noobaa with some bucket policy in place
> Automate BZ 2302507: Test upgrade Noobaa with some bucket policy in place

- ocs_ci/utility/ibmcloud.py
> use paginator to get objects in IBM cloud

- ocs_ci/framework/conf/ocs_version/ocs-4.19.yaml
- ocs_ci/utility/ocs_build.py
- ocs_ci/utility/utils.py
> support to fetch latest-stable-upgrade version from ocs-build

- ocs_ci/helpers/keyrotation_helper.py
- ocs_ci/utility/kms.py
- tests/functional/encryption/test_encryption_keyrotation.py
Polarian : https://polarion.engineering.redhat.com/polarion/#/project/OpenShiftContainerStorage/workitem?id=OCS-5963
> Adding test for test/OCS-5963

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/backingstore.py
- ocs_ci/templates/nfs/cluster-role-binding.yaml
- ocs_ci/templates/nfs/cluster-role.yaml
- ocs_ci/templates/nfs/deployment.yaml
- ocs_ci/templates/nfs/nfs_sa.yaml
- ocs_ci/templates/nfs/role-binding.yaml
- ocs_ci/templates/nfs/role.yaml
- ocs_ci/templates/nfs/storageclass.yaml
- tests/conftest.py
- tests/functional/object/mcg/test_pv_pool.py
This covers: https://issues.redhat.com/browse/DFBUGS-1114
Goal is to test pv-pool backingstore with NFS storageclass that doesnt support xattr
> Automate DFBUGS-1114: Test pv-pool with NFS storageclass

- ocs_ci/ocs/ui/pvc_ui.py
- ocs_ci/ocs/ui/views.py
Fixes PVC UI tests, tests.cross_functional.ui.test_validation_ui and project locator failures across multiple tests
> Update project locator for 4.19

- ocs_ci/ocs/resources/pod.py
> correct delete_deployment_pods

- ocs_ci/ocs/ocs_upgrade.py
> Chnage default noobaa pods for upgrade

- ocs_ci/utility/utils.py
> Fixing in getting version for latest-konflux-4.19

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/utils.py
> skip validating rbd mirror pods on recovery cluster

- conf/upgrade/cephfs_update_strategy_20p.yaml
Add configurations to update strategy for cephfs-csi plugin with default recommended value
> Add configurations to update strategy for cephfs-csi plugin with default

- conf/upgrade/rbd_update_strategy_20p.yaml
Add configurations for update strategy for rbd csi plugin with default recommended value
> Add configurations for update strategy for rbd csi plugin

- ocs_ci/ocs/resources/pod.py
> discard storegeclient status reporter in running pod list

- ocs_ci/ocs/ocs_upgrade.py
> make noobaa-default-backing-store as count for upgrade

- ocs_ci/deployment/aws.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/utility/aws.py
Cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/11913
> [release-4.17] AWS STS cloudfront origin identity teardown

- ocs_ci/deployment/aws.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/utility/aws.py
Cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/11913
> [release-4.16] AWS STS cloudfront origin identity teardown

- ocs_ci/deployment/aws.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/utility/aws.py
Cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/11913
> [release-4.15] AWS STS cloudfront origin identity teardown

- ocs_ci/utility/utils.py
> kubeconfig not supported for oc mirror command

- ocs_ci/deployment/netsplit.py
- tests/functional/disaster-recovery/sc_arbiter/test_netsplit.py
> use kubeconfig for netsplit

- ocs_ci/deployment/hosted_cluster.py
- ocs_ci/ocs/resources/storageconsumer.py
- ocs_ci/templates/ocs-deployment/provider-mode/storage_consumer.yaml
This PR covers changes provided with Epic https://issues.redhat.com/browse/RHSTOR-6664
StorageConsumer should be created before the StorageClient and there are changes in onboarding procedure.
> new onboarding procedure for client

- ocs_ci/deployment/hosted_cluster.py
This is not independent change.
Tested in python console.
```
import ocs_ci.framework
config = ocs_ci.framework.config
config.ENV_DATA["cluster_path"] = "/Users/danielosypenko/Work/automation_4/ocs-ci/cluster_path"
config.RUN["kubeconfig"] = "/Users/danielosypenko/Work/automation_4/ocs-ci/cluster_path/auth/kubeconfig"
from ocs_ci.ocs.resources.storageconsumer import *
config.RUN["resource_checker"] = False
from ocs_ci.deployment.hosted_cluster import (
HypershiftHostedOCP,
HostedODF,
HostedClients,
)
config.ENV_DATA["platform"] = "hci_baremetal"
from ocs_ci.deployment.hosted_cluster import HostedODF
h = HostedODF("cl-418-x")
h.cluster_kubeconfig = "/Users/danielosypenko/clusters/cl-418-x/openshift-cluster-dir/auth/kubeconfig"
h.wait_console_plugin_pod_running()
True …
```
> enable console plugin on clients via patch

- ocs_ci/ocs/ocp.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/resiliency/network_faults.py
- ocs_ci/resiliency/node_stats.py
- ocs_ci/resiliency/platform_failures.py
- ocs_ci/resiliency/platform_stress.py
- ocs_ci/resiliency/resiliency_helper.py
- ocs_ci/utility/utils.py
- tests/resiliency/conftest.py
- tests/resiliency/test_platfrom_failures_scenarios.py
This PR introduces the resiliency scenario automation under platform stress . following stress conditions are induce to node-level using stress-ng tool.
Stress types:
- CPU stress: stress-ng --cpu 4 --cpu-load 70 --timeout 60s
- Memory stress: stress-ng --vm 4 --vm-bytes 70% --timeout 60s
- IO stress: stress-ng --hdd 4 --hdd-bytes 2G --timeout 60s
- Network stress: stress-ng --sock 4 --timeout 60s
- All combined stress: stress-ng --cpu 1 --vm 1 --io 1 --sock 1 --timeout 60s
> Resiliency test automation when platform under stress

- tests/functional/z_cluster/nodes/test_az_failure.py
Rename deprecated tests brown squad
> Rename deprecated tests

- ocs_ci/deployment/vmware.py
> increase CSR timeout for arbiter deployment

- ocs_ci/ocs/acm/acm.py
- ocs_ci/ocs/ui/views.py
> Fix locators for RDR deployment on OCP 4.19

- ocs_ci/ocs/utils.py
> retry for fetching pgsql version after upgrade

- tests/conftest.py
> Adds code for copying CA cert inside pod for scale_cli_pod

- ocs_ci/deployment/disconnected.py
> mirror images using ocs version instead of ocp version

- ocs_ci/deployment/hosted_cluster.py
- ocs_ci/ocs/resources/storageconsumer.py
- ocs_ci/templates/ocs-deployment/provider-mode/storage_consumer.yaml
This is a cherry-puck from #11926
This PR went through review and being only picked from master-converged-mode branch to master
> New client onboarding procedure to master

- ocs_ci/ocs/ocp.py
> retry for oc debug

- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/constants.py
- tests/functional/z_cluster/test_ceph_default_values_check.py
fix https://github.com/red-hat-storage/ocs-ci/issues/12005
fix https://github.com/red-hat-storage/ocs-ci/issues/9418
> Run the test on Provider cluster and change the mds value to '1073741824' when we use lower requirements

- ocs_ci/deployment/vmware.py
> CSR timeout for multus deployment with stretch

- ocs_ci/ocs/node.py
- tests/functional/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
> Fix test_automated_recovery_from_stopped_node_and_start[True] on clusters with 6W

- ocs_ci/deployment/helpers/odf_deployment_helpers.py
- ocs_ci/ocs/cluster.py
- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/ocs/utils.py
> use 4.19 version instead of z version

- tests/functional/odf-cli/test_debug_verbocity_of_ceph_component.py
fixes [issue](https://github.com/red-hat-storage/ocs-ci/issues/11347)
> Skipif added to test test_debug_verbosity_of_ceph_components

- ocs_ci/ocs/resources/storage_cluster.py
- ocs_ci/utility/utils.py
> Fix slow ops issue in rdr deployment

- ocs_ci/ocs/ocs_upgrade.py
> increase timeout for checking noobaa pods after upgrade

- ocs_ci/utility/utils.py
cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/11894
> [release-4.18] recover module crash

- ocs_ci/utility/framework/initialization.py
This is a (partial) backport of https://github.com/red-hat-storage/ocs-ci/pull/12083.
> Make sure run id is unique - backport to release 4.17

- ocs_ci/ocs/ocs_upgrade.py
- ocs_ci/ocs/resources/storage_cluster.py
DFBUG: https://issues.redhat.com/browse/DFBUGS-2279
> nodeplugin pods on compute nodes only

- tests/conftest.py
Followed Steps mentioned in below PR-
https://github.com/red-hat-storage/ocs-operator/pull/3196#issuecomment-2838980820
> Remove cephblockpoolradosnamespaces before cephblockpool

- tests/functional/upgrade/test_configuration.py
> Fix test test_max_unavaialable_rbd for issue 11908

- tests/functional/object/mcg/test_cors_config_elements.py
Adds more test coverage for CORS feature
> Adds more test coverage for CORS feature

- ocs_ci/ocs/resources/pod.py
- tests/functional/z_cluster/nodes/test_toleration.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/12036
> skip check for storageclient pod

- ocs_ci/deployment/ibm.py
- ocs_ci/utility/utils.py
> remove oc in exec_oc_cmd

- tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
fix https://github.com/red-hat-storage/ocs-ci/issues/11172
> Pause the IO in Background for the resize osd test

- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/pod.py
The tests in this file started failing due to the new noobaa-db HA solution, and this PR just makes the necessary updates.
> Fix test_noobaa_db_cleartext_postgres_password.py

- ocs_ci/helpers/osd_resize.py
- ocs_ci/ocs/cluster.py
[https://github.com/red-hat-storage/ocs-ci/issues/12109](https://github.com/red-hat-storage/ocs-ci/issues/12109)
> Fix calcualtion of check_storage_size_is_reflected_in_ui

- tests/functional/object/rgw/test_rgw_read_affinity.py
Adds upgrade scenarios for readAffinity feature
> Adds upgrade scenarios for readAffinity feature

- ocs_ci/deployment/helpers/storage_class.py
> Storageclass map for baremetal and HCI baremetal

- ocs_ci/ocs/bucket_utils.py
- ocs_ci/ocs/resources/mcg.py
- ocs_ci/ocs/ui/page_objects/buckets_tab.py
- ocs_ci/utility/utils.py
- tests/functional/object/mcg/ui/test_mcg_ui.py
fix https://github.com/red-hat-storage/ocs-ci/issues/11635
> performance improvement in function: generate_folder_with_files

- ocs_ci/helpers/cnv_helpers.py
- tests/conftest.py
- tests/functional/workloads/cnv/test_vm_lifecycle_and_io.py
> Added code for continuous io on VM

- tests/conftest.py
Manual cherry-pick of pr #11990
> [release-4.16] Delete thanos bucket created for ACM observability during cluster teardown

- ocs_ci/deployment/helpers/storage_class.py
Fixes deployment with IBM Power
Signed-off-by: Shilpi Das: shdas@redhat.com
> Storage class map update for IBM Power Deployment

- ocs_ci/deployment/helpers/lso_helpers.py
- ocs_ci/templates/ocs-deployment/local-storage-optional-operators.yaml
This pr is about, updating the optional-operator catalogsource with different versioons. Earlier it had fixed value.
> Updated local storage template to accept different version

- tests/functional/object/mcg/test_object_versioning.py
- Update the test to make the noobaa-db queries against the new cnpg pods
- Track the used threads and wait for them to finish to fix a teardown issue where objects were still being written to the bucket at the same time we were trying to delete it
- Some spelling and documentation improvements
> Fix `test_versioning_parallel_ops` 

- ocs_ci/ocs/resources/storage_cluster.py
> Fix MCG only deplyment KeyError `status`

- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/utils.py
This reverts commit e9d56cd4d56c89f3a7b154c2b995a5c4c562e76f.
> Revert "fix get_ceph_tools_pod to run with provider context (#11839)"

- ocs_ci/ocs/ocs_upgrade.py
- tests/functional/upgrade/test_upgrade_ocp.py
> increase ocp upgrade timeout for arbiter

- ocs_ci/ocs/resources/mcg.py
- tests/functional/monitoring/prometheus/metrics/test_mcg_hpa.py
- tests/functional/pv/pv_services/test_change_reclaim_policy_of_pv.py
- tests/functional/upgrade/test_configuration.py
cherry-pick of https://github.com/red-hat-storage/ocs-ci/pull/11571
> [release-4.18]  Fix several tier1 tests for provider mode

- ocs_ci/deployment/vmware.py
> continue to destroy cluster incase of failed in fetching vms

- conf/deployment/vsphere/upi_1az_rhcos_multus_public_vsan_3m_3w.yaml
upi_1az_rhcos_multus_public_vsan_3m_3w.yaml
> Fix multus configuration

- tests/functional/pod_and_daemons/test_ephemeral_pod.py
WA should be removed with merge of https://github.com/red-hat-storage/ocs-ci/pull/12041
> Added new fixture as workaround[test_ephemeral_pod_creation]

- ocs_ci/utility/ibmcloud.py
> delete IBM cos objects in batches

- ocs_ci/helpers/cnv_helpers.py
- tests/conftest.py
- tests/functional/workloads/cnv/test_vm_snapshot_cloning_ops.py
This PR will validate PVC expansion operation before cloning the VM and After cloning the VM.
> CNV vm clone with PVC expansion ops

- ocs_ci/deployment/hosted_cluster.py
- ocs_ci/templates/hosted-cluster/rbac-wa.yaml
w/a for https://issues.redhat.com/browse/OCPBUGS-56015
> rbac added. workaround for mce-2.8.2

- ocs_ci/ocs/acm/acm.py
- ocs_ci/ocs/ui/acm_ui.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/views.py
> [release-4.18] Stabilize RDR deployment by using OCP to ACM navigation fix

- ocs_ci/ocs/constants.py
> Fixes AWS CLI region issue

- ocs_ci/helpers/helpers.py
- ocs_ci/helpers/storage_auto_scaler.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/storage-auto-scaling/storage-autoscaler.yaml
- tests/functional/z_cluster/cluster_expansion/test_storage_auto_scaling.py
See more details in the Jira issue: https://issues.redhat.com/browse/RHSTOR-1943.
Test the auto-scaling functionality using the CLI.
This test includes the following steps:
- Creating the CR
- Triggering threshold by filling the cluster
- Verifying SmartScaling behavior post-threshold
> Create a new test for the storage auto scaling

- ocs_ci/deployment/fusion.py
- ocs_ci/deployment/fusion_data_foundation.py
- ocs_ci/ocs/constants.py
- ocs_ci/templates/fusion-data-foundation/odfcluster.yaml
- ocs_ci/utility/framework/fusion_fdf_init.py
This change includes refactoring the storage cluster creation and a couple other actions taken during deployment to support the creation of the storagecluster.
Issue: https://url.corp.redhat.com/1327000
> FDF storage configuration after deployment

- ocs_ci/ocs/resources/mcg.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/12367
> Fix endpoint reference

- ocs_ci/ocs/utils.py
As there are multiple threads trying to download the binary we need a locking mechanism
Fixes #12381
> Introduce lock for downloaing subctl binary

- ocs_ci/framework/conf/ocp_version/ocp-4.20-config.yaml
- ocs_ci/framework/conf/ocp_version/ocp-4.20-upgrade.yaml
> Add OCP 4.20 config files

- ocs_ci/ocs/utils.py
> increase timeout for checking toolbox

- ocs_ci/ocs/dr/dr_workload.py
- tests/conftest.py
> Fix AttributeError in RDR Discovered apps tests

- ocs_ci/ocs/replica_one.py
- tests/functional/storageclass/test_replica1.py
This fix one of few issues in Replica1 test
> Fix issue with node labels[Replica-1]

- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/utils.py
cephtoolbox pod was running in provider due to missing context, this commit add the context to run with provider mode context when available.
> fix get_ceph_tools_pod to run with provider context

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/ui/base_ui.py
- ocs_ci/ocs/ui/views.py
> Fix UI deployment for 4.19

- ocs_ci/templates/acm-deployment/submariner_downstream_brew_idms.yaml
Related to: https://github.com/red-hat-storage/ocs-ci/pull/11336
> fix ACM Deployment IDMS yaml - apiVersion

- ocs_ci/ocs/benchmark_operator_fio.py
- tests/cross_functional/system_test/test_cluster_full_and_recovery.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/12257
> fix run_fio_benchmark_operator 

- ocs_ci/ocs/bucket_utils.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/cloud_manager.py
- ocs_ci/ocs/resources/mcg.py
- tests/conftest.py
- tests/functional/object/mcg/flowtest/test_mcg_namespace_disruptions_crd.py
- tests/functional/object/mcg/flowtest/test_mcg_namespace_disruptions_rpc.py
- tests/functional/object/mcg/lifecycle/test_mcg_namespace_lifecyle_crd.py
- tests/functional/object/mcg/lifecycle/test_mcg_namespace_lifecyle_rpc.py
- tests/functional/object/mcg/lifecycle/test_mcg_namespace_s3_ops_crd.py
- tests/functional/object/mcg/lifecycle/test_mcg_namespace_s3_ops_rpc.py
- tests/functional/object/mcg/test_namespace_crd.py
- tests/functional/object/mcg/test_namespace_rpc.py
> change MCG_NS_AWS_ENDPOINT to include region

- ocs_ci/ocs/ocs_upgrade.py
> increase retry for fetching noobaa pods during upgrade

- ocs_ci/ocs/resources/bucket_notifications_manager.py
Fixes typo while applying notification to bucket
The is addon PR for issue #12388
> Fixes typo while applying notification to bucket

- conf/README.md
- conf/ocsci/cephClusterDebugRgw.yaml
- ocs_ci/deployment/deployment.py
For bug: [DFBUGS-2413](https://issues.redhat.com//browse/DFBUGS-2413)
> Debug RGW ceph override

- ocs_ci/deployment/cnv.py
Fix problem:
```
2025-06-21 13:46:47  06:46:47 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n kubevirt-hyperconverged get Subscription.operators.coreos.com -n kubevirt-hyperconverged -o yaml
2025-06-21 13:46:48  06:46:47 - MainThread - ocs_ci.utility.utils - INFO  - Going to sleep for 10 seconds before next iteration
2025-06-21 13:47:00  06:46:58 - MainThread - ocs_ci.framework.pytest_customization.reports - INFO  - duration reported by tests/functional/deployment/test_deployment.py::test_deployment immediately after test execution: 312.13
2025-06-21 13:47:00  ERROR
2025-06-21 13:47:00  ______________________ ERROR at setup of test_deployment _______________________
2025-06-21 …
```
> fix ns for multi-client deployment

- tests/functional/object/mcg/test_cors_config_elements.py
> Fixes CORS script for ipV6 deployment

- ocs_ci/ocs/ocs_upgrade.py
> [release-4.18] update condition for slowops for upgrade

- ocs_ci/ocs/machine.py
- ocs_ci/ocs/node.py
fix https://github.com/red-hat-storage/ocs-ci/issues/12361
> Wait more time for verifying the node names in the Ceph OSD status

- ocs_ci/ocs/metrics.py
As clarified in https://issues.redhat.com/browse/DFBUGS-2931
> Fix ceph_rocksdb_* metric names

- tests/functional/object/rgw/test_rgw_read_affinity.py
> Fixes method name mismatch issue while calling it

- ocs_ci/ocs/amq.py
- tests/functional/workloads/app/amq/test_amq_node_reboot_and_shutdown.py
> Retry AMQ cleanup if failed due to temporay issue

- tests/functional/workloads/app/couchbase/test_couchbase.py
- tests/functional/workloads/app/jenkins/test_jenkins.py
- tests/functional/workloads/app/pgsql/test_pgsql.py
> Stop exporting workload data to google spreadhseet

- ocs_ci/framework/conf/ocs_version/ocs-4.20.yaml
> update must gather image for 4.20

- ocs_ci/deployment/helpers/storage_class.py
- ocs_ci/deployment/vmware.py
> get storageclass for vSphere cluster

- ocs_ci/ocs/constants.py
- tests/functional/z_cluster/test_ceph_default_values_check.py
> Added 4.19 values- test_validate_ceph_config_values_in_rook_config_override

- ocs_ci/helpers/dr_helpers.py
> initialize vrg_list

- tests/functional/z_cluster/test_ceph_default_values_check.py
> changed version check to live check

- ocs_ci/ocs/bucket_utils.py
> Fixes rgw object download method

- ocs_ci/deployment/deployment.py
> remove storagesystem creation in multistoragecluster

- tests/functional/upgrade/test_upgrade_ocp.py
> OCP upgrade timeout

- docs/usecases/fusion_and_fdf.md
- ocs_ci/deployment/fusion.py
- ocs_ci/framework/conf/fusion_version/fusion-2.10-ga.yaml
- ocs_ci/framework/conf/fusion_version/fusion-2.8-ga.yaml
- ocs_ci/framework/conf/fusion_version/fusion-2.9-ga.yaml
> support to install previous Fusion GA releases

- ocs_ci/ocs/resources/pod.py
- tests/functional/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
> Improve wait_for_storage_pod

- ocs_ci/deployment/hosted_cluster.py
fix issue seen here: https://url.corp.redhat.com/73ba50a
> increase-timeout-storageClient-create

- ocs_ci/ocs/ocs_upgrade.py
To upgrade from 4.19 to 4.20, bring down ocs-client-operator-controller-manager and delete subscriptions webhook.
https://issues.redhat.com/browse/DFBUGS-3572
> delete subscriptions webhook and bring down ocs-client-operator-controller-manager

- ocs_ci/helpers/vdbench_helpers.py
- ocs_ci/ocs/constants.py
- ocs_ci/resiliency/resiliency_helper.py
- ocs_ci/resiliency/resiliency_workload.py
- ocs_ci/templates/workloads/vdbench/configmap.yaml.j2
- ocs_ci/templates/workloads/vdbench/deployment.yaml.j2
- ocs_ci/templates/workloads/vdbench/vdbench_benchmark.yaml.j2
- ocs_ci/workloads/README.md
- ocs_ci/workloads/vdbench.py
- tests/cross_functional/resilience/conftest.py
- tests/cross_functional/resilience/test_app_scale_on_storage_component_failure.py
This PR introduces comprehensive resiliency testing capabilities with application scaling scenarios and a complete VDBENCH workload implementation for ODF storage testing.
This release introduces a comprehensive framework for resiliency validation and application workload testing using VDBENCH on ODF storage.
- Dynamic scaling under storage failures Validates app scale-up/down behavior while critical storage components are disrupted.
- Failure scenarios covered:
- OSD pod failure
- MON pod failure
- MGR pod failure
- MDS pod failure
- RGW pod failure
- CephFS pod failure
⸻
✅ Core Features:
•	Multi-level I/O testing
•	RBD (block) workloads
•	CephFS (filesystem) workloads
•	Dynamic scaling of workload threads during execution
•	Workload lifecycle control
•	Pause/resume support
•	Graceful …
> Adding Vdbench Workload Automation to ocs-ci

- ocs_ci/deployment/deployment.py
- ocs_ci/ocs/ocs_upgrade.py
> use timeout which is more than mcp timeout in exec_cmd

- ocs_ci/ocs/ocs_upgrade.py
> remove WA of deleting subscriptions webhook

- tests/functional/upgrade/test_configuration.py
Just wait for few seconds before taking information related to update strategy. 
Fixes https://github.com/red-hat-storage/ocs-ci/issues/11479
> Issue#11479 is uncertain issue while execution because slowness in update

- ocs_ci/utility/environment_check.py
> Fixed Leftover exception due to job-pods

- ocs_ci/ocs/constants.py
- ocs_ci/utility/multicluster.py
- tests/conftest.py
- tests/functional/upgrade/test_upgrade.py
- tests/functional/upgrade/test_upgrade_ocp.py
1. Refactor DR upgrade code the base class
2. Introduce relevant RDR markers to the upgrade tests
> Add RDR Upgrade scenario: Refactor the code to accomodate RDR upgrades and introduce relevant markers to the upgrade tests

- ocs_ci/helpers/helpers.py
- tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/12672
and moved teardown part in common function file
> add toleration to drivers

- tests/functional/object/mcg/test_namespace_crd.py
Updating the region of AWS
fixes: https://github.com/red-hat-storage/ocs-ci/issues/12691
> Updating the region of AWS

- tests/functional/object/mcg/test_bucket_replication.py
- tests/functional/object/mcg/test_cached_buckets.py
- tests/functional/object/mcg/test_namespace_crd.py
> use endpoint and region from pytest params

- ocs_ci/framework/conf/default_config.yaml
- setup.py
> Defaulting ocs-ci to ODF 4.20

- ocs_ci/helpers/helpers.py
- ocs_ci/ocs/resources/namespacestore.py
- ocs_ci/ocs/resources/pod.py
- ocs_ci/ocs/resources/storage_client.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/12842
> Don't use config structure as a default for namespace parameter

- ocs_ci/ocs/defaults.py
> increase IBM_CLOUD_LOAD_BALANCER_QUOTA

- ocs_ci/utility/framework/fusion_fdf_init.py
Add cli arg for report path and add reportportal related testsuite properties (#12632)
> [release-4.18] Add report cli arg for fusion and fdf

- ocs_ci/deployment/helpers/mcg_helpers.py
Fixes: #12856
This PR makes two adjustments to the helper function [check_if_mcg_secrets_in_env](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/helpers/mcg_helpers.py) which is used by the test:
1. Fetch the noobaa-db environment variables from the primary CNPG pod instead of the old Statefulset that no longer exists in 4.19.
2. Attempt to fetch the secrets only on the Provider context in Provider-Client deployments since these resources are not available to the Clients.
> Fix test_noobaa_secret_in_env_variable

- ocs_ci/ocs/resources/pod.py
it should fix in test_check_pod_status_after_two_nodes_shutdown_recovery.py
> Added validation for pod STATUS_COMPLETED

- tests/functional/z_cluster/test_storagesystem.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/12891
> Except missing storagesystem CR

- ocs_ci/ocs/resources/storage_cluster.py
> fix_ceph_health to True in install verification

- ocs_ci/utility/kms.py
> fix uniqueidentifier in cs-thales-kmip

- ocs_ci/deployment/ibmcloud.py
> delete IBM resources based in resource id

- tests/functional/pv/pvc_resize/test_pvc_expansion.py
> Increase timeout for PVC factory

- ocs_ci/ocs/bucket_utils.py
> Fix s3_copy_object for when metadata is not provided

- ocs_ci/utility/retry.py
- ocs_ci/utility/utils.py
> Improve hypercovnerged deployment in CNV

- ocs_ci/utility/retry.py
- ocs_ci/utility/utils.py
> Re-try exec_cmd in case of client connetion lost

- ocs_ci/deployment/helpers/hypershift_base.py
Fix the function that get the hosted cluster names.
Fixes #12992
> Fix the function that get the hosted cluster names

- ocs_ci/ocs/md_blow.py
Adds script for md_blow tool which is required for dumping IO directly into noobaa DB
> Adds support of md_blow tool

- ocs_ci/deployment/acm.py
- ocs_ci/ocs/acm/acm.py
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/exceptions.py
- ocs_ci/templates/acm-deployment/clusterset.yaml
- ocs_ci/templates/acm-deployment/submariner_addon.yaml
- ocs_ci/templates/acm-deployment/submariner_broker.yaml
- ocs_ci/templates/acm-deployment/submariner_config.yaml
- ocs_ci/utility/ibmcloud.py
* Add Submariner support over IBM CLOUD IPI
> Add Submariner support over IBM CLOUD IPI (#12146)

- ocs_ci/helpers/helpers.py
Details: https://issues.redhat.com/browse/DFBUGS-3791
> patch the storageclient with storageconsumer uid

- ocs_ci/deployment/deployment.py
- ocs_ci/utility/multicluster.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/13051
> Fix image tag discovery condition

- ocs_ci/helpers/helpers.py
> use odf-cli for live deployments

- tests/functional/workloads/cnv/test_vm_snapshot_cloning_ops.py
This PR will replacing Ayush's 11151 with new code changes.
> [CNV + ODF] Validate Clone of restored VM

- ocs_ci/framework/conf/ocp_version/ocp-4.20-config.yaml
> update RHCOS for ODF 4.20

- ocs_ci/ocs/constants.py
- tests/functional/z_cluster/test_ceph_default_values_check.py
> Adjusted Test ceph_config_values_in_rook_config_override to 4.20

- ocs_ci/framework/pytest_customization/marks.py
- ocs_ci/helpers/e2e_helpers.py
- tests/functional/pod_and_daemons/test_mds_cache_trim_standby.py
Resubmit #10892 with updates, which should cover BZ -2141422
> <GSS Closed Loop BZ: 2141422> Verify mds cache trim in standby-replay mode

- ocs_ci/ocs/registry.py
> increase timeout for registry-cephfs-rwx-pvc

- tests/functional/pv/pv_services/test_overprovision_level_policy_control_with_capacity.py
This is Fix for the Issue: https://github.com/red-hat-storage/ocs-ci/issues/12791
I've successfully analyzed and fixed the `clusterresourcequota` timing issue in the `test_overprovision_level_policy_control_with_capacity test`. Here's what I accomplished:
The issue was a race condition where the test tried to access the clusterresourcequota resource immediately after setting the overprovision policy, but before the StorageCluster controller had time to create the quota resource.
Added a  wait mechanism using:
`TimeoutSampler` with a `120-second` timeout and `5-second `intervals
`verify_quota_resource_exist` helper function to check for resource existence
Proper logging for debugging
> Fix race condition: test accessed clusterresourcequota before StorageCluster created it

- ocs_ci/utility/ibmcloud.py
> Fix restart_nodes_by_stop_and_start_force for IBM Cloud

- ocs_ci/ocs/bucket_utils.py
- tests/functional/object/mcg/test_bucket_replication_and_its_metrics.py
Feature link: https://issues.redhat.com/browse/RHSTOR-7208
QE Link: https://issues.redhat.com/browse/OCSQE-3523
Tests:
OCS-6916
OCS-6917
OCS-6918
> Adding tests for RHSTOR-7208

- ocs_ci/framework/conf/ocs_version/ocs-4.21.yaml
- ocs_ci/utility/framework/initialization.py
> Adding ODF 4.21 config files

- ocs_ci/ocs/ui/views.py
Fixes https://github.com/red-hat-storage/ocs-ci/issues/13270
> Fix UI deployment for 4.20

- tests/conftest.py
- tests/functional/pv/pv_services/test_run_io_multiple_pods.py
Fix `test_run_io_multiple_pods` for multi-client setups
> switch context on deployment_pod_factory factory. Unblock pvc deletion.

- ocs_ci/ocs/ui/views.py
return back dropped locators from commit 4 https://github.com/red-hat-storage/ocs-ci/pull/13208/commits/95d7d76ee459d6e4e41b5b34207d06508287ee65 
some views.py changes were overwritten
> locators-for-dashboard420

- ocs_ci/framework/conf/default_config.yaml
> Remove OCP MG image from default config

- ocs_ci/deployment/vmware.py
> scale down pods and remove pvc before removing cluster for vSphere IPI

- ocs_ci/ocs/ui/page_objects/encryption_module.py
- ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py
- ocs_ci/ocs/ui/page_objects/object_storage.py
- ocs_ci/ocs/ui/page_objects/page_navigator.py
- ocs_ci/ocs/ui/storageclass.py
- ocs_ci/ocs/ui/views.py
- tests/cross_functional/ui/test_validation_ui.py
- tests/functional/encryption/test_encryption_configuration_dashboard.py
- tests/functional/object/mcg/ui/test_mcg_ui.py
- tests/functional/ui/test_error_improvements.py
failed tests: https://jenkins-csb-odf-qe-ocs4.dno.corp.redhat.com/job/qe-deploy-ocs-cluster-prod/17460/consoleFull
Fixes test_new_sc_new_rbd_pool, test_file_block_encryption_configuration_dashboard, test_object_storage_encryption_configuration_dashboard, test_pvc_ui, test_mcg_ui
> Fix a few UI tests failing in 4.20

- ocs_ci/deployment/hosted_cluster.py
- ocs_ci/deployment/mce.py
- ocs_ci/framework/conf/default_config.yaml
- ocs_ci/ocs/constants.py
- ocs_ci/ocs/resources/storage_client.py
storage-client rename for cequence of upgrades (we must have ocs-storagecluster storage client name for upgrade between 4.18 and 4.19)
and
1 - symbol change (added space in oc cmd) for MCE installation
> 418 provider deployment adjustments

- ocs_ci/ocs/acm_upgrade.py
> 4.19 Upgrade acm version 1-line fix
